// behavior: computed-assignment-delays-topropertykey
// expected: pass
// goal: script
// size: large
// variant: script.sloppy

var assignKeyScore = 0;
function assignKeyCheck(condition, label) {
if (!condition) {
throw label;
}
assignKeyScore = assignKeyScore + 1;
return true;
}
var assignLog = [];
function assignMark(value) { assignLog[assignLog.length] = value; return value; }
var assignTotal = 0;
var assignObj0 = { p: 10, late: 0, alt: 0 };
var assignStart0 = assignLog.length;
var assignKeyObj0 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj0[assignMark(2) && assignKeyObj0] = assignMark(4);
assignKeyCheck(assignLog[assignStart0] === 1 && assignLog[assignStart0 + 1] === 2 && assignLog[assignStart0 + 2] === 4 && assignLog[assignStart0 + 3] === 3, "delayed coercion order 0");
assignKeyCheck(assignObj0.p === 4, "delayed coercion value 0");
var assignSeen0 = 0;
var assignRhs0 = 0;
var assignLateKey0 = { name: "late", toString: function() { assignSeen0 = assignRhs0 + 10; return this.name; } };
assignObj0[assignLateKey0] = (assignRhs0 = 4);
assignKeyCheck(assignSeen0 === 14, "rhs before coercion 0");
assignKeyCheck(assignObj0.late === 4, "late assignment value 0");
var assignValueKey0 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj0[assignValueKey0] = 70;
assignKeyCheck(assignObj0.alt === 70, "valueOf assignment key 0");
assignTotal = assignTotal + assignObj0.p + assignObj0.late + assignObj0.alt + assignSeen0;
var assignObj1 = { p: 11, late: 0, alt: 0 };
var assignStart1 = assignLog.length;
var assignKeyObj1 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj1[assignMark(2) && assignKeyObj1] = assignMark(4);
assignKeyCheck(assignLog[assignStart1] === 1 && assignLog[assignStart1 + 1] === 2 && assignLog[assignStart1 + 2] === 4 && assignLog[assignStart1 + 3] === 3, "delayed coercion order 1");
assignKeyCheck(assignObj1.p === 4, "delayed coercion value 1");
var assignSeen1 = 0;
var assignRhs1 = 0;
var assignLateKey1 = { name: "late", toString: function() { assignSeen1 = assignRhs1 + 11; return this.name; } };
assignObj1[assignLateKey1] = (assignRhs1 = 5);
assignKeyCheck(assignSeen1 === 16, "rhs before coercion 1");
assignKeyCheck(assignObj1.late === 5, "late assignment value 1");
var assignValueKey1 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj1[assignValueKey1] = 71;
assignKeyCheck(assignObj1.alt === 71, "valueOf assignment key 1");
assignTotal = assignTotal + assignObj1.p + assignObj1.late + assignObj1.alt + assignSeen1;
var assignObj2 = { p: 12, late: 0, alt: 0 };
var assignStart2 = assignLog.length;
var assignKeyObj2 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj2[assignMark(2) && assignKeyObj2] = assignMark(4);
assignKeyCheck(assignLog[assignStart2] === 1 && assignLog[assignStart2 + 1] === 2 && assignLog[assignStart2 + 2] === 4 && assignLog[assignStart2 + 3] === 3, "delayed coercion order 2");
assignKeyCheck(assignObj2.p === 4, "delayed coercion value 2");
var assignSeen2 = 0;
var assignRhs2 = 0;
var assignLateKey2 = { name: "late", toString: function() { assignSeen2 = assignRhs2 + 12; return this.name; } };
assignObj2[assignLateKey2] = (assignRhs2 = 6);
assignKeyCheck(assignSeen2 === 18, "rhs before coercion 2");
assignKeyCheck(assignObj2.late === 6, "late assignment value 2");
var assignValueKey2 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj2[assignValueKey2] = 72;
assignKeyCheck(assignObj2.alt === 72, "valueOf assignment key 2");
assignTotal = assignTotal + assignObj2.p + assignObj2.late + assignObj2.alt + assignSeen2;
var assignObj3 = { p: 13, late: 0, alt: 0 };
var assignStart3 = assignLog.length;
var assignKeyObj3 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj3[assignMark(2) && assignKeyObj3] = assignMark(4);
assignKeyCheck(assignLog[assignStart3] === 1 && assignLog[assignStart3 + 1] === 2 && assignLog[assignStart3 + 2] === 4 && assignLog[assignStart3 + 3] === 3, "delayed coercion order 3");
assignKeyCheck(assignObj3.p === 4, "delayed coercion value 3");
var assignSeen3 = 0;
var assignRhs3 = 0;
var assignLateKey3 = { name: "late", toString: function() { assignSeen3 = assignRhs3 + 13; return this.name; } };
assignObj3[assignLateKey3] = (assignRhs3 = 7);
assignKeyCheck(assignSeen3 === 20, "rhs before coercion 3");
assignKeyCheck(assignObj3.late === 7, "late assignment value 3");
var assignValueKey3 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj3[assignValueKey3] = 73;
assignKeyCheck(assignObj3.alt === 73, "valueOf assignment key 3");
assignTotal = assignTotal + assignObj3.p + assignObj3.late + assignObj3.alt + assignSeen3;
var assignObj4 = { p: 14, late: 0, alt: 0 };
var assignStart4 = assignLog.length;
var assignKeyObj4 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj4[assignMark(2) && assignKeyObj4] = assignMark(4);
assignKeyCheck(assignLog[assignStart4] === 1 && assignLog[assignStart4 + 1] === 2 && assignLog[assignStart4 + 2] === 4 && assignLog[assignStart4 + 3] === 3, "delayed coercion order 4");
assignKeyCheck(assignObj4.p === 4, "delayed coercion value 4");
var assignSeen4 = 0;
var assignRhs4 = 0;
var assignLateKey4 = { name: "late", toString: function() { assignSeen4 = assignRhs4 + 14; return this.name; } };
assignObj4[assignLateKey4] = (assignRhs4 = 8);
assignKeyCheck(assignSeen4 === 22, "rhs before coercion 4");
assignKeyCheck(assignObj4.late === 8, "late assignment value 4");
var assignValueKey4 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj4[assignValueKey4] = 74;
assignKeyCheck(assignObj4.alt === 74, "valueOf assignment key 4");
assignTotal = assignTotal + assignObj4.p + assignObj4.late + assignObj4.alt + assignSeen4;
var assignObj5 = { p: 15, late: 0, alt: 0 };
var assignStart5 = assignLog.length;
var assignKeyObj5 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj5[assignMark(2) && assignKeyObj5] = assignMark(4);
assignKeyCheck(assignLog[assignStart5] === 1 && assignLog[assignStart5 + 1] === 2 && assignLog[assignStart5 + 2] === 4 && assignLog[assignStart5 + 3] === 3, "delayed coercion order 5");
assignKeyCheck(assignObj5.p === 4, "delayed coercion value 5");
var assignSeen5 = 0;
var assignRhs5 = 0;
var assignLateKey5 = { name: "late", toString: function() { assignSeen5 = assignRhs5 + 15; return this.name; } };
assignObj5[assignLateKey5] = (assignRhs5 = 9);
assignKeyCheck(assignSeen5 === 24, "rhs before coercion 5");
assignKeyCheck(assignObj5.late === 9, "late assignment value 5");
var assignValueKey5 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj5[assignValueKey5] = 75;
assignKeyCheck(assignObj5.alt === 75, "valueOf assignment key 5");
assignTotal = assignTotal + assignObj5.p + assignObj5.late + assignObj5.alt + assignSeen5;
var assignObj6 = { p: 16, late: 0, alt: 0 };
var assignStart6 = assignLog.length;
var assignKeyObj6 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj6[assignMark(2) && assignKeyObj6] = assignMark(4);
assignKeyCheck(assignLog[assignStart6] === 1 && assignLog[assignStart6 + 1] === 2 && assignLog[assignStart6 + 2] === 4 && assignLog[assignStart6 + 3] === 3, "delayed coercion order 6");
assignKeyCheck(assignObj6.p === 4, "delayed coercion value 6");
var assignSeen6 = 0;
var assignRhs6 = 0;
var assignLateKey6 = { name: "late", toString: function() { assignSeen6 = assignRhs6 + 16; return this.name; } };
assignObj6[assignLateKey6] = (assignRhs6 = 10);
assignKeyCheck(assignSeen6 === 26, "rhs before coercion 6");
assignKeyCheck(assignObj6.late === 10, "late assignment value 6");
var assignValueKey6 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj6[assignValueKey6] = 76;
assignKeyCheck(assignObj6.alt === 76, "valueOf assignment key 6");
assignTotal = assignTotal + assignObj6.p + assignObj6.late + assignObj6.alt + assignSeen6;
var assignObj7 = { p: 17, late: 0, alt: 0 };
var assignStart7 = assignLog.length;
var assignKeyObj7 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj7[assignMark(2) && assignKeyObj7] = assignMark(4);
assignKeyCheck(assignLog[assignStart7] === 1 && assignLog[assignStart7 + 1] === 2 && assignLog[assignStart7 + 2] === 4 && assignLog[assignStart7 + 3] === 3, "delayed coercion order 7");
assignKeyCheck(assignObj7.p === 4, "delayed coercion value 7");
var assignSeen7 = 0;
var assignRhs7 = 0;
var assignLateKey7 = { name: "late", toString: function() { assignSeen7 = assignRhs7 + 17; return this.name; } };
assignObj7[assignLateKey7] = (assignRhs7 = 11);
assignKeyCheck(assignSeen7 === 28, "rhs before coercion 7");
assignKeyCheck(assignObj7.late === 11, "late assignment value 7");
var assignValueKey7 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj7[assignValueKey7] = 77;
assignKeyCheck(assignObj7.alt === 77, "valueOf assignment key 7");
assignTotal = assignTotal + assignObj7.p + assignObj7.late + assignObj7.alt + assignSeen7;
var assignObj8 = { p: 18, late: 0, alt: 0 };
var assignStart8 = assignLog.length;
var assignKeyObj8 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj8[assignMark(2) && assignKeyObj8] = assignMark(4);
assignKeyCheck(assignLog[assignStart8] === 1 && assignLog[assignStart8 + 1] === 2 && assignLog[assignStart8 + 2] === 4 && assignLog[assignStart8 + 3] === 3, "delayed coercion order 8");
assignKeyCheck(assignObj8.p === 4, "delayed coercion value 8");
var assignSeen8 = 0;
var assignRhs8 = 0;
var assignLateKey8 = { name: "late", toString: function() { assignSeen8 = assignRhs8 + 18; return this.name; } };
assignObj8[assignLateKey8] = (assignRhs8 = 12);
assignKeyCheck(assignSeen8 === 30, "rhs before coercion 8");
assignKeyCheck(assignObj8.late === 12, "late assignment value 8");
var assignValueKey8 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj8[assignValueKey8] = 78;
assignKeyCheck(assignObj8.alt === 78, "valueOf assignment key 8");
assignTotal = assignTotal + assignObj8.p + assignObj8.late + assignObj8.alt + assignSeen8;
var assignObj9 = { p: 19, late: 0, alt: 0 };
var assignStart9 = assignLog.length;
var assignKeyObj9 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj9[assignMark(2) && assignKeyObj9] = assignMark(4);
assignKeyCheck(assignLog[assignStart9] === 1 && assignLog[assignStart9 + 1] === 2 && assignLog[assignStart9 + 2] === 4 && assignLog[assignStart9 + 3] === 3, "delayed coercion order 9");
assignKeyCheck(assignObj9.p === 4, "delayed coercion value 9");
var assignSeen9 = 0;
var assignRhs9 = 0;
var assignLateKey9 = { name: "late", toString: function() { assignSeen9 = assignRhs9 + 19; return this.name; } };
assignObj9[assignLateKey9] = (assignRhs9 = 13);
assignKeyCheck(assignSeen9 === 32, "rhs before coercion 9");
assignKeyCheck(assignObj9.late === 13, "late assignment value 9");
var assignValueKey9 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj9[assignValueKey9] = 79;
assignKeyCheck(assignObj9.alt === 79, "valueOf assignment key 9");
assignTotal = assignTotal + assignObj9.p + assignObj9.late + assignObj9.alt + assignSeen9;
var assignObj10 = { p: 20, late: 0, alt: 0 };
var assignStart10 = assignLog.length;
var assignKeyObj10 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj10[assignMark(2) && assignKeyObj10] = assignMark(4);
assignKeyCheck(assignLog[assignStart10] === 1 && assignLog[assignStart10 + 1] === 2 && assignLog[assignStart10 + 2] === 4 && assignLog[assignStart10 + 3] === 3, "delayed coercion order 10");
assignKeyCheck(assignObj10.p === 4, "delayed coercion value 10");
var assignSeen10 = 0;
var assignRhs10 = 0;
var assignLateKey10 = { name: "late", toString: function() { assignSeen10 = assignRhs10 + 20; return this.name; } };
assignObj10[assignLateKey10] = (assignRhs10 = 14);
assignKeyCheck(assignSeen10 === 34, "rhs before coercion 10");
assignKeyCheck(assignObj10.late === 14, "late assignment value 10");
var assignValueKey10 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj10[assignValueKey10] = 80;
assignKeyCheck(assignObj10.alt === 80, "valueOf assignment key 10");
assignTotal = assignTotal + assignObj10.p + assignObj10.late + assignObj10.alt + assignSeen10;
var assignObj11 = { p: 21, late: 0, alt: 0 };
var assignStart11 = assignLog.length;
var assignKeyObj11 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj11[assignMark(2) && assignKeyObj11] = assignMark(4);
assignKeyCheck(assignLog[assignStart11] === 1 && assignLog[assignStart11 + 1] === 2 && assignLog[assignStart11 + 2] === 4 && assignLog[assignStart11 + 3] === 3, "delayed coercion order 11");
assignKeyCheck(assignObj11.p === 4, "delayed coercion value 11");
var assignSeen11 = 0;
var assignRhs11 = 0;
var assignLateKey11 = { name: "late", toString: function() { assignSeen11 = assignRhs11 + 21; return this.name; } };
assignObj11[assignLateKey11] = (assignRhs11 = 15);
assignKeyCheck(assignSeen11 === 36, "rhs before coercion 11");
assignKeyCheck(assignObj11.late === 15, "late assignment value 11");
var assignValueKey11 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj11[assignValueKey11] = 81;
assignKeyCheck(assignObj11.alt === 81, "valueOf assignment key 11");
assignTotal = assignTotal + assignObj11.p + assignObj11.late + assignObj11.alt + assignSeen11;
var assignObj12 = { p: 22, late: 0, alt: 0 };
var assignStart12 = assignLog.length;
var assignKeyObj12 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj12[assignMark(2) && assignKeyObj12] = assignMark(4);
assignKeyCheck(assignLog[assignStart12] === 1 && assignLog[assignStart12 + 1] === 2 && assignLog[assignStart12 + 2] === 4 && assignLog[assignStart12 + 3] === 3, "delayed coercion order 12");
assignKeyCheck(assignObj12.p === 4, "delayed coercion value 12");
var assignSeen12 = 0;
var assignRhs12 = 0;
var assignLateKey12 = { name: "late", toString: function() { assignSeen12 = assignRhs12 + 22; return this.name; } };
assignObj12[assignLateKey12] = (assignRhs12 = 16);
assignKeyCheck(assignSeen12 === 38, "rhs before coercion 12");
assignKeyCheck(assignObj12.late === 16, "late assignment value 12");
var assignValueKey12 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj12[assignValueKey12] = 82;
assignKeyCheck(assignObj12.alt === 82, "valueOf assignment key 12");
assignTotal = assignTotal + assignObj12.p + assignObj12.late + assignObj12.alt + assignSeen12;
var assignObj13 = { p: 23, late: 0, alt: 0 };
var assignStart13 = assignLog.length;
var assignKeyObj13 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj13[assignMark(2) && assignKeyObj13] = assignMark(4);
assignKeyCheck(assignLog[assignStart13] === 1 && assignLog[assignStart13 + 1] === 2 && assignLog[assignStart13 + 2] === 4 && assignLog[assignStart13 + 3] === 3, "delayed coercion order 13");
assignKeyCheck(assignObj13.p === 4, "delayed coercion value 13");
var assignSeen13 = 0;
var assignRhs13 = 0;
var assignLateKey13 = { name: "late", toString: function() { assignSeen13 = assignRhs13 + 23; return this.name; } };
assignObj13[assignLateKey13] = (assignRhs13 = 17);
assignKeyCheck(assignSeen13 === 40, "rhs before coercion 13");
assignKeyCheck(assignObj13.late === 17, "late assignment value 13");
var assignValueKey13 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj13[assignValueKey13] = 83;
assignKeyCheck(assignObj13.alt === 83, "valueOf assignment key 13");
assignTotal = assignTotal + assignObj13.p + assignObj13.late + assignObj13.alt + assignSeen13;
var assignObj14 = { p: 24, late: 0, alt: 0 };
var assignStart14 = assignLog.length;
var assignKeyObj14 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj14[assignMark(2) && assignKeyObj14] = assignMark(4);
assignKeyCheck(assignLog[assignStart14] === 1 && assignLog[assignStart14 + 1] === 2 && assignLog[assignStart14 + 2] === 4 && assignLog[assignStart14 + 3] === 3, "delayed coercion order 14");
assignKeyCheck(assignObj14.p === 4, "delayed coercion value 14");
var assignSeen14 = 0;
var assignRhs14 = 0;
var assignLateKey14 = { name: "late", toString: function() { assignSeen14 = assignRhs14 + 24; return this.name; } };
assignObj14[assignLateKey14] = (assignRhs14 = 18);
assignKeyCheck(assignSeen14 === 42, "rhs before coercion 14");
assignKeyCheck(assignObj14.late === 18, "late assignment value 14");
var assignValueKey14 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj14[assignValueKey14] = 84;
assignKeyCheck(assignObj14.alt === 84, "valueOf assignment key 14");
assignTotal = assignTotal + assignObj14.p + assignObj14.late + assignObj14.alt + assignSeen14;
var assignObj15 = { p: 25, late: 0, alt: 0 };
var assignStart15 = assignLog.length;
var assignKeyObj15 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj15[assignMark(2) && assignKeyObj15] = assignMark(4);
assignKeyCheck(assignLog[assignStart15] === 1 && assignLog[assignStart15 + 1] === 2 && assignLog[assignStart15 + 2] === 4 && assignLog[assignStart15 + 3] === 3, "delayed coercion order 15");
assignKeyCheck(assignObj15.p === 4, "delayed coercion value 15");
var assignSeen15 = 0;
var assignRhs15 = 0;
var assignLateKey15 = { name: "late", toString: function() { assignSeen15 = assignRhs15 + 25; return this.name; } };
assignObj15[assignLateKey15] = (assignRhs15 = 19);
assignKeyCheck(assignSeen15 === 44, "rhs before coercion 15");
assignKeyCheck(assignObj15.late === 19, "late assignment value 15");
var assignValueKey15 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj15[assignValueKey15] = 85;
assignKeyCheck(assignObj15.alt === 85, "valueOf assignment key 15");
assignTotal = assignTotal + assignObj15.p + assignObj15.late + assignObj15.alt + assignSeen15;
var assignObj16 = { p: 26, late: 0, alt: 0 };
var assignStart16 = assignLog.length;
var assignKeyObj16 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj16[assignMark(2) && assignKeyObj16] = assignMark(4);
assignKeyCheck(assignLog[assignStart16] === 1 && assignLog[assignStart16 + 1] === 2 && assignLog[assignStart16 + 2] === 4 && assignLog[assignStart16 + 3] === 3, "delayed coercion order 16");
assignKeyCheck(assignObj16.p === 4, "delayed coercion value 16");
var assignSeen16 = 0;
var assignRhs16 = 0;
var assignLateKey16 = { name: "late", toString: function() { assignSeen16 = assignRhs16 + 26; return this.name; } };
assignObj16[assignLateKey16] = (assignRhs16 = 20);
assignKeyCheck(assignSeen16 === 46, "rhs before coercion 16");
assignKeyCheck(assignObj16.late === 20, "late assignment value 16");
var assignValueKey16 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj16[assignValueKey16] = 86;
assignKeyCheck(assignObj16.alt === 86, "valueOf assignment key 16");
assignTotal = assignTotal + assignObj16.p + assignObj16.late + assignObj16.alt + assignSeen16;
var assignObj17 = { p: 27, late: 0, alt: 0 };
var assignStart17 = assignLog.length;
var assignKeyObj17 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj17[assignMark(2) && assignKeyObj17] = assignMark(4);
assignKeyCheck(assignLog[assignStart17] === 1 && assignLog[assignStart17 + 1] === 2 && assignLog[assignStart17 + 2] === 4 && assignLog[assignStart17 + 3] === 3, "delayed coercion order 17");
assignKeyCheck(assignObj17.p === 4, "delayed coercion value 17");
var assignSeen17 = 0;
var assignRhs17 = 0;
var assignLateKey17 = { name: "late", toString: function() { assignSeen17 = assignRhs17 + 27; return this.name; } };
assignObj17[assignLateKey17] = (assignRhs17 = 21);
assignKeyCheck(assignSeen17 === 48, "rhs before coercion 17");
assignKeyCheck(assignObj17.late === 21, "late assignment value 17");
var assignValueKey17 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj17[assignValueKey17] = 87;
assignKeyCheck(assignObj17.alt === 87, "valueOf assignment key 17");
assignTotal = assignTotal + assignObj17.p + assignObj17.late + assignObj17.alt + assignSeen17;
var assignObj18 = { p: 28, late: 0, alt: 0 };
var assignStart18 = assignLog.length;
var assignKeyObj18 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj18[assignMark(2) && assignKeyObj18] = assignMark(4);
assignKeyCheck(assignLog[assignStart18] === 1 && assignLog[assignStart18 + 1] === 2 && assignLog[assignStart18 + 2] === 4 && assignLog[assignStart18 + 3] === 3, "delayed coercion order 18");
assignKeyCheck(assignObj18.p === 4, "delayed coercion value 18");
var assignSeen18 = 0;
var assignRhs18 = 0;
var assignLateKey18 = { name: "late", toString: function() { assignSeen18 = assignRhs18 + 28; return this.name; } };
assignObj18[assignLateKey18] = (assignRhs18 = 22);
assignKeyCheck(assignSeen18 === 50, "rhs before coercion 18");
assignKeyCheck(assignObj18.late === 22, "late assignment value 18");
var assignValueKey18 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj18[assignValueKey18] = 88;
assignKeyCheck(assignObj18.alt === 88, "valueOf assignment key 18");
assignTotal = assignTotal + assignObj18.p + assignObj18.late + assignObj18.alt + assignSeen18;
var assignObj19 = { p: 29, late: 0, alt: 0 };
var assignStart19 = assignLog.length;
var assignKeyObj19 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj19[assignMark(2) && assignKeyObj19] = assignMark(4);
assignKeyCheck(assignLog[assignStart19] === 1 && assignLog[assignStart19 + 1] === 2 && assignLog[assignStart19 + 2] === 4 && assignLog[assignStart19 + 3] === 3, "delayed coercion order 19");
assignKeyCheck(assignObj19.p === 4, "delayed coercion value 19");
var assignSeen19 = 0;
var assignRhs19 = 0;
var assignLateKey19 = { name: "late", toString: function() { assignSeen19 = assignRhs19 + 29; return this.name; } };
assignObj19[assignLateKey19] = (assignRhs19 = 23);
assignKeyCheck(assignSeen19 === 52, "rhs before coercion 19");
assignKeyCheck(assignObj19.late === 23, "late assignment value 19");
var assignValueKey19 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj19[assignValueKey19] = 89;
assignKeyCheck(assignObj19.alt === 89, "valueOf assignment key 19");
assignTotal = assignTotal + assignObj19.p + assignObj19.late + assignObj19.alt + assignSeen19;
var assignObj20 = { p: 30, late: 0, alt: 0 };
var assignStart20 = assignLog.length;
var assignKeyObj20 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj20[assignMark(2) && assignKeyObj20] = assignMark(4);
assignKeyCheck(assignLog[assignStart20] === 1 && assignLog[assignStart20 + 1] === 2 && assignLog[assignStart20 + 2] === 4 && assignLog[assignStart20 + 3] === 3, "delayed coercion order 20");
assignKeyCheck(assignObj20.p === 4, "delayed coercion value 20");
var assignSeen20 = 0;
var assignRhs20 = 0;
var assignLateKey20 = { name: "late", toString: function() { assignSeen20 = assignRhs20 + 30; return this.name; } };
assignObj20[assignLateKey20] = (assignRhs20 = 24);
assignKeyCheck(assignSeen20 === 54, "rhs before coercion 20");
assignKeyCheck(assignObj20.late === 24, "late assignment value 20");
var assignValueKey20 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj20[assignValueKey20] = 90;
assignKeyCheck(assignObj20.alt === 90, "valueOf assignment key 20");
assignTotal = assignTotal + assignObj20.p + assignObj20.late + assignObj20.alt + assignSeen20;
var assignObj21 = { p: 31, late: 0, alt: 0 };
var assignStart21 = assignLog.length;
var assignKeyObj21 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj21[assignMark(2) && assignKeyObj21] = assignMark(4);
assignKeyCheck(assignLog[assignStart21] === 1 && assignLog[assignStart21 + 1] === 2 && assignLog[assignStart21 + 2] === 4 && assignLog[assignStart21 + 3] === 3, "delayed coercion order 21");
assignKeyCheck(assignObj21.p === 4, "delayed coercion value 21");
var assignSeen21 = 0;
var assignRhs21 = 0;
var assignLateKey21 = { name: "late", toString: function() { assignSeen21 = assignRhs21 + 31; return this.name; } };
assignObj21[assignLateKey21] = (assignRhs21 = 25);
assignKeyCheck(assignSeen21 === 56, "rhs before coercion 21");
assignKeyCheck(assignObj21.late === 25, "late assignment value 21");
var assignValueKey21 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj21[assignValueKey21] = 91;
assignKeyCheck(assignObj21.alt === 91, "valueOf assignment key 21");
assignTotal = assignTotal + assignObj21.p + assignObj21.late + assignObj21.alt + assignSeen21;
var assignObj22 = { p: 32, late: 0, alt: 0 };
var assignStart22 = assignLog.length;
var assignKeyObj22 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj22[assignMark(2) && assignKeyObj22] = assignMark(4);
assignKeyCheck(assignLog[assignStart22] === 1 && assignLog[assignStart22 + 1] === 2 && assignLog[assignStart22 + 2] === 4 && assignLog[assignStart22 + 3] === 3, "delayed coercion order 22");
assignKeyCheck(assignObj22.p === 4, "delayed coercion value 22");
var assignSeen22 = 0;
var assignRhs22 = 0;
var assignLateKey22 = { name: "late", toString: function() { assignSeen22 = assignRhs22 + 32; return this.name; } };
assignObj22[assignLateKey22] = (assignRhs22 = 26);
assignKeyCheck(assignSeen22 === 58, "rhs before coercion 22");
assignKeyCheck(assignObj22.late === 26, "late assignment value 22");
var assignValueKey22 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj22[assignValueKey22] = 92;
assignKeyCheck(assignObj22.alt === 92, "valueOf assignment key 22");
assignTotal = assignTotal + assignObj22.p + assignObj22.late + assignObj22.alt + assignSeen22;
var assignObj23 = { p: 33, late: 0, alt: 0 };
var assignStart23 = assignLog.length;
var assignKeyObj23 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj23[assignMark(2) && assignKeyObj23] = assignMark(4);
assignKeyCheck(assignLog[assignStart23] === 1 && assignLog[assignStart23 + 1] === 2 && assignLog[assignStart23 + 2] === 4 && assignLog[assignStart23 + 3] === 3, "delayed coercion order 23");
assignKeyCheck(assignObj23.p === 4, "delayed coercion value 23");
var assignSeen23 = 0;
var assignRhs23 = 0;
var assignLateKey23 = { name: "late", toString: function() { assignSeen23 = assignRhs23 + 33; return this.name; } };
assignObj23[assignLateKey23] = (assignRhs23 = 27);
assignKeyCheck(assignSeen23 === 60, "rhs before coercion 23");
assignKeyCheck(assignObj23.late === 27, "late assignment value 23");
var assignValueKey23 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj23[assignValueKey23] = 93;
assignKeyCheck(assignObj23.alt === 93, "valueOf assignment key 23");
assignTotal = assignTotal + assignObj23.p + assignObj23.late + assignObj23.alt + assignSeen23;
var assignObj24 = { p: 34, late: 0, alt: 0 };
var assignStart24 = assignLog.length;
var assignKeyObj24 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj24[assignMark(2) && assignKeyObj24] = assignMark(4);
assignKeyCheck(assignLog[assignStart24] === 1 && assignLog[assignStart24 + 1] === 2 && assignLog[assignStart24 + 2] === 4 && assignLog[assignStart24 + 3] === 3, "delayed coercion order 24");
assignKeyCheck(assignObj24.p === 4, "delayed coercion value 24");
var assignSeen24 = 0;
var assignRhs24 = 0;
var assignLateKey24 = { name: "late", toString: function() { assignSeen24 = assignRhs24 + 34; return this.name; } };
assignObj24[assignLateKey24] = (assignRhs24 = 28);
assignKeyCheck(assignSeen24 === 62, "rhs before coercion 24");
assignKeyCheck(assignObj24.late === 28, "late assignment value 24");
var assignValueKey24 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj24[assignValueKey24] = 94;
assignKeyCheck(assignObj24.alt === 94, "valueOf assignment key 24");
assignTotal = assignTotal + assignObj24.p + assignObj24.late + assignObj24.alt + assignSeen24;
var assignObj25 = { p: 35, late: 0, alt: 0 };
var assignStart25 = assignLog.length;
var assignKeyObj25 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj25[assignMark(2) && assignKeyObj25] = assignMark(4);
assignKeyCheck(assignLog[assignStart25] === 1 && assignLog[assignStart25 + 1] === 2 && assignLog[assignStart25 + 2] === 4 && assignLog[assignStart25 + 3] === 3, "delayed coercion order 25");
assignKeyCheck(assignObj25.p === 4, "delayed coercion value 25");
var assignSeen25 = 0;
var assignRhs25 = 0;
var assignLateKey25 = { name: "late", toString: function() { assignSeen25 = assignRhs25 + 35; return this.name; } };
assignObj25[assignLateKey25] = (assignRhs25 = 29);
assignKeyCheck(assignSeen25 === 64, "rhs before coercion 25");
assignKeyCheck(assignObj25.late === 29, "late assignment value 25");
var assignValueKey25 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj25[assignValueKey25] = 95;
assignKeyCheck(assignObj25.alt === 95, "valueOf assignment key 25");
assignTotal = assignTotal + assignObj25.p + assignObj25.late + assignObj25.alt + assignSeen25;
var assignObj26 = { p: 36, late: 0, alt: 0 };
var assignStart26 = assignLog.length;
var assignKeyObj26 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj26[assignMark(2) && assignKeyObj26] = assignMark(4);
assignKeyCheck(assignLog[assignStart26] === 1 && assignLog[assignStart26 + 1] === 2 && assignLog[assignStart26 + 2] === 4 && assignLog[assignStart26 + 3] === 3, "delayed coercion order 26");
assignKeyCheck(assignObj26.p === 4, "delayed coercion value 26");
var assignSeen26 = 0;
var assignRhs26 = 0;
var assignLateKey26 = { name: "late", toString: function() { assignSeen26 = assignRhs26 + 36; return this.name; } };
assignObj26[assignLateKey26] = (assignRhs26 = 30);
assignKeyCheck(assignSeen26 === 66, "rhs before coercion 26");
assignKeyCheck(assignObj26.late === 30, "late assignment value 26");
var assignValueKey26 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj26[assignValueKey26] = 96;
assignKeyCheck(assignObj26.alt === 96, "valueOf assignment key 26");
assignTotal = assignTotal + assignObj26.p + assignObj26.late + assignObj26.alt + assignSeen26;
var assignObj27 = { p: 37, late: 0, alt: 0 };
var assignStart27 = assignLog.length;
var assignKeyObj27 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj27[assignMark(2) && assignKeyObj27] = assignMark(4);
assignKeyCheck(assignLog[assignStart27] === 1 && assignLog[assignStart27 + 1] === 2 && assignLog[assignStart27 + 2] === 4 && assignLog[assignStart27 + 3] === 3, "delayed coercion order 27");
assignKeyCheck(assignObj27.p === 4, "delayed coercion value 27");
var assignSeen27 = 0;
var assignRhs27 = 0;
var assignLateKey27 = { name: "late", toString: function() { assignSeen27 = assignRhs27 + 37; return this.name; } };
assignObj27[assignLateKey27] = (assignRhs27 = 31);
assignKeyCheck(assignSeen27 === 68, "rhs before coercion 27");
assignKeyCheck(assignObj27.late === 31, "late assignment value 27");
var assignValueKey27 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj27[assignValueKey27] = 97;
assignKeyCheck(assignObj27.alt === 97, "valueOf assignment key 27");
assignTotal = assignTotal + assignObj27.p + assignObj27.late + assignObj27.alt + assignSeen27;
var assignObj28 = { p: 38, late: 0, alt: 0 };
var assignStart28 = assignLog.length;
var assignKeyObj28 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj28[assignMark(2) && assignKeyObj28] = assignMark(4);
assignKeyCheck(assignLog[assignStart28] === 1 && assignLog[assignStart28 + 1] === 2 && assignLog[assignStart28 + 2] === 4 && assignLog[assignStart28 + 3] === 3, "delayed coercion order 28");
assignKeyCheck(assignObj28.p === 4, "delayed coercion value 28");
var assignSeen28 = 0;
var assignRhs28 = 0;
var assignLateKey28 = { name: "late", toString: function() { assignSeen28 = assignRhs28 + 38; return this.name; } };
assignObj28[assignLateKey28] = (assignRhs28 = 32);
assignKeyCheck(assignSeen28 === 70, "rhs before coercion 28");
assignKeyCheck(assignObj28.late === 32, "late assignment value 28");
var assignValueKey28 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj28[assignValueKey28] = 98;
assignKeyCheck(assignObj28.alt === 98, "valueOf assignment key 28");
assignTotal = assignTotal + assignObj28.p + assignObj28.late + assignObj28.alt + assignSeen28;
var assignObj29 = { p: 39, late: 0, alt: 0 };
var assignStart29 = assignLog.length;
var assignKeyObj29 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj29[assignMark(2) && assignKeyObj29] = assignMark(4);
assignKeyCheck(assignLog[assignStart29] === 1 && assignLog[assignStart29 + 1] === 2 && assignLog[assignStart29 + 2] === 4 && assignLog[assignStart29 + 3] === 3, "delayed coercion order 29");
assignKeyCheck(assignObj29.p === 4, "delayed coercion value 29");
var assignSeen29 = 0;
var assignRhs29 = 0;
var assignLateKey29 = { name: "late", toString: function() { assignSeen29 = assignRhs29 + 39; return this.name; } };
assignObj29[assignLateKey29] = (assignRhs29 = 33);
assignKeyCheck(assignSeen29 === 72, "rhs before coercion 29");
assignKeyCheck(assignObj29.late === 33, "late assignment value 29");
var assignValueKey29 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj29[assignValueKey29] = 99;
assignKeyCheck(assignObj29.alt === 99, "valueOf assignment key 29");
assignTotal = assignTotal + assignObj29.p + assignObj29.late + assignObj29.alt + assignSeen29;
var assignObj30 = { p: 40, late: 0, alt: 0 };
var assignStart30 = assignLog.length;
var assignKeyObj30 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj30[assignMark(2) && assignKeyObj30] = assignMark(4);
assignKeyCheck(assignLog[assignStart30] === 1 && assignLog[assignStart30 + 1] === 2 && assignLog[assignStart30 + 2] === 4 && assignLog[assignStart30 + 3] === 3, "delayed coercion order 30");
assignKeyCheck(assignObj30.p === 4, "delayed coercion value 30");
var assignSeen30 = 0;
var assignRhs30 = 0;
var assignLateKey30 = { name: "late", toString: function() { assignSeen30 = assignRhs30 + 40; return this.name; } };
assignObj30[assignLateKey30] = (assignRhs30 = 34);
assignKeyCheck(assignSeen30 === 74, "rhs before coercion 30");
assignKeyCheck(assignObj30.late === 34, "late assignment value 30");
var assignValueKey30 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj30[assignValueKey30] = 100;
assignKeyCheck(assignObj30.alt === 100, "valueOf assignment key 30");
assignTotal = assignTotal + assignObj30.p + assignObj30.late + assignObj30.alt + assignSeen30;
var assignObj31 = { p: 41, late: 0, alt: 0 };
var assignStart31 = assignLog.length;
var assignKeyObj31 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj31[assignMark(2) && assignKeyObj31] = assignMark(4);
assignKeyCheck(assignLog[assignStart31] === 1 && assignLog[assignStart31 + 1] === 2 && assignLog[assignStart31 + 2] === 4 && assignLog[assignStart31 + 3] === 3, "delayed coercion order 31");
assignKeyCheck(assignObj31.p === 4, "delayed coercion value 31");
var assignSeen31 = 0;
var assignRhs31 = 0;
var assignLateKey31 = { name: "late", toString: function() { assignSeen31 = assignRhs31 + 41; return this.name; } };
assignObj31[assignLateKey31] = (assignRhs31 = 35);
assignKeyCheck(assignSeen31 === 76, "rhs before coercion 31");
assignKeyCheck(assignObj31.late === 35, "late assignment value 31");
var assignValueKey31 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj31[assignValueKey31] = 101;
assignKeyCheck(assignObj31.alt === 101, "valueOf assignment key 31");
assignTotal = assignTotal + assignObj31.p + assignObj31.late + assignObj31.alt + assignSeen31;
var assignObj32 = { p: 42, late: 0, alt: 0 };
var assignStart32 = assignLog.length;
var assignKeyObj32 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj32[assignMark(2) && assignKeyObj32] = assignMark(4);
assignKeyCheck(assignLog[assignStart32] === 1 && assignLog[assignStart32 + 1] === 2 && assignLog[assignStart32 + 2] === 4 && assignLog[assignStart32 + 3] === 3, "delayed coercion order 32");
assignKeyCheck(assignObj32.p === 4, "delayed coercion value 32");
var assignSeen32 = 0;
var assignRhs32 = 0;
var assignLateKey32 = { name: "late", toString: function() { assignSeen32 = assignRhs32 + 42; return this.name; } };
assignObj32[assignLateKey32] = (assignRhs32 = 36);
assignKeyCheck(assignSeen32 === 78, "rhs before coercion 32");
assignKeyCheck(assignObj32.late === 36, "late assignment value 32");
var assignValueKey32 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj32[assignValueKey32] = 102;
assignKeyCheck(assignObj32.alt === 102, "valueOf assignment key 32");
assignTotal = assignTotal + assignObj32.p + assignObj32.late + assignObj32.alt + assignSeen32;
var assignObj33 = { p: 43, late: 0, alt: 0 };
var assignStart33 = assignLog.length;
var assignKeyObj33 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj33[assignMark(2) && assignKeyObj33] = assignMark(4);
assignKeyCheck(assignLog[assignStart33] === 1 && assignLog[assignStart33 + 1] === 2 && assignLog[assignStart33 + 2] === 4 && assignLog[assignStart33 + 3] === 3, "delayed coercion order 33");
assignKeyCheck(assignObj33.p === 4, "delayed coercion value 33");
var assignSeen33 = 0;
var assignRhs33 = 0;
var assignLateKey33 = { name: "late", toString: function() { assignSeen33 = assignRhs33 + 43; return this.name; } };
assignObj33[assignLateKey33] = (assignRhs33 = 37);
assignKeyCheck(assignSeen33 === 80, "rhs before coercion 33");
assignKeyCheck(assignObj33.late === 37, "late assignment value 33");
var assignValueKey33 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj33[assignValueKey33] = 103;
assignKeyCheck(assignObj33.alt === 103, "valueOf assignment key 33");
assignTotal = assignTotal + assignObj33.p + assignObj33.late + assignObj33.alt + assignSeen33;
var assignObj34 = { p: 44, late: 0, alt: 0 };
var assignStart34 = assignLog.length;
var assignKeyObj34 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj34[assignMark(2) && assignKeyObj34] = assignMark(4);
assignKeyCheck(assignLog[assignStart34] === 1 && assignLog[assignStart34 + 1] === 2 && assignLog[assignStart34 + 2] === 4 && assignLog[assignStart34 + 3] === 3, "delayed coercion order 34");
assignKeyCheck(assignObj34.p === 4, "delayed coercion value 34");
var assignSeen34 = 0;
var assignRhs34 = 0;
var assignLateKey34 = { name: "late", toString: function() { assignSeen34 = assignRhs34 + 44; return this.name; } };
assignObj34[assignLateKey34] = (assignRhs34 = 38);
assignKeyCheck(assignSeen34 === 82, "rhs before coercion 34");
assignKeyCheck(assignObj34.late === 38, "late assignment value 34");
var assignValueKey34 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj34[assignValueKey34] = 104;
assignKeyCheck(assignObj34.alt === 104, "valueOf assignment key 34");
assignTotal = assignTotal + assignObj34.p + assignObj34.late + assignObj34.alt + assignSeen34;
var assignObj35 = { p: 45, late: 0, alt: 0 };
var assignStart35 = assignLog.length;
var assignKeyObj35 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj35[assignMark(2) && assignKeyObj35] = assignMark(4);
assignKeyCheck(assignLog[assignStart35] === 1 && assignLog[assignStart35 + 1] === 2 && assignLog[assignStart35 + 2] === 4 && assignLog[assignStart35 + 3] === 3, "delayed coercion order 35");
assignKeyCheck(assignObj35.p === 4, "delayed coercion value 35");
var assignSeen35 = 0;
var assignRhs35 = 0;
var assignLateKey35 = { name: "late", toString: function() { assignSeen35 = assignRhs35 + 45; return this.name; } };
assignObj35[assignLateKey35] = (assignRhs35 = 39);
assignKeyCheck(assignSeen35 === 84, "rhs before coercion 35");
assignKeyCheck(assignObj35.late === 39, "late assignment value 35");
var assignValueKey35 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj35[assignValueKey35] = 105;
assignKeyCheck(assignObj35.alt === 105, "valueOf assignment key 35");
assignTotal = assignTotal + assignObj35.p + assignObj35.late + assignObj35.alt + assignSeen35;
var assignObj36 = { p: 46, late: 0, alt: 0 };
var assignStart36 = assignLog.length;
var assignKeyObj36 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj36[assignMark(2) && assignKeyObj36] = assignMark(4);
assignKeyCheck(assignLog[assignStart36] === 1 && assignLog[assignStart36 + 1] === 2 && assignLog[assignStart36 + 2] === 4 && assignLog[assignStart36 + 3] === 3, "delayed coercion order 36");
assignKeyCheck(assignObj36.p === 4, "delayed coercion value 36");
var assignSeen36 = 0;
var assignRhs36 = 0;
var assignLateKey36 = { name: "late", toString: function() { assignSeen36 = assignRhs36 + 46; return this.name; } };
assignObj36[assignLateKey36] = (assignRhs36 = 40);
assignKeyCheck(assignSeen36 === 86, "rhs before coercion 36");
assignKeyCheck(assignObj36.late === 40, "late assignment value 36");
var assignValueKey36 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj36[assignValueKey36] = 106;
assignKeyCheck(assignObj36.alt === 106, "valueOf assignment key 36");
assignTotal = assignTotal + assignObj36.p + assignObj36.late + assignObj36.alt + assignSeen36;
var assignObj37 = { p: 47, late: 0, alt: 0 };
var assignStart37 = assignLog.length;
var assignKeyObj37 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj37[assignMark(2) && assignKeyObj37] = assignMark(4);
assignKeyCheck(assignLog[assignStart37] === 1 && assignLog[assignStart37 + 1] === 2 && assignLog[assignStart37 + 2] === 4 && assignLog[assignStart37 + 3] === 3, "delayed coercion order 37");
assignKeyCheck(assignObj37.p === 4, "delayed coercion value 37");
var assignSeen37 = 0;
var assignRhs37 = 0;
var assignLateKey37 = { name: "late", toString: function() { assignSeen37 = assignRhs37 + 47; return this.name; } };
assignObj37[assignLateKey37] = (assignRhs37 = 41);
assignKeyCheck(assignSeen37 === 88, "rhs before coercion 37");
assignKeyCheck(assignObj37.late === 41, "late assignment value 37");
var assignValueKey37 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj37[assignValueKey37] = 107;
assignKeyCheck(assignObj37.alt === 107, "valueOf assignment key 37");
assignTotal = assignTotal + assignObj37.p + assignObj37.late + assignObj37.alt + assignSeen37;
var assignObj38 = { p: 48, late: 0, alt: 0 };
var assignStart38 = assignLog.length;
var assignKeyObj38 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj38[assignMark(2) && assignKeyObj38] = assignMark(4);
assignKeyCheck(assignLog[assignStart38] === 1 && assignLog[assignStart38 + 1] === 2 && assignLog[assignStart38 + 2] === 4 && assignLog[assignStart38 + 3] === 3, "delayed coercion order 38");
assignKeyCheck(assignObj38.p === 4, "delayed coercion value 38");
var assignSeen38 = 0;
var assignRhs38 = 0;
var assignLateKey38 = { name: "late", toString: function() { assignSeen38 = assignRhs38 + 48; return this.name; } };
assignObj38[assignLateKey38] = (assignRhs38 = 42);
assignKeyCheck(assignSeen38 === 90, "rhs before coercion 38");
assignKeyCheck(assignObj38.late === 42, "late assignment value 38");
var assignValueKey38 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj38[assignValueKey38] = 108;
assignKeyCheck(assignObj38.alt === 108, "valueOf assignment key 38");
assignTotal = assignTotal + assignObj38.p + assignObj38.late + assignObj38.alt + assignSeen38;
var assignObj39 = { p: 49, late: 0, alt: 0 };
var assignStart39 = assignLog.length;
var assignKeyObj39 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj39[assignMark(2) && assignKeyObj39] = assignMark(4);
assignKeyCheck(assignLog[assignStart39] === 1 && assignLog[assignStart39 + 1] === 2 && assignLog[assignStart39 + 2] === 4 && assignLog[assignStart39 + 3] === 3, "delayed coercion order 39");
assignKeyCheck(assignObj39.p === 4, "delayed coercion value 39");
var assignSeen39 = 0;
var assignRhs39 = 0;
var assignLateKey39 = { name: "late", toString: function() { assignSeen39 = assignRhs39 + 49; return this.name; } };
assignObj39[assignLateKey39] = (assignRhs39 = 43);
assignKeyCheck(assignSeen39 === 92, "rhs before coercion 39");
assignKeyCheck(assignObj39.late === 43, "late assignment value 39");
var assignValueKey39 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj39[assignValueKey39] = 109;
assignKeyCheck(assignObj39.alt === 109, "valueOf assignment key 39");
assignTotal = assignTotal + assignObj39.p + assignObj39.late + assignObj39.alt + assignSeen39;
assignKeyCheck(assignKeyScore === 200, "assign key score");
assignKeyCheck(assignTotal > 0, "assign key accumulated result");
