// behavior: computed-assignment-delays-topropertykey
// expected: pass
// goal: script
// size: standard
// variant: script.sloppy

var assignKeyScore = 0;
function assignKeyCheck(condition, label) {
if (!condition) {
throw label;
}
assignKeyScore = assignKeyScore + 1;
return true;
}
var assignLog = [];
function assignMark(value) { assignLog[assignLog.length] = value; return value; }
var assignTotal = 0;
var assignObj0 = { p: 10, late: 0, alt: 0 };
var assignStart0 = assignLog.length;
var assignKeyObj0 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj0[assignMark(2) && assignKeyObj0] = assignMark(4);
assignKeyCheck(assignLog[assignStart0] === 1 && assignLog[assignStart0 + 1] === 2 && assignLog[assignStart0 + 2] === 4 && assignLog[assignStart0 + 3] === 3, "delayed coercion order 0");
assignKeyCheck(assignObj0.p === 4, "delayed coercion value 0");
var assignSeen0 = 0;
var assignRhs0 = 0;
var assignLateKey0 = { name: "late", toString: function() { assignSeen0 = assignRhs0 + 10; return this.name; } };
assignObj0[assignLateKey0] = (assignRhs0 = 4);
assignKeyCheck(assignSeen0 === 14, "rhs before coercion 0");
assignKeyCheck(assignObj0.late === 4, "late assignment value 0");
var assignValueKey0 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj0[assignValueKey0] = 70;
assignKeyCheck(assignObj0.alt === 70, "valueOf assignment key 0");
assignTotal = assignTotal + assignObj0.p + assignObj0.late + assignObj0.alt + assignSeen0;
var assignObj1 = { p: 11, late: 0, alt: 0 };
var assignStart1 = assignLog.length;
var assignKeyObj1 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj1[assignMark(2) && assignKeyObj1] = assignMark(4);
assignKeyCheck(assignLog[assignStart1] === 1 && assignLog[assignStart1 + 1] === 2 && assignLog[assignStart1 + 2] === 4 && assignLog[assignStart1 + 3] === 3, "delayed coercion order 1");
assignKeyCheck(assignObj1.p === 4, "delayed coercion value 1");
var assignSeen1 = 0;
var assignRhs1 = 0;
var assignLateKey1 = { name: "late", toString: function() { assignSeen1 = assignRhs1 + 11; return this.name; } };
assignObj1[assignLateKey1] = (assignRhs1 = 5);
assignKeyCheck(assignSeen1 === 16, "rhs before coercion 1");
assignKeyCheck(assignObj1.late === 5, "late assignment value 1");
var assignValueKey1 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj1[assignValueKey1] = 71;
assignKeyCheck(assignObj1.alt === 71, "valueOf assignment key 1");
assignTotal = assignTotal + assignObj1.p + assignObj1.late + assignObj1.alt + assignSeen1;
var assignObj2 = { p: 12, late: 0, alt: 0 };
var assignStart2 = assignLog.length;
var assignKeyObj2 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj2[assignMark(2) && assignKeyObj2] = assignMark(4);
assignKeyCheck(assignLog[assignStart2] === 1 && assignLog[assignStart2 + 1] === 2 && assignLog[assignStart2 + 2] === 4 && assignLog[assignStart2 + 3] === 3, "delayed coercion order 2");
assignKeyCheck(assignObj2.p === 4, "delayed coercion value 2");
var assignSeen2 = 0;
var assignRhs2 = 0;
var assignLateKey2 = { name: "late", toString: function() { assignSeen2 = assignRhs2 + 12; return this.name; } };
assignObj2[assignLateKey2] = (assignRhs2 = 6);
assignKeyCheck(assignSeen2 === 18, "rhs before coercion 2");
assignKeyCheck(assignObj2.late === 6, "late assignment value 2");
var assignValueKey2 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj2[assignValueKey2] = 72;
assignKeyCheck(assignObj2.alt === 72, "valueOf assignment key 2");
assignTotal = assignTotal + assignObj2.p + assignObj2.late + assignObj2.alt + assignSeen2;
var assignObj3 = { p: 13, late: 0, alt: 0 };
var assignStart3 = assignLog.length;
var assignKeyObj3 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj3[assignMark(2) && assignKeyObj3] = assignMark(4);
assignKeyCheck(assignLog[assignStart3] === 1 && assignLog[assignStart3 + 1] === 2 && assignLog[assignStart3 + 2] === 4 && assignLog[assignStart3 + 3] === 3, "delayed coercion order 3");
assignKeyCheck(assignObj3.p === 4, "delayed coercion value 3");
var assignSeen3 = 0;
var assignRhs3 = 0;
var assignLateKey3 = { name: "late", toString: function() { assignSeen3 = assignRhs3 + 13; return this.name; } };
assignObj3[assignLateKey3] = (assignRhs3 = 7);
assignKeyCheck(assignSeen3 === 20, "rhs before coercion 3");
assignKeyCheck(assignObj3.late === 7, "late assignment value 3");
var assignValueKey3 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj3[assignValueKey3] = 73;
assignKeyCheck(assignObj3.alt === 73, "valueOf assignment key 3");
assignTotal = assignTotal + assignObj3.p + assignObj3.late + assignObj3.alt + assignSeen3;
var assignObj4 = { p: 14, late: 0, alt: 0 };
var assignStart4 = assignLog.length;
var assignKeyObj4 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj4[assignMark(2) && assignKeyObj4] = assignMark(4);
assignKeyCheck(assignLog[assignStart4] === 1 && assignLog[assignStart4 + 1] === 2 && assignLog[assignStart4 + 2] === 4 && assignLog[assignStart4 + 3] === 3, "delayed coercion order 4");
assignKeyCheck(assignObj4.p === 4, "delayed coercion value 4");
var assignSeen4 = 0;
var assignRhs4 = 0;
var assignLateKey4 = { name: "late", toString: function() { assignSeen4 = assignRhs4 + 14; return this.name; } };
assignObj4[assignLateKey4] = (assignRhs4 = 8);
assignKeyCheck(assignSeen4 === 22, "rhs before coercion 4");
assignKeyCheck(assignObj4.late === 8, "late assignment value 4");
var assignValueKey4 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj4[assignValueKey4] = 74;
assignKeyCheck(assignObj4.alt === 74, "valueOf assignment key 4");
assignTotal = assignTotal + assignObj4.p + assignObj4.late + assignObj4.alt + assignSeen4;
var assignObj5 = { p: 15, late: 0, alt: 0 };
var assignStart5 = assignLog.length;
var assignKeyObj5 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj5[assignMark(2) && assignKeyObj5] = assignMark(4);
assignKeyCheck(assignLog[assignStart5] === 1 && assignLog[assignStart5 + 1] === 2 && assignLog[assignStart5 + 2] === 4 && assignLog[assignStart5 + 3] === 3, "delayed coercion order 5");
assignKeyCheck(assignObj5.p === 4, "delayed coercion value 5");
var assignSeen5 = 0;
var assignRhs5 = 0;
var assignLateKey5 = { name: "late", toString: function() { assignSeen5 = assignRhs5 + 15; return this.name; } };
assignObj5[assignLateKey5] = (assignRhs5 = 9);
assignKeyCheck(assignSeen5 === 24, "rhs before coercion 5");
assignKeyCheck(assignObj5.late === 9, "late assignment value 5");
var assignValueKey5 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj5[assignValueKey5] = 75;
assignKeyCheck(assignObj5.alt === 75, "valueOf assignment key 5");
assignTotal = assignTotal + assignObj5.p + assignObj5.late + assignObj5.alt + assignSeen5;
var assignObj6 = { p: 16, late: 0, alt: 0 };
var assignStart6 = assignLog.length;
var assignKeyObj6 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj6[assignMark(2) && assignKeyObj6] = assignMark(4);
assignKeyCheck(assignLog[assignStart6] === 1 && assignLog[assignStart6 + 1] === 2 && assignLog[assignStart6 + 2] === 4 && assignLog[assignStart6 + 3] === 3, "delayed coercion order 6");
assignKeyCheck(assignObj6.p === 4, "delayed coercion value 6");
var assignSeen6 = 0;
var assignRhs6 = 0;
var assignLateKey6 = { name: "late", toString: function() { assignSeen6 = assignRhs6 + 16; return this.name; } };
assignObj6[assignLateKey6] = (assignRhs6 = 10);
assignKeyCheck(assignSeen6 === 26, "rhs before coercion 6");
assignKeyCheck(assignObj6.late === 10, "late assignment value 6");
var assignValueKey6 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj6[assignValueKey6] = 76;
assignKeyCheck(assignObj6.alt === 76, "valueOf assignment key 6");
assignTotal = assignTotal + assignObj6.p + assignObj6.late + assignObj6.alt + assignSeen6;
var assignObj7 = { p: 17, late: 0, alt: 0 };
var assignStart7 = assignLog.length;
var assignKeyObj7 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj7[assignMark(2) && assignKeyObj7] = assignMark(4);
assignKeyCheck(assignLog[assignStart7] === 1 && assignLog[assignStart7 + 1] === 2 && assignLog[assignStart7 + 2] === 4 && assignLog[assignStart7 + 3] === 3, "delayed coercion order 7");
assignKeyCheck(assignObj7.p === 4, "delayed coercion value 7");
var assignSeen7 = 0;
var assignRhs7 = 0;
var assignLateKey7 = { name: "late", toString: function() { assignSeen7 = assignRhs7 + 17; return this.name; } };
assignObj7[assignLateKey7] = (assignRhs7 = 11);
assignKeyCheck(assignSeen7 === 28, "rhs before coercion 7");
assignKeyCheck(assignObj7.late === 11, "late assignment value 7");
var assignValueKey7 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj7[assignValueKey7] = 77;
assignKeyCheck(assignObj7.alt === 77, "valueOf assignment key 7");
assignTotal = assignTotal + assignObj7.p + assignObj7.late + assignObj7.alt + assignSeen7;
var assignObj8 = { p: 18, late: 0, alt: 0 };
var assignStart8 = assignLog.length;
var assignKeyObj8 = { name: "p", toString: function() { assignMark(3); return this.name; } };
assignMark(1);
assignObj8[assignMark(2) && assignKeyObj8] = assignMark(4);
assignKeyCheck(assignLog[assignStart8] === 1 && assignLog[assignStart8 + 1] === 2 && assignLog[assignStart8 + 2] === 4 && assignLog[assignStart8 + 3] === 3, "delayed coercion order 8");
assignKeyCheck(assignObj8.p === 4, "delayed coercion value 8");
var assignSeen8 = 0;
var assignRhs8 = 0;
var assignLateKey8 = { name: "late", toString: function() { assignSeen8 = assignRhs8 + 18; return this.name; } };
assignObj8[assignLateKey8] = (assignRhs8 = 12);
assignKeyCheck(assignSeen8 === 30, "rhs before coercion 8");
assignKeyCheck(assignObj8.late === 12, "late assignment value 8");
var assignValueKey8 = { name: "alt", toString: 1, valueOf: function() { assignMark(5); return this.name; } };
assignObj8[assignValueKey8] = 78;
assignKeyCheck(assignObj8.alt === 78, "valueOf assignment key 8");
assignTotal = assignTotal + assignObj8.p + assignObj8.late + assignObj8.alt + assignSeen8;
assignKeyCheck(assignKeyScore === 45, "assign key score");
assignKeyCheck(assignTotal > 0, "assign key accumulated result");
