// behavior: primary-identifier-reference-unresolvable-throws
// expected: runtime-error
// goal: script
// size: large
// variant: script.sloppy

var setupPrimaryTotal = 0;
var setupPrimaryBase = 11;
function checkSetupPrimary(condition, label) {
if (!condition) {
throw label;
}
setupPrimaryTotal = setupPrimaryTotal + 1;
return true;
}
function setupPrimaryReferenceWork() {
var setupPrimaryBase = 20;
var localTotal = 0;
localTotal = localTotal + setupPrimaryBase;
checkSetupPrimary(localTotal === 20, "setup local base");
var setupLocal0 = setupPrimaryBase + 0;
checkSetupPrimary(setupLocal0 === setupPrimaryBase + 0, "setup read 0");
setupLocal0 = setupLocal0 + 1;
checkSetupPrimary(setupLocal0 === setupPrimaryBase + 0 + 1, "setup write 0");
localTotal = localTotal + setupLocal0;
var setupBox0 = { value: setupLocal0, base: setupPrimaryBase };
checkSetupPrimary(setupBox0.base === setupPrimaryBase, "setup object 0");
var setupList0 = [setupPrimaryBase, setupLocal0];
checkSetupPrimary(setupList0[0] + setupList0[1] === setupPrimaryBase + setupLocal0, "setup array 0");
var setupLocal1 = setupPrimaryBase + 1;
checkSetupPrimary(setupLocal1 === setupPrimaryBase + 1, "setup read 1");
setupLocal1 = setupLocal1 + 2;
checkSetupPrimary(setupLocal1 === setupPrimaryBase + 1 + 2, "setup write 1");
localTotal = localTotal + setupLocal1;
var setupLocal2 = setupPrimaryBase + 2;
checkSetupPrimary(setupLocal2 === setupPrimaryBase + 2, "setup read 2");
setupLocal2 = setupLocal2 + 3;
checkSetupPrimary(setupLocal2 === setupPrimaryBase + 2 + 3, "setup write 2");
localTotal = localTotal + setupLocal2;
var setupLocal3 = setupPrimaryBase + 3;
checkSetupPrimary(setupLocal3 === setupPrimaryBase + 3, "setup read 3");
setupLocal3 = setupLocal3 + 4;
checkSetupPrimary(setupLocal3 === setupPrimaryBase + 3 + 4, "setup write 3");
localTotal = localTotal + setupLocal3;
var setupBox3 = { value: setupLocal3, base: setupPrimaryBase };
checkSetupPrimary(setupBox3.base === setupPrimaryBase, "setup object 3");
var setupLocal4 = setupPrimaryBase + 4;
checkSetupPrimary(setupLocal4 === setupPrimaryBase + 4, "setup read 4");
setupLocal4 = setupLocal4 + 5;
checkSetupPrimary(setupLocal4 === setupPrimaryBase + 4 + 5, "setup write 4");
localTotal = localTotal + setupLocal4;
var setupList4 = [setupPrimaryBase, setupLocal4];
checkSetupPrimary(setupList4[0] + setupList4[1] === setupPrimaryBase + setupLocal4, "setup array 4");
var setupLocal5 = setupPrimaryBase + 5;
checkSetupPrimary(setupLocal5 === setupPrimaryBase + 5, "setup read 5");
setupLocal5 = setupLocal5 + 6;
checkSetupPrimary(setupLocal5 === setupPrimaryBase + 5 + 6, "setup write 5");
localTotal = localTotal + setupLocal5;
var setupLocal6 = setupPrimaryBase + 6;
checkSetupPrimary(setupLocal6 === setupPrimaryBase + 6, "setup read 6");
setupLocal6 = setupLocal6 + 7;
checkSetupPrimary(setupLocal6 === setupPrimaryBase + 6 + 7, "setup write 6");
localTotal = localTotal + setupLocal6;
var setupBox6 = { value: setupLocal6, base: setupPrimaryBase };
checkSetupPrimary(setupBox6.base === setupPrimaryBase, "setup object 6");
var setupLocal7 = setupPrimaryBase + 7;
checkSetupPrimary(setupLocal7 === setupPrimaryBase + 7, "setup read 7");
setupLocal7 = setupLocal7 + 8;
checkSetupPrimary(setupLocal7 === setupPrimaryBase + 7 + 8, "setup write 7");
localTotal = localTotal + setupLocal7;
var setupLocal8 = setupPrimaryBase + 8;
checkSetupPrimary(setupLocal8 === setupPrimaryBase + 8, "setup read 8");
setupLocal8 = setupLocal8 + 9;
checkSetupPrimary(setupLocal8 === setupPrimaryBase + 8 + 9, "setup write 8");
localTotal = localTotal + setupLocal8;
var setupList8 = [setupPrimaryBase, setupLocal8];
checkSetupPrimary(setupList8[0] + setupList8[1] === setupPrimaryBase + setupLocal8, "setup array 8");
var setupLocal9 = setupPrimaryBase + 9;
checkSetupPrimary(setupLocal9 === setupPrimaryBase + 9, "setup read 9");
setupLocal9 = setupLocal9 + 1;
checkSetupPrimary(setupLocal9 === setupPrimaryBase + 9 + 1, "setup write 9");
localTotal = localTotal + setupLocal9;
var setupBox9 = { value: setupLocal9, base: setupPrimaryBase };
checkSetupPrimary(setupBox9.base === setupPrimaryBase, "setup object 9");
var setupLocal10 = setupPrimaryBase + 10;
checkSetupPrimary(setupLocal10 === setupPrimaryBase + 10, "setup read 10");
setupLocal10 = setupLocal10 + 2;
checkSetupPrimary(setupLocal10 === setupPrimaryBase + 10 + 2, "setup write 10");
localTotal = localTotal + setupLocal10;
var setupLocal11 = setupPrimaryBase + 11;
checkSetupPrimary(setupLocal11 === setupPrimaryBase + 11, "setup read 11");
setupLocal11 = setupLocal11 + 3;
checkSetupPrimary(setupLocal11 === setupPrimaryBase + 11 + 3, "setup write 11");
localTotal = localTotal + setupLocal11;
var setupLocal12 = setupPrimaryBase + 12;
checkSetupPrimary(setupLocal12 === setupPrimaryBase + 12, "setup read 12");
setupLocal12 = setupLocal12 + 4;
checkSetupPrimary(setupLocal12 === setupPrimaryBase + 12 + 4, "setup write 12");
localTotal = localTotal + setupLocal12;
var setupBox12 = { value: setupLocal12, base: setupPrimaryBase };
checkSetupPrimary(setupBox12.base === setupPrimaryBase, "setup object 12");
var setupList12 = [setupPrimaryBase, setupLocal12];
checkSetupPrimary(setupList12[0] + setupList12[1] === setupPrimaryBase + setupLocal12, "setup array 12");
var setupLocal13 = setupPrimaryBase + 13;
checkSetupPrimary(setupLocal13 === setupPrimaryBase + 13, "setup read 13");
setupLocal13 = setupLocal13 + 5;
checkSetupPrimary(setupLocal13 === setupPrimaryBase + 13 + 5, "setup write 13");
localTotal = localTotal + setupLocal13;
var setupLocal14 = setupPrimaryBase + 14;
checkSetupPrimary(setupLocal14 === setupPrimaryBase + 14, "setup read 14");
setupLocal14 = setupLocal14 + 6;
checkSetupPrimary(setupLocal14 === setupPrimaryBase + 14 + 6, "setup write 14");
localTotal = localTotal + setupLocal14;
var setupLocal15 = setupPrimaryBase + 15;
checkSetupPrimary(setupLocal15 === setupPrimaryBase + 15, "setup read 15");
setupLocal15 = setupLocal15 + 7;
checkSetupPrimary(setupLocal15 === setupPrimaryBase + 15 + 7, "setup write 15");
localTotal = localTotal + setupLocal15;
var setupBox15 = { value: setupLocal15, base: setupPrimaryBase };
checkSetupPrimary(setupBox15.base === setupPrimaryBase, "setup object 15");
var setupLocal16 = setupPrimaryBase + 16;
checkSetupPrimary(setupLocal16 === setupPrimaryBase + 16, "setup read 16");
setupLocal16 = setupLocal16 + 8;
checkSetupPrimary(setupLocal16 === setupPrimaryBase + 16 + 8, "setup write 16");
localTotal = localTotal + setupLocal16;
var setupList16 = [setupPrimaryBase, setupLocal16];
checkSetupPrimary(setupList16[0] + setupList16[1] === setupPrimaryBase + setupLocal16, "setup array 16");
var setupLocal17 = setupPrimaryBase + 17;
checkSetupPrimary(setupLocal17 === setupPrimaryBase + 17, "setup read 17");
setupLocal17 = setupLocal17 + 9;
checkSetupPrimary(setupLocal17 === setupPrimaryBase + 17 + 9, "setup write 17");
localTotal = localTotal + setupLocal17;
var setupLocal18 = setupPrimaryBase + 18;
checkSetupPrimary(setupLocal18 === setupPrimaryBase + 18, "setup read 18");
setupLocal18 = setupLocal18 + 1;
checkSetupPrimary(setupLocal18 === setupPrimaryBase + 18 + 1, "setup write 18");
localTotal = localTotal + setupLocal18;
var setupBox18 = { value: setupLocal18, base: setupPrimaryBase };
checkSetupPrimary(setupBox18.base === setupPrimaryBase, "setup object 18");
var setupLocal19 = setupPrimaryBase + 19;
checkSetupPrimary(setupLocal19 === setupPrimaryBase + 19, "setup read 19");
setupLocal19 = setupLocal19 + 2;
checkSetupPrimary(setupLocal19 === setupPrimaryBase + 19 + 2, "setup write 19");
localTotal = localTotal + setupLocal19;
var setupLocal20 = setupPrimaryBase + 20;
checkSetupPrimary(setupLocal20 === setupPrimaryBase + 20, "setup read 20");
setupLocal20 = setupLocal20 + 3;
checkSetupPrimary(setupLocal20 === setupPrimaryBase + 20 + 3, "setup write 20");
localTotal = localTotal + setupLocal20;
var setupList20 = [setupPrimaryBase, setupLocal20];
checkSetupPrimary(setupList20[0] + setupList20[1] === setupPrimaryBase + setupLocal20, "setup array 20");
var setupLocal21 = setupPrimaryBase + 21;
checkSetupPrimary(setupLocal21 === setupPrimaryBase + 21, "setup read 21");
setupLocal21 = setupLocal21 + 4;
checkSetupPrimary(setupLocal21 === setupPrimaryBase + 21 + 4, "setup write 21");
localTotal = localTotal + setupLocal21;
var setupBox21 = { value: setupLocal21, base: setupPrimaryBase };
checkSetupPrimary(setupBox21.base === setupPrimaryBase, "setup object 21");
var setupLocal22 = setupPrimaryBase + 22;
checkSetupPrimary(setupLocal22 === setupPrimaryBase + 22, "setup read 22");
setupLocal22 = setupLocal22 + 5;
checkSetupPrimary(setupLocal22 === setupPrimaryBase + 22 + 5, "setup write 22");
localTotal = localTotal + setupLocal22;
var setupLocal23 = setupPrimaryBase + 23;
checkSetupPrimary(setupLocal23 === setupPrimaryBase + 23, "setup read 23");
setupLocal23 = setupLocal23 + 6;
checkSetupPrimary(setupLocal23 === setupPrimaryBase + 23 + 6, "setup write 23");
localTotal = localTotal + setupLocal23;
var setupLocal24 = setupPrimaryBase + 24;
checkSetupPrimary(setupLocal24 === setupPrimaryBase + 24, "setup read 24");
setupLocal24 = setupLocal24 + 7;
checkSetupPrimary(setupLocal24 === setupPrimaryBase + 24 + 7, "setup write 24");
localTotal = localTotal + setupLocal24;
var setupBox24 = { value: setupLocal24, base: setupPrimaryBase };
checkSetupPrimary(setupBox24.base === setupPrimaryBase, "setup object 24");
var setupList24 = [setupPrimaryBase, setupLocal24];
checkSetupPrimary(setupList24[0] + setupList24[1] === setupPrimaryBase + setupLocal24, "setup array 24");
var setupLocal25 = setupPrimaryBase + 25;
checkSetupPrimary(setupLocal25 === setupPrimaryBase + 25, "setup read 25");
setupLocal25 = setupLocal25 + 8;
checkSetupPrimary(setupLocal25 === setupPrimaryBase + 25 + 8, "setup write 25");
localTotal = localTotal + setupLocal25;
var setupLocal26 = setupPrimaryBase + 26;
checkSetupPrimary(setupLocal26 === setupPrimaryBase + 26, "setup read 26");
setupLocal26 = setupLocal26 + 9;
checkSetupPrimary(setupLocal26 === setupPrimaryBase + 26 + 9, "setup write 26");
localTotal = localTotal + setupLocal26;
var setupLocal27 = setupPrimaryBase + 27;
checkSetupPrimary(setupLocal27 === setupPrimaryBase + 27, "setup read 27");
setupLocal27 = setupLocal27 + 1;
checkSetupPrimary(setupLocal27 === setupPrimaryBase + 27 + 1, "setup write 27");
localTotal = localTotal + setupLocal27;
var setupBox27 = { value: setupLocal27, base: setupPrimaryBase };
checkSetupPrimary(setupBox27.base === setupPrimaryBase, "setup object 27");
var setupLocal28 = setupPrimaryBase + 28;
checkSetupPrimary(setupLocal28 === setupPrimaryBase + 28, "setup read 28");
setupLocal28 = setupLocal28 + 2;
checkSetupPrimary(setupLocal28 === setupPrimaryBase + 28 + 2, "setup write 28");
localTotal = localTotal + setupLocal28;
var setupList28 = [setupPrimaryBase, setupLocal28];
checkSetupPrimary(setupList28[0] + setupList28[1] === setupPrimaryBase + setupLocal28, "setup array 28");
var setupLocal29 = setupPrimaryBase + 29;
checkSetupPrimary(setupLocal29 === setupPrimaryBase + 29, "setup read 29");
setupLocal29 = setupLocal29 + 3;
checkSetupPrimary(setupLocal29 === setupPrimaryBase + 29 + 3, "setup write 29");
localTotal = localTotal + setupLocal29;
var setupLocal30 = setupPrimaryBase + 30;
checkSetupPrimary(setupLocal30 === setupPrimaryBase + 30, "setup read 30");
setupLocal30 = setupLocal30 + 4;
checkSetupPrimary(setupLocal30 === setupPrimaryBase + 30 + 4, "setup write 30");
localTotal = localTotal + setupLocal30;
var setupBox30 = { value: setupLocal30, base: setupPrimaryBase };
checkSetupPrimary(setupBox30.base === setupPrimaryBase, "setup object 30");
var setupLocal31 = setupPrimaryBase + 31;
checkSetupPrimary(setupLocal31 === setupPrimaryBase + 31, "setup read 31");
setupLocal31 = setupLocal31 + 5;
checkSetupPrimary(setupLocal31 === setupPrimaryBase + 31 + 5, "setup write 31");
localTotal = localTotal + setupLocal31;
var setupLocal32 = setupPrimaryBase + 32;
checkSetupPrimary(setupLocal32 === setupPrimaryBase + 32, "setup read 32");
setupLocal32 = setupLocal32 + 6;
checkSetupPrimary(setupLocal32 === setupPrimaryBase + 32 + 6, "setup write 32");
localTotal = localTotal + setupLocal32;
var setupList32 = [setupPrimaryBase, setupLocal32];
checkSetupPrimary(setupList32[0] + setupList32[1] === setupPrimaryBase + setupLocal32, "setup array 32");
var setupLocal33 = setupPrimaryBase + 33;
checkSetupPrimary(setupLocal33 === setupPrimaryBase + 33, "setup read 33");
setupLocal33 = setupLocal33 + 7;
checkSetupPrimary(setupLocal33 === setupPrimaryBase + 33 + 7, "setup write 33");
localTotal = localTotal + setupLocal33;
var setupBox33 = { value: setupLocal33, base: setupPrimaryBase };
checkSetupPrimary(setupBox33.base === setupPrimaryBase, "setup object 33");
var setupLocal34 = setupPrimaryBase + 34;
checkSetupPrimary(setupLocal34 === setupPrimaryBase + 34, "setup read 34");
setupLocal34 = setupLocal34 + 8;
checkSetupPrimary(setupLocal34 === setupPrimaryBase + 34 + 8, "setup write 34");
localTotal = localTotal + setupLocal34;
var setupLocal35 = setupPrimaryBase + 35;
checkSetupPrimary(setupLocal35 === setupPrimaryBase + 35, "setup read 35");
setupLocal35 = setupLocal35 + 9;
checkSetupPrimary(setupLocal35 === setupPrimaryBase + 35 + 9, "setup write 35");
localTotal = localTotal + setupLocal35;
var setupLocal36 = setupPrimaryBase + 36;
checkSetupPrimary(setupLocal36 === setupPrimaryBase + 36, "setup read 36");
setupLocal36 = setupLocal36 + 1;
checkSetupPrimary(setupLocal36 === setupPrimaryBase + 36 + 1, "setup write 36");
localTotal = localTotal + setupLocal36;
var setupBox36 = { value: setupLocal36, base: setupPrimaryBase };
checkSetupPrimary(setupBox36.base === setupPrimaryBase, "setup object 36");
var setupList36 = [setupPrimaryBase, setupLocal36];
checkSetupPrimary(setupList36[0] + setupList36[1] === setupPrimaryBase + setupLocal36, "setup array 36");
var setupLocal37 = setupPrimaryBase + 37;
checkSetupPrimary(setupLocal37 === setupPrimaryBase + 37, "setup read 37");
setupLocal37 = setupLocal37 + 2;
checkSetupPrimary(setupLocal37 === setupPrimaryBase + 37 + 2, "setup write 37");
localTotal = localTotal + setupLocal37;
var setupLocal38 = setupPrimaryBase + 38;
checkSetupPrimary(setupLocal38 === setupPrimaryBase + 38, "setup read 38");
setupLocal38 = setupLocal38 + 3;
checkSetupPrimary(setupLocal38 === setupPrimaryBase + 38 + 3, "setup write 38");
localTotal = localTotal + setupLocal38;
var setupLocal39 = setupPrimaryBase + 39;
checkSetupPrimary(setupLocal39 === setupPrimaryBase + 39, "setup read 39");
setupLocal39 = setupLocal39 + 4;
checkSetupPrimary(setupLocal39 === setupPrimaryBase + 39 + 4, "setup write 39");
localTotal = localTotal + setupLocal39;
var setupBox39 = { value: setupLocal39, base: setupPrimaryBase };
checkSetupPrimary(setupBox39.base === setupPrimaryBase, "setup object 39");
var setupLocal40 = setupPrimaryBase + 40;
checkSetupPrimary(setupLocal40 === setupPrimaryBase + 40, "setup read 40");
setupLocal40 = setupLocal40 + 5;
checkSetupPrimary(setupLocal40 === setupPrimaryBase + 40 + 5, "setup write 40");
localTotal = localTotal + setupLocal40;
var setupList40 = [setupPrimaryBase, setupLocal40];
checkSetupPrimary(setupList40[0] + setupList40[1] === setupPrimaryBase + setupLocal40, "setup array 40");
var setupLocal41 = setupPrimaryBase + 41;
checkSetupPrimary(setupLocal41 === setupPrimaryBase + 41, "setup read 41");
setupLocal41 = setupLocal41 + 6;
checkSetupPrimary(setupLocal41 === setupPrimaryBase + 41 + 6, "setup write 41");
localTotal = localTotal + setupLocal41;
var setupLocal42 = setupPrimaryBase + 42;
checkSetupPrimary(setupLocal42 === setupPrimaryBase + 42, "setup read 42");
setupLocal42 = setupLocal42 + 7;
checkSetupPrimary(setupLocal42 === setupPrimaryBase + 42 + 7, "setup write 42");
localTotal = localTotal + setupLocal42;
var setupBox42 = { value: setupLocal42, base: setupPrimaryBase };
checkSetupPrimary(setupBox42.base === setupPrimaryBase, "setup object 42");
var setupLocal43 = setupPrimaryBase + 43;
checkSetupPrimary(setupLocal43 === setupPrimaryBase + 43, "setup read 43");
setupLocal43 = setupLocal43 + 8;
checkSetupPrimary(setupLocal43 === setupPrimaryBase + 43 + 8, "setup write 43");
localTotal = localTotal + setupLocal43;
var setupLocal44 = setupPrimaryBase + 44;
checkSetupPrimary(setupLocal44 === setupPrimaryBase + 44, "setup read 44");
setupLocal44 = setupLocal44 + 9;
checkSetupPrimary(setupLocal44 === setupPrimaryBase + 44 + 9, "setup write 44");
localTotal = localTotal + setupLocal44;
var setupList44 = [setupPrimaryBase, setupLocal44];
checkSetupPrimary(setupList44[0] + setupList44[1] === setupPrimaryBase + setupLocal44, "setup array 44");
var setupLocal45 = setupPrimaryBase + 45;
checkSetupPrimary(setupLocal45 === setupPrimaryBase + 45, "setup read 45");
setupLocal45 = setupLocal45 + 1;
checkSetupPrimary(setupLocal45 === setupPrimaryBase + 45 + 1, "setup write 45");
localTotal = localTotal + setupLocal45;
var setupBox45 = { value: setupLocal45, base: setupPrimaryBase };
checkSetupPrimary(setupBox45.base === setupPrimaryBase, "setup object 45");
var setupLocal46 = setupPrimaryBase + 46;
checkSetupPrimary(setupLocal46 === setupPrimaryBase + 46, "setup read 46");
setupLocal46 = setupLocal46 + 2;
checkSetupPrimary(setupLocal46 === setupPrimaryBase + 46 + 2, "setup write 46");
localTotal = localTotal + setupLocal46;
var setupLocal47 = setupPrimaryBase + 47;
checkSetupPrimary(setupLocal47 === setupPrimaryBase + 47, "setup read 47");
setupLocal47 = setupLocal47 + 3;
checkSetupPrimary(setupLocal47 === setupPrimaryBase + 47 + 3, "setup write 47");
localTotal = localTotal + setupLocal47;
var setupLocal48 = setupPrimaryBase + 48;
checkSetupPrimary(setupLocal48 === setupPrimaryBase + 48, "setup read 48");
setupLocal48 = setupLocal48 + 4;
checkSetupPrimary(setupLocal48 === setupPrimaryBase + 48 + 4, "setup write 48");
localTotal = localTotal + setupLocal48;
var setupBox48 = { value: setupLocal48, base: setupPrimaryBase };
checkSetupPrimary(setupBox48.base === setupPrimaryBase, "setup object 48");
var setupList48 = [setupPrimaryBase, setupLocal48];
checkSetupPrimary(setupList48[0] + setupList48[1] === setupPrimaryBase + setupLocal48, "setup array 48");
var setupLocal49 = setupPrimaryBase + 49;
checkSetupPrimary(setupLocal49 === setupPrimaryBase + 49, "setup read 49");
setupLocal49 = setupLocal49 + 5;
checkSetupPrimary(setupLocal49 === setupPrimaryBase + 49 + 5, "setup write 49");
localTotal = localTotal + setupLocal49;
var setupLocal50 = setupPrimaryBase + 50;
checkSetupPrimary(setupLocal50 === setupPrimaryBase + 50, "setup read 50");
setupLocal50 = setupLocal50 + 6;
checkSetupPrimary(setupLocal50 === setupPrimaryBase + 50 + 6, "setup write 50");
localTotal = localTotal + setupLocal50;
var setupLocal51 = setupPrimaryBase + 51;
checkSetupPrimary(setupLocal51 === setupPrimaryBase + 51, "setup read 51");
setupLocal51 = setupLocal51 + 7;
checkSetupPrimary(setupLocal51 === setupPrimaryBase + 51 + 7, "setup write 51");
localTotal = localTotal + setupLocal51;
var setupBox51 = { value: setupLocal51, base: setupPrimaryBase };
checkSetupPrimary(setupBox51.base === setupPrimaryBase, "setup object 51");
var setupLocal52 = setupPrimaryBase + 52;
checkSetupPrimary(setupLocal52 === setupPrimaryBase + 52, "setup read 52");
setupLocal52 = setupLocal52 + 8;
checkSetupPrimary(setupLocal52 === setupPrimaryBase + 52 + 8, "setup write 52");
localTotal = localTotal + setupLocal52;
var setupList52 = [setupPrimaryBase, setupLocal52];
checkSetupPrimary(setupList52[0] + setupList52[1] === setupPrimaryBase + setupLocal52, "setup array 52");
var setupLocal53 = setupPrimaryBase + 53;
checkSetupPrimary(setupLocal53 === setupPrimaryBase + 53, "setup read 53");
setupLocal53 = setupLocal53 + 9;
checkSetupPrimary(setupLocal53 === setupPrimaryBase + 53 + 9, "setup write 53");
localTotal = localTotal + setupLocal53;
var setupLocal54 = setupPrimaryBase + 54;
checkSetupPrimary(setupLocal54 === setupPrimaryBase + 54, "setup read 54");
setupLocal54 = setupLocal54 + 1;
checkSetupPrimary(setupLocal54 === setupPrimaryBase + 54 + 1, "setup write 54");
localTotal = localTotal + setupLocal54;
var setupBox54 = { value: setupLocal54, base: setupPrimaryBase };
checkSetupPrimary(setupBox54.base === setupPrimaryBase, "setup object 54");
var setupLocal55 = setupPrimaryBase + 55;
checkSetupPrimary(setupLocal55 === setupPrimaryBase + 55, "setup read 55");
setupLocal55 = setupLocal55 + 2;
checkSetupPrimary(setupLocal55 === setupPrimaryBase + 55 + 2, "setup write 55");
localTotal = localTotal + setupLocal55;
var setupLocal56 = setupPrimaryBase + 56;
checkSetupPrimary(setupLocal56 === setupPrimaryBase + 56, "setup read 56");
setupLocal56 = setupLocal56 + 3;
checkSetupPrimary(setupLocal56 === setupPrimaryBase + 56 + 3, "setup write 56");
localTotal = localTotal + setupLocal56;
var setupList56 = [setupPrimaryBase, setupLocal56];
checkSetupPrimary(setupList56[0] + setupList56[1] === setupPrimaryBase + setupLocal56, "setup array 56");
var setupLocal57 = setupPrimaryBase + 57;
checkSetupPrimary(setupLocal57 === setupPrimaryBase + 57, "setup read 57");
setupLocal57 = setupLocal57 + 4;
checkSetupPrimary(setupLocal57 === setupPrimaryBase + 57 + 4, "setup write 57");
localTotal = localTotal + setupLocal57;
var setupBox57 = { value: setupLocal57, base: setupPrimaryBase };
checkSetupPrimary(setupBox57.base === setupPrimaryBase, "setup object 57");
var setupLocal58 = setupPrimaryBase + 58;
checkSetupPrimary(setupLocal58 === setupPrimaryBase + 58, "setup read 58");
setupLocal58 = setupLocal58 + 5;
checkSetupPrimary(setupLocal58 === setupPrimaryBase + 58 + 5, "setup write 58");
localTotal = localTotal + setupLocal58;
var setupLocal59 = setupPrimaryBase + 59;
checkSetupPrimary(setupLocal59 === setupPrimaryBase + 59, "setup read 59");
setupLocal59 = setupLocal59 + 6;
checkSetupPrimary(setupLocal59 === setupPrimaryBase + 59 + 6, "setup write 59");
localTotal = localTotal + setupLocal59;
var setupLocal60 = setupPrimaryBase + 60;
checkSetupPrimary(setupLocal60 === setupPrimaryBase + 60, "setup read 60");
setupLocal60 = setupLocal60 + 7;
checkSetupPrimary(setupLocal60 === setupPrimaryBase + 60 + 7, "setup write 60");
localTotal = localTotal + setupLocal60;
var setupBox60 = { value: setupLocal60, base: setupPrimaryBase };
checkSetupPrimary(setupBox60.base === setupPrimaryBase, "setup object 60");
var setupList60 = [setupPrimaryBase, setupLocal60];
checkSetupPrimary(setupList60[0] + setupList60[1] === setupPrimaryBase + setupLocal60, "setup array 60");
var setupLocal61 = setupPrimaryBase + 61;
checkSetupPrimary(setupLocal61 === setupPrimaryBase + 61, "setup read 61");
setupLocal61 = setupLocal61 + 8;
checkSetupPrimary(setupLocal61 === setupPrimaryBase + 61 + 8, "setup write 61");
localTotal = localTotal + setupLocal61;
var setupLocal62 = setupPrimaryBase + 62;
checkSetupPrimary(setupLocal62 === setupPrimaryBase + 62, "setup read 62");
setupLocal62 = setupLocal62 + 9;
checkSetupPrimary(setupLocal62 === setupPrimaryBase + 62 + 9, "setup write 62");
localTotal = localTotal + setupLocal62;
var setupLocal63 = setupPrimaryBase + 63;
checkSetupPrimary(setupLocal63 === setupPrimaryBase + 63, "setup read 63");
setupLocal63 = setupLocal63 + 1;
checkSetupPrimary(setupLocal63 === setupPrimaryBase + 63 + 1, "setup write 63");
localTotal = localTotal + setupLocal63;
var setupBox63 = { value: setupLocal63, base: setupPrimaryBase };
checkSetupPrimary(setupBox63.base === setupPrimaryBase, "setup object 63");
var setupLocal64 = setupPrimaryBase + 64;
checkSetupPrimary(setupLocal64 === setupPrimaryBase + 64, "setup read 64");
setupLocal64 = setupLocal64 + 2;
checkSetupPrimary(setupLocal64 === setupPrimaryBase + 64 + 2, "setup write 64");
localTotal = localTotal + setupLocal64;
var setupList64 = [setupPrimaryBase, setupLocal64];
checkSetupPrimary(setupList64[0] + setupList64[1] === setupPrimaryBase + setupLocal64, "setup array 64");
var setupLocal65 = setupPrimaryBase + 65;
checkSetupPrimary(setupLocal65 === setupPrimaryBase + 65, "setup read 65");
setupLocal65 = setupLocal65 + 3;
checkSetupPrimary(setupLocal65 === setupPrimaryBase + 65 + 3, "setup write 65");
localTotal = localTotal + setupLocal65;
var setupLocal66 = setupPrimaryBase + 66;
checkSetupPrimary(setupLocal66 === setupPrimaryBase + 66, "setup read 66");
setupLocal66 = setupLocal66 + 4;
checkSetupPrimary(setupLocal66 === setupPrimaryBase + 66 + 4, "setup write 66");
localTotal = localTotal + setupLocal66;
var setupBox66 = { value: setupLocal66, base: setupPrimaryBase };
checkSetupPrimary(setupBox66.base === setupPrimaryBase, "setup object 66");
var setupLocal67 = setupPrimaryBase + 67;
checkSetupPrimary(setupLocal67 === setupPrimaryBase + 67, "setup read 67");
setupLocal67 = setupLocal67 + 5;
checkSetupPrimary(setupLocal67 === setupPrimaryBase + 67 + 5, "setup write 67");
localTotal = localTotal + setupLocal67;
var setupLocal68 = setupPrimaryBase + 68;
checkSetupPrimary(setupLocal68 === setupPrimaryBase + 68, "setup read 68");
setupLocal68 = setupLocal68 + 6;
checkSetupPrimary(setupLocal68 === setupPrimaryBase + 68 + 6, "setup write 68");
localTotal = localTotal + setupLocal68;
var setupList68 = [setupPrimaryBase, setupLocal68];
checkSetupPrimary(setupList68[0] + setupList68[1] === setupPrimaryBase + setupLocal68, "setup array 68");
var setupLocal69 = setupPrimaryBase + 69;
checkSetupPrimary(setupLocal69 === setupPrimaryBase + 69, "setup read 69");
setupLocal69 = setupLocal69 + 7;
checkSetupPrimary(setupLocal69 === setupPrimaryBase + 69 + 7, "setup write 69");
localTotal = localTotal + setupLocal69;
var setupBox69 = { value: setupLocal69, base: setupPrimaryBase };
checkSetupPrimary(setupBox69.base === setupPrimaryBase, "setup object 69");
var setupLocal70 = setupPrimaryBase + 70;
checkSetupPrimary(setupLocal70 === setupPrimaryBase + 70, "setup read 70");
setupLocal70 = setupLocal70 + 8;
checkSetupPrimary(setupLocal70 === setupPrimaryBase + 70 + 8, "setup write 70");
localTotal = localTotal + setupLocal70;
var setupLocal71 = setupPrimaryBase + 71;
checkSetupPrimary(setupLocal71 === setupPrimaryBase + 71, "setup read 71");
setupLocal71 = setupLocal71 + 9;
checkSetupPrimary(setupLocal71 === setupPrimaryBase + 71 + 9, "setup write 71");
localTotal = localTotal + setupLocal71;
var setupLocal72 = setupPrimaryBase + 72;
checkSetupPrimary(setupLocal72 === setupPrimaryBase + 72, "setup read 72");
setupLocal72 = setupLocal72 + 1;
checkSetupPrimary(setupLocal72 === setupPrimaryBase + 72 + 1, "setup write 72");
localTotal = localTotal + setupLocal72;
var setupBox72 = { value: setupLocal72, base: setupPrimaryBase };
checkSetupPrimary(setupBox72.base === setupPrimaryBase, "setup object 72");
var setupList72 = [setupPrimaryBase, setupLocal72];
checkSetupPrimary(setupList72[0] + setupList72[1] === setupPrimaryBase + setupLocal72, "setup array 72");
var setupLocal73 = setupPrimaryBase + 73;
checkSetupPrimary(setupLocal73 === setupPrimaryBase + 73, "setup read 73");
setupLocal73 = setupLocal73 + 2;
checkSetupPrimary(setupLocal73 === setupPrimaryBase + 73 + 2, "setup write 73");
localTotal = localTotal + setupLocal73;
var setupLocal74 = setupPrimaryBase + 74;
checkSetupPrimary(setupLocal74 === setupPrimaryBase + 74, "setup read 74");
setupLocal74 = setupLocal74 + 3;
checkSetupPrimary(setupLocal74 === setupPrimaryBase + 74 + 3, "setup write 74");
localTotal = localTotal + setupLocal74;
var setupLocal75 = setupPrimaryBase + 75;
checkSetupPrimary(setupLocal75 === setupPrimaryBase + 75, "setup read 75");
setupLocal75 = setupLocal75 + 4;
checkSetupPrimary(setupLocal75 === setupPrimaryBase + 75 + 4, "setup write 75");
localTotal = localTotal + setupLocal75;
var setupBox75 = { value: setupLocal75, base: setupPrimaryBase };
checkSetupPrimary(setupBox75.base === setupPrimaryBase, "setup object 75");
var setupLocal76 = setupPrimaryBase + 76;
checkSetupPrimary(setupLocal76 === setupPrimaryBase + 76, "setup read 76");
setupLocal76 = setupLocal76 + 5;
checkSetupPrimary(setupLocal76 === setupPrimaryBase + 76 + 5, "setup write 76");
localTotal = localTotal + setupLocal76;
var setupList76 = [setupPrimaryBase, setupLocal76];
checkSetupPrimary(setupList76[0] + setupList76[1] === setupPrimaryBase + setupLocal76, "setup array 76");
var setupLocal77 = setupPrimaryBase + 77;
checkSetupPrimary(setupLocal77 === setupPrimaryBase + 77, "setup read 77");
setupLocal77 = setupLocal77 + 6;
checkSetupPrimary(setupLocal77 === setupPrimaryBase + 77 + 6, "setup write 77");
localTotal = localTotal + setupLocal77;
var setupLocal78 = setupPrimaryBase + 78;
checkSetupPrimary(setupLocal78 === setupPrimaryBase + 78, "setup read 78");
setupLocal78 = setupLocal78 + 7;
checkSetupPrimary(setupLocal78 === setupPrimaryBase + 78 + 7, "setup write 78");
localTotal = localTotal + setupLocal78;
var setupBox78 = { value: setupLocal78, base: setupPrimaryBase };
checkSetupPrimary(setupBox78.base === setupPrimaryBase, "setup object 78");
var setupLocal79 = setupPrimaryBase + 79;
checkSetupPrimary(setupLocal79 === setupPrimaryBase + 79, "setup read 79");
setupLocal79 = setupLocal79 + 8;
checkSetupPrimary(setupLocal79 === setupPrimaryBase + 79 + 8, "setup write 79");
localTotal = localTotal + setupLocal79;
var setupLocal80 = setupPrimaryBase + 80;
checkSetupPrimary(setupLocal80 === setupPrimaryBase + 80, "setup read 80");
setupLocal80 = setupLocal80 + 9;
checkSetupPrimary(setupLocal80 === setupPrimaryBase + 80 + 9, "setup write 80");
localTotal = localTotal + setupLocal80;
var setupList80 = [setupPrimaryBase, setupLocal80];
checkSetupPrimary(setupList80[0] + setupList80[1] === setupPrimaryBase + setupLocal80, "setup array 80");
var setupLocal81 = setupPrimaryBase + 81;
checkSetupPrimary(setupLocal81 === setupPrimaryBase + 81, "setup read 81");
setupLocal81 = setupLocal81 + 1;
checkSetupPrimary(setupLocal81 === setupPrimaryBase + 81 + 1, "setup write 81");
localTotal = localTotal + setupLocal81;
var setupBox81 = { value: setupLocal81, base: setupPrimaryBase };
checkSetupPrimary(setupBox81.base === setupPrimaryBase, "setup object 81");
return localTotal;
}
setupPrimaryTotal = setupPrimaryReferenceWork();
if (setupPrimaryTotal <= 0) { throw "setup did not run"; }
console.log(__ayyMissingPrimaryIdentifierReference);
