// behavior: null-literal-evaluates-null
// expected: pass
// goal: script
// size: large
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}
var missingValue = undefined;
function returnNull(value) { if (value) { return null; } return null; }
var nullValue0 = null;
check(nullValue0 === null, 'null strict 0');
check(!(nullValue0 !== null), 'null strict inverse 0');
check(nullValue0 == missingValue, 'null loose undefined 0');
check(!(nullValue0 === missingValue), 'null not undefined 0');
check(typeof nullValue0 === 'object', 'null typeof 0');
check((true ? null : 0) === nullValue0, 'null ternary true 0');
check((false ? 0 : null) === nullValue0, 'null ternary false 0');
check(returnNull(true) === null, 'null return 0');
var nullValue1 = null;
check(nullValue1 === null, 'null strict 1');
check(!(nullValue1 !== null), 'null strict inverse 1');
check(nullValue1 == missingValue, 'null loose undefined 1');
check(!(nullValue1 === missingValue), 'null not undefined 1');
check(typeof nullValue1 === 'object', 'null typeof 1');
check((true ? null : 1) === nullValue1, 'null ternary true 1');
check((false ? 1 : null) === nullValue1, 'null ternary false 1');
check(returnNull(false) === null, 'null return 1');
var nullValue2 = null;
check(nullValue2 === null, 'null strict 2');
check(!(nullValue2 !== null), 'null strict inverse 2');
check(nullValue2 == missingValue, 'null loose undefined 2');
check(!(nullValue2 === missingValue), 'null not undefined 2');
check(typeof nullValue2 === 'object', 'null typeof 2');
check((true ? null : 2) === nullValue2, 'null ternary true 2');
check((false ? 2 : null) === nullValue2, 'null ternary false 2');
check(returnNull(true) === null, 'null return 2');
var nullValue3 = null;
check(nullValue3 === null, 'null strict 3');
check(!(nullValue3 !== null), 'null strict inverse 3');
check(nullValue3 == missingValue, 'null loose undefined 3');
check(!(nullValue3 === missingValue), 'null not undefined 3');
check(typeof nullValue3 === 'object', 'null typeof 3');
check((true ? null : 3) === nullValue3, 'null ternary true 3');
check((false ? 3 : null) === nullValue3, 'null ternary false 3');
check(returnNull(false) === null, 'null return 3');
var nullValue4 = null;
check(nullValue4 === null, 'null strict 4');
check(!(nullValue4 !== null), 'null strict inverse 4');
check(nullValue4 == missingValue, 'null loose undefined 4');
check(!(nullValue4 === missingValue), 'null not undefined 4');
check(typeof nullValue4 === 'object', 'null typeof 4');
check((true ? null : 4) === nullValue4, 'null ternary true 4');
check((false ? 4 : null) === nullValue4, 'null ternary false 4');
check(returnNull(true) === null, 'null return 4');
var nullValue5 = null;
check(nullValue5 === null, 'null strict 5');
check(!(nullValue5 !== null), 'null strict inverse 5');
check(nullValue5 == missingValue, 'null loose undefined 5');
check(!(nullValue5 === missingValue), 'null not undefined 5');
check(typeof nullValue5 === 'object', 'null typeof 5');
check((true ? null : 5) === nullValue5, 'null ternary true 5');
check((false ? 5 : null) === nullValue5, 'null ternary false 5');
check(returnNull(false) === null, 'null return 5');
var nullValue6 = null;
check(nullValue6 === null, 'null strict 6');
check(!(nullValue6 !== null), 'null strict inverse 6');
check(nullValue6 == missingValue, 'null loose undefined 6');
check(!(nullValue6 === missingValue), 'null not undefined 6');
check(typeof nullValue6 === 'object', 'null typeof 6');
check((true ? null : 6) === nullValue6, 'null ternary true 6');
check((false ? 6 : null) === nullValue6, 'null ternary false 6');
check(returnNull(true) === null, 'null return 6');
var nullValue7 = null;
check(nullValue7 === null, 'null strict 7');
check(!(nullValue7 !== null), 'null strict inverse 7');
check(nullValue7 == missingValue, 'null loose undefined 7');
check(!(nullValue7 === missingValue), 'null not undefined 7');
check(typeof nullValue7 === 'object', 'null typeof 7');
check((true ? null : 7) === nullValue7, 'null ternary true 7');
check((false ? 7 : null) === nullValue7, 'null ternary false 7');
check(returnNull(false) === null, 'null return 7');
var nullValue8 = null;
check(nullValue8 === null, 'null strict 8');
check(!(nullValue8 !== null), 'null strict inverse 8');
check(nullValue8 == missingValue, 'null loose undefined 8');
check(!(nullValue8 === missingValue), 'null not undefined 8');
check(typeof nullValue8 === 'object', 'null typeof 8');
check((true ? null : 8) === nullValue8, 'null ternary true 8');
check((false ? 8 : null) === nullValue8, 'null ternary false 8');
check(returnNull(true) === null, 'null return 8');
var nullValue9 = null;
check(nullValue9 === null, 'null strict 9');
check(!(nullValue9 !== null), 'null strict inverse 9');
check(nullValue9 == missingValue, 'null loose undefined 9');
check(!(nullValue9 === missingValue), 'null not undefined 9');
check(typeof nullValue9 === 'object', 'null typeof 9');
check((true ? null : 9) === nullValue9, 'null ternary true 9');
check((false ? 9 : null) === nullValue9, 'null ternary false 9');
check(returnNull(false) === null, 'null return 9');
var nullValue10 = null;
check(nullValue10 === null, 'null strict 10');
check(!(nullValue10 !== null), 'null strict inverse 10');
check(nullValue10 == missingValue, 'null loose undefined 10');
check(!(nullValue10 === missingValue), 'null not undefined 10');
check(typeof nullValue10 === 'object', 'null typeof 10');
check((true ? null : 10) === nullValue10, 'null ternary true 10');
check((false ? 10 : null) === nullValue10, 'null ternary false 10');
check(returnNull(true) === null, 'null return 10');
var nullValue11 = null;
check(nullValue11 === null, 'null strict 11');
check(!(nullValue11 !== null), 'null strict inverse 11');
check(nullValue11 == missingValue, 'null loose undefined 11');
check(!(nullValue11 === missingValue), 'null not undefined 11');
check(typeof nullValue11 === 'object', 'null typeof 11');
check((true ? null : 11) === nullValue11, 'null ternary true 11');
check((false ? 11 : null) === nullValue11, 'null ternary false 11');
check(returnNull(false) === null, 'null return 11');
var nullValue12 = null;
check(nullValue12 === null, 'null strict 12');
check(!(nullValue12 !== null), 'null strict inverse 12');
check(nullValue12 == missingValue, 'null loose undefined 12');
check(!(nullValue12 === missingValue), 'null not undefined 12');
check(typeof nullValue12 === 'object', 'null typeof 12');
check((true ? null : 12) === nullValue12, 'null ternary true 12');
check((false ? 12 : null) === nullValue12, 'null ternary false 12');
check(returnNull(true) === null, 'null return 12');
var nullValue13 = null;
check(nullValue13 === null, 'null strict 13');
check(!(nullValue13 !== null), 'null strict inverse 13');
check(nullValue13 == missingValue, 'null loose undefined 13');
check(!(nullValue13 === missingValue), 'null not undefined 13');
check(typeof nullValue13 === 'object', 'null typeof 13');
check((true ? null : 13) === nullValue13, 'null ternary true 13');
check((false ? 13 : null) === nullValue13, 'null ternary false 13');
check(returnNull(false) === null, 'null return 13');
var nullValue14 = null;
check(nullValue14 === null, 'null strict 14');
check(!(nullValue14 !== null), 'null strict inverse 14');
check(nullValue14 == missingValue, 'null loose undefined 14');
check(!(nullValue14 === missingValue), 'null not undefined 14');
check(typeof nullValue14 === 'object', 'null typeof 14');
check((true ? null : 14) === nullValue14, 'null ternary true 14');
check((false ? 14 : null) === nullValue14, 'null ternary false 14');
check(returnNull(true) === null, 'null return 14');
var nullValue15 = null;
check(nullValue15 === null, 'null strict 15');
check(!(nullValue15 !== null), 'null strict inverse 15');
check(nullValue15 == missingValue, 'null loose undefined 15');
check(!(nullValue15 === missingValue), 'null not undefined 15');
check(typeof nullValue15 === 'object', 'null typeof 15');
check((true ? null : 15) === nullValue15, 'null ternary true 15');
check((false ? 15 : null) === nullValue15, 'null ternary false 15');
check(returnNull(false) === null, 'null return 15');
var nullValue16 = null;
check(nullValue16 === null, 'null strict 16');
check(!(nullValue16 !== null), 'null strict inverse 16');
check(nullValue16 == missingValue, 'null loose undefined 16');
check(!(nullValue16 === missingValue), 'null not undefined 16');
check(typeof nullValue16 === 'object', 'null typeof 16');
check((true ? null : 16) === nullValue16, 'null ternary true 16');
check((false ? 16 : null) === nullValue16, 'null ternary false 16');
check(returnNull(true) === null, 'null return 16');
var nullValue17 = null;
check(nullValue17 === null, 'null strict 17');
check(!(nullValue17 !== null), 'null strict inverse 17');
check(nullValue17 == missingValue, 'null loose undefined 17');
check(!(nullValue17 === missingValue), 'null not undefined 17');
check(typeof nullValue17 === 'object', 'null typeof 17');
check((true ? null : 17) === nullValue17, 'null ternary true 17');
check((false ? 17 : null) === nullValue17, 'null ternary false 17');
check(returnNull(false) === null, 'null return 17');
var nullValue18 = null;
check(nullValue18 === null, 'null strict 18');
check(!(nullValue18 !== null), 'null strict inverse 18');
check(nullValue18 == missingValue, 'null loose undefined 18');
check(!(nullValue18 === missingValue), 'null not undefined 18');
check(typeof nullValue18 === 'object', 'null typeof 18');
check((true ? null : 18) === nullValue18, 'null ternary true 18');
check((false ? 18 : null) === nullValue18, 'null ternary false 18');
check(returnNull(true) === null, 'null return 18');
var nullValue19 = null;
check(nullValue19 === null, 'null strict 19');
check(!(nullValue19 !== null), 'null strict inverse 19');
check(nullValue19 == missingValue, 'null loose undefined 19');
check(!(nullValue19 === missingValue), 'null not undefined 19');
check(typeof nullValue19 === 'object', 'null typeof 19');
check((true ? null : 19) === nullValue19, 'null ternary true 19');
check((false ? 19 : null) === nullValue19, 'null ternary false 19');
check(returnNull(false) === null, 'null return 19');
var nullValue20 = null;
check(nullValue20 === null, 'null strict 20');
check(!(nullValue20 !== null), 'null strict inverse 20');
check(nullValue20 == missingValue, 'null loose undefined 20');
check(!(nullValue20 === missingValue), 'null not undefined 20');
check(typeof nullValue20 === 'object', 'null typeof 20');
check((true ? null : 20) === nullValue20, 'null ternary true 20');
check((false ? 20 : null) === nullValue20, 'null ternary false 20');
check(returnNull(true) === null, 'null return 20');
var nullValue21 = null;
check(nullValue21 === null, 'null strict 21');
check(!(nullValue21 !== null), 'null strict inverse 21');
check(nullValue21 == missingValue, 'null loose undefined 21');
check(!(nullValue21 === missingValue), 'null not undefined 21');
check(typeof nullValue21 === 'object', 'null typeof 21');
check((true ? null : 21) === nullValue21, 'null ternary true 21');
check((false ? 21 : null) === nullValue21, 'null ternary false 21');
check(returnNull(false) === null, 'null return 21');
var nullValue22 = null;
check(nullValue22 === null, 'null strict 22');
check(!(nullValue22 !== null), 'null strict inverse 22');
check(nullValue22 == missingValue, 'null loose undefined 22');
check(!(nullValue22 === missingValue), 'null not undefined 22');
check(typeof nullValue22 === 'object', 'null typeof 22');
check((true ? null : 22) === nullValue22, 'null ternary true 22');
check((false ? 22 : null) === nullValue22, 'null ternary false 22');
check(returnNull(true) === null, 'null return 22');
var nullValue23 = null;
check(nullValue23 === null, 'null strict 23');
check(!(nullValue23 !== null), 'null strict inverse 23');
check(nullValue23 == missingValue, 'null loose undefined 23');
check(!(nullValue23 === missingValue), 'null not undefined 23');
check(typeof nullValue23 === 'object', 'null typeof 23');
check((true ? null : 23) === nullValue23, 'null ternary true 23');
check((false ? 23 : null) === nullValue23, 'null ternary false 23');
check(returnNull(false) === null, 'null return 23');
var nullValue24 = null;
check(nullValue24 === null, 'null strict 24');
check(!(nullValue24 !== null), 'null strict inverse 24');
check(nullValue24 == missingValue, 'null loose undefined 24');
check(!(nullValue24 === missingValue), 'null not undefined 24');
check(typeof nullValue24 === 'object', 'null typeof 24');
check((true ? null : 24) === nullValue24, 'null ternary true 24');
check((false ? 24 : null) === nullValue24, 'null ternary false 24');
check(returnNull(true) === null, 'null return 24');
var nullValue25 = null;
check(nullValue25 === null, 'null strict 25');
check(!(nullValue25 !== null), 'null strict inverse 25');
check(nullValue25 == missingValue, 'null loose undefined 25');
check(!(nullValue25 === missingValue), 'null not undefined 25');
check(typeof nullValue25 === 'object', 'null typeof 25');
check((true ? null : 25) === nullValue25, 'null ternary true 25');
check((false ? 25 : null) === nullValue25, 'null ternary false 25');
check(returnNull(false) === null, 'null return 25');
var nullValue26 = null;
check(nullValue26 === null, 'null strict 26');
check(!(nullValue26 !== null), 'null strict inverse 26');
check(nullValue26 == missingValue, 'null loose undefined 26');
check(!(nullValue26 === missingValue), 'null not undefined 26');
check(typeof nullValue26 === 'object', 'null typeof 26');
check((true ? null : 26) === nullValue26, 'null ternary true 26');
check((false ? 26 : null) === nullValue26, 'null ternary false 26');
check(returnNull(true) === null, 'null return 26');
var nullValue27 = null;
check(nullValue27 === null, 'null strict 27');
check(!(nullValue27 !== null), 'null strict inverse 27');
check(nullValue27 == missingValue, 'null loose undefined 27');
check(!(nullValue27 === missingValue), 'null not undefined 27');
check(typeof nullValue27 === 'object', 'null typeof 27');
check((true ? null : 27) === nullValue27, 'null ternary true 27');
check((false ? 27 : null) === nullValue27, 'null ternary false 27');
check(returnNull(false) === null, 'null return 27');
var nullValue28 = null;
check(nullValue28 === null, 'null strict 28');
check(!(nullValue28 !== null), 'null strict inverse 28');
check(nullValue28 == missingValue, 'null loose undefined 28');
check(!(nullValue28 === missingValue), 'null not undefined 28');
check(typeof nullValue28 === 'object', 'null typeof 28');
check((true ? null : 28) === nullValue28, 'null ternary true 28');
check((false ? 28 : null) === nullValue28, 'null ternary false 28');
check(returnNull(true) === null, 'null return 28');
var nullValue29 = null;
check(nullValue29 === null, 'null strict 29');
check(!(nullValue29 !== null), 'null strict inverse 29');
check(nullValue29 == missingValue, 'null loose undefined 29');
check(!(nullValue29 === missingValue), 'null not undefined 29');
check(typeof nullValue29 === 'object', 'null typeof 29');
check((true ? null : 29) === nullValue29, 'null ternary true 29');
check((false ? 29 : null) === nullValue29, 'null ternary false 29');
check(returnNull(false) === null, 'null return 29');
var nullValue30 = null;
check(nullValue30 === null, 'null strict 30');
check(!(nullValue30 !== null), 'null strict inverse 30');
check(nullValue30 == missingValue, 'null loose undefined 30');
check(!(nullValue30 === missingValue), 'null not undefined 30');
check(typeof nullValue30 === 'object', 'null typeof 30');
check((true ? null : 30) === nullValue30, 'null ternary true 30');
check((false ? 30 : null) === nullValue30, 'null ternary false 30');
check(returnNull(true) === null, 'null return 30');
var nullValue31 = null;
check(nullValue31 === null, 'null strict 31');
check(!(nullValue31 !== null), 'null strict inverse 31');
check(nullValue31 == missingValue, 'null loose undefined 31');
check(!(nullValue31 === missingValue), 'null not undefined 31');
check(typeof nullValue31 === 'object', 'null typeof 31');
check((true ? null : 31) === nullValue31, 'null ternary true 31');
check((false ? 31 : null) === nullValue31, 'null ternary false 31');
check(returnNull(false) === null, 'null return 31');
var nullValue32 = null;
check(nullValue32 === null, 'null strict 32');
check(!(nullValue32 !== null), 'null strict inverse 32');
check(nullValue32 == missingValue, 'null loose undefined 32');
check(!(nullValue32 === missingValue), 'null not undefined 32');
check(typeof nullValue32 === 'object', 'null typeof 32');
check((true ? null : 32) === nullValue32, 'null ternary true 32');
check((false ? 32 : null) === nullValue32, 'null ternary false 32');
check(returnNull(true) === null, 'null return 32');
var nullValue33 = null;
check(nullValue33 === null, 'null strict 33');
check(!(nullValue33 !== null), 'null strict inverse 33');
check(nullValue33 == missingValue, 'null loose undefined 33');
check(!(nullValue33 === missingValue), 'null not undefined 33');
check(typeof nullValue33 === 'object', 'null typeof 33');
check((true ? null : 33) === nullValue33, 'null ternary true 33');
check((false ? 33 : null) === nullValue33, 'null ternary false 33');
check(returnNull(false) === null, 'null return 33');
var nullValue34 = null;
check(nullValue34 === null, 'null strict 34');
check(!(nullValue34 !== null), 'null strict inverse 34');
check(nullValue34 == missingValue, 'null loose undefined 34');
check(!(nullValue34 === missingValue), 'null not undefined 34');
check(typeof nullValue34 === 'object', 'null typeof 34');
check((true ? null : 34) === nullValue34, 'null ternary true 34');
check((false ? 34 : null) === nullValue34, 'null ternary false 34');
check(returnNull(true) === null, 'null return 34');
var nullValue35 = null;
check(nullValue35 === null, 'null strict 35');
check(!(nullValue35 !== null), 'null strict inverse 35');
check(nullValue35 == missingValue, 'null loose undefined 35');
check(!(nullValue35 === missingValue), 'null not undefined 35');
check(typeof nullValue35 === 'object', 'null typeof 35');
check((true ? null : 35) === nullValue35, 'null ternary true 35');
check((false ? 35 : null) === nullValue35, 'null ternary false 35');
check(returnNull(false) === null, 'null return 35');
var nullValue36 = null;
check(nullValue36 === null, 'null strict 36');
check(!(nullValue36 !== null), 'null strict inverse 36');
check(nullValue36 == missingValue, 'null loose undefined 36');
check(!(nullValue36 === missingValue), 'null not undefined 36');
check(typeof nullValue36 === 'object', 'null typeof 36');
check((true ? null : 36) === nullValue36, 'null ternary true 36');
check((false ? 36 : null) === nullValue36, 'null ternary false 36');
check(returnNull(true) === null, 'null return 36');
var nullValue37 = null;
check(nullValue37 === null, 'null strict 37');
check(!(nullValue37 !== null), 'null strict inverse 37');
check(nullValue37 == missingValue, 'null loose undefined 37');
check(!(nullValue37 === missingValue), 'null not undefined 37');
check(typeof nullValue37 === 'object', 'null typeof 37');
check((true ? null : 37) === nullValue37, 'null ternary true 37');
check((false ? 37 : null) === nullValue37, 'null ternary false 37');
check(returnNull(false) === null, 'null return 37');
var nullValue38 = null;
check(nullValue38 === null, 'null strict 38');
check(!(nullValue38 !== null), 'null strict inverse 38');
check(nullValue38 == missingValue, 'null loose undefined 38');
check(!(nullValue38 === missingValue), 'null not undefined 38');
check(typeof nullValue38 === 'object', 'null typeof 38');
check((true ? null : 38) === nullValue38, 'null ternary true 38');
check((false ? 38 : null) === nullValue38, 'null ternary false 38');
check(returnNull(true) === null, 'null return 38');
var nullValue39 = null;
check(nullValue39 === null, 'null strict 39');
check(!(nullValue39 !== null), 'null strict inverse 39');
check(nullValue39 == missingValue, 'null loose undefined 39');
check(!(nullValue39 === missingValue), 'null not undefined 39');
check(typeof nullValue39 === 'object', 'null typeof 39');
check((true ? null : 39) === nullValue39, 'null ternary true 39');
check((false ? 39 : null) === nullValue39, 'null ternary false 39');
check(returnNull(false) === null, 'null return 39');
var nullValue40 = null;
check(nullValue40 === null, 'null strict 40');
check(!(nullValue40 !== null), 'null strict inverse 40');
check(nullValue40 == missingValue, 'null loose undefined 40');
check(!(nullValue40 === missingValue), 'null not undefined 40');
check(typeof nullValue40 === 'object', 'null typeof 40');
check((true ? null : 40) === nullValue40, 'null ternary true 40');
check((false ? 40 : null) === nullValue40, 'null ternary false 40');
check(returnNull(true) === null, 'null return 40');
var nullValue41 = null;
check(nullValue41 === null, 'null strict 41');
check(!(nullValue41 !== null), 'null strict inverse 41');
check(nullValue41 == missingValue, 'null loose undefined 41');
check(!(nullValue41 === missingValue), 'null not undefined 41');
check(typeof nullValue41 === 'object', 'null typeof 41');
check((true ? null : 41) === nullValue41, 'null ternary true 41');
check((false ? 41 : null) === nullValue41, 'null ternary false 41');
check(returnNull(false) === null, 'null return 41');
var nullValue42 = null;
check(nullValue42 === null, 'null strict 42');
check(!(nullValue42 !== null), 'null strict inverse 42');
check(nullValue42 == missingValue, 'null loose undefined 42');
check(!(nullValue42 === missingValue), 'null not undefined 42');
check(typeof nullValue42 === 'object', 'null typeof 42');
check((true ? null : 42) === nullValue42, 'null ternary true 42');
check((false ? 42 : null) === nullValue42, 'null ternary false 42');
check(returnNull(true) === null, 'null return 42');
var nullValue43 = null;
check(nullValue43 === null, 'null strict 43');
check(!(nullValue43 !== null), 'null strict inverse 43');
check(nullValue43 == missingValue, 'null loose undefined 43');
check(!(nullValue43 === missingValue), 'null not undefined 43');
check(typeof nullValue43 === 'object', 'null typeof 43');
check((true ? null : 43) === nullValue43, 'null ternary true 43');
check((false ? 43 : null) === nullValue43, 'null ternary false 43');
check(returnNull(false) === null, 'null return 43');
var nullValue44 = null;
check(nullValue44 === null, 'null strict 44');
check(!(nullValue44 !== null), 'null strict inverse 44');
check(nullValue44 == missingValue, 'null loose undefined 44');
check(!(nullValue44 === missingValue), 'null not undefined 44');
check(typeof nullValue44 === 'object', 'null typeof 44');
check((true ? null : 44) === nullValue44, 'null ternary true 44');
check((false ? 44 : null) === nullValue44, 'null ternary false 44');
check(returnNull(true) === null, 'null return 44');
var nullValue45 = null;
check(nullValue45 === null, 'null strict 45');
check(!(nullValue45 !== null), 'null strict inverse 45');
check(nullValue45 == missingValue, 'null loose undefined 45');
check(!(nullValue45 === missingValue), 'null not undefined 45');
check(typeof nullValue45 === 'object', 'null typeof 45');
check((true ? null : 45) === nullValue45, 'null ternary true 45');
check((false ? 45 : null) === nullValue45, 'null ternary false 45');
check(returnNull(false) === null, 'null return 45');
var nullValue46 = null;
check(nullValue46 === null, 'null strict 46');
check(!(nullValue46 !== null), 'null strict inverse 46');
check(nullValue46 == missingValue, 'null loose undefined 46');
check(!(nullValue46 === missingValue), 'null not undefined 46');
check(typeof nullValue46 === 'object', 'null typeof 46');
check((true ? null : 46) === nullValue46, 'null ternary true 46');
check((false ? 46 : null) === nullValue46, 'null ternary false 46');
check(returnNull(true) === null, 'null return 46');
var nullValue47 = null;
check(nullValue47 === null, 'null strict 47');
check(!(nullValue47 !== null), 'null strict inverse 47');
check(nullValue47 == missingValue, 'null loose undefined 47');
check(!(nullValue47 === missingValue), 'null not undefined 47');
check(typeof nullValue47 === 'object', 'null typeof 47');
check((true ? null : 47) === nullValue47, 'null ternary true 47');
check((false ? 47 : null) === nullValue47, 'null ternary false 47');
check(returnNull(false) === null, 'null return 47');
var nullValue48 = null;
check(nullValue48 === null, 'null strict 48');
check(!(nullValue48 !== null), 'null strict inverse 48');
check(nullValue48 == missingValue, 'null loose undefined 48');
check(!(nullValue48 === missingValue), 'null not undefined 48');
check(typeof nullValue48 === 'object', 'null typeof 48');
check((true ? null : 48) === nullValue48, 'null ternary true 48');
check((false ? 48 : null) === nullValue48, 'null ternary false 48');
check(returnNull(true) === null, 'null return 48');
var nullValue49 = null;
check(nullValue49 === null, 'null strict 49');
check(!(nullValue49 !== null), 'null strict inverse 49');
check(nullValue49 == missingValue, 'null loose undefined 49');
check(!(nullValue49 === missingValue), 'null not undefined 49');
check(typeof nullValue49 === 'object', 'null typeof 49');
check((true ? null : 49) === nullValue49, 'null ternary true 49');
check((false ? 49 : null) === nullValue49, 'null ternary false 49');
check(returnNull(false) === null, 'null return 49');
var nullValue50 = null;
check(nullValue50 === null, 'null strict 50');
check(!(nullValue50 !== null), 'null strict inverse 50');
check(nullValue50 == missingValue, 'null loose undefined 50');
check(!(nullValue50 === missingValue), 'null not undefined 50');
check(typeof nullValue50 === 'object', 'null typeof 50');
check((true ? null : 50) === nullValue50, 'null ternary true 50');
check((false ? 50 : null) === nullValue50, 'null ternary false 50');
check(returnNull(true) === null, 'null return 50');
var nullValue51 = null;
check(nullValue51 === null, 'null strict 51');
check(!(nullValue51 !== null), 'null strict inverse 51');
check(nullValue51 == missingValue, 'null loose undefined 51');
check(!(nullValue51 === missingValue), 'null not undefined 51');
check(typeof nullValue51 === 'object', 'null typeof 51');
check((true ? null : 51) === nullValue51, 'null ternary true 51');
check((false ? 51 : null) === nullValue51, 'null ternary false 51');
check(returnNull(false) === null, 'null return 51');
var nullValue52 = null;
check(nullValue52 === null, 'null strict 52');
check(!(nullValue52 !== null), 'null strict inverse 52');
check(nullValue52 == missingValue, 'null loose undefined 52');
check(!(nullValue52 === missingValue), 'null not undefined 52');
check(typeof nullValue52 === 'object', 'null typeof 52');
check((true ? null : 52) === nullValue52, 'null ternary true 52');
check((false ? 52 : null) === nullValue52, 'null ternary false 52');
check(returnNull(true) === null, 'null return 52');
var nullValue53 = null;
check(nullValue53 === null, 'null strict 53');
check(!(nullValue53 !== null), 'null strict inverse 53');
check(nullValue53 == missingValue, 'null loose undefined 53');
check(!(nullValue53 === missingValue), 'null not undefined 53');
check(typeof nullValue53 === 'object', 'null typeof 53');
check((true ? null : 53) === nullValue53, 'null ternary true 53');
check((false ? 53 : null) === nullValue53, 'null ternary false 53');
check(returnNull(false) === null, 'null return 53');
var nullValue54 = null;
check(nullValue54 === null, 'null strict 54');
check(!(nullValue54 !== null), 'null strict inverse 54');
check(nullValue54 == missingValue, 'null loose undefined 54');
check(!(nullValue54 === missingValue), 'null not undefined 54');
check(typeof nullValue54 === 'object', 'null typeof 54');
check((true ? null : 54) === nullValue54, 'null ternary true 54');
check((false ? 54 : null) === nullValue54, 'null ternary false 54');
check(returnNull(true) === null, 'null return 54');
var nullValue55 = null;
check(nullValue55 === null, 'null strict 55');
check(!(nullValue55 !== null), 'null strict inverse 55');
check(nullValue55 == missingValue, 'null loose undefined 55');
check(!(nullValue55 === missingValue), 'null not undefined 55');
check(typeof nullValue55 === 'object', 'null typeof 55');
check((true ? null : 55) === nullValue55, 'null ternary true 55');
check((false ? 55 : null) === nullValue55, 'null ternary false 55');
check(returnNull(false) === null, 'null return 55');
console.log('null-literal-evaluates-null large ' + score);
