// behavior: null-literal-evaluates-null
// expected: pass
// goal: script
// size: stress
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}
var missingValue = undefined;
function returnNull(value) { if (value) { return null; } return null; }
var nullValue0 = null;
check(nullValue0 === null, 'null strict 0');
check(!(nullValue0 !== null), 'null strict inverse 0');
check(nullValue0 == missingValue, 'null loose undefined 0');
check(!(nullValue0 === missingValue), 'null not undefined 0');
check(typeof nullValue0 === 'object', 'null typeof 0');
check((true ? null : 0) === nullValue0, 'null ternary true 0');
check((false ? 0 : null) === nullValue0, 'null ternary false 0');
check(returnNull(true) === null, 'null return 0');
var nullValue1 = null;
check(nullValue1 === null, 'null strict 1');
check(!(nullValue1 !== null), 'null strict inverse 1');
check(nullValue1 == missingValue, 'null loose undefined 1');
check(!(nullValue1 === missingValue), 'null not undefined 1');
check(typeof nullValue1 === 'object', 'null typeof 1');
check((true ? null : 1) === nullValue1, 'null ternary true 1');
check((false ? 1 : null) === nullValue1, 'null ternary false 1');
check(returnNull(false) === null, 'null return 1');
var nullValue2 = null;
check(nullValue2 === null, 'null strict 2');
check(!(nullValue2 !== null), 'null strict inverse 2');
check(nullValue2 == missingValue, 'null loose undefined 2');
check(!(nullValue2 === missingValue), 'null not undefined 2');
check(typeof nullValue2 === 'object', 'null typeof 2');
check((true ? null : 2) === nullValue2, 'null ternary true 2');
check((false ? 2 : null) === nullValue2, 'null ternary false 2');
check(returnNull(true) === null, 'null return 2');
var nullValue3 = null;
check(nullValue3 === null, 'null strict 3');
check(!(nullValue3 !== null), 'null strict inverse 3');
check(nullValue3 == missingValue, 'null loose undefined 3');
check(!(nullValue3 === missingValue), 'null not undefined 3');
check(typeof nullValue3 === 'object', 'null typeof 3');
check((true ? null : 3) === nullValue3, 'null ternary true 3');
check((false ? 3 : null) === nullValue3, 'null ternary false 3');
check(returnNull(false) === null, 'null return 3');
var nullValue4 = null;
check(nullValue4 === null, 'null strict 4');
check(!(nullValue4 !== null), 'null strict inverse 4');
check(nullValue4 == missingValue, 'null loose undefined 4');
check(!(nullValue4 === missingValue), 'null not undefined 4');
check(typeof nullValue4 === 'object', 'null typeof 4');
check((true ? null : 4) === nullValue4, 'null ternary true 4');
check((false ? 4 : null) === nullValue4, 'null ternary false 4');
check(returnNull(true) === null, 'null return 4');
var nullValue5 = null;
check(nullValue5 === null, 'null strict 5');
check(!(nullValue5 !== null), 'null strict inverse 5');
check(nullValue5 == missingValue, 'null loose undefined 5');
check(!(nullValue5 === missingValue), 'null not undefined 5');
check(typeof nullValue5 === 'object', 'null typeof 5');
check((true ? null : 5) === nullValue5, 'null ternary true 5');
check((false ? 5 : null) === nullValue5, 'null ternary false 5');
check(returnNull(false) === null, 'null return 5');
var nullValue6 = null;
check(nullValue6 === null, 'null strict 6');
check(!(nullValue6 !== null), 'null strict inverse 6');
check(nullValue6 == missingValue, 'null loose undefined 6');
check(!(nullValue6 === missingValue), 'null not undefined 6');
check(typeof nullValue6 === 'object', 'null typeof 6');
check((true ? null : 6) === nullValue6, 'null ternary true 6');
check((false ? 6 : null) === nullValue6, 'null ternary false 6');
check(returnNull(true) === null, 'null return 6');
var nullValue7 = null;
check(nullValue7 === null, 'null strict 7');
check(!(nullValue7 !== null), 'null strict inverse 7');
check(nullValue7 == missingValue, 'null loose undefined 7');
check(!(nullValue7 === missingValue), 'null not undefined 7');
check(typeof nullValue7 === 'object', 'null typeof 7');
check((true ? null : 7) === nullValue7, 'null ternary true 7');
check((false ? 7 : null) === nullValue7, 'null ternary false 7');
check(returnNull(false) === null, 'null return 7');
var nullValue8 = null;
check(nullValue8 === null, 'null strict 8');
check(!(nullValue8 !== null), 'null strict inverse 8');
check(nullValue8 == missingValue, 'null loose undefined 8');
check(!(nullValue8 === missingValue), 'null not undefined 8');
check(typeof nullValue8 === 'object', 'null typeof 8');
check((true ? null : 8) === nullValue8, 'null ternary true 8');
check((false ? 8 : null) === nullValue8, 'null ternary false 8');
check(returnNull(true) === null, 'null return 8');
var nullValue9 = null;
check(nullValue9 === null, 'null strict 9');
check(!(nullValue9 !== null), 'null strict inverse 9');
check(nullValue9 == missingValue, 'null loose undefined 9');
check(!(nullValue9 === missingValue), 'null not undefined 9');
check(typeof nullValue9 === 'object', 'null typeof 9');
check((true ? null : 9) === nullValue9, 'null ternary true 9');
check((false ? 9 : null) === nullValue9, 'null ternary false 9');
check(returnNull(false) === null, 'null return 9');
var nullValue10 = null;
check(nullValue10 === null, 'null strict 10');
check(!(nullValue10 !== null), 'null strict inverse 10');
check(nullValue10 == missingValue, 'null loose undefined 10');
check(!(nullValue10 === missingValue), 'null not undefined 10');
check(typeof nullValue10 === 'object', 'null typeof 10');
check((true ? null : 10) === nullValue10, 'null ternary true 10');
check((false ? 10 : null) === nullValue10, 'null ternary false 10');
check(returnNull(true) === null, 'null return 10');
var nullValue11 = null;
check(nullValue11 === null, 'null strict 11');
check(!(nullValue11 !== null), 'null strict inverse 11');
check(nullValue11 == missingValue, 'null loose undefined 11');
check(!(nullValue11 === missingValue), 'null not undefined 11');
check(typeof nullValue11 === 'object', 'null typeof 11');
check((true ? null : 11) === nullValue11, 'null ternary true 11');
check((false ? 11 : null) === nullValue11, 'null ternary false 11');
check(returnNull(false) === null, 'null return 11');
var nullValue12 = null;
check(nullValue12 === null, 'null strict 12');
check(!(nullValue12 !== null), 'null strict inverse 12');
check(nullValue12 == missingValue, 'null loose undefined 12');
check(!(nullValue12 === missingValue), 'null not undefined 12');
check(typeof nullValue12 === 'object', 'null typeof 12');
check((true ? null : 12) === nullValue12, 'null ternary true 12');
check((false ? 12 : null) === nullValue12, 'null ternary false 12');
check(returnNull(true) === null, 'null return 12');
var nullValue13 = null;
check(nullValue13 === null, 'null strict 13');
check(!(nullValue13 !== null), 'null strict inverse 13');
check(nullValue13 == missingValue, 'null loose undefined 13');
check(!(nullValue13 === missingValue), 'null not undefined 13');
check(typeof nullValue13 === 'object', 'null typeof 13');
check((true ? null : 13) === nullValue13, 'null ternary true 13');
check((false ? 13 : null) === nullValue13, 'null ternary false 13');
check(returnNull(false) === null, 'null return 13');
var nullValue14 = null;
check(nullValue14 === null, 'null strict 14');
check(!(nullValue14 !== null), 'null strict inverse 14');
check(nullValue14 == missingValue, 'null loose undefined 14');
check(!(nullValue14 === missingValue), 'null not undefined 14');
check(typeof nullValue14 === 'object', 'null typeof 14');
check((true ? null : 14) === nullValue14, 'null ternary true 14');
check((false ? 14 : null) === nullValue14, 'null ternary false 14');
check(returnNull(true) === null, 'null return 14');
var nullValue15 = null;
check(nullValue15 === null, 'null strict 15');
check(!(nullValue15 !== null), 'null strict inverse 15');
check(nullValue15 == missingValue, 'null loose undefined 15');
check(!(nullValue15 === missingValue), 'null not undefined 15');
check(typeof nullValue15 === 'object', 'null typeof 15');
check((true ? null : 15) === nullValue15, 'null ternary true 15');
check((false ? 15 : null) === nullValue15, 'null ternary false 15');
check(returnNull(false) === null, 'null return 15');
var nullValue16 = null;
check(nullValue16 === null, 'null strict 16');
check(!(nullValue16 !== null), 'null strict inverse 16');
check(nullValue16 == missingValue, 'null loose undefined 16');
check(!(nullValue16 === missingValue), 'null not undefined 16');
check(typeof nullValue16 === 'object', 'null typeof 16');
check((true ? null : 16) === nullValue16, 'null ternary true 16');
check((false ? 16 : null) === nullValue16, 'null ternary false 16');
check(returnNull(true) === null, 'null return 16');
var nullValue17 = null;
check(nullValue17 === null, 'null strict 17');
check(!(nullValue17 !== null), 'null strict inverse 17');
check(nullValue17 == missingValue, 'null loose undefined 17');
check(!(nullValue17 === missingValue), 'null not undefined 17');
check(typeof nullValue17 === 'object', 'null typeof 17');
check((true ? null : 17) === nullValue17, 'null ternary true 17');
check((false ? 17 : null) === nullValue17, 'null ternary false 17');
check(returnNull(false) === null, 'null return 17');
var nullValue18 = null;
check(nullValue18 === null, 'null strict 18');
check(!(nullValue18 !== null), 'null strict inverse 18');
check(nullValue18 == missingValue, 'null loose undefined 18');
check(!(nullValue18 === missingValue), 'null not undefined 18');
check(typeof nullValue18 === 'object', 'null typeof 18');
check((true ? null : 18) === nullValue18, 'null ternary true 18');
check((false ? 18 : null) === nullValue18, 'null ternary false 18');
check(returnNull(true) === null, 'null return 18');
var nullValue19 = null;
check(nullValue19 === null, 'null strict 19');
check(!(nullValue19 !== null), 'null strict inverse 19');
check(nullValue19 == missingValue, 'null loose undefined 19');
check(!(nullValue19 === missingValue), 'null not undefined 19');
check(typeof nullValue19 === 'object', 'null typeof 19');
check((true ? null : 19) === nullValue19, 'null ternary true 19');
check((false ? 19 : null) === nullValue19, 'null ternary false 19');
check(returnNull(false) === null, 'null return 19');
var nullValue20 = null;
check(nullValue20 === null, 'null strict 20');
check(!(nullValue20 !== null), 'null strict inverse 20');
check(nullValue20 == missingValue, 'null loose undefined 20');
check(!(nullValue20 === missingValue), 'null not undefined 20');
check(typeof nullValue20 === 'object', 'null typeof 20');
check((true ? null : 20) === nullValue20, 'null ternary true 20');
check((false ? 20 : null) === nullValue20, 'null ternary false 20');
check(returnNull(true) === null, 'null return 20');
var nullValue21 = null;
check(nullValue21 === null, 'null strict 21');
check(!(nullValue21 !== null), 'null strict inverse 21');
check(nullValue21 == missingValue, 'null loose undefined 21');
check(!(nullValue21 === missingValue), 'null not undefined 21');
check(typeof nullValue21 === 'object', 'null typeof 21');
check((true ? null : 21) === nullValue21, 'null ternary true 21');
check((false ? 21 : null) === nullValue21, 'null ternary false 21');
check(returnNull(false) === null, 'null return 21');
var nullValue22 = null;
check(nullValue22 === null, 'null strict 22');
check(!(nullValue22 !== null), 'null strict inverse 22');
check(nullValue22 == missingValue, 'null loose undefined 22');
check(!(nullValue22 === missingValue), 'null not undefined 22');
check(typeof nullValue22 === 'object', 'null typeof 22');
check((true ? null : 22) === nullValue22, 'null ternary true 22');
check((false ? 22 : null) === nullValue22, 'null ternary false 22');
check(returnNull(true) === null, 'null return 22');
var nullValue23 = null;
check(nullValue23 === null, 'null strict 23');
check(!(nullValue23 !== null), 'null strict inverse 23');
check(nullValue23 == missingValue, 'null loose undefined 23');
check(!(nullValue23 === missingValue), 'null not undefined 23');
check(typeof nullValue23 === 'object', 'null typeof 23');
check((true ? null : 23) === nullValue23, 'null ternary true 23');
check((false ? 23 : null) === nullValue23, 'null ternary false 23');
check(returnNull(false) === null, 'null return 23');
var nullValue24 = null;
check(nullValue24 === null, 'null strict 24');
check(!(nullValue24 !== null), 'null strict inverse 24');
check(nullValue24 == missingValue, 'null loose undefined 24');
check(!(nullValue24 === missingValue), 'null not undefined 24');
check(typeof nullValue24 === 'object', 'null typeof 24');
check((true ? null : 24) === nullValue24, 'null ternary true 24');
check((false ? 24 : null) === nullValue24, 'null ternary false 24');
check(returnNull(true) === null, 'null return 24');
var nullValue25 = null;
check(nullValue25 === null, 'null strict 25');
check(!(nullValue25 !== null), 'null strict inverse 25');
check(nullValue25 == missingValue, 'null loose undefined 25');
check(!(nullValue25 === missingValue), 'null not undefined 25');
check(typeof nullValue25 === 'object', 'null typeof 25');
check((true ? null : 25) === nullValue25, 'null ternary true 25');
check((false ? 25 : null) === nullValue25, 'null ternary false 25');
check(returnNull(false) === null, 'null return 25');
var nullValue26 = null;
check(nullValue26 === null, 'null strict 26');
check(!(nullValue26 !== null), 'null strict inverse 26');
check(nullValue26 == missingValue, 'null loose undefined 26');
check(!(nullValue26 === missingValue), 'null not undefined 26');
check(typeof nullValue26 === 'object', 'null typeof 26');
check((true ? null : 26) === nullValue26, 'null ternary true 26');
check((false ? 26 : null) === nullValue26, 'null ternary false 26');
check(returnNull(true) === null, 'null return 26');
var nullValue27 = null;
check(nullValue27 === null, 'null strict 27');
check(!(nullValue27 !== null), 'null strict inverse 27');
check(nullValue27 == missingValue, 'null loose undefined 27');
check(!(nullValue27 === missingValue), 'null not undefined 27');
check(typeof nullValue27 === 'object', 'null typeof 27');
check((true ? null : 27) === nullValue27, 'null ternary true 27');
check((false ? 27 : null) === nullValue27, 'null ternary false 27');
check(returnNull(false) === null, 'null return 27');
var nullValue28 = null;
check(nullValue28 === null, 'null strict 28');
check(!(nullValue28 !== null), 'null strict inverse 28');
check(nullValue28 == missingValue, 'null loose undefined 28');
check(!(nullValue28 === missingValue), 'null not undefined 28');
check(typeof nullValue28 === 'object', 'null typeof 28');
check((true ? null : 28) === nullValue28, 'null ternary true 28');
check((false ? 28 : null) === nullValue28, 'null ternary false 28');
check(returnNull(true) === null, 'null return 28');
var nullValue29 = null;
check(nullValue29 === null, 'null strict 29');
check(!(nullValue29 !== null), 'null strict inverse 29');
check(nullValue29 == missingValue, 'null loose undefined 29');
check(!(nullValue29 === missingValue), 'null not undefined 29');
check(typeof nullValue29 === 'object', 'null typeof 29');
check((true ? null : 29) === nullValue29, 'null ternary true 29');
check((false ? 29 : null) === nullValue29, 'null ternary false 29');
check(returnNull(false) === null, 'null return 29');
var nullValue30 = null;
check(nullValue30 === null, 'null strict 30');
check(!(nullValue30 !== null), 'null strict inverse 30');
check(nullValue30 == missingValue, 'null loose undefined 30');
check(!(nullValue30 === missingValue), 'null not undefined 30');
check(typeof nullValue30 === 'object', 'null typeof 30');
check((true ? null : 30) === nullValue30, 'null ternary true 30');
check((false ? 30 : null) === nullValue30, 'null ternary false 30');
check(returnNull(true) === null, 'null return 30');
var nullValue31 = null;
check(nullValue31 === null, 'null strict 31');
check(!(nullValue31 !== null), 'null strict inverse 31');
check(nullValue31 == missingValue, 'null loose undefined 31');
check(!(nullValue31 === missingValue), 'null not undefined 31');
check(typeof nullValue31 === 'object', 'null typeof 31');
check((true ? null : 31) === nullValue31, 'null ternary true 31');
check((false ? 31 : null) === nullValue31, 'null ternary false 31');
check(returnNull(false) === null, 'null return 31');
var nullValue32 = null;
check(nullValue32 === null, 'null strict 32');
check(!(nullValue32 !== null), 'null strict inverse 32');
check(nullValue32 == missingValue, 'null loose undefined 32');
check(!(nullValue32 === missingValue), 'null not undefined 32');
check(typeof nullValue32 === 'object', 'null typeof 32');
check((true ? null : 32) === nullValue32, 'null ternary true 32');
check((false ? 32 : null) === nullValue32, 'null ternary false 32');
check(returnNull(true) === null, 'null return 32');
var nullValue33 = null;
check(nullValue33 === null, 'null strict 33');
check(!(nullValue33 !== null), 'null strict inverse 33');
check(nullValue33 == missingValue, 'null loose undefined 33');
check(!(nullValue33 === missingValue), 'null not undefined 33');
check(typeof nullValue33 === 'object', 'null typeof 33');
check((true ? null : 33) === nullValue33, 'null ternary true 33');
check((false ? 33 : null) === nullValue33, 'null ternary false 33');
check(returnNull(false) === null, 'null return 33');
var nullValue34 = null;
check(nullValue34 === null, 'null strict 34');
check(!(nullValue34 !== null), 'null strict inverse 34');
check(nullValue34 == missingValue, 'null loose undefined 34');
check(!(nullValue34 === missingValue), 'null not undefined 34');
check(typeof nullValue34 === 'object', 'null typeof 34');
check((true ? null : 34) === nullValue34, 'null ternary true 34');
check((false ? 34 : null) === nullValue34, 'null ternary false 34');
check(returnNull(true) === null, 'null return 34');
var nullValue35 = null;
check(nullValue35 === null, 'null strict 35');
check(!(nullValue35 !== null), 'null strict inverse 35');
check(nullValue35 == missingValue, 'null loose undefined 35');
check(!(nullValue35 === missingValue), 'null not undefined 35');
check(typeof nullValue35 === 'object', 'null typeof 35');
check((true ? null : 35) === nullValue35, 'null ternary true 35');
check((false ? 35 : null) === nullValue35, 'null ternary false 35');
check(returnNull(false) === null, 'null return 35');
var nullValue36 = null;
check(nullValue36 === null, 'null strict 36');
check(!(nullValue36 !== null), 'null strict inverse 36');
check(nullValue36 == missingValue, 'null loose undefined 36');
check(!(nullValue36 === missingValue), 'null not undefined 36');
check(typeof nullValue36 === 'object', 'null typeof 36');
check((true ? null : 36) === nullValue36, 'null ternary true 36');
check((false ? 36 : null) === nullValue36, 'null ternary false 36');
check(returnNull(true) === null, 'null return 36');
var nullValue37 = null;
check(nullValue37 === null, 'null strict 37');
check(!(nullValue37 !== null), 'null strict inverse 37');
check(nullValue37 == missingValue, 'null loose undefined 37');
check(!(nullValue37 === missingValue), 'null not undefined 37');
check(typeof nullValue37 === 'object', 'null typeof 37');
check((true ? null : 37) === nullValue37, 'null ternary true 37');
check((false ? 37 : null) === nullValue37, 'null ternary false 37');
check(returnNull(false) === null, 'null return 37');
var nullValue38 = null;
check(nullValue38 === null, 'null strict 38');
check(!(nullValue38 !== null), 'null strict inverse 38');
check(nullValue38 == missingValue, 'null loose undefined 38');
check(!(nullValue38 === missingValue), 'null not undefined 38');
check(typeof nullValue38 === 'object', 'null typeof 38');
check((true ? null : 38) === nullValue38, 'null ternary true 38');
check((false ? 38 : null) === nullValue38, 'null ternary false 38');
check(returnNull(true) === null, 'null return 38');
var nullValue39 = null;
check(nullValue39 === null, 'null strict 39');
check(!(nullValue39 !== null), 'null strict inverse 39');
check(nullValue39 == missingValue, 'null loose undefined 39');
check(!(nullValue39 === missingValue), 'null not undefined 39');
check(typeof nullValue39 === 'object', 'null typeof 39');
check((true ? null : 39) === nullValue39, 'null ternary true 39');
check((false ? 39 : null) === nullValue39, 'null ternary false 39');
check(returnNull(false) === null, 'null return 39');
var nullValue40 = null;
check(nullValue40 === null, 'null strict 40');
check(!(nullValue40 !== null), 'null strict inverse 40');
check(nullValue40 == missingValue, 'null loose undefined 40');
check(!(nullValue40 === missingValue), 'null not undefined 40');
check(typeof nullValue40 === 'object', 'null typeof 40');
check((true ? null : 40) === nullValue40, 'null ternary true 40');
check((false ? 40 : null) === nullValue40, 'null ternary false 40');
check(returnNull(true) === null, 'null return 40');
var nullValue41 = null;
check(nullValue41 === null, 'null strict 41');
check(!(nullValue41 !== null), 'null strict inverse 41');
check(nullValue41 == missingValue, 'null loose undefined 41');
check(!(nullValue41 === missingValue), 'null not undefined 41');
check(typeof nullValue41 === 'object', 'null typeof 41');
check((true ? null : 41) === nullValue41, 'null ternary true 41');
check((false ? 41 : null) === nullValue41, 'null ternary false 41');
check(returnNull(false) === null, 'null return 41');
var nullValue42 = null;
check(nullValue42 === null, 'null strict 42');
check(!(nullValue42 !== null), 'null strict inverse 42');
check(nullValue42 == missingValue, 'null loose undefined 42');
check(!(nullValue42 === missingValue), 'null not undefined 42');
check(typeof nullValue42 === 'object', 'null typeof 42');
check((true ? null : 42) === nullValue42, 'null ternary true 42');
check((false ? 42 : null) === nullValue42, 'null ternary false 42');
check(returnNull(true) === null, 'null return 42');
var nullValue43 = null;
check(nullValue43 === null, 'null strict 43');
check(!(nullValue43 !== null), 'null strict inverse 43');
check(nullValue43 == missingValue, 'null loose undefined 43');
check(!(nullValue43 === missingValue), 'null not undefined 43');
check(typeof nullValue43 === 'object', 'null typeof 43');
check((true ? null : 43) === nullValue43, 'null ternary true 43');
check((false ? 43 : null) === nullValue43, 'null ternary false 43');
check(returnNull(false) === null, 'null return 43');
var nullValue44 = null;
check(nullValue44 === null, 'null strict 44');
check(!(nullValue44 !== null), 'null strict inverse 44');
check(nullValue44 == missingValue, 'null loose undefined 44');
check(!(nullValue44 === missingValue), 'null not undefined 44');
check(typeof nullValue44 === 'object', 'null typeof 44');
check((true ? null : 44) === nullValue44, 'null ternary true 44');
check((false ? 44 : null) === nullValue44, 'null ternary false 44');
check(returnNull(true) === null, 'null return 44');
var nullValue45 = null;
check(nullValue45 === null, 'null strict 45');
check(!(nullValue45 !== null), 'null strict inverse 45');
check(nullValue45 == missingValue, 'null loose undefined 45');
check(!(nullValue45 === missingValue), 'null not undefined 45');
check(typeof nullValue45 === 'object', 'null typeof 45');
check((true ? null : 45) === nullValue45, 'null ternary true 45');
check((false ? 45 : null) === nullValue45, 'null ternary false 45');
check(returnNull(false) === null, 'null return 45');
var nullValue46 = null;
check(nullValue46 === null, 'null strict 46');
check(!(nullValue46 !== null), 'null strict inverse 46');
check(nullValue46 == missingValue, 'null loose undefined 46');
check(!(nullValue46 === missingValue), 'null not undefined 46');
check(typeof nullValue46 === 'object', 'null typeof 46');
check((true ? null : 46) === nullValue46, 'null ternary true 46');
check((false ? 46 : null) === nullValue46, 'null ternary false 46');
check(returnNull(true) === null, 'null return 46');
var nullValue47 = null;
check(nullValue47 === null, 'null strict 47');
check(!(nullValue47 !== null), 'null strict inverse 47');
check(nullValue47 == missingValue, 'null loose undefined 47');
check(!(nullValue47 === missingValue), 'null not undefined 47');
check(typeof nullValue47 === 'object', 'null typeof 47');
check((true ? null : 47) === nullValue47, 'null ternary true 47');
check((false ? 47 : null) === nullValue47, 'null ternary false 47');
check(returnNull(false) === null, 'null return 47');
var nullValue48 = null;
check(nullValue48 === null, 'null strict 48');
check(!(nullValue48 !== null), 'null strict inverse 48');
check(nullValue48 == missingValue, 'null loose undefined 48');
check(!(nullValue48 === missingValue), 'null not undefined 48');
check(typeof nullValue48 === 'object', 'null typeof 48');
check((true ? null : 48) === nullValue48, 'null ternary true 48');
check((false ? 48 : null) === nullValue48, 'null ternary false 48');
check(returnNull(true) === null, 'null return 48');
var nullValue49 = null;
check(nullValue49 === null, 'null strict 49');
check(!(nullValue49 !== null), 'null strict inverse 49');
check(nullValue49 == missingValue, 'null loose undefined 49');
check(!(nullValue49 === missingValue), 'null not undefined 49');
check(typeof nullValue49 === 'object', 'null typeof 49');
check((true ? null : 49) === nullValue49, 'null ternary true 49');
check((false ? 49 : null) === nullValue49, 'null ternary false 49');
check(returnNull(false) === null, 'null return 49');
var nullValue50 = null;
check(nullValue50 === null, 'null strict 50');
check(!(nullValue50 !== null), 'null strict inverse 50');
check(nullValue50 == missingValue, 'null loose undefined 50');
check(!(nullValue50 === missingValue), 'null not undefined 50');
check(typeof nullValue50 === 'object', 'null typeof 50');
check((true ? null : 50) === nullValue50, 'null ternary true 50');
check((false ? 50 : null) === nullValue50, 'null ternary false 50');
check(returnNull(true) === null, 'null return 50');
var nullValue51 = null;
check(nullValue51 === null, 'null strict 51');
check(!(nullValue51 !== null), 'null strict inverse 51');
check(nullValue51 == missingValue, 'null loose undefined 51');
check(!(nullValue51 === missingValue), 'null not undefined 51');
check(typeof nullValue51 === 'object', 'null typeof 51');
check((true ? null : 51) === nullValue51, 'null ternary true 51');
check((false ? 51 : null) === nullValue51, 'null ternary false 51');
check(returnNull(false) === null, 'null return 51');
var nullValue52 = null;
check(nullValue52 === null, 'null strict 52');
check(!(nullValue52 !== null), 'null strict inverse 52');
check(nullValue52 == missingValue, 'null loose undefined 52');
check(!(nullValue52 === missingValue), 'null not undefined 52');
check(typeof nullValue52 === 'object', 'null typeof 52');
check((true ? null : 52) === nullValue52, 'null ternary true 52');
check((false ? 52 : null) === nullValue52, 'null ternary false 52');
check(returnNull(true) === null, 'null return 52');
var nullValue53 = null;
check(nullValue53 === null, 'null strict 53');
check(!(nullValue53 !== null), 'null strict inverse 53');
check(nullValue53 == missingValue, 'null loose undefined 53');
check(!(nullValue53 === missingValue), 'null not undefined 53');
check(typeof nullValue53 === 'object', 'null typeof 53');
check((true ? null : 53) === nullValue53, 'null ternary true 53');
check((false ? 53 : null) === nullValue53, 'null ternary false 53');
check(returnNull(false) === null, 'null return 53');
var nullValue54 = null;
check(nullValue54 === null, 'null strict 54');
check(!(nullValue54 !== null), 'null strict inverse 54');
check(nullValue54 == missingValue, 'null loose undefined 54');
check(!(nullValue54 === missingValue), 'null not undefined 54');
check(typeof nullValue54 === 'object', 'null typeof 54');
check((true ? null : 54) === nullValue54, 'null ternary true 54');
check((false ? 54 : null) === nullValue54, 'null ternary false 54');
check(returnNull(true) === null, 'null return 54');
var nullValue55 = null;
check(nullValue55 === null, 'null strict 55');
check(!(nullValue55 !== null), 'null strict inverse 55');
check(nullValue55 == missingValue, 'null loose undefined 55');
check(!(nullValue55 === missingValue), 'null not undefined 55');
check(typeof nullValue55 === 'object', 'null typeof 55');
check((true ? null : 55) === nullValue55, 'null ternary true 55');
check((false ? 55 : null) === nullValue55, 'null ternary false 55');
check(returnNull(false) === null, 'null return 55');
var nullValue56 = null;
check(nullValue56 === null, 'null strict 56');
check(!(nullValue56 !== null), 'null strict inverse 56');
check(nullValue56 == missingValue, 'null loose undefined 56');
check(!(nullValue56 === missingValue), 'null not undefined 56');
check(typeof nullValue56 === 'object', 'null typeof 56');
check((true ? null : 56) === nullValue56, 'null ternary true 56');
check((false ? 56 : null) === nullValue56, 'null ternary false 56');
check(returnNull(true) === null, 'null return 56');
var nullValue57 = null;
check(nullValue57 === null, 'null strict 57');
check(!(nullValue57 !== null), 'null strict inverse 57');
check(nullValue57 == missingValue, 'null loose undefined 57');
check(!(nullValue57 === missingValue), 'null not undefined 57');
check(typeof nullValue57 === 'object', 'null typeof 57');
check((true ? null : 57) === nullValue57, 'null ternary true 57');
check((false ? 57 : null) === nullValue57, 'null ternary false 57');
check(returnNull(false) === null, 'null return 57');
var nullValue58 = null;
check(nullValue58 === null, 'null strict 58');
check(!(nullValue58 !== null), 'null strict inverse 58');
check(nullValue58 == missingValue, 'null loose undefined 58');
check(!(nullValue58 === missingValue), 'null not undefined 58');
check(typeof nullValue58 === 'object', 'null typeof 58');
check((true ? null : 58) === nullValue58, 'null ternary true 58');
check((false ? 58 : null) === nullValue58, 'null ternary false 58');
check(returnNull(true) === null, 'null return 58');
var nullValue59 = null;
check(nullValue59 === null, 'null strict 59');
check(!(nullValue59 !== null), 'null strict inverse 59');
check(nullValue59 == missingValue, 'null loose undefined 59');
check(!(nullValue59 === missingValue), 'null not undefined 59');
check(typeof nullValue59 === 'object', 'null typeof 59');
check((true ? null : 59) === nullValue59, 'null ternary true 59');
check((false ? 59 : null) === nullValue59, 'null ternary false 59');
check(returnNull(false) === null, 'null return 59');
var nullValue60 = null;
check(nullValue60 === null, 'null strict 60');
check(!(nullValue60 !== null), 'null strict inverse 60');
check(nullValue60 == missingValue, 'null loose undefined 60');
check(!(nullValue60 === missingValue), 'null not undefined 60');
check(typeof nullValue60 === 'object', 'null typeof 60');
check((true ? null : 60) === nullValue60, 'null ternary true 60');
check((false ? 60 : null) === nullValue60, 'null ternary false 60');
check(returnNull(true) === null, 'null return 60');
var nullValue61 = null;
check(nullValue61 === null, 'null strict 61');
check(!(nullValue61 !== null), 'null strict inverse 61');
check(nullValue61 == missingValue, 'null loose undefined 61');
check(!(nullValue61 === missingValue), 'null not undefined 61');
check(typeof nullValue61 === 'object', 'null typeof 61');
check((true ? null : 61) === nullValue61, 'null ternary true 61');
check((false ? 61 : null) === nullValue61, 'null ternary false 61');
check(returnNull(false) === null, 'null return 61');
var nullValue62 = null;
check(nullValue62 === null, 'null strict 62');
check(!(nullValue62 !== null), 'null strict inverse 62');
check(nullValue62 == missingValue, 'null loose undefined 62');
check(!(nullValue62 === missingValue), 'null not undefined 62');
check(typeof nullValue62 === 'object', 'null typeof 62');
check((true ? null : 62) === nullValue62, 'null ternary true 62');
check((false ? 62 : null) === nullValue62, 'null ternary false 62');
check(returnNull(true) === null, 'null return 62');
var nullValue63 = null;
check(nullValue63 === null, 'null strict 63');
check(!(nullValue63 !== null), 'null strict inverse 63');
check(nullValue63 == missingValue, 'null loose undefined 63');
check(!(nullValue63 === missingValue), 'null not undefined 63');
check(typeof nullValue63 === 'object', 'null typeof 63');
check((true ? null : 63) === nullValue63, 'null ternary true 63');
check((false ? 63 : null) === nullValue63, 'null ternary false 63');
check(returnNull(false) === null, 'null return 63');
var nullValue64 = null;
check(nullValue64 === null, 'null strict 64');
check(!(nullValue64 !== null), 'null strict inverse 64');
check(nullValue64 == missingValue, 'null loose undefined 64');
check(!(nullValue64 === missingValue), 'null not undefined 64');
check(typeof nullValue64 === 'object', 'null typeof 64');
check((true ? null : 64) === nullValue64, 'null ternary true 64');
check((false ? 64 : null) === nullValue64, 'null ternary false 64');
check(returnNull(true) === null, 'null return 64');
var nullValue65 = null;
check(nullValue65 === null, 'null strict 65');
check(!(nullValue65 !== null), 'null strict inverse 65');
check(nullValue65 == missingValue, 'null loose undefined 65');
check(!(nullValue65 === missingValue), 'null not undefined 65');
check(typeof nullValue65 === 'object', 'null typeof 65');
check((true ? null : 65) === nullValue65, 'null ternary true 65');
check((false ? 65 : null) === nullValue65, 'null ternary false 65');
check(returnNull(false) === null, 'null return 65');
var nullValue66 = null;
check(nullValue66 === null, 'null strict 66');
check(!(nullValue66 !== null), 'null strict inverse 66');
check(nullValue66 == missingValue, 'null loose undefined 66');
check(!(nullValue66 === missingValue), 'null not undefined 66');
check(typeof nullValue66 === 'object', 'null typeof 66');
check((true ? null : 66) === nullValue66, 'null ternary true 66');
check((false ? 66 : null) === nullValue66, 'null ternary false 66');
check(returnNull(true) === null, 'null return 66');
var nullValue67 = null;
check(nullValue67 === null, 'null strict 67');
check(!(nullValue67 !== null), 'null strict inverse 67');
check(nullValue67 == missingValue, 'null loose undefined 67');
check(!(nullValue67 === missingValue), 'null not undefined 67');
check(typeof nullValue67 === 'object', 'null typeof 67');
check((true ? null : 67) === nullValue67, 'null ternary true 67');
check((false ? 67 : null) === nullValue67, 'null ternary false 67');
check(returnNull(false) === null, 'null return 67');
var nullValue68 = null;
check(nullValue68 === null, 'null strict 68');
check(!(nullValue68 !== null), 'null strict inverse 68');
check(nullValue68 == missingValue, 'null loose undefined 68');
check(!(nullValue68 === missingValue), 'null not undefined 68');
check(typeof nullValue68 === 'object', 'null typeof 68');
check((true ? null : 68) === nullValue68, 'null ternary true 68');
check((false ? 68 : null) === nullValue68, 'null ternary false 68');
check(returnNull(true) === null, 'null return 68');
var nullValue69 = null;
check(nullValue69 === null, 'null strict 69');
check(!(nullValue69 !== null), 'null strict inverse 69');
check(nullValue69 == missingValue, 'null loose undefined 69');
check(!(nullValue69 === missingValue), 'null not undefined 69');
check(typeof nullValue69 === 'object', 'null typeof 69');
check((true ? null : 69) === nullValue69, 'null ternary true 69');
check((false ? 69 : null) === nullValue69, 'null ternary false 69');
check(returnNull(false) === null, 'null return 69');
var nullValue70 = null;
check(nullValue70 === null, 'null strict 70');
check(!(nullValue70 !== null), 'null strict inverse 70');
check(nullValue70 == missingValue, 'null loose undefined 70');
check(!(nullValue70 === missingValue), 'null not undefined 70');
check(typeof nullValue70 === 'object', 'null typeof 70');
check((true ? null : 70) === nullValue70, 'null ternary true 70');
check((false ? 70 : null) === nullValue70, 'null ternary false 70');
check(returnNull(true) === null, 'null return 70');
var nullValue71 = null;
check(nullValue71 === null, 'null strict 71');
check(!(nullValue71 !== null), 'null strict inverse 71');
check(nullValue71 == missingValue, 'null loose undefined 71');
check(!(nullValue71 === missingValue), 'null not undefined 71');
check(typeof nullValue71 === 'object', 'null typeof 71');
check((true ? null : 71) === nullValue71, 'null ternary true 71');
check((false ? 71 : null) === nullValue71, 'null ternary false 71');
check(returnNull(false) === null, 'null return 71');
var nullValue72 = null;
check(nullValue72 === null, 'null strict 72');
check(!(nullValue72 !== null), 'null strict inverse 72');
check(nullValue72 == missingValue, 'null loose undefined 72');
check(!(nullValue72 === missingValue), 'null not undefined 72');
check(typeof nullValue72 === 'object', 'null typeof 72');
check((true ? null : 72) === nullValue72, 'null ternary true 72');
check((false ? 72 : null) === nullValue72, 'null ternary false 72');
check(returnNull(true) === null, 'null return 72');
var nullValue73 = null;
check(nullValue73 === null, 'null strict 73');
check(!(nullValue73 !== null), 'null strict inverse 73');
check(nullValue73 == missingValue, 'null loose undefined 73');
check(!(nullValue73 === missingValue), 'null not undefined 73');
check(typeof nullValue73 === 'object', 'null typeof 73');
check((true ? null : 73) === nullValue73, 'null ternary true 73');
check((false ? 73 : null) === nullValue73, 'null ternary false 73');
check(returnNull(false) === null, 'null return 73');
var nullValue74 = null;
check(nullValue74 === null, 'null strict 74');
check(!(nullValue74 !== null), 'null strict inverse 74');
check(nullValue74 == missingValue, 'null loose undefined 74');
check(!(nullValue74 === missingValue), 'null not undefined 74');
check(typeof nullValue74 === 'object', 'null typeof 74');
check((true ? null : 74) === nullValue74, 'null ternary true 74');
check((false ? 74 : null) === nullValue74, 'null ternary false 74');
check(returnNull(true) === null, 'null return 74');
var nullValue75 = null;
check(nullValue75 === null, 'null strict 75');
check(!(nullValue75 !== null), 'null strict inverse 75');
check(nullValue75 == missingValue, 'null loose undefined 75');
check(!(nullValue75 === missingValue), 'null not undefined 75');
check(typeof nullValue75 === 'object', 'null typeof 75');
check((true ? null : 75) === nullValue75, 'null ternary true 75');
check((false ? 75 : null) === nullValue75, 'null ternary false 75');
check(returnNull(false) === null, 'null return 75');
var nullValue76 = null;
check(nullValue76 === null, 'null strict 76');
check(!(nullValue76 !== null), 'null strict inverse 76');
check(nullValue76 == missingValue, 'null loose undefined 76');
check(!(nullValue76 === missingValue), 'null not undefined 76');
check(typeof nullValue76 === 'object', 'null typeof 76');
check((true ? null : 76) === nullValue76, 'null ternary true 76');
check((false ? 76 : null) === nullValue76, 'null ternary false 76');
check(returnNull(true) === null, 'null return 76');
var nullValue77 = null;
check(nullValue77 === null, 'null strict 77');
check(!(nullValue77 !== null), 'null strict inverse 77');
check(nullValue77 == missingValue, 'null loose undefined 77');
check(!(nullValue77 === missingValue), 'null not undefined 77');
check(typeof nullValue77 === 'object', 'null typeof 77');
check((true ? null : 77) === nullValue77, 'null ternary true 77');
check((false ? 77 : null) === nullValue77, 'null ternary false 77');
check(returnNull(false) === null, 'null return 77');
var nullValue78 = null;
check(nullValue78 === null, 'null strict 78');
check(!(nullValue78 !== null), 'null strict inverse 78');
check(nullValue78 == missingValue, 'null loose undefined 78');
check(!(nullValue78 === missingValue), 'null not undefined 78');
check(typeof nullValue78 === 'object', 'null typeof 78');
check((true ? null : 78) === nullValue78, 'null ternary true 78');
check((false ? 78 : null) === nullValue78, 'null ternary false 78');
check(returnNull(true) === null, 'null return 78');
var nullValue79 = null;
check(nullValue79 === null, 'null strict 79');
check(!(nullValue79 !== null), 'null strict inverse 79');
check(nullValue79 == missingValue, 'null loose undefined 79');
check(!(nullValue79 === missingValue), 'null not undefined 79');
check(typeof nullValue79 === 'object', 'null typeof 79');
check((true ? null : 79) === nullValue79, 'null ternary true 79');
check((false ? 79 : null) === nullValue79, 'null ternary false 79');
check(returnNull(false) === null, 'null return 79');
var nullValue80 = null;
check(nullValue80 === null, 'null strict 80');
check(!(nullValue80 !== null), 'null strict inverse 80');
check(nullValue80 == missingValue, 'null loose undefined 80');
check(!(nullValue80 === missingValue), 'null not undefined 80');
check(typeof nullValue80 === 'object', 'null typeof 80');
check((true ? null : 80) === nullValue80, 'null ternary true 80');
check((false ? 80 : null) === nullValue80, 'null ternary false 80');
check(returnNull(true) === null, 'null return 80');
var nullValue81 = null;
check(nullValue81 === null, 'null strict 81');
check(!(nullValue81 !== null), 'null strict inverse 81');
check(nullValue81 == missingValue, 'null loose undefined 81');
check(!(nullValue81 === missingValue), 'null not undefined 81');
check(typeof nullValue81 === 'object', 'null typeof 81');
check((true ? null : 81) === nullValue81, 'null ternary true 81');
check((false ? 81 : null) === nullValue81, 'null ternary false 81');
check(returnNull(false) === null, 'null return 81');
var nullValue82 = null;
check(nullValue82 === null, 'null strict 82');
check(!(nullValue82 !== null), 'null strict inverse 82');
check(nullValue82 == missingValue, 'null loose undefined 82');
check(!(nullValue82 === missingValue), 'null not undefined 82');
check(typeof nullValue82 === 'object', 'null typeof 82');
check((true ? null : 82) === nullValue82, 'null ternary true 82');
check((false ? 82 : null) === nullValue82, 'null ternary false 82');
check(returnNull(true) === null, 'null return 82');
var nullValue83 = null;
check(nullValue83 === null, 'null strict 83');
check(!(nullValue83 !== null), 'null strict inverse 83');
check(nullValue83 == missingValue, 'null loose undefined 83');
check(!(nullValue83 === missingValue), 'null not undefined 83');
check(typeof nullValue83 === 'object', 'null typeof 83');
check((true ? null : 83) === nullValue83, 'null ternary true 83');
check((false ? 83 : null) === nullValue83, 'null ternary false 83');
check(returnNull(false) === null, 'null return 83');
var nullValue84 = null;
check(nullValue84 === null, 'null strict 84');
check(!(nullValue84 !== null), 'null strict inverse 84');
check(nullValue84 == missingValue, 'null loose undefined 84');
check(!(nullValue84 === missingValue), 'null not undefined 84');
check(typeof nullValue84 === 'object', 'null typeof 84');
check((true ? null : 84) === nullValue84, 'null ternary true 84');
check((false ? 84 : null) === nullValue84, 'null ternary false 84');
check(returnNull(true) === null, 'null return 84');
var nullValue85 = null;
check(nullValue85 === null, 'null strict 85');
check(!(nullValue85 !== null), 'null strict inverse 85');
check(nullValue85 == missingValue, 'null loose undefined 85');
check(!(nullValue85 === missingValue), 'null not undefined 85');
check(typeof nullValue85 === 'object', 'null typeof 85');
check((true ? null : 85) === nullValue85, 'null ternary true 85');
check((false ? 85 : null) === nullValue85, 'null ternary false 85');
check(returnNull(false) === null, 'null return 85');
var nullValue86 = null;
check(nullValue86 === null, 'null strict 86');
check(!(nullValue86 !== null), 'null strict inverse 86');
check(nullValue86 == missingValue, 'null loose undefined 86');
check(!(nullValue86 === missingValue), 'null not undefined 86');
check(typeof nullValue86 === 'object', 'null typeof 86');
check((true ? null : 86) === nullValue86, 'null ternary true 86');
check((false ? 86 : null) === nullValue86, 'null ternary false 86');
check(returnNull(true) === null, 'null return 86');
var nullValue87 = null;
check(nullValue87 === null, 'null strict 87');
check(!(nullValue87 !== null), 'null strict inverse 87');
check(nullValue87 == missingValue, 'null loose undefined 87');
check(!(nullValue87 === missingValue), 'null not undefined 87');
check(typeof nullValue87 === 'object', 'null typeof 87');
check((true ? null : 87) === nullValue87, 'null ternary true 87');
check((false ? 87 : null) === nullValue87, 'null ternary false 87');
check(returnNull(false) === null, 'null return 87');
var nullValue88 = null;
check(nullValue88 === null, 'null strict 88');
check(!(nullValue88 !== null), 'null strict inverse 88');
check(nullValue88 == missingValue, 'null loose undefined 88');
check(!(nullValue88 === missingValue), 'null not undefined 88');
check(typeof nullValue88 === 'object', 'null typeof 88');
check((true ? null : 88) === nullValue88, 'null ternary true 88');
check((false ? 88 : null) === nullValue88, 'null ternary false 88');
check(returnNull(true) === null, 'null return 88');
var nullValue89 = null;
check(nullValue89 === null, 'null strict 89');
check(!(nullValue89 !== null), 'null strict inverse 89');
check(nullValue89 == missingValue, 'null loose undefined 89');
check(!(nullValue89 === missingValue), 'null not undefined 89');
check(typeof nullValue89 === 'object', 'null typeof 89');
check((true ? null : 89) === nullValue89, 'null ternary true 89');
check((false ? 89 : null) === nullValue89, 'null ternary false 89');
check(returnNull(false) === null, 'null return 89');
var nullValue90 = null;
check(nullValue90 === null, 'null strict 90');
check(!(nullValue90 !== null), 'null strict inverse 90');
check(nullValue90 == missingValue, 'null loose undefined 90');
check(!(nullValue90 === missingValue), 'null not undefined 90');
check(typeof nullValue90 === 'object', 'null typeof 90');
check((true ? null : 90) === nullValue90, 'null ternary true 90');
check((false ? 90 : null) === nullValue90, 'null ternary false 90');
check(returnNull(true) === null, 'null return 90');
var nullValue91 = null;
check(nullValue91 === null, 'null strict 91');
check(!(nullValue91 !== null), 'null strict inverse 91');
check(nullValue91 == missingValue, 'null loose undefined 91');
check(!(nullValue91 === missingValue), 'null not undefined 91');
check(typeof nullValue91 === 'object', 'null typeof 91');
check((true ? null : 91) === nullValue91, 'null ternary true 91');
check((false ? 91 : null) === nullValue91, 'null ternary false 91');
check(returnNull(false) === null, 'null return 91');
var nullValue92 = null;
check(nullValue92 === null, 'null strict 92');
check(!(nullValue92 !== null), 'null strict inverse 92');
check(nullValue92 == missingValue, 'null loose undefined 92');
check(!(nullValue92 === missingValue), 'null not undefined 92');
check(typeof nullValue92 === 'object', 'null typeof 92');
check((true ? null : 92) === nullValue92, 'null ternary true 92');
check((false ? 92 : null) === nullValue92, 'null ternary false 92');
check(returnNull(true) === null, 'null return 92');
var nullValue93 = null;
check(nullValue93 === null, 'null strict 93');
check(!(nullValue93 !== null), 'null strict inverse 93');
check(nullValue93 == missingValue, 'null loose undefined 93');
check(!(nullValue93 === missingValue), 'null not undefined 93');
check(typeof nullValue93 === 'object', 'null typeof 93');
check((true ? null : 93) === nullValue93, 'null ternary true 93');
check((false ? 93 : null) === nullValue93, 'null ternary false 93');
check(returnNull(false) === null, 'null return 93');
var nullValue94 = null;
check(nullValue94 === null, 'null strict 94');
check(!(nullValue94 !== null), 'null strict inverse 94');
check(nullValue94 == missingValue, 'null loose undefined 94');
check(!(nullValue94 === missingValue), 'null not undefined 94');
check(typeof nullValue94 === 'object', 'null typeof 94');
check((true ? null : 94) === nullValue94, 'null ternary true 94');
check((false ? 94 : null) === nullValue94, 'null ternary false 94');
check(returnNull(true) === null, 'null return 94');
var nullValue95 = null;
check(nullValue95 === null, 'null strict 95');
check(!(nullValue95 !== null), 'null strict inverse 95');
check(nullValue95 == missingValue, 'null loose undefined 95');
check(!(nullValue95 === missingValue), 'null not undefined 95');
check(typeof nullValue95 === 'object', 'null typeof 95');
check((true ? null : 95) === nullValue95, 'null ternary true 95');
check((false ? 95 : null) === nullValue95, 'null ternary false 95');
check(returnNull(false) === null, 'null return 95');
var nullValue96 = null;
check(nullValue96 === null, 'null strict 96');
check(!(nullValue96 !== null), 'null strict inverse 96');
check(nullValue96 == missingValue, 'null loose undefined 96');
check(!(nullValue96 === missingValue), 'null not undefined 96');
check(typeof nullValue96 === 'object', 'null typeof 96');
check((true ? null : 96) === nullValue96, 'null ternary true 96');
check((false ? 96 : null) === nullValue96, 'null ternary false 96');
check(returnNull(true) === null, 'null return 96');
var nullValue97 = null;
check(nullValue97 === null, 'null strict 97');
check(!(nullValue97 !== null), 'null strict inverse 97');
check(nullValue97 == missingValue, 'null loose undefined 97');
check(!(nullValue97 === missingValue), 'null not undefined 97');
check(typeof nullValue97 === 'object', 'null typeof 97');
check((true ? null : 97) === nullValue97, 'null ternary true 97');
check((false ? 97 : null) === nullValue97, 'null ternary false 97');
check(returnNull(false) === null, 'null return 97');
var nullValue98 = null;
check(nullValue98 === null, 'null strict 98');
check(!(nullValue98 !== null), 'null strict inverse 98');
check(nullValue98 == missingValue, 'null loose undefined 98');
check(!(nullValue98 === missingValue), 'null not undefined 98');
check(typeof nullValue98 === 'object', 'null typeof 98');
check((true ? null : 98) === nullValue98, 'null ternary true 98');
check((false ? 98 : null) === nullValue98, 'null ternary false 98');
check(returnNull(true) === null, 'null return 98');
var nullValue99 = null;
check(nullValue99 === null, 'null strict 99');
check(!(nullValue99 !== null), 'null strict inverse 99');
check(nullValue99 == missingValue, 'null loose undefined 99');
check(!(nullValue99 === missingValue), 'null not undefined 99');
check(typeof nullValue99 === 'object', 'null typeof 99');
check((true ? null : 99) === nullValue99, 'null ternary true 99');
check((false ? 99 : null) === nullValue99, 'null ternary false 99');
check(returnNull(false) === null, 'null return 99');
var nullValue100 = null;
check(nullValue100 === null, 'null strict 100');
check(!(nullValue100 !== null), 'null strict inverse 100');
check(nullValue100 == missingValue, 'null loose undefined 100');
check(!(nullValue100 === missingValue), 'null not undefined 100');
check(typeof nullValue100 === 'object', 'null typeof 100');
check((true ? null : 100) === nullValue100, 'null ternary true 100');
check((false ? 100 : null) === nullValue100, 'null ternary false 100');
check(returnNull(true) === null, 'null return 100');
var nullValue101 = null;
check(nullValue101 === null, 'null strict 101');
check(!(nullValue101 !== null), 'null strict inverse 101');
check(nullValue101 == missingValue, 'null loose undefined 101');
check(!(nullValue101 === missingValue), 'null not undefined 101');
check(typeof nullValue101 === 'object', 'null typeof 101');
check((true ? null : 101) === nullValue101, 'null ternary true 101');
check((false ? 101 : null) === nullValue101, 'null ternary false 101');
check(returnNull(false) === null, 'null return 101');
var nullValue102 = null;
check(nullValue102 === null, 'null strict 102');
check(!(nullValue102 !== null), 'null strict inverse 102');
check(nullValue102 == missingValue, 'null loose undefined 102');
check(!(nullValue102 === missingValue), 'null not undefined 102');
check(typeof nullValue102 === 'object', 'null typeof 102');
check((true ? null : 102) === nullValue102, 'null ternary true 102');
check((false ? 102 : null) === nullValue102, 'null ternary false 102');
check(returnNull(true) === null, 'null return 102');
var nullValue103 = null;
check(nullValue103 === null, 'null strict 103');
check(!(nullValue103 !== null), 'null strict inverse 103');
check(nullValue103 == missingValue, 'null loose undefined 103');
check(!(nullValue103 === missingValue), 'null not undefined 103');
check(typeof nullValue103 === 'object', 'null typeof 103');
check((true ? null : 103) === nullValue103, 'null ternary true 103');
check((false ? 103 : null) === nullValue103, 'null ternary false 103');
check(returnNull(false) === null, 'null return 103');
var nullValue104 = null;
check(nullValue104 === null, 'null strict 104');
check(!(nullValue104 !== null), 'null strict inverse 104');
check(nullValue104 == missingValue, 'null loose undefined 104');
check(!(nullValue104 === missingValue), 'null not undefined 104');
check(typeof nullValue104 === 'object', 'null typeof 104');
check((true ? null : 104) === nullValue104, 'null ternary true 104');
check((false ? 104 : null) === nullValue104, 'null ternary false 104');
check(returnNull(true) === null, 'null return 104');
var nullValue105 = null;
check(nullValue105 === null, 'null strict 105');
check(!(nullValue105 !== null), 'null strict inverse 105');
check(nullValue105 == missingValue, 'null loose undefined 105');
check(!(nullValue105 === missingValue), 'null not undefined 105');
check(typeof nullValue105 === 'object', 'null typeof 105');
check((true ? null : 105) === nullValue105, 'null ternary true 105');
check((false ? 105 : null) === nullValue105, 'null ternary false 105');
check(returnNull(false) === null, 'null return 105');
var nullValue106 = null;
check(nullValue106 === null, 'null strict 106');
check(!(nullValue106 !== null), 'null strict inverse 106');
check(nullValue106 == missingValue, 'null loose undefined 106');
check(!(nullValue106 === missingValue), 'null not undefined 106');
check(typeof nullValue106 === 'object', 'null typeof 106');
check((true ? null : 106) === nullValue106, 'null ternary true 106');
check((false ? 106 : null) === nullValue106, 'null ternary false 106');
check(returnNull(true) === null, 'null return 106');
var nullValue107 = null;
check(nullValue107 === null, 'null strict 107');
check(!(nullValue107 !== null), 'null strict inverse 107');
check(nullValue107 == missingValue, 'null loose undefined 107');
check(!(nullValue107 === missingValue), 'null not undefined 107');
check(typeof nullValue107 === 'object', 'null typeof 107');
check((true ? null : 107) === nullValue107, 'null ternary true 107');
check((false ? 107 : null) === nullValue107, 'null ternary false 107');
check(returnNull(false) === null, 'null return 107');
var nullValue108 = null;
check(nullValue108 === null, 'null strict 108');
check(!(nullValue108 !== null), 'null strict inverse 108');
check(nullValue108 == missingValue, 'null loose undefined 108');
check(!(nullValue108 === missingValue), 'null not undefined 108');
check(typeof nullValue108 === 'object', 'null typeof 108');
check((true ? null : 108) === nullValue108, 'null ternary true 108');
check((false ? 108 : null) === nullValue108, 'null ternary false 108');
check(returnNull(true) === null, 'null return 108');
var nullValue109 = null;
check(nullValue109 === null, 'null strict 109');
check(!(nullValue109 !== null), 'null strict inverse 109');
check(nullValue109 == missingValue, 'null loose undefined 109');
check(!(nullValue109 === missingValue), 'null not undefined 109');
check(typeof nullValue109 === 'object', 'null typeof 109');
check((true ? null : 109) === nullValue109, 'null ternary true 109');
check((false ? 109 : null) === nullValue109, 'null ternary false 109');
check(returnNull(false) === null, 'null return 109');
var nullValue110 = null;
check(nullValue110 === null, 'null strict 110');
check(!(nullValue110 !== null), 'null strict inverse 110');
check(nullValue110 == missingValue, 'null loose undefined 110');
check(!(nullValue110 === missingValue), 'null not undefined 110');
check(typeof nullValue110 === 'object', 'null typeof 110');
check((true ? null : 110) === nullValue110, 'null ternary true 110');
check((false ? 110 : null) === nullValue110, 'null ternary false 110');
check(returnNull(true) === null, 'null return 110');
console.log('null-literal-evaluates-null stress ' + score);
