// behavior: this-resolves-current-this-binding
// expected: pass
// goal: module
// size: stress
// variant: module

var score = 0;
function assertThis(condition, name) {
if (!condition) { throw new Error(name); }
score = score + 1;
}
function strictIdentity() { "use strict"; return this; }
function sloppyIdentity() { return this; }
function receiverIdentity() { return this; }
function ArrowSource(value) { this.value = value; return (() => this); }
function Box(value) { this.value = value; this.self = this; }
function makeAccessorSlot(value) {
var target = { value: value, seen: null };
Object.defineProperty(target, "slot", {
get: function() { this.seen = this; return this.value; },
set: function(next) { this.seen = this; this.value = next; },
configurable: true
});
return target;
}
assertThis(this === undefined, "module-top-level-this");
assertThis(sloppyIdentity() === undefined, "module-plain-0");
assertThis(strictIdentity() === undefined, "module-explicit-0");
var methodTarget0 = { value: 0, method: receiverIdentity };
assertThis(methodTarget0.method() === methodTarget0, "module-method-0");
var detached0 = methodTarget0.method;
assertThis(detached0() === undefined, "module-detached-0");
var callTarget0 = { value: 1 };
assertThis(receiverIdentity.call(callTarget0) === callTarget0, "module-call-object-0");
assertThis(receiverIdentity.apply(callTarget0, []) === callTarget0, "module-apply-object-0");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-0");
var bound0 = receiverIdentity.bind(callTarget0);
assertThis(bound0() === callTarget0, "module-bind-0");
var arrow0 = ArrowSource.call(callTarget0, 2);
assertThis(arrow0() === callTarget0, "module-arrow-0");
var box0 = new Box(3);
assertThis(box0.self === box0 && box0.value === 3, "module-constructor-0");
var access0 = makeAccessorSlot(4);
assertThis(access0.slot === 4 && access0.seen === access0, "module-getter-0");
access0.slot = 5;
assertThis(access0.value === 5 && access0.seen === access0, "module-setter-0");
assertThis(sloppyIdentity() === undefined, "module-plain-1");
assertThis(strictIdentity() === undefined, "module-explicit-1");
var methodTarget1 = { value: 1, method: receiverIdentity };
assertThis(methodTarget1.method() === methodTarget1, "module-method-1");
var detached1 = methodTarget1.method;
assertThis(detached1() === undefined, "module-detached-1");
var callTarget1 = { value: 2 };
assertThis(receiverIdentity.call(callTarget1) === callTarget1, "module-call-object-1");
assertThis(receiverIdentity.apply(callTarget1, []) === callTarget1, "module-apply-object-1");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-1");
var bound1 = receiverIdentity.bind(callTarget1);
assertThis(bound1() === callTarget1, "module-bind-1");
var arrow1 = ArrowSource.call(callTarget1, 3);
assertThis(arrow1() === callTarget1, "module-arrow-1");
var box1 = new Box(4);
assertThis(box1.self === box1 && box1.value === 4, "module-constructor-1");
var access1 = makeAccessorSlot(5);
assertThis(access1.slot === 5 && access1.seen === access1, "module-getter-1");
access1.slot = 6;
assertThis(access1.value === 6 && access1.seen === access1, "module-setter-1");
assertThis(sloppyIdentity() === undefined, "module-plain-2");
assertThis(strictIdentity() === undefined, "module-explicit-2");
var methodTarget2 = { value: 2, method: receiverIdentity };
assertThis(methodTarget2.method() === methodTarget2, "module-method-2");
var detached2 = methodTarget2.method;
assertThis(detached2() === undefined, "module-detached-2");
var callTarget2 = { value: 3 };
assertThis(receiverIdentity.call(callTarget2) === callTarget2, "module-call-object-2");
assertThis(receiverIdentity.apply(callTarget2, []) === callTarget2, "module-apply-object-2");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-2");
var bound2 = receiverIdentity.bind(callTarget2);
assertThis(bound2() === callTarget2, "module-bind-2");
var arrow2 = ArrowSource.call(callTarget2, 4);
assertThis(arrow2() === callTarget2, "module-arrow-2");
var box2 = new Box(5);
assertThis(box2.self === box2 && box2.value === 5, "module-constructor-2");
var access2 = makeAccessorSlot(6);
assertThis(access2.slot === 6 && access2.seen === access2, "module-getter-2");
access2.slot = 7;
assertThis(access2.value === 7 && access2.seen === access2, "module-setter-2");
assertThis(sloppyIdentity() === undefined, "module-plain-3");
assertThis(strictIdentity() === undefined, "module-explicit-3");
var methodTarget3 = { value: 3, method: receiverIdentity };
assertThis(methodTarget3.method() === methodTarget3, "module-method-3");
var detached3 = methodTarget3.method;
assertThis(detached3() === undefined, "module-detached-3");
var callTarget3 = { value: 4 };
assertThis(receiverIdentity.call(callTarget3) === callTarget3, "module-call-object-3");
assertThis(receiverIdentity.apply(callTarget3, []) === callTarget3, "module-apply-object-3");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-3");
var bound3 = receiverIdentity.bind(callTarget3);
assertThis(bound3() === callTarget3, "module-bind-3");
var arrow3 = ArrowSource.call(callTarget3, 5);
assertThis(arrow3() === callTarget3, "module-arrow-3");
var box3 = new Box(6);
assertThis(box3.self === box3 && box3.value === 6, "module-constructor-3");
var access3 = makeAccessorSlot(7);
assertThis(access3.slot === 7 && access3.seen === access3, "module-getter-3");
access3.slot = 8;
assertThis(access3.value === 8 && access3.seen === access3, "module-setter-3");
assertThis(sloppyIdentity() === undefined, "module-plain-4");
assertThis(strictIdentity() === undefined, "module-explicit-4");
var methodTarget4 = { value: 4, method: receiverIdentity };
assertThis(methodTarget4.method() === methodTarget4, "module-method-4");
var detached4 = methodTarget4.method;
assertThis(detached4() === undefined, "module-detached-4");
var callTarget4 = { value: 5 };
assertThis(receiverIdentity.call(callTarget4) === callTarget4, "module-call-object-4");
assertThis(receiverIdentity.apply(callTarget4, []) === callTarget4, "module-apply-object-4");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-4");
var bound4 = receiverIdentity.bind(callTarget4);
assertThis(bound4() === callTarget4, "module-bind-4");
var arrow4 = ArrowSource.call(callTarget4, 6);
assertThis(arrow4() === callTarget4, "module-arrow-4");
var box4 = new Box(7);
assertThis(box4.self === box4 && box4.value === 7, "module-constructor-4");
var access4 = makeAccessorSlot(8);
assertThis(access4.slot === 8 && access4.seen === access4, "module-getter-4");
access4.slot = 9;
assertThis(access4.value === 9 && access4.seen === access4, "module-setter-4");
assertThis(sloppyIdentity() === undefined, "module-plain-5");
assertThis(strictIdentity() === undefined, "module-explicit-5");
var methodTarget5 = { value: 5, method: receiverIdentity };
assertThis(methodTarget5.method() === methodTarget5, "module-method-5");
var detached5 = methodTarget5.method;
assertThis(detached5() === undefined, "module-detached-5");
var callTarget5 = { value: 6 };
assertThis(receiverIdentity.call(callTarget5) === callTarget5, "module-call-object-5");
assertThis(receiverIdentity.apply(callTarget5, []) === callTarget5, "module-apply-object-5");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-5");
var bound5 = receiverIdentity.bind(callTarget5);
assertThis(bound5() === callTarget5, "module-bind-5");
var arrow5 = ArrowSource.call(callTarget5, 7);
assertThis(arrow5() === callTarget5, "module-arrow-5");
var box5 = new Box(8);
assertThis(box5.self === box5 && box5.value === 8, "module-constructor-5");
var access5 = makeAccessorSlot(9);
assertThis(access5.slot === 9 && access5.seen === access5, "module-getter-5");
access5.slot = 10;
assertThis(access5.value === 10 && access5.seen === access5, "module-setter-5");
assertThis(sloppyIdentity() === undefined, "module-plain-6");
assertThis(strictIdentity() === undefined, "module-explicit-6");
var methodTarget6 = { value: 6, method: receiverIdentity };
assertThis(methodTarget6.method() === methodTarget6, "module-method-6");
var detached6 = methodTarget6.method;
assertThis(detached6() === undefined, "module-detached-6");
var callTarget6 = { value: 7 };
assertThis(receiverIdentity.call(callTarget6) === callTarget6, "module-call-object-6");
assertThis(receiverIdentity.apply(callTarget6, []) === callTarget6, "module-apply-object-6");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-6");
var bound6 = receiverIdentity.bind(callTarget6);
assertThis(bound6() === callTarget6, "module-bind-6");
var arrow6 = ArrowSource.call(callTarget6, 8);
assertThis(arrow6() === callTarget6, "module-arrow-6");
var box6 = new Box(9);
assertThis(box6.self === box6 && box6.value === 9, "module-constructor-6");
var access6 = makeAccessorSlot(10);
assertThis(access6.slot === 10 && access6.seen === access6, "module-getter-6");
access6.slot = 11;
assertThis(access6.value === 11 && access6.seen === access6, "module-setter-6");
assertThis(sloppyIdentity() === undefined, "module-plain-7");
assertThis(strictIdentity() === undefined, "module-explicit-7");
var methodTarget7 = { value: 7, method: receiverIdentity };
assertThis(methodTarget7.method() === methodTarget7, "module-method-7");
var detached7 = methodTarget7.method;
assertThis(detached7() === undefined, "module-detached-7");
var callTarget7 = { value: 8 };
assertThis(receiverIdentity.call(callTarget7) === callTarget7, "module-call-object-7");
assertThis(receiverIdentity.apply(callTarget7, []) === callTarget7, "module-apply-object-7");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-7");
var bound7 = receiverIdentity.bind(callTarget7);
assertThis(bound7() === callTarget7, "module-bind-7");
var arrow7 = ArrowSource.call(callTarget7, 9);
assertThis(arrow7() === callTarget7, "module-arrow-7");
var box7 = new Box(10);
assertThis(box7.self === box7 && box7.value === 10, "module-constructor-7");
var access7 = makeAccessorSlot(11);
assertThis(access7.slot === 11 && access7.seen === access7, "module-getter-7");
access7.slot = 12;
assertThis(access7.value === 12 && access7.seen === access7, "module-setter-7");
assertThis(sloppyIdentity() === undefined, "module-plain-8");
assertThis(strictIdentity() === undefined, "module-explicit-8");
var methodTarget8 = { value: 8, method: receiverIdentity };
assertThis(methodTarget8.method() === methodTarget8, "module-method-8");
var detached8 = methodTarget8.method;
assertThis(detached8() === undefined, "module-detached-8");
var callTarget8 = { value: 9 };
assertThis(receiverIdentity.call(callTarget8) === callTarget8, "module-call-object-8");
assertThis(receiverIdentity.apply(callTarget8, []) === callTarget8, "module-apply-object-8");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-8");
var bound8 = receiverIdentity.bind(callTarget8);
assertThis(bound8() === callTarget8, "module-bind-8");
var arrow8 = ArrowSource.call(callTarget8, 10);
assertThis(arrow8() === callTarget8, "module-arrow-8");
var box8 = new Box(11);
assertThis(box8.self === box8 && box8.value === 11, "module-constructor-8");
var access8 = makeAccessorSlot(12);
assertThis(access8.slot === 12 && access8.seen === access8, "module-getter-8");
access8.slot = 13;
assertThis(access8.value === 13 && access8.seen === access8, "module-setter-8");
assertThis(sloppyIdentity() === undefined, "module-plain-9");
assertThis(strictIdentity() === undefined, "module-explicit-9");
var methodTarget9 = { value: 9, method: receiverIdentity };
assertThis(methodTarget9.method() === methodTarget9, "module-method-9");
var detached9 = methodTarget9.method;
assertThis(detached9() === undefined, "module-detached-9");
var callTarget9 = { value: 10 };
assertThis(receiverIdentity.call(callTarget9) === callTarget9, "module-call-object-9");
assertThis(receiverIdentity.apply(callTarget9, []) === callTarget9, "module-apply-object-9");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-9");
var bound9 = receiverIdentity.bind(callTarget9);
assertThis(bound9() === callTarget9, "module-bind-9");
var arrow9 = ArrowSource.call(callTarget9, 11);
assertThis(arrow9() === callTarget9, "module-arrow-9");
var box9 = new Box(12);
assertThis(box9.self === box9 && box9.value === 12, "module-constructor-9");
var access9 = makeAccessorSlot(13);
assertThis(access9.slot === 13 && access9.seen === access9, "module-getter-9");
access9.slot = 14;
assertThis(access9.value === 14 && access9.seen === access9, "module-setter-9");
assertThis(sloppyIdentity() === undefined, "module-plain-10");
assertThis(strictIdentity() === undefined, "module-explicit-10");
var methodTarget10 = { value: 10, method: receiverIdentity };
assertThis(methodTarget10.method() === methodTarget10, "module-method-10");
var detached10 = methodTarget10.method;
assertThis(detached10() === undefined, "module-detached-10");
var callTarget10 = { value: 11 };
assertThis(receiverIdentity.call(callTarget10) === callTarget10, "module-call-object-10");
assertThis(receiverIdentity.apply(callTarget10, []) === callTarget10, "module-apply-object-10");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-10");
var bound10 = receiverIdentity.bind(callTarget10);
assertThis(bound10() === callTarget10, "module-bind-10");
var arrow10 = ArrowSource.call(callTarget10, 12);
assertThis(arrow10() === callTarget10, "module-arrow-10");
var box10 = new Box(13);
assertThis(box10.self === box10 && box10.value === 13, "module-constructor-10");
var access10 = makeAccessorSlot(14);
assertThis(access10.slot === 14 && access10.seen === access10, "module-getter-10");
access10.slot = 15;
assertThis(access10.value === 15 && access10.seen === access10, "module-setter-10");
assertThis(sloppyIdentity() === undefined, "module-plain-11");
assertThis(strictIdentity() === undefined, "module-explicit-11");
var methodTarget11 = { value: 11, method: receiverIdentity };
assertThis(methodTarget11.method() === methodTarget11, "module-method-11");
var detached11 = methodTarget11.method;
assertThis(detached11() === undefined, "module-detached-11");
var callTarget11 = { value: 12 };
assertThis(receiverIdentity.call(callTarget11) === callTarget11, "module-call-object-11");
assertThis(receiverIdentity.apply(callTarget11, []) === callTarget11, "module-apply-object-11");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-11");
var bound11 = receiverIdentity.bind(callTarget11);
assertThis(bound11() === callTarget11, "module-bind-11");
var arrow11 = ArrowSource.call(callTarget11, 13);
assertThis(arrow11() === callTarget11, "module-arrow-11");
var box11 = new Box(14);
assertThis(box11.self === box11 && box11.value === 14, "module-constructor-11");
var access11 = makeAccessorSlot(15);
assertThis(access11.slot === 15 && access11.seen === access11, "module-getter-11");
access11.slot = 16;
assertThis(access11.value === 16 && access11.seen === access11, "module-setter-11");
assertThis(sloppyIdentity() === undefined, "module-plain-12");
assertThis(strictIdentity() === undefined, "module-explicit-12");
var methodTarget12 = { value: 12, method: receiverIdentity };
assertThis(methodTarget12.method() === methodTarget12, "module-method-12");
var detached12 = methodTarget12.method;
assertThis(detached12() === undefined, "module-detached-12");
var callTarget12 = { value: 13 };
assertThis(receiverIdentity.call(callTarget12) === callTarget12, "module-call-object-12");
assertThis(receiverIdentity.apply(callTarget12, []) === callTarget12, "module-apply-object-12");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-12");
var bound12 = receiverIdentity.bind(callTarget12);
assertThis(bound12() === callTarget12, "module-bind-12");
var arrow12 = ArrowSource.call(callTarget12, 14);
assertThis(arrow12() === callTarget12, "module-arrow-12");
var box12 = new Box(15);
assertThis(box12.self === box12 && box12.value === 15, "module-constructor-12");
var access12 = makeAccessorSlot(16);
assertThis(access12.slot === 16 && access12.seen === access12, "module-getter-12");
access12.slot = 17;
assertThis(access12.value === 17 && access12.seen === access12, "module-setter-12");
assertThis(sloppyIdentity() === undefined, "module-plain-13");
assertThis(strictIdentity() === undefined, "module-explicit-13");
var methodTarget13 = { value: 13, method: receiverIdentity };
assertThis(methodTarget13.method() === methodTarget13, "module-method-13");
var detached13 = methodTarget13.method;
assertThis(detached13() === undefined, "module-detached-13");
var callTarget13 = { value: 14 };
assertThis(receiverIdentity.call(callTarget13) === callTarget13, "module-call-object-13");
assertThis(receiverIdentity.apply(callTarget13, []) === callTarget13, "module-apply-object-13");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-13");
var bound13 = receiverIdentity.bind(callTarget13);
assertThis(bound13() === callTarget13, "module-bind-13");
var arrow13 = ArrowSource.call(callTarget13, 15);
assertThis(arrow13() === callTarget13, "module-arrow-13");
var box13 = new Box(16);
assertThis(box13.self === box13 && box13.value === 16, "module-constructor-13");
var access13 = makeAccessorSlot(17);
assertThis(access13.slot === 17 && access13.seen === access13, "module-getter-13");
access13.slot = 18;
assertThis(access13.value === 18 && access13.seen === access13, "module-setter-13");
assertThis(sloppyIdentity() === undefined, "module-plain-14");
assertThis(strictIdentity() === undefined, "module-explicit-14");
var methodTarget14 = { value: 14, method: receiverIdentity };
assertThis(methodTarget14.method() === methodTarget14, "module-method-14");
var detached14 = methodTarget14.method;
assertThis(detached14() === undefined, "module-detached-14");
var callTarget14 = { value: 15 };
assertThis(receiverIdentity.call(callTarget14) === callTarget14, "module-call-object-14");
assertThis(receiverIdentity.apply(callTarget14, []) === callTarget14, "module-apply-object-14");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-14");
var bound14 = receiverIdentity.bind(callTarget14);
assertThis(bound14() === callTarget14, "module-bind-14");
var arrow14 = ArrowSource.call(callTarget14, 16);
assertThis(arrow14() === callTarget14, "module-arrow-14");
var box14 = new Box(17);
assertThis(box14.self === box14 && box14.value === 17, "module-constructor-14");
var access14 = makeAccessorSlot(18);
assertThis(access14.slot === 18 && access14.seen === access14, "module-getter-14");
access14.slot = 19;
assertThis(access14.value === 19 && access14.seen === access14, "module-setter-14");
assertThis(sloppyIdentity() === undefined, "module-plain-15");
assertThis(strictIdentity() === undefined, "module-explicit-15");
var methodTarget15 = { value: 15, method: receiverIdentity };
assertThis(methodTarget15.method() === methodTarget15, "module-method-15");
var detached15 = methodTarget15.method;
assertThis(detached15() === undefined, "module-detached-15");
var callTarget15 = { value: 16 };
assertThis(receiverIdentity.call(callTarget15) === callTarget15, "module-call-object-15");
assertThis(receiverIdentity.apply(callTarget15, []) === callTarget15, "module-apply-object-15");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-15");
var bound15 = receiverIdentity.bind(callTarget15);
assertThis(bound15() === callTarget15, "module-bind-15");
var arrow15 = ArrowSource.call(callTarget15, 17);
assertThis(arrow15() === callTarget15, "module-arrow-15");
var box15 = new Box(18);
assertThis(box15.self === box15 && box15.value === 18, "module-constructor-15");
var access15 = makeAccessorSlot(19);
assertThis(access15.slot === 19 && access15.seen === access15, "module-getter-15");
access15.slot = 20;
assertThis(access15.value === 20 && access15.seen === access15, "module-setter-15");
assertThis(sloppyIdentity() === undefined, "module-plain-16");
assertThis(strictIdentity() === undefined, "module-explicit-16");
var methodTarget16 = { value: 16, method: receiverIdentity };
assertThis(methodTarget16.method() === methodTarget16, "module-method-16");
var detached16 = methodTarget16.method;
assertThis(detached16() === undefined, "module-detached-16");
var callTarget16 = { value: 17 };
assertThis(receiverIdentity.call(callTarget16) === callTarget16, "module-call-object-16");
assertThis(receiverIdentity.apply(callTarget16, []) === callTarget16, "module-apply-object-16");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-16");
var bound16 = receiverIdentity.bind(callTarget16);
assertThis(bound16() === callTarget16, "module-bind-16");
var arrow16 = ArrowSource.call(callTarget16, 18);
assertThis(arrow16() === callTarget16, "module-arrow-16");
var box16 = new Box(19);
assertThis(box16.self === box16 && box16.value === 19, "module-constructor-16");
var access16 = makeAccessorSlot(20);
assertThis(access16.slot === 20 && access16.seen === access16, "module-getter-16");
access16.slot = 21;
assertThis(access16.value === 21 && access16.seen === access16, "module-setter-16");
assertThis(sloppyIdentity() === undefined, "module-plain-17");
assertThis(strictIdentity() === undefined, "module-explicit-17");
var methodTarget17 = { value: 17, method: receiverIdentity };
assertThis(methodTarget17.method() === methodTarget17, "module-method-17");
var detached17 = methodTarget17.method;
assertThis(detached17() === undefined, "module-detached-17");
var callTarget17 = { value: 18 };
assertThis(receiverIdentity.call(callTarget17) === callTarget17, "module-call-object-17");
assertThis(receiverIdentity.apply(callTarget17, []) === callTarget17, "module-apply-object-17");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-17");
var bound17 = receiverIdentity.bind(callTarget17);
assertThis(bound17() === callTarget17, "module-bind-17");
var arrow17 = ArrowSource.call(callTarget17, 19);
assertThis(arrow17() === callTarget17, "module-arrow-17");
var box17 = new Box(20);
assertThis(box17.self === box17 && box17.value === 20, "module-constructor-17");
var access17 = makeAccessorSlot(21);
assertThis(access17.slot === 21 && access17.seen === access17, "module-getter-17");
access17.slot = 22;
assertThis(access17.value === 22 && access17.seen === access17, "module-setter-17");
assertThis(sloppyIdentity() === undefined, "module-plain-18");
assertThis(strictIdentity() === undefined, "module-explicit-18");
var methodTarget18 = { value: 18, method: receiverIdentity };
assertThis(methodTarget18.method() === methodTarget18, "module-method-18");
var detached18 = methodTarget18.method;
assertThis(detached18() === undefined, "module-detached-18");
var callTarget18 = { value: 19 };
assertThis(receiverIdentity.call(callTarget18) === callTarget18, "module-call-object-18");
assertThis(receiverIdentity.apply(callTarget18, []) === callTarget18, "module-apply-object-18");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-18");
var bound18 = receiverIdentity.bind(callTarget18);
assertThis(bound18() === callTarget18, "module-bind-18");
var arrow18 = ArrowSource.call(callTarget18, 20);
assertThis(arrow18() === callTarget18, "module-arrow-18");
var box18 = new Box(21);
assertThis(box18.self === box18 && box18.value === 21, "module-constructor-18");
var access18 = makeAccessorSlot(22);
assertThis(access18.slot === 22 && access18.seen === access18, "module-getter-18");
access18.slot = 23;
assertThis(access18.value === 23 && access18.seen === access18, "module-setter-18");
assertThis(sloppyIdentity() === undefined, "module-plain-19");
assertThis(strictIdentity() === undefined, "module-explicit-19");
var methodTarget19 = { value: 19, method: receiverIdentity };
assertThis(methodTarget19.method() === methodTarget19, "module-method-19");
var detached19 = methodTarget19.method;
assertThis(detached19() === undefined, "module-detached-19");
var callTarget19 = { value: 20 };
assertThis(receiverIdentity.call(callTarget19) === callTarget19, "module-call-object-19");
assertThis(receiverIdentity.apply(callTarget19, []) === callTarget19, "module-apply-object-19");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-19");
var bound19 = receiverIdentity.bind(callTarget19);
assertThis(bound19() === callTarget19, "module-bind-19");
var arrow19 = ArrowSource.call(callTarget19, 21);
assertThis(arrow19() === callTarget19, "module-arrow-19");
var box19 = new Box(22);
assertThis(box19.self === box19 && box19.value === 22, "module-constructor-19");
var access19 = makeAccessorSlot(23);
assertThis(access19.slot === 23 && access19.seen === access19, "module-getter-19");
access19.slot = 24;
assertThis(access19.value === 24 && access19.seen === access19, "module-setter-19");
assertThis(sloppyIdentity() === undefined, "module-plain-20");
assertThis(strictIdentity() === undefined, "module-explicit-20");
var methodTarget20 = { value: 20, method: receiverIdentity };
assertThis(methodTarget20.method() === methodTarget20, "module-method-20");
var detached20 = methodTarget20.method;
assertThis(detached20() === undefined, "module-detached-20");
var callTarget20 = { value: 21 };
assertThis(receiverIdentity.call(callTarget20) === callTarget20, "module-call-object-20");
assertThis(receiverIdentity.apply(callTarget20, []) === callTarget20, "module-apply-object-20");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-20");
var bound20 = receiverIdentity.bind(callTarget20);
assertThis(bound20() === callTarget20, "module-bind-20");
var arrow20 = ArrowSource.call(callTarget20, 22);
assertThis(arrow20() === callTarget20, "module-arrow-20");
var box20 = new Box(23);
assertThis(box20.self === box20 && box20.value === 23, "module-constructor-20");
var access20 = makeAccessorSlot(24);
assertThis(access20.slot === 24 && access20.seen === access20, "module-getter-20");
access20.slot = 25;
assertThis(access20.value === 25 && access20.seen === access20, "module-setter-20");
assertThis(sloppyIdentity() === undefined, "module-plain-21");
assertThis(strictIdentity() === undefined, "module-explicit-21");
var methodTarget21 = { value: 21, method: receiverIdentity };
assertThis(methodTarget21.method() === methodTarget21, "module-method-21");
var detached21 = methodTarget21.method;
assertThis(detached21() === undefined, "module-detached-21");
var callTarget21 = { value: 22 };
assertThis(receiverIdentity.call(callTarget21) === callTarget21, "module-call-object-21");
assertThis(receiverIdentity.apply(callTarget21, []) === callTarget21, "module-apply-object-21");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-21");
var bound21 = receiverIdentity.bind(callTarget21);
assertThis(bound21() === callTarget21, "module-bind-21");
var arrow21 = ArrowSource.call(callTarget21, 23);
assertThis(arrow21() === callTarget21, "module-arrow-21");
var box21 = new Box(24);
assertThis(box21.self === box21 && box21.value === 24, "module-constructor-21");
var access21 = makeAccessorSlot(25);
assertThis(access21.slot === 25 && access21.seen === access21, "module-getter-21");
access21.slot = 26;
assertThis(access21.value === 26 && access21.seen === access21, "module-setter-21");
assertThis(sloppyIdentity() === undefined, "module-plain-22");
assertThis(strictIdentity() === undefined, "module-explicit-22");
var methodTarget22 = { value: 22, method: receiverIdentity };
assertThis(methodTarget22.method() === methodTarget22, "module-method-22");
var detached22 = methodTarget22.method;
assertThis(detached22() === undefined, "module-detached-22");
var callTarget22 = { value: 23 };
assertThis(receiverIdentity.call(callTarget22) === callTarget22, "module-call-object-22");
assertThis(receiverIdentity.apply(callTarget22, []) === callTarget22, "module-apply-object-22");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-22");
var bound22 = receiverIdentity.bind(callTarget22);
assertThis(bound22() === callTarget22, "module-bind-22");
var arrow22 = ArrowSource.call(callTarget22, 24);
assertThis(arrow22() === callTarget22, "module-arrow-22");
var box22 = new Box(25);
assertThis(box22.self === box22 && box22.value === 25, "module-constructor-22");
var access22 = makeAccessorSlot(26);
assertThis(access22.slot === 26 && access22.seen === access22, "module-getter-22");
access22.slot = 27;
assertThis(access22.value === 27 && access22.seen === access22, "module-setter-22");
assertThis(sloppyIdentity() === undefined, "module-plain-23");
assertThis(strictIdentity() === undefined, "module-explicit-23");
var methodTarget23 = { value: 23, method: receiverIdentity };
assertThis(methodTarget23.method() === methodTarget23, "module-method-23");
var detached23 = methodTarget23.method;
assertThis(detached23() === undefined, "module-detached-23");
var callTarget23 = { value: 24 };
assertThis(receiverIdentity.call(callTarget23) === callTarget23, "module-call-object-23");
assertThis(receiverIdentity.apply(callTarget23, []) === callTarget23, "module-apply-object-23");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-23");
var bound23 = receiverIdentity.bind(callTarget23);
assertThis(bound23() === callTarget23, "module-bind-23");
var arrow23 = ArrowSource.call(callTarget23, 25);
assertThis(arrow23() === callTarget23, "module-arrow-23");
var box23 = new Box(26);
assertThis(box23.self === box23 && box23.value === 26, "module-constructor-23");
var access23 = makeAccessorSlot(27);
assertThis(access23.slot === 27 && access23.seen === access23, "module-getter-23");
access23.slot = 28;
assertThis(access23.value === 28 && access23.seen === access23, "module-setter-23");
assertThis(sloppyIdentity() === undefined, "module-plain-24");
assertThis(strictIdentity() === undefined, "module-explicit-24");
var methodTarget24 = { value: 24, method: receiverIdentity };
assertThis(methodTarget24.method() === methodTarget24, "module-method-24");
var detached24 = methodTarget24.method;
assertThis(detached24() === undefined, "module-detached-24");
var callTarget24 = { value: 25 };
assertThis(receiverIdentity.call(callTarget24) === callTarget24, "module-call-object-24");
assertThis(receiverIdentity.apply(callTarget24, []) === callTarget24, "module-apply-object-24");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-24");
var bound24 = receiverIdentity.bind(callTarget24);
assertThis(bound24() === callTarget24, "module-bind-24");
var arrow24 = ArrowSource.call(callTarget24, 26);
assertThis(arrow24() === callTarget24, "module-arrow-24");
var box24 = new Box(27);
assertThis(box24.self === box24 && box24.value === 27, "module-constructor-24");
var access24 = makeAccessorSlot(28);
assertThis(access24.slot === 28 && access24.seen === access24, "module-getter-24");
access24.slot = 29;
assertThis(access24.value === 29 && access24.seen === access24, "module-setter-24");
assertThis(sloppyIdentity() === undefined, "module-plain-25");
assertThis(strictIdentity() === undefined, "module-explicit-25");
var methodTarget25 = { value: 25, method: receiverIdentity };
assertThis(methodTarget25.method() === methodTarget25, "module-method-25");
var detached25 = methodTarget25.method;
assertThis(detached25() === undefined, "module-detached-25");
var callTarget25 = { value: 26 };
assertThis(receiverIdentity.call(callTarget25) === callTarget25, "module-call-object-25");
assertThis(receiverIdentity.apply(callTarget25, []) === callTarget25, "module-apply-object-25");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-25");
var bound25 = receiverIdentity.bind(callTarget25);
assertThis(bound25() === callTarget25, "module-bind-25");
var arrow25 = ArrowSource.call(callTarget25, 27);
assertThis(arrow25() === callTarget25, "module-arrow-25");
var box25 = new Box(28);
assertThis(box25.self === box25 && box25.value === 28, "module-constructor-25");
var access25 = makeAccessorSlot(29);
assertThis(access25.slot === 29 && access25.seen === access25, "module-getter-25");
access25.slot = 30;
assertThis(access25.value === 30 && access25.seen === access25, "module-setter-25");
assertThis(sloppyIdentity() === undefined, "module-plain-26");
assertThis(strictIdentity() === undefined, "module-explicit-26");
var methodTarget26 = { value: 26, method: receiverIdentity };
assertThis(methodTarget26.method() === methodTarget26, "module-method-26");
var detached26 = methodTarget26.method;
assertThis(detached26() === undefined, "module-detached-26");
var callTarget26 = { value: 27 };
assertThis(receiverIdentity.call(callTarget26) === callTarget26, "module-call-object-26");
assertThis(receiverIdentity.apply(callTarget26, []) === callTarget26, "module-apply-object-26");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-26");
var bound26 = receiverIdentity.bind(callTarget26);
assertThis(bound26() === callTarget26, "module-bind-26");
var arrow26 = ArrowSource.call(callTarget26, 28);
assertThis(arrow26() === callTarget26, "module-arrow-26");
var box26 = new Box(29);
assertThis(box26.self === box26 && box26.value === 29, "module-constructor-26");
var access26 = makeAccessorSlot(30);
assertThis(access26.slot === 30 && access26.seen === access26, "module-getter-26");
access26.slot = 31;
assertThis(access26.value === 31 && access26.seen === access26, "module-setter-26");
assertThis(sloppyIdentity() === undefined, "module-plain-27");
assertThis(strictIdentity() === undefined, "module-explicit-27");
var methodTarget27 = { value: 27, method: receiverIdentity };
assertThis(methodTarget27.method() === methodTarget27, "module-method-27");
var detached27 = methodTarget27.method;
assertThis(detached27() === undefined, "module-detached-27");
var callTarget27 = { value: 28 };
assertThis(receiverIdentity.call(callTarget27) === callTarget27, "module-call-object-27");
assertThis(receiverIdentity.apply(callTarget27, []) === callTarget27, "module-apply-object-27");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-27");
var bound27 = receiverIdentity.bind(callTarget27);
assertThis(bound27() === callTarget27, "module-bind-27");
var arrow27 = ArrowSource.call(callTarget27, 29);
assertThis(arrow27() === callTarget27, "module-arrow-27");
var box27 = new Box(30);
assertThis(box27.self === box27 && box27.value === 30, "module-constructor-27");
var access27 = makeAccessorSlot(31);
assertThis(access27.slot === 31 && access27.seen === access27, "module-getter-27");
access27.slot = 32;
assertThis(access27.value === 32 && access27.seen === access27, "module-setter-27");
assertThis(sloppyIdentity() === undefined, "module-plain-28");
assertThis(strictIdentity() === undefined, "module-explicit-28");
var methodTarget28 = { value: 28, method: receiverIdentity };
assertThis(methodTarget28.method() === methodTarget28, "module-method-28");
var detached28 = methodTarget28.method;
assertThis(detached28() === undefined, "module-detached-28");
var callTarget28 = { value: 29 };
assertThis(receiverIdentity.call(callTarget28) === callTarget28, "module-call-object-28");
assertThis(receiverIdentity.apply(callTarget28, []) === callTarget28, "module-apply-object-28");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-28");
var bound28 = receiverIdentity.bind(callTarget28);
assertThis(bound28() === callTarget28, "module-bind-28");
var arrow28 = ArrowSource.call(callTarget28, 30);
assertThis(arrow28() === callTarget28, "module-arrow-28");
var box28 = new Box(31);
assertThis(box28.self === box28 && box28.value === 31, "module-constructor-28");
var access28 = makeAccessorSlot(32);
assertThis(access28.slot === 32 && access28.seen === access28, "module-getter-28");
access28.slot = 33;
assertThis(access28.value === 33 && access28.seen === access28, "module-setter-28");
assertThis(sloppyIdentity() === undefined, "module-plain-29");
assertThis(strictIdentity() === undefined, "module-explicit-29");
var methodTarget29 = { value: 29, method: receiverIdentity };
assertThis(methodTarget29.method() === methodTarget29, "module-method-29");
var detached29 = methodTarget29.method;
assertThis(detached29() === undefined, "module-detached-29");
var callTarget29 = { value: 30 };
assertThis(receiverIdentity.call(callTarget29) === callTarget29, "module-call-object-29");
assertThis(receiverIdentity.apply(callTarget29, []) === callTarget29, "module-apply-object-29");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-29");
var bound29 = receiverIdentity.bind(callTarget29);
assertThis(bound29() === callTarget29, "module-bind-29");
var arrow29 = ArrowSource.call(callTarget29, 31);
assertThis(arrow29() === callTarget29, "module-arrow-29");
var box29 = new Box(32);
assertThis(box29.self === box29 && box29.value === 32, "module-constructor-29");
var access29 = makeAccessorSlot(33);
assertThis(access29.slot === 33 && access29.seen === access29, "module-getter-29");
access29.slot = 34;
assertThis(access29.value === 34 && access29.seen === access29, "module-setter-29");
assertThis(sloppyIdentity() === undefined, "module-plain-30");
assertThis(strictIdentity() === undefined, "module-explicit-30");
var methodTarget30 = { value: 30, method: receiverIdentity };
assertThis(methodTarget30.method() === methodTarget30, "module-method-30");
var detached30 = methodTarget30.method;
assertThis(detached30() === undefined, "module-detached-30");
var callTarget30 = { value: 31 };
assertThis(receiverIdentity.call(callTarget30) === callTarget30, "module-call-object-30");
assertThis(receiverIdentity.apply(callTarget30, []) === callTarget30, "module-apply-object-30");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-30");
var bound30 = receiverIdentity.bind(callTarget30);
assertThis(bound30() === callTarget30, "module-bind-30");
var arrow30 = ArrowSource.call(callTarget30, 32);
assertThis(arrow30() === callTarget30, "module-arrow-30");
var box30 = new Box(33);
assertThis(box30.self === box30 && box30.value === 33, "module-constructor-30");
var access30 = makeAccessorSlot(34);
assertThis(access30.slot === 34 && access30.seen === access30, "module-getter-30");
access30.slot = 35;
assertThis(access30.value === 35 && access30.seen === access30, "module-setter-30");
assertThis(sloppyIdentity() === undefined, "module-plain-31");
assertThis(strictIdentity() === undefined, "module-explicit-31");
var methodTarget31 = { value: 31, method: receiverIdentity };
assertThis(methodTarget31.method() === methodTarget31, "module-method-31");
var detached31 = methodTarget31.method;
assertThis(detached31() === undefined, "module-detached-31");
var callTarget31 = { value: 32 };
assertThis(receiverIdentity.call(callTarget31) === callTarget31, "module-call-object-31");
assertThis(receiverIdentity.apply(callTarget31, []) === callTarget31, "module-apply-object-31");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-31");
var bound31 = receiverIdentity.bind(callTarget31);
assertThis(bound31() === callTarget31, "module-bind-31");
var arrow31 = ArrowSource.call(callTarget31, 33);
assertThis(arrow31() === callTarget31, "module-arrow-31");
var box31 = new Box(34);
assertThis(box31.self === box31 && box31.value === 34, "module-constructor-31");
var access31 = makeAccessorSlot(35);
assertThis(access31.slot === 35 && access31.seen === access31, "module-getter-31");
access31.slot = 36;
assertThis(access31.value === 36 && access31.seen === access31, "module-setter-31");
assertThis(sloppyIdentity() === undefined, "module-plain-32");
assertThis(strictIdentity() === undefined, "module-explicit-32");
var methodTarget32 = { value: 32, method: receiverIdentity };
assertThis(methodTarget32.method() === methodTarget32, "module-method-32");
var detached32 = methodTarget32.method;
assertThis(detached32() === undefined, "module-detached-32");
var callTarget32 = { value: 33 };
assertThis(receiverIdentity.call(callTarget32) === callTarget32, "module-call-object-32");
assertThis(receiverIdentity.apply(callTarget32, []) === callTarget32, "module-apply-object-32");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-32");
var bound32 = receiverIdentity.bind(callTarget32);
assertThis(bound32() === callTarget32, "module-bind-32");
var arrow32 = ArrowSource.call(callTarget32, 34);
assertThis(arrow32() === callTarget32, "module-arrow-32");
var box32 = new Box(35);
assertThis(box32.self === box32 && box32.value === 35, "module-constructor-32");
var access32 = makeAccessorSlot(36);
assertThis(access32.slot === 36 && access32.seen === access32, "module-getter-32");
access32.slot = 37;
assertThis(access32.value === 37 && access32.seen === access32, "module-setter-32");
assertThis(sloppyIdentity() === undefined, "module-plain-33");
assertThis(strictIdentity() === undefined, "module-explicit-33");
var methodTarget33 = { value: 33, method: receiverIdentity };
assertThis(methodTarget33.method() === methodTarget33, "module-method-33");
var detached33 = methodTarget33.method;
assertThis(detached33() === undefined, "module-detached-33");
var callTarget33 = { value: 34 };
assertThis(receiverIdentity.call(callTarget33) === callTarget33, "module-call-object-33");
assertThis(receiverIdentity.apply(callTarget33, []) === callTarget33, "module-apply-object-33");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-33");
var bound33 = receiverIdentity.bind(callTarget33);
assertThis(bound33() === callTarget33, "module-bind-33");
var arrow33 = ArrowSource.call(callTarget33, 35);
assertThis(arrow33() === callTarget33, "module-arrow-33");
var box33 = new Box(36);
assertThis(box33.self === box33 && box33.value === 36, "module-constructor-33");
var access33 = makeAccessorSlot(37);
assertThis(access33.slot === 37 && access33.seen === access33, "module-getter-33");
access33.slot = 38;
assertThis(access33.value === 38 && access33.seen === access33, "module-setter-33");
assertThis(sloppyIdentity() === undefined, "module-plain-34");
assertThis(strictIdentity() === undefined, "module-explicit-34");
var methodTarget34 = { value: 34, method: receiverIdentity };
assertThis(methodTarget34.method() === methodTarget34, "module-method-34");
var detached34 = methodTarget34.method;
assertThis(detached34() === undefined, "module-detached-34");
var callTarget34 = { value: 35 };
assertThis(receiverIdentity.call(callTarget34) === callTarget34, "module-call-object-34");
assertThis(receiverIdentity.apply(callTarget34, []) === callTarget34, "module-apply-object-34");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-34");
var bound34 = receiverIdentity.bind(callTarget34);
assertThis(bound34() === callTarget34, "module-bind-34");
var arrow34 = ArrowSource.call(callTarget34, 36);
assertThis(arrow34() === callTarget34, "module-arrow-34");
var box34 = new Box(37);
assertThis(box34.self === box34 && box34.value === 37, "module-constructor-34");
var access34 = makeAccessorSlot(38);
assertThis(access34.slot === 38 && access34.seen === access34, "module-getter-34");
access34.slot = 39;
assertThis(access34.value === 39 && access34.seen === access34, "module-setter-34");
assertThis(sloppyIdentity() === undefined, "module-plain-35");
assertThis(strictIdentity() === undefined, "module-explicit-35");
var methodTarget35 = { value: 35, method: receiverIdentity };
assertThis(methodTarget35.method() === methodTarget35, "module-method-35");
var detached35 = methodTarget35.method;
assertThis(detached35() === undefined, "module-detached-35");
var callTarget35 = { value: 36 };
assertThis(receiverIdentity.call(callTarget35) === callTarget35, "module-call-object-35");
assertThis(receiverIdentity.apply(callTarget35, []) === callTarget35, "module-apply-object-35");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-35");
var bound35 = receiverIdentity.bind(callTarget35);
assertThis(bound35() === callTarget35, "module-bind-35");
var arrow35 = ArrowSource.call(callTarget35, 37);
assertThis(arrow35() === callTarget35, "module-arrow-35");
var box35 = new Box(38);
assertThis(box35.self === box35 && box35.value === 38, "module-constructor-35");
var access35 = makeAccessorSlot(39);
assertThis(access35.slot === 39 && access35.seen === access35, "module-getter-35");
access35.slot = 40;
assertThis(access35.value === 40 && access35.seen === access35, "module-setter-35");
assertThis(sloppyIdentity() === undefined, "module-plain-36");
assertThis(strictIdentity() === undefined, "module-explicit-36");
var methodTarget36 = { value: 36, method: receiverIdentity };
assertThis(methodTarget36.method() === methodTarget36, "module-method-36");
var detached36 = methodTarget36.method;
assertThis(detached36() === undefined, "module-detached-36");
var callTarget36 = { value: 37 };
assertThis(receiverIdentity.call(callTarget36) === callTarget36, "module-call-object-36");
assertThis(receiverIdentity.apply(callTarget36, []) === callTarget36, "module-apply-object-36");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-36");
var bound36 = receiverIdentity.bind(callTarget36);
assertThis(bound36() === callTarget36, "module-bind-36");
var arrow36 = ArrowSource.call(callTarget36, 38);
assertThis(arrow36() === callTarget36, "module-arrow-36");
var box36 = new Box(39);
assertThis(box36.self === box36 && box36.value === 39, "module-constructor-36");
var access36 = makeAccessorSlot(40);
assertThis(access36.slot === 40 && access36.seen === access36, "module-getter-36");
access36.slot = 41;
assertThis(access36.value === 41 && access36.seen === access36, "module-setter-36");
assertThis(sloppyIdentity() === undefined, "module-plain-37");
assertThis(strictIdentity() === undefined, "module-explicit-37");
var methodTarget37 = { value: 37, method: receiverIdentity };
assertThis(methodTarget37.method() === methodTarget37, "module-method-37");
var detached37 = methodTarget37.method;
assertThis(detached37() === undefined, "module-detached-37");
var callTarget37 = { value: 38 };
assertThis(receiverIdentity.call(callTarget37) === callTarget37, "module-call-object-37");
assertThis(receiverIdentity.apply(callTarget37, []) === callTarget37, "module-apply-object-37");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-37");
var bound37 = receiverIdentity.bind(callTarget37);
assertThis(bound37() === callTarget37, "module-bind-37");
var arrow37 = ArrowSource.call(callTarget37, 39);
assertThis(arrow37() === callTarget37, "module-arrow-37");
var box37 = new Box(40);
assertThis(box37.self === box37 && box37.value === 40, "module-constructor-37");
var access37 = makeAccessorSlot(41);
assertThis(access37.slot === 41 && access37.seen === access37, "module-getter-37");
access37.slot = 42;
assertThis(access37.value === 42 && access37.seen === access37, "module-setter-37");
assertThis(sloppyIdentity() === undefined, "module-plain-38");
assertThis(strictIdentity() === undefined, "module-explicit-38");
var methodTarget38 = { value: 38, method: receiverIdentity };
assertThis(methodTarget38.method() === methodTarget38, "module-method-38");
var detached38 = methodTarget38.method;
assertThis(detached38() === undefined, "module-detached-38");
var callTarget38 = { value: 39 };
assertThis(receiverIdentity.call(callTarget38) === callTarget38, "module-call-object-38");
assertThis(receiverIdentity.apply(callTarget38, []) === callTarget38, "module-apply-object-38");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-38");
var bound38 = receiverIdentity.bind(callTarget38);
assertThis(bound38() === callTarget38, "module-bind-38");
var arrow38 = ArrowSource.call(callTarget38, 40);
assertThis(arrow38() === callTarget38, "module-arrow-38");
var box38 = new Box(41);
assertThis(box38.self === box38 && box38.value === 41, "module-constructor-38");
var access38 = makeAccessorSlot(42);
assertThis(access38.slot === 42 && access38.seen === access38, "module-getter-38");
access38.slot = 43;
assertThis(access38.value === 43 && access38.seen === access38, "module-setter-38");
assertThis(sloppyIdentity() === undefined, "module-plain-39");
assertThis(strictIdentity() === undefined, "module-explicit-39");
var methodTarget39 = { value: 39, method: receiverIdentity };
assertThis(methodTarget39.method() === methodTarget39, "module-method-39");
var detached39 = methodTarget39.method;
assertThis(detached39() === undefined, "module-detached-39");
var callTarget39 = { value: 40 };
assertThis(receiverIdentity.call(callTarget39) === callTarget39, "module-call-object-39");
assertThis(receiverIdentity.apply(callTarget39, []) === callTarget39, "module-apply-object-39");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-39");
var bound39 = receiverIdentity.bind(callTarget39);
assertThis(bound39() === callTarget39, "module-bind-39");
var arrow39 = ArrowSource.call(callTarget39, 41);
assertThis(arrow39() === callTarget39, "module-arrow-39");
var box39 = new Box(42);
assertThis(box39.self === box39 && box39.value === 42, "module-constructor-39");
var access39 = makeAccessorSlot(43);
assertThis(access39.slot === 43 && access39.seen === access39, "module-getter-39");
access39.slot = 44;
assertThis(access39.value === 44 && access39.seen === access39, "module-setter-39");
assertThis(sloppyIdentity() === undefined, "module-plain-40");
assertThis(strictIdentity() === undefined, "module-explicit-40");
var methodTarget40 = { value: 40, method: receiverIdentity };
assertThis(methodTarget40.method() === methodTarget40, "module-method-40");
var detached40 = methodTarget40.method;
assertThis(detached40() === undefined, "module-detached-40");
var callTarget40 = { value: 41 };
assertThis(receiverIdentity.call(callTarget40) === callTarget40, "module-call-object-40");
assertThis(receiverIdentity.apply(callTarget40, []) === callTarget40, "module-apply-object-40");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-40");
var bound40 = receiverIdentity.bind(callTarget40);
assertThis(bound40() === callTarget40, "module-bind-40");
var arrow40 = ArrowSource.call(callTarget40, 42);
assertThis(arrow40() === callTarget40, "module-arrow-40");
var box40 = new Box(43);
assertThis(box40.self === box40 && box40.value === 43, "module-constructor-40");
var access40 = makeAccessorSlot(44);
assertThis(access40.slot === 44 && access40.seen === access40, "module-getter-40");
access40.slot = 45;
assertThis(access40.value === 45 && access40.seen === access40, "module-setter-40");
assertThis(sloppyIdentity() === undefined, "module-plain-41");
assertThis(strictIdentity() === undefined, "module-explicit-41");
var methodTarget41 = { value: 41, method: receiverIdentity };
assertThis(methodTarget41.method() === methodTarget41, "module-method-41");
var detached41 = methodTarget41.method;
assertThis(detached41() === undefined, "module-detached-41");
var callTarget41 = { value: 42 };
assertThis(receiverIdentity.call(callTarget41) === callTarget41, "module-call-object-41");
assertThis(receiverIdentity.apply(callTarget41, []) === callTarget41, "module-apply-object-41");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-41");
var bound41 = receiverIdentity.bind(callTarget41);
assertThis(bound41() === callTarget41, "module-bind-41");
var arrow41 = ArrowSource.call(callTarget41, 43);
assertThis(arrow41() === callTarget41, "module-arrow-41");
var box41 = new Box(44);
assertThis(box41.self === box41 && box41.value === 44, "module-constructor-41");
var access41 = makeAccessorSlot(45);
assertThis(access41.slot === 45 && access41.seen === access41, "module-getter-41");
access41.slot = 46;
assertThis(access41.value === 46 && access41.seen === access41, "module-setter-41");
assertThis(sloppyIdentity() === undefined, "module-plain-42");
assertThis(strictIdentity() === undefined, "module-explicit-42");
var methodTarget42 = { value: 42, method: receiverIdentity };
assertThis(methodTarget42.method() === methodTarget42, "module-method-42");
var detached42 = methodTarget42.method;
assertThis(detached42() === undefined, "module-detached-42");
var callTarget42 = { value: 43 };
assertThis(receiverIdentity.call(callTarget42) === callTarget42, "module-call-object-42");
assertThis(receiverIdentity.apply(callTarget42, []) === callTarget42, "module-apply-object-42");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-42");
var bound42 = receiverIdentity.bind(callTarget42);
assertThis(bound42() === callTarget42, "module-bind-42");
var arrow42 = ArrowSource.call(callTarget42, 44);
assertThis(arrow42() === callTarget42, "module-arrow-42");
var box42 = new Box(45);
assertThis(box42.self === box42 && box42.value === 45, "module-constructor-42");
var access42 = makeAccessorSlot(46);
assertThis(access42.slot === 46 && access42.seen === access42, "module-getter-42");
access42.slot = 47;
assertThis(access42.value === 47 && access42.seen === access42, "module-setter-42");
assertThis(sloppyIdentity() === undefined, "module-plain-43");
assertThis(strictIdentity() === undefined, "module-explicit-43");
var methodTarget43 = { value: 43, method: receiverIdentity };
assertThis(methodTarget43.method() === methodTarget43, "module-method-43");
var detached43 = methodTarget43.method;
assertThis(detached43() === undefined, "module-detached-43");
var callTarget43 = { value: 44 };
assertThis(receiverIdentity.call(callTarget43) === callTarget43, "module-call-object-43");
assertThis(receiverIdentity.apply(callTarget43, []) === callTarget43, "module-apply-object-43");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-43");
var bound43 = receiverIdentity.bind(callTarget43);
assertThis(bound43() === callTarget43, "module-bind-43");
var arrow43 = ArrowSource.call(callTarget43, 45);
assertThis(arrow43() === callTarget43, "module-arrow-43");
var box43 = new Box(46);
assertThis(box43.self === box43 && box43.value === 46, "module-constructor-43");
var access43 = makeAccessorSlot(47);
assertThis(access43.slot === 47 && access43.seen === access43, "module-getter-43");
access43.slot = 48;
assertThis(access43.value === 48 && access43.seen === access43, "module-setter-43");
assertThis(sloppyIdentity() === undefined, "module-plain-44");
assertThis(strictIdentity() === undefined, "module-explicit-44");
var methodTarget44 = { value: 44, method: receiverIdentity };
assertThis(methodTarget44.method() === methodTarget44, "module-method-44");
var detached44 = methodTarget44.method;
assertThis(detached44() === undefined, "module-detached-44");
var callTarget44 = { value: 45 };
assertThis(receiverIdentity.call(callTarget44) === callTarget44, "module-call-object-44");
assertThis(receiverIdentity.apply(callTarget44, []) === callTarget44, "module-apply-object-44");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-44");
var bound44 = receiverIdentity.bind(callTarget44);
assertThis(bound44() === callTarget44, "module-bind-44");
var arrow44 = ArrowSource.call(callTarget44, 46);
assertThis(arrow44() === callTarget44, "module-arrow-44");
var box44 = new Box(47);
assertThis(box44.self === box44 && box44.value === 47, "module-constructor-44");
var access44 = makeAccessorSlot(48);
assertThis(access44.slot === 48 && access44.seen === access44, "module-getter-44");
access44.slot = 49;
assertThis(access44.value === 49 && access44.seen === access44, "module-setter-44");
assertThis(sloppyIdentity() === undefined, "module-plain-45");
assertThis(strictIdentity() === undefined, "module-explicit-45");
var methodTarget45 = { value: 45, method: receiverIdentity };
assertThis(methodTarget45.method() === methodTarget45, "module-method-45");
var detached45 = methodTarget45.method;
assertThis(detached45() === undefined, "module-detached-45");
var callTarget45 = { value: 46 };
assertThis(receiverIdentity.call(callTarget45) === callTarget45, "module-call-object-45");
assertThis(receiverIdentity.apply(callTarget45, []) === callTarget45, "module-apply-object-45");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-45");
var bound45 = receiverIdentity.bind(callTarget45);
assertThis(bound45() === callTarget45, "module-bind-45");
var arrow45 = ArrowSource.call(callTarget45, 47);
assertThis(arrow45() === callTarget45, "module-arrow-45");
var box45 = new Box(48);
assertThis(box45.self === box45 && box45.value === 48, "module-constructor-45");
var access45 = makeAccessorSlot(49);
assertThis(access45.slot === 49 && access45.seen === access45, "module-getter-45");
access45.slot = 50;
assertThis(access45.value === 50 && access45.seen === access45, "module-setter-45");
assertThis(sloppyIdentity() === undefined, "module-plain-46");
assertThis(strictIdentity() === undefined, "module-explicit-46");
var methodTarget46 = { value: 46, method: receiverIdentity };
assertThis(methodTarget46.method() === methodTarget46, "module-method-46");
var detached46 = methodTarget46.method;
assertThis(detached46() === undefined, "module-detached-46");
var callTarget46 = { value: 47 };
assertThis(receiverIdentity.call(callTarget46) === callTarget46, "module-call-object-46");
assertThis(receiverIdentity.apply(callTarget46, []) === callTarget46, "module-apply-object-46");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-46");
var bound46 = receiverIdentity.bind(callTarget46);
assertThis(bound46() === callTarget46, "module-bind-46");
var arrow46 = ArrowSource.call(callTarget46, 48);
assertThis(arrow46() === callTarget46, "module-arrow-46");
var box46 = new Box(49);
assertThis(box46.self === box46 && box46.value === 49, "module-constructor-46");
var access46 = makeAccessorSlot(50);
assertThis(access46.slot === 50 && access46.seen === access46, "module-getter-46");
access46.slot = 51;
assertThis(access46.value === 51 && access46.seen === access46, "module-setter-46");
assertThis(sloppyIdentity() === undefined, "module-plain-47");
assertThis(strictIdentity() === undefined, "module-explicit-47");
var methodTarget47 = { value: 47, method: receiverIdentity };
assertThis(methodTarget47.method() === methodTarget47, "module-method-47");
var detached47 = methodTarget47.method;
assertThis(detached47() === undefined, "module-detached-47");
var callTarget47 = { value: 48 };
assertThis(receiverIdentity.call(callTarget47) === callTarget47, "module-call-object-47");
assertThis(receiverIdentity.apply(callTarget47, []) === callTarget47, "module-apply-object-47");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-47");
var bound47 = receiverIdentity.bind(callTarget47);
assertThis(bound47() === callTarget47, "module-bind-47");
var arrow47 = ArrowSource.call(callTarget47, 49);
assertThis(arrow47() === callTarget47, "module-arrow-47");
var box47 = new Box(50);
assertThis(box47.self === box47 && box47.value === 50, "module-constructor-47");
var access47 = makeAccessorSlot(51);
assertThis(access47.slot === 51 && access47.seen === access47, "module-getter-47");
access47.slot = 52;
assertThis(access47.value === 52 && access47.seen === access47, "module-setter-47");
assertThis(sloppyIdentity() === undefined, "module-plain-48");
assertThis(strictIdentity() === undefined, "module-explicit-48");
var methodTarget48 = { value: 48, method: receiverIdentity };
assertThis(methodTarget48.method() === methodTarget48, "module-method-48");
var detached48 = methodTarget48.method;
assertThis(detached48() === undefined, "module-detached-48");
var callTarget48 = { value: 49 };
assertThis(receiverIdentity.call(callTarget48) === callTarget48, "module-call-object-48");
assertThis(receiverIdentity.apply(callTarget48, []) === callTarget48, "module-apply-object-48");
assertThis(receiverIdentity.call(undefined) === undefined, "module-call-undefined-48");
var bound48 = receiverIdentity.bind(callTarget48);
assertThis(bound48() === callTarget48, "module-bind-48");
var arrow48 = ArrowSource.call(callTarget48, 50);
assertThis(arrow48() === callTarget48, "module-arrow-48");
var box48 = new Box(51);
assertThis(box48.self === box48 && box48.value === 51, "module-constructor-48");
var access48 = makeAccessorSlot(52);
assertThis(access48.slot === 52 && access48.seen === access48, "module-getter-48");
access48.slot = 53;
assertThis(access48.value === 53 && access48.seen === access48, "module-setter-48");
console.log("ok", score);
