// behavior: this-resolves-current-this-binding
// expected: pass
// goal: script
// size: large
// variant: script.strict

var score = 0;
function assertThis(condition, name) {
if (!condition) { throw new Error(name); }
score = score + 1;
}
function strictIdentity() { "use strict"; return this; }
function sloppyIdentity() { return this; }
function receiverIdentity() { return this; }
function ArrowSource(value) { this.value = value; return (() => this); }
function Box(value) { this.value = value; this.self = this; }
function makeAccessorSlot(value) {
var target = { value: value, seen: null };
Object.defineProperty(target, "slot", {
get: function() { this.seen = this; return this.value; },
set: function(next) { this.seen = this; this.value = next; },
configurable: true
});
return target;
}
assertThis(sloppyIdentity() === undefined, "strict-plain-0");
assertThis(strictIdentity() === undefined, "strict-explicit-0");
var methodTarget0 = { value: 0, method: receiverIdentity };
assertThis(methodTarget0.method() === methodTarget0, "strict-method-0");
var detached0 = methodTarget0.method;
assertThis(detached0() === undefined, "strict-detached-0");
var callTarget0 = { value: 1 };
assertThis(receiverIdentity.call(callTarget0) === callTarget0, "strict-call-object-0");
assertThis(receiverIdentity.apply(callTarget0, []) === callTarget0, "strict-apply-object-0");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-0");
assertThis(receiverIdentity.call(2) === 2, "strict-call-primitive-0");
var bound0 = receiverIdentity.bind(callTarget0);
assertThis(bound0() === callTarget0, "strict-bind-0");
var arrow0 = ArrowSource.call(callTarget0, 3);
assertThis(arrow0() === callTarget0, "strict-arrow-0");
var box0 = new Box(4);
assertThis(box0.self === box0 && box0.value === 4, "strict-constructor-0");
var access0 = makeAccessorSlot(5);
assertThis(access0.slot === 5 && access0.seen === access0, "strict-getter-0");
access0.slot = 6;
assertThis(access0.value === 6 && access0.seen === access0, "strict-setter-0");
assertThis(sloppyIdentity() === undefined, "strict-plain-1");
assertThis(strictIdentity() === undefined, "strict-explicit-1");
var methodTarget1 = { value: 1, method: receiverIdentity };
assertThis(methodTarget1.method() === methodTarget1, "strict-method-1");
var detached1 = methodTarget1.method;
assertThis(detached1() === undefined, "strict-detached-1");
var callTarget1 = { value: 2 };
assertThis(receiverIdentity.call(callTarget1) === callTarget1, "strict-call-object-1");
assertThis(receiverIdentity.apply(callTarget1, []) === callTarget1, "strict-apply-object-1");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-1");
assertThis(receiverIdentity.call(3) === 3, "strict-call-primitive-1");
var bound1 = receiverIdentity.bind(callTarget1);
assertThis(bound1() === callTarget1, "strict-bind-1");
var arrow1 = ArrowSource.call(callTarget1, 4);
assertThis(arrow1() === callTarget1, "strict-arrow-1");
var box1 = new Box(5);
assertThis(box1.self === box1 && box1.value === 5, "strict-constructor-1");
var access1 = makeAccessorSlot(6);
assertThis(access1.slot === 6 && access1.seen === access1, "strict-getter-1");
access1.slot = 7;
assertThis(access1.value === 7 && access1.seen === access1, "strict-setter-1");
assertThis(sloppyIdentity() === undefined, "strict-plain-2");
assertThis(strictIdentity() === undefined, "strict-explicit-2");
var methodTarget2 = { value: 2, method: receiverIdentity };
assertThis(methodTarget2.method() === methodTarget2, "strict-method-2");
var detached2 = methodTarget2.method;
assertThis(detached2() === undefined, "strict-detached-2");
var callTarget2 = { value: 3 };
assertThis(receiverIdentity.call(callTarget2) === callTarget2, "strict-call-object-2");
assertThis(receiverIdentity.apply(callTarget2, []) === callTarget2, "strict-apply-object-2");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-2");
assertThis(receiverIdentity.call(4) === 4, "strict-call-primitive-2");
var bound2 = receiverIdentity.bind(callTarget2);
assertThis(bound2() === callTarget2, "strict-bind-2");
var arrow2 = ArrowSource.call(callTarget2, 5);
assertThis(arrow2() === callTarget2, "strict-arrow-2");
var box2 = new Box(6);
assertThis(box2.self === box2 && box2.value === 6, "strict-constructor-2");
var access2 = makeAccessorSlot(7);
assertThis(access2.slot === 7 && access2.seen === access2, "strict-getter-2");
access2.slot = 8;
assertThis(access2.value === 8 && access2.seen === access2, "strict-setter-2");
assertThis(sloppyIdentity() === undefined, "strict-plain-3");
assertThis(strictIdentity() === undefined, "strict-explicit-3");
var methodTarget3 = { value: 3, method: receiverIdentity };
assertThis(methodTarget3.method() === methodTarget3, "strict-method-3");
var detached3 = methodTarget3.method;
assertThis(detached3() === undefined, "strict-detached-3");
var callTarget3 = { value: 4 };
assertThis(receiverIdentity.call(callTarget3) === callTarget3, "strict-call-object-3");
assertThis(receiverIdentity.apply(callTarget3, []) === callTarget3, "strict-apply-object-3");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-3");
assertThis(receiverIdentity.call(5) === 5, "strict-call-primitive-3");
var bound3 = receiverIdentity.bind(callTarget3);
assertThis(bound3() === callTarget3, "strict-bind-3");
var arrow3 = ArrowSource.call(callTarget3, 6);
assertThis(arrow3() === callTarget3, "strict-arrow-3");
var box3 = new Box(7);
assertThis(box3.self === box3 && box3.value === 7, "strict-constructor-3");
var access3 = makeAccessorSlot(8);
assertThis(access3.slot === 8 && access3.seen === access3, "strict-getter-3");
access3.slot = 9;
assertThis(access3.value === 9 && access3.seen === access3, "strict-setter-3");
assertThis(sloppyIdentity() === undefined, "strict-plain-4");
assertThis(strictIdentity() === undefined, "strict-explicit-4");
var methodTarget4 = { value: 4, method: receiverIdentity };
assertThis(methodTarget4.method() === methodTarget4, "strict-method-4");
var detached4 = methodTarget4.method;
assertThis(detached4() === undefined, "strict-detached-4");
var callTarget4 = { value: 5 };
assertThis(receiverIdentity.call(callTarget4) === callTarget4, "strict-call-object-4");
assertThis(receiverIdentity.apply(callTarget4, []) === callTarget4, "strict-apply-object-4");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-4");
assertThis(receiverIdentity.call(6) === 6, "strict-call-primitive-4");
var bound4 = receiverIdentity.bind(callTarget4);
assertThis(bound4() === callTarget4, "strict-bind-4");
var arrow4 = ArrowSource.call(callTarget4, 7);
assertThis(arrow4() === callTarget4, "strict-arrow-4");
var box4 = new Box(8);
assertThis(box4.self === box4 && box4.value === 8, "strict-constructor-4");
var access4 = makeAccessorSlot(9);
assertThis(access4.slot === 9 && access4.seen === access4, "strict-getter-4");
access4.slot = 10;
assertThis(access4.value === 10 && access4.seen === access4, "strict-setter-4");
assertThis(sloppyIdentity() === undefined, "strict-plain-5");
assertThis(strictIdentity() === undefined, "strict-explicit-5");
var methodTarget5 = { value: 5, method: receiverIdentity };
assertThis(methodTarget5.method() === methodTarget5, "strict-method-5");
var detached5 = methodTarget5.method;
assertThis(detached5() === undefined, "strict-detached-5");
var callTarget5 = { value: 6 };
assertThis(receiverIdentity.call(callTarget5) === callTarget5, "strict-call-object-5");
assertThis(receiverIdentity.apply(callTarget5, []) === callTarget5, "strict-apply-object-5");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-5");
assertThis(receiverIdentity.call(7) === 7, "strict-call-primitive-5");
var bound5 = receiverIdentity.bind(callTarget5);
assertThis(bound5() === callTarget5, "strict-bind-5");
var arrow5 = ArrowSource.call(callTarget5, 8);
assertThis(arrow5() === callTarget5, "strict-arrow-5");
var box5 = new Box(9);
assertThis(box5.self === box5 && box5.value === 9, "strict-constructor-5");
var access5 = makeAccessorSlot(10);
assertThis(access5.slot === 10 && access5.seen === access5, "strict-getter-5");
access5.slot = 11;
assertThis(access5.value === 11 && access5.seen === access5, "strict-setter-5");
assertThis(sloppyIdentity() === undefined, "strict-plain-6");
assertThis(strictIdentity() === undefined, "strict-explicit-6");
var methodTarget6 = { value: 6, method: receiverIdentity };
assertThis(methodTarget6.method() === methodTarget6, "strict-method-6");
var detached6 = methodTarget6.method;
assertThis(detached6() === undefined, "strict-detached-6");
var callTarget6 = { value: 7 };
assertThis(receiverIdentity.call(callTarget6) === callTarget6, "strict-call-object-6");
assertThis(receiverIdentity.apply(callTarget6, []) === callTarget6, "strict-apply-object-6");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-6");
assertThis(receiverIdentity.call(8) === 8, "strict-call-primitive-6");
var bound6 = receiverIdentity.bind(callTarget6);
assertThis(bound6() === callTarget6, "strict-bind-6");
var arrow6 = ArrowSource.call(callTarget6, 9);
assertThis(arrow6() === callTarget6, "strict-arrow-6");
var box6 = new Box(10);
assertThis(box6.self === box6 && box6.value === 10, "strict-constructor-6");
var access6 = makeAccessorSlot(11);
assertThis(access6.slot === 11 && access6.seen === access6, "strict-getter-6");
access6.slot = 12;
assertThis(access6.value === 12 && access6.seen === access6, "strict-setter-6");
assertThis(sloppyIdentity() === undefined, "strict-plain-7");
assertThis(strictIdentity() === undefined, "strict-explicit-7");
var methodTarget7 = { value: 7, method: receiverIdentity };
assertThis(methodTarget7.method() === methodTarget7, "strict-method-7");
var detached7 = methodTarget7.method;
assertThis(detached7() === undefined, "strict-detached-7");
var callTarget7 = { value: 8 };
assertThis(receiverIdentity.call(callTarget7) === callTarget7, "strict-call-object-7");
assertThis(receiverIdentity.apply(callTarget7, []) === callTarget7, "strict-apply-object-7");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-7");
assertThis(receiverIdentity.call(9) === 9, "strict-call-primitive-7");
var bound7 = receiverIdentity.bind(callTarget7);
assertThis(bound7() === callTarget7, "strict-bind-7");
var arrow7 = ArrowSource.call(callTarget7, 10);
assertThis(arrow7() === callTarget7, "strict-arrow-7");
var box7 = new Box(11);
assertThis(box7.self === box7 && box7.value === 11, "strict-constructor-7");
var access7 = makeAccessorSlot(12);
assertThis(access7.slot === 12 && access7.seen === access7, "strict-getter-7");
access7.slot = 13;
assertThis(access7.value === 13 && access7.seen === access7, "strict-setter-7");
assertThis(sloppyIdentity() === undefined, "strict-plain-8");
assertThis(strictIdentity() === undefined, "strict-explicit-8");
var methodTarget8 = { value: 8, method: receiverIdentity };
assertThis(methodTarget8.method() === methodTarget8, "strict-method-8");
var detached8 = methodTarget8.method;
assertThis(detached8() === undefined, "strict-detached-8");
var callTarget8 = { value: 9 };
assertThis(receiverIdentity.call(callTarget8) === callTarget8, "strict-call-object-8");
assertThis(receiverIdentity.apply(callTarget8, []) === callTarget8, "strict-apply-object-8");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-8");
assertThis(receiverIdentity.call(10) === 10, "strict-call-primitive-8");
var bound8 = receiverIdentity.bind(callTarget8);
assertThis(bound8() === callTarget8, "strict-bind-8");
var arrow8 = ArrowSource.call(callTarget8, 11);
assertThis(arrow8() === callTarget8, "strict-arrow-8");
var box8 = new Box(12);
assertThis(box8.self === box8 && box8.value === 12, "strict-constructor-8");
var access8 = makeAccessorSlot(13);
assertThis(access8.slot === 13 && access8.seen === access8, "strict-getter-8");
access8.slot = 14;
assertThis(access8.value === 14 && access8.seen === access8, "strict-setter-8");
assertThis(sloppyIdentity() === undefined, "strict-plain-9");
assertThis(strictIdentity() === undefined, "strict-explicit-9");
var methodTarget9 = { value: 9, method: receiverIdentity };
assertThis(methodTarget9.method() === methodTarget9, "strict-method-9");
var detached9 = methodTarget9.method;
assertThis(detached9() === undefined, "strict-detached-9");
var callTarget9 = { value: 10 };
assertThis(receiverIdentity.call(callTarget9) === callTarget9, "strict-call-object-9");
assertThis(receiverIdentity.apply(callTarget9, []) === callTarget9, "strict-apply-object-9");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-9");
assertThis(receiverIdentity.call(11) === 11, "strict-call-primitive-9");
var bound9 = receiverIdentity.bind(callTarget9);
assertThis(bound9() === callTarget9, "strict-bind-9");
var arrow9 = ArrowSource.call(callTarget9, 12);
assertThis(arrow9() === callTarget9, "strict-arrow-9");
var box9 = new Box(13);
assertThis(box9.self === box9 && box9.value === 13, "strict-constructor-9");
var access9 = makeAccessorSlot(14);
assertThis(access9.slot === 14 && access9.seen === access9, "strict-getter-9");
access9.slot = 15;
assertThis(access9.value === 15 && access9.seen === access9, "strict-setter-9");
assertThis(sloppyIdentity() === undefined, "strict-plain-10");
assertThis(strictIdentity() === undefined, "strict-explicit-10");
var methodTarget10 = { value: 10, method: receiverIdentity };
assertThis(methodTarget10.method() === methodTarget10, "strict-method-10");
var detached10 = methodTarget10.method;
assertThis(detached10() === undefined, "strict-detached-10");
var callTarget10 = { value: 11 };
assertThis(receiverIdentity.call(callTarget10) === callTarget10, "strict-call-object-10");
assertThis(receiverIdentity.apply(callTarget10, []) === callTarget10, "strict-apply-object-10");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-10");
assertThis(receiverIdentity.call(12) === 12, "strict-call-primitive-10");
var bound10 = receiverIdentity.bind(callTarget10);
assertThis(bound10() === callTarget10, "strict-bind-10");
var arrow10 = ArrowSource.call(callTarget10, 13);
assertThis(arrow10() === callTarget10, "strict-arrow-10");
var box10 = new Box(14);
assertThis(box10.self === box10 && box10.value === 14, "strict-constructor-10");
var access10 = makeAccessorSlot(15);
assertThis(access10.slot === 15 && access10.seen === access10, "strict-getter-10");
access10.slot = 16;
assertThis(access10.value === 16 && access10.seen === access10, "strict-setter-10");
assertThis(sloppyIdentity() === undefined, "strict-plain-11");
assertThis(strictIdentity() === undefined, "strict-explicit-11");
var methodTarget11 = { value: 11, method: receiverIdentity };
assertThis(methodTarget11.method() === methodTarget11, "strict-method-11");
var detached11 = methodTarget11.method;
assertThis(detached11() === undefined, "strict-detached-11");
var callTarget11 = { value: 12 };
assertThis(receiverIdentity.call(callTarget11) === callTarget11, "strict-call-object-11");
assertThis(receiverIdentity.apply(callTarget11, []) === callTarget11, "strict-apply-object-11");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-11");
assertThis(receiverIdentity.call(13) === 13, "strict-call-primitive-11");
var bound11 = receiverIdentity.bind(callTarget11);
assertThis(bound11() === callTarget11, "strict-bind-11");
var arrow11 = ArrowSource.call(callTarget11, 14);
assertThis(arrow11() === callTarget11, "strict-arrow-11");
var box11 = new Box(15);
assertThis(box11.self === box11 && box11.value === 15, "strict-constructor-11");
var access11 = makeAccessorSlot(16);
assertThis(access11.slot === 16 && access11.seen === access11, "strict-getter-11");
access11.slot = 17;
assertThis(access11.value === 17 && access11.seen === access11, "strict-setter-11");
assertThis(sloppyIdentity() === undefined, "strict-plain-12");
assertThis(strictIdentity() === undefined, "strict-explicit-12");
var methodTarget12 = { value: 12, method: receiverIdentity };
assertThis(methodTarget12.method() === methodTarget12, "strict-method-12");
var detached12 = methodTarget12.method;
assertThis(detached12() === undefined, "strict-detached-12");
var callTarget12 = { value: 13 };
assertThis(receiverIdentity.call(callTarget12) === callTarget12, "strict-call-object-12");
assertThis(receiverIdentity.apply(callTarget12, []) === callTarget12, "strict-apply-object-12");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-12");
assertThis(receiverIdentity.call(14) === 14, "strict-call-primitive-12");
var bound12 = receiverIdentity.bind(callTarget12);
assertThis(bound12() === callTarget12, "strict-bind-12");
var arrow12 = ArrowSource.call(callTarget12, 15);
assertThis(arrow12() === callTarget12, "strict-arrow-12");
var box12 = new Box(16);
assertThis(box12.self === box12 && box12.value === 16, "strict-constructor-12");
var access12 = makeAccessorSlot(17);
assertThis(access12.slot === 17 && access12.seen === access12, "strict-getter-12");
access12.slot = 18;
assertThis(access12.value === 18 && access12.seen === access12, "strict-setter-12");
assertThis(sloppyIdentity() === undefined, "strict-plain-13");
assertThis(strictIdentity() === undefined, "strict-explicit-13");
var methodTarget13 = { value: 13, method: receiverIdentity };
assertThis(methodTarget13.method() === methodTarget13, "strict-method-13");
var detached13 = methodTarget13.method;
assertThis(detached13() === undefined, "strict-detached-13");
var callTarget13 = { value: 14 };
assertThis(receiverIdentity.call(callTarget13) === callTarget13, "strict-call-object-13");
assertThis(receiverIdentity.apply(callTarget13, []) === callTarget13, "strict-apply-object-13");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-13");
assertThis(receiverIdentity.call(15) === 15, "strict-call-primitive-13");
var bound13 = receiverIdentity.bind(callTarget13);
assertThis(bound13() === callTarget13, "strict-bind-13");
var arrow13 = ArrowSource.call(callTarget13, 16);
assertThis(arrow13() === callTarget13, "strict-arrow-13");
var box13 = new Box(17);
assertThis(box13.self === box13 && box13.value === 17, "strict-constructor-13");
var access13 = makeAccessorSlot(18);
assertThis(access13.slot === 18 && access13.seen === access13, "strict-getter-13");
access13.slot = 19;
assertThis(access13.value === 19 && access13.seen === access13, "strict-setter-13");
assertThis(sloppyIdentity() === undefined, "strict-plain-14");
assertThis(strictIdentity() === undefined, "strict-explicit-14");
var methodTarget14 = { value: 14, method: receiverIdentity };
assertThis(methodTarget14.method() === methodTarget14, "strict-method-14");
var detached14 = methodTarget14.method;
assertThis(detached14() === undefined, "strict-detached-14");
var callTarget14 = { value: 15 };
assertThis(receiverIdentity.call(callTarget14) === callTarget14, "strict-call-object-14");
assertThis(receiverIdentity.apply(callTarget14, []) === callTarget14, "strict-apply-object-14");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-14");
assertThis(receiverIdentity.call(16) === 16, "strict-call-primitive-14");
var bound14 = receiverIdentity.bind(callTarget14);
assertThis(bound14() === callTarget14, "strict-bind-14");
var arrow14 = ArrowSource.call(callTarget14, 17);
assertThis(arrow14() === callTarget14, "strict-arrow-14");
var box14 = new Box(18);
assertThis(box14.self === box14 && box14.value === 18, "strict-constructor-14");
var access14 = makeAccessorSlot(19);
assertThis(access14.slot === 19 && access14.seen === access14, "strict-getter-14");
access14.slot = 20;
assertThis(access14.value === 20 && access14.seen === access14, "strict-setter-14");
assertThis(sloppyIdentity() === undefined, "strict-plain-15");
assertThis(strictIdentity() === undefined, "strict-explicit-15");
var methodTarget15 = { value: 15, method: receiverIdentity };
assertThis(methodTarget15.method() === methodTarget15, "strict-method-15");
var detached15 = methodTarget15.method;
assertThis(detached15() === undefined, "strict-detached-15");
var callTarget15 = { value: 16 };
assertThis(receiverIdentity.call(callTarget15) === callTarget15, "strict-call-object-15");
assertThis(receiverIdentity.apply(callTarget15, []) === callTarget15, "strict-apply-object-15");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-15");
assertThis(receiverIdentity.call(17) === 17, "strict-call-primitive-15");
var bound15 = receiverIdentity.bind(callTarget15);
assertThis(bound15() === callTarget15, "strict-bind-15");
var arrow15 = ArrowSource.call(callTarget15, 18);
assertThis(arrow15() === callTarget15, "strict-arrow-15");
var box15 = new Box(19);
assertThis(box15.self === box15 && box15.value === 19, "strict-constructor-15");
var access15 = makeAccessorSlot(20);
assertThis(access15.slot === 20 && access15.seen === access15, "strict-getter-15");
access15.slot = 21;
assertThis(access15.value === 21 && access15.seen === access15, "strict-setter-15");
assertThis(sloppyIdentity() === undefined, "strict-plain-16");
assertThis(strictIdentity() === undefined, "strict-explicit-16");
var methodTarget16 = { value: 16, method: receiverIdentity };
assertThis(methodTarget16.method() === methodTarget16, "strict-method-16");
var detached16 = methodTarget16.method;
assertThis(detached16() === undefined, "strict-detached-16");
var callTarget16 = { value: 17 };
assertThis(receiverIdentity.call(callTarget16) === callTarget16, "strict-call-object-16");
assertThis(receiverIdentity.apply(callTarget16, []) === callTarget16, "strict-apply-object-16");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-16");
assertThis(receiverIdentity.call(18) === 18, "strict-call-primitive-16");
var bound16 = receiverIdentity.bind(callTarget16);
assertThis(bound16() === callTarget16, "strict-bind-16");
var arrow16 = ArrowSource.call(callTarget16, 19);
assertThis(arrow16() === callTarget16, "strict-arrow-16");
var box16 = new Box(20);
assertThis(box16.self === box16 && box16.value === 20, "strict-constructor-16");
var access16 = makeAccessorSlot(21);
assertThis(access16.slot === 21 && access16.seen === access16, "strict-getter-16");
access16.slot = 22;
assertThis(access16.value === 22 && access16.seen === access16, "strict-setter-16");
assertThis(sloppyIdentity() === undefined, "strict-plain-17");
assertThis(strictIdentity() === undefined, "strict-explicit-17");
var methodTarget17 = { value: 17, method: receiverIdentity };
assertThis(methodTarget17.method() === methodTarget17, "strict-method-17");
var detached17 = methodTarget17.method;
assertThis(detached17() === undefined, "strict-detached-17");
var callTarget17 = { value: 18 };
assertThis(receiverIdentity.call(callTarget17) === callTarget17, "strict-call-object-17");
assertThis(receiverIdentity.apply(callTarget17, []) === callTarget17, "strict-apply-object-17");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-17");
assertThis(receiverIdentity.call(19) === 19, "strict-call-primitive-17");
var bound17 = receiverIdentity.bind(callTarget17);
assertThis(bound17() === callTarget17, "strict-bind-17");
var arrow17 = ArrowSource.call(callTarget17, 20);
assertThis(arrow17() === callTarget17, "strict-arrow-17");
var box17 = new Box(21);
assertThis(box17.self === box17 && box17.value === 21, "strict-constructor-17");
var access17 = makeAccessorSlot(22);
assertThis(access17.slot === 22 && access17.seen === access17, "strict-getter-17");
access17.slot = 23;
assertThis(access17.value === 23 && access17.seen === access17, "strict-setter-17");
assertThis(sloppyIdentity() === undefined, "strict-plain-18");
assertThis(strictIdentity() === undefined, "strict-explicit-18");
var methodTarget18 = { value: 18, method: receiverIdentity };
assertThis(methodTarget18.method() === methodTarget18, "strict-method-18");
var detached18 = methodTarget18.method;
assertThis(detached18() === undefined, "strict-detached-18");
var callTarget18 = { value: 19 };
assertThis(receiverIdentity.call(callTarget18) === callTarget18, "strict-call-object-18");
assertThis(receiverIdentity.apply(callTarget18, []) === callTarget18, "strict-apply-object-18");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-18");
assertThis(receiverIdentity.call(20) === 20, "strict-call-primitive-18");
var bound18 = receiverIdentity.bind(callTarget18);
assertThis(bound18() === callTarget18, "strict-bind-18");
var arrow18 = ArrowSource.call(callTarget18, 21);
assertThis(arrow18() === callTarget18, "strict-arrow-18");
var box18 = new Box(22);
assertThis(box18.self === box18 && box18.value === 22, "strict-constructor-18");
var access18 = makeAccessorSlot(23);
assertThis(access18.slot === 23 && access18.seen === access18, "strict-getter-18");
access18.slot = 24;
assertThis(access18.value === 24 && access18.seen === access18, "strict-setter-18");
assertThis(sloppyIdentity() === undefined, "strict-plain-19");
assertThis(strictIdentity() === undefined, "strict-explicit-19");
var methodTarget19 = { value: 19, method: receiverIdentity };
assertThis(methodTarget19.method() === methodTarget19, "strict-method-19");
var detached19 = methodTarget19.method;
assertThis(detached19() === undefined, "strict-detached-19");
var callTarget19 = { value: 20 };
assertThis(receiverIdentity.call(callTarget19) === callTarget19, "strict-call-object-19");
assertThis(receiverIdentity.apply(callTarget19, []) === callTarget19, "strict-apply-object-19");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-19");
assertThis(receiverIdentity.call(21) === 21, "strict-call-primitive-19");
var bound19 = receiverIdentity.bind(callTarget19);
assertThis(bound19() === callTarget19, "strict-bind-19");
var arrow19 = ArrowSource.call(callTarget19, 22);
assertThis(arrow19() === callTarget19, "strict-arrow-19");
var box19 = new Box(23);
assertThis(box19.self === box19 && box19.value === 23, "strict-constructor-19");
var access19 = makeAccessorSlot(24);
assertThis(access19.slot === 24 && access19.seen === access19, "strict-getter-19");
access19.slot = 25;
assertThis(access19.value === 25 && access19.seen === access19, "strict-setter-19");
assertThis(sloppyIdentity() === undefined, "strict-plain-20");
assertThis(strictIdentity() === undefined, "strict-explicit-20");
var methodTarget20 = { value: 20, method: receiverIdentity };
assertThis(methodTarget20.method() === methodTarget20, "strict-method-20");
var detached20 = methodTarget20.method;
assertThis(detached20() === undefined, "strict-detached-20");
var callTarget20 = { value: 21 };
assertThis(receiverIdentity.call(callTarget20) === callTarget20, "strict-call-object-20");
assertThis(receiverIdentity.apply(callTarget20, []) === callTarget20, "strict-apply-object-20");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-20");
assertThis(receiverIdentity.call(22) === 22, "strict-call-primitive-20");
var bound20 = receiverIdentity.bind(callTarget20);
assertThis(bound20() === callTarget20, "strict-bind-20");
var arrow20 = ArrowSource.call(callTarget20, 23);
assertThis(arrow20() === callTarget20, "strict-arrow-20");
var box20 = new Box(24);
assertThis(box20.self === box20 && box20.value === 24, "strict-constructor-20");
var access20 = makeAccessorSlot(25);
assertThis(access20.slot === 25 && access20.seen === access20, "strict-getter-20");
access20.slot = 26;
assertThis(access20.value === 26 && access20.seen === access20, "strict-setter-20");
assertThis(sloppyIdentity() === undefined, "strict-plain-21");
assertThis(strictIdentity() === undefined, "strict-explicit-21");
var methodTarget21 = { value: 21, method: receiverIdentity };
assertThis(methodTarget21.method() === methodTarget21, "strict-method-21");
var detached21 = methodTarget21.method;
assertThis(detached21() === undefined, "strict-detached-21");
var callTarget21 = { value: 22 };
assertThis(receiverIdentity.call(callTarget21) === callTarget21, "strict-call-object-21");
assertThis(receiverIdentity.apply(callTarget21, []) === callTarget21, "strict-apply-object-21");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-21");
assertThis(receiverIdentity.call(23) === 23, "strict-call-primitive-21");
var bound21 = receiverIdentity.bind(callTarget21);
assertThis(bound21() === callTarget21, "strict-bind-21");
var arrow21 = ArrowSource.call(callTarget21, 24);
assertThis(arrow21() === callTarget21, "strict-arrow-21");
var box21 = new Box(25);
assertThis(box21.self === box21 && box21.value === 25, "strict-constructor-21");
var access21 = makeAccessorSlot(26);
assertThis(access21.slot === 26 && access21.seen === access21, "strict-getter-21");
access21.slot = 27;
assertThis(access21.value === 27 && access21.seen === access21, "strict-setter-21");
assertThis(sloppyIdentity() === undefined, "strict-plain-22");
assertThis(strictIdentity() === undefined, "strict-explicit-22");
var methodTarget22 = { value: 22, method: receiverIdentity };
assertThis(methodTarget22.method() === methodTarget22, "strict-method-22");
var detached22 = methodTarget22.method;
assertThis(detached22() === undefined, "strict-detached-22");
var callTarget22 = { value: 23 };
assertThis(receiverIdentity.call(callTarget22) === callTarget22, "strict-call-object-22");
assertThis(receiverIdentity.apply(callTarget22, []) === callTarget22, "strict-apply-object-22");
assertThis(receiverIdentity.call(null) === null, "strict-call-null-22");
assertThis(receiverIdentity.call(24) === 24, "strict-call-primitive-22");
var bound22 = receiverIdentity.bind(callTarget22);
assertThis(bound22() === callTarget22, "strict-bind-22");
var arrow22 = ArrowSource.call(callTarget22, 25);
assertThis(arrow22() === callTarget22, "strict-arrow-22");
var box22 = new Box(26);
assertThis(box22.self === box22 && box22.value === 26, "strict-constructor-22");
var access22 = makeAccessorSlot(27);
assertThis(access22.slot === 27 && access22.seen === access22, "strict-getter-22");
access22.slot = 28;
assertThis(access22.value === 28 && access22.seen === access22, "strict-setter-22");
console.log("ok", score);
