// behavior: trailing-comma-does-not-add-element
// expected: pass
// goal: script
// size: large
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}
var noExtraElement0 = [41,];
check(noExtraElement0.length === 1, 'single trailing length 0');
check((0 in noExtraElement0) && !(1 in noExtraElement0), 'single trailing properties 0');
check(noExtraElement0[0] === 41, 'single trailing value 0');
var twoTrailing0 = [41, 42,];
check(twoTrailing0.length === 2, 'two trailing length 0');
check(twoTrailing0[0] === 41 && twoTrailing0[1] === 42, 'two trailing values 0');
check(!(2 in twoTrailing0), 'two trailing no property 0');
var elisionAfterComma0 = [41,,];
check(elisionAfterComma0.length === 2, 'elision trailing length 0');
check((0 in elisionAfterComma0) && !(1 in elisionAfterComma0), 'elision trailing properties 0');
var noExtraElement1 = [42,];
check(noExtraElement1.length === 1, 'single trailing length 1');
check((0 in noExtraElement1) && !(1 in noExtraElement1), 'single trailing properties 1');
check(noExtraElement1[0] === 42, 'single trailing value 1');
var twoTrailing1 = [42, 43,];
check(twoTrailing1.length === 2, 'two trailing length 1');
check(twoTrailing1[0] === 42 && twoTrailing1[1] === 43, 'two trailing values 1');
check(!(2 in twoTrailing1), 'two trailing no property 1');
var elisionAfterComma1 = [42,,];
check(elisionAfterComma1.length === 2, 'elision trailing length 1');
check((0 in elisionAfterComma1) && !(1 in elisionAfterComma1), 'elision trailing properties 1');
var noExtraElement2 = [43,];
check(noExtraElement2.length === 1, 'single trailing length 2');
check((0 in noExtraElement2) && !(1 in noExtraElement2), 'single trailing properties 2');
check(noExtraElement2[0] === 43, 'single trailing value 2');
var twoTrailing2 = [43, 44,];
check(twoTrailing2.length === 2, 'two trailing length 2');
check(twoTrailing2[0] === 43 && twoTrailing2[1] === 44, 'two trailing values 2');
check(!(2 in twoTrailing2), 'two trailing no property 2');
var elisionAfterComma2 = [43,,];
check(elisionAfterComma2.length === 2, 'elision trailing length 2');
check((0 in elisionAfterComma2) && !(1 in elisionAfterComma2), 'elision trailing properties 2');
var noExtraElement3 = [44,];
check(noExtraElement3.length === 1, 'single trailing length 3');
check((0 in noExtraElement3) && !(1 in noExtraElement3), 'single trailing properties 3');
check(noExtraElement3[0] === 44, 'single trailing value 3');
var twoTrailing3 = [44, 45,];
check(twoTrailing3.length === 2, 'two trailing length 3');
check(twoTrailing3[0] === 44 && twoTrailing3[1] === 45, 'two trailing values 3');
check(!(2 in twoTrailing3), 'two trailing no property 3');
var elisionAfterComma3 = [44,,];
check(elisionAfterComma3.length === 2, 'elision trailing length 3');
check((0 in elisionAfterComma3) && !(1 in elisionAfterComma3), 'elision trailing properties 3');
var noExtraElement4 = [45,];
check(noExtraElement4.length === 1, 'single trailing length 4');
check((0 in noExtraElement4) && !(1 in noExtraElement4), 'single trailing properties 4');
check(noExtraElement4[0] === 45, 'single trailing value 4');
var twoTrailing4 = [45, 46,];
check(twoTrailing4.length === 2, 'two trailing length 4');
check(twoTrailing4[0] === 45 && twoTrailing4[1] === 46, 'two trailing values 4');
check(!(2 in twoTrailing4), 'two trailing no property 4');
var elisionAfterComma4 = [45,,];
check(elisionAfterComma4.length === 2, 'elision trailing length 4');
check((0 in elisionAfterComma4) && !(1 in elisionAfterComma4), 'elision trailing properties 4');
var noExtraElement5 = [46,];
check(noExtraElement5.length === 1, 'single trailing length 5');
check((0 in noExtraElement5) && !(1 in noExtraElement5), 'single trailing properties 5');
check(noExtraElement5[0] === 46, 'single trailing value 5');
var twoTrailing5 = [46, 47,];
check(twoTrailing5.length === 2, 'two trailing length 5');
check(twoTrailing5[0] === 46 && twoTrailing5[1] === 47, 'two trailing values 5');
check(!(2 in twoTrailing5), 'two trailing no property 5');
var elisionAfterComma5 = [46,,];
check(elisionAfterComma5.length === 2, 'elision trailing length 5');
check((0 in elisionAfterComma5) && !(1 in elisionAfterComma5), 'elision trailing properties 5');
var noExtraElement6 = [47,];
check(noExtraElement6.length === 1, 'single trailing length 6');
check((0 in noExtraElement6) && !(1 in noExtraElement6), 'single trailing properties 6');
check(noExtraElement6[0] === 47, 'single trailing value 6');
var twoTrailing6 = [47, 48,];
check(twoTrailing6.length === 2, 'two trailing length 6');
check(twoTrailing6[0] === 47 && twoTrailing6[1] === 48, 'two trailing values 6');
check(!(2 in twoTrailing6), 'two trailing no property 6');
var elisionAfterComma6 = [47,,];
check(elisionAfterComma6.length === 2, 'elision trailing length 6');
check((0 in elisionAfterComma6) && !(1 in elisionAfterComma6), 'elision trailing properties 6');
var noExtraElement7 = [48,];
check(noExtraElement7.length === 1, 'single trailing length 7');
check((0 in noExtraElement7) && !(1 in noExtraElement7), 'single trailing properties 7');
check(noExtraElement7[0] === 48, 'single trailing value 7');
var twoTrailing7 = [48, 49,];
check(twoTrailing7.length === 2, 'two trailing length 7');
check(twoTrailing7[0] === 48 && twoTrailing7[1] === 49, 'two trailing values 7');
check(!(2 in twoTrailing7), 'two trailing no property 7');
var elisionAfterComma7 = [48,,];
check(elisionAfterComma7.length === 2, 'elision trailing length 7');
check((0 in elisionAfterComma7) && !(1 in elisionAfterComma7), 'elision trailing properties 7');
var noExtraElement8 = [49,];
check(noExtraElement8.length === 1, 'single trailing length 8');
check((0 in noExtraElement8) && !(1 in noExtraElement8), 'single trailing properties 8');
check(noExtraElement8[0] === 49, 'single trailing value 8');
var twoTrailing8 = [49, 50,];
check(twoTrailing8.length === 2, 'two trailing length 8');
check(twoTrailing8[0] === 49 && twoTrailing8[1] === 50, 'two trailing values 8');
check(!(2 in twoTrailing8), 'two trailing no property 8');
var elisionAfterComma8 = [49,,];
check(elisionAfterComma8.length === 2, 'elision trailing length 8');
check((0 in elisionAfterComma8) && !(1 in elisionAfterComma8), 'elision trailing properties 8');
var noExtraElement9 = [50,];
check(noExtraElement9.length === 1, 'single trailing length 9');
check((0 in noExtraElement9) && !(1 in noExtraElement9), 'single trailing properties 9');
check(noExtraElement9[0] === 50, 'single trailing value 9');
var twoTrailing9 = [50, 51,];
check(twoTrailing9.length === 2, 'two trailing length 9');
check(twoTrailing9[0] === 50 && twoTrailing9[1] === 51, 'two trailing values 9');
check(!(2 in twoTrailing9), 'two trailing no property 9');
var elisionAfterComma9 = [50,,];
check(elisionAfterComma9.length === 2, 'elision trailing length 9');
check((0 in elisionAfterComma9) && !(1 in elisionAfterComma9), 'elision trailing properties 9');
var noExtraElement10 = [51,];
check(noExtraElement10.length === 1, 'single trailing length 10');
check((0 in noExtraElement10) && !(1 in noExtraElement10), 'single trailing properties 10');
check(noExtraElement10[0] === 51, 'single trailing value 10');
var twoTrailing10 = [51, 52,];
check(twoTrailing10.length === 2, 'two trailing length 10');
check(twoTrailing10[0] === 51 && twoTrailing10[1] === 52, 'two trailing values 10');
check(!(2 in twoTrailing10), 'two trailing no property 10');
var elisionAfterComma10 = [51,,];
check(elisionAfterComma10.length === 2, 'elision trailing length 10');
check((0 in elisionAfterComma10) && !(1 in elisionAfterComma10), 'elision trailing properties 10');
var noExtraElement11 = [52,];
check(noExtraElement11.length === 1, 'single trailing length 11');
check((0 in noExtraElement11) && !(1 in noExtraElement11), 'single trailing properties 11');
check(noExtraElement11[0] === 52, 'single trailing value 11');
var twoTrailing11 = [52, 53,];
check(twoTrailing11.length === 2, 'two trailing length 11');
check(twoTrailing11[0] === 52 && twoTrailing11[1] === 53, 'two trailing values 11');
check(!(2 in twoTrailing11), 'two trailing no property 11');
var elisionAfterComma11 = [52,,];
check(elisionAfterComma11.length === 2, 'elision trailing length 11');
check((0 in elisionAfterComma11) && !(1 in elisionAfterComma11), 'elision trailing properties 11');
var noExtraElement12 = [53,];
check(noExtraElement12.length === 1, 'single trailing length 12');
check((0 in noExtraElement12) && !(1 in noExtraElement12), 'single trailing properties 12');
check(noExtraElement12[0] === 53, 'single trailing value 12');
var twoTrailing12 = [53, 54,];
check(twoTrailing12.length === 2, 'two trailing length 12');
check(twoTrailing12[0] === 53 && twoTrailing12[1] === 54, 'two trailing values 12');
check(!(2 in twoTrailing12), 'two trailing no property 12');
var elisionAfterComma12 = [53,,];
check(elisionAfterComma12.length === 2, 'elision trailing length 12');
check((0 in elisionAfterComma12) && !(1 in elisionAfterComma12), 'elision trailing properties 12');
var noExtraElement13 = [54,];
check(noExtraElement13.length === 1, 'single trailing length 13');
check((0 in noExtraElement13) && !(1 in noExtraElement13), 'single trailing properties 13');
check(noExtraElement13[0] === 54, 'single trailing value 13');
var twoTrailing13 = [54, 55,];
check(twoTrailing13.length === 2, 'two trailing length 13');
check(twoTrailing13[0] === 54 && twoTrailing13[1] === 55, 'two trailing values 13');
check(!(2 in twoTrailing13), 'two trailing no property 13');
var elisionAfterComma13 = [54,,];
check(elisionAfterComma13.length === 2, 'elision trailing length 13');
check((0 in elisionAfterComma13) && !(1 in elisionAfterComma13), 'elision trailing properties 13');
var noExtraElement14 = [55,];
check(noExtraElement14.length === 1, 'single trailing length 14');
check((0 in noExtraElement14) && !(1 in noExtraElement14), 'single trailing properties 14');
check(noExtraElement14[0] === 55, 'single trailing value 14');
var twoTrailing14 = [55, 56,];
check(twoTrailing14.length === 2, 'two trailing length 14');
check(twoTrailing14[0] === 55 && twoTrailing14[1] === 56, 'two trailing values 14');
check(!(2 in twoTrailing14), 'two trailing no property 14');
var elisionAfterComma14 = [55,,];
check(elisionAfterComma14.length === 2, 'elision trailing length 14');
check((0 in elisionAfterComma14) && !(1 in elisionAfterComma14), 'elision trailing properties 14');
var noExtraElement15 = [56,];
check(noExtraElement15.length === 1, 'single trailing length 15');
check((0 in noExtraElement15) && !(1 in noExtraElement15), 'single trailing properties 15');
check(noExtraElement15[0] === 56, 'single trailing value 15');
var twoTrailing15 = [56, 57,];
check(twoTrailing15.length === 2, 'two trailing length 15');
check(twoTrailing15[0] === 56 && twoTrailing15[1] === 57, 'two trailing values 15');
check(!(2 in twoTrailing15), 'two trailing no property 15');
var elisionAfterComma15 = [56,,];
check(elisionAfterComma15.length === 2, 'elision trailing length 15');
check((0 in elisionAfterComma15) && !(1 in elisionAfterComma15), 'elision trailing properties 15');
var noExtraElement16 = [57,];
check(noExtraElement16.length === 1, 'single trailing length 16');
check((0 in noExtraElement16) && !(1 in noExtraElement16), 'single trailing properties 16');
check(noExtraElement16[0] === 57, 'single trailing value 16');
var twoTrailing16 = [57, 58,];
check(twoTrailing16.length === 2, 'two trailing length 16');
check(twoTrailing16[0] === 57 && twoTrailing16[1] === 58, 'two trailing values 16');
check(!(2 in twoTrailing16), 'two trailing no property 16');
var elisionAfterComma16 = [57,,];
check(elisionAfterComma16.length === 2, 'elision trailing length 16');
check((0 in elisionAfterComma16) && !(1 in elisionAfterComma16), 'elision trailing properties 16');
var noExtraElement17 = [58,];
check(noExtraElement17.length === 1, 'single trailing length 17');
check((0 in noExtraElement17) && !(1 in noExtraElement17), 'single trailing properties 17');
check(noExtraElement17[0] === 58, 'single trailing value 17');
var twoTrailing17 = [58, 59,];
check(twoTrailing17.length === 2, 'two trailing length 17');
check(twoTrailing17[0] === 58 && twoTrailing17[1] === 59, 'two trailing values 17');
check(!(2 in twoTrailing17), 'two trailing no property 17');
var elisionAfterComma17 = [58,,];
check(elisionAfterComma17.length === 2, 'elision trailing length 17');
check((0 in elisionAfterComma17) && !(1 in elisionAfterComma17), 'elision trailing properties 17');
var noExtraElement18 = [59,];
check(noExtraElement18.length === 1, 'single trailing length 18');
check((0 in noExtraElement18) && !(1 in noExtraElement18), 'single trailing properties 18');
check(noExtraElement18[0] === 59, 'single trailing value 18');
var twoTrailing18 = [59, 60,];
check(twoTrailing18.length === 2, 'two trailing length 18');
check(twoTrailing18[0] === 59 && twoTrailing18[1] === 60, 'two trailing values 18');
check(!(2 in twoTrailing18), 'two trailing no property 18');
var elisionAfterComma18 = [59,,];
check(elisionAfterComma18.length === 2, 'elision trailing length 18');
check((0 in elisionAfterComma18) && !(1 in elisionAfterComma18), 'elision trailing properties 18');
var noExtraElement19 = [60,];
check(noExtraElement19.length === 1, 'single trailing length 19');
check((0 in noExtraElement19) && !(1 in noExtraElement19), 'single trailing properties 19');
check(noExtraElement19[0] === 60, 'single trailing value 19');
var twoTrailing19 = [60, 61,];
check(twoTrailing19.length === 2, 'two trailing length 19');
check(twoTrailing19[0] === 60 && twoTrailing19[1] === 61, 'two trailing values 19');
check(!(2 in twoTrailing19), 'two trailing no property 19');
var elisionAfterComma19 = [60,,];
check(elisionAfterComma19.length === 2, 'elision trailing length 19');
check((0 in elisionAfterComma19) && !(1 in elisionAfterComma19), 'elision trailing properties 19');
var noExtraElement20 = [61,];
check(noExtraElement20.length === 1, 'single trailing length 20');
check((0 in noExtraElement20) && !(1 in noExtraElement20), 'single trailing properties 20');
check(noExtraElement20[0] === 61, 'single trailing value 20');
var twoTrailing20 = [61, 62,];
check(twoTrailing20.length === 2, 'two trailing length 20');
check(twoTrailing20[0] === 61 && twoTrailing20[1] === 62, 'two trailing values 20');
check(!(2 in twoTrailing20), 'two trailing no property 20');
var elisionAfterComma20 = [61,,];
check(elisionAfterComma20.length === 2, 'elision trailing length 20');
check((0 in elisionAfterComma20) && !(1 in elisionAfterComma20), 'elision trailing properties 20');
var noExtraElement21 = [62,];
check(noExtraElement21.length === 1, 'single trailing length 21');
check((0 in noExtraElement21) && !(1 in noExtraElement21), 'single trailing properties 21');
check(noExtraElement21[0] === 62, 'single trailing value 21');
var twoTrailing21 = [62, 63,];
check(twoTrailing21.length === 2, 'two trailing length 21');
check(twoTrailing21[0] === 62 && twoTrailing21[1] === 63, 'two trailing values 21');
check(!(2 in twoTrailing21), 'two trailing no property 21');
var elisionAfterComma21 = [62,,];
check(elisionAfterComma21.length === 2, 'elision trailing length 21');
check((0 in elisionAfterComma21) && !(1 in elisionAfterComma21), 'elision trailing properties 21');
var noExtraElement22 = [63,];
check(noExtraElement22.length === 1, 'single trailing length 22');
check((0 in noExtraElement22) && !(1 in noExtraElement22), 'single trailing properties 22');
check(noExtraElement22[0] === 63, 'single trailing value 22');
var twoTrailing22 = [63, 64,];
check(twoTrailing22.length === 2, 'two trailing length 22');
check(twoTrailing22[0] === 63 && twoTrailing22[1] === 64, 'two trailing values 22');
check(!(2 in twoTrailing22), 'two trailing no property 22');
var elisionAfterComma22 = [63,,];
check(elisionAfterComma22.length === 2, 'elision trailing length 22');
check((0 in elisionAfterComma22) && !(1 in elisionAfterComma22), 'elision trailing properties 22');
var noExtraElement23 = [64,];
check(noExtraElement23.length === 1, 'single trailing length 23');
check((0 in noExtraElement23) && !(1 in noExtraElement23), 'single trailing properties 23');
check(noExtraElement23[0] === 64, 'single trailing value 23');
var twoTrailing23 = [64, 65,];
check(twoTrailing23.length === 2, 'two trailing length 23');
check(twoTrailing23[0] === 64 && twoTrailing23[1] === 65, 'two trailing values 23');
check(!(2 in twoTrailing23), 'two trailing no property 23');
var elisionAfterComma23 = [64,,];
check(elisionAfterComma23.length === 2, 'elision trailing length 23');
check((0 in elisionAfterComma23) && !(1 in elisionAfterComma23), 'elision trailing properties 23');
var noExtraElement24 = [65,];
check(noExtraElement24.length === 1, 'single trailing length 24');
check((0 in noExtraElement24) && !(1 in noExtraElement24), 'single trailing properties 24');
check(noExtraElement24[0] === 65, 'single trailing value 24');
var twoTrailing24 = [65, 66,];
check(twoTrailing24.length === 2, 'two trailing length 24');
check(twoTrailing24[0] === 65 && twoTrailing24[1] === 66, 'two trailing values 24');
check(!(2 in twoTrailing24), 'two trailing no property 24');
var elisionAfterComma24 = [65,,];
check(elisionAfterComma24.length === 2, 'elision trailing length 24');
check((0 in elisionAfterComma24) && !(1 in elisionAfterComma24), 'elision trailing properties 24');
var noExtraElement25 = [66,];
check(noExtraElement25.length === 1, 'single trailing length 25');
check((0 in noExtraElement25) && !(1 in noExtraElement25), 'single trailing properties 25');
check(noExtraElement25[0] === 66, 'single trailing value 25');
var twoTrailing25 = [66, 67,];
check(twoTrailing25.length === 2, 'two trailing length 25');
check(twoTrailing25[0] === 66 && twoTrailing25[1] === 67, 'two trailing values 25');
check(!(2 in twoTrailing25), 'two trailing no property 25');
var elisionAfterComma25 = [66,,];
check(elisionAfterComma25.length === 2, 'elision trailing length 25');
check((0 in elisionAfterComma25) && !(1 in elisionAfterComma25), 'elision trailing properties 25');
var noExtraElement26 = [67,];
check(noExtraElement26.length === 1, 'single trailing length 26');
check((0 in noExtraElement26) && !(1 in noExtraElement26), 'single trailing properties 26');
check(noExtraElement26[0] === 67, 'single trailing value 26');
var twoTrailing26 = [67, 68,];
check(twoTrailing26.length === 2, 'two trailing length 26');
check(twoTrailing26[0] === 67 && twoTrailing26[1] === 68, 'two trailing values 26');
check(!(2 in twoTrailing26), 'two trailing no property 26');
var elisionAfterComma26 = [67,,];
check(elisionAfterComma26.length === 2, 'elision trailing length 26');
check((0 in elisionAfterComma26) && !(1 in elisionAfterComma26), 'elision trailing properties 26');
var noExtraElement27 = [68,];
check(noExtraElement27.length === 1, 'single trailing length 27');
check((0 in noExtraElement27) && !(1 in noExtraElement27), 'single trailing properties 27');
check(noExtraElement27[0] === 68, 'single trailing value 27');
var twoTrailing27 = [68, 69,];
check(twoTrailing27.length === 2, 'two trailing length 27');
check(twoTrailing27[0] === 68 && twoTrailing27[1] === 69, 'two trailing values 27');
check(!(2 in twoTrailing27), 'two trailing no property 27');
var elisionAfterComma27 = [68,,];
check(elisionAfterComma27.length === 2, 'elision trailing length 27');
check((0 in elisionAfterComma27) && !(1 in elisionAfterComma27), 'elision trailing properties 27');
var noExtraElement28 = [69,];
check(noExtraElement28.length === 1, 'single trailing length 28');
check((0 in noExtraElement28) && !(1 in noExtraElement28), 'single trailing properties 28');
check(noExtraElement28[0] === 69, 'single trailing value 28');
var twoTrailing28 = [69, 70,];
check(twoTrailing28.length === 2, 'two trailing length 28');
check(twoTrailing28[0] === 69 && twoTrailing28[1] === 70, 'two trailing values 28');
check(!(2 in twoTrailing28), 'two trailing no property 28');
var elisionAfterComma28 = [69,,];
check(elisionAfterComma28.length === 2, 'elision trailing length 28');
check((0 in elisionAfterComma28) && !(1 in elisionAfterComma28), 'elision trailing properties 28');
var noExtraElement29 = [70,];
check(noExtraElement29.length === 1, 'single trailing length 29');
check((0 in noExtraElement29) && !(1 in noExtraElement29), 'single trailing properties 29');
check(noExtraElement29[0] === 70, 'single trailing value 29');
var twoTrailing29 = [70, 71,];
check(twoTrailing29.length === 2, 'two trailing length 29');
check(twoTrailing29[0] === 70 && twoTrailing29[1] === 71, 'two trailing values 29');
check(!(2 in twoTrailing29), 'two trailing no property 29');
var elisionAfterComma29 = [70,,];
check(elisionAfterComma29.length === 2, 'elision trailing length 29');
check((0 in elisionAfterComma29) && !(1 in elisionAfterComma29), 'elision trailing properties 29');
var noExtraElement30 = [71,];
check(noExtraElement30.length === 1, 'single trailing length 30');
check((0 in noExtraElement30) && !(1 in noExtraElement30), 'single trailing properties 30');
check(noExtraElement30[0] === 71, 'single trailing value 30');
var twoTrailing30 = [71, 72,];
check(twoTrailing30.length === 2, 'two trailing length 30');
check(twoTrailing30[0] === 71 && twoTrailing30[1] === 72, 'two trailing values 30');
check(!(2 in twoTrailing30), 'two trailing no property 30');
var elisionAfterComma30 = [71,,];
check(elisionAfterComma30.length === 2, 'elision trailing length 30');
check((0 in elisionAfterComma30) && !(1 in elisionAfterComma30), 'elision trailing properties 30');
var noExtraElement31 = [72,];
check(noExtraElement31.length === 1, 'single trailing length 31');
check((0 in noExtraElement31) && !(1 in noExtraElement31), 'single trailing properties 31');
check(noExtraElement31[0] === 72, 'single trailing value 31');
var twoTrailing31 = [72, 73,];
check(twoTrailing31.length === 2, 'two trailing length 31');
check(twoTrailing31[0] === 72 && twoTrailing31[1] === 73, 'two trailing values 31');
check(!(2 in twoTrailing31), 'two trailing no property 31');
var elisionAfterComma31 = [72,,];
check(elisionAfterComma31.length === 2, 'elision trailing length 31');
check((0 in elisionAfterComma31) && !(1 in elisionAfterComma31), 'elision trailing properties 31');
var noExtraElement32 = [73,];
check(noExtraElement32.length === 1, 'single trailing length 32');
check((0 in noExtraElement32) && !(1 in noExtraElement32), 'single trailing properties 32');
check(noExtraElement32[0] === 73, 'single trailing value 32');
var twoTrailing32 = [73, 74,];
check(twoTrailing32.length === 2, 'two trailing length 32');
check(twoTrailing32[0] === 73 && twoTrailing32[1] === 74, 'two trailing values 32');
check(!(2 in twoTrailing32), 'two trailing no property 32');
var elisionAfterComma32 = [73,,];
check(elisionAfterComma32.length === 2, 'elision trailing length 32');
check((0 in elisionAfterComma32) && !(1 in elisionAfterComma32), 'elision trailing properties 32');
var noExtraElement33 = [74,];
check(noExtraElement33.length === 1, 'single trailing length 33');
check((0 in noExtraElement33) && !(1 in noExtraElement33), 'single trailing properties 33');
check(noExtraElement33[0] === 74, 'single trailing value 33');
var twoTrailing33 = [74, 75,];
check(twoTrailing33.length === 2, 'two trailing length 33');
check(twoTrailing33[0] === 74 && twoTrailing33[1] === 75, 'two trailing values 33');
check(!(2 in twoTrailing33), 'two trailing no property 33');
var elisionAfterComma33 = [74,,];
check(elisionAfterComma33.length === 2, 'elision trailing length 33');
check((0 in elisionAfterComma33) && !(1 in elisionAfterComma33), 'elision trailing properties 33');
var noExtraElement34 = [75,];
check(noExtraElement34.length === 1, 'single trailing length 34');
check((0 in noExtraElement34) && !(1 in noExtraElement34), 'single trailing properties 34');
check(noExtraElement34[0] === 75, 'single trailing value 34');
var twoTrailing34 = [75, 76,];
check(twoTrailing34.length === 2, 'two trailing length 34');
check(twoTrailing34[0] === 75 && twoTrailing34[1] === 76, 'two trailing values 34');
check(!(2 in twoTrailing34), 'two trailing no property 34');
var elisionAfterComma34 = [75,,];
check(elisionAfterComma34.length === 2, 'elision trailing length 34');
check((0 in elisionAfterComma34) && !(1 in elisionAfterComma34), 'elision trailing properties 34');
var noExtraElement35 = [76,];
check(noExtraElement35.length === 1, 'single trailing length 35');
check((0 in noExtraElement35) && !(1 in noExtraElement35), 'single trailing properties 35');
check(noExtraElement35[0] === 76, 'single trailing value 35');
var twoTrailing35 = [76, 77,];
check(twoTrailing35.length === 2, 'two trailing length 35');
check(twoTrailing35[0] === 76 && twoTrailing35[1] === 77, 'two trailing values 35');
check(!(2 in twoTrailing35), 'two trailing no property 35');
var elisionAfterComma35 = [76,,];
check(elisionAfterComma35.length === 2, 'elision trailing length 35');
check((0 in elisionAfterComma35) && !(1 in elisionAfterComma35), 'elision trailing properties 35');
var noExtraElement36 = [77,];
check(noExtraElement36.length === 1, 'single trailing length 36');
check((0 in noExtraElement36) && !(1 in noExtraElement36), 'single trailing properties 36');
check(noExtraElement36[0] === 77, 'single trailing value 36');
var twoTrailing36 = [77, 78,];
check(twoTrailing36.length === 2, 'two trailing length 36');
check(twoTrailing36[0] === 77 && twoTrailing36[1] === 78, 'two trailing values 36');
check(!(2 in twoTrailing36), 'two trailing no property 36');
var elisionAfterComma36 = [77,,];
check(elisionAfterComma36.length === 2, 'elision trailing length 36');
check((0 in elisionAfterComma36) && !(1 in elisionAfterComma36), 'elision trailing properties 36');
var noExtraElement37 = [78,];
check(noExtraElement37.length === 1, 'single trailing length 37');
check((0 in noExtraElement37) && !(1 in noExtraElement37), 'single trailing properties 37');
check(noExtraElement37[0] === 78, 'single trailing value 37');
var twoTrailing37 = [78, 79,];
check(twoTrailing37.length === 2, 'two trailing length 37');
check(twoTrailing37[0] === 78 && twoTrailing37[1] === 79, 'two trailing values 37');
check(!(2 in twoTrailing37), 'two trailing no property 37');
var elisionAfterComma37 = [78,,];
check(elisionAfterComma37.length === 2, 'elision trailing length 37');
check((0 in elisionAfterComma37) && !(1 in elisionAfterComma37), 'elision trailing properties 37');
var noExtraElement38 = [79,];
check(noExtraElement38.length === 1, 'single trailing length 38');
check((0 in noExtraElement38) && !(1 in noExtraElement38), 'single trailing properties 38');
check(noExtraElement38[0] === 79, 'single trailing value 38');
var twoTrailing38 = [79, 80,];
check(twoTrailing38.length === 2, 'two trailing length 38');
check(twoTrailing38[0] === 79 && twoTrailing38[1] === 80, 'two trailing values 38');
check(!(2 in twoTrailing38), 'two trailing no property 38');
var elisionAfterComma38 = [79,,];
check(elisionAfterComma38.length === 2, 'elision trailing length 38');
check((0 in elisionAfterComma38) && !(1 in elisionAfterComma38), 'elision trailing properties 38');
var noExtraElement39 = [80,];
check(noExtraElement39.length === 1, 'single trailing length 39');
check((0 in noExtraElement39) && !(1 in noExtraElement39), 'single trailing properties 39');
check(noExtraElement39[0] === 80, 'single trailing value 39');
var twoTrailing39 = [80, 81,];
check(twoTrailing39.length === 2, 'two trailing length 39');
check(twoTrailing39[0] === 80 && twoTrailing39[1] === 81, 'two trailing values 39');
check(!(2 in twoTrailing39), 'two trailing no property 39');
var elisionAfterComma39 = [80,,];
check(elisionAfterComma39.length === 2, 'elision trailing length 39');
check((0 in elisionAfterComma39) && !(1 in elisionAfterComma39), 'elision trailing properties 39');
var noExtraElement40 = [81,];
check(noExtraElement40.length === 1, 'single trailing length 40');
check((0 in noExtraElement40) && !(1 in noExtraElement40), 'single trailing properties 40');
check(noExtraElement40[0] === 81, 'single trailing value 40');
var twoTrailing40 = [81, 82,];
check(twoTrailing40.length === 2, 'two trailing length 40');
check(twoTrailing40[0] === 81 && twoTrailing40[1] === 82, 'two trailing values 40');
check(!(2 in twoTrailing40), 'two trailing no property 40');
var elisionAfterComma40 = [81,,];
check(elisionAfterComma40.length === 2, 'elision trailing length 40');
check((0 in elisionAfterComma40) && !(1 in elisionAfterComma40), 'elision trailing properties 40');
var noExtraElement41 = [82,];
check(noExtraElement41.length === 1, 'single trailing length 41');
check((0 in noExtraElement41) && !(1 in noExtraElement41), 'single trailing properties 41');
check(noExtraElement41[0] === 82, 'single trailing value 41');
var twoTrailing41 = [82, 83,];
check(twoTrailing41.length === 2, 'two trailing length 41');
check(twoTrailing41[0] === 82 && twoTrailing41[1] === 83, 'two trailing values 41');
check(!(2 in twoTrailing41), 'two trailing no property 41');
var elisionAfterComma41 = [82,,];
check(elisionAfterComma41.length === 2, 'elision trailing length 41');
check((0 in elisionAfterComma41) && !(1 in elisionAfterComma41), 'elision trailing properties 41');
var noExtraElement42 = [83,];
check(noExtraElement42.length === 1, 'single trailing length 42');
check((0 in noExtraElement42) && !(1 in noExtraElement42), 'single trailing properties 42');
check(noExtraElement42[0] === 83, 'single trailing value 42');
var twoTrailing42 = [83, 84,];
check(twoTrailing42.length === 2, 'two trailing length 42');
check(twoTrailing42[0] === 83 && twoTrailing42[1] === 84, 'two trailing values 42');
check(!(2 in twoTrailing42), 'two trailing no property 42');
var elisionAfterComma42 = [83,,];
check(elisionAfterComma42.length === 2, 'elision trailing length 42');
check((0 in elisionAfterComma42) && !(1 in elisionAfterComma42), 'elision trailing properties 42');
var noExtraElement43 = [84,];
check(noExtraElement43.length === 1, 'single trailing length 43');
check((0 in noExtraElement43) && !(1 in noExtraElement43), 'single trailing properties 43');
check(noExtraElement43[0] === 84, 'single trailing value 43');
var twoTrailing43 = [84, 85,];
check(twoTrailing43.length === 2, 'two trailing length 43');
check(twoTrailing43[0] === 84 && twoTrailing43[1] === 85, 'two trailing values 43');
check(!(2 in twoTrailing43), 'two trailing no property 43');
var elisionAfterComma43 = [84,,];
check(elisionAfterComma43.length === 2, 'elision trailing length 43');
check((0 in elisionAfterComma43) && !(1 in elisionAfterComma43), 'elision trailing properties 43');
var noExtraElement44 = [85,];
check(noExtraElement44.length === 1, 'single trailing length 44');
check((0 in noExtraElement44) && !(1 in noExtraElement44), 'single trailing properties 44');
check(noExtraElement44[0] === 85, 'single trailing value 44');
var twoTrailing44 = [85, 86,];
check(twoTrailing44.length === 2, 'two trailing length 44');
check(twoTrailing44[0] === 85 && twoTrailing44[1] === 86, 'two trailing values 44');
check(!(2 in twoTrailing44), 'two trailing no property 44');
var elisionAfterComma44 = [85,,];
check(elisionAfterComma44.length === 2, 'elision trailing length 44');
check((0 in elisionAfterComma44) && !(1 in elisionAfterComma44), 'elision trailing properties 44');
var noExtraElement45 = [86,];
check(noExtraElement45.length === 1, 'single trailing length 45');
check((0 in noExtraElement45) && !(1 in noExtraElement45), 'single trailing properties 45');
check(noExtraElement45[0] === 86, 'single trailing value 45');
var twoTrailing45 = [86, 87,];
check(twoTrailing45.length === 2, 'two trailing length 45');
check(twoTrailing45[0] === 86 && twoTrailing45[1] === 87, 'two trailing values 45');
check(!(2 in twoTrailing45), 'two trailing no property 45');
var elisionAfterComma45 = [86,,];
check(elisionAfterComma45.length === 2, 'elision trailing length 45');
check((0 in elisionAfterComma45) && !(1 in elisionAfterComma45), 'elision trailing properties 45');
console.log('trailing-comma-does-not-add-element large ' + score);
