// behavior: trailing-comma-does-not-add-element
// expected: pass
// goal: script
// size: standard
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}
var noExtraElement0 = [41,];
check(noExtraElement0.length === 1, 'single trailing length 0');
check((0 in noExtraElement0) && !(1 in noExtraElement0), 'single trailing properties 0');
check(noExtraElement0[0] === 41, 'single trailing value 0');
var twoTrailing0 = [41, 42,];
check(twoTrailing0.length === 2, 'two trailing length 0');
check(twoTrailing0[0] === 41 && twoTrailing0[1] === 42, 'two trailing values 0');
check(!(2 in twoTrailing0), 'two trailing no property 0');
var elisionAfterComma0 = [41,,];
check(elisionAfterComma0.length === 2, 'elision trailing length 0');
check((0 in elisionAfterComma0) && !(1 in elisionAfterComma0), 'elision trailing properties 0');
var noExtraElement1 = [42,];
check(noExtraElement1.length === 1, 'single trailing length 1');
check((0 in noExtraElement1) && !(1 in noExtraElement1), 'single trailing properties 1');
check(noExtraElement1[0] === 42, 'single trailing value 1');
var twoTrailing1 = [42, 43,];
check(twoTrailing1.length === 2, 'two trailing length 1');
check(twoTrailing1[0] === 42 && twoTrailing1[1] === 43, 'two trailing values 1');
check(!(2 in twoTrailing1), 'two trailing no property 1');
var elisionAfterComma1 = [42,,];
check(elisionAfterComma1.length === 2, 'elision trailing length 1');
check((0 in elisionAfterComma1) && !(1 in elisionAfterComma1), 'elision trailing properties 1');
var noExtraElement2 = [43,];
check(noExtraElement2.length === 1, 'single trailing length 2');
check((0 in noExtraElement2) && !(1 in noExtraElement2), 'single trailing properties 2');
check(noExtraElement2[0] === 43, 'single trailing value 2');
var twoTrailing2 = [43, 44,];
check(twoTrailing2.length === 2, 'two trailing length 2');
check(twoTrailing2[0] === 43 && twoTrailing2[1] === 44, 'two trailing values 2');
check(!(2 in twoTrailing2), 'two trailing no property 2');
var elisionAfterComma2 = [43,,];
check(elisionAfterComma2.length === 2, 'elision trailing length 2');
check((0 in elisionAfterComma2) && !(1 in elisionAfterComma2), 'elision trailing properties 2');
var noExtraElement3 = [44,];
check(noExtraElement3.length === 1, 'single trailing length 3');
check((0 in noExtraElement3) && !(1 in noExtraElement3), 'single trailing properties 3');
check(noExtraElement3[0] === 44, 'single trailing value 3');
var twoTrailing3 = [44, 45,];
check(twoTrailing3.length === 2, 'two trailing length 3');
check(twoTrailing3[0] === 44 && twoTrailing3[1] === 45, 'two trailing values 3');
check(!(2 in twoTrailing3), 'two trailing no property 3');
var elisionAfterComma3 = [44,,];
check(elisionAfterComma3.length === 2, 'elision trailing length 3');
check((0 in elisionAfterComma3) && !(1 in elisionAfterComma3), 'elision trailing properties 3');
var noExtraElement4 = [45,];
check(noExtraElement4.length === 1, 'single trailing length 4');
check((0 in noExtraElement4) && !(1 in noExtraElement4), 'single trailing properties 4');
check(noExtraElement4[0] === 45, 'single trailing value 4');
var twoTrailing4 = [45, 46,];
check(twoTrailing4.length === 2, 'two trailing length 4');
check(twoTrailing4[0] === 45 && twoTrailing4[1] === 46, 'two trailing values 4');
check(!(2 in twoTrailing4), 'two trailing no property 4');
var elisionAfterComma4 = [45,,];
check(elisionAfterComma4.length === 2, 'elision trailing length 4');
check((0 in elisionAfterComma4) && !(1 in elisionAfterComma4), 'elision trailing properties 4');
var noExtraElement5 = [46,];
check(noExtraElement5.length === 1, 'single trailing length 5');
check((0 in noExtraElement5) && !(1 in noExtraElement5), 'single trailing properties 5');
check(noExtraElement5[0] === 46, 'single trailing value 5');
var twoTrailing5 = [46, 47,];
check(twoTrailing5.length === 2, 'two trailing length 5');
check(twoTrailing5[0] === 46 && twoTrailing5[1] === 47, 'two trailing values 5');
check(!(2 in twoTrailing5), 'two trailing no property 5');
var elisionAfterComma5 = [46,,];
check(elisionAfterComma5.length === 2, 'elision trailing length 5');
check((0 in elisionAfterComma5) && !(1 in elisionAfterComma5), 'elision trailing properties 5');
var noExtraElement6 = [47,];
check(noExtraElement6.length === 1, 'single trailing length 6');
check((0 in noExtraElement6) && !(1 in noExtraElement6), 'single trailing properties 6');
check(noExtraElement6[0] === 47, 'single trailing value 6');
var twoTrailing6 = [47, 48,];
check(twoTrailing6.length === 2, 'two trailing length 6');
check(twoTrailing6[0] === 47 && twoTrailing6[1] === 48, 'two trailing values 6');
check(!(2 in twoTrailing6), 'two trailing no property 6');
var elisionAfterComma6 = [47,,];
check(elisionAfterComma6.length === 2, 'elision trailing length 6');
check((0 in elisionAfterComma6) && !(1 in elisionAfterComma6), 'elision trailing properties 6');
var noExtraElement7 = [48,];
check(noExtraElement7.length === 1, 'single trailing length 7');
check((0 in noExtraElement7) && !(1 in noExtraElement7), 'single trailing properties 7');
check(noExtraElement7[0] === 48, 'single trailing value 7');
var twoTrailing7 = [48, 49,];
check(twoTrailing7.length === 2, 'two trailing length 7');
check(twoTrailing7[0] === 48 && twoTrailing7[1] === 49, 'two trailing values 7');
check(!(2 in twoTrailing7), 'two trailing no property 7');
var elisionAfterComma7 = [48,,];
check(elisionAfterComma7.length === 2, 'elision trailing length 7');
check((0 in elisionAfterComma7) && !(1 in elisionAfterComma7), 'elision trailing properties 7');
var noExtraElement8 = [49,];
check(noExtraElement8.length === 1, 'single trailing length 8');
check((0 in noExtraElement8) && !(1 in noExtraElement8), 'single trailing properties 8');
check(noExtraElement8[0] === 49, 'single trailing value 8');
var twoTrailing8 = [49, 50,];
check(twoTrailing8.length === 2, 'two trailing length 8');
check(twoTrailing8[0] === 49 && twoTrailing8[1] === 50, 'two trailing values 8');
check(!(2 in twoTrailing8), 'two trailing no property 8');
var elisionAfterComma8 = [49,,];
check(elisionAfterComma8.length === 2, 'elision trailing length 8');
check((0 in elisionAfterComma8) && !(1 in elisionAfterComma8), 'elision trailing properties 8');
var noExtraElement9 = [50,];
check(noExtraElement9.length === 1, 'single trailing length 9');
check((0 in noExtraElement9) && !(1 in noExtraElement9), 'single trailing properties 9');
check(noExtraElement9[0] === 50, 'single trailing value 9');
var twoTrailing9 = [50, 51,];
check(twoTrailing9.length === 2, 'two trailing length 9');
check(twoTrailing9[0] === 50 && twoTrailing9[1] === 51, 'two trailing values 9');
check(!(2 in twoTrailing9), 'two trailing no property 9');
var elisionAfterComma9 = [50,,];
check(elisionAfterComma9.length === 2, 'elision trailing length 9');
check((0 in elisionAfterComma9) && !(1 in elisionAfterComma9), 'elision trailing properties 9');
console.log('trailing-comma-does-not-add-element standard ' + score);
