// behavior: trailing-comma-does-not-add-element
// expected: pass
// goal: script
// size: stress
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}
var noExtraElement0 = [41,];
check(noExtraElement0.length === 1, 'single trailing length 0');
check((0 in noExtraElement0) && !(1 in noExtraElement0), 'single trailing properties 0');
check(noExtraElement0[0] === 41, 'single trailing value 0');
var twoTrailing0 = [41, 42,];
check(twoTrailing0.length === 2, 'two trailing length 0');
check(twoTrailing0[0] === 41 && twoTrailing0[1] === 42, 'two trailing values 0');
check(!(2 in twoTrailing0), 'two trailing no property 0');
var elisionAfterComma0 = [41,,];
check(elisionAfterComma0.length === 2, 'elision trailing length 0');
check((0 in elisionAfterComma0) && !(1 in elisionAfterComma0), 'elision trailing properties 0');
var noExtraElement1 = [42,];
check(noExtraElement1.length === 1, 'single trailing length 1');
check((0 in noExtraElement1) && !(1 in noExtraElement1), 'single trailing properties 1');
check(noExtraElement1[0] === 42, 'single trailing value 1');
var twoTrailing1 = [42, 43,];
check(twoTrailing1.length === 2, 'two trailing length 1');
check(twoTrailing1[0] === 42 && twoTrailing1[1] === 43, 'two trailing values 1');
check(!(2 in twoTrailing1), 'two trailing no property 1');
var elisionAfterComma1 = [42,,];
check(elisionAfterComma1.length === 2, 'elision trailing length 1');
check((0 in elisionAfterComma1) && !(1 in elisionAfterComma1), 'elision trailing properties 1');
var noExtraElement2 = [43,];
check(noExtraElement2.length === 1, 'single trailing length 2');
check((0 in noExtraElement2) && !(1 in noExtraElement2), 'single trailing properties 2');
check(noExtraElement2[0] === 43, 'single trailing value 2');
var twoTrailing2 = [43, 44,];
check(twoTrailing2.length === 2, 'two trailing length 2');
check(twoTrailing2[0] === 43 && twoTrailing2[1] === 44, 'two trailing values 2');
check(!(2 in twoTrailing2), 'two trailing no property 2');
var elisionAfterComma2 = [43,,];
check(elisionAfterComma2.length === 2, 'elision trailing length 2');
check((0 in elisionAfterComma2) && !(1 in elisionAfterComma2), 'elision trailing properties 2');
var noExtraElement3 = [44,];
check(noExtraElement3.length === 1, 'single trailing length 3');
check((0 in noExtraElement3) && !(1 in noExtraElement3), 'single trailing properties 3');
check(noExtraElement3[0] === 44, 'single trailing value 3');
var twoTrailing3 = [44, 45,];
check(twoTrailing3.length === 2, 'two trailing length 3');
check(twoTrailing3[0] === 44 && twoTrailing3[1] === 45, 'two trailing values 3');
check(!(2 in twoTrailing3), 'two trailing no property 3');
var elisionAfterComma3 = [44,,];
check(elisionAfterComma3.length === 2, 'elision trailing length 3');
check((0 in elisionAfterComma3) && !(1 in elisionAfterComma3), 'elision trailing properties 3');
var noExtraElement4 = [45,];
check(noExtraElement4.length === 1, 'single trailing length 4');
check((0 in noExtraElement4) && !(1 in noExtraElement4), 'single trailing properties 4');
check(noExtraElement4[0] === 45, 'single trailing value 4');
var twoTrailing4 = [45, 46,];
check(twoTrailing4.length === 2, 'two trailing length 4');
check(twoTrailing4[0] === 45 && twoTrailing4[1] === 46, 'two trailing values 4');
check(!(2 in twoTrailing4), 'two trailing no property 4');
var elisionAfterComma4 = [45,,];
check(elisionAfterComma4.length === 2, 'elision trailing length 4');
check((0 in elisionAfterComma4) && !(1 in elisionAfterComma4), 'elision trailing properties 4');
var noExtraElement5 = [46,];
check(noExtraElement5.length === 1, 'single trailing length 5');
check((0 in noExtraElement5) && !(1 in noExtraElement5), 'single trailing properties 5');
check(noExtraElement5[0] === 46, 'single trailing value 5');
var twoTrailing5 = [46, 47,];
check(twoTrailing5.length === 2, 'two trailing length 5');
check(twoTrailing5[0] === 46 && twoTrailing5[1] === 47, 'two trailing values 5');
check(!(2 in twoTrailing5), 'two trailing no property 5');
var elisionAfterComma5 = [46,,];
check(elisionAfterComma5.length === 2, 'elision trailing length 5');
check((0 in elisionAfterComma5) && !(1 in elisionAfterComma5), 'elision trailing properties 5');
var noExtraElement6 = [47,];
check(noExtraElement6.length === 1, 'single trailing length 6');
check((0 in noExtraElement6) && !(1 in noExtraElement6), 'single trailing properties 6');
check(noExtraElement6[0] === 47, 'single trailing value 6');
var twoTrailing6 = [47, 48,];
check(twoTrailing6.length === 2, 'two trailing length 6');
check(twoTrailing6[0] === 47 && twoTrailing6[1] === 48, 'two trailing values 6');
check(!(2 in twoTrailing6), 'two trailing no property 6');
var elisionAfterComma6 = [47,,];
check(elisionAfterComma6.length === 2, 'elision trailing length 6');
check((0 in elisionAfterComma6) && !(1 in elisionAfterComma6), 'elision trailing properties 6');
var noExtraElement7 = [48,];
check(noExtraElement7.length === 1, 'single trailing length 7');
check((0 in noExtraElement7) && !(1 in noExtraElement7), 'single trailing properties 7');
check(noExtraElement7[0] === 48, 'single trailing value 7');
var twoTrailing7 = [48, 49,];
check(twoTrailing7.length === 2, 'two trailing length 7');
check(twoTrailing7[0] === 48 && twoTrailing7[1] === 49, 'two trailing values 7');
check(!(2 in twoTrailing7), 'two trailing no property 7');
var elisionAfterComma7 = [48,,];
check(elisionAfterComma7.length === 2, 'elision trailing length 7');
check((0 in elisionAfterComma7) && !(1 in elisionAfterComma7), 'elision trailing properties 7');
var noExtraElement8 = [49,];
check(noExtraElement8.length === 1, 'single trailing length 8');
check((0 in noExtraElement8) && !(1 in noExtraElement8), 'single trailing properties 8');
check(noExtraElement8[0] === 49, 'single trailing value 8');
var twoTrailing8 = [49, 50,];
check(twoTrailing8.length === 2, 'two trailing length 8');
check(twoTrailing8[0] === 49 && twoTrailing8[1] === 50, 'two trailing values 8');
check(!(2 in twoTrailing8), 'two trailing no property 8');
var elisionAfterComma8 = [49,,];
check(elisionAfterComma8.length === 2, 'elision trailing length 8');
check((0 in elisionAfterComma8) && !(1 in elisionAfterComma8), 'elision trailing properties 8');
var noExtraElement9 = [50,];
check(noExtraElement9.length === 1, 'single trailing length 9');
check((0 in noExtraElement9) && !(1 in noExtraElement9), 'single trailing properties 9');
check(noExtraElement9[0] === 50, 'single trailing value 9');
var twoTrailing9 = [50, 51,];
check(twoTrailing9.length === 2, 'two trailing length 9');
check(twoTrailing9[0] === 50 && twoTrailing9[1] === 51, 'two trailing values 9');
check(!(2 in twoTrailing9), 'two trailing no property 9');
var elisionAfterComma9 = [50,,];
check(elisionAfterComma9.length === 2, 'elision trailing length 9');
check((0 in elisionAfterComma9) && !(1 in elisionAfterComma9), 'elision trailing properties 9');
var noExtraElement10 = [51,];
check(noExtraElement10.length === 1, 'single trailing length 10');
check((0 in noExtraElement10) && !(1 in noExtraElement10), 'single trailing properties 10');
check(noExtraElement10[0] === 51, 'single trailing value 10');
var twoTrailing10 = [51, 52,];
check(twoTrailing10.length === 2, 'two trailing length 10');
check(twoTrailing10[0] === 51 && twoTrailing10[1] === 52, 'two trailing values 10');
check(!(2 in twoTrailing10), 'two trailing no property 10');
var elisionAfterComma10 = [51,,];
check(elisionAfterComma10.length === 2, 'elision trailing length 10');
check((0 in elisionAfterComma10) && !(1 in elisionAfterComma10), 'elision trailing properties 10');
var noExtraElement11 = [52,];
check(noExtraElement11.length === 1, 'single trailing length 11');
check((0 in noExtraElement11) && !(1 in noExtraElement11), 'single trailing properties 11');
check(noExtraElement11[0] === 52, 'single trailing value 11');
var twoTrailing11 = [52, 53,];
check(twoTrailing11.length === 2, 'two trailing length 11');
check(twoTrailing11[0] === 52 && twoTrailing11[1] === 53, 'two trailing values 11');
check(!(2 in twoTrailing11), 'two trailing no property 11');
var elisionAfterComma11 = [52,,];
check(elisionAfterComma11.length === 2, 'elision trailing length 11');
check((0 in elisionAfterComma11) && !(1 in elisionAfterComma11), 'elision trailing properties 11');
var noExtraElement12 = [53,];
check(noExtraElement12.length === 1, 'single trailing length 12');
check((0 in noExtraElement12) && !(1 in noExtraElement12), 'single trailing properties 12');
check(noExtraElement12[0] === 53, 'single trailing value 12');
var twoTrailing12 = [53, 54,];
check(twoTrailing12.length === 2, 'two trailing length 12');
check(twoTrailing12[0] === 53 && twoTrailing12[1] === 54, 'two trailing values 12');
check(!(2 in twoTrailing12), 'two trailing no property 12');
var elisionAfterComma12 = [53,,];
check(elisionAfterComma12.length === 2, 'elision trailing length 12');
check((0 in elisionAfterComma12) && !(1 in elisionAfterComma12), 'elision trailing properties 12');
var noExtraElement13 = [54,];
check(noExtraElement13.length === 1, 'single trailing length 13');
check((0 in noExtraElement13) && !(1 in noExtraElement13), 'single trailing properties 13');
check(noExtraElement13[0] === 54, 'single trailing value 13');
var twoTrailing13 = [54, 55,];
check(twoTrailing13.length === 2, 'two trailing length 13');
check(twoTrailing13[0] === 54 && twoTrailing13[1] === 55, 'two trailing values 13');
check(!(2 in twoTrailing13), 'two trailing no property 13');
var elisionAfterComma13 = [54,,];
check(elisionAfterComma13.length === 2, 'elision trailing length 13');
check((0 in elisionAfterComma13) && !(1 in elisionAfterComma13), 'elision trailing properties 13');
var noExtraElement14 = [55,];
check(noExtraElement14.length === 1, 'single trailing length 14');
check((0 in noExtraElement14) && !(1 in noExtraElement14), 'single trailing properties 14');
check(noExtraElement14[0] === 55, 'single trailing value 14');
var twoTrailing14 = [55, 56,];
check(twoTrailing14.length === 2, 'two trailing length 14');
check(twoTrailing14[0] === 55 && twoTrailing14[1] === 56, 'two trailing values 14');
check(!(2 in twoTrailing14), 'two trailing no property 14');
var elisionAfterComma14 = [55,,];
check(elisionAfterComma14.length === 2, 'elision trailing length 14');
check((0 in elisionAfterComma14) && !(1 in elisionAfterComma14), 'elision trailing properties 14');
var noExtraElement15 = [56,];
check(noExtraElement15.length === 1, 'single trailing length 15');
check((0 in noExtraElement15) && !(1 in noExtraElement15), 'single trailing properties 15');
check(noExtraElement15[0] === 56, 'single trailing value 15');
var twoTrailing15 = [56, 57,];
check(twoTrailing15.length === 2, 'two trailing length 15');
check(twoTrailing15[0] === 56 && twoTrailing15[1] === 57, 'two trailing values 15');
check(!(2 in twoTrailing15), 'two trailing no property 15');
var elisionAfterComma15 = [56,,];
check(elisionAfterComma15.length === 2, 'elision trailing length 15');
check((0 in elisionAfterComma15) && !(1 in elisionAfterComma15), 'elision trailing properties 15');
var noExtraElement16 = [57,];
check(noExtraElement16.length === 1, 'single trailing length 16');
check((0 in noExtraElement16) && !(1 in noExtraElement16), 'single trailing properties 16');
check(noExtraElement16[0] === 57, 'single trailing value 16');
var twoTrailing16 = [57, 58,];
check(twoTrailing16.length === 2, 'two trailing length 16');
check(twoTrailing16[0] === 57 && twoTrailing16[1] === 58, 'two trailing values 16');
check(!(2 in twoTrailing16), 'two trailing no property 16');
var elisionAfterComma16 = [57,,];
check(elisionAfterComma16.length === 2, 'elision trailing length 16');
check((0 in elisionAfterComma16) && !(1 in elisionAfterComma16), 'elision trailing properties 16');
var noExtraElement17 = [58,];
check(noExtraElement17.length === 1, 'single trailing length 17');
check((0 in noExtraElement17) && !(1 in noExtraElement17), 'single trailing properties 17');
check(noExtraElement17[0] === 58, 'single trailing value 17');
var twoTrailing17 = [58, 59,];
check(twoTrailing17.length === 2, 'two trailing length 17');
check(twoTrailing17[0] === 58 && twoTrailing17[1] === 59, 'two trailing values 17');
check(!(2 in twoTrailing17), 'two trailing no property 17');
var elisionAfterComma17 = [58,,];
check(elisionAfterComma17.length === 2, 'elision trailing length 17');
check((0 in elisionAfterComma17) && !(1 in elisionAfterComma17), 'elision trailing properties 17');
var noExtraElement18 = [59,];
check(noExtraElement18.length === 1, 'single trailing length 18');
check((0 in noExtraElement18) && !(1 in noExtraElement18), 'single trailing properties 18');
check(noExtraElement18[0] === 59, 'single trailing value 18');
var twoTrailing18 = [59, 60,];
check(twoTrailing18.length === 2, 'two trailing length 18');
check(twoTrailing18[0] === 59 && twoTrailing18[1] === 60, 'two trailing values 18');
check(!(2 in twoTrailing18), 'two trailing no property 18');
var elisionAfterComma18 = [59,,];
check(elisionAfterComma18.length === 2, 'elision trailing length 18');
check((0 in elisionAfterComma18) && !(1 in elisionAfterComma18), 'elision trailing properties 18');
var noExtraElement19 = [60,];
check(noExtraElement19.length === 1, 'single trailing length 19');
check((0 in noExtraElement19) && !(1 in noExtraElement19), 'single trailing properties 19');
check(noExtraElement19[0] === 60, 'single trailing value 19');
var twoTrailing19 = [60, 61,];
check(twoTrailing19.length === 2, 'two trailing length 19');
check(twoTrailing19[0] === 60 && twoTrailing19[1] === 61, 'two trailing values 19');
check(!(2 in twoTrailing19), 'two trailing no property 19');
var elisionAfterComma19 = [60,,];
check(elisionAfterComma19.length === 2, 'elision trailing length 19');
check((0 in elisionAfterComma19) && !(1 in elisionAfterComma19), 'elision trailing properties 19');
var noExtraElement20 = [61,];
check(noExtraElement20.length === 1, 'single trailing length 20');
check((0 in noExtraElement20) && !(1 in noExtraElement20), 'single trailing properties 20');
check(noExtraElement20[0] === 61, 'single trailing value 20');
var twoTrailing20 = [61, 62,];
check(twoTrailing20.length === 2, 'two trailing length 20');
check(twoTrailing20[0] === 61 && twoTrailing20[1] === 62, 'two trailing values 20');
check(!(2 in twoTrailing20), 'two trailing no property 20');
var elisionAfterComma20 = [61,,];
check(elisionAfterComma20.length === 2, 'elision trailing length 20');
check((0 in elisionAfterComma20) && !(1 in elisionAfterComma20), 'elision trailing properties 20');
var noExtraElement21 = [62,];
check(noExtraElement21.length === 1, 'single trailing length 21');
check((0 in noExtraElement21) && !(1 in noExtraElement21), 'single trailing properties 21');
check(noExtraElement21[0] === 62, 'single trailing value 21');
var twoTrailing21 = [62, 63,];
check(twoTrailing21.length === 2, 'two trailing length 21');
check(twoTrailing21[0] === 62 && twoTrailing21[1] === 63, 'two trailing values 21');
check(!(2 in twoTrailing21), 'two trailing no property 21');
var elisionAfterComma21 = [62,,];
check(elisionAfterComma21.length === 2, 'elision trailing length 21');
check((0 in elisionAfterComma21) && !(1 in elisionAfterComma21), 'elision trailing properties 21');
var noExtraElement22 = [63,];
check(noExtraElement22.length === 1, 'single trailing length 22');
check((0 in noExtraElement22) && !(1 in noExtraElement22), 'single trailing properties 22');
check(noExtraElement22[0] === 63, 'single trailing value 22');
var twoTrailing22 = [63, 64,];
check(twoTrailing22.length === 2, 'two trailing length 22');
check(twoTrailing22[0] === 63 && twoTrailing22[1] === 64, 'two trailing values 22');
check(!(2 in twoTrailing22), 'two trailing no property 22');
var elisionAfterComma22 = [63,,];
check(elisionAfterComma22.length === 2, 'elision trailing length 22');
check((0 in elisionAfterComma22) && !(1 in elisionAfterComma22), 'elision trailing properties 22');
var noExtraElement23 = [64,];
check(noExtraElement23.length === 1, 'single trailing length 23');
check((0 in noExtraElement23) && !(1 in noExtraElement23), 'single trailing properties 23');
check(noExtraElement23[0] === 64, 'single trailing value 23');
var twoTrailing23 = [64, 65,];
check(twoTrailing23.length === 2, 'two trailing length 23');
check(twoTrailing23[0] === 64 && twoTrailing23[1] === 65, 'two trailing values 23');
check(!(2 in twoTrailing23), 'two trailing no property 23');
var elisionAfterComma23 = [64,,];
check(elisionAfterComma23.length === 2, 'elision trailing length 23');
check((0 in elisionAfterComma23) && !(1 in elisionAfterComma23), 'elision trailing properties 23');
var noExtraElement24 = [65,];
check(noExtraElement24.length === 1, 'single trailing length 24');
check((0 in noExtraElement24) && !(1 in noExtraElement24), 'single trailing properties 24');
check(noExtraElement24[0] === 65, 'single trailing value 24');
var twoTrailing24 = [65, 66,];
check(twoTrailing24.length === 2, 'two trailing length 24');
check(twoTrailing24[0] === 65 && twoTrailing24[1] === 66, 'two trailing values 24');
check(!(2 in twoTrailing24), 'two trailing no property 24');
var elisionAfterComma24 = [65,,];
check(elisionAfterComma24.length === 2, 'elision trailing length 24');
check((0 in elisionAfterComma24) && !(1 in elisionAfterComma24), 'elision trailing properties 24');
var noExtraElement25 = [66,];
check(noExtraElement25.length === 1, 'single trailing length 25');
check((0 in noExtraElement25) && !(1 in noExtraElement25), 'single trailing properties 25');
check(noExtraElement25[0] === 66, 'single trailing value 25');
var twoTrailing25 = [66, 67,];
check(twoTrailing25.length === 2, 'two trailing length 25');
check(twoTrailing25[0] === 66 && twoTrailing25[1] === 67, 'two trailing values 25');
check(!(2 in twoTrailing25), 'two trailing no property 25');
var elisionAfterComma25 = [66,,];
check(elisionAfterComma25.length === 2, 'elision trailing length 25');
check((0 in elisionAfterComma25) && !(1 in elisionAfterComma25), 'elision trailing properties 25');
var noExtraElement26 = [67,];
check(noExtraElement26.length === 1, 'single trailing length 26');
check((0 in noExtraElement26) && !(1 in noExtraElement26), 'single trailing properties 26');
check(noExtraElement26[0] === 67, 'single trailing value 26');
var twoTrailing26 = [67, 68,];
check(twoTrailing26.length === 2, 'two trailing length 26');
check(twoTrailing26[0] === 67 && twoTrailing26[1] === 68, 'two trailing values 26');
check(!(2 in twoTrailing26), 'two trailing no property 26');
var elisionAfterComma26 = [67,,];
check(elisionAfterComma26.length === 2, 'elision trailing length 26');
check((0 in elisionAfterComma26) && !(1 in elisionAfterComma26), 'elision trailing properties 26');
var noExtraElement27 = [68,];
check(noExtraElement27.length === 1, 'single trailing length 27');
check((0 in noExtraElement27) && !(1 in noExtraElement27), 'single trailing properties 27');
check(noExtraElement27[0] === 68, 'single trailing value 27');
var twoTrailing27 = [68, 69,];
check(twoTrailing27.length === 2, 'two trailing length 27');
check(twoTrailing27[0] === 68 && twoTrailing27[1] === 69, 'two trailing values 27');
check(!(2 in twoTrailing27), 'two trailing no property 27');
var elisionAfterComma27 = [68,,];
check(elisionAfterComma27.length === 2, 'elision trailing length 27');
check((0 in elisionAfterComma27) && !(1 in elisionAfterComma27), 'elision trailing properties 27');
var noExtraElement28 = [69,];
check(noExtraElement28.length === 1, 'single trailing length 28');
check((0 in noExtraElement28) && !(1 in noExtraElement28), 'single trailing properties 28');
check(noExtraElement28[0] === 69, 'single trailing value 28');
var twoTrailing28 = [69, 70,];
check(twoTrailing28.length === 2, 'two trailing length 28');
check(twoTrailing28[0] === 69 && twoTrailing28[1] === 70, 'two trailing values 28');
check(!(2 in twoTrailing28), 'two trailing no property 28');
var elisionAfterComma28 = [69,,];
check(elisionAfterComma28.length === 2, 'elision trailing length 28');
check((0 in elisionAfterComma28) && !(1 in elisionAfterComma28), 'elision trailing properties 28');
var noExtraElement29 = [70,];
check(noExtraElement29.length === 1, 'single trailing length 29');
check((0 in noExtraElement29) && !(1 in noExtraElement29), 'single trailing properties 29');
check(noExtraElement29[0] === 70, 'single trailing value 29');
var twoTrailing29 = [70, 71,];
check(twoTrailing29.length === 2, 'two trailing length 29');
check(twoTrailing29[0] === 70 && twoTrailing29[1] === 71, 'two trailing values 29');
check(!(2 in twoTrailing29), 'two trailing no property 29');
var elisionAfterComma29 = [70,,];
check(elisionAfterComma29.length === 2, 'elision trailing length 29');
check((0 in elisionAfterComma29) && !(1 in elisionAfterComma29), 'elision trailing properties 29');
var noExtraElement30 = [71,];
check(noExtraElement30.length === 1, 'single trailing length 30');
check((0 in noExtraElement30) && !(1 in noExtraElement30), 'single trailing properties 30');
check(noExtraElement30[0] === 71, 'single trailing value 30');
var twoTrailing30 = [71, 72,];
check(twoTrailing30.length === 2, 'two trailing length 30');
check(twoTrailing30[0] === 71 && twoTrailing30[1] === 72, 'two trailing values 30');
check(!(2 in twoTrailing30), 'two trailing no property 30');
var elisionAfterComma30 = [71,,];
check(elisionAfterComma30.length === 2, 'elision trailing length 30');
check((0 in elisionAfterComma30) && !(1 in elisionAfterComma30), 'elision trailing properties 30');
var noExtraElement31 = [72,];
check(noExtraElement31.length === 1, 'single trailing length 31');
check((0 in noExtraElement31) && !(1 in noExtraElement31), 'single trailing properties 31');
check(noExtraElement31[0] === 72, 'single trailing value 31');
var twoTrailing31 = [72, 73,];
check(twoTrailing31.length === 2, 'two trailing length 31');
check(twoTrailing31[0] === 72 && twoTrailing31[1] === 73, 'two trailing values 31');
check(!(2 in twoTrailing31), 'two trailing no property 31');
var elisionAfterComma31 = [72,,];
check(elisionAfterComma31.length === 2, 'elision trailing length 31');
check((0 in elisionAfterComma31) && !(1 in elisionAfterComma31), 'elision trailing properties 31');
var noExtraElement32 = [73,];
check(noExtraElement32.length === 1, 'single trailing length 32');
check((0 in noExtraElement32) && !(1 in noExtraElement32), 'single trailing properties 32');
check(noExtraElement32[0] === 73, 'single trailing value 32');
var twoTrailing32 = [73, 74,];
check(twoTrailing32.length === 2, 'two trailing length 32');
check(twoTrailing32[0] === 73 && twoTrailing32[1] === 74, 'two trailing values 32');
check(!(2 in twoTrailing32), 'two trailing no property 32');
var elisionAfterComma32 = [73,,];
check(elisionAfterComma32.length === 2, 'elision trailing length 32');
check((0 in elisionAfterComma32) && !(1 in elisionAfterComma32), 'elision trailing properties 32');
var noExtraElement33 = [74,];
check(noExtraElement33.length === 1, 'single trailing length 33');
check((0 in noExtraElement33) && !(1 in noExtraElement33), 'single trailing properties 33');
check(noExtraElement33[0] === 74, 'single trailing value 33');
var twoTrailing33 = [74, 75,];
check(twoTrailing33.length === 2, 'two trailing length 33');
check(twoTrailing33[0] === 74 && twoTrailing33[1] === 75, 'two trailing values 33');
check(!(2 in twoTrailing33), 'two trailing no property 33');
var elisionAfterComma33 = [74,,];
check(elisionAfterComma33.length === 2, 'elision trailing length 33');
check((0 in elisionAfterComma33) && !(1 in elisionAfterComma33), 'elision trailing properties 33');
var noExtraElement34 = [75,];
check(noExtraElement34.length === 1, 'single trailing length 34');
check((0 in noExtraElement34) && !(1 in noExtraElement34), 'single trailing properties 34');
check(noExtraElement34[0] === 75, 'single trailing value 34');
var twoTrailing34 = [75, 76,];
check(twoTrailing34.length === 2, 'two trailing length 34');
check(twoTrailing34[0] === 75 && twoTrailing34[1] === 76, 'two trailing values 34');
check(!(2 in twoTrailing34), 'two trailing no property 34');
var elisionAfterComma34 = [75,,];
check(elisionAfterComma34.length === 2, 'elision trailing length 34');
check((0 in elisionAfterComma34) && !(1 in elisionAfterComma34), 'elision trailing properties 34');
var noExtraElement35 = [76,];
check(noExtraElement35.length === 1, 'single trailing length 35');
check((0 in noExtraElement35) && !(1 in noExtraElement35), 'single trailing properties 35');
check(noExtraElement35[0] === 76, 'single trailing value 35');
var twoTrailing35 = [76, 77,];
check(twoTrailing35.length === 2, 'two trailing length 35');
check(twoTrailing35[0] === 76 && twoTrailing35[1] === 77, 'two trailing values 35');
check(!(2 in twoTrailing35), 'two trailing no property 35');
var elisionAfterComma35 = [76,,];
check(elisionAfterComma35.length === 2, 'elision trailing length 35');
check((0 in elisionAfterComma35) && !(1 in elisionAfterComma35), 'elision trailing properties 35');
var noExtraElement36 = [77,];
check(noExtraElement36.length === 1, 'single trailing length 36');
check((0 in noExtraElement36) && !(1 in noExtraElement36), 'single trailing properties 36');
check(noExtraElement36[0] === 77, 'single trailing value 36');
var twoTrailing36 = [77, 78,];
check(twoTrailing36.length === 2, 'two trailing length 36');
check(twoTrailing36[0] === 77 && twoTrailing36[1] === 78, 'two trailing values 36');
check(!(2 in twoTrailing36), 'two trailing no property 36');
var elisionAfterComma36 = [77,,];
check(elisionAfterComma36.length === 2, 'elision trailing length 36');
check((0 in elisionAfterComma36) && !(1 in elisionAfterComma36), 'elision trailing properties 36');
var noExtraElement37 = [78,];
check(noExtraElement37.length === 1, 'single trailing length 37');
check((0 in noExtraElement37) && !(1 in noExtraElement37), 'single trailing properties 37');
check(noExtraElement37[0] === 78, 'single trailing value 37');
var twoTrailing37 = [78, 79,];
check(twoTrailing37.length === 2, 'two trailing length 37');
check(twoTrailing37[0] === 78 && twoTrailing37[1] === 79, 'two trailing values 37');
check(!(2 in twoTrailing37), 'two trailing no property 37');
var elisionAfterComma37 = [78,,];
check(elisionAfterComma37.length === 2, 'elision trailing length 37');
check((0 in elisionAfterComma37) && !(1 in elisionAfterComma37), 'elision trailing properties 37');
var noExtraElement38 = [79,];
check(noExtraElement38.length === 1, 'single trailing length 38');
check((0 in noExtraElement38) && !(1 in noExtraElement38), 'single trailing properties 38');
check(noExtraElement38[0] === 79, 'single trailing value 38');
var twoTrailing38 = [79, 80,];
check(twoTrailing38.length === 2, 'two trailing length 38');
check(twoTrailing38[0] === 79 && twoTrailing38[1] === 80, 'two trailing values 38');
check(!(2 in twoTrailing38), 'two trailing no property 38');
var elisionAfterComma38 = [79,,];
check(elisionAfterComma38.length === 2, 'elision trailing length 38');
check((0 in elisionAfterComma38) && !(1 in elisionAfterComma38), 'elision trailing properties 38');
var noExtraElement39 = [80,];
check(noExtraElement39.length === 1, 'single trailing length 39');
check((0 in noExtraElement39) && !(1 in noExtraElement39), 'single trailing properties 39');
check(noExtraElement39[0] === 80, 'single trailing value 39');
var twoTrailing39 = [80, 81,];
check(twoTrailing39.length === 2, 'two trailing length 39');
check(twoTrailing39[0] === 80 && twoTrailing39[1] === 81, 'two trailing values 39');
check(!(2 in twoTrailing39), 'two trailing no property 39');
var elisionAfterComma39 = [80,,];
check(elisionAfterComma39.length === 2, 'elision trailing length 39');
check((0 in elisionAfterComma39) && !(1 in elisionAfterComma39), 'elision trailing properties 39');
var noExtraElement40 = [81,];
check(noExtraElement40.length === 1, 'single trailing length 40');
check((0 in noExtraElement40) && !(1 in noExtraElement40), 'single trailing properties 40');
check(noExtraElement40[0] === 81, 'single trailing value 40');
var twoTrailing40 = [81, 82,];
check(twoTrailing40.length === 2, 'two trailing length 40');
check(twoTrailing40[0] === 81 && twoTrailing40[1] === 82, 'two trailing values 40');
check(!(2 in twoTrailing40), 'two trailing no property 40');
var elisionAfterComma40 = [81,,];
check(elisionAfterComma40.length === 2, 'elision trailing length 40');
check((0 in elisionAfterComma40) && !(1 in elisionAfterComma40), 'elision trailing properties 40');
var noExtraElement41 = [82,];
check(noExtraElement41.length === 1, 'single trailing length 41');
check((0 in noExtraElement41) && !(1 in noExtraElement41), 'single trailing properties 41');
check(noExtraElement41[0] === 82, 'single trailing value 41');
var twoTrailing41 = [82, 83,];
check(twoTrailing41.length === 2, 'two trailing length 41');
check(twoTrailing41[0] === 82 && twoTrailing41[1] === 83, 'two trailing values 41');
check(!(2 in twoTrailing41), 'two trailing no property 41');
var elisionAfterComma41 = [82,,];
check(elisionAfterComma41.length === 2, 'elision trailing length 41');
check((0 in elisionAfterComma41) && !(1 in elisionAfterComma41), 'elision trailing properties 41');
var noExtraElement42 = [83,];
check(noExtraElement42.length === 1, 'single trailing length 42');
check((0 in noExtraElement42) && !(1 in noExtraElement42), 'single trailing properties 42');
check(noExtraElement42[0] === 83, 'single trailing value 42');
var twoTrailing42 = [83, 84,];
check(twoTrailing42.length === 2, 'two trailing length 42');
check(twoTrailing42[0] === 83 && twoTrailing42[1] === 84, 'two trailing values 42');
check(!(2 in twoTrailing42), 'two trailing no property 42');
var elisionAfterComma42 = [83,,];
check(elisionAfterComma42.length === 2, 'elision trailing length 42');
check((0 in elisionAfterComma42) && !(1 in elisionAfterComma42), 'elision trailing properties 42');
var noExtraElement43 = [84,];
check(noExtraElement43.length === 1, 'single trailing length 43');
check((0 in noExtraElement43) && !(1 in noExtraElement43), 'single trailing properties 43');
check(noExtraElement43[0] === 84, 'single trailing value 43');
var twoTrailing43 = [84, 85,];
check(twoTrailing43.length === 2, 'two trailing length 43');
check(twoTrailing43[0] === 84 && twoTrailing43[1] === 85, 'two trailing values 43');
check(!(2 in twoTrailing43), 'two trailing no property 43');
var elisionAfterComma43 = [84,,];
check(elisionAfterComma43.length === 2, 'elision trailing length 43');
check((0 in elisionAfterComma43) && !(1 in elisionAfterComma43), 'elision trailing properties 43');
var noExtraElement44 = [85,];
check(noExtraElement44.length === 1, 'single trailing length 44');
check((0 in noExtraElement44) && !(1 in noExtraElement44), 'single trailing properties 44');
check(noExtraElement44[0] === 85, 'single trailing value 44');
var twoTrailing44 = [85, 86,];
check(twoTrailing44.length === 2, 'two trailing length 44');
check(twoTrailing44[0] === 85 && twoTrailing44[1] === 86, 'two trailing values 44');
check(!(2 in twoTrailing44), 'two trailing no property 44');
var elisionAfterComma44 = [85,,];
check(elisionAfterComma44.length === 2, 'elision trailing length 44');
check((0 in elisionAfterComma44) && !(1 in elisionAfterComma44), 'elision trailing properties 44');
var noExtraElement45 = [86,];
check(noExtraElement45.length === 1, 'single trailing length 45');
check((0 in noExtraElement45) && !(1 in noExtraElement45), 'single trailing properties 45');
check(noExtraElement45[0] === 86, 'single trailing value 45');
var twoTrailing45 = [86, 87,];
check(twoTrailing45.length === 2, 'two trailing length 45');
check(twoTrailing45[0] === 86 && twoTrailing45[1] === 87, 'two trailing values 45');
check(!(2 in twoTrailing45), 'two trailing no property 45');
var elisionAfterComma45 = [86,,];
check(elisionAfterComma45.length === 2, 'elision trailing length 45');
check((0 in elisionAfterComma45) && !(1 in elisionAfterComma45), 'elision trailing properties 45');
var noExtraElement46 = [87,];
check(noExtraElement46.length === 1, 'single trailing length 46');
check((0 in noExtraElement46) && !(1 in noExtraElement46), 'single trailing properties 46');
check(noExtraElement46[0] === 87, 'single trailing value 46');
var twoTrailing46 = [87, 88,];
check(twoTrailing46.length === 2, 'two trailing length 46');
check(twoTrailing46[0] === 87 && twoTrailing46[1] === 88, 'two trailing values 46');
check(!(2 in twoTrailing46), 'two trailing no property 46');
var elisionAfterComma46 = [87,,];
check(elisionAfterComma46.length === 2, 'elision trailing length 46');
check((0 in elisionAfterComma46) && !(1 in elisionAfterComma46), 'elision trailing properties 46');
var noExtraElement47 = [88,];
check(noExtraElement47.length === 1, 'single trailing length 47');
check((0 in noExtraElement47) && !(1 in noExtraElement47), 'single trailing properties 47');
check(noExtraElement47[0] === 88, 'single trailing value 47');
var twoTrailing47 = [88, 89,];
check(twoTrailing47.length === 2, 'two trailing length 47');
check(twoTrailing47[0] === 88 && twoTrailing47[1] === 89, 'two trailing values 47');
check(!(2 in twoTrailing47), 'two trailing no property 47');
var elisionAfterComma47 = [88,,];
check(elisionAfterComma47.length === 2, 'elision trailing length 47');
check((0 in elisionAfterComma47) && !(1 in elisionAfterComma47), 'elision trailing properties 47');
var noExtraElement48 = [89,];
check(noExtraElement48.length === 1, 'single trailing length 48');
check((0 in noExtraElement48) && !(1 in noExtraElement48), 'single trailing properties 48');
check(noExtraElement48[0] === 89, 'single trailing value 48');
var twoTrailing48 = [89, 90,];
check(twoTrailing48.length === 2, 'two trailing length 48');
check(twoTrailing48[0] === 89 && twoTrailing48[1] === 90, 'two trailing values 48');
check(!(2 in twoTrailing48), 'two trailing no property 48');
var elisionAfterComma48 = [89,,];
check(elisionAfterComma48.length === 2, 'elision trailing length 48');
check((0 in elisionAfterComma48) && !(1 in elisionAfterComma48), 'elision trailing properties 48');
var noExtraElement49 = [90,];
check(noExtraElement49.length === 1, 'single trailing length 49');
check((0 in noExtraElement49) && !(1 in noExtraElement49), 'single trailing properties 49');
check(noExtraElement49[0] === 90, 'single trailing value 49');
var twoTrailing49 = [90, 91,];
check(twoTrailing49.length === 2, 'two trailing length 49');
check(twoTrailing49[0] === 90 && twoTrailing49[1] === 91, 'two trailing values 49');
check(!(2 in twoTrailing49), 'two trailing no property 49');
var elisionAfterComma49 = [90,,];
check(elisionAfterComma49.length === 2, 'elision trailing length 49');
check((0 in elisionAfterComma49) && !(1 in elisionAfterComma49), 'elision trailing properties 49');
var noExtraElement50 = [91,];
check(noExtraElement50.length === 1, 'single trailing length 50');
check((0 in noExtraElement50) && !(1 in noExtraElement50), 'single trailing properties 50');
check(noExtraElement50[0] === 91, 'single trailing value 50');
var twoTrailing50 = [91, 92,];
check(twoTrailing50.length === 2, 'two trailing length 50');
check(twoTrailing50[0] === 91 && twoTrailing50[1] === 92, 'two trailing values 50');
check(!(2 in twoTrailing50), 'two trailing no property 50');
var elisionAfterComma50 = [91,,];
check(elisionAfterComma50.length === 2, 'elision trailing length 50');
check((0 in elisionAfterComma50) && !(1 in elisionAfterComma50), 'elision trailing properties 50');
var noExtraElement51 = [92,];
check(noExtraElement51.length === 1, 'single trailing length 51');
check((0 in noExtraElement51) && !(1 in noExtraElement51), 'single trailing properties 51');
check(noExtraElement51[0] === 92, 'single trailing value 51');
var twoTrailing51 = [92, 93,];
check(twoTrailing51.length === 2, 'two trailing length 51');
check(twoTrailing51[0] === 92 && twoTrailing51[1] === 93, 'two trailing values 51');
check(!(2 in twoTrailing51), 'two trailing no property 51');
var elisionAfterComma51 = [92,,];
check(elisionAfterComma51.length === 2, 'elision trailing length 51');
check((0 in elisionAfterComma51) && !(1 in elisionAfterComma51), 'elision trailing properties 51');
var noExtraElement52 = [93,];
check(noExtraElement52.length === 1, 'single trailing length 52');
check((0 in noExtraElement52) && !(1 in noExtraElement52), 'single trailing properties 52');
check(noExtraElement52[0] === 93, 'single trailing value 52');
var twoTrailing52 = [93, 94,];
check(twoTrailing52.length === 2, 'two trailing length 52');
check(twoTrailing52[0] === 93 && twoTrailing52[1] === 94, 'two trailing values 52');
check(!(2 in twoTrailing52), 'two trailing no property 52');
var elisionAfterComma52 = [93,,];
check(elisionAfterComma52.length === 2, 'elision trailing length 52');
check((0 in elisionAfterComma52) && !(1 in elisionAfterComma52), 'elision trailing properties 52');
var noExtraElement53 = [94,];
check(noExtraElement53.length === 1, 'single trailing length 53');
check((0 in noExtraElement53) && !(1 in noExtraElement53), 'single trailing properties 53');
check(noExtraElement53[0] === 94, 'single trailing value 53');
var twoTrailing53 = [94, 95,];
check(twoTrailing53.length === 2, 'two trailing length 53');
check(twoTrailing53[0] === 94 && twoTrailing53[1] === 95, 'two trailing values 53');
check(!(2 in twoTrailing53), 'two trailing no property 53');
var elisionAfterComma53 = [94,,];
check(elisionAfterComma53.length === 2, 'elision trailing length 53');
check((0 in elisionAfterComma53) && !(1 in elisionAfterComma53), 'elision trailing properties 53');
var noExtraElement54 = [95,];
check(noExtraElement54.length === 1, 'single trailing length 54');
check((0 in noExtraElement54) && !(1 in noExtraElement54), 'single trailing properties 54');
check(noExtraElement54[0] === 95, 'single trailing value 54');
var twoTrailing54 = [95, 96,];
check(twoTrailing54.length === 2, 'two trailing length 54');
check(twoTrailing54[0] === 95 && twoTrailing54[1] === 96, 'two trailing values 54');
check(!(2 in twoTrailing54), 'two trailing no property 54');
var elisionAfterComma54 = [95,,];
check(elisionAfterComma54.length === 2, 'elision trailing length 54');
check((0 in elisionAfterComma54) && !(1 in elisionAfterComma54), 'elision trailing properties 54');
var noExtraElement55 = [96,];
check(noExtraElement55.length === 1, 'single trailing length 55');
check((0 in noExtraElement55) && !(1 in noExtraElement55), 'single trailing properties 55');
check(noExtraElement55[0] === 96, 'single trailing value 55');
var twoTrailing55 = [96, 97,];
check(twoTrailing55.length === 2, 'two trailing length 55');
check(twoTrailing55[0] === 96 && twoTrailing55[1] === 97, 'two trailing values 55');
check(!(2 in twoTrailing55), 'two trailing no property 55');
var elisionAfterComma55 = [96,,];
check(elisionAfterComma55.length === 2, 'elision trailing length 55');
check((0 in elisionAfterComma55) && !(1 in elisionAfterComma55), 'elision trailing properties 55');
var noExtraElement56 = [97,];
check(noExtraElement56.length === 1, 'single trailing length 56');
check((0 in noExtraElement56) && !(1 in noExtraElement56), 'single trailing properties 56');
check(noExtraElement56[0] === 97, 'single trailing value 56');
var twoTrailing56 = [97, 98,];
check(twoTrailing56.length === 2, 'two trailing length 56');
check(twoTrailing56[0] === 97 && twoTrailing56[1] === 98, 'two trailing values 56');
check(!(2 in twoTrailing56), 'two trailing no property 56');
var elisionAfterComma56 = [97,,];
check(elisionAfterComma56.length === 2, 'elision trailing length 56');
check((0 in elisionAfterComma56) && !(1 in elisionAfterComma56), 'elision trailing properties 56');
var noExtraElement57 = [98,];
check(noExtraElement57.length === 1, 'single trailing length 57');
check((0 in noExtraElement57) && !(1 in noExtraElement57), 'single trailing properties 57');
check(noExtraElement57[0] === 98, 'single trailing value 57');
var twoTrailing57 = [98, 99,];
check(twoTrailing57.length === 2, 'two trailing length 57');
check(twoTrailing57[0] === 98 && twoTrailing57[1] === 99, 'two trailing values 57');
check(!(2 in twoTrailing57), 'two trailing no property 57');
var elisionAfterComma57 = [98,,];
check(elisionAfterComma57.length === 2, 'elision trailing length 57');
check((0 in elisionAfterComma57) && !(1 in elisionAfterComma57), 'elision trailing properties 57');
var noExtraElement58 = [99,];
check(noExtraElement58.length === 1, 'single trailing length 58');
check((0 in noExtraElement58) && !(1 in noExtraElement58), 'single trailing properties 58');
check(noExtraElement58[0] === 99, 'single trailing value 58');
var twoTrailing58 = [99, 100,];
check(twoTrailing58.length === 2, 'two trailing length 58');
check(twoTrailing58[0] === 99 && twoTrailing58[1] === 100, 'two trailing values 58');
check(!(2 in twoTrailing58), 'two trailing no property 58');
var elisionAfterComma58 = [99,,];
check(elisionAfterComma58.length === 2, 'elision trailing length 58');
check((0 in elisionAfterComma58) && !(1 in elisionAfterComma58), 'elision trailing properties 58');
var noExtraElement59 = [100,];
check(noExtraElement59.length === 1, 'single trailing length 59');
check((0 in noExtraElement59) && !(1 in noExtraElement59), 'single trailing properties 59');
check(noExtraElement59[0] === 100, 'single trailing value 59');
var twoTrailing59 = [100, 101,];
check(twoTrailing59.length === 2, 'two trailing length 59');
check(twoTrailing59[0] === 100 && twoTrailing59[1] === 101, 'two trailing values 59');
check(!(2 in twoTrailing59), 'two trailing no property 59');
var elisionAfterComma59 = [100,,];
check(elisionAfterComma59.length === 2, 'elision trailing length 59');
check((0 in elisionAfterComma59) && !(1 in elisionAfterComma59), 'elision trailing properties 59');
var noExtraElement60 = [101,];
check(noExtraElement60.length === 1, 'single trailing length 60');
check((0 in noExtraElement60) && !(1 in noExtraElement60), 'single trailing properties 60');
check(noExtraElement60[0] === 101, 'single trailing value 60');
var twoTrailing60 = [101, 102,];
check(twoTrailing60.length === 2, 'two trailing length 60');
check(twoTrailing60[0] === 101 && twoTrailing60[1] === 102, 'two trailing values 60');
check(!(2 in twoTrailing60), 'two trailing no property 60');
var elisionAfterComma60 = [101,,];
check(elisionAfterComma60.length === 2, 'elision trailing length 60');
check((0 in elisionAfterComma60) && !(1 in elisionAfterComma60), 'elision trailing properties 60');
var noExtraElement61 = [102,];
check(noExtraElement61.length === 1, 'single trailing length 61');
check((0 in noExtraElement61) && !(1 in noExtraElement61), 'single trailing properties 61');
check(noExtraElement61[0] === 102, 'single trailing value 61');
var twoTrailing61 = [102, 103,];
check(twoTrailing61.length === 2, 'two trailing length 61');
check(twoTrailing61[0] === 102 && twoTrailing61[1] === 103, 'two trailing values 61');
check(!(2 in twoTrailing61), 'two trailing no property 61');
var elisionAfterComma61 = [102,,];
check(elisionAfterComma61.length === 2, 'elision trailing length 61');
check((0 in elisionAfterComma61) && !(1 in elisionAfterComma61), 'elision trailing properties 61');
var noExtraElement62 = [103,];
check(noExtraElement62.length === 1, 'single trailing length 62');
check((0 in noExtraElement62) && !(1 in noExtraElement62), 'single trailing properties 62');
check(noExtraElement62[0] === 103, 'single trailing value 62');
var twoTrailing62 = [103, 104,];
check(twoTrailing62.length === 2, 'two trailing length 62');
check(twoTrailing62[0] === 103 && twoTrailing62[1] === 104, 'two trailing values 62');
check(!(2 in twoTrailing62), 'two trailing no property 62');
var elisionAfterComma62 = [103,,];
check(elisionAfterComma62.length === 2, 'elision trailing length 62');
check((0 in elisionAfterComma62) && !(1 in elisionAfterComma62), 'elision trailing properties 62');
var noExtraElement63 = [104,];
check(noExtraElement63.length === 1, 'single trailing length 63');
check((0 in noExtraElement63) && !(1 in noExtraElement63), 'single trailing properties 63');
check(noExtraElement63[0] === 104, 'single trailing value 63');
var twoTrailing63 = [104, 105,];
check(twoTrailing63.length === 2, 'two trailing length 63');
check(twoTrailing63[0] === 104 && twoTrailing63[1] === 105, 'two trailing values 63');
check(!(2 in twoTrailing63), 'two trailing no property 63');
var elisionAfterComma63 = [104,,];
check(elisionAfterComma63.length === 2, 'elision trailing length 63');
check((0 in elisionAfterComma63) && !(1 in elisionAfterComma63), 'elision trailing properties 63');
var noExtraElement64 = [105,];
check(noExtraElement64.length === 1, 'single trailing length 64');
check((0 in noExtraElement64) && !(1 in noExtraElement64), 'single trailing properties 64');
check(noExtraElement64[0] === 105, 'single trailing value 64');
var twoTrailing64 = [105, 106,];
check(twoTrailing64.length === 2, 'two trailing length 64');
check(twoTrailing64[0] === 105 && twoTrailing64[1] === 106, 'two trailing values 64');
check(!(2 in twoTrailing64), 'two trailing no property 64');
var elisionAfterComma64 = [105,,];
check(elisionAfterComma64.length === 2, 'elision trailing length 64');
check((0 in elisionAfterComma64) && !(1 in elisionAfterComma64), 'elision trailing properties 64');
var noExtraElement65 = [106,];
check(noExtraElement65.length === 1, 'single trailing length 65');
check((0 in noExtraElement65) && !(1 in noExtraElement65), 'single trailing properties 65');
check(noExtraElement65[0] === 106, 'single trailing value 65');
var twoTrailing65 = [106, 107,];
check(twoTrailing65.length === 2, 'two trailing length 65');
check(twoTrailing65[0] === 106 && twoTrailing65[1] === 107, 'two trailing values 65');
check(!(2 in twoTrailing65), 'two trailing no property 65');
var elisionAfterComma65 = [106,,];
check(elisionAfterComma65.length === 2, 'elision trailing length 65');
check((0 in elisionAfterComma65) && !(1 in elisionAfterComma65), 'elision trailing properties 65');
var noExtraElement66 = [107,];
check(noExtraElement66.length === 1, 'single trailing length 66');
check((0 in noExtraElement66) && !(1 in noExtraElement66), 'single trailing properties 66');
check(noExtraElement66[0] === 107, 'single trailing value 66');
var twoTrailing66 = [107, 108,];
check(twoTrailing66.length === 2, 'two trailing length 66');
check(twoTrailing66[0] === 107 && twoTrailing66[1] === 108, 'two trailing values 66');
check(!(2 in twoTrailing66), 'two trailing no property 66');
var elisionAfterComma66 = [107,,];
check(elisionAfterComma66.length === 2, 'elision trailing length 66');
check((0 in elisionAfterComma66) && !(1 in elisionAfterComma66), 'elision trailing properties 66');
var noExtraElement67 = [108,];
check(noExtraElement67.length === 1, 'single trailing length 67');
check((0 in noExtraElement67) && !(1 in noExtraElement67), 'single trailing properties 67');
check(noExtraElement67[0] === 108, 'single trailing value 67');
var twoTrailing67 = [108, 109,];
check(twoTrailing67.length === 2, 'two trailing length 67');
check(twoTrailing67[0] === 108 && twoTrailing67[1] === 109, 'two trailing values 67');
check(!(2 in twoTrailing67), 'two trailing no property 67');
var elisionAfterComma67 = [108,,];
check(elisionAfterComma67.length === 2, 'elision trailing length 67');
check((0 in elisionAfterComma67) && !(1 in elisionAfterComma67), 'elision trailing properties 67');
var noExtraElement68 = [109,];
check(noExtraElement68.length === 1, 'single trailing length 68');
check((0 in noExtraElement68) && !(1 in noExtraElement68), 'single trailing properties 68');
check(noExtraElement68[0] === 109, 'single trailing value 68');
var twoTrailing68 = [109, 110,];
check(twoTrailing68.length === 2, 'two trailing length 68');
check(twoTrailing68[0] === 109 && twoTrailing68[1] === 110, 'two trailing values 68');
check(!(2 in twoTrailing68), 'two trailing no property 68');
var elisionAfterComma68 = [109,,];
check(elisionAfterComma68.length === 2, 'elision trailing length 68');
check((0 in elisionAfterComma68) && !(1 in elisionAfterComma68), 'elision trailing properties 68');
var noExtraElement69 = [110,];
check(noExtraElement69.length === 1, 'single trailing length 69');
check((0 in noExtraElement69) && !(1 in noExtraElement69), 'single trailing properties 69');
check(noExtraElement69[0] === 110, 'single trailing value 69');
var twoTrailing69 = [110, 111,];
check(twoTrailing69.length === 2, 'two trailing length 69');
check(twoTrailing69[0] === 110 && twoTrailing69[1] === 111, 'two trailing values 69');
check(!(2 in twoTrailing69), 'two trailing no property 69');
var elisionAfterComma69 = [110,,];
check(elisionAfterComma69.length === 2, 'elision trailing length 69');
check((0 in elisionAfterComma69) && !(1 in elisionAfterComma69), 'elision trailing properties 69');
var noExtraElement70 = [111,];
check(noExtraElement70.length === 1, 'single trailing length 70');
check((0 in noExtraElement70) && !(1 in noExtraElement70), 'single trailing properties 70');
check(noExtraElement70[0] === 111, 'single trailing value 70');
var twoTrailing70 = [111, 112,];
check(twoTrailing70.length === 2, 'two trailing length 70');
check(twoTrailing70[0] === 111 && twoTrailing70[1] === 112, 'two trailing values 70');
check(!(2 in twoTrailing70), 'two trailing no property 70');
var elisionAfterComma70 = [111,,];
check(elisionAfterComma70.length === 2, 'elision trailing length 70');
check((0 in elisionAfterComma70) && !(1 in elisionAfterComma70), 'elision trailing properties 70');
var noExtraElement71 = [112,];
check(noExtraElement71.length === 1, 'single trailing length 71');
check((0 in noExtraElement71) && !(1 in noExtraElement71), 'single trailing properties 71');
check(noExtraElement71[0] === 112, 'single trailing value 71');
var twoTrailing71 = [112, 113,];
check(twoTrailing71.length === 2, 'two trailing length 71');
check(twoTrailing71[0] === 112 && twoTrailing71[1] === 113, 'two trailing values 71');
check(!(2 in twoTrailing71), 'two trailing no property 71');
var elisionAfterComma71 = [112,,];
check(elisionAfterComma71.length === 2, 'elision trailing length 71');
check((0 in elisionAfterComma71) && !(1 in elisionAfterComma71), 'elision trailing properties 71');
var noExtraElement72 = [113,];
check(noExtraElement72.length === 1, 'single trailing length 72');
check((0 in noExtraElement72) && !(1 in noExtraElement72), 'single trailing properties 72');
check(noExtraElement72[0] === 113, 'single trailing value 72');
var twoTrailing72 = [113, 114,];
check(twoTrailing72.length === 2, 'two trailing length 72');
check(twoTrailing72[0] === 113 && twoTrailing72[1] === 114, 'two trailing values 72');
check(!(2 in twoTrailing72), 'two trailing no property 72');
var elisionAfterComma72 = [113,,];
check(elisionAfterComma72.length === 2, 'elision trailing length 72');
check((0 in elisionAfterComma72) && !(1 in elisionAfterComma72), 'elision trailing properties 72');
var noExtraElement73 = [114,];
check(noExtraElement73.length === 1, 'single trailing length 73');
check((0 in noExtraElement73) && !(1 in noExtraElement73), 'single trailing properties 73');
check(noExtraElement73[0] === 114, 'single trailing value 73');
var twoTrailing73 = [114, 115,];
check(twoTrailing73.length === 2, 'two trailing length 73');
check(twoTrailing73[0] === 114 && twoTrailing73[1] === 115, 'two trailing values 73');
check(!(2 in twoTrailing73), 'two trailing no property 73');
var elisionAfterComma73 = [114,,];
check(elisionAfterComma73.length === 2, 'elision trailing length 73');
check((0 in elisionAfterComma73) && !(1 in elisionAfterComma73), 'elision trailing properties 73');
var noExtraElement74 = [115,];
check(noExtraElement74.length === 1, 'single trailing length 74');
check((0 in noExtraElement74) && !(1 in noExtraElement74), 'single trailing properties 74');
check(noExtraElement74[0] === 115, 'single trailing value 74');
var twoTrailing74 = [115, 116,];
check(twoTrailing74.length === 2, 'two trailing length 74');
check(twoTrailing74[0] === 115 && twoTrailing74[1] === 116, 'two trailing values 74');
check(!(2 in twoTrailing74), 'two trailing no property 74');
var elisionAfterComma74 = [115,,];
check(elisionAfterComma74.length === 2, 'elision trailing length 74');
check((0 in elisionAfterComma74) && !(1 in elisionAfterComma74), 'elision trailing properties 74');
var noExtraElement75 = [116,];
check(noExtraElement75.length === 1, 'single trailing length 75');
check((0 in noExtraElement75) && !(1 in noExtraElement75), 'single trailing properties 75');
check(noExtraElement75[0] === 116, 'single trailing value 75');
var twoTrailing75 = [116, 117,];
check(twoTrailing75.length === 2, 'two trailing length 75');
check(twoTrailing75[0] === 116 && twoTrailing75[1] === 117, 'two trailing values 75');
check(!(2 in twoTrailing75), 'two trailing no property 75');
var elisionAfterComma75 = [116,,];
check(elisionAfterComma75.length === 2, 'elision trailing length 75');
check((0 in elisionAfterComma75) && !(1 in elisionAfterComma75), 'elision trailing properties 75');
var noExtraElement76 = [117,];
check(noExtraElement76.length === 1, 'single trailing length 76');
check((0 in noExtraElement76) && !(1 in noExtraElement76), 'single trailing properties 76');
check(noExtraElement76[0] === 117, 'single trailing value 76');
var twoTrailing76 = [117, 118,];
check(twoTrailing76.length === 2, 'two trailing length 76');
check(twoTrailing76[0] === 117 && twoTrailing76[1] === 118, 'two trailing values 76');
check(!(2 in twoTrailing76), 'two trailing no property 76');
var elisionAfterComma76 = [117,,];
check(elisionAfterComma76.length === 2, 'elision trailing length 76');
check((0 in elisionAfterComma76) && !(1 in elisionAfterComma76), 'elision trailing properties 76');
var noExtraElement77 = [118,];
check(noExtraElement77.length === 1, 'single trailing length 77');
check((0 in noExtraElement77) && !(1 in noExtraElement77), 'single trailing properties 77');
check(noExtraElement77[0] === 118, 'single trailing value 77');
var twoTrailing77 = [118, 119,];
check(twoTrailing77.length === 2, 'two trailing length 77');
check(twoTrailing77[0] === 118 && twoTrailing77[1] === 119, 'two trailing values 77');
check(!(2 in twoTrailing77), 'two trailing no property 77');
var elisionAfterComma77 = [118,,];
check(elisionAfterComma77.length === 2, 'elision trailing length 77');
check((0 in elisionAfterComma77) && !(1 in elisionAfterComma77), 'elision trailing properties 77');
var noExtraElement78 = [119,];
check(noExtraElement78.length === 1, 'single trailing length 78');
check((0 in noExtraElement78) && !(1 in noExtraElement78), 'single trailing properties 78');
check(noExtraElement78[0] === 119, 'single trailing value 78');
var twoTrailing78 = [119, 120,];
check(twoTrailing78.length === 2, 'two trailing length 78');
check(twoTrailing78[0] === 119 && twoTrailing78[1] === 120, 'two trailing values 78');
check(!(2 in twoTrailing78), 'two trailing no property 78');
var elisionAfterComma78 = [119,,];
check(elisionAfterComma78.length === 2, 'elision trailing length 78');
check((0 in elisionAfterComma78) && !(1 in elisionAfterComma78), 'elision trailing properties 78');
var noExtraElement79 = [120,];
check(noExtraElement79.length === 1, 'single trailing length 79');
check((0 in noExtraElement79) && !(1 in noExtraElement79), 'single trailing properties 79');
check(noExtraElement79[0] === 120, 'single trailing value 79');
var twoTrailing79 = [120, 121,];
check(twoTrailing79.length === 2, 'two trailing length 79');
check(twoTrailing79[0] === 120 && twoTrailing79[1] === 121, 'two trailing values 79');
check(!(2 in twoTrailing79), 'two trailing no property 79');
var elisionAfterComma79 = [120,,];
check(elisionAfterComma79.length === 2, 'elision trailing length 79');
check((0 in elisionAfterComma79) && !(1 in elisionAfterComma79), 'elision trailing properties 79');
var noExtraElement80 = [121,];
check(noExtraElement80.length === 1, 'single trailing length 80');
check((0 in noExtraElement80) && !(1 in noExtraElement80), 'single trailing properties 80');
check(noExtraElement80[0] === 121, 'single trailing value 80');
var twoTrailing80 = [121, 122,];
check(twoTrailing80.length === 2, 'two trailing length 80');
check(twoTrailing80[0] === 121 && twoTrailing80[1] === 122, 'two trailing values 80');
check(!(2 in twoTrailing80), 'two trailing no property 80');
var elisionAfterComma80 = [121,,];
check(elisionAfterComma80.length === 2, 'elision trailing length 80');
check((0 in elisionAfterComma80) && !(1 in elisionAfterComma80), 'elision trailing properties 80');
var noExtraElement81 = [122,];
check(noExtraElement81.length === 1, 'single trailing length 81');
check((0 in noExtraElement81) && !(1 in noExtraElement81), 'single trailing properties 81');
check(noExtraElement81[0] === 122, 'single trailing value 81');
var twoTrailing81 = [122, 123,];
check(twoTrailing81.length === 2, 'two trailing length 81');
check(twoTrailing81[0] === 122 && twoTrailing81[1] === 123, 'two trailing values 81');
check(!(2 in twoTrailing81), 'two trailing no property 81');
var elisionAfterComma81 = [122,,];
check(elisionAfterComma81.length === 2, 'elision trailing length 81');
check((0 in elisionAfterComma81) && !(1 in elisionAfterComma81), 'elision trailing properties 81');
var noExtraElement82 = [123,];
check(noExtraElement82.length === 1, 'single trailing length 82');
check((0 in noExtraElement82) && !(1 in noExtraElement82), 'single trailing properties 82');
check(noExtraElement82[0] === 123, 'single trailing value 82');
var twoTrailing82 = [123, 124,];
check(twoTrailing82.length === 2, 'two trailing length 82');
check(twoTrailing82[0] === 123 && twoTrailing82[1] === 124, 'two trailing values 82');
check(!(2 in twoTrailing82), 'two trailing no property 82');
var elisionAfterComma82 = [123,,];
check(elisionAfterComma82.length === 2, 'elision trailing length 82');
check((0 in elisionAfterComma82) && !(1 in elisionAfterComma82), 'elision trailing properties 82');
var noExtraElement83 = [124,];
check(noExtraElement83.length === 1, 'single trailing length 83');
check((0 in noExtraElement83) && !(1 in noExtraElement83), 'single trailing properties 83');
check(noExtraElement83[0] === 124, 'single trailing value 83');
var twoTrailing83 = [124, 125,];
check(twoTrailing83.length === 2, 'two trailing length 83');
check(twoTrailing83[0] === 124 && twoTrailing83[1] === 125, 'two trailing values 83');
check(!(2 in twoTrailing83), 'two trailing no property 83');
var elisionAfterComma83 = [124,,];
check(elisionAfterComma83.length === 2, 'elision trailing length 83');
check((0 in elisionAfterComma83) && !(1 in elisionAfterComma83), 'elision trailing properties 83');
var noExtraElement84 = [125,];
check(noExtraElement84.length === 1, 'single trailing length 84');
check((0 in noExtraElement84) && !(1 in noExtraElement84), 'single trailing properties 84');
check(noExtraElement84[0] === 125, 'single trailing value 84');
var twoTrailing84 = [125, 126,];
check(twoTrailing84.length === 2, 'two trailing length 84');
check(twoTrailing84[0] === 125 && twoTrailing84[1] === 126, 'two trailing values 84');
check(!(2 in twoTrailing84), 'two trailing no property 84');
var elisionAfterComma84 = [125,,];
check(elisionAfterComma84.length === 2, 'elision trailing length 84');
check((0 in elisionAfterComma84) && !(1 in elisionAfterComma84), 'elision trailing properties 84');
var noExtraElement85 = [126,];
check(noExtraElement85.length === 1, 'single trailing length 85');
check((0 in noExtraElement85) && !(1 in noExtraElement85), 'single trailing properties 85');
check(noExtraElement85[0] === 126, 'single trailing value 85');
var twoTrailing85 = [126, 127,];
check(twoTrailing85.length === 2, 'two trailing length 85');
check(twoTrailing85[0] === 126 && twoTrailing85[1] === 127, 'two trailing values 85');
check(!(2 in twoTrailing85), 'two trailing no property 85');
var elisionAfterComma85 = [126,,];
check(elisionAfterComma85.length === 2, 'elision trailing length 85');
check((0 in elisionAfterComma85) && !(1 in elisionAfterComma85), 'elision trailing properties 85');
var noExtraElement86 = [127,];
check(noExtraElement86.length === 1, 'single trailing length 86');
check((0 in noExtraElement86) && !(1 in noExtraElement86), 'single trailing properties 86');
check(noExtraElement86[0] === 127, 'single trailing value 86');
var twoTrailing86 = [127, 128,];
check(twoTrailing86.length === 2, 'two trailing length 86');
check(twoTrailing86[0] === 127 && twoTrailing86[1] === 128, 'two trailing values 86');
check(!(2 in twoTrailing86), 'two trailing no property 86');
var elisionAfterComma86 = [127,,];
check(elisionAfterComma86.length === 2, 'elision trailing length 86');
check((0 in elisionAfterComma86) && !(1 in elisionAfterComma86), 'elision trailing properties 86');
var noExtraElement87 = [128,];
check(noExtraElement87.length === 1, 'single trailing length 87');
check((0 in noExtraElement87) && !(1 in noExtraElement87), 'single trailing properties 87');
check(noExtraElement87[0] === 128, 'single trailing value 87');
var twoTrailing87 = [128, 129,];
check(twoTrailing87.length === 2, 'two trailing length 87');
check(twoTrailing87[0] === 128 && twoTrailing87[1] === 129, 'two trailing values 87');
check(!(2 in twoTrailing87), 'two trailing no property 87');
var elisionAfterComma87 = [128,,];
check(elisionAfterComma87.length === 2, 'elision trailing length 87');
check((0 in elisionAfterComma87) && !(1 in elisionAfterComma87), 'elision trailing properties 87');
var noExtraElement88 = [129,];
check(noExtraElement88.length === 1, 'single trailing length 88');
check((0 in noExtraElement88) && !(1 in noExtraElement88), 'single trailing properties 88');
check(noExtraElement88[0] === 129, 'single trailing value 88');
var twoTrailing88 = [129, 130,];
check(twoTrailing88.length === 2, 'two trailing length 88');
check(twoTrailing88[0] === 129 && twoTrailing88[1] === 130, 'two trailing values 88');
check(!(2 in twoTrailing88), 'two trailing no property 88');
var elisionAfterComma88 = [129,,];
check(elisionAfterComma88.length === 2, 'elision trailing length 88');
check((0 in elisionAfterComma88) && !(1 in elisionAfterComma88), 'elision trailing properties 88');
var noExtraElement89 = [130,];
check(noExtraElement89.length === 1, 'single trailing length 89');
check((0 in noExtraElement89) && !(1 in noExtraElement89), 'single trailing properties 89');
check(noExtraElement89[0] === 130, 'single trailing value 89');
var twoTrailing89 = [130, 131,];
check(twoTrailing89.length === 2, 'two trailing length 89');
check(twoTrailing89[0] === 130 && twoTrailing89[1] === 131, 'two trailing values 89');
check(!(2 in twoTrailing89), 'two trailing no property 89');
var elisionAfterComma89 = [130,,];
check(elisionAfterComma89.length === 2, 'elision trailing length 89');
check((0 in elisionAfterComma89) && !(1 in elisionAfterComma89), 'elision trailing properties 89');
var noExtraElement90 = [131,];
check(noExtraElement90.length === 1, 'single trailing length 90');
check((0 in noExtraElement90) && !(1 in noExtraElement90), 'single trailing properties 90');
check(noExtraElement90[0] === 131, 'single trailing value 90');
var twoTrailing90 = [131, 132,];
check(twoTrailing90.length === 2, 'two trailing length 90');
check(twoTrailing90[0] === 131 && twoTrailing90[1] === 132, 'two trailing values 90');
check(!(2 in twoTrailing90), 'two trailing no property 90');
var elisionAfterComma90 = [131,,];
check(elisionAfterComma90.length === 2, 'elision trailing length 90');
check((0 in elisionAfterComma90) && !(1 in elisionAfterComma90), 'elision trailing properties 90');
console.log('trailing-comma-does-not-add-element stress ' + score);
