// behavior: primary-identifier-reference-delegates-to-identifierreference
// expected: pass
// goal: script
// size: large
// variant: script.sloppy

var primaryGlobal = 10;
var primaryShadow = 200;
var primaryScore = 0;
function checkPrimary(condition, label) {
if (!condition) {
throw label;
}
primaryScore = primaryScore + 1;
return true;
}
function readPrimaryArgument(value) {
return value + primaryGlobal;
}
function makePrimaryClosure(seed) {
var primaryGlobal = seed;
return function(extra) { return primaryGlobal + extra; };
}
function shadowPrimaryBinding(input) {
var primaryGlobal = input;
primaryGlobal = primaryGlobal + 3;
checkPrimary(primaryGlobal === input + 3, "shadow local write");
return primaryGlobal;
}
checkPrimary(primaryGlobal === 10, "initial primary read");
primaryGlobal = primaryGlobal + 5;
checkPrimary(primaryGlobal === 15, "primary assignment writes binding");
var postValue = primaryGlobal++;
checkPrimary(postValue === 15, "post increment result");
checkPrimary(primaryGlobal === 16, "post increment write");
var preValue = ++primaryGlobal;
checkPrimary(preValue === 17, "pre increment result");
checkPrimary(primaryGlobal === 17, "pre increment write");
var closureCheck = makePrimaryClosure(30);
checkPrimary(closureCheck(4) === 34, "closure captures nearest primary");
checkPrimary(shadowPrimaryBinding(40) === 43, "shadow function returns local");
checkPrimary(primaryGlobal === 17, "shadow does not overwrite outer");
checkPrimary(readPrimaryArgument(8) === 25, "identifier in call argument value");
var localPrimary0 = primaryGlobal + 0;
checkPrimary(localPrimary0 === primaryGlobal + 0, "local read 0");
localPrimary0 = localPrimary0 + primaryShadow;
checkPrimary(localPrimary0 === primaryGlobal + 0 + primaryShadow, "local write 0");
var primaryArray0 = [primaryGlobal, localPrimary0, primaryShadow];
checkPrimary(primaryArray0[0] === primaryGlobal, "array primary 0");
var primaryObject0 = { value: localPrimary0, alias: primaryGlobal };
checkPrimary(primaryObject0.alias + primaryObject0.value === primaryGlobal + localPrimary0, "object primary 0");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 0");
function nestedPrimary0(input) {
var primaryGlobal = input + 0;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary0(1) === 1 + 0 + primaryShadow, "nested nearest 0");
var closurePrimary0 = makePrimaryClosure(50);
checkPrimary(closurePrimary0(0) === 50 + 0, "closure primary 0");
var localPrimary1 = primaryGlobal + 1;
checkPrimary(localPrimary1 === primaryGlobal + 1, "local read 1");
localPrimary1 = localPrimary1 + primaryShadow;
checkPrimary(localPrimary1 === primaryGlobal + 1 + primaryShadow, "local write 1");
var primaryArray1 = [primaryGlobal, localPrimary1, primaryShadow];
checkPrimary(primaryArray1[0] === primaryGlobal, "array primary 1");
var primaryObject1 = { value: localPrimary1, alias: primaryGlobal };
checkPrimary(primaryObject1.alias + primaryObject1.value === primaryGlobal + localPrimary1, "object primary 1");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 1");
var localPrimary2 = primaryGlobal + 2;
checkPrimary(localPrimary2 === primaryGlobal + 2, "local read 2");
localPrimary2 = localPrimary2 + primaryShadow;
checkPrimary(localPrimary2 === primaryGlobal + 2 + primaryShadow, "local write 2");
var primaryArray2 = [primaryGlobal, localPrimary2, primaryShadow];
checkPrimary(primaryArray2[0] === primaryGlobal, "array primary 2");
var primaryObject2 = { value: localPrimary2, alias: primaryGlobal };
checkPrimary(primaryObject2.alias + primaryObject2.value === primaryGlobal + localPrimary2, "object primary 2");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 2");
var localPrimary3 = primaryGlobal + 3;
checkPrimary(localPrimary3 === primaryGlobal + 3, "local read 3");
localPrimary3 = localPrimary3 + primaryShadow;
checkPrimary(localPrimary3 === primaryGlobal + 3 + primaryShadow, "local write 3");
var primaryArray3 = [primaryGlobal, localPrimary3, primaryShadow];
checkPrimary(primaryArray3[0] === primaryGlobal, "array primary 3");
var primaryObject3 = { value: localPrimary3, alias: primaryGlobal };
checkPrimary(primaryObject3.alias + primaryObject3.value === primaryGlobal + localPrimary3, "object primary 3");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 3");
var localPrimary4 = primaryGlobal + 4;
checkPrimary(localPrimary4 === primaryGlobal + 4, "local read 4");
localPrimary4 = localPrimary4 + primaryShadow;
checkPrimary(localPrimary4 === primaryGlobal + 4 + primaryShadow, "local write 4");
var primaryArray4 = [primaryGlobal, localPrimary4, primaryShadow];
checkPrimary(primaryArray4[0] === primaryGlobal, "array primary 4");
var primaryObject4 = { value: localPrimary4, alias: primaryGlobal };
checkPrimary(primaryObject4.alias + primaryObject4.value === primaryGlobal + localPrimary4, "object primary 4");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 4");
function nestedPrimary4(input) {
var primaryGlobal = input + 4;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary4(5) === 5 + 4 + primaryShadow, "nested nearest 4");
var localPrimary5 = primaryGlobal + 5;
checkPrimary(localPrimary5 === primaryGlobal + 5, "local read 5");
localPrimary5 = localPrimary5 + primaryShadow;
checkPrimary(localPrimary5 === primaryGlobal + 5 + primaryShadow, "local write 5");
var primaryArray5 = [primaryGlobal, localPrimary5, primaryShadow];
checkPrimary(primaryArray5[0] === primaryGlobal, "array primary 5");
var primaryObject5 = { value: localPrimary5, alias: primaryGlobal };
checkPrimary(primaryObject5.alias + primaryObject5.value === primaryGlobal + localPrimary5, "object primary 5");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 5");
var closurePrimary5 = makePrimaryClosure(55);
checkPrimary(closurePrimary5(5) === 55 + 5, "closure primary 5");
var localPrimary6 = primaryGlobal + 6;
checkPrimary(localPrimary6 === primaryGlobal + 6, "local read 6");
localPrimary6 = localPrimary6 + primaryShadow;
checkPrimary(localPrimary6 === primaryGlobal + 6 + primaryShadow, "local write 6");
var primaryArray6 = [primaryGlobal, localPrimary6, primaryShadow];
checkPrimary(primaryArray6[0] === primaryGlobal, "array primary 6");
var primaryObject6 = { value: localPrimary6, alias: primaryGlobal };
checkPrimary(primaryObject6.alias + primaryObject6.value === primaryGlobal + localPrimary6, "object primary 6");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 6");
var localPrimary7 = primaryGlobal + 7;
checkPrimary(localPrimary7 === primaryGlobal + 7, "local read 7");
localPrimary7 = localPrimary7 + primaryShadow;
checkPrimary(localPrimary7 === primaryGlobal + 7 + primaryShadow, "local write 7");
var primaryArray7 = [primaryGlobal, localPrimary7, primaryShadow];
checkPrimary(primaryArray7[0] === primaryGlobal, "array primary 7");
var primaryObject7 = { value: localPrimary7, alias: primaryGlobal };
checkPrimary(primaryObject7.alias + primaryObject7.value === primaryGlobal + localPrimary7, "object primary 7");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 7");
var localPrimary8 = primaryGlobal + 8;
checkPrimary(localPrimary8 === primaryGlobal + 8, "local read 8");
localPrimary8 = localPrimary8 + primaryShadow;
checkPrimary(localPrimary8 === primaryGlobal + 8 + primaryShadow, "local write 8");
var primaryArray8 = [primaryGlobal, localPrimary8, primaryShadow];
checkPrimary(primaryArray8[0] === primaryGlobal, "array primary 8");
var primaryObject8 = { value: localPrimary8, alias: primaryGlobal };
checkPrimary(primaryObject8.alias + primaryObject8.value === primaryGlobal + localPrimary8, "object primary 8");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 8");
function nestedPrimary8(input) {
var primaryGlobal = input + 8;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary8(9) === 9 + 8 + primaryShadow, "nested nearest 8");
var localPrimary9 = primaryGlobal + 9;
checkPrimary(localPrimary9 === primaryGlobal + 9, "local read 9");
localPrimary9 = localPrimary9 + primaryShadow;
checkPrimary(localPrimary9 === primaryGlobal + 9 + primaryShadow, "local write 9");
var primaryArray9 = [primaryGlobal, localPrimary9, primaryShadow];
checkPrimary(primaryArray9[0] === primaryGlobal, "array primary 9");
var primaryObject9 = { value: localPrimary9, alias: primaryGlobal };
checkPrimary(primaryObject9.alias + primaryObject9.value === primaryGlobal + localPrimary9, "object primary 9");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 9");
var localPrimary10 = primaryGlobal + 10;
checkPrimary(localPrimary10 === primaryGlobal + 10, "local read 10");
localPrimary10 = localPrimary10 + primaryShadow;
checkPrimary(localPrimary10 === primaryGlobal + 10 + primaryShadow, "local write 10");
var primaryArray10 = [primaryGlobal, localPrimary10, primaryShadow];
checkPrimary(primaryArray10[0] === primaryGlobal, "array primary 10");
var primaryObject10 = { value: localPrimary10, alias: primaryGlobal };
checkPrimary(primaryObject10.alias + primaryObject10.value === primaryGlobal + localPrimary10, "object primary 10");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 10");
var closurePrimary10 = makePrimaryClosure(60);
checkPrimary(closurePrimary10(10) === 60 + 10, "closure primary 10");
var localPrimary11 = primaryGlobal + 11;
checkPrimary(localPrimary11 === primaryGlobal + 11, "local read 11");
localPrimary11 = localPrimary11 + primaryShadow;
checkPrimary(localPrimary11 === primaryGlobal + 11 + primaryShadow, "local write 11");
var primaryArray11 = [primaryGlobal, localPrimary11, primaryShadow];
checkPrimary(primaryArray11[0] === primaryGlobal, "array primary 11");
var primaryObject11 = { value: localPrimary11, alias: primaryGlobal };
checkPrimary(primaryObject11.alias + primaryObject11.value === primaryGlobal + localPrimary11, "object primary 11");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 11");
var localPrimary12 = primaryGlobal + 12;
checkPrimary(localPrimary12 === primaryGlobal + 12, "local read 12");
localPrimary12 = localPrimary12 + primaryShadow;
checkPrimary(localPrimary12 === primaryGlobal + 12 + primaryShadow, "local write 12");
var primaryArray12 = [primaryGlobal, localPrimary12, primaryShadow];
checkPrimary(primaryArray12[0] === primaryGlobal, "array primary 12");
var primaryObject12 = { value: localPrimary12, alias: primaryGlobal };
checkPrimary(primaryObject12.alias + primaryObject12.value === primaryGlobal + localPrimary12, "object primary 12");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 12");
function nestedPrimary12(input) {
var primaryGlobal = input + 12;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary12(13) === 13 + 12 + primaryShadow, "nested nearest 12");
var localPrimary13 = primaryGlobal + 13;
checkPrimary(localPrimary13 === primaryGlobal + 13, "local read 13");
localPrimary13 = localPrimary13 + primaryShadow;
checkPrimary(localPrimary13 === primaryGlobal + 13 + primaryShadow, "local write 13");
var primaryArray13 = [primaryGlobal, localPrimary13, primaryShadow];
checkPrimary(primaryArray13[0] === primaryGlobal, "array primary 13");
var primaryObject13 = { value: localPrimary13, alias: primaryGlobal };
checkPrimary(primaryObject13.alias + primaryObject13.value === primaryGlobal + localPrimary13, "object primary 13");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 13");
var localPrimary14 = primaryGlobal + 14;
checkPrimary(localPrimary14 === primaryGlobal + 14, "local read 14");
localPrimary14 = localPrimary14 + primaryShadow;
checkPrimary(localPrimary14 === primaryGlobal + 14 + primaryShadow, "local write 14");
var primaryArray14 = [primaryGlobal, localPrimary14, primaryShadow];
checkPrimary(primaryArray14[0] === primaryGlobal, "array primary 14");
var primaryObject14 = { value: localPrimary14, alias: primaryGlobal };
checkPrimary(primaryObject14.alias + primaryObject14.value === primaryGlobal + localPrimary14, "object primary 14");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 14");
var localPrimary15 = primaryGlobal + 15;
checkPrimary(localPrimary15 === primaryGlobal + 15, "local read 15");
localPrimary15 = localPrimary15 + primaryShadow;
checkPrimary(localPrimary15 === primaryGlobal + 15 + primaryShadow, "local write 15");
var primaryArray15 = [primaryGlobal, localPrimary15, primaryShadow];
checkPrimary(primaryArray15[0] === primaryGlobal, "array primary 15");
var primaryObject15 = { value: localPrimary15, alias: primaryGlobal };
checkPrimary(primaryObject15.alias + primaryObject15.value === primaryGlobal + localPrimary15, "object primary 15");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 15");
var closurePrimary15 = makePrimaryClosure(65);
checkPrimary(closurePrimary15(15) === 65 + 15, "closure primary 15");
var localPrimary16 = primaryGlobal + 16;
checkPrimary(localPrimary16 === primaryGlobal + 16, "local read 16");
localPrimary16 = localPrimary16 + primaryShadow;
checkPrimary(localPrimary16 === primaryGlobal + 16 + primaryShadow, "local write 16");
var primaryArray16 = [primaryGlobal, localPrimary16, primaryShadow];
checkPrimary(primaryArray16[0] === primaryGlobal, "array primary 16");
var primaryObject16 = { value: localPrimary16, alias: primaryGlobal };
checkPrimary(primaryObject16.alias + primaryObject16.value === primaryGlobal + localPrimary16, "object primary 16");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 16");
function nestedPrimary16(input) {
var primaryGlobal = input + 16;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary16(17) === 17 + 16 + primaryShadow, "nested nearest 16");
var localPrimary17 = primaryGlobal + 17;
checkPrimary(localPrimary17 === primaryGlobal + 17, "local read 17");
localPrimary17 = localPrimary17 + primaryShadow;
checkPrimary(localPrimary17 === primaryGlobal + 17 + primaryShadow, "local write 17");
var primaryArray17 = [primaryGlobal, localPrimary17, primaryShadow];
checkPrimary(primaryArray17[0] === primaryGlobal, "array primary 17");
var primaryObject17 = { value: localPrimary17, alias: primaryGlobal };
checkPrimary(primaryObject17.alias + primaryObject17.value === primaryGlobal + localPrimary17, "object primary 17");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 17");
var localPrimary18 = primaryGlobal + 18;
checkPrimary(localPrimary18 === primaryGlobal + 18, "local read 18");
localPrimary18 = localPrimary18 + primaryShadow;
checkPrimary(localPrimary18 === primaryGlobal + 18 + primaryShadow, "local write 18");
var primaryArray18 = [primaryGlobal, localPrimary18, primaryShadow];
checkPrimary(primaryArray18[0] === primaryGlobal, "array primary 18");
var primaryObject18 = { value: localPrimary18, alias: primaryGlobal };
checkPrimary(primaryObject18.alias + primaryObject18.value === primaryGlobal + localPrimary18, "object primary 18");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 18");
var localPrimary19 = primaryGlobal + 19;
checkPrimary(localPrimary19 === primaryGlobal + 19, "local read 19");
localPrimary19 = localPrimary19 + primaryShadow;
checkPrimary(localPrimary19 === primaryGlobal + 19 + primaryShadow, "local write 19");
var primaryArray19 = [primaryGlobal, localPrimary19, primaryShadow];
checkPrimary(primaryArray19[0] === primaryGlobal, "array primary 19");
var primaryObject19 = { value: localPrimary19, alias: primaryGlobal };
checkPrimary(primaryObject19.alias + primaryObject19.value === primaryGlobal + localPrimary19, "object primary 19");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 19");
var localPrimary20 = primaryGlobal + 20;
checkPrimary(localPrimary20 === primaryGlobal + 20, "local read 20");
localPrimary20 = localPrimary20 + primaryShadow;
checkPrimary(localPrimary20 === primaryGlobal + 20 + primaryShadow, "local write 20");
var primaryArray20 = [primaryGlobal, localPrimary20, primaryShadow];
checkPrimary(primaryArray20[0] === primaryGlobal, "array primary 20");
var primaryObject20 = { value: localPrimary20, alias: primaryGlobal };
checkPrimary(primaryObject20.alias + primaryObject20.value === primaryGlobal + localPrimary20, "object primary 20");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 20");
function nestedPrimary20(input) {
var primaryGlobal = input + 20;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary20(21) === 21 + 20 + primaryShadow, "nested nearest 20");
var closurePrimary20 = makePrimaryClosure(70);
checkPrimary(closurePrimary20(20) === 70 + 20, "closure primary 20");
var localPrimary21 = primaryGlobal + 21;
checkPrimary(localPrimary21 === primaryGlobal + 21, "local read 21");
localPrimary21 = localPrimary21 + primaryShadow;
checkPrimary(localPrimary21 === primaryGlobal + 21 + primaryShadow, "local write 21");
var primaryArray21 = [primaryGlobal, localPrimary21, primaryShadow];
checkPrimary(primaryArray21[0] === primaryGlobal, "array primary 21");
var primaryObject21 = { value: localPrimary21, alias: primaryGlobal };
checkPrimary(primaryObject21.alias + primaryObject21.value === primaryGlobal + localPrimary21, "object primary 21");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 21");
var localPrimary22 = primaryGlobal + 22;
checkPrimary(localPrimary22 === primaryGlobal + 22, "local read 22");
localPrimary22 = localPrimary22 + primaryShadow;
checkPrimary(localPrimary22 === primaryGlobal + 22 + primaryShadow, "local write 22");
var primaryArray22 = [primaryGlobal, localPrimary22, primaryShadow];
checkPrimary(primaryArray22[0] === primaryGlobal, "array primary 22");
var primaryObject22 = { value: localPrimary22, alias: primaryGlobal };
checkPrimary(primaryObject22.alias + primaryObject22.value === primaryGlobal + localPrimary22, "object primary 22");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 22");
var localPrimary23 = primaryGlobal + 23;
checkPrimary(localPrimary23 === primaryGlobal + 23, "local read 23");
localPrimary23 = localPrimary23 + primaryShadow;
checkPrimary(localPrimary23 === primaryGlobal + 23 + primaryShadow, "local write 23");
var primaryArray23 = [primaryGlobal, localPrimary23, primaryShadow];
checkPrimary(primaryArray23[0] === primaryGlobal, "array primary 23");
var primaryObject23 = { value: localPrimary23, alias: primaryGlobal };
checkPrimary(primaryObject23.alias + primaryObject23.value === primaryGlobal + localPrimary23, "object primary 23");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 23");
var localPrimary24 = primaryGlobal + 24;
checkPrimary(localPrimary24 === primaryGlobal + 24, "local read 24");
localPrimary24 = localPrimary24 + primaryShadow;
checkPrimary(localPrimary24 === primaryGlobal + 24 + primaryShadow, "local write 24");
var primaryArray24 = [primaryGlobal, localPrimary24, primaryShadow];
checkPrimary(primaryArray24[0] === primaryGlobal, "array primary 24");
var primaryObject24 = { value: localPrimary24, alias: primaryGlobal };
checkPrimary(primaryObject24.alias + primaryObject24.value === primaryGlobal + localPrimary24, "object primary 24");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 24");
function nestedPrimary24(input) {
var primaryGlobal = input + 24;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary24(25) === 25 + 24 + primaryShadow, "nested nearest 24");
var localPrimary25 = primaryGlobal + 25;
checkPrimary(localPrimary25 === primaryGlobal + 25, "local read 25");
localPrimary25 = localPrimary25 + primaryShadow;
checkPrimary(localPrimary25 === primaryGlobal + 25 + primaryShadow, "local write 25");
var primaryArray25 = [primaryGlobal, localPrimary25, primaryShadow];
checkPrimary(primaryArray25[0] === primaryGlobal, "array primary 25");
var primaryObject25 = { value: localPrimary25, alias: primaryGlobal };
checkPrimary(primaryObject25.alias + primaryObject25.value === primaryGlobal + localPrimary25, "object primary 25");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 25");
var closurePrimary25 = makePrimaryClosure(75);
checkPrimary(closurePrimary25(25) === 75 + 25, "closure primary 25");
var localPrimary26 = primaryGlobal + 26;
checkPrimary(localPrimary26 === primaryGlobal + 26, "local read 26");
localPrimary26 = localPrimary26 + primaryShadow;
checkPrimary(localPrimary26 === primaryGlobal + 26 + primaryShadow, "local write 26");
var primaryArray26 = [primaryGlobal, localPrimary26, primaryShadow];
checkPrimary(primaryArray26[0] === primaryGlobal, "array primary 26");
var primaryObject26 = { value: localPrimary26, alias: primaryGlobal };
checkPrimary(primaryObject26.alias + primaryObject26.value === primaryGlobal + localPrimary26, "object primary 26");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 26");
var localPrimary27 = primaryGlobal + 27;
checkPrimary(localPrimary27 === primaryGlobal + 27, "local read 27");
localPrimary27 = localPrimary27 + primaryShadow;
checkPrimary(localPrimary27 === primaryGlobal + 27 + primaryShadow, "local write 27");
var primaryArray27 = [primaryGlobal, localPrimary27, primaryShadow];
checkPrimary(primaryArray27[0] === primaryGlobal, "array primary 27");
var primaryObject27 = { value: localPrimary27, alias: primaryGlobal };
checkPrimary(primaryObject27.alias + primaryObject27.value === primaryGlobal + localPrimary27, "object primary 27");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 27");
var localPrimary28 = primaryGlobal + 28;
checkPrimary(localPrimary28 === primaryGlobal + 28, "local read 28");
localPrimary28 = localPrimary28 + primaryShadow;
checkPrimary(localPrimary28 === primaryGlobal + 28 + primaryShadow, "local write 28");
var primaryArray28 = [primaryGlobal, localPrimary28, primaryShadow];
checkPrimary(primaryArray28[0] === primaryGlobal, "array primary 28");
var primaryObject28 = { value: localPrimary28, alias: primaryGlobal };
checkPrimary(primaryObject28.alias + primaryObject28.value === primaryGlobal + localPrimary28, "object primary 28");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 28");
function nestedPrimary28(input) {
var primaryGlobal = input + 28;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary28(29) === 29 + 28 + primaryShadow, "nested nearest 28");
var localPrimary29 = primaryGlobal + 29;
checkPrimary(localPrimary29 === primaryGlobal + 29, "local read 29");
localPrimary29 = localPrimary29 + primaryShadow;
checkPrimary(localPrimary29 === primaryGlobal + 29 + primaryShadow, "local write 29");
var primaryArray29 = [primaryGlobal, localPrimary29, primaryShadow];
checkPrimary(primaryArray29[0] === primaryGlobal, "array primary 29");
var primaryObject29 = { value: localPrimary29, alias: primaryGlobal };
checkPrimary(primaryObject29.alias + primaryObject29.value === primaryGlobal + localPrimary29, "object primary 29");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 29");
var localPrimary30 = primaryGlobal + 30;
checkPrimary(localPrimary30 === primaryGlobal + 30, "local read 30");
localPrimary30 = localPrimary30 + primaryShadow;
checkPrimary(localPrimary30 === primaryGlobal + 30 + primaryShadow, "local write 30");
var primaryArray30 = [primaryGlobal, localPrimary30, primaryShadow];
checkPrimary(primaryArray30[0] === primaryGlobal, "array primary 30");
var primaryObject30 = { value: localPrimary30, alias: primaryGlobal };
checkPrimary(primaryObject30.alias + primaryObject30.value === primaryGlobal + localPrimary30, "object primary 30");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 30");
var closurePrimary30 = makePrimaryClosure(80);
checkPrimary(closurePrimary30(30) === 80 + 30, "closure primary 30");
var localPrimary31 = primaryGlobal + 31;
checkPrimary(localPrimary31 === primaryGlobal + 31, "local read 31");
localPrimary31 = localPrimary31 + primaryShadow;
checkPrimary(localPrimary31 === primaryGlobal + 31 + primaryShadow, "local write 31");
var primaryArray31 = [primaryGlobal, localPrimary31, primaryShadow];
checkPrimary(primaryArray31[0] === primaryGlobal, "array primary 31");
var primaryObject31 = { value: localPrimary31, alias: primaryGlobal };
checkPrimary(primaryObject31.alias + primaryObject31.value === primaryGlobal + localPrimary31, "object primary 31");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 31");
var localPrimary32 = primaryGlobal + 32;
checkPrimary(localPrimary32 === primaryGlobal + 32, "local read 32");
localPrimary32 = localPrimary32 + primaryShadow;
checkPrimary(localPrimary32 === primaryGlobal + 32 + primaryShadow, "local write 32");
var primaryArray32 = [primaryGlobal, localPrimary32, primaryShadow];
checkPrimary(primaryArray32[0] === primaryGlobal, "array primary 32");
var primaryObject32 = { value: localPrimary32, alias: primaryGlobal };
checkPrimary(primaryObject32.alias + primaryObject32.value === primaryGlobal + localPrimary32, "object primary 32");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 32");
function nestedPrimary32(input) {
var primaryGlobal = input + 32;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary32(33) === 33 + 32 + primaryShadow, "nested nearest 32");
var localPrimary33 = primaryGlobal + 33;
checkPrimary(localPrimary33 === primaryGlobal + 33, "local read 33");
localPrimary33 = localPrimary33 + primaryShadow;
checkPrimary(localPrimary33 === primaryGlobal + 33 + primaryShadow, "local write 33");
var primaryArray33 = [primaryGlobal, localPrimary33, primaryShadow];
checkPrimary(primaryArray33[0] === primaryGlobal, "array primary 33");
var primaryObject33 = { value: localPrimary33, alias: primaryGlobal };
checkPrimary(primaryObject33.alias + primaryObject33.value === primaryGlobal + localPrimary33, "object primary 33");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 33");
var localPrimary34 = primaryGlobal + 34;
checkPrimary(localPrimary34 === primaryGlobal + 34, "local read 34");
localPrimary34 = localPrimary34 + primaryShadow;
checkPrimary(localPrimary34 === primaryGlobal + 34 + primaryShadow, "local write 34");
var primaryArray34 = [primaryGlobal, localPrimary34, primaryShadow];
checkPrimary(primaryArray34[0] === primaryGlobal, "array primary 34");
var primaryObject34 = { value: localPrimary34, alias: primaryGlobal };
checkPrimary(primaryObject34.alias + primaryObject34.value === primaryGlobal + localPrimary34, "object primary 34");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 34");
var localPrimary35 = primaryGlobal + 35;
checkPrimary(localPrimary35 === primaryGlobal + 35, "local read 35");
localPrimary35 = localPrimary35 + primaryShadow;
checkPrimary(localPrimary35 === primaryGlobal + 35 + primaryShadow, "local write 35");
var primaryArray35 = [primaryGlobal, localPrimary35, primaryShadow];
checkPrimary(primaryArray35[0] === primaryGlobal, "array primary 35");
var primaryObject35 = { value: localPrimary35, alias: primaryGlobal };
checkPrimary(primaryObject35.alias + primaryObject35.value === primaryGlobal + localPrimary35, "object primary 35");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 35");
var closurePrimary35 = makePrimaryClosure(85);
checkPrimary(closurePrimary35(35) === 85 + 35, "closure primary 35");
var localPrimary36 = primaryGlobal + 36;
checkPrimary(localPrimary36 === primaryGlobal + 36, "local read 36");
localPrimary36 = localPrimary36 + primaryShadow;
checkPrimary(localPrimary36 === primaryGlobal + 36 + primaryShadow, "local write 36");
var primaryArray36 = [primaryGlobal, localPrimary36, primaryShadow];
checkPrimary(primaryArray36[0] === primaryGlobal, "array primary 36");
var primaryObject36 = { value: localPrimary36, alias: primaryGlobal };
checkPrimary(primaryObject36.alias + primaryObject36.value === primaryGlobal + localPrimary36, "object primary 36");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 36");
function nestedPrimary36(input) {
var primaryGlobal = input + 36;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary36(37) === 37 + 36 + primaryShadow, "nested nearest 36");
var localPrimary37 = primaryGlobal + 37;
checkPrimary(localPrimary37 === primaryGlobal + 37, "local read 37");
localPrimary37 = localPrimary37 + primaryShadow;
checkPrimary(localPrimary37 === primaryGlobal + 37 + primaryShadow, "local write 37");
var primaryArray37 = [primaryGlobal, localPrimary37, primaryShadow];
checkPrimary(primaryArray37[0] === primaryGlobal, "array primary 37");
var primaryObject37 = { value: localPrimary37, alias: primaryGlobal };
checkPrimary(primaryObject37.alias + primaryObject37.value === primaryGlobal + localPrimary37, "object primary 37");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 37");
var localPrimary38 = primaryGlobal + 38;
checkPrimary(localPrimary38 === primaryGlobal + 38, "local read 38");
localPrimary38 = localPrimary38 + primaryShadow;
checkPrimary(localPrimary38 === primaryGlobal + 38 + primaryShadow, "local write 38");
var primaryArray38 = [primaryGlobal, localPrimary38, primaryShadow];
checkPrimary(primaryArray38[0] === primaryGlobal, "array primary 38");
var primaryObject38 = { value: localPrimary38, alias: primaryGlobal };
checkPrimary(primaryObject38.alias + primaryObject38.value === primaryGlobal + localPrimary38, "object primary 38");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 38");
var localPrimary39 = primaryGlobal + 39;
checkPrimary(localPrimary39 === primaryGlobal + 39, "local read 39");
localPrimary39 = localPrimary39 + primaryShadow;
checkPrimary(localPrimary39 === primaryGlobal + 39 + primaryShadow, "local write 39");
var primaryArray39 = [primaryGlobal, localPrimary39, primaryShadow];
checkPrimary(primaryArray39[0] === primaryGlobal, "array primary 39");
var primaryObject39 = { value: localPrimary39, alias: primaryGlobal };
checkPrimary(primaryObject39.alias + primaryObject39.value === primaryGlobal + localPrimary39, "object primary 39");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 39");
var localPrimary40 = primaryGlobal + 40;
checkPrimary(localPrimary40 === primaryGlobal + 40, "local read 40");
localPrimary40 = localPrimary40 + primaryShadow;
checkPrimary(localPrimary40 === primaryGlobal + 40 + primaryShadow, "local write 40");
var primaryArray40 = [primaryGlobal, localPrimary40, primaryShadow];
checkPrimary(primaryArray40[0] === primaryGlobal, "array primary 40");
var primaryObject40 = { value: localPrimary40, alias: primaryGlobal };
checkPrimary(primaryObject40.alias + primaryObject40.value === primaryGlobal + localPrimary40, "object primary 40");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 40");
function nestedPrimary40(input) {
var primaryGlobal = input + 40;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary40(41) === 41 + 40 + primaryShadow, "nested nearest 40");
var closurePrimary40 = makePrimaryClosure(90);
checkPrimary(closurePrimary40(40) === 90 + 40, "closure primary 40");
var localPrimary41 = primaryGlobal + 41;
checkPrimary(localPrimary41 === primaryGlobal + 41, "local read 41");
localPrimary41 = localPrimary41 + primaryShadow;
checkPrimary(localPrimary41 === primaryGlobal + 41 + primaryShadow, "local write 41");
var primaryArray41 = [primaryGlobal, localPrimary41, primaryShadow];
checkPrimary(primaryArray41[0] === primaryGlobal, "array primary 41");
var primaryObject41 = { value: localPrimary41, alias: primaryGlobal };
checkPrimary(primaryObject41.alias + primaryObject41.value === primaryGlobal + localPrimary41, "object primary 41");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 41");
var localPrimary42 = primaryGlobal + 42;
checkPrimary(localPrimary42 === primaryGlobal + 42, "local read 42");
localPrimary42 = localPrimary42 + primaryShadow;
checkPrimary(localPrimary42 === primaryGlobal + 42 + primaryShadow, "local write 42");
var primaryArray42 = [primaryGlobal, localPrimary42, primaryShadow];
checkPrimary(primaryArray42[0] === primaryGlobal, "array primary 42");
var primaryObject42 = { value: localPrimary42, alias: primaryGlobal };
checkPrimary(primaryObject42.alias + primaryObject42.value === primaryGlobal + localPrimary42, "object primary 42");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 42");
var localPrimary43 = primaryGlobal + 43;
checkPrimary(localPrimary43 === primaryGlobal + 43, "local read 43");
localPrimary43 = localPrimary43 + primaryShadow;
checkPrimary(localPrimary43 === primaryGlobal + 43 + primaryShadow, "local write 43");
var primaryArray43 = [primaryGlobal, localPrimary43, primaryShadow];
checkPrimary(primaryArray43[0] === primaryGlobal, "array primary 43");
var primaryObject43 = { value: localPrimary43, alias: primaryGlobal };
checkPrimary(primaryObject43.alias + primaryObject43.value === primaryGlobal + localPrimary43, "object primary 43");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 43");
var localPrimary44 = primaryGlobal + 44;
checkPrimary(localPrimary44 === primaryGlobal + 44, "local read 44");
localPrimary44 = localPrimary44 + primaryShadow;
checkPrimary(localPrimary44 === primaryGlobal + 44 + primaryShadow, "local write 44");
var primaryArray44 = [primaryGlobal, localPrimary44, primaryShadow];
checkPrimary(primaryArray44[0] === primaryGlobal, "array primary 44");
var primaryObject44 = { value: localPrimary44, alias: primaryGlobal };
checkPrimary(primaryObject44.alias + primaryObject44.value === primaryGlobal + localPrimary44, "object primary 44");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 44");
function nestedPrimary44(input) {
var primaryGlobal = input + 44;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary44(45) === 45 + 44 + primaryShadow, "nested nearest 44");
var localPrimary45 = primaryGlobal + 45;
checkPrimary(localPrimary45 === primaryGlobal + 45, "local read 45");
localPrimary45 = localPrimary45 + primaryShadow;
checkPrimary(localPrimary45 === primaryGlobal + 45 + primaryShadow, "local write 45");
var primaryArray45 = [primaryGlobal, localPrimary45, primaryShadow];
checkPrimary(primaryArray45[0] === primaryGlobal, "array primary 45");
var primaryObject45 = { value: localPrimary45, alias: primaryGlobal };
checkPrimary(primaryObject45.alias + primaryObject45.value === primaryGlobal + localPrimary45, "object primary 45");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 45");
var closurePrimary45 = makePrimaryClosure(95);
checkPrimary(closurePrimary45(45) === 95 + 45, "closure primary 45");
var localPrimary46 = primaryGlobal + 46;
checkPrimary(localPrimary46 === primaryGlobal + 46, "local read 46");
localPrimary46 = localPrimary46 + primaryShadow;
checkPrimary(localPrimary46 === primaryGlobal + 46 + primaryShadow, "local write 46");
var primaryArray46 = [primaryGlobal, localPrimary46, primaryShadow];
checkPrimary(primaryArray46[0] === primaryGlobal, "array primary 46");
var primaryObject46 = { value: localPrimary46, alias: primaryGlobal };
checkPrimary(primaryObject46.alias + primaryObject46.value === primaryGlobal + localPrimary46, "object primary 46");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 46");
var localPrimary47 = primaryGlobal + 47;
checkPrimary(localPrimary47 === primaryGlobal + 47, "local read 47");
localPrimary47 = localPrimary47 + primaryShadow;
checkPrimary(localPrimary47 === primaryGlobal + 47 + primaryShadow, "local write 47");
var primaryArray47 = [primaryGlobal, localPrimary47, primaryShadow];
checkPrimary(primaryArray47[0] === primaryGlobal, "array primary 47");
var primaryObject47 = { value: localPrimary47, alias: primaryGlobal };
checkPrimary(primaryObject47.alias + primaryObject47.value === primaryGlobal + localPrimary47, "object primary 47");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 47");
var localPrimary48 = primaryGlobal + 48;
checkPrimary(localPrimary48 === primaryGlobal + 48, "local read 48");
localPrimary48 = localPrimary48 + primaryShadow;
checkPrimary(localPrimary48 === primaryGlobal + 48 + primaryShadow, "local write 48");
var primaryArray48 = [primaryGlobal, localPrimary48, primaryShadow];
checkPrimary(primaryArray48[0] === primaryGlobal, "array primary 48");
var primaryObject48 = { value: localPrimary48, alias: primaryGlobal };
checkPrimary(primaryObject48.alias + primaryObject48.value === primaryGlobal + localPrimary48, "object primary 48");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 48");
function nestedPrimary48(input) {
var primaryGlobal = input + 48;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary48(49) === 49 + 48 + primaryShadow, "nested nearest 48");
var localPrimary49 = primaryGlobal + 49;
checkPrimary(localPrimary49 === primaryGlobal + 49, "local read 49");
localPrimary49 = localPrimary49 + primaryShadow;
checkPrimary(localPrimary49 === primaryGlobal + 49 + primaryShadow, "local write 49");
var primaryArray49 = [primaryGlobal, localPrimary49, primaryShadow];
checkPrimary(primaryArray49[0] === primaryGlobal, "array primary 49");
var primaryObject49 = { value: localPrimary49, alias: primaryGlobal };
checkPrimary(primaryObject49.alias + primaryObject49.value === primaryGlobal + localPrimary49, "object primary 49");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 49");
var localPrimary50 = primaryGlobal + 50;
checkPrimary(localPrimary50 === primaryGlobal + 50, "local read 50");
localPrimary50 = localPrimary50 + primaryShadow;
checkPrimary(localPrimary50 === primaryGlobal + 50 + primaryShadow, "local write 50");
var primaryArray50 = [primaryGlobal, localPrimary50, primaryShadow];
checkPrimary(primaryArray50[0] === primaryGlobal, "array primary 50");
var primaryObject50 = { value: localPrimary50, alias: primaryGlobal };
checkPrimary(primaryObject50.alias + primaryObject50.value === primaryGlobal + localPrimary50, "object primary 50");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 50");
var closurePrimary50 = makePrimaryClosure(100);
checkPrimary(closurePrimary50(50) === 100 + 50, "closure primary 50");
var localPrimary51 = primaryGlobal + 51;
checkPrimary(localPrimary51 === primaryGlobal + 51, "local read 51");
localPrimary51 = localPrimary51 + primaryShadow;
checkPrimary(localPrimary51 === primaryGlobal + 51 + primaryShadow, "local write 51");
var primaryArray51 = [primaryGlobal, localPrimary51, primaryShadow];
checkPrimary(primaryArray51[0] === primaryGlobal, "array primary 51");
var primaryObject51 = { value: localPrimary51, alias: primaryGlobal };
checkPrimary(primaryObject51.alias + primaryObject51.value === primaryGlobal + localPrimary51, "object primary 51");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 51");
var localPrimary52 = primaryGlobal + 52;
checkPrimary(localPrimary52 === primaryGlobal + 52, "local read 52");
localPrimary52 = localPrimary52 + primaryShadow;
checkPrimary(localPrimary52 === primaryGlobal + 52 + primaryShadow, "local write 52");
var primaryArray52 = [primaryGlobal, localPrimary52, primaryShadow];
checkPrimary(primaryArray52[0] === primaryGlobal, "array primary 52");
var primaryObject52 = { value: localPrimary52, alias: primaryGlobal };
checkPrimary(primaryObject52.alias + primaryObject52.value === primaryGlobal + localPrimary52, "object primary 52");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 52");
function nestedPrimary52(input) {
var primaryGlobal = input + 52;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary52(53) === 53 + 52 + primaryShadow, "nested nearest 52");
var localPrimary53 = primaryGlobal + 53;
checkPrimary(localPrimary53 === primaryGlobal + 53, "local read 53");
localPrimary53 = localPrimary53 + primaryShadow;
checkPrimary(localPrimary53 === primaryGlobal + 53 + primaryShadow, "local write 53");
var primaryArray53 = [primaryGlobal, localPrimary53, primaryShadow];
checkPrimary(primaryArray53[0] === primaryGlobal, "array primary 53");
var primaryObject53 = { value: localPrimary53, alias: primaryGlobal };
checkPrimary(primaryObject53.alias + primaryObject53.value === primaryGlobal + localPrimary53, "object primary 53");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 53");
var localPrimary54 = primaryGlobal + 54;
checkPrimary(localPrimary54 === primaryGlobal + 54, "local read 54");
localPrimary54 = localPrimary54 + primaryShadow;
checkPrimary(localPrimary54 === primaryGlobal + 54 + primaryShadow, "local write 54");
var primaryArray54 = [primaryGlobal, localPrimary54, primaryShadow];
checkPrimary(primaryArray54[0] === primaryGlobal, "array primary 54");
var primaryObject54 = { value: localPrimary54, alias: primaryGlobal };
checkPrimary(primaryObject54.alias + primaryObject54.value === primaryGlobal + localPrimary54, "object primary 54");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 54");
var localPrimary55 = primaryGlobal + 55;
checkPrimary(localPrimary55 === primaryGlobal + 55, "local read 55");
localPrimary55 = localPrimary55 + primaryShadow;
checkPrimary(localPrimary55 === primaryGlobal + 55 + primaryShadow, "local write 55");
var primaryArray55 = [primaryGlobal, localPrimary55, primaryShadow];
checkPrimary(primaryArray55[0] === primaryGlobal, "array primary 55");
var primaryObject55 = { value: localPrimary55, alias: primaryGlobal };
checkPrimary(primaryObject55.alias + primaryObject55.value === primaryGlobal + localPrimary55, "object primary 55");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 55");
var closurePrimary55 = makePrimaryClosure(105);
checkPrimary(closurePrimary55(55) === 105 + 55, "closure primary 55");
var localPrimary56 = primaryGlobal + 56;
checkPrimary(localPrimary56 === primaryGlobal + 56, "local read 56");
localPrimary56 = localPrimary56 + primaryShadow;
checkPrimary(localPrimary56 === primaryGlobal + 56 + primaryShadow, "local write 56");
var primaryArray56 = [primaryGlobal, localPrimary56, primaryShadow];
checkPrimary(primaryArray56[0] === primaryGlobal, "array primary 56");
var primaryObject56 = { value: localPrimary56, alias: primaryGlobal };
checkPrimary(primaryObject56.alias + primaryObject56.value === primaryGlobal + localPrimary56, "object primary 56");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 56");
function nestedPrimary56(input) {
var primaryGlobal = input + 56;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary56(57) === 57 + 56 + primaryShadow, "nested nearest 56");
var localPrimary57 = primaryGlobal + 57;
checkPrimary(localPrimary57 === primaryGlobal + 57, "local read 57");
localPrimary57 = localPrimary57 + primaryShadow;
checkPrimary(localPrimary57 === primaryGlobal + 57 + primaryShadow, "local write 57");
var primaryArray57 = [primaryGlobal, localPrimary57, primaryShadow];
checkPrimary(primaryArray57[0] === primaryGlobal, "array primary 57");
var primaryObject57 = { value: localPrimary57, alias: primaryGlobal };
checkPrimary(primaryObject57.alias + primaryObject57.value === primaryGlobal + localPrimary57, "object primary 57");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 57");
var localPrimary58 = primaryGlobal + 58;
checkPrimary(localPrimary58 === primaryGlobal + 58, "local read 58");
localPrimary58 = localPrimary58 + primaryShadow;
checkPrimary(localPrimary58 === primaryGlobal + 58 + primaryShadow, "local write 58");
var primaryArray58 = [primaryGlobal, localPrimary58, primaryShadow];
checkPrimary(primaryArray58[0] === primaryGlobal, "array primary 58");
var primaryObject58 = { value: localPrimary58, alias: primaryGlobal };
checkPrimary(primaryObject58.alias + primaryObject58.value === primaryGlobal + localPrimary58, "object primary 58");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 58");
var localPrimary59 = primaryGlobal + 59;
checkPrimary(localPrimary59 === primaryGlobal + 59, "local read 59");
localPrimary59 = localPrimary59 + primaryShadow;
checkPrimary(localPrimary59 === primaryGlobal + 59 + primaryShadow, "local write 59");
var primaryArray59 = [primaryGlobal, localPrimary59, primaryShadow];
checkPrimary(primaryArray59[0] === primaryGlobal, "array primary 59");
var primaryObject59 = { value: localPrimary59, alias: primaryGlobal };
checkPrimary(primaryObject59.alias + primaryObject59.value === primaryGlobal + localPrimary59, "object primary 59");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 59");
var localPrimary60 = primaryGlobal + 60;
checkPrimary(localPrimary60 === primaryGlobal + 60, "local read 60");
localPrimary60 = localPrimary60 + primaryShadow;
checkPrimary(localPrimary60 === primaryGlobal + 60 + primaryShadow, "local write 60");
var primaryArray60 = [primaryGlobal, localPrimary60, primaryShadow];
checkPrimary(primaryArray60[0] === primaryGlobal, "array primary 60");
var primaryObject60 = { value: localPrimary60, alias: primaryGlobal };
checkPrimary(primaryObject60.alias + primaryObject60.value === primaryGlobal + localPrimary60, "object primary 60");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 60");
function nestedPrimary60(input) {
var primaryGlobal = input + 60;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary60(61) === 61 + 60 + primaryShadow, "nested nearest 60");
var closurePrimary60 = makePrimaryClosure(110);
checkPrimary(closurePrimary60(60) === 110 + 60, "closure primary 60");
var localPrimary61 = primaryGlobal + 61;
checkPrimary(localPrimary61 === primaryGlobal + 61, "local read 61");
localPrimary61 = localPrimary61 + primaryShadow;
checkPrimary(localPrimary61 === primaryGlobal + 61 + primaryShadow, "local write 61");
var primaryArray61 = [primaryGlobal, localPrimary61, primaryShadow];
checkPrimary(primaryArray61[0] === primaryGlobal, "array primary 61");
var primaryObject61 = { value: localPrimary61, alias: primaryGlobal };
checkPrimary(primaryObject61.alias + primaryObject61.value === primaryGlobal + localPrimary61, "object primary 61");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 61");
var localPrimary62 = primaryGlobal + 62;
checkPrimary(localPrimary62 === primaryGlobal + 62, "local read 62");
localPrimary62 = localPrimary62 + primaryShadow;
checkPrimary(localPrimary62 === primaryGlobal + 62 + primaryShadow, "local write 62");
var primaryArray62 = [primaryGlobal, localPrimary62, primaryShadow];
checkPrimary(primaryArray62[0] === primaryGlobal, "array primary 62");
var primaryObject62 = { value: localPrimary62, alias: primaryGlobal };
checkPrimary(primaryObject62.alias + primaryObject62.value === primaryGlobal + localPrimary62, "object primary 62");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 62");
var localPrimary63 = primaryGlobal + 63;
checkPrimary(localPrimary63 === primaryGlobal + 63, "local read 63");
localPrimary63 = localPrimary63 + primaryShadow;
checkPrimary(localPrimary63 === primaryGlobal + 63 + primaryShadow, "local write 63");
var primaryArray63 = [primaryGlobal, localPrimary63, primaryShadow];
checkPrimary(primaryArray63[0] === primaryGlobal, "array primary 63");
var primaryObject63 = { value: localPrimary63, alias: primaryGlobal };
checkPrimary(primaryObject63.alias + primaryObject63.value === primaryGlobal + localPrimary63, "object primary 63");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 63");
var localPrimary64 = primaryGlobal + 64;
checkPrimary(localPrimary64 === primaryGlobal + 64, "local read 64");
localPrimary64 = localPrimary64 + primaryShadow;
checkPrimary(localPrimary64 === primaryGlobal + 64 + primaryShadow, "local write 64");
var primaryArray64 = [primaryGlobal, localPrimary64, primaryShadow];
checkPrimary(primaryArray64[0] === primaryGlobal, "array primary 64");
var primaryObject64 = { value: localPrimary64, alias: primaryGlobal };
checkPrimary(primaryObject64.alias + primaryObject64.value === primaryGlobal + localPrimary64, "object primary 64");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 64");
function nestedPrimary64(input) {
var primaryGlobal = input + 64;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary64(65) === 65 + 64 + primaryShadow, "nested nearest 64");
var localPrimary65 = primaryGlobal + 65;
checkPrimary(localPrimary65 === primaryGlobal + 65, "local read 65");
localPrimary65 = localPrimary65 + primaryShadow;
checkPrimary(localPrimary65 === primaryGlobal + 65 + primaryShadow, "local write 65");
var primaryArray65 = [primaryGlobal, localPrimary65, primaryShadow];
checkPrimary(primaryArray65[0] === primaryGlobal, "array primary 65");
var primaryObject65 = { value: localPrimary65, alias: primaryGlobal };
checkPrimary(primaryObject65.alias + primaryObject65.value === primaryGlobal + localPrimary65, "object primary 65");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 65");
var closurePrimary65 = makePrimaryClosure(115);
checkPrimary(closurePrimary65(65) === 115 + 65, "closure primary 65");
var localPrimary66 = primaryGlobal + 66;
checkPrimary(localPrimary66 === primaryGlobal + 66, "local read 66");
localPrimary66 = localPrimary66 + primaryShadow;
checkPrimary(localPrimary66 === primaryGlobal + 66 + primaryShadow, "local write 66");
var primaryArray66 = [primaryGlobal, localPrimary66, primaryShadow];
checkPrimary(primaryArray66[0] === primaryGlobal, "array primary 66");
var primaryObject66 = { value: localPrimary66, alias: primaryGlobal };
checkPrimary(primaryObject66.alias + primaryObject66.value === primaryGlobal + localPrimary66, "object primary 66");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 66");
var localPrimary67 = primaryGlobal + 67;
checkPrimary(localPrimary67 === primaryGlobal + 67, "local read 67");
localPrimary67 = localPrimary67 + primaryShadow;
checkPrimary(localPrimary67 === primaryGlobal + 67 + primaryShadow, "local write 67");
var primaryArray67 = [primaryGlobal, localPrimary67, primaryShadow];
checkPrimary(primaryArray67[0] === primaryGlobal, "array primary 67");
var primaryObject67 = { value: localPrimary67, alias: primaryGlobal };
checkPrimary(primaryObject67.alias + primaryObject67.value === primaryGlobal + localPrimary67, "object primary 67");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 67");
var localPrimary68 = primaryGlobal + 68;
checkPrimary(localPrimary68 === primaryGlobal + 68, "local read 68");
localPrimary68 = localPrimary68 + primaryShadow;
checkPrimary(localPrimary68 === primaryGlobal + 68 + primaryShadow, "local write 68");
var primaryArray68 = [primaryGlobal, localPrimary68, primaryShadow];
checkPrimary(primaryArray68[0] === primaryGlobal, "array primary 68");
var primaryObject68 = { value: localPrimary68, alias: primaryGlobal };
checkPrimary(primaryObject68.alias + primaryObject68.value === primaryGlobal + localPrimary68, "object primary 68");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 68");
function nestedPrimary68(input) {
var primaryGlobal = input + 68;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary68(69) === 69 + 68 + primaryShadow, "nested nearest 68");
var localPrimary69 = primaryGlobal + 69;
checkPrimary(localPrimary69 === primaryGlobal + 69, "local read 69");
localPrimary69 = localPrimary69 + primaryShadow;
checkPrimary(localPrimary69 === primaryGlobal + 69 + primaryShadow, "local write 69");
var primaryArray69 = [primaryGlobal, localPrimary69, primaryShadow];
checkPrimary(primaryArray69[0] === primaryGlobal, "array primary 69");
var primaryObject69 = { value: localPrimary69, alias: primaryGlobal };
checkPrimary(primaryObject69.alias + primaryObject69.value === primaryGlobal + localPrimary69, "object primary 69");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 69");
var localPrimary70 = primaryGlobal + 70;
checkPrimary(localPrimary70 === primaryGlobal + 70, "local read 70");
localPrimary70 = localPrimary70 + primaryShadow;
checkPrimary(localPrimary70 === primaryGlobal + 70 + primaryShadow, "local write 70");
var primaryArray70 = [primaryGlobal, localPrimary70, primaryShadow];
checkPrimary(primaryArray70[0] === primaryGlobal, "array primary 70");
var primaryObject70 = { value: localPrimary70, alias: primaryGlobal };
checkPrimary(primaryObject70.alias + primaryObject70.value === primaryGlobal + localPrimary70, "object primary 70");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 70");
var closurePrimary70 = makePrimaryClosure(120);
checkPrimary(closurePrimary70(70) === 120 + 70, "closure primary 70");
var localPrimary71 = primaryGlobal + 71;
checkPrimary(localPrimary71 === primaryGlobal + 71, "local read 71");
localPrimary71 = localPrimary71 + primaryShadow;
checkPrimary(localPrimary71 === primaryGlobal + 71 + primaryShadow, "local write 71");
var primaryArray71 = [primaryGlobal, localPrimary71, primaryShadow];
checkPrimary(primaryArray71[0] === primaryGlobal, "array primary 71");
var primaryObject71 = { value: localPrimary71, alias: primaryGlobal };
checkPrimary(primaryObject71.alias + primaryObject71.value === primaryGlobal + localPrimary71, "object primary 71");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 71");
var localPrimary72 = primaryGlobal + 72;
checkPrimary(localPrimary72 === primaryGlobal + 72, "local read 72");
localPrimary72 = localPrimary72 + primaryShadow;
checkPrimary(localPrimary72 === primaryGlobal + 72 + primaryShadow, "local write 72");
var primaryArray72 = [primaryGlobal, localPrimary72, primaryShadow];
checkPrimary(primaryArray72[0] === primaryGlobal, "array primary 72");
var primaryObject72 = { value: localPrimary72, alias: primaryGlobal };
checkPrimary(primaryObject72.alias + primaryObject72.value === primaryGlobal + localPrimary72, "object primary 72");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 72");
function nestedPrimary72(input) {
var primaryGlobal = input + 72;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary72(73) === 73 + 72 + primaryShadow, "nested nearest 72");
var localPrimary73 = primaryGlobal + 73;
checkPrimary(localPrimary73 === primaryGlobal + 73, "local read 73");
localPrimary73 = localPrimary73 + primaryShadow;
checkPrimary(localPrimary73 === primaryGlobal + 73 + primaryShadow, "local write 73");
var primaryArray73 = [primaryGlobal, localPrimary73, primaryShadow];
checkPrimary(primaryArray73[0] === primaryGlobal, "array primary 73");
var primaryObject73 = { value: localPrimary73, alias: primaryGlobal };
checkPrimary(primaryObject73.alias + primaryObject73.value === primaryGlobal + localPrimary73, "object primary 73");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 73");
var localPrimary74 = primaryGlobal + 74;
checkPrimary(localPrimary74 === primaryGlobal + 74, "local read 74");
localPrimary74 = localPrimary74 + primaryShadow;
checkPrimary(localPrimary74 === primaryGlobal + 74 + primaryShadow, "local write 74");
var primaryArray74 = [primaryGlobal, localPrimary74, primaryShadow];
checkPrimary(primaryArray74[0] === primaryGlobal, "array primary 74");
var primaryObject74 = { value: localPrimary74, alias: primaryGlobal };
checkPrimary(primaryObject74.alias + primaryObject74.value === primaryGlobal + localPrimary74, "object primary 74");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 74");
var localPrimary75 = primaryGlobal + 75;
checkPrimary(localPrimary75 === primaryGlobal + 75, "local read 75");
localPrimary75 = localPrimary75 + primaryShadow;
checkPrimary(localPrimary75 === primaryGlobal + 75 + primaryShadow, "local write 75");
var primaryArray75 = [primaryGlobal, localPrimary75, primaryShadow];
checkPrimary(primaryArray75[0] === primaryGlobal, "array primary 75");
var primaryObject75 = { value: localPrimary75, alias: primaryGlobal };
checkPrimary(primaryObject75.alias + primaryObject75.value === primaryGlobal + localPrimary75, "object primary 75");
primaryGlobal = primaryGlobal + 6;
primaryGlobal = primaryGlobal - 6;
checkPrimary(primaryGlobal === 17, "stable outer 75");
var closurePrimary75 = makePrimaryClosure(125);
checkPrimary(closurePrimary75(75) === 125 + 75, "closure primary 75");
var localPrimary76 = primaryGlobal + 76;
checkPrimary(localPrimary76 === primaryGlobal + 76, "local read 76");
localPrimary76 = localPrimary76 + primaryShadow;
checkPrimary(localPrimary76 === primaryGlobal + 76 + primaryShadow, "local write 76");
var primaryArray76 = [primaryGlobal, localPrimary76, primaryShadow];
checkPrimary(primaryArray76[0] === primaryGlobal, "array primary 76");
var primaryObject76 = { value: localPrimary76, alias: primaryGlobal };
checkPrimary(primaryObject76.alias + primaryObject76.value === primaryGlobal + localPrimary76, "object primary 76");
primaryGlobal = primaryGlobal + 7;
primaryGlobal = primaryGlobal - 7;
checkPrimary(primaryGlobal === 17, "stable outer 76");
function nestedPrimary76(input) {
var primaryGlobal = input + 76;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary76(77) === 77 + 76 + primaryShadow, "nested nearest 76");
var localPrimary77 = primaryGlobal + 77;
checkPrimary(localPrimary77 === primaryGlobal + 77, "local read 77");
localPrimary77 = localPrimary77 + primaryShadow;
checkPrimary(localPrimary77 === primaryGlobal + 77 + primaryShadow, "local write 77");
var primaryArray77 = [primaryGlobal, localPrimary77, primaryShadow];
checkPrimary(primaryArray77[0] === primaryGlobal, "array primary 77");
var primaryObject77 = { value: localPrimary77, alias: primaryGlobal };
checkPrimary(primaryObject77.alias + primaryObject77.value === primaryGlobal + localPrimary77, "object primary 77");
primaryGlobal = primaryGlobal + 1;
primaryGlobal = primaryGlobal - 1;
checkPrimary(primaryGlobal === 17, "stable outer 77");
var localPrimary78 = primaryGlobal + 78;
checkPrimary(localPrimary78 === primaryGlobal + 78, "local read 78");
localPrimary78 = localPrimary78 + primaryShadow;
checkPrimary(localPrimary78 === primaryGlobal + 78 + primaryShadow, "local write 78");
var primaryArray78 = [primaryGlobal, localPrimary78, primaryShadow];
checkPrimary(primaryArray78[0] === primaryGlobal, "array primary 78");
var primaryObject78 = { value: localPrimary78, alias: primaryGlobal };
checkPrimary(primaryObject78.alias + primaryObject78.value === primaryGlobal + localPrimary78, "object primary 78");
primaryGlobal = primaryGlobal + 2;
primaryGlobal = primaryGlobal - 2;
checkPrimary(primaryGlobal === 17, "stable outer 78");
var localPrimary79 = primaryGlobal + 79;
checkPrimary(localPrimary79 === primaryGlobal + 79, "local read 79");
localPrimary79 = localPrimary79 + primaryShadow;
checkPrimary(localPrimary79 === primaryGlobal + 79 + primaryShadow, "local write 79");
var primaryArray79 = [primaryGlobal, localPrimary79, primaryShadow];
checkPrimary(primaryArray79[0] === primaryGlobal, "array primary 79");
var primaryObject79 = { value: localPrimary79, alias: primaryGlobal };
checkPrimary(primaryObject79.alias + primaryObject79.value === primaryGlobal + localPrimary79, "object primary 79");
primaryGlobal = primaryGlobal + 3;
primaryGlobal = primaryGlobal - 3;
checkPrimary(primaryGlobal === 17, "stable outer 79");
var localPrimary80 = primaryGlobal + 80;
checkPrimary(localPrimary80 === primaryGlobal + 80, "local read 80");
localPrimary80 = localPrimary80 + primaryShadow;
checkPrimary(localPrimary80 === primaryGlobal + 80 + primaryShadow, "local write 80");
var primaryArray80 = [primaryGlobal, localPrimary80, primaryShadow];
checkPrimary(primaryArray80[0] === primaryGlobal, "array primary 80");
var primaryObject80 = { value: localPrimary80, alias: primaryGlobal };
checkPrimary(primaryObject80.alias + primaryObject80.value === primaryGlobal + localPrimary80, "object primary 80");
primaryGlobal = primaryGlobal + 4;
primaryGlobal = primaryGlobal - 4;
checkPrimary(primaryGlobal === 17, "stable outer 80");
function nestedPrimary80(input) {
var primaryGlobal = input + 80;
return primaryGlobal + primaryShadow;
}
checkPrimary(nestedPrimary80(81) === 81 + 80 + primaryShadow, "nested nearest 80");
var closurePrimary80 = makePrimaryClosure(130);
checkPrimary(closurePrimary80(80) === 130 + 80, "closure primary 80");
var localPrimary81 = primaryGlobal + 81;
checkPrimary(localPrimary81 === primaryGlobal + 81, "local read 81");
localPrimary81 = localPrimary81 + primaryShadow;
checkPrimary(localPrimary81 === primaryGlobal + 81 + primaryShadow, "local write 81");
var primaryArray81 = [primaryGlobal, localPrimary81, primaryShadow];
checkPrimary(primaryArray81[0] === primaryGlobal, "array primary 81");
var primaryObject81 = { value: localPrimary81, alias: primaryGlobal };
checkPrimary(primaryObject81.alias + primaryObject81.value === primaryGlobal + localPrimary81, "object primary 81");
primaryGlobal = primaryGlobal + 5;
primaryGlobal = primaryGlobal - 5;
checkPrimary(primaryGlobal === 17, "stable outer 81");
checkPrimary(primaryGlobal === 17, "final primary global");
checkPrimary(primaryScore > 0, "score advanced");
console.log("ok", primaryScore, primaryGlobal, primaryShadow);
