// behavior: string-literals-evaluate-sv
// expected: pass
// goal: script
// size: large
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}
function sameString(value) { return value; }
var plainString0 = "literal-0";
check(plainString0 === 'literal-0', 'plain string 0');
check(plainString0.length === 9, 'plain length 0');
var singleString0 = 'single-0';
check(singleString0 === "single-0", 'single string 0');
var newlineString0 = "row\n0";
check(newlineString0.length === 5, 'newline length 0');
var hexEscapeString0 = "\x41-0";
check(hexEscapeString0 === 'A-0', 'hex escape string 0');
var unicodeEscapeString0 = "\u0041\u0042-0";
check(unicodeEscapeString0 === 'AB-0', 'unicode escape string 0');
var codePointString0 = "\u{1F600}-0";
check(codePointString0.length === 4, 'code point length 0');
var quoteString0 = "\"\'0";
check(quoteString0.length === 3, 'quote escape length 0');
var slashString0 = "path\\0";
check(slashString0 === 'path\\0', 'slash escape string 0');
var nullEscapeString0 = "\0x0";
check(nullEscapeString0.length === 3, 'null escape length 0');
var continuedString0 = "left\
right0";
check(continuedString0 === 'leftright0', 'line continuation string 0');
check(sameString(plainString0) === 'literal-0', 'string argument 0');
var plainString1 = "literal-1";
check(plainString1 === 'literal-1', 'plain string 1');
check(plainString1.length === 9, 'plain length 1');
var singleString1 = 'single-1';
check(singleString1 === "single-1", 'single string 1');
var newlineString1 = "row\n1";
check(newlineString1.length === 5, 'newline length 1');
var hexEscapeString1 = "\x41-1";
check(hexEscapeString1 === 'A-1', 'hex escape string 1');
var unicodeEscapeString1 = "\u0041\u0042-1";
check(unicodeEscapeString1 === 'AB-1', 'unicode escape string 1');
var codePointString1 = "\u{1F600}-1";
check(codePointString1.length === 4, 'code point length 1');
var quoteString1 = "\"\'1";
check(quoteString1.length === 3, 'quote escape length 1');
var slashString1 = "path\\1";
check(slashString1 === 'path\\1', 'slash escape string 1');
var nullEscapeString1 = "\0x1";
check(nullEscapeString1.length === 3, 'null escape length 1');
var continuedString1 = "left\
right1";
check(continuedString1 === 'leftright1', 'line continuation string 1');
check(sameString(plainString1) === 'literal-1', 'string argument 1');
var plainString2 = "literal-2";
check(plainString2 === 'literal-2', 'plain string 2');
check(plainString2.length === 9, 'plain length 2');
var singleString2 = 'single-2';
check(singleString2 === "single-2", 'single string 2');
var newlineString2 = "row\n2";
check(newlineString2.length === 5, 'newline length 2');
var hexEscapeString2 = "\x41-2";
check(hexEscapeString2 === 'A-2', 'hex escape string 2');
var unicodeEscapeString2 = "\u0041\u0042-2";
check(unicodeEscapeString2 === 'AB-2', 'unicode escape string 2');
var codePointString2 = "\u{1F600}-2";
check(codePointString2.length === 4, 'code point length 2');
var quoteString2 = "\"\'2";
check(quoteString2.length === 3, 'quote escape length 2');
var slashString2 = "path\\2";
check(slashString2 === 'path\\2', 'slash escape string 2');
var nullEscapeString2 = "\0x2";
check(nullEscapeString2.length === 3, 'null escape length 2');
var continuedString2 = "left\
right2";
check(continuedString2 === 'leftright2', 'line continuation string 2');
check(sameString(plainString2) === 'literal-2', 'string argument 2');
var plainString3 = "literal-3";
check(plainString3 === 'literal-3', 'plain string 3');
check(plainString3.length === 9, 'plain length 3');
var singleString3 = 'single-3';
check(singleString3 === "single-3", 'single string 3');
var newlineString3 = "row\n3";
check(newlineString3.length === 5, 'newline length 3');
var hexEscapeString3 = "\x41-3";
check(hexEscapeString3 === 'A-3', 'hex escape string 3');
var unicodeEscapeString3 = "\u0041\u0042-3";
check(unicodeEscapeString3 === 'AB-3', 'unicode escape string 3');
var codePointString3 = "\u{1F600}-3";
check(codePointString3.length === 4, 'code point length 3');
var quoteString3 = "\"\'3";
check(quoteString3.length === 3, 'quote escape length 3');
var slashString3 = "path\\3";
check(slashString3 === 'path\\3', 'slash escape string 3');
var nullEscapeString3 = "\0x3";
check(nullEscapeString3.length === 3, 'null escape length 3');
var continuedString3 = "left\
right3";
check(continuedString3 === 'leftright3', 'line continuation string 3');
check(sameString(plainString3) === 'literal-3', 'string argument 3');
var plainString4 = "literal-4";
check(plainString4 === 'literal-4', 'plain string 4');
check(plainString4.length === 9, 'plain length 4');
var singleString4 = 'single-4';
check(singleString4 === "single-4", 'single string 4');
var newlineString4 = "row\n4";
check(newlineString4.length === 5, 'newline length 4');
var hexEscapeString4 = "\x41-4";
check(hexEscapeString4 === 'A-4', 'hex escape string 4');
var unicodeEscapeString4 = "\u0041\u0042-4";
check(unicodeEscapeString4 === 'AB-4', 'unicode escape string 4');
var codePointString4 = "\u{1F600}-4";
check(codePointString4.length === 4, 'code point length 4');
var quoteString4 = "\"\'4";
check(quoteString4.length === 3, 'quote escape length 4');
var slashString4 = "path\\4";
check(slashString4 === 'path\\4', 'slash escape string 4');
var nullEscapeString4 = "\0x4";
check(nullEscapeString4.length === 3, 'null escape length 4');
var continuedString4 = "left\
right4";
check(continuedString4 === 'leftright4', 'line continuation string 4');
check(sameString(plainString4) === 'literal-4', 'string argument 4');
var plainString5 = "literal-5";
check(plainString5 === 'literal-5', 'plain string 5');
check(plainString5.length === 9, 'plain length 5');
var singleString5 = 'single-5';
check(singleString5 === "single-5", 'single string 5');
var newlineString5 = "row\n5";
check(newlineString5.length === 5, 'newline length 5');
var hexEscapeString5 = "\x41-5";
check(hexEscapeString5 === 'A-5', 'hex escape string 5');
var unicodeEscapeString5 = "\u0041\u0042-5";
check(unicodeEscapeString5 === 'AB-5', 'unicode escape string 5');
var codePointString5 = "\u{1F600}-5";
check(codePointString5.length === 4, 'code point length 5');
var quoteString5 = "\"\'5";
check(quoteString5.length === 3, 'quote escape length 5');
var slashString5 = "path\\5";
check(slashString5 === 'path\\5', 'slash escape string 5');
var nullEscapeString5 = "\0x5";
check(nullEscapeString5.length === 3, 'null escape length 5');
var continuedString5 = "left\
right5";
check(continuedString5 === 'leftright5', 'line continuation string 5');
check(sameString(plainString5) === 'literal-5', 'string argument 5');
var plainString6 = "literal-6";
check(plainString6 === 'literal-6', 'plain string 6');
check(plainString6.length === 9, 'plain length 6');
var singleString6 = 'single-6';
check(singleString6 === "single-6", 'single string 6');
var newlineString6 = "row\n6";
check(newlineString6.length === 5, 'newline length 6');
var hexEscapeString6 = "\x41-6";
check(hexEscapeString6 === 'A-6', 'hex escape string 6');
var unicodeEscapeString6 = "\u0041\u0042-6";
check(unicodeEscapeString6 === 'AB-6', 'unicode escape string 6');
var codePointString6 = "\u{1F600}-6";
check(codePointString6.length === 4, 'code point length 6');
var quoteString6 = "\"\'6";
check(quoteString6.length === 3, 'quote escape length 6');
var slashString6 = "path\\6";
check(slashString6 === 'path\\6', 'slash escape string 6');
var nullEscapeString6 = "\0x6";
check(nullEscapeString6.length === 3, 'null escape length 6');
var continuedString6 = "left\
right6";
check(continuedString6 === 'leftright6', 'line continuation string 6');
check(sameString(plainString6) === 'literal-6', 'string argument 6');
var plainString7 = "literal-7";
check(plainString7 === 'literal-7', 'plain string 7');
check(plainString7.length === 9, 'plain length 7');
var singleString7 = 'single-7';
check(singleString7 === "single-7", 'single string 7');
var newlineString7 = "row\n7";
check(newlineString7.length === 5, 'newline length 7');
var hexEscapeString7 = "\x41-7";
check(hexEscapeString7 === 'A-7', 'hex escape string 7');
var unicodeEscapeString7 = "\u0041\u0042-7";
check(unicodeEscapeString7 === 'AB-7', 'unicode escape string 7');
var codePointString7 = "\u{1F600}-7";
check(codePointString7.length === 4, 'code point length 7');
var quoteString7 = "\"\'7";
check(quoteString7.length === 3, 'quote escape length 7');
var slashString7 = "path\\7";
check(slashString7 === 'path\\7', 'slash escape string 7');
var nullEscapeString7 = "\0x7";
check(nullEscapeString7.length === 3, 'null escape length 7');
var continuedString7 = "left\
right7";
check(continuedString7 === 'leftright7', 'line continuation string 7');
check(sameString(plainString7) === 'literal-7', 'string argument 7');
var plainString8 = "literal-8";
check(plainString8 === 'literal-8', 'plain string 8');
check(plainString8.length === 9, 'plain length 8');
var singleString8 = 'single-8';
check(singleString8 === "single-8", 'single string 8');
var newlineString8 = "row\n8";
check(newlineString8.length === 5, 'newline length 8');
var hexEscapeString8 = "\x41-8";
check(hexEscapeString8 === 'A-8', 'hex escape string 8');
var unicodeEscapeString8 = "\u0041\u0042-8";
check(unicodeEscapeString8 === 'AB-8', 'unicode escape string 8');
var codePointString8 = "\u{1F600}-8";
check(codePointString8.length === 4, 'code point length 8');
var quoteString8 = "\"\'8";
check(quoteString8.length === 3, 'quote escape length 8');
var slashString8 = "path\\8";
check(slashString8 === 'path\\8', 'slash escape string 8');
var nullEscapeString8 = "\0x8";
check(nullEscapeString8.length === 3, 'null escape length 8');
var continuedString8 = "left\
right8";
check(continuedString8 === 'leftright8', 'line continuation string 8');
check(sameString(plainString8) === 'literal-8', 'string argument 8');
var plainString9 = "literal-9";
check(plainString9 === 'literal-9', 'plain string 9');
check(plainString9.length === 9, 'plain length 9');
var singleString9 = 'single-9';
check(singleString9 === "single-9", 'single string 9');
var newlineString9 = "row\n9";
check(newlineString9.length === 5, 'newline length 9');
var hexEscapeString9 = "\x41-9";
check(hexEscapeString9 === 'A-9', 'hex escape string 9');
var unicodeEscapeString9 = "\u0041\u0042-9";
check(unicodeEscapeString9 === 'AB-9', 'unicode escape string 9');
var codePointString9 = "\u{1F600}-9";
check(codePointString9.length === 4, 'code point length 9');
var quoteString9 = "\"\'9";
check(quoteString9.length === 3, 'quote escape length 9');
var slashString9 = "path\\9";
check(slashString9 === 'path\\9', 'slash escape string 9');
var nullEscapeString9 = "\0x9";
check(nullEscapeString9.length === 3, 'null escape length 9');
var continuedString9 = "left\
right9";
check(continuedString9 === 'leftright9', 'line continuation string 9');
check(sameString(plainString9) === 'literal-9', 'string argument 9');
var plainString10 = "literal-10";
check(plainString10 === 'literal-10', 'plain string 10');
check(plainString10.length === 10, 'plain length 10');
var singleString10 = 'single-10';
check(singleString10 === "single-10", 'single string 10');
var newlineString10 = "row\n10";
check(newlineString10.length === 6, 'newline length 10');
var hexEscapeString10 = "\x41-10";
check(hexEscapeString10 === 'A-10', 'hex escape string 10');
var unicodeEscapeString10 = "\u0041\u0042-10";
check(unicodeEscapeString10 === 'AB-10', 'unicode escape string 10');
var codePointString10 = "\u{1F600}-10";
check(codePointString10.length === 5, 'code point length 10');
var quoteString10 = "\"\'10";
check(quoteString10.length === 4, 'quote escape length 10');
var slashString10 = "path\\10";
check(slashString10 === 'path\\10', 'slash escape string 10');
var nullEscapeString10 = "\0x10";
check(nullEscapeString10.length === 4, 'null escape length 10');
var continuedString10 = "left\
right10";
check(continuedString10 === 'leftright10', 'line continuation string 10');
check(sameString(plainString10) === 'literal-10', 'string argument 10');
var plainString11 = "literal-11";
check(plainString11 === 'literal-11', 'plain string 11');
check(plainString11.length === 10, 'plain length 11');
var singleString11 = 'single-11';
check(singleString11 === "single-11", 'single string 11');
var newlineString11 = "row\n11";
check(newlineString11.length === 6, 'newline length 11');
var hexEscapeString11 = "\x41-11";
check(hexEscapeString11 === 'A-11', 'hex escape string 11');
var unicodeEscapeString11 = "\u0041\u0042-11";
check(unicodeEscapeString11 === 'AB-11', 'unicode escape string 11');
var codePointString11 = "\u{1F600}-11";
check(codePointString11.length === 5, 'code point length 11');
var quoteString11 = "\"\'11";
check(quoteString11.length === 4, 'quote escape length 11');
var slashString11 = "path\\11";
check(slashString11 === 'path\\11', 'slash escape string 11');
var nullEscapeString11 = "\0x11";
check(nullEscapeString11.length === 4, 'null escape length 11');
var continuedString11 = "left\
right11";
check(continuedString11 === 'leftright11', 'line continuation string 11');
check(sameString(plainString11) === 'literal-11', 'string argument 11');
var plainString12 = "literal-12";
check(plainString12 === 'literal-12', 'plain string 12');
check(plainString12.length === 10, 'plain length 12');
var singleString12 = 'single-12';
check(singleString12 === "single-12", 'single string 12');
var newlineString12 = "row\n12";
check(newlineString12.length === 6, 'newline length 12');
var hexEscapeString12 = "\x41-12";
check(hexEscapeString12 === 'A-12', 'hex escape string 12');
var unicodeEscapeString12 = "\u0041\u0042-12";
check(unicodeEscapeString12 === 'AB-12', 'unicode escape string 12');
var codePointString12 = "\u{1F600}-12";
check(codePointString12.length === 5, 'code point length 12');
var quoteString12 = "\"\'12";
check(quoteString12.length === 4, 'quote escape length 12');
var slashString12 = "path\\12";
check(slashString12 === 'path\\12', 'slash escape string 12');
var nullEscapeString12 = "\0x12";
check(nullEscapeString12.length === 4, 'null escape length 12');
var continuedString12 = "left\
right12";
check(continuedString12 === 'leftright12', 'line continuation string 12');
check(sameString(plainString12) === 'literal-12', 'string argument 12');
var plainString13 = "literal-13";
check(plainString13 === 'literal-13', 'plain string 13');
check(plainString13.length === 10, 'plain length 13');
var singleString13 = 'single-13';
check(singleString13 === "single-13", 'single string 13');
var newlineString13 = "row\n13";
check(newlineString13.length === 6, 'newline length 13');
var hexEscapeString13 = "\x41-13";
check(hexEscapeString13 === 'A-13', 'hex escape string 13');
var unicodeEscapeString13 = "\u0041\u0042-13";
check(unicodeEscapeString13 === 'AB-13', 'unicode escape string 13');
var codePointString13 = "\u{1F600}-13";
check(codePointString13.length === 5, 'code point length 13');
var quoteString13 = "\"\'13";
check(quoteString13.length === 4, 'quote escape length 13');
var slashString13 = "path\\13";
check(slashString13 === 'path\\13', 'slash escape string 13');
var nullEscapeString13 = "\0x13";
check(nullEscapeString13.length === 4, 'null escape length 13');
var continuedString13 = "left\
right13";
check(continuedString13 === 'leftright13', 'line continuation string 13');
check(sameString(plainString13) === 'literal-13', 'string argument 13');
var plainString14 = "literal-14";
check(plainString14 === 'literal-14', 'plain string 14');
check(plainString14.length === 10, 'plain length 14');
var singleString14 = 'single-14';
check(singleString14 === "single-14", 'single string 14');
var newlineString14 = "row\n14";
check(newlineString14.length === 6, 'newline length 14');
var hexEscapeString14 = "\x41-14";
check(hexEscapeString14 === 'A-14', 'hex escape string 14');
var unicodeEscapeString14 = "\u0041\u0042-14";
check(unicodeEscapeString14 === 'AB-14', 'unicode escape string 14');
var codePointString14 = "\u{1F600}-14";
check(codePointString14.length === 5, 'code point length 14');
var quoteString14 = "\"\'14";
check(quoteString14.length === 4, 'quote escape length 14');
var slashString14 = "path\\14";
check(slashString14 === 'path\\14', 'slash escape string 14');
var nullEscapeString14 = "\0x14";
check(nullEscapeString14.length === 4, 'null escape length 14');
var continuedString14 = "left\
right14";
check(continuedString14 === 'leftright14', 'line continuation string 14');
check(sameString(plainString14) === 'literal-14', 'string argument 14');
var plainString15 = "literal-15";
check(plainString15 === 'literal-15', 'plain string 15');
check(plainString15.length === 10, 'plain length 15');
var singleString15 = 'single-15';
check(singleString15 === "single-15", 'single string 15');
var newlineString15 = "row\n15";
check(newlineString15.length === 6, 'newline length 15');
var hexEscapeString15 = "\x41-15";
check(hexEscapeString15 === 'A-15', 'hex escape string 15');
var unicodeEscapeString15 = "\u0041\u0042-15";
check(unicodeEscapeString15 === 'AB-15', 'unicode escape string 15');
var codePointString15 = "\u{1F600}-15";
check(codePointString15.length === 5, 'code point length 15');
var quoteString15 = "\"\'15";
check(quoteString15.length === 4, 'quote escape length 15');
var slashString15 = "path\\15";
check(slashString15 === 'path\\15', 'slash escape string 15');
var nullEscapeString15 = "\0x15";
check(nullEscapeString15.length === 4, 'null escape length 15');
var continuedString15 = "left\
right15";
check(continuedString15 === 'leftright15', 'line continuation string 15');
check(sameString(plainString15) === 'literal-15', 'string argument 15');
var plainString16 = "literal-16";
check(plainString16 === 'literal-16', 'plain string 16');
check(plainString16.length === 10, 'plain length 16');
var singleString16 = 'single-16';
check(singleString16 === "single-16", 'single string 16');
var newlineString16 = "row\n16";
check(newlineString16.length === 6, 'newline length 16');
var hexEscapeString16 = "\x41-16";
check(hexEscapeString16 === 'A-16', 'hex escape string 16');
var unicodeEscapeString16 = "\u0041\u0042-16";
check(unicodeEscapeString16 === 'AB-16', 'unicode escape string 16');
var codePointString16 = "\u{1F600}-16";
check(codePointString16.length === 5, 'code point length 16');
var quoteString16 = "\"\'16";
check(quoteString16.length === 4, 'quote escape length 16');
var slashString16 = "path\\16";
check(slashString16 === 'path\\16', 'slash escape string 16');
var nullEscapeString16 = "\0x16";
check(nullEscapeString16.length === 4, 'null escape length 16');
var continuedString16 = "left\
right16";
check(continuedString16 === 'leftright16', 'line continuation string 16');
check(sameString(plainString16) === 'literal-16', 'string argument 16');
var plainString17 = "literal-17";
check(plainString17 === 'literal-17', 'plain string 17');
check(plainString17.length === 10, 'plain length 17');
var singleString17 = 'single-17';
check(singleString17 === "single-17", 'single string 17');
var newlineString17 = "row\n17";
check(newlineString17.length === 6, 'newline length 17');
var hexEscapeString17 = "\x41-17";
check(hexEscapeString17 === 'A-17', 'hex escape string 17');
var unicodeEscapeString17 = "\u0041\u0042-17";
check(unicodeEscapeString17 === 'AB-17', 'unicode escape string 17');
var codePointString17 = "\u{1F600}-17";
check(codePointString17.length === 5, 'code point length 17');
var quoteString17 = "\"\'17";
check(quoteString17.length === 4, 'quote escape length 17');
var slashString17 = "path\\17";
check(slashString17 === 'path\\17', 'slash escape string 17');
var nullEscapeString17 = "\0x17";
check(nullEscapeString17.length === 4, 'null escape length 17');
var continuedString17 = "left\
right17";
check(continuedString17 === 'leftright17', 'line continuation string 17');
check(sameString(plainString17) === 'literal-17', 'string argument 17');
var plainString18 = "literal-18";
check(plainString18 === 'literal-18', 'plain string 18');
check(plainString18.length === 10, 'plain length 18');
var singleString18 = 'single-18';
check(singleString18 === "single-18", 'single string 18');
var newlineString18 = "row\n18";
check(newlineString18.length === 6, 'newline length 18');
var hexEscapeString18 = "\x41-18";
check(hexEscapeString18 === 'A-18', 'hex escape string 18');
var unicodeEscapeString18 = "\u0041\u0042-18";
check(unicodeEscapeString18 === 'AB-18', 'unicode escape string 18');
var codePointString18 = "\u{1F600}-18";
check(codePointString18.length === 5, 'code point length 18');
var quoteString18 = "\"\'18";
check(quoteString18.length === 4, 'quote escape length 18');
var slashString18 = "path\\18";
check(slashString18 === 'path\\18', 'slash escape string 18');
var nullEscapeString18 = "\0x18";
check(nullEscapeString18.length === 4, 'null escape length 18');
var continuedString18 = "left\
right18";
check(continuedString18 === 'leftright18', 'line continuation string 18');
check(sameString(plainString18) === 'literal-18', 'string argument 18');
var plainString19 = "literal-19";
check(plainString19 === 'literal-19', 'plain string 19');
check(plainString19.length === 10, 'plain length 19');
var singleString19 = 'single-19';
check(singleString19 === "single-19", 'single string 19');
var newlineString19 = "row\n19";
check(newlineString19.length === 6, 'newline length 19');
var hexEscapeString19 = "\x41-19";
check(hexEscapeString19 === 'A-19', 'hex escape string 19');
var unicodeEscapeString19 = "\u0041\u0042-19";
check(unicodeEscapeString19 === 'AB-19', 'unicode escape string 19');
var codePointString19 = "\u{1F600}-19";
check(codePointString19.length === 5, 'code point length 19');
var quoteString19 = "\"\'19";
check(quoteString19.length === 4, 'quote escape length 19');
var slashString19 = "path\\19";
check(slashString19 === 'path\\19', 'slash escape string 19');
var nullEscapeString19 = "\0x19";
check(nullEscapeString19.length === 4, 'null escape length 19');
var continuedString19 = "left\
right19";
check(continuedString19 === 'leftright19', 'line continuation string 19');
check(sameString(plainString19) === 'literal-19', 'string argument 19');
var plainString20 = "literal-20";
check(plainString20 === 'literal-20', 'plain string 20');
check(plainString20.length === 10, 'plain length 20');
var singleString20 = 'single-20';
check(singleString20 === "single-20", 'single string 20');
var newlineString20 = "row\n20";
check(newlineString20.length === 6, 'newline length 20');
var hexEscapeString20 = "\x41-20";
check(hexEscapeString20 === 'A-20', 'hex escape string 20');
var unicodeEscapeString20 = "\u0041\u0042-20";
check(unicodeEscapeString20 === 'AB-20', 'unicode escape string 20');
var codePointString20 = "\u{1F600}-20";
check(codePointString20.length === 5, 'code point length 20');
var quoteString20 = "\"\'20";
check(quoteString20.length === 4, 'quote escape length 20');
var slashString20 = "path\\20";
check(slashString20 === 'path\\20', 'slash escape string 20');
var nullEscapeString20 = "\0x20";
check(nullEscapeString20.length === 4, 'null escape length 20');
var continuedString20 = "left\
right20";
check(continuedString20 === 'leftright20', 'line continuation string 20');
check(sameString(plainString20) === 'literal-20', 'string argument 20');
var plainString21 = "literal-21";
check(plainString21 === 'literal-21', 'plain string 21');
check(plainString21.length === 10, 'plain length 21');
var singleString21 = 'single-21';
check(singleString21 === "single-21", 'single string 21');
var newlineString21 = "row\n21";
check(newlineString21.length === 6, 'newline length 21');
var hexEscapeString21 = "\x41-21";
check(hexEscapeString21 === 'A-21', 'hex escape string 21');
var unicodeEscapeString21 = "\u0041\u0042-21";
check(unicodeEscapeString21 === 'AB-21', 'unicode escape string 21');
var codePointString21 = "\u{1F600}-21";
check(codePointString21.length === 5, 'code point length 21');
var quoteString21 = "\"\'21";
check(quoteString21.length === 4, 'quote escape length 21');
var slashString21 = "path\\21";
check(slashString21 === 'path\\21', 'slash escape string 21');
var nullEscapeString21 = "\0x21";
check(nullEscapeString21.length === 4, 'null escape length 21');
var continuedString21 = "left\
right21";
check(continuedString21 === 'leftright21', 'line continuation string 21');
check(sameString(plainString21) === 'literal-21', 'string argument 21');
console.log('string-literals-evaluate-sv large ' + score);
