// behavior: string-literals-evaluate-sv
// expected: pass
// goal: script
// size: stress
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}
function sameString(value) { return value; }
var plainString0 = "literal-0";
check(plainString0 === 'literal-0', 'plain string 0');
check(plainString0.length === 9, 'plain length 0');
var singleString0 = 'single-0';
check(singleString0 === "single-0", 'single string 0');
var newlineString0 = "row\n0";
check(newlineString0.length === 5, 'newline length 0');
var hexEscapeString0 = "\x41-0";
check(hexEscapeString0 === 'A-0', 'hex escape string 0');
var unicodeEscapeString0 = "\u0041\u0042-0";
check(unicodeEscapeString0 === 'AB-0', 'unicode escape string 0');
var codePointString0 = "\u{1F600}-0";
check(codePointString0.length === 4, 'code point length 0');
var quoteString0 = "\"\'0";
check(quoteString0.length === 3, 'quote escape length 0');
var slashString0 = "path\\0";
check(slashString0 === 'path\\0', 'slash escape string 0');
var nullEscapeString0 = "\0x0";
check(nullEscapeString0.length === 3, 'null escape length 0');
var continuedString0 = "left\
right0";
check(continuedString0 === 'leftright0', 'line continuation string 0');
check(sameString(plainString0) === 'literal-0', 'string argument 0');
var plainString1 = "literal-1";
check(plainString1 === 'literal-1', 'plain string 1');
check(plainString1.length === 9, 'plain length 1');
var singleString1 = 'single-1';
check(singleString1 === "single-1", 'single string 1');
var newlineString1 = "row\n1";
check(newlineString1.length === 5, 'newline length 1');
var hexEscapeString1 = "\x41-1";
check(hexEscapeString1 === 'A-1', 'hex escape string 1');
var unicodeEscapeString1 = "\u0041\u0042-1";
check(unicodeEscapeString1 === 'AB-1', 'unicode escape string 1');
var codePointString1 = "\u{1F600}-1";
check(codePointString1.length === 4, 'code point length 1');
var quoteString1 = "\"\'1";
check(quoteString1.length === 3, 'quote escape length 1');
var slashString1 = "path\\1";
check(slashString1 === 'path\\1', 'slash escape string 1');
var nullEscapeString1 = "\0x1";
check(nullEscapeString1.length === 3, 'null escape length 1');
var continuedString1 = "left\
right1";
check(continuedString1 === 'leftright1', 'line continuation string 1');
check(sameString(plainString1) === 'literal-1', 'string argument 1');
var plainString2 = "literal-2";
check(plainString2 === 'literal-2', 'plain string 2');
check(plainString2.length === 9, 'plain length 2');
var singleString2 = 'single-2';
check(singleString2 === "single-2", 'single string 2');
var newlineString2 = "row\n2";
check(newlineString2.length === 5, 'newline length 2');
var hexEscapeString2 = "\x41-2";
check(hexEscapeString2 === 'A-2', 'hex escape string 2');
var unicodeEscapeString2 = "\u0041\u0042-2";
check(unicodeEscapeString2 === 'AB-2', 'unicode escape string 2');
var codePointString2 = "\u{1F600}-2";
check(codePointString2.length === 4, 'code point length 2');
var quoteString2 = "\"\'2";
check(quoteString2.length === 3, 'quote escape length 2');
var slashString2 = "path\\2";
check(slashString2 === 'path\\2', 'slash escape string 2');
var nullEscapeString2 = "\0x2";
check(nullEscapeString2.length === 3, 'null escape length 2');
var continuedString2 = "left\
right2";
check(continuedString2 === 'leftright2', 'line continuation string 2');
check(sameString(plainString2) === 'literal-2', 'string argument 2');
var plainString3 = "literal-3";
check(plainString3 === 'literal-3', 'plain string 3');
check(plainString3.length === 9, 'plain length 3');
var singleString3 = 'single-3';
check(singleString3 === "single-3", 'single string 3');
var newlineString3 = "row\n3";
check(newlineString3.length === 5, 'newline length 3');
var hexEscapeString3 = "\x41-3";
check(hexEscapeString3 === 'A-3', 'hex escape string 3');
var unicodeEscapeString3 = "\u0041\u0042-3";
check(unicodeEscapeString3 === 'AB-3', 'unicode escape string 3');
var codePointString3 = "\u{1F600}-3";
check(codePointString3.length === 4, 'code point length 3');
var quoteString3 = "\"\'3";
check(quoteString3.length === 3, 'quote escape length 3');
var slashString3 = "path\\3";
check(slashString3 === 'path\\3', 'slash escape string 3');
var nullEscapeString3 = "\0x3";
check(nullEscapeString3.length === 3, 'null escape length 3');
var continuedString3 = "left\
right3";
check(continuedString3 === 'leftright3', 'line continuation string 3');
check(sameString(plainString3) === 'literal-3', 'string argument 3');
var plainString4 = "literal-4";
check(plainString4 === 'literal-4', 'plain string 4');
check(plainString4.length === 9, 'plain length 4');
var singleString4 = 'single-4';
check(singleString4 === "single-4", 'single string 4');
var newlineString4 = "row\n4";
check(newlineString4.length === 5, 'newline length 4');
var hexEscapeString4 = "\x41-4";
check(hexEscapeString4 === 'A-4', 'hex escape string 4');
var unicodeEscapeString4 = "\u0041\u0042-4";
check(unicodeEscapeString4 === 'AB-4', 'unicode escape string 4');
var codePointString4 = "\u{1F600}-4";
check(codePointString4.length === 4, 'code point length 4');
var quoteString4 = "\"\'4";
check(quoteString4.length === 3, 'quote escape length 4');
var slashString4 = "path\\4";
check(slashString4 === 'path\\4', 'slash escape string 4');
var nullEscapeString4 = "\0x4";
check(nullEscapeString4.length === 3, 'null escape length 4');
var continuedString4 = "left\
right4";
check(continuedString4 === 'leftright4', 'line continuation string 4');
check(sameString(plainString4) === 'literal-4', 'string argument 4');
var plainString5 = "literal-5";
check(plainString5 === 'literal-5', 'plain string 5');
check(plainString5.length === 9, 'plain length 5');
var singleString5 = 'single-5';
check(singleString5 === "single-5", 'single string 5');
var newlineString5 = "row\n5";
check(newlineString5.length === 5, 'newline length 5');
var hexEscapeString5 = "\x41-5";
check(hexEscapeString5 === 'A-5', 'hex escape string 5');
var unicodeEscapeString5 = "\u0041\u0042-5";
check(unicodeEscapeString5 === 'AB-5', 'unicode escape string 5');
var codePointString5 = "\u{1F600}-5";
check(codePointString5.length === 4, 'code point length 5');
var quoteString5 = "\"\'5";
check(quoteString5.length === 3, 'quote escape length 5');
var slashString5 = "path\\5";
check(slashString5 === 'path\\5', 'slash escape string 5');
var nullEscapeString5 = "\0x5";
check(nullEscapeString5.length === 3, 'null escape length 5');
var continuedString5 = "left\
right5";
check(continuedString5 === 'leftright5', 'line continuation string 5');
check(sameString(plainString5) === 'literal-5', 'string argument 5');
var plainString6 = "literal-6";
check(plainString6 === 'literal-6', 'plain string 6');
check(plainString6.length === 9, 'plain length 6');
var singleString6 = 'single-6';
check(singleString6 === "single-6", 'single string 6');
var newlineString6 = "row\n6";
check(newlineString6.length === 5, 'newline length 6');
var hexEscapeString6 = "\x41-6";
check(hexEscapeString6 === 'A-6', 'hex escape string 6');
var unicodeEscapeString6 = "\u0041\u0042-6";
check(unicodeEscapeString6 === 'AB-6', 'unicode escape string 6');
var codePointString6 = "\u{1F600}-6";
check(codePointString6.length === 4, 'code point length 6');
var quoteString6 = "\"\'6";
check(quoteString6.length === 3, 'quote escape length 6');
var slashString6 = "path\\6";
check(slashString6 === 'path\\6', 'slash escape string 6');
var nullEscapeString6 = "\0x6";
check(nullEscapeString6.length === 3, 'null escape length 6');
var continuedString6 = "left\
right6";
check(continuedString6 === 'leftright6', 'line continuation string 6');
check(sameString(plainString6) === 'literal-6', 'string argument 6');
var plainString7 = "literal-7";
check(plainString7 === 'literal-7', 'plain string 7');
check(plainString7.length === 9, 'plain length 7');
var singleString7 = 'single-7';
check(singleString7 === "single-7", 'single string 7');
var newlineString7 = "row\n7";
check(newlineString7.length === 5, 'newline length 7');
var hexEscapeString7 = "\x41-7";
check(hexEscapeString7 === 'A-7', 'hex escape string 7');
var unicodeEscapeString7 = "\u0041\u0042-7";
check(unicodeEscapeString7 === 'AB-7', 'unicode escape string 7');
var codePointString7 = "\u{1F600}-7";
check(codePointString7.length === 4, 'code point length 7');
var quoteString7 = "\"\'7";
check(quoteString7.length === 3, 'quote escape length 7');
var slashString7 = "path\\7";
check(slashString7 === 'path\\7', 'slash escape string 7');
var nullEscapeString7 = "\0x7";
check(nullEscapeString7.length === 3, 'null escape length 7');
var continuedString7 = "left\
right7";
check(continuedString7 === 'leftright7', 'line continuation string 7');
check(sameString(plainString7) === 'literal-7', 'string argument 7');
var plainString8 = "literal-8";
check(plainString8 === 'literal-8', 'plain string 8');
check(plainString8.length === 9, 'plain length 8');
var singleString8 = 'single-8';
check(singleString8 === "single-8", 'single string 8');
var newlineString8 = "row\n8";
check(newlineString8.length === 5, 'newline length 8');
var hexEscapeString8 = "\x41-8";
check(hexEscapeString8 === 'A-8', 'hex escape string 8');
var unicodeEscapeString8 = "\u0041\u0042-8";
check(unicodeEscapeString8 === 'AB-8', 'unicode escape string 8');
var codePointString8 = "\u{1F600}-8";
check(codePointString8.length === 4, 'code point length 8');
var quoteString8 = "\"\'8";
check(quoteString8.length === 3, 'quote escape length 8');
var slashString8 = "path\\8";
check(slashString8 === 'path\\8', 'slash escape string 8');
var nullEscapeString8 = "\0x8";
check(nullEscapeString8.length === 3, 'null escape length 8');
var continuedString8 = "left\
right8";
check(continuedString8 === 'leftright8', 'line continuation string 8');
check(sameString(plainString8) === 'literal-8', 'string argument 8');
var plainString9 = "literal-9";
check(plainString9 === 'literal-9', 'plain string 9');
check(plainString9.length === 9, 'plain length 9');
var singleString9 = 'single-9';
check(singleString9 === "single-9", 'single string 9');
var newlineString9 = "row\n9";
check(newlineString9.length === 5, 'newline length 9');
var hexEscapeString9 = "\x41-9";
check(hexEscapeString9 === 'A-9', 'hex escape string 9');
var unicodeEscapeString9 = "\u0041\u0042-9";
check(unicodeEscapeString9 === 'AB-9', 'unicode escape string 9');
var codePointString9 = "\u{1F600}-9";
check(codePointString9.length === 4, 'code point length 9');
var quoteString9 = "\"\'9";
check(quoteString9.length === 3, 'quote escape length 9');
var slashString9 = "path\\9";
check(slashString9 === 'path\\9', 'slash escape string 9');
var nullEscapeString9 = "\0x9";
check(nullEscapeString9.length === 3, 'null escape length 9');
var continuedString9 = "left\
right9";
check(continuedString9 === 'leftright9', 'line continuation string 9');
check(sameString(plainString9) === 'literal-9', 'string argument 9');
var plainString10 = "literal-10";
check(plainString10 === 'literal-10', 'plain string 10');
check(plainString10.length === 10, 'plain length 10');
var singleString10 = 'single-10';
check(singleString10 === "single-10", 'single string 10');
var newlineString10 = "row\n10";
check(newlineString10.length === 6, 'newline length 10');
var hexEscapeString10 = "\x41-10";
check(hexEscapeString10 === 'A-10', 'hex escape string 10');
var unicodeEscapeString10 = "\u0041\u0042-10";
check(unicodeEscapeString10 === 'AB-10', 'unicode escape string 10');
var codePointString10 = "\u{1F600}-10";
check(codePointString10.length === 5, 'code point length 10');
var quoteString10 = "\"\'10";
check(quoteString10.length === 4, 'quote escape length 10');
var slashString10 = "path\\10";
check(slashString10 === 'path\\10', 'slash escape string 10');
var nullEscapeString10 = "\0x10";
check(nullEscapeString10.length === 4, 'null escape length 10');
var continuedString10 = "left\
right10";
check(continuedString10 === 'leftright10', 'line continuation string 10');
check(sameString(plainString10) === 'literal-10', 'string argument 10');
var plainString11 = "literal-11";
check(plainString11 === 'literal-11', 'plain string 11');
check(plainString11.length === 10, 'plain length 11');
var singleString11 = 'single-11';
check(singleString11 === "single-11", 'single string 11');
var newlineString11 = "row\n11";
check(newlineString11.length === 6, 'newline length 11');
var hexEscapeString11 = "\x41-11";
check(hexEscapeString11 === 'A-11', 'hex escape string 11');
var unicodeEscapeString11 = "\u0041\u0042-11";
check(unicodeEscapeString11 === 'AB-11', 'unicode escape string 11');
var codePointString11 = "\u{1F600}-11";
check(codePointString11.length === 5, 'code point length 11');
var quoteString11 = "\"\'11";
check(quoteString11.length === 4, 'quote escape length 11');
var slashString11 = "path\\11";
check(slashString11 === 'path\\11', 'slash escape string 11');
var nullEscapeString11 = "\0x11";
check(nullEscapeString11.length === 4, 'null escape length 11');
var continuedString11 = "left\
right11";
check(continuedString11 === 'leftright11', 'line continuation string 11');
check(sameString(plainString11) === 'literal-11', 'string argument 11');
var plainString12 = "literal-12";
check(plainString12 === 'literal-12', 'plain string 12');
check(plainString12.length === 10, 'plain length 12');
var singleString12 = 'single-12';
check(singleString12 === "single-12", 'single string 12');
var newlineString12 = "row\n12";
check(newlineString12.length === 6, 'newline length 12');
var hexEscapeString12 = "\x41-12";
check(hexEscapeString12 === 'A-12', 'hex escape string 12');
var unicodeEscapeString12 = "\u0041\u0042-12";
check(unicodeEscapeString12 === 'AB-12', 'unicode escape string 12');
var codePointString12 = "\u{1F600}-12";
check(codePointString12.length === 5, 'code point length 12');
var quoteString12 = "\"\'12";
check(quoteString12.length === 4, 'quote escape length 12');
var slashString12 = "path\\12";
check(slashString12 === 'path\\12', 'slash escape string 12');
var nullEscapeString12 = "\0x12";
check(nullEscapeString12.length === 4, 'null escape length 12');
var continuedString12 = "left\
right12";
check(continuedString12 === 'leftright12', 'line continuation string 12');
check(sameString(plainString12) === 'literal-12', 'string argument 12');
var plainString13 = "literal-13";
check(plainString13 === 'literal-13', 'plain string 13');
check(plainString13.length === 10, 'plain length 13');
var singleString13 = 'single-13';
check(singleString13 === "single-13", 'single string 13');
var newlineString13 = "row\n13";
check(newlineString13.length === 6, 'newline length 13');
var hexEscapeString13 = "\x41-13";
check(hexEscapeString13 === 'A-13', 'hex escape string 13');
var unicodeEscapeString13 = "\u0041\u0042-13";
check(unicodeEscapeString13 === 'AB-13', 'unicode escape string 13');
var codePointString13 = "\u{1F600}-13";
check(codePointString13.length === 5, 'code point length 13');
var quoteString13 = "\"\'13";
check(quoteString13.length === 4, 'quote escape length 13');
var slashString13 = "path\\13";
check(slashString13 === 'path\\13', 'slash escape string 13');
var nullEscapeString13 = "\0x13";
check(nullEscapeString13.length === 4, 'null escape length 13');
var continuedString13 = "left\
right13";
check(continuedString13 === 'leftright13', 'line continuation string 13');
check(sameString(plainString13) === 'literal-13', 'string argument 13');
var plainString14 = "literal-14";
check(plainString14 === 'literal-14', 'plain string 14');
check(plainString14.length === 10, 'plain length 14');
var singleString14 = 'single-14';
check(singleString14 === "single-14", 'single string 14');
var newlineString14 = "row\n14";
check(newlineString14.length === 6, 'newline length 14');
var hexEscapeString14 = "\x41-14";
check(hexEscapeString14 === 'A-14', 'hex escape string 14');
var unicodeEscapeString14 = "\u0041\u0042-14";
check(unicodeEscapeString14 === 'AB-14', 'unicode escape string 14');
var codePointString14 = "\u{1F600}-14";
check(codePointString14.length === 5, 'code point length 14');
var quoteString14 = "\"\'14";
check(quoteString14.length === 4, 'quote escape length 14');
var slashString14 = "path\\14";
check(slashString14 === 'path\\14', 'slash escape string 14');
var nullEscapeString14 = "\0x14";
check(nullEscapeString14.length === 4, 'null escape length 14');
var continuedString14 = "left\
right14";
check(continuedString14 === 'leftright14', 'line continuation string 14');
check(sameString(plainString14) === 'literal-14', 'string argument 14');
var plainString15 = "literal-15";
check(plainString15 === 'literal-15', 'plain string 15');
check(plainString15.length === 10, 'plain length 15');
var singleString15 = 'single-15';
check(singleString15 === "single-15", 'single string 15');
var newlineString15 = "row\n15";
check(newlineString15.length === 6, 'newline length 15');
var hexEscapeString15 = "\x41-15";
check(hexEscapeString15 === 'A-15', 'hex escape string 15');
var unicodeEscapeString15 = "\u0041\u0042-15";
check(unicodeEscapeString15 === 'AB-15', 'unicode escape string 15');
var codePointString15 = "\u{1F600}-15";
check(codePointString15.length === 5, 'code point length 15');
var quoteString15 = "\"\'15";
check(quoteString15.length === 4, 'quote escape length 15');
var slashString15 = "path\\15";
check(slashString15 === 'path\\15', 'slash escape string 15');
var nullEscapeString15 = "\0x15";
check(nullEscapeString15.length === 4, 'null escape length 15');
var continuedString15 = "left\
right15";
check(continuedString15 === 'leftright15', 'line continuation string 15');
check(sameString(plainString15) === 'literal-15', 'string argument 15');
var plainString16 = "literal-16";
check(plainString16 === 'literal-16', 'plain string 16');
check(plainString16.length === 10, 'plain length 16');
var singleString16 = 'single-16';
check(singleString16 === "single-16", 'single string 16');
var newlineString16 = "row\n16";
check(newlineString16.length === 6, 'newline length 16');
var hexEscapeString16 = "\x41-16";
check(hexEscapeString16 === 'A-16', 'hex escape string 16');
var unicodeEscapeString16 = "\u0041\u0042-16";
check(unicodeEscapeString16 === 'AB-16', 'unicode escape string 16');
var codePointString16 = "\u{1F600}-16";
check(codePointString16.length === 5, 'code point length 16');
var quoteString16 = "\"\'16";
check(quoteString16.length === 4, 'quote escape length 16');
var slashString16 = "path\\16";
check(slashString16 === 'path\\16', 'slash escape string 16');
var nullEscapeString16 = "\0x16";
check(nullEscapeString16.length === 4, 'null escape length 16');
var continuedString16 = "left\
right16";
check(continuedString16 === 'leftright16', 'line continuation string 16');
check(sameString(plainString16) === 'literal-16', 'string argument 16');
var plainString17 = "literal-17";
check(plainString17 === 'literal-17', 'plain string 17');
check(plainString17.length === 10, 'plain length 17');
var singleString17 = 'single-17';
check(singleString17 === "single-17", 'single string 17');
var newlineString17 = "row\n17";
check(newlineString17.length === 6, 'newline length 17');
var hexEscapeString17 = "\x41-17";
check(hexEscapeString17 === 'A-17', 'hex escape string 17');
var unicodeEscapeString17 = "\u0041\u0042-17";
check(unicodeEscapeString17 === 'AB-17', 'unicode escape string 17');
var codePointString17 = "\u{1F600}-17";
check(codePointString17.length === 5, 'code point length 17');
var quoteString17 = "\"\'17";
check(quoteString17.length === 4, 'quote escape length 17');
var slashString17 = "path\\17";
check(slashString17 === 'path\\17', 'slash escape string 17');
var nullEscapeString17 = "\0x17";
check(nullEscapeString17.length === 4, 'null escape length 17');
var continuedString17 = "left\
right17";
check(continuedString17 === 'leftright17', 'line continuation string 17');
check(sameString(plainString17) === 'literal-17', 'string argument 17');
var plainString18 = "literal-18";
check(plainString18 === 'literal-18', 'plain string 18');
check(plainString18.length === 10, 'plain length 18');
var singleString18 = 'single-18';
check(singleString18 === "single-18", 'single string 18');
var newlineString18 = "row\n18";
check(newlineString18.length === 6, 'newline length 18');
var hexEscapeString18 = "\x41-18";
check(hexEscapeString18 === 'A-18', 'hex escape string 18');
var unicodeEscapeString18 = "\u0041\u0042-18";
check(unicodeEscapeString18 === 'AB-18', 'unicode escape string 18');
var codePointString18 = "\u{1F600}-18";
check(codePointString18.length === 5, 'code point length 18');
var quoteString18 = "\"\'18";
check(quoteString18.length === 4, 'quote escape length 18');
var slashString18 = "path\\18";
check(slashString18 === 'path\\18', 'slash escape string 18');
var nullEscapeString18 = "\0x18";
check(nullEscapeString18.length === 4, 'null escape length 18');
var continuedString18 = "left\
right18";
check(continuedString18 === 'leftright18', 'line continuation string 18');
check(sameString(plainString18) === 'literal-18', 'string argument 18');
var plainString19 = "literal-19";
check(plainString19 === 'literal-19', 'plain string 19');
check(plainString19.length === 10, 'plain length 19');
var singleString19 = 'single-19';
check(singleString19 === "single-19", 'single string 19');
var newlineString19 = "row\n19";
check(newlineString19.length === 6, 'newline length 19');
var hexEscapeString19 = "\x41-19";
check(hexEscapeString19 === 'A-19', 'hex escape string 19');
var unicodeEscapeString19 = "\u0041\u0042-19";
check(unicodeEscapeString19 === 'AB-19', 'unicode escape string 19');
var codePointString19 = "\u{1F600}-19";
check(codePointString19.length === 5, 'code point length 19');
var quoteString19 = "\"\'19";
check(quoteString19.length === 4, 'quote escape length 19');
var slashString19 = "path\\19";
check(slashString19 === 'path\\19', 'slash escape string 19');
var nullEscapeString19 = "\0x19";
check(nullEscapeString19.length === 4, 'null escape length 19');
var continuedString19 = "left\
right19";
check(continuedString19 === 'leftright19', 'line continuation string 19');
check(sameString(plainString19) === 'literal-19', 'string argument 19');
var plainString20 = "literal-20";
check(plainString20 === 'literal-20', 'plain string 20');
check(plainString20.length === 10, 'plain length 20');
var singleString20 = 'single-20';
check(singleString20 === "single-20", 'single string 20');
var newlineString20 = "row\n20";
check(newlineString20.length === 6, 'newline length 20');
var hexEscapeString20 = "\x41-20";
check(hexEscapeString20 === 'A-20', 'hex escape string 20');
var unicodeEscapeString20 = "\u0041\u0042-20";
check(unicodeEscapeString20 === 'AB-20', 'unicode escape string 20');
var codePointString20 = "\u{1F600}-20";
check(codePointString20.length === 5, 'code point length 20');
var quoteString20 = "\"\'20";
check(quoteString20.length === 4, 'quote escape length 20');
var slashString20 = "path\\20";
check(slashString20 === 'path\\20', 'slash escape string 20');
var nullEscapeString20 = "\0x20";
check(nullEscapeString20.length === 4, 'null escape length 20');
var continuedString20 = "left\
right20";
check(continuedString20 === 'leftright20', 'line continuation string 20');
check(sameString(plainString20) === 'literal-20', 'string argument 20');
var plainString21 = "literal-21";
check(plainString21 === 'literal-21', 'plain string 21');
check(plainString21.length === 10, 'plain length 21');
var singleString21 = 'single-21';
check(singleString21 === "single-21", 'single string 21');
var newlineString21 = "row\n21";
check(newlineString21.length === 6, 'newline length 21');
var hexEscapeString21 = "\x41-21";
check(hexEscapeString21 === 'A-21', 'hex escape string 21');
var unicodeEscapeString21 = "\u0041\u0042-21";
check(unicodeEscapeString21 === 'AB-21', 'unicode escape string 21');
var codePointString21 = "\u{1F600}-21";
check(codePointString21.length === 5, 'code point length 21');
var quoteString21 = "\"\'21";
check(quoteString21.length === 4, 'quote escape length 21');
var slashString21 = "path\\21";
check(slashString21 === 'path\\21', 'slash escape string 21');
var nullEscapeString21 = "\0x21";
check(nullEscapeString21.length === 4, 'null escape length 21');
var continuedString21 = "left\
right21";
check(continuedString21 === 'leftright21', 'line continuation string 21');
check(sameString(plainString21) === 'literal-21', 'string argument 21');
var plainString22 = "literal-22";
check(plainString22 === 'literal-22', 'plain string 22');
check(plainString22.length === 10, 'plain length 22');
var singleString22 = 'single-22';
check(singleString22 === "single-22", 'single string 22');
var newlineString22 = "row\n22";
check(newlineString22.length === 6, 'newline length 22');
var hexEscapeString22 = "\x41-22";
check(hexEscapeString22 === 'A-22', 'hex escape string 22');
var unicodeEscapeString22 = "\u0041\u0042-22";
check(unicodeEscapeString22 === 'AB-22', 'unicode escape string 22');
var codePointString22 = "\u{1F600}-22";
check(codePointString22.length === 5, 'code point length 22');
var quoteString22 = "\"\'22";
check(quoteString22.length === 4, 'quote escape length 22');
var slashString22 = "path\\22";
check(slashString22 === 'path\\22', 'slash escape string 22');
var nullEscapeString22 = "\0x22";
check(nullEscapeString22.length === 4, 'null escape length 22');
var continuedString22 = "left\
right22";
check(continuedString22 === 'leftright22', 'line continuation string 22');
check(sameString(plainString22) === 'literal-22', 'string argument 22');
var plainString23 = "literal-23";
check(plainString23 === 'literal-23', 'plain string 23');
check(plainString23.length === 10, 'plain length 23');
var singleString23 = 'single-23';
check(singleString23 === "single-23", 'single string 23');
var newlineString23 = "row\n23";
check(newlineString23.length === 6, 'newline length 23');
var hexEscapeString23 = "\x41-23";
check(hexEscapeString23 === 'A-23', 'hex escape string 23');
var unicodeEscapeString23 = "\u0041\u0042-23";
check(unicodeEscapeString23 === 'AB-23', 'unicode escape string 23');
var codePointString23 = "\u{1F600}-23";
check(codePointString23.length === 5, 'code point length 23');
var quoteString23 = "\"\'23";
check(quoteString23.length === 4, 'quote escape length 23');
var slashString23 = "path\\23";
check(slashString23 === 'path\\23', 'slash escape string 23');
var nullEscapeString23 = "\0x23";
check(nullEscapeString23.length === 4, 'null escape length 23');
var continuedString23 = "left\
right23";
check(continuedString23 === 'leftright23', 'line continuation string 23');
check(sameString(plainString23) === 'literal-23', 'string argument 23');
var plainString24 = "literal-24";
check(plainString24 === 'literal-24', 'plain string 24');
check(plainString24.length === 10, 'plain length 24');
var singleString24 = 'single-24';
check(singleString24 === "single-24", 'single string 24');
var newlineString24 = "row\n24";
check(newlineString24.length === 6, 'newline length 24');
var hexEscapeString24 = "\x41-24";
check(hexEscapeString24 === 'A-24', 'hex escape string 24');
var unicodeEscapeString24 = "\u0041\u0042-24";
check(unicodeEscapeString24 === 'AB-24', 'unicode escape string 24');
var codePointString24 = "\u{1F600}-24";
check(codePointString24.length === 5, 'code point length 24');
var quoteString24 = "\"\'24";
check(quoteString24.length === 4, 'quote escape length 24');
var slashString24 = "path\\24";
check(slashString24 === 'path\\24', 'slash escape string 24');
var nullEscapeString24 = "\0x24";
check(nullEscapeString24.length === 4, 'null escape length 24');
var continuedString24 = "left\
right24";
check(continuedString24 === 'leftright24', 'line continuation string 24');
check(sameString(plainString24) === 'literal-24', 'string argument 24');
var plainString25 = "literal-25";
check(plainString25 === 'literal-25', 'plain string 25');
check(plainString25.length === 10, 'plain length 25');
var singleString25 = 'single-25';
check(singleString25 === "single-25", 'single string 25');
var newlineString25 = "row\n25";
check(newlineString25.length === 6, 'newline length 25');
var hexEscapeString25 = "\x41-25";
check(hexEscapeString25 === 'A-25', 'hex escape string 25');
var unicodeEscapeString25 = "\u0041\u0042-25";
check(unicodeEscapeString25 === 'AB-25', 'unicode escape string 25');
var codePointString25 = "\u{1F600}-25";
check(codePointString25.length === 5, 'code point length 25');
var quoteString25 = "\"\'25";
check(quoteString25.length === 4, 'quote escape length 25');
var slashString25 = "path\\25";
check(slashString25 === 'path\\25', 'slash escape string 25');
var nullEscapeString25 = "\0x25";
check(nullEscapeString25.length === 4, 'null escape length 25');
var continuedString25 = "left\
right25";
check(continuedString25 === 'leftright25', 'line continuation string 25');
check(sameString(plainString25) === 'literal-25', 'string argument 25');
var plainString26 = "literal-26";
check(plainString26 === 'literal-26', 'plain string 26');
check(plainString26.length === 10, 'plain length 26');
var singleString26 = 'single-26';
check(singleString26 === "single-26", 'single string 26');
var newlineString26 = "row\n26";
check(newlineString26.length === 6, 'newline length 26');
var hexEscapeString26 = "\x41-26";
check(hexEscapeString26 === 'A-26', 'hex escape string 26');
var unicodeEscapeString26 = "\u0041\u0042-26";
check(unicodeEscapeString26 === 'AB-26', 'unicode escape string 26');
var codePointString26 = "\u{1F600}-26";
check(codePointString26.length === 5, 'code point length 26');
var quoteString26 = "\"\'26";
check(quoteString26.length === 4, 'quote escape length 26');
var slashString26 = "path\\26";
check(slashString26 === 'path\\26', 'slash escape string 26');
var nullEscapeString26 = "\0x26";
check(nullEscapeString26.length === 4, 'null escape length 26');
var continuedString26 = "left\
right26";
check(continuedString26 === 'leftright26', 'line continuation string 26');
check(sameString(plainString26) === 'literal-26', 'string argument 26');
var plainString27 = "literal-27";
check(plainString27 === 'literal-27', 'plain string 27');
check(plainString27.length === 10, 'plain length 27');
var singleString27 = 'single-27';
check(singleString27 === "single-27", 'single string 27');
var newlineString27 = "row\n27";
check(newlineString27.length === 6, 'newline length 27');
var hexEscapeString27 = "\x41-27";
check(hexEscapeString27 === 'A-27', 'hex escape string 27');
var unicodeEscapeString27 = "\u0041\u0042-27";
check(unicodeEscapeString27 === 'AB-27', 'unicode escape string 27');
var codePointString27 = "\u{1F600}-27";
check(codePointString27.length === 5, 'code point length 27');
var quoteString27 = "\"\'27";
check(quoteString27.length === 4, 'quote escape length 27');
var slashString27 = "path\\27";
check(slashString27 === 'path\\27', 'slash escape string 27');
var nullEscapeString27 = "\0x27";
check(nullEscapeString27.length === 4, 'null escape length 27');
var continuedString27 = "left\
right27";
check(continuedString27 === 'leftright27', 'line continuation string 27');
check(sameString(plainString27) === 'literal-27', 'string argument 27');
var plainString28 = "literal-28";
check(plainString28 === 'literal-28', 'plain string 28');
check(plainString28.length === 10, 'plain length 28');
var singleString28 = 'single-28';
check(singleString28 === "single-28", 'single string 28');
var newlineString28 = "row\n28";
check(newlineString28.length === 6, 'newline length 28');
var hexEscapeString28 = "\x41-28";
check(hexEscapeString28 === 'A-28', 'hex escape string 28');
var unicodeEscapeString28 = "\u0041\u0042-28";
check(unicodeEscapeString28 === 'AB-28', 'unicode escape string 28');
var codePointString28 = "\u{1F600}-28";
check(codePointString28.length === 5, 'code point length 28');
var quoteString28 = "\"\'28";
check(quoteString28.length === 4, 'quote escape length 28');
var slashString28 = "path\\28";
check(slashString28 === 'path\\28', 'slash escape string 28');
var nullEscapeString28 = "\0x28";
check(nullEscapeString28.length === 4, 'null escape length 28');
var continuedString28 = "left\
right28";
check(continuedString28 === 'leftright28', 'line continuation string 28');
check(sameString(plainString28) === 'literal-28', 'string argument 28');
var plainString29 = "literal-29";
check(plainString29 === 'literal-29', 'plain string 29');
check(plainString29.length === 10, 'plain length 29');
var singleString29 = 'single-29';
check(singleString29 === "single-29", 'single string 29');
var newlineString29 = "row\n29";
check(newlineString29.length === 6, 'newline length 29');
var hexEscapeString29 = "\x41-29";
check(hexEscapeString29 === 'A-29', 'hex escape string 29');
var unicodeEscapeString29 = "\u0041\u0042-29";
check(unicodeEscapeString29 === 'AB-29', 'unicode escape string 29');
var codePointString29 = "\u{1F600}-29";
check(codePointString29.length === 5, 'code point length 29');
var quoteString29 = "\"\'29";
check(quoteString29.length === 4, 'quote escape length 29');
var slashString29 = "path\\29";
check(slashString29 === 'path\\29', 'slash escape string 29');
var nullEscapeString29 = "\0x29";
check(nullEscapeString29.length === 4, 'null escape length 29');
var continuedString29 = "left\
right29";
check(continuedString29 === 'leftright29', 'line continuation string 29');
check(sameString(plainString29) === 'literal-29', 'string argument 29');
var plainString30 = "literal-30";
check(plainString30 === 'literal-30', 'plain string 30');
check(plainString30.length === 10, 'plain length 30');
var singleString30 = 'single-30';
check(singleString30 === "single-30", 'single string 30');
var newlineString30 = "row\n30";
check(newlineString30.length === 6, 'newline length 30');
var hexEscapeString30 = "\x41-30";
check(hexEscapeString30 === 'A-30', 'hex escape string 30');
var unicodeEscapeString30 = "\u0041\u0042-30";
check(unicodeEscapeString30 === 'AB-30', 'unicode escape string 30');
var codePointString30 = "\u{1F600}-30";
check(codePointString30.length === 5, 'code point length 30');
var quoteString30 = "\"\'30";
check(quoteString30.length === 4, 'quote escape length 30');
var slashString30 = "path\\30";
check(slashString30 === 'path\\30', 'slash escape string 30');
var nullEscapeString30 = "\0x30";
check(nullEscapeString30.length === 4, 'null escape length 30');
var continuedString30 = "left\
right30";
check(continuedString30 === 'leftright30', 'line continuation string 30');
check(sameString(plainString30) === 'literal-30', 'string argument 30');
var plainString31 = "literal-31";
check(plainString31 === 'literal-31', 'plain string 31');
check(plainString31.length === 10, 'plain length 31');
var singleString31 = 'single-31';
check(singleString31 === "single-31", 'single string 31');
var newlineString31 = "row\n31";
check(newlineString31.length === 6, 'newline length 31');
var hexEscapeString31 = "\x41-31";
check(hexEscapeString31 === 'A-31', 'hex escape string 31');
var unicodeEscapeString31 = "\u0041\u0042-31";
check(unicodeEscapeString31 === 'AB-31', 'unicode escape string 31');
var codePointString31 = "\u{1F600}-31";
check(codePointString31.length === 5, 'code point length 31');
var quoteString31 = "\"\'31";
check(quoteString31.length === 4, 'quote escape length 31');
var slashString31 = "path\\31";
check(slashString31 === 'path\\31', 'slash escape string 31');
var nullEscapeString31 = "\0x31";
check(nullEscapeString31.length === 4, 'null escape length 31');
var continuedString31 = "left\
right31";
check(continuedString31 === 'leftright31', 'line continuation string 31');
check(sameString(plainString31) === 'literal-31', 'string argument 31');
var plainString32 = "literal-32";
check(plainString32 === 'literal-32', 'plain string 32');
check(plainString32.length === 10, 'plain length 32');
var singleString32 = 'single-32';
check(singleString32 === "single-32", 'single string 32');
var newlineString32 = "row\n32";
check(newlineString32.length === 6, 'newline length 32');
var hexEscapeString32 = "\x41-32";
check(hexEscapeString32 === 'A-32', 'hex escape string 32');
var unicodeEscapeString32 = "\u0041\u0042-32";
check(unicodeEscapeString32 === 'AB-32', 'unicode escape string 32');
var codePointString32 = "\u{1F600}-32";
check(codePointString32.length === 5, 'code point length 32');
var quoteString32 = "\"\'32";
check(quoteString32.length === 4, 'quote escape length 32');
var slashString32 = "path\\32";
check(slashString32 === 'path\\32', 'slash escape string 32');
var nullEscapeString32 = "\0x32";
check(nullEscapeString32.length === 4, 'null escape length 32');
var continuedString32 = "left\
right32";
check(continuedString32 === 'leftright32', 'line continuation string 32');
check(sameString(plainString32) === 'literal-32', 'string argument 32');
var plainString33 = "literal-33";
check(plainString33 === 'literal-33', 'plain string 33');
check(plainString33.length === 10, 'plain length 33');
var singleString33 = 'single-33';
check(singleString33 === "single-33", 'single string 33');
var newlineString33 = "row\n33";
check(newlineString33.length === 6, 'newline length 33');
var hexEscapeString33 = "\x41-33";
check(hexEscapeString33 === 'A-33', 'hex escape string 33');
var unicodeEscapeString33 = "\u0041\u0042-33";
check(unicodeEscapeString33 === 'AB-33', 'unicode escape string 33');
var codePointString33 = "\u{1F600}-33";
check(codePointString33.length === 5, 'code point length 33');
var quoteString33 = "\"\'33";
check(quoteString33.length === 4, 'quote escape length 33');
var slashString33 = "path\\33";
check(slashString33 === 'path\\33', 'slash escape string 33');
var nullEscapeString33 = "\0x33";
check(nullEscapeString33.length === 4, 'null escape length 33');
var continuedString33 = "left\
right33";
check(continuedString33 === 'leftright33', 'line continuation string 33');
check(sameString(plainString33) === 'literal-33', 'string argument 33');
var plainString34 = "literal-34";
check(plainString34 === 'literal-34', 'plain string 34');
check(plainString34.length === 10, 'plain length 34');
var singleString34 = 'single-34';
check(singleString34 === "single-34", 'single string 34');
var newlineString34 = "row\n34";
check(newlineString34.length === 6, 'newline length 34');
var hexEscapeString34 = "\x41-34";
check(hexEscapeString34 === 'A-34', 'hex escape string 34');
var unicodeEscapeString34 = "\u0041\u0042-34";
check(unicodeEscapeString34 === 'AB-34', 'unicode escape string 34');
var codePointString34 = "\u{1F600}-34";
check(codePointString34.length === 5, 'code point length 34');
var quoteString34 = "\"\'34";
check(quoteString34.length === 4, 'quote escape length 34');
var slashString34 = "path\\34";
check(slashString34 === 'path\\34', 'slash escape string 34');
var nullEscapeString34 = "\0x34";
check(nullEscapeString34.length === 4, 'null escape length 34');
var continuedString34 = "left\
right34";
check(continuedString34 === 'leftright34', 'line continuation string 34');
check(sameString(plainString34) === 'literal-34', 'string argument 34');
var plainString35 = "literal-35";
check(plainString35 === 'literal-35', 'plain string 35');
check(plainString35.length === 10, 'plain length 35');
var singleString35 = 'single-35';
check(singleString35 === "single-35", 'single string 35');
var newlineString35 = "row\n35";
check(newlineString35.length === 6, 'newline length 35');
var hexEscapeString35 = "\x41-35";
check(hexEscapeString35 === 'A-35', 'hex escape string 35');
var unicodeEscapeString35 = "\u0041\u0042-35";
check(unicodeEscapeString35 === 'AB-35', 'unicode escape string 35');
var codePointString35 = "\u{1F600}-35";
check(codePointString35.length === 5, 'code point length 35');
var quoteString35 = "\"\'35";
check(quoteString35.length === 4, 'quote escape length 35');
var slashString35 = "path\\35";
check(slashString35 === 'path\\35', 'slash escape string 35');
var nullEscapeString35 = "\0x35";
check(nullEscapeString35.length === 4, 'null escape length 35');
var continuedString35 = "left\
right35";
check(continuedString35 === 'leftright35', 'line continuation string 35');
check(sameString(plainString35) === 'literal-35', 'string argument 35');
var plainString36 = "literal-36";
check(plainString36 === 'literal-36', 'plain string 36');
check(plainString36.length === 10, 'plain length 36');
var singleString36 = 'single-36';
check(singleString36 === "single-36", 'single string 36');
var newlineString36 = "row\n36";
check(newlineString36.length === 6, 'newline length 36');
var hexEscapeString36 = "\x41-36";
check(hexEscapeString36 === 'A-36', 'hex escape string 36');
var unicodeEscapeString36 = "\u0041\u0042-36";
check(unicodeEscapeString36 === 'AB-36', 'unicode escape string 36');
var codePointString36 = "\u{1F600}-36";
check(codePointString36.length === 5, 'code point length 36');
var quoteString36 = "\"\'36";
check(quoteString36.length === 4, 'quote escape length 36');
var slashString36 = "path\\36";
check(slashString36 === 'path\\36', 'slash escape string 36');
var nullEscapeString36 = "\0x36";
check(nullEscapeString36.length === 4, 'null escape length 36');
var continuedString36 = "left\
right36";
check(continuedString36 === 'leftright36', 'line continuation string 36');
check(sameString(plainString36) === 'literal-36', 'string argument 36');
var plainString37 = "literal-37";
check(plainString37 === 'literal-37', 'plain string 37');
check(plainString37.length === 10, 'plain length 37');
var singleString37 = 'single-37';
check(singleString37 === "single-37", 'single string 37');
var newlineString37 = "row\n37";
check(newlineString37.length === 6, 'newline length 37');
var hexEscapeString37 = "\x41-37";
check(hexEscapeString37 === 'A-37', 'hex escape string 37');
var unicodeEscapeString37 = "\u0041\u0042-37";
check(unicodeEscapeString37 === 'AB-37', 'unicode escape string 37');
var codePointString37 = "\u{1F600}-37";
check(codePointString37.length === 5, 'code point length 37');
var quoteString37 = "\"\'37";
check(quoteString37.length === 4, 'quote escape length 37');
var slashString37 = "path\\37";
check(slashString37 === 'path\\37', 'slash escape string 37');
var nullEscapeString37 = "\0x37";
check(nullEscapeString37.length === 4, 'null escape length 37');
var continuedString37 = "left\
right37";
check(continuedString37 === 'leftright37', 'line continuation string 37');
check(sameString(plainString37) === 'literal-37', 'string argument 37');
var plainString38 = "literal-38";
check(plainString38 === 'literal-38', 'plain string 38');
check(plainString38.length === 10, 'plain length 38');
var singleString38 = 'single-38';
check(singleString38 === "single-38", 'single string 38');
var newlineString38 = "row\n38";
check(newlineString38.length === 6, 'newline length 38');
var hexEscapeString38 = "\x41-38";
check(hexEscapeString38 === 'A-38', 'hex escape string 38');
var unicodeEscapeString38 = "\u0041\u0042-38";
check(unicodeEscapeString38 === 'AB-38', 'unicode escape string 38');
var codePointString38 = "\u{1F600}-38";
check(codePointString38.length === 5, 'code point length 38');
var quoteString38 = "\"\'38";
check(quoteString38.length === 4, 'quote escape length 38');
var slashString38 = "path\\38";
check(slashString38 === 'path\\38', 'slash escape string 38');
var nullEscapeString38 = "\0x38";
check(nullEscapeString38.length === 4, 'null escape length 38');
var continuedString38 = "left\
right38";
check(continuedString38 === 'leftright38', 'line continuation string 38');
check(sameString(plainString38) === 'literal-38', 'string argument 38');
var plainString39 = "literal-39";
check(plainString39 === 'literal-39', 'plain string 39');
check(plainString39.length === 10, 'plain length 39');
var singleString39 = 'single-39';
check(singleString39 === "single-39", 'single string 39');
var newlineString39 = "row\n39";
check(newlineString39.length === 6, 'newline length 39');
var hexEscapeString39 = "\x41-39";
check(hexEscapeString39 === 'A-39', 'hex escape string 39');
var unicodeEscapeString39 = "\u0041\u0042-39";
check(unicodeEscapeString39 === 'AB-39', 'unicode escape string 39');
var codePointString39 = "\u{1F600}-39";
check(codePointString39.length === 5, 'code point length 39');
var quoteString39 = "\"\'39";
check(quoteString39.length === 4, 'quote escape length 39');
var slashString39 = "path\\39";
check(slashString39 === 'path\\39', 'slash escape string 39');
var nullEscapeString39 = "\0x39";
check(nullEscapeString39.length === 4, 'null escape length 39');
var continuedString39 = "left\
right39";
check(continuedString39 === 'leftright39', 'line continuation string 39');
check(sameString(plainString39) === 'literal-39', 'string argument 39');
var plainString40 = "literal-40";
check(plainString40 === 'literal-40', 'plain string 40');
check(plainString40.length === 10, 'plain length 40');
var singleString40 = 'single-40';
check(singleString40 === "single-40", 'single string 40');
var newlineString40 = "row\n40";
check(newlineString40.length === 6, 'newline length 40');
var hexEscapeString40 = "\x41-40";
check(hexEscapeString40 === 'A-40', 'hex escape string 40');
var unicodeEscapeString40 = "\u0041\u0042-40";
check(unicodeEscapeString40 === 'AB-40', 'unicode escape string 40');
var codePointString40 = "\u{1F600}-40";
check(codePointString40.length === 5, 'code point length 40');
var quoteString40 = "\"\'40";
check(quoteString40.length === 4, 'quote escape length 40');
var slashString40 = "path\\40";
check(slashString40 === 'path\\40', 'slash escape string 40');
var nullEscapeString40 = "\0x40";
check(nullEscapeString40.length === 4, 'null escape length 40');
var continuedString40 = "left\
right40";
check(continuedString40 === 'leftright40', 'line continuation string 40');
check(sameString(plainString40) === 'literal-40', 'string argument 40');
var plainString41 = "literal-41";
check(plainString41 === 'literal-41', 'plain string 41');
check(plainString41.length === 10, 'plain length 41');
var singleString41 = 'single-41';
check(singleString41 === "single-41", 'single string 41');
var newlineString41 = "row\n41";
check(newlineString41.length === 6, 'newline length 41');
var hexEscapeString41 = "\x41-41";
check(hexEscapeString41 === 'A-41', 'hex escape string 41');
var unicodeEscapeString41 = "\u0041\u0042-41";
check(unicodeEscapeString41 === 'AB-41', 'unicode escape string 41');
var codePointString41 = "\u{1F600}-41";
check(codePointString41.length === 5, 'code point length 41');
var quoteString41 = "\"\'41";
check(quoteString41.length === 4, 'quote escape length 41');
var slashString41 = "path\\41";
check(slashString41 === 'path\\41', 'slash escape string 41');
var nullEscapeString41 = "\0x41";
check(nullEscapeString41.length === 4, 'null escape length 41');
var continuedString41 = "left\
right41";
check(continuedString41 === 'leftright41', 'line continuation string 41');
check(sameString(plainString41) === 'literal-41', 'string argument 41');
var plainString42 = "literal-42";
check(plainString42 === 'literal-42', 'plain string 42');
check(plainString42.length === 10, 'plain length 42');
var singleString42 = 'single-42';
check(singleString42 === "single-42", 'single string 42');
var newlineString42 = "row\n42";
check(newlineString42.length === 6, 'newline length 42');
var hexEscapeString42 = "\x41-42";
check(hexEscapeString42 === 'A-42', 'hex escape string 42');
var unicodeEscapeString42 = "\u0041\u0042-42";
check(unicodeEscapeString42 === 'AB-42', 'unicode escape string 42');
var codePointString42 = "\u{1F600}-42";
check(codePointString42.length === 5, 'code point length 42');
var quoteString42 = "\"\'42";
check(quoteString42.length === 4, 'quote escape length 42');
var slashString42 = "path\\42";
check(slashString42 === 'path\\42', 'slash escape string 42');
var nullEscapeString42 = "\0x42";
check(nullEscapeString42.length === 4, 'null escape length 42');
var continuedString42 = "left\
right42";
check(continuedString42 === 'leftright42', 'line continuation string 42');
check(sameString(plainString42) === 'literal-42', 'string argument 42');
var plainString43 = "literal-43";
check(plainString43 === 'literal-43', 'plain string 43');
check(plainString43.length === 10, 'plain length 43');
var singleString43 = 'single-43';
check(singleString43 === "single-43", 'single string 43');
var newlineString43 = "row\n43";
check(newlineString43.length === 6, 'newline length 43');
var hexEscapeString43 = "\x41-43";
check(hexEscapeString43 === 'A-43', 'hex escape string 43');
var unicodeEscapeString43 = "\u0041\u0042-43";
check(unicodeEscapeString43 === 'AB-43', 'unicode escape string 43');
var codePointString43 = "\u{1F600}-43";
check(codePointString43.length === 5, 'code point length 43');
var quoteString43 = "\"\'43";
check(quoteString43.length === 4, 'quote escape length 43');
var slashString43 = "path\\43";
check(slashString43 === 'path\\43', 'slash escape string 43');
var nullEscapeString43 = "\0x43";
check(nullEscapeString43.length === 4, 'null escape length 43');
var continuedString43 = "left\
right43";
check(continuedString43 === 'leftright43', 'line continuation string 43');
check(sameString(plainString43) === 'literal-43', 'string argument 43');
console.log('string-literals-evaluate-sv stress ' + score);
