// behavior: dot-access-uses-identifier-stringvalue
// expected: pass
// goal: script
// size: standard
// variant: script.sloppy

var dotScore = 0;
function dotCheck(condition, label) {
if (!condition) {
throw label;
}
dotScore = dotScore + 1;
return true;
}
function makeDotObject(seed) {
return { alpha: seed, beta: seed + 1, while: seed + 2, method: function(delta) { return this.alpha + this.beta + delta; } };
}
var dotTotal = 0;
var dotObj0 = makeDotObject(0);
dotCheck(dotObj0.alpha === 0, "dot alpha initial 0");
dotCheck(dotObj0.\u0061lpha === 0, "dot escaped alpha 0");
dotObj0.alpha = dotObj0.alpha + 10;
dotCheck(dotObj0.alpha === 10, "dot alpha write 0");
dotObj0.if = 20;
dotObj0.for = dotObj0.if + 1;
dotObj0.class = dotObj0.for + 1;
dotCheck(dotObj0.while === 2, "dot reserved while 0");
dotCheck(dotObj0.if === 20, "dot reserved if 0");
dotCheck(dotObj0.for === 21 && dotObj0.class === 22, "dot reserved chain 0");
var dotCall0 = dotObj0.method(5);
dotCheck(dotCall0 === dotObj0.alpha + dotObj0.beta + 5, "dot method this 0");
dotTotal = dotTotal + dotObj0.if + dotObj0.for + dotObj0.class + dotCall0;
var dotObj1 = makeDotObject(1);
dotCheck(dotObj1.alpha === 1, "dot alpha initial 1");
dotCheck(dotObj1.\u0061lpha === 1, "dot escaped alpha 1");
dotObj1.alpha = dotObj1.alpha + 11;
dotCheck(dotObj1.alpha === 12, "dot alpha write 1");
dotObj1.if = 21;
dotObj1.for = dotObj1.if + 1;
dotObj1.class = dotObj1.for + 1;
dotCheck(dotObj1.while === 3, "dot reserved while 1");
dotCheck(dotObj1.if === 21, "dot reserved if 1");
dotCheck(dotObj1.for === 22 && dotObj1.class === 23, "dot reserved chain 1");
var dotCall1 = dotObj1.method(6);
dotCheck(dotCall1 === dotObj1.alpha + dotObj1.beta + 6, "dot method this 1");
dotTotal = dotTotal + dotObj1.if + dotObj1.for + dotObj1.class + dotCall1;
var dotObj2 = makeDotObject(2);
dotCheck(dotObj2.alpha === 2, "dot alpha initial 2");
dotCheck(dotObj2.\u0061lpha === 2, "dot escaped alpha 2");
dotObj2.alpha = dotObj2.alpha + 12;
dotCheck(dotObj2.alpha === 14, "dot alpha write 2");
dotObj2.if = 22;
dotObj2.for = dotObj2.if + 1;
dotObj2.class = dotObj2.for + 1;
dotCheck(dotObj2.while === 4, "dot reserved while 2");
dotCheck(dotObj2.if === 22, "dot reserved if 2");
dotCheck(dotObj2.for === 23 && dotObj2.class === 24, "dot reserved chain 2");
var dotCall2 = dotObj2.method(7);
dotCheck(dotCall2 === dotObj2.alpha + dotObj2.beta + 7, "dot method this 2");
dotTotal = dotTotal + dotObj2.if + dotObj2.for + dotObj2.class + dotCall2;
var dotObj3 = makeDotObject(3);
dotCheck(dotObj3.alpha === 3, "dot alpha initial 3");
dotCheck(dotObj3.\u0061lpha === 3, "dot escaped alpha 3");
dotObj3.alpha = dotObj3.alpha + 13;
dotCheck(dotObj3.alpha === 16, "dot alpha write 3");
dotObj3.if = 23;
dotObj3.for = dotObj3.if + 1;
dotObj3.class = dotObj3.for + 1;
dotCheck(dotObj3.while === 5, "dot reserved while 3");
dotCheck(dotObj3.if === 23, "dot reserved if 3");
dotCheck(dotObj3.for === 24 && dotObj3.class === 25, "dot reserved chain 3");
var dotCall3 = dotObj3.method(8);
dotCheck(dotCall3 === dotObj3.alpha + dotObj3.beta + 8, "dot method this 3");
dotTotal = dotTotal + dotObj3.if + dotObj3.for + dotObj3.class + dotCall3;
var dotObj4 = makeDotObject(4);
dotCheck(dotObj4.alpha === 4, "dot alpha initial 4");
dotCheck(dotObj4.\u0061lpha === 4, "dot escaped alpha 4");
dotObj4.alpha = dotObj4.alpha + 14;
dotCheck(dotObj4.alpha === 18, "dot alpha write 4");
dotObj4.if = 24;
dotObj4.for = dotObj4.if + 1;
dotObj4.class = dotObj4.for + 1;
dotCheck(dotObj4.while === 6, "dot reserved while 4");
dotCheck(dotObj4.if === 24, "dot reserved if 4");
dotCheck(dotObj4.for === 25 && dotObj4.class === 26, "dot reserved chain 4");
var dotCall4 = dotObj4.method(9);
dotCheck(dotCall4 === dotObj4.alpha + dotObj4.beta + 9, "dot method this 4");
dotTotal = dotTotal + dotObj4.if + dotObj4.for + dotObj4.class + dotCall4;
var dotObj5 = makeDotObject(5);
dotCheck(dotObj5.alpha === 5, "dot alpha initial 5");
dotCheck(dotObj5.\u0061lpha === 5, "dot escaped alpha 5");
dotObj5.alpha = dotObj5.alpha + 15;
dotCheck(dotObj5.alpha === 20, "dot alpha write 5");
dotObj5.if = 25;
dotObj5.for = dotObj5.if + 1;
dotObj5.class = dotObj5.for + 1;
dotCheck(dotObj5.while === 7, "dot reserved while 5");
dotCheck(dotObj5.if === 25, "dot reserved if 5");
dotCheck(dotObj5.for === 26 && dotObj5.class === 27, "dot reserved chain 5");
var dotCall5 = dotObj5.method(10);
dotCheck(dotCall5 === dotObj5.alpha + dotObj5.beta + 10, "dot method this 5");
dotTotal = dotTotal + dotObj5.if + dotObj5.for + dotObj5.class + dotCall5;
var dotObj6 = makeDotObject(6);
dotCheck(dotObj6.alpha === 6, "dot alpha initial 6");
dotCheck(dotObj6.\u0061lpha === 6, "dot escaped alpha 6");
dotObj6.alpha = dotObj6.alpha + 16;
dotCheck(dotObj6.alpha === 22, "dot alpha write 6");
dotObj6.if = 26;
dotObj6.for = dotObj6.if + 1;
dotObj6.class = dotObj6.for + 1;
dotCheck(dotObj6.while === 8, "dot reserved while 6");
dotCheck(dotObj6.if === 26, "dot reserved if 6");
dotCheck(dotObj6.for === 27 && dotObj6.class === 28, "dot reserved chain 6");
var dotCall6 = dotObj6.method(11);
dotCheck(dotCall6 === dotObj6.alpha + dotObj6.beta + 11, "dot method this 6");
dotTotal = dotTotal + dotObj6.if + dotObj6.for + dotObj6.class + dotCall6;
var dotObj7 = makeDotObject(7);
dotCheck(dotObj7.alpha === 7, "dot alpha initial 7");
dotCheck(dotObj7.\u0061lpha === 7, "dot escaped alpha 7");
dotObj7.alpha = dotObj7.alpha + 17;
dotCheck(dotObj7.alpha === 24, "dot alpha write 7");
dotObj7.if = 27;
dotObj7.for = dotObj7.if + 1;
dotObj7.class = dotObj7.for + 1;
dotCheck(dotObj7.while === 9, "dot reserved while 7");
dotCheck(dotObj7.if === 27, "dot reserved if 7");
dotCheck(dotObj7.for === 28 && dotObj7.class === 29, "dot reserved chain 7");
var dotCall7 = dotObj7.method(12);
dotCheck(dotCall7 === dotObj7.alpha + dotObj7.beta + 12, "dot method this 7");
dotTotal = dotTotal + dotObj7.if + dotObj7.for + dotObj7.class + dotCall7;
var dotObj8 = makeDotObject(8);
dotCheck(dotObj8.alpha === 8, "dot alpha initial 8");
dotCheck(dotObj8.\u0061lpha === 8, "dot escaped alpha 8");
dotObj8.alpha = dotObj8.alpha + 18;
dotCheck(dotObj8.alpha === 26, "dot alpha write 8");
dotObj8.if = 28;
dotObj8.for = dotObj8.if + 1;
dotObj8.class = dotObj8.for + 1;
dotCheck(dotObj8.while === 10, "dot reserved while 8");
dotCheck(dotObj8.if === 28, "dot reserved if 8");
dotCheck(dotObj8.for === 29 && dotObj8.class === 30, "dot reserved chain 8");
var dotCall8 = dotObj8.method(13);
dotCheck(dotCall8 === dotObj8.alpha + dotObj8.beta + 13, "dot method this 8");
dotTotal = dotTotal + dotObj8.if + dotObj8.for + dotObj8.class + dotCall8;
var dotObj9 = makeDotObject(9);
dotCheck(dotObj9.alpha === 9, "dot alpha initial 9");
dotCheck(dotObj9.\u0061lpha === 9, "dot escaped alpha 9");
dotObj9.alpha = dotObj9.alpha + 19;
dotCheck(dotObj9.alpha === 28, "dot alpha write 9");
dotObj9.if = 29;
dotObj9.for = dotObj9.if + 1;
dotObj9.class = dotObj9.for + 1;
dotCheck(dotObj9.while === 11, "dot reserved while 9");
dotCheck(dotObj9.if === 29, "dot reserved if 9");
dotCheck(dotObj9.for === 30 && dotObj9.class === 31, "dot reserved chain 9");
var dotCall9 = dotObj9.method(14);
dotCheck(dotCall9 === dotObj9.alpha + dotObj9.beta + 14, "dot method this 9");
dotTotal = dotTotal + dotObj9.if + dotObj9.for + dotObj9.class + dotCall9;
var dotObj10 = makeDotObject(10);
dotCheck(dotObj10.alpha === 10, "dot alpha initial 10");
dotCheck(dotObj10.\u0061lpha === 10, "dot escaped alpha 10");
dotObj10.alpha = dotObj10.alpha + 20;
dotCheck(dotObj10.alpha === 30, "dot alpha write 10");
dotObj10.if = 30;
dotObj10.for = dotObj10.if + 1;
dotObj10.class = dotObj10.for + 1;
dotCheck(dotObj10.while === 12, "dot reserved while 10");
dotCheck(dotObj10.if === 30, "dot reserved if 10");
dotCheck(dotObj10.for === 31 && dotObj10.class === 32, "dot reserved chain 10");
var dotCall10 = dotObj10.method(15);
dotCheck(dotCall10 === dotObj10.alpha + dotObj10.beta + 15, "dot method this 10");
dotTotal = dotTotal + dotObj10.if + dotObj10.for + dotObj10.class + dotCall10;
var dotObj11 = makeDotObject(11);
dotCheck(dotObj11.alpha === 11, "dot alpha initial 11");
dotCheck(dotObj11.\u0061lpha === 11, "dot escaped alpha 11");
dotObj11.alpha = dotObj11.alpha + 21;
dotCheck(dotObj11.alpha === 32, "dot alpha write 11");
dotObj11.if = 31;
dotObj11.for = dotObj11.if + 1;
dotObj11.class = dotObj11.for + 1;
dotCheck(dotObj11.while === 13, "dot reserved while 11");
dotCheck(dotObj11.if === 31, "dot reserved if 11");
dotCheck(dotObj11.for === 32 && dotObj11.class === 33, "dot reserved chain 11");
var dotCall11 = dotObj11.method(16);
dotCheck(dotCall11 === dotObj11.alpha + dotObj11.beta + 16, "dot method this 11");
dotTotal = dotTotal + dotObj11.if + dotObj11.for + dotObj11.class + dotCall11;
dotCheck(dotScore === 84, "dot score");
dotCheck(dotTotal > 0, "dot accumulated result");
