// behavior: identifier-key-is-stringvalue
// expected: pass
// goal: script
// size: standard
// variant: script.sloppy

var identScore = 0;
function identCheck(condition, label) {
if (!condition) {
throw label;
}
identScore = identScore + 1;
return true;
}
var identTotal = 0;
var identObj0 = {};
identObj0.if = 1;
identObj0.enum = identObj0.if + 1;
identObj0.true = identObj0.enum + 1;
identObj0.null = identObj0.true + 1;
identObj0.public = identObj0.null + 1;
identCheck(identObj0.\u0069f === 1, "escaped reserved if 0");
identCheck(identObj0.enum === 2, "reserved enum 0");
identCheck(identObj0.true === 3, "reserved true 0");
identCheck(identObj0.null === 4, "reserved null 0");
identCheck(identObj0.\u0070ublic === 5, "escaped public 0");
identTotal = identTotal + identObj0.if + identObj0.enum + identObj0.true + identObj0.null + identObj0.public;
var identObj1 = {};
identObj1.if = 2;
identObj1.enum = identObj1.if + 1;
identObj1.true = identObj1.enum + 1;
identObj1.null = identObj1.true + 1;
identObj1.public = identObj1.null + 1;
identCheck(identObj1.\u0069f === 2, "escaped reserved if 1");
identCheck(identObj1.enum === 3, "reserved enum 1");
identCheck(identObj1.true === 4, "reserved true 1");
identCheck(identObj1.null === 5, "reserved null 1");
identCheck(identObj1.\u0070ublic === 6, "escaped public 1");
identTotal = identTotal + identObj1.if + identObj1.enum + identObj1.true + identObj1.null + identObj1.public;
var identObj2 = {};
identObj2.if = 3;
identObj2.enum = identObj2.if + 1;
identObj2.true = identObj2.enum + 1;
identObj2.null = identObj2.true + 1;
identObj2.public = identObj2.null + 1;
identCheck(identObj2.\u0069f === 3, "escaped reserved if 2");
identCheck(identObj2.enum === 4, "reserved enum 2");
identCheck(identObj2.true === 5, "reserved true 2");
identCheck(identObj2.null === 6, "reserved null 2");
identCheck(identObj2.\u0070ublic === 7, "escaped public 2");
identTotal = identTotal + identObj2.if + identObj2.enum + identObj2.true + identObj2.null + identObj2.public;
var identObj3 = {};
identObj3.if = 4;
identObj3.enum = identObj3.if + 1;
identObj3.true = identObj3.enum + 1;
identObj3.null = identObj3.true + 1;
identObj3.public = identObj3.null + 1;
identCheck(identObj3.\u0069f === 4, "escaped reserved if 3");
identCheck(identObj3.enum === 5, "reserved enum 3");
identCheck(identObj3.true === 6, "reserved true 3");
identCheck(identObj3.null === 7, "reserved null 3");
identCheck(identObj3.\u0070ublic === 8, "escaped public 3");
identTotal = identTotal + identObj3.if + identObj3.enum + identObj3.true + identObj3.null + identObj3.public;
var identObj4 = {};
identObj4.if = 5;
identObj4.enum = identObj4.if + 1;
identObj4.true = identObj4.enum + 1;
identObj4.null = identObj4.true + 1;
identObj4.public = identObj4.null + 1;
identCheck(identObj4.\u0069f === 5, "escaped reserved if 4");
identCheck(identObj4.enum === 6, "reserved enum 4");
identCheck(identObj4.true === 7, "reserved true 4");
identCheck(identObj4.null === 8, "reserved null 4");
identCheck(identObj4.\u0070ublic === 9, "escaped public 4");
identTotal = identTotal + identObj4.if + identObj4.enum + identObj4.true + identObj4.null + identObj4.public;
var identObj5 = {};
identObj5.if = 6;
identObj5.enum = identObj5.if + 1;
identObj5.true = identObj5.enum + 1;
identObj5.null = identObj5.true + 1;
identObj5.public = identObj5.null + 1;
identCheck(identObj5.\u0069f === 6, "escaped reserved if 5");
identCheck(identObj5.enum === 7, "reserved enum 5");
identCheck(identObj5.true === 8, "reserved true 5");
identCheck(identObj5.null === 9, "reserved null 5");
identCheck(identObj5.\u0070ublic === 10, "escaped public 5");
identTotal = identTotal + identObj5.if + identObj5.enum + identObj5.true + identObj5.null + identObj5.public;
var identObj6 = {};
identObj6.if = 7;
identObj6.enum = identObj6.if + 1;
identObj6.true = identObj6.enum + 1;
identObj6.null = identObj6.true + 1;
identObj6.public = identObj6.null + 1;
identCheck(identObj6.\u0069f === 7, "escaped reserved if 6");
identCheck(identObj6.enum === 8, "reserved enum 6");
identCheck(identObj6.true === 9, "reserved true 6");
identCheck(identObj6.null === 10, "reserved null 6");
identCheck(identObj6.\u0070ublic === 11, "escaped public 6");
identTotal = identTotal + identObj6.if + identObj6.enum + identObj6.true + identObj6.null + identObj6.public;
var identObj7 = {};
identObj7.if = 8;
identObj7.enum = identObj7.if + 1;
identObj7.true = identObj7.enum + 1;
identObj7.null = identObj7.true + 1;
identObj7.public = identObj7.null + 1;
identCheck(identObj7.\u0069f === 8, "escaped reserved if 7");
identCheck(identObj7.enum === 9, "reserved enum 7");
identCheck(identObj7.true === 10, "reserved true 7");
identCheck(identObj7.null === 11, "reserved null 7");
identCheck(identObj7.\u0070ublic === 12, "escaped public 7");
identTotal = identTotal + identObj7.if + identObj7.enum + identObj7.true + identObj7.null + identObj7.public;
var identObj8 = {};
identObj8.if = 9;
identObj8.enum = identObj8.if + 1;
identObj8.true = identObj8.enum + 1;
identObj8.null = identObj8.true + 1;
identObj8.public = identObj8.null + 1;
identCheck(identObj8.\u0069f === 9, "escaped reserved if 8");
identCheck(identObj8.enum === 10, "reserved enum 8");
identCheck(identObj8.true === 11, "reserved true 8");
identCheck(identObj8.null === 12, "reserved null 8");
identCheck(identObj8.\u0070ublic === 13, "escaped public 8");
identTotal = identTotal + identObj8.if + identObj8.enum + identObj8.true + identObj8.null + identObj8.public;
var identObj9 = {};
identObj9.if = 10;
identObj9.enum = identObj9.if + 1;
identObj9.true = identObj9.enum + 1;
identObj9.null = identObj9.true + 1;
identObj9.public = identObj9.null + 1;
identCheck(identObj9.\u0069f === 10, "escaped reserved if 9");
identCheck(identObj9.enum === 11, "reserved enum 9");
identCheck(identObj9.true === 12, "reserved true 9");
identCheck(identObj9.null === 13, "reserved null 9");
identCheck(identObj9.\u0070ublic === 14, "escaped public 9");
identTotal = identTotal + identObj9.if + identObj9.enum + identObj9.true + identObj9.null + identObj9.public;
var identObj10 = {};
identObj10.if = 11;
identObj10.enum = identObj10.if + 1;
identObj10.true = identObj10.enum + 1;
identObj10.null = identObj10.true + 1;
identObj10.public = identObj10.null + 1;
identCheck(identObj10.\u0069f === 11, "escaped reserved if 10");
identCheck(identObj10.enum === 12, "reserved enum 10");
identCheck(identObj10.true === 13, "reserved true 10");
identCheck(identObj10.null === 14, "reserved null 10");
identCheck(identObj10.\u0070ublic === 15, "escaped public 10");
identTotal = identTotal + identObj10.if + identObj10.enum + identObj10.true + identObj10.null + identObj10.public;
var identObj11 = {};
identObj11.if = 12;
identObj11.enum = identObj11.if + 1;
identObj11.true = identObj11.enum + 1;
identObj11.null = identObj11.true + 1;
identObj11.public = identObj11.null + 1;
identCheck(identObj11.\u0069f === 12, "escaped reserved if 11");
identCheck(identObj11.enum === 13, "reserved enum 11");
identCheck(identObj11.true === 14, "reserved true 11");
identCheck(identObj11.null === 15, "reserved null 11");
identCheck(identObj11.\u0070ublic === 16, "escaped public 11");
identTotal = identTotal + identObj11.if + identObj11.enum + identObj11.true + identObj11.null + identObj11.public;
identCheck(identScore === 60, "identifier score");
identCheck(identTotal > 0, "identifier accumulated result");
