// behavior: computed-proto-key-is-data-property
// expected: pass
// goal: script
// size: stress
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}

var protoLiteral0 = { inheritedMarker: 10 };
var literalProtoObj0 = { __proto__: protoLiteral0, ownMarker: 10 + 1 };
check(Object.getPrototypeOf(literalProtoObj0) === protoLiteral0, "literal proto prototype 0");
check(literalProtoObj0.inheritedMarker === 10, "literal proto inherited 0");
var protoComputed0 = { dataMarker: 10 + 2 };
var computedProtoObj0 = { ["__proto__"]: protoComputed0, ownMarker: 10 + 3 };
check(Object.getPrototypeOf(computedProtoObj0) === Object.prototype, "computed proto prototype 0");
check(computedProtoObj0.__proto__ === protoComputed0, "computed proto own data 0");
check(computedProtoObj0.ownMarker === 10 + 3, "computed proto other data 0");
var ignoredProtoObj0 = { __proto__: 10, regular0: 10 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj0) === Object.prototype, "non object proto ignored 0");
check(ignoredProtoObj0.regular0 === 10 + 4, "non object proto regular 0");

var protoLiteral1 = { inheritedMarker: 15 };
var literalProtoObj1 = { __proto__: protoLiteral1, ownMarker: 15 + 1 };
check(Object.getPrototypeOf(literalProtoObj1) === protoLiteral1, "literal proto prototype 1");
check(literalProtoObj1.inheritedMarker === 15, "literal proto inherited 1");
var protoComputed1 = { dataMarker: 15 + 2 };
var computedProtoObj1 = { ["__proto__"]: protoComputed1, ownMarker: 15 + 3 };
check(Object.getPrototypeOf(computedProtoObj1) === Object.prototype, "computed proto prototype 1");
check(computedProtoObj1.__proto__ === protoComputed1, "computed proto own data 1");
check(computedProtoObj1.ownMarker === 15 + 3, "computed proto other data 1");
var ignoredProtoObj1 = { __proto__: 15, regular1: 15 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj1) === Object.prototype, "non object proto ignored 1");
check(ignoredProtoObj1.regular1 === 15 + 4, "non object proto regular 1");

var protoLiteral2 = { inheritedMarker: 20 };
var literalProtoObj2 = { __proto__: protoLiteral2, ownMarker: 20 + 1 };
check(Object.getPrototypeOf(literalProtoObj2) === protoLiteral2, "literal proto prototype 2");
check(literalProtoObj2.inheritedMarker === 20, "literal proto inherited 2");
var protoComputed2 = { dataMarker: 20 + 2 };
var computedProtoObj2 = { ["__proto__"]: protoComputed2, ownMarker: 20 + 3 };
check(Object.getPrototypeOf(computedProtoObj2) === Object.prototype, "computed proto prototype 2");
check(computedProtoObj2.__proto__ === protoComputed2, "computed proto own data 2");
check(computedProtoObj2.ownMarker === 20 + 3, "computed proto other data 2");
var ignoredProtoObj2 = { __proto__: 20, regular2: 20 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj2) === Object.prototype, "non object proto ignored 2");
check(ignoredProtoObj2.regular2 === 20 + 4, "non object proto regular 2");

var protoLiteral3 = { inheritedMarker: 25 };
var literalProtoObj3 = { __proto__: protoLiteral3, ownMarker: 25 + 1 };
check(Object.getPrototypeOf(literalProtoObj3) === protoLiteral3, "literal proto prototype 3");
check(literalProtoObj3.inheritedMarker === 25, "literal proto inherited 3");
var protoComputed3 = { dataMarker: 25 + 2 };
var computedProtoObj3 = { ["__proto__"]: protoComputed3, ownMarker: 25 + 3 };
check(Object.getPrototypeOf(computedProtoObj3) === Object.prototype, "computed proto prototype 3");
check(computedProtoObj3.__proto__ === protoComputed3, "computed proto own data 3");
check(computedProtoObj3.ownMarker === 25 + 3, "computed proto other data 3");
var ignoredProtoObj3 = { __proto__: 25, regular3: 25 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj3) === Object.prototype, "non object proto ignored 3");
check(ignoredProtoObj3.regular3 === 25 + 4, "non object proto regular 3");

var protoLiteral4 = { inheritedMarker: 30 };
var literalProtoObj4 = { __proto__: protoLiteral4, ownMarker: 30 + 1 };
check(Object.getPrototypeOf(literalProtoObj4) === protoLiteral4, "literal proto prototype 4");
check(literalProtoObj4.inheritedMarker === 30, "literal proto inherited 4");
var protoComputed4 = { dataMarker: 30 + 2 };
var computedProtoObj4 = { ["__proto__"]: protoComputed4, ownMarker: 30 + 3 };
check(Object.getPrototypeOf(computedProtoObj4) === Object.prototype, "computed proto prototype 4");
check(computedProtoObj4.__proto__ === protoComputed4, "computed proto own data 4");
check(computedProtoObj4.ownMarker === 30 + 3, "computed proto other data 4");
var ignoredProtoObj4 = { __proto__: 30, regular4: 30 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj4) === Object.prototype, "non object proto ignored 4");
check(ignoredProtoObj4.regular4 === 30 + 4, "non object proto regular 4");

var protoLiteral5 = { inheritedMarker: 35 };
var literalProtoObj5 = { __proto__: protoLiteral5, ownMarker: 35 + 1 };
check(Object.getPrototypeOf(literalProtoObj5) === protoLiteral5, "literal proto prototype 5");
check(literalProtoObj5.inheritedMarker === 35, "literal proto inherited 5");
var protoComputed5 = { dataMarker: 35 + 2 };
var computedProtoObj5 = { ["__proto__"]: protoComputed5, ownMarker: 35 + 3 };
check(Object.getPrototypeOf(computedProtoObj5) === Object.prototype, "computed proto prototype 5");
check(computedProtoObj5.__proto__ === protoComputed5, "computed proto own data 5");
check(computedProtoObj5.ownMarker === 35 + 3, "computed proto other data 5");
var ignoredProtoObj5 = { __proto__: 35, regular5: 35 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj5) === Object.prototype, "non object proto ignored 5");
check(ignoredProtoObj5.regular5 === 35 + 4, "non object proto regular 5");

var protoLiteral6 = { inheritedMarker: 40 };
var literalProtoObj6 = { __proto__: protoLiteral6, ownMarker: 40 + 1 };
check(Object.getPrototypeOf(literalProtoObj6) === protoLiteral6, "literal proto prototype 6");
check(literalProtoObj6.inheritedMarker === 40, "literal proto inherited 6");
var protoComputed6 = { dataMarker: 40 + 2 };
var computedProtoObj6 = { ["__proto__"]: protoComputed6, ownMarker: 40 + 3 };
check(Object.getPrototypeOf(computedProtoObj6) === Object.prototype, "computed proto prototype 6");
check(computedProtoObj6.__proto__ === protoComputed6, "computed proto own data 6");
check(computedProtoObj6.ownMarker === 40 + 3, "computed proto other data 6");
var ignoredProtoObj6 = { __proto__: 40, regular6: 40 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj6) === Object.prototype, "non object proto ignored 6");
check(ignoredProtoObj6.regular6 === 40 + 4, "non object proto regular 6");

var protoLiteral7 = { inheritedMarker: 45 };
var literalProtoObj7 = { __proto__: protoLiteral7, ownMarker: 45 + 1 };
check(Object.getPrototypeOf(literalProtoObj7) === protoLiteral7, "literal proto prototype 7");
check(literalProtoObj7.inheritedMarker === 45, "literal proto inherited 7");
var protoComputed7 = { dataMarker: 45 + 2 };
var computedProtoObj7 = { ["__proto__"]: protoComputed7, ownMarker: 45 + 3 };
check(Object.getPrototypeOf(computedProtoObj7) === Object.prototype, "computed proto prototype 7");
check(computedProtoObj7.__proto__ === protoComputed7, "computed proto own data 7");
check(computedProtoObj7.ownMarker === 45 + 3, "computed proto other data 7");
var ignoredProtoObj7 = { __proto__: 45, regular7: 45 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj7) === Object.prototype, "non object proto ignored 7");
check(ignoredProtoObj7.regular7 === 45 + 4, "non object proto regular 7");

var protoLiteral8 = { inheritedMarker: 50 };
var literalProtoObj8 = { __proto__: protoLiteral8, ownMarker: 50 + 1 };
check(Object.getPrototypeOf(literalProtoObj8) === protoLiteral8, "literal proto prototype 8");
check(literalProtoObj8.inheritedMarker === 50, "literal proto inherited 8");
var protoComputed8 = { dataMarker: 50 + 2 };
var computedProtoObj8 = { ["__proto__"]: protoComputed8, ownMarker: 50 + 3 };
check(Object.getPrototypeOf(computedProtoObj8) === Object.prototype, "computed proto prototype 8");
check(computedProtoObj8.__proto__ === protoComputed8, "computed proto own data 8");
check(computedProtoObj8.ownMarker === 50 + 3, "computed proto other data 8");
var ignoredProtoObj8 = { __proto__: 50, regular8: 50 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj8) === Object.prototype, "non object proto ignored 8");
check(ignoredProtoObj8.regular8 === 50 + 4, "non object proto regular 8");

var protoLiteral9 = { inheritedMarker: 55 };
var literalProtoObj9 = { __proto__: protoLiteral9, ownMarker: 55 + 1 };
check(Object.getPrototypeOf(literalProtoObj9) === protoLiteral9, "literal proto prototype 9");
check(literalProtoObj9.inheritedMarker === 55, "literal proto inherited 9");
var protoComputed9 = { dataMarker: 55 + 2 };
var computedProtoObj9 = { ["__proto__"]: protoComputed9, ownMarker: 55 + 3 };
check(Object.getPrototypeOf(computedProtoObj9) === Object.prototype, "computed proto prototype 9");
check(computedProtoObj9.__proto__ === protoComputed9, "computed proto own data 9");
check(computedProtoObj9.ownMarker === 55 + 3, "computed proto other data 9");
var ignoredProtoObj9 = { __proto__: 55, regular9: 55 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj9) === Object.prototype, "non object proto ignored 9");
check(ignoredProtoObj9.regular9 === 55 + 4, "non object proto regular 9");

var protoLiteral10 = { inheritedMarker: 60 };
var literalProtoObj10 = { __proto__: protoLiteral10, ownMarker: 60 + 1 };
check(Object.getPrototypeOf(literalProtoObj10) === protoLiteral10, "literal proto prototype 10");
check(literalProtoObj10.inheritedMarker === 60, "literal proto inherited 10");
var protoComputed10 = { dataMarker: 60 + 2 };
var computedProtoObj10 = { ["__proto__"]: protoComputed10, ownMarker: 60 + 3 };
check(Object.getPrototypeOf(computedProtoObj10) === Object.prototype, "computed proto prototype 10");
check(computedProtoObj10.__proto__ === protoComputed10, "computed proto own data 10");
check(computedProtoObj10.ownMarker === 60 + 3, "computed proto other data 10");
var ignoredProtoObj10 = { __proto__: 60, regular10: 60 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj10) === Object.prototype, "non object proto ignored 10");
check(ignoredProtoObj10.regular10 === 60 + 4, "non object proto regular 10");

var protoLiteral11 = { inheritedMarker: 65 };
var literalProtoObj11 = { __proto__: protoLiteral11, ownMarker: 65 + 1 };
check(Object.getPrototypeOf(literalProtoObj11) === protoLiteral11, "literal proto prototype 11");
check(literalProtoObj11.inheritedMarker === 65, "literal proto inherited 11");
var protoComputed11 = { dataMarker: 65 + 2 };
var computedProtoObj11 = { ["__proto__"]: protoComputed11, ownMarker: 65 + 3 };
check(Object.getPrototypeOf(computedProtoObj11) === Object.prototype, "computed proto prototype 11");
check(computedProtoObj11.__proto__ === protoComputed11, "computed proto own data 11");
check(computedProtoObj11.ownMarker === 65 + 3, "computed proto other data 11");
var ignoredProtoObj11 = { __proto__: 65, regular11: 65 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj11) === Object.prototype, "non object proto ignored 11");
check(ignoredProtoObj11.regular11 === 65 + 4, "non object proto regular 11");

var protoLiteral12 = { inheritedMarker: 70 };
var literalProtoObj12 = { __proto__: protoLiteral12, ownMarker: 70 + 1 };
check(Object.getPrototypeOf(literalProtoObj12) === protoLiteral12, "literal proto prototype 12");
check(literalProtoObj12.inheritedMarker === 70, "literal proto inherited 12");
var protoComputed12 = { dataMarker: 70 + 2 };
var computedProtoObj12 = { ["__proto__"]: protoComputed12, ownMarker: 70 + 3 };
check(Object.getPrototypeOf(computedProtoObj12) === Object.prototype, "computed proto prototype 12");
check(computedProtoObj12.__proto__ === protoComputed12, "computed proto own data 12");
check(computedProtoObj12.ownMarker === 70 + 3, "computed proto other data 12");
var ignoredProtoObj12 = { __proto__: 70, regular12: 70 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj12) === Object.prototype, "non object proto ignored 12");
check(ignoredProtoObj12.regular12 === 70 + 4, "non object proto regular 12");

var protoLiteral13 = { inheritedMarker: 75 };
var literalProtoObj13 = { __proto__: protoLiteral13, ownMarker: 75 + 1 };
check(Object.getPrototypeOf(literalProtoObj13) === protoLiteral13, "literal proto prototype 13");
check(literalProtoObj13.inheritedMarker === 75, "literal proto inherited 13");
var protoComputed13 = { dataMarker: 75 + 2 };
var computedProtoObj13 = { ["__proto__"]: protoComputed13, ownMarker: 75 + 3 };
check(Object.getPrototypeOf(computedProtoObj13) === Object.prototype, "computed proto prototype 13");
check(computedProtoObj13.__proto__ === protoComputed13, "computed proto own data 13");
check(computedProtoObj13.ownMarker === 75 + 3, "computed proto other data 13");
var ignoredProtoObj13 = { __proto__: 75, regular13: 75 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj13) === Object.prototype, "non object proto ignored 13");
check(ignoredProtoObj13.regular13 === 75 + 4, "non object proto regular 13");

var protoLiteral14 = { inheritedMarker: 80 };
var literalProtoObj14 = { __proto__: protoLiteral14, ownMarker: 80 + 1 };
check(Object.getPrototypeOf(literalProtoObj14) === protoLiteral14, "literal proto prototype 14");
check(literalProtoObj14.inheritedMarker === 80, "literal proto inherited 14");
var protoComputed14 = { dataMarker: 80 + 2 };
var computedProtoObj14 = { ["__proto__"]: protoComputed14, ownMarker: 80 + 3 };
check(Object.getPrototypeOf(computedProtoObj14) === Object.prototype, "computed proto prototype 14");
check(computedProtoObj14.__proto__ === protoComputed14, "computed proto own data 14");
check(computedProtoObj14.ownMarker === 80 + 3, "computed proto other data 14");
var ignoredProtoObj14 = { __proto__: 80, regular14: 80 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj14) === Object.prototype, "non object proto ignored 14");
check(ignoredProtoObj14.regular14 === 80 + 4, "non object proto regular 14");

var protoLiteral15 = { inheritedMarker: 85 };
var literalProtoObj15 = { __proto__: protoLiteral15, ownMarker: 85 + 1 };
check(Object.getPrototypeOf(literalProtoObj15) === protoLiteral15, "literal proto prototype 15");
check(literalProtoObj15.inheritedMarker === 85, "literal proto inherited 15");
var protoComputed15 = { dataMarker: 85 + 2 };
var computedProtoObj15 = { ["__proto__"]: protoComputed15, ownMarker: 85 + 3 };
check(Object.getPrototypeOf(computedProtoObj15) === Object.prototype, "computed proto prototype 15");
check(computedProtoObj15.__proto__ === protoComputed15, "computed proto own data 15");
check(computedProtoObj15.ownMarker === 85 + 3, "computed proto other data 15");
var ignoredProtoObj15 = { __proto__: 85, regular15: 85 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj15) === Object.prototype, "non object proto ignored 15");
check(ignoredProtoObj15.regular15 === 85 + 4, "non object proto regular 15");

var protoLiteral16 = { inheritedMarker: 90 };
var literalProtoObj16 = { __proto__: protoLiteral16, ownMarker: 90 + 1 };
check(Object.getPrototypeOf(literalProtoObj16) === protoLiteral16, "literal proto prototype 16");
check(literalProtoObj16.inheritedMarker === 90, "literal proto inherited 16");
var protoComputed16 = { dataMarker: 90 + 2 };
var computedProtoObj16 = { ["__proto__"]: protoComputed16, ownMarker: 90 + 3 };
check(Object.getPrototypeOf(computedProtoObj16) === Object.prototype, "computed proto prototype 16");
check(computedProtoObj16.__proto__ === protoComputed16, "computed proto own data 16");
check(computedProtoObj16.ownMarker === 90 + 3, "computed proto other data 16");
var ignoredProtoObj16 = { __proto__: 90, regular16: 90 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj16) === Object.prototype, "non object proto ignored 16");
check(ignoredProtoObj16.regular16 === 90 + 4, "non object proto regular 16");

var protoLiteral17 = { inheritedMarker: 95 };
var literalProtoObj17 = { __proto__: protoLiteral17, ownMarker: 95 + 1 };
check(Object.getPrototypeOf(literalProtoObj17) === protoLiteral17, "literal proto prototype 17");
check(literalProtoObj17.inheritedMarker === 95, "literal proto inherited 17");
var protoComputed17 = { dataMarker: 95 + 2 };
var computedProtoObj17 = { ["__proto__"]: protoComputed17, ownMarker: 95 + 3 };
check(Object.getPrototypeOf(computedProtoObj17) === Object.prototype, "computed proto prototype 17");
check(computedProtoObj17.__proto__ === protoComputed17, "computed proto own data 17");
check(computedProtoObj17.ownMarker === 95 + 3, "computed proto other data 17");
var ignoredProtoObj17 = { __proto__: 95, regular17: 95 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj17) === Object.prototype, "non object proto ignored 17");
check(ignoredProtoObj17.regular17 === 95 + 4, "non object proto regular 17");

var protoLiteral18 = { inheritedMarker: 100 };
var literalProtoObj18 = { __proto__: protoLiteral18, ownMarker: 100 + 1 };
check(Object.getPrototypeOf(literalProtoObj18) === protoLiteral18, "literal proto prototype 18");
check(literalProtoObj18.inheritedMarker === 100, "literal proto inherited 18");
var protoComputed18 = { dataMarker: 100 + 2 };
var computedProtoObj18 = { ["__proto__"]: protoComputed18, ownMarker: 100 + 3 };
check(Object.getPrototypeOf(computedProtoObj18) === Object.prototype, "computed proto prototype 18");
check(computedProtoObj18.__proto__ === protoComputed18, "computed proto own data 18");
check(computedProtoObj18.ownMarker === 100 + 3, "computed proto other data 18");
var ignoredProtoObj18 = { __proto__: 100, regular18: 100 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj18) === Object.prototype, "non object proto ignored 18");
check(ignoredProtoObj18.regular18 === 100 + 4, "non object proto regular 18");

var protoLiteral19 = { inheritedMarker: 105 };
var literalProtoObj19 = { __proto__: protoLiteral19, ownMarker: 105 + 1 };
check(Object.getPrototypeOf(literalProtoObj19) === protoLiteral19, "literal proto prototype 19");
check(literalProtoObj19.inheritedMarker === 105, "literal proto inherited 19");
var protoComputed19 = { dataMarker: 105 + 2 };
var computedProtoObj19 = { ["__proto__"]: protoComputed19, ownMarker: 105 + 3 };
check(Object.getPrototypeOf(computedProtoObj19) === Object.prototype, "computed proto prototype 19");
check(computedProtoObj19.__proto__ === protoComputed19, "computed proto own data 19");
check(computedProtoObj19.ownMarker === 105 + 3, "computed proto other data 19");
var ignoredProtoObj19 = { __proto__: 105, regular19: 105 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj19) === Object.prototype, "non object proto ignored 19");
check(ignoredProtoObj19.regular19 === 105 + 4, "non object proto regular 19");

var protoLiteral20 = { inheritedMarker: 110 };
var literalProtoObj20 = { __proto__: protoLiteral20, ownMarker: 110 + 1 };
check(Object.getPrototypeOf(literalProtoObj20) === protoLiteral20, "literal proto prototype 20");
check(literalProtoObj20.inheritedMarker === 110, "literal proto inherited 20");
var protoComputed20 = { dataMarker: 110 + 2 };
var computedProtoObj20 = { ["__proto__"]: protoComputed20, ownMarker: 110 + 3 };
check(Object.getPrototypeOf(computedProtoObj20) === Object.prototype, "computed proto prototype 20");
check(computedProtoObj20.__proto__ === protoComputed20, "computed proto own data 20");
check(computedProtoObj20.ownMarker === 110 + 3, "computed proto other data 20");
var ignoredProtoObj20 = { __proto__: 110, regular20: 110 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj20) === Object.prototype, "non object proto ignored 20");
check(ignoredProtoObj20.regular20 === 110 + 4, "non object proto regular 20");

var protoLiteral21 = { inheritedMarker: 115 };
var literalProtoObj21 = { __proto__: protoLiteral21, ownMarker: 115 + 1 };
check(Object.getPrototypeOf(literalProtoObj21) === protoLiteral21, "literal proto prototype 21");
check(literalProtoObj21.inheritedMarker === 115, "literal proto inherited 21");
var protoComputed21 = { dataMarker: 115 + 2 };
var computedProtoObj21 = { ["__proto__"]: protoComputed21, ownMarker: 115 + 3 };
check(Object.getPrototypeOf(computedProtoObj21) === Object.prototype, "computed proto prototype 21");
check(computedProtoObj21.__proto__ === protoComputed21, "computed proto own data 21");
check(computedProtoObj21.ownMarker === 115 + 3, "computed proto other data 21");
var ignoredProtoObj21 = { __proto__: 115, regular21: 115 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj21) === Object.prototype, "non object proto ignored 21");
check(ignoredProtoObj21.regular21 === 115 + 4, "non object proto regular 21");

var protoLiteral22 = { inheritedMarker: 120 };
var literalProtoObj22 = { __proto__: protoLiteral22, ownMarker: 120 + 1 };
check(Object.getPrototypeOf(literalProtoObj22) === protoLiteral22, "literal proto prototype 22");
check(literalProtoObj22.inheritedMarker === 120, "literal proto inherited 22");
var protoComputed22 = { dataMarker: 120 + 2 };
var computedProtoObj22 = { ["__proto__"]: protoComputed22, ownMarker: 120 + 3 };
check(Object.getPrototypeOf(computedProtoObj22) === Object.prototype, "computed proto prototype 22");
check(computedProtoObj22.__proto__ === protoComputed22, "computed proto own data 22");
check(computedProtoObj22.ownMarker === 120 + 3, "computed proto other data 22");
var ignoredProtoObj22 = { __proto__: 120, regular22: 120 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj22) === Object.prototype, "non object proto ignored 22");
check(ignoredProtoObj22.regular22 === 120 + 4, "non object proto regular 22");

var protoLiteral23 = { inheritedMarker: 125 };
var literalProtoObj23 = { __proto__: protoLiteral23, ownMarker: 125 + 1 };
check(Object.getPrototypeOf(literalProtoObj23) === protoLiteral23, "literal proto prototype 23");
check(literalProtoObj23.inheritedMarker === 125, "literal proto inherited 23");
var protoComputed23 = { dataMarker: 125 + 2 };
var computedProtoObj23 = { ["__proto__"]: protoComputed23, ownMarker: 125 + 3 };
check(Object.getPrototypeOf(computedProtoObj23) === Object.prototype, "computed proto prototype 23");
check(computedProtoObj23.__proto__ === protoComputed23, "computed proto own data 23");
check(computedProtoObj23.ownMarker === 125 + 3, "computed proto other data 23");
var ignoredProtoObj23 = { __proto__: 125, regular23: 125 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj23) === Object.prototype, "non object proto ignored 23");
check(ignoredProtoObj23.regular23 === 125 + 4, "non object proto regular 23");

var protoLiteral24 = { inheritedMarker: 130 };
var literalProtoObj24 = { __proto__: protoLiteral24, ownMarker: 130 + 1 };
check(Object.getPrototypeOf(literalProtoObj24) === protoLiteral24, "literal proto prototype 24");
check(literalProtoObj24.inheritedMarker === 130, "literal proto inherited 24");
var protoComputed24 = { dataMarker: 130 + 2 };
var computedProtoObj24 = { ["__proto__"]: protoComputed24, ownMarker: 130 + 3 };
check(Object.getPrototypeOf(computedProtoObj24) === Object.prototype, "computed proto prototype 24");
check(computedProtoObj24.__proto__ === protoComputed24, "computed proto own data 24");
check(computedProtoObj24.ownMarker === 130 + 3, "computed proto other data 24");
var ignoredProtoObj24 = { __proto__: 130, regular24: 130 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj24) === Object.prototype, "non object proto ignored 24");
check(ignoredProtoObj24.regular24 === 130 + 4, "non object proto regular 24");

var protoLiteral25 = { inheritedMarker: 135 };
var literalProtoObj25 = { __proto__: protoLiteral25, ownMarker: 135 + 1 };
check(Object.getPrototypeOf(literalProtoObj25) === protoLiteral25, "literal proto prototype 25");
check(literalProtoObj25.inheritedMarker === 135, "literal proto inherited 25");
var protoComputed25 = { dataMarker: 135 + 2 };
var computedProtoObj25 = { ["__proto__"]: protoComputed25, ownMarker: 135 + 3 };
check(Object.getPrototypeOf(computedProtoObj25) === Object.prototype, "computed proto prototype 25");
check(computedProtoObj25.__proto__ === protoComputed25, "computed proto own data 25");
check(computedProtoObj25.ownMarker === 135 + 3, "computed proto other data 25");
var ignoredProtoObj25 = { __proto__: 135, regular25: 135 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj25) === Object.prototype, "non object proto ignored 25");
check(ignoredProtoObj25.regular25 === 135 + 4, "non object proto regular 25");

var protoLiteral26 = { inheritedMarker: 140 };
var literalProtoObj26 = { __proto__: protoLiteral26, ownMarker: 140 + 1 };
check(Object.getPrototypeOf(literalProtoObj26) === protoLiteral26, "literal proto prototype 26");
check(literalProtoObj26.inheritedMarker === 140, "literal proto inherited 26");
var protoComputed26 = { dataMarker: 140 + 2 };
var computedProtoObj26 = { ["__proto__"]: protoComputed26, ownMarker: 140 + 3 };
check(Object.getPrototypeOf(computedProtoObj26) === Object.prototype, "computed proto prototype 26");
check(computedProtoObj26.__proto__ === protoComputed26, "computed proto own data 26");
check(computedProtoObj26.ownMarker === 140 + 3, "computed proto other data 26");
var ignoredProtoObj26 = { __proto__: 140, regular26: 140 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj26) === Object.prototype, "non object proto ignored 26");
check(ignoredProtoObj26.regular26 === 140 + 4, "non object proto regular 26");

var protoLiteral27 = { inheritedMarker: 145 };
var literalProtoObj27 = { __proto__: protoLiteral27, ownMarker: 145 + 1 };
check(Object.getPrototypeOf(literalProtoObj27) === protoLiteral27, "literal proto prototype 27");
check(literalProtoObj27.inheritedMarker === 145, "literal proto inherited 27");
var protoComputed27 = { dataMarker: 145 + 2 };
var computedProtoObj27 = { ["__proto__"]: protoComputed27, ownMarker: 145 + 3 };
check(Object.getPrototypeOf(computedProtoObj27) === Object.prototype, "computed proto prototype 27");
check(computedProtoObj27.__proto__ === protoComputed27, "computed proto own data 27");
check(computedProtoObj27.ownMarker === 145 + 3, "computed proto other data 27");
var ignoredProtoObj27 = { __proto__: 145, regular27: 145 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj27) === Object.prototype, "non object proto ignored 27");
check(ignoredProtoObj27.regular27 === 145 + 4, "non object proto regular 27");

var protoLiteral28 = { inheritedMarker: 150 };
var literalProtoObj28 = { __proto__: protoLiteral28, ownMarker: 150 + 1 };
check(Object.getPrototypeOf(literalProtoObj28) === protoLiteral28, "literal proto prototype 28");
check(literalProtoObj28.inheritedMarker === 150, "literal proto inherited 28");
var protoComputed28 = { dataMarker: 150 + 2 };
var computedProtoObj28 = { ["__proto__"]: protoComputed28, ownMarker: 150 + 3 };
check(Object.getPrototypeOf(computedProtoObj28) === Object.prototype, "computed proto prototype 28");
check(computedProtoObj28.__proto__ === protoComputed28, "computed proto own data 28");
check(computedProtoObj28.ownMarker === 150 + 3, "computed proto other data 28");
var ignoredProtoObj28 = { __proto__: 150, regular28: 150 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj28) === Object.prototype, "non object proto ignored 28");
check(ignoredProtoObj28.regular28 === 150 + 4, "non object proto regular 28");

var protoLiteral29 = { inheritedMarker: 155 };
var literalProtoObj29 = { __proto__: protoLiteral29, ownMarker: 155 + 1 };
check(Object.getPrototypeOf(literalProtoObj29) === protoLiteral29, "literal proto prototype 29");
check(literalProtoObj29.inheritedMarker === 155, "literal proto inherited 29");
var protoComputed29 = { dataMarker: 155 + 2 };
var computedProtoObj29 = { ["__proto__"]: protoComputed29, ownMarker: 155 + 3 };
check(Object.getPrototypeOf(computedProtoObj29) === Object.prototype, "computed proto prototype 29");
check(computedProtoObj29.__proto__ === protoComputed29, "computed proto own data 29");
check(computedProtoObj29.ownMarker === 155 + 3, "computed proto other data 29");
var ignoredProtoObj29 = { __proto__: 155, regular29: 155 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj29) === Object.prototype, "non object proto ignored 29");
check(ignoredProtoObj29.regular29 === 155 + 4, "non object proto regular 29");

var protoLiteral30 = { inheritedMarker: 160 };
var literalProtoObj30 = { __proto__: protoLiteral30, ownMarker: 160 + 1 };
check(Object.getPrototypeOf(literalProtoObj30) === protoLiteral30, "literal proto prototype 30");
check(literalProtoObj30.inheritedMarker === 160, "literal proto inherited 30");
var protoComputed30 = { dataMarker: 160 + 2 };
var computedProtoObj30 = { ["__proto__"]: protoComputed30, ownMarker: 160 + 3 };
check(Object.getPrototypeOf(computedProtoObj30) === Object.prototype, "computed proto prototype 30");
check(computedProtoObj30.__proto__ === protoComputed30, "computed proto own data 30");
check(computedProtoObj30.ownMarker === 160 + 3, "computed proto other data 30");
var ignoredProtoObj30 = { __proto__: 160, regular30: 160 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj30) === Object.prototype, "non object proto ignored 30");
check(ignoredProtoObj30.regular30 === 160 + 4, "non object proto regular 30");

var protoLiteral31 = { inheritedMarker: 165 };
var literalProtoObj31 = { __proto__: protoLiteral31, ownMarker: 165 + 1 };
check(Object.getPrototypeOf(literalProtoObj31) === protoLiteral31, "literal proto prototype 31");
check(literalProtoObj31.inheritedMarker === 165, "literal proto inherited 31");
var protoComputed31 = { dataMarker: 165 + 2 };
var computedProtoObj31 = { ["__proto__"]: protoComputed31, ownMarker: 165 + 3 };
check(Object.getPrototypeOf(computedProtoObj31) === Object.prototype, "computed proto prototype 31");
check(computedProtoObj31.__proto__ === protoComputed31, "computed proto own data 31");
check(computedProtoObj31.ownMarker === 165 + 3, "computed proto other data 31");
var ignoredProtoObj31 = { __proto__: 165, regular31: 165 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj31) === Object.prototype, "non object proto ignored 31");
check(ignoredProtoObj31.regular31 === 165 + 4, "non object proto regular 31");

var protoLiteral32 = { inheritedMarker: 170 };
var literalProtoObj32 = { __proto__: protoLiteral32, ownMarker: 170 + 1 };
check(Object.getPrototypeOf(literalProtoObj32) === protoLiteral32, "literal proto prototype 32");
check(literalProtoObj32.inheritedMarker === 170, "literal proto inherited 32");
var protoComputed32 = { dataMarker: 170 + 2 };
var computedProtoObj32 = { ["__proto__"]: protoComputed32, ownMarker: 170 + 3 };
check(Object.getPrototypeOf(computedProtoObj32) === Object.prototype, "computed proto prototype 32");
check(computedProtoObj32.__proto__ === protoComputed32, "computed proto own data 32");
check(computedProtoObj32.ownMarker === 170 + 3, "computed proto other data 32");
var ignoredProtoObj32 = { __proto__: 170, regular32: 170 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj32) === Object.prototype, "non object proto ignored 32");
check(ignoredProtoObj32.regular32 === 170 + 4, "non object proto regular 32");

var protoLiteral33 = { inheritedMarker: 175 };
var literalProtoObj33 = { __proto__: protoLiteral33, ownMarker: 175 + 1 };
check(Object.getPrototypeOf(literalProtoObj33) === protoLiteral33, "literal proto prototype 33");
check(literalProtoObj33.inheritedMarker === 175, "literal proto inherited 33");
var protoComputed33 = { dataMarker: 175 + 2 };
var computedProtoObj33 = { ["__proto__"]: protoComputed33, ownMarker: 175 + 3 };
check(Object.getPrototypeOf(computedProtoObj33) === Object.prototype, "computed proto prototype 33");
check(computedProtoObj33.__proto__ === protoComputed33, "computed proto own data 33");
check(computedProtoObj33.ownMarker === 175 + 3, "computed proto other data 33");
var ignoredProtoObj33 = { __proto__: 175, regular33: 175 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj33) === Object.prototype, "non object proto ignored 33");
check(ignoredProtoObj33.regular33 === 175 + 4, "non object proto regular 33");

var protoLiteral34 = { inheritedMarker: 180 };
var literalProtoObj34 = { __proto__: protoLiteral34, ownMarker: 180 + 1 };
check(Object.getPrototypeOf(literalProtoObj34) === protoLiteral34, "literal proto prototype 34");
check(literalProtoObj34.inheritedMarker === 180, "literal proto inherited 34");
var protoComputed34 = { dataMarker: 180 + 2 };
var computedProtoObj34 = { ["__proto__"]: protoComputed34, ownMarker: 180 + 3 };
check(Object.getPrototypeOf(computedProtoObj34) === Object.prototype, "computed proto prototype 34");
check(computedProtoObj34.__proto__ === protoComputed34, "computed proto own data 34");
check(computedProtoObj34.ownMarker === 180 + 3, "computed proto other data 34");
var ignoredProtoObj34 = { __proto__: 180, regular34: 180 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj34) === Object.prototype, "non object proto ignored 34");
check(ignoredProtoObj34.regular34 === 180 + 4, "non object proto regular 34");

var protoLiteral35 = { inheritedMarker: 185 };
var literalProtoObj35 = { __proto__: protoLiteral35, ownMarker: 185 + 1 };
check(Object.getPrototypeOf(literalProtoObj35) === protoLiteral35, "literal proto prototype 35");
check(literalProtoObj35.inheritedMarker === 185, "literal proto inherited 35");
var protoComputed35 = { dataMarker: 185 + 2 };
var computedProtoObj35 = { ["__proto__"]: protoComputed35, ownMarker: 185 + 3 };
check(Object.getPrototypeOf(computedProtoObj35) === Object.prototype, "computed proto prototype 35");
check(computedProtoObj35.__proto__ === protoComputed35, "computed proto own data 35");
check(computedProtoObj35.ownMarker === 185 + 3, "computed proto other data 35");
var ignoredProtoObj35 = { __proto__: 185, regular35: 185 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj35) === Object.prototype, "non object proto ignored 35");
check(ignoredProtoObj35.regular35 === 185 + 4, "non object proto regular 35");

var protoLiteral36 = { inheritedMarker: 190 };
var literalProtoObj36 = { __proto__: protoLiteral36, ownMarker: 190 + 1 };
check(Object.getPrototypeOf(literalProtoObj36) === protoLiteral36, "literal proto prototype 36");
check(literalProtoObj36.inheritedMarker === 190, "literal proto inherited 36");
var protoComputed36 = { dataMarker: 190 + 2 };
var computedProtoObj36 = { ["__proto__"]: protoComputed36, ownMarker: 190 + 3 };
check(Object.getPrototypeOf(computedProtoObj36) === Object.prototype, "computed proto prototype 36");
check(computedProtoObj36.__proto__ === protoComputed36, "computed proto own data 36");
check(computedProtoObj36.ownMarker === 190 + 3, "computed proto other data 36");
var ignoredProtoObj36 = { __proto__: 190, regular36: 190 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj36) === Object.prototype, "non object proto ignored 36");
check(ignoredProtoObj36.regular36 === 190 + 4, "non object proto regular 36");

var protoLiteral37 = { inheritedMarker: 195 };
var literalProtoObj37 = { __proto__: protoLiteral37, ownMarker: 195 + 1 };
check(Object.getPrototypeOf(literalProtoObj37) === protoLiteral37, "literal proto prototype 37");
check(literalProtoObj37.inheritedMarker === 195, "literal proto inherited 37");
var protoComputed37 = { dataMarker: 195 + 2 };
var computedProtoObj37 = { ["__proto__"]: protoComputed37, ownMarker: 195 + 3 };
check(Object.getPrototypeOf(computedProtoObj37) === Object.prototype, "computed proto prototype 37");
check(computedProtoObj37.__proto__ === protoComputed37, "computed proto own data 37");
check(computedProtoObj37.ownMarker === 195 + 3, "computed proto other data 37");
var ignoredProtoObj37 = { __proto__: 195, regular37: 195 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj37) === Object.prototype, "non object proto ignored 37");
check(ignoredProtoObj37.regular37 === 195 + 4, "non object proto regular 37");

var protoLiteral38 = { inheritedMarker: 200 };
var literalProtoObj38 = { __proto__: protoLiteral38, ownMarker: 200 + 1 };
check(Object.getPrototypeOf(literalProtoObj38) === protoLiteral38, "literal proto prototype 38");
check(literalProtoObj38.inheritedMarker === 200, "literal proto inherited 38");
var protoComputed38 = { dataMarker: 200 + 2 };
var computedProtoObj38 = { ["__proto__"]: protoComputed38, ownMarker: 200 + 3 };
check(Object.getPrototypeOf(computedProtoObj38) === Object.prototype, "computed proto prototype 38");
check(computedProtoObj38.__proto__ === protoComputed38, "computed proto own data 38");
check(computedProtoObj38.ownMarker === 200 + 3, "computed proto other data 38");
var ignoredProtoObj38 = { __proto__: 200, regular38: 200 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj38) === Object.prototype, "non object proto ignored 38");
check(ignoredProtoObj38.regular38 === 200 + 4, "non object proto regular 38");

var protoLiteral39 = { inheritedMarker: 205 };
var literalProtoObj39 = { __proto__: protoLiteral39, ownMarker: 205 + 1 };
check(Object.getPrototypeOf(literalProtoObj39) === protoLiteral39, "literal proto prototype 39");
check(literalProtoObj39.inheritedMarker === 205, "literal proto inherited 39");
var protoComputed39 = { dataMarker: 205 + 2 };
var computedProtoObj39 = { ["__proto__"]: protoComputed39, ownMarker: 205 + 3 };
check(Object.getPrototypeOf(computedProtoObj39) === Object.prototype, "computed proto prototype 39");
check(computedProtoObj39.__proto__ === protoComputed39, "computed proto own data 39");
check(computedProtoObj39.ownMarker === 205 + 3, "computed proto other data 39");
var ignoredProtoObj39 = { __proto__: 205, regular39: 205 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj39) === Object.prototype, "non object proto ignored 39");
check(ignoredProtoObj39.regular39 === 205 + 4, "non object proto regular 39");

var protoLiteral40 = { inheritedMarker: 210 };
var literalProtoObj40 = { __proto__: protoLiteral40, ownMarker: 210 + 1 };
check(Object.getPrototypeOf(literalProtoObj40) === protoLiteral40, "literal proto prototype 40");
check(literalProtoObj40.inheritedMarker === 210, "literal proto inherited 40");
var protoComputed40 = { dataMarker: 210 + 2 };
var computedProtoObj40 = { ["__proto__"]: protoComputed40, ownMarker: 210 + 3 };
check(Object.getPrototypeOf(computedProtoObj40) === Object.prototype, "computed proto prototype 40");
check(computedProtoObj40.__proto__ === protoComputed40, "computed proto own data 40");
check(computedProtoObj40.ownMarker === 210 + 3, "computed proto other data 40");
var ignoredProtoObj40 = { __proto__: 210, regular40: 210 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj40) === Object.prototype, "non object proto ignored 40");
check(ignoredProtoObj40.regular40 === 210 + 4, "non object proto regular 40");

var protoLiteral41 = { inheritedMarker: 215 };
var literalProtoObj41 = { __proto__: protoLiteral41, ownMarker: 215 + 1 };
check(Object.getPrototypeOf(literalProtoObj41) === protoLiteral41, "literal proto prototype 41");
check(literalProtoObj41.inheritedMarker === 215, "literal proto inherited 41");
var protoComputed41 = { dataMarker: 215 + 2 };
var computedProtoObj41 = { ["__proto__"]: protoComputed41, ownMarker: 215 + 3 };
check(Object.getPrototypeOf(computedProtoObj41) === Object.prototype, "computed proto prototype 41");
check(computedProtoObj41.__proto__ === protoComputed41, "computed proto own data 41");
check(computedProtoObj41.ownMarker === 215 + 3, "computed proto other data 41");
var ignoredProtoObj41 = { __proto__: 215, regular41: 215 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj41) === Object.prototype, "non object proto ignored 41");
check(ignoredProtoObj41.regular41 === 215 + 4, "non object proto regular 41");

var protoLiteral42 = { inheritedMarker: 220 };
var literalProtoObj42 = { __proto__: protoLiteral42, ownMarker: 220 + 1 };
check(Object.getPrototypeOf(literalProtoObj42) === protoLiteral42, "literal proto prototype 42");
check(literalProtoObj42.inheritedMarker === 220, "literal proto inherited 42");
var protoComputed42 = { dataMarker: 220 + 2 };
var computedProtoObj42 = { ["__proto__"]: protoComputed42, ownMarker: 220 + 3 };
check(Object.getPrototypeOf(computedProtoObj42) === Object.prototype, "computed proto prototype 42");
check(computedProtoObj42.__proto__ === protoComputed42, "computed proto own data 42");
check(computedProtoObj42.ownMarker === 220 + 3, "computed proto other data 42");
var ignoredProtoObj42 = { __proto__: 220, regular42: 220 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj42) === Object.prototype, "non object proto ignored 42");
check(ignoredProtoObj42.regular42 === 220 + 4, "non object proto regular 42");

var protoLiteral43 = { inheritedMarker: 225 };
var literalProtoObj43 = { __proto__: protoLiteral43, ownMarker: 225 + 1 };
check(Object.getPrototypeOf(literalProtoObj43) === protoLiteral43, "literal proto prototype 43");
check(literalProtoObj43.inheritedMarker === 225, "literal proto inherited 43");
var protoComputed43 = { dataMarker: 225 + 2 };
var computedProtoObj43 = { ["__proto__"]: protoComputed43, ownMarker: 225 + 3 };
check(Object.getPrototypeOf(computedProtoObj43) === Object.prototype, "computed proto prototype 43");
check(computedProtoObj43.__proto__ === protoComputed43, "computed proto own data 43");
check(computedProtoObj43.ownMarker === 225 + 3, "computed proto other data 43");
var ignoredProtoObj43 = { __proto__: 225, regular43: 225 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj43) === Object.prototype, "non object proto ignored 43");
check(ignoredProtoObj43.regular43 === 225 + 4, "non object proto regular 43");

var protoLiteral44 = { inheritedMarker: 230 };
var literalProtoObj44 = { __proto__: protoLiteral44, ownMarker: 230 + 1 };
check(Object.getPrototypeOf(literalProtoObj44) === protoLiteral44, "literal proto prototype 44");
check(literalProtoObj44.inheritedMarker === 230, "literal proto inherited 44");
var protoComputed44 = { dataMarker: 230 + 2 };
var computedProtoObj44 = { ["__proto__"]: protoComputed44, ownMarker: 230 + 3 };
check(Object.getPrototypeOf(computedProtoObj44) === Object.prototype, "computed proto prototype 44");
check(computedProtoObj44.__proto__ === protoComputed44, "computed proto own data 44");
check(computedProtoObj44.ownMarker === 230 + 3, "computed proto other data 44");
var ignoredProtoObj44 = { __proto__: 230, regular44: 230 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj44) === Object.prototype, "non object proto ignored 44");
check(ignoredProtoObj44.regular44 === 230 + 4, "non object proto regular 44");

var protoLiteral45 = { inheritedMarker: 235 };
var literalProtoObj45 = { __proto__: protoLiteral45, ownMarker: 235 + 1 };
check(Object.getPrototypeOf(literalProtoObj45) === protoLiteral45, "literal proto prototype 45");
check(literalProtoObj45.inheritedMarker === 235, "literal proto inherited 45");
var protoComputed45 = { dataMarker: 235 + 2 };
var computedProtoObj45 = { ["__proto__"]: protoComputed45, ownMarker: 235 + 3 };
check(Object.getPrototypeOf(computedProtoObj45) === Object.prototype, "computed proto prototype 45");
check(computedProtoObj45.__proto__ === protoComputed45, "computed proto own data 45");
check(computedProtoObj45.ownMarker === 235 + 3, "computed proto other data 45");
var ignoredProtoObj45 = { __proto__: 235, regular45: 235 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj45) === Object.prototype, "non object proto ignored 45");
check(ignoredProtoObj45.regular45 === 235 + 4, "non object proto regular 45");

var protoLiteral46 = { inheritedMarker: 240 };
var literalProtoObj46 = { __proto__: protoLiteral46, ownMarker: 240 + 1 };
check(Object.getPrototypeOf(literalProtoObj46) === protoLiteral46, "literal proto prototype 46");
check(literalProtoObj46.inheritedMarker === 240, "literal proto inherited 46");
var protoComputed46 = { dataMarker: 240 + 2 };
var computedProtoObj46 = { ["__proto__"]: protoComputed46, ownMarker: 240 + 3 };
check(Object.getPrototypeOf(computedProtoObj46) === Object.prototype, "computed proto prototype 46");
check(computedProtoObj46.__proto__ === protoComputed46, "computed proto own data 46");
check(computedProtoObj46.ownMarker === 240 + 3, "computed proto other data 46");
var ignoredProtoObj46 = { __proto__: 240, regular46: 240 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj46) === Object.prototype, "non object proto ignored 46");
check(ignoredProtoObj46.regular46 === 240 + 4, "non object proto regular 46");

var protoLiteral47 = { inheritedMarker: 245 };
var literalProtoObj47 = { __proto__: protoLiteral47, ownMarker: 245 + 1 };
check(Object.getPrototypeOf(literalProtoObj47) === protoLiteral47, "literal proto prototype 47");
check(literalProtoObj47.inheritedMarker === 245, "literal proto inherited 47");
var protoComputed47 = { dataMarker: 245 + 2 };
var computedProtoObj47 = { ["__proto__"]: protoComputed47, ownMarker: 245 + 3 };
check(Object.getPrototypeOf(computedProtoObj47) === Object.prototype, "computed proto prototype 47");
check(computedProtoObj47.__proto__ === protoComputed47, "computed proto own data 47");
check(computedProtoObj47.ownMarker === 245 + 3, "computed proto other data 47");
var ignoredProtoObj47 = { __proto__: 245, regular47: 245 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj47) === Object.prototype, "non object proto ignored 47");
check(ignoredProtoObj47.regular47 === 245 + 4, "non object proto regular 47");

var protoLiteral48 = { inheritedMarker: 250 };
var literalProtoObj48 = { __proto__: protoLiteral48, ownMarker: 250 + 1 };
check(Object.getPrototypeOf(literalProtoObj48) === protoLiteral48, "literal proto prototype 48");
check(literalProtoObj48.inheritedMarker === 250, "literal proto inherited 48");
var protoComputed48 = { dataMarker: 250 + 2 };
var computedProtoObj48 = { ["__proto__"]: protoComputed48, ownMarker: 250 + 3 };
check(Object.getPrototypeOf(computedProtoObj48) === Object.prototype, "computed proto prototype 48");
check(computedProtoObj48.__proto__ === protoComputed48, "computed proto own data 48");
check(computedProtoObj48.ownMarker === 250 + 3, "computed proto other data 48");
var ignoredProtoObj48 = { __proto__: 250, regular48: 250 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj48) === Object.prototype, "non object proto ignored 48");
check(ignoredProtoObj48.regular48 === 250 + 4, "non object proto regular 48");

var protoLiteral49 = { inheritedMarker: 255 };
var literalProtoObj49 = { __proto__: protoLiteral49, ownMarker: 255 + 1 };
check(Object.getPrototypeOf(literalProtoObj49) === protoLiteral49, "literal proto prototype 49");
check(literalProtoObj49.inheritedMarker === 255, "literal proto inherited 49");
var protoComputed49 = { dataMarker: 255 + 2 };
var computedProtoObj49 = { ["__proto__"]: protoComputed49, ownMarker: 255 + 3 };
check(Object.getPrototypeOf(computedProtoObj49) === Object.prototype, "computed proto prototype 49");
check(computedProtoObj49.__proto__ === protoComputed49, "computed proto own data 49");
check(computedProtoObj49.ownMarker === 255 + 3, "computed proto other data 49");
var ignoredProtoObj49 = { __proto__: 255, regular49: 255 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj49) === Object.prototype, "non object proto ignored 49");
check(ignoredProtoObj49.regular49 === 255 + 4, "non object proto regular 49");

var protoLiteral50 = { inheritedMarker: 260 };
var literalProtoObj50 = { __proto__: protoLiteral50, ownMarker: 260 + 1 };
check(Object.getPrototypeOf(literalProtoObj50) === protoLiteral50, "literal proto prototype 50");
check(literalProtoObj50.inheritedMarker === 260, "literal proto inherited 50");
var protoComputed50 = { dataMarker: 260 + 2 };
var computedProtoObj50 = { ["__proto__"]: protoComputed50, ownMarker: 260 + 3 };
check(Object.getPrototypeOf(computedProtoObj50) === Object.prototype, "computed proto prototype 50");
check(computedProtoObj50.__proto__ === protoComputed50, "computed proto own data 50");
check(computedProtoObj50.ownMarker === 260 + 3, "computed proto other data 50");
var ignoredProtoObj50 = { __proto__: 260, regular50: 260 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj50) === Object.prototype, "non object proto ignored 50");
check(ignoredProtoObj50.regular50 === 260 + 4, "non object proto regular 50");

var protoLiteral51 = { inheritedMarker: 265 };
var literalProtoObj51 = { __proto__: protoLiteral51, ownMarker: 265 + 1 };
check(Object.getPrototypeOf(literalProtoObj51) === protoLiteral51, "literal proto prototype 51");
check(literalProtoObj51.inheritedMarker === 265, "literal proto inherited 51");
var protoComputed51 = { dataMarker: 265 + 2 };
var computedProtoObj51 = { ["__proto__"]: protoComputed51, ownMarker: 265 + 3 };
check(Object.getPrototypeOf(computedProtoObj51) === Object.prototype, "computed proto prototype 51");
check(computedProtoObj51.__proto__ === protoComputed51, "computed proto own data 51");
check(computedProtoObj51.ownMarker === 265 + 3, "computed proto other data 51");
var ignoredProtoObj51 = { __proto__: 265, regular51: 265 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj51) === Object.prototype, "non object proto ignored 51");
check(ignoredProtoObj51.regular51 === 265 + 4, "non object proto regular 51");

var protoLiteral52 = { inheritedMarker: 270 };
var literalProtoObj52 = { __proto__: protoLiteral52, ownMarker: 270 + 1 };
check(Object.getPrototypeOf(literalProtoObj52) === protoLiteral52, "literal proto prototype 52");
check(literalProtoObj52.inheritedMarker === 270, "literal proto inherited 52");
var protoComputed52 = { dataMarker: 270 + 2 };
var computedProtoObj52 = { ["__proto__"]: protoComputed52, ownMarker: 270 + 3 };
check(Object.getPrototypeOf(computedProtoObj52) === Object.prototype, "computed proto prototype 52");
check(computedProtoObj52.__proto__ === protoComputed52, "computed proto own data 52");
check(computedProtoObj52.ownMarker === 270 + 3, "computed proto other data 52");
var ignoredProtoObj52 = { __proto__: 270, regular52: 270 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj52) === Object.prototype, "non object proto ignored 52");
check(ignoredProtoObj52.regular52 === 270 + 4, "non object proto regular 52");

var protoLiteral53 = { inheritedMarker: 275 };
var literalProtoObj53 = { __proto__: protoLiteral53, ownMarker: 275 + 1 };
check(Object.getPrototypeOf(literalProtoObj53) === protoLiteral53, "literal proto prototype 53");
check(literalProtoObj53.inheritedMarker === 275, "literal proto inherited 53");
var protoComputed53 = { dataMarker: 275 + 2 };
var computedProtoObj53 = { ["__proto__"]: protoComputed53, ownMarker: 275 + 3 };
check(Object.getPrototypeOf(computedProtoObj53) === Object.prototype, "computed proto prototype 53");
check(computedProtoObj53.__proto__ === protoComputed53, "computed proto own data 53");
check(computedProtoObj53.ownMarker === 275 + 3, "computed proto other data 53");
var ignoredProtoObj53 = { __proto__: 275, regular53: 275 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj53) === Object.prototype, "non object proto ignored 53");
check(ignoredProtoObj53.regular53 === 275 + 4, "non object proto regular 53");

var protoLiteral54 = { inheritedMarker: 280 };
var literalProtoObj54 = { __proto__: protoLiteral54, ownMarker: 280 + 1 };
check(Object.getPrototypeOf(literalProtoObj54) === protoLiteral54, "literal proto prototype 54");
check(literalProtoObj54.inheritedMarker === 280, "literal proto inherited 54");
var protoComputed54 = { dataMarker: 280 + 2 };
var computedProtoObj54 = { ["__proto__"]: protoComputed54, ownMarker: 280 + 3 };
check(Object.getPrototypeOf(computedProtoObj54) === Object.prototype, "computed proto prototype 54");
check(computedProtoObj54.__proto__ === protoComputed54, "computed proto own data 54");
check(computedProtoObj54.ownMarker === 280 + 3, "computed proto other data 54");
var ignoredProtoObj54 = { __proto__: 280, regular54: 280 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj54) === Object.prototype, "non object proto ignored 54");
check(ignoredProtoObj54.regular54 === 280 + 4, "non object proto regular 54");

var protoLiteral55 = { inheritedMarker: 285 };
var literalProtoObj55 = { __proto__: protoLiteral55, ownMarker: 285 + 1 };
check(Object.getPrototypeOf(literalProtoObj55) === protoLiteral55, "literal proto prototype 55");
check(literalProtoObj55.inheritedMarker === 285, "literal proto inherited 55");
var protoComputed55 = { dataMarker: 285 + 2 };
var computedProtoObj55 = { ["__proto__"]: protoComputed55, ownMarker: 285 + 3 };
check(Object.getPrototypeOf(computedProtoObj55) === Object.prototype, "computed proto prototype 55");
check(computedProtoObj55.__proto__ === protoComputed55, "computed proto own data 55");
check(computedProtoObj55.ownMarker === 285 + 3, "computed proto other data 55");
var ignoredProtoObj55 = { __proto__: 285, regular55: 285 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj55) === Object.prototype, "non object proto ignored 55");
check(ignoredProtoObj55.regular55 === 285 + 4, "non object proto regular 55");

var protoLiteral56 = { inheritedMarker: 290 };
var literalProtoObj56 = { __proto__: protoLiteral56, ownMarker: 290 + 1 };
check(Object.getPrototypeOf(literalProtoObj56) === protoLiteral56, "literal proto prototype 56");
check(literalProtoObj56.inheritedMarker === 290, "literal proto inherited 56");
var protoComputed56 = { dataMarker: 290 + 2 };
var computedProtoObj56 = { ["__proto__"]: protoComputed56, ownMarker: 290 + 3 };
check(Object.getPrototypeOf(computedProtoObj56) === Object.prototype, "computed proto prototype 56");
check(computedProtoObj56.__proto__ === protoComputed56, "computed proto own data 56");
check(computedProtoObj56.ownMarker === 290 + 3, "computed proto other data 56");
var ignoredProtoObj56 = { __proto__: 290, regular56: 290 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj56) === Object.prototype, "non object proto ignored 56");
check(ignoredProtoObj56.regular56 === 290 + 4, "non object proto regular 56");

var protoLiteral57 = { inheritedMarker: 295 };
var literalProtoObj57 = { __proto__: protoLiteral57, ownMarker: 295 + 1 };
check(Object.getPrototypeOf(literalProtoObj57) === protoLiteral57, "literal proto prototype 57");
check(literalProtoObj57.inheritedMarker === 295, "literal proto inherited 57");
var protoComputed57 = { dataMarker: 295 + 2 };
var computedProtoObj57 = { ["__proto__"]: protoComputed57, ownMarker: 295 + 3 };
check(Object.getPrototypeOf(computedProtoObj57) === Object.prototype, "computed proto prototype 57");
check(computedProtoObj57.__proto__ === protoComputed57, "computed proto own data 57");
check(computedProtoObj57.ownMarker === 295 + 3, "computed proto other data 57");
var ignoredProtoObj57 = { __proto__: 295, regular57: 295 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj57) === Object.prototype, "non object proto ignored 57");
check(ignoredProtoObj57.regular57 === 295 + 4, "non object proto regular 57");

var protoLiteral58 = { inheritedMarker: 300 };
var literalProtoObj58 = { __proto__: protoLiteral58, ownMarker: 300 + 1 };
check(Object.getPrototypeOf(literalProtoObj58) === protoLiteral58, "literal proto prototype 58");
check(literalProtoObj58.inheritedMarker === 300, "literal proto inherited 58");
var protoComputed58 = { dataMarker: 300 + 2 };
var computedProtoObj58 = { ["__proto__"]: protoComputed58, ownMarker: 300 + 3 };
check(Object.getPrototypeOf(computedProtoObj58) === Object.prototype, "computed proto prototype 58");
check(computedProtoObj58.__proto__ === protoComputed58, "computed proto own data 58");
check(computedProtoObj58.ownMarker === 300 + 3, "computed proto other data 58");
var ignoredProtoObj58 = { __proto__: 300, regular58: 300 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj58) === Object.prototype, "non object proto ignored 58");
check(ignoredProtoObj58.regular58 === 300 + 4, "non object proto regular 58");

var protoLiteral59 = { inheritedMarker: 305 };
var literalProtoObj59 = { __proto__: protoLiteral59, ownMarker: 305 + 1 };
check(Object.getPrototypeOf(literalProtoObj59) === protoLiteral59, "literal proto prototype 59");
check(literalProtoObj59.inheritedMarker === 305, "literal proto inherited 59");
var protoComputed59 = { dataMarker: 305 + 2 };
var computedProtoObj59 = { ["__proto__"]: protoComputed59, ownMarker: 305 + 3 };
check(Object.getPrototypeOf(computedProtoObj59) === Object.prototype, "computed proto prototype 59");
check(computedProtoObj59.__proto__ === protoComputed59, "computed proto own data 59");
check(computedProtoObj59.ownMarker === 305 + 3, "computed proto other data 59");
var ignoredProtoObj59 = { __proto__: 305, regular59: 305 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj59) === Object.prototype, "non object proto ignored 59");
check(ignoredProtoObj59.regular59 === 305 + 4, "non object proto regular 59");

var protoLiteral60 = { inheritedMarker: 310 };
var literalProtoObj60 = { __proto__: protoLiteral60, ownMarker: 310 + 1 };
check(Object.getPrototypeOf(literalProtoObj60) === protoLiteral60, "literal proto prototype 60");
check(literalProtoObj60.inheritedMarker === 310, "literal proto inherited 60");
var protoComputed60 = { dataMarker: 310 + 2 };
var computedProtoObj60 = { ["__proto__"]: protoComputed60, ownMarker: 310 + 3 };
check(Object.getPrototypeOf(computedProtoObj60) === Object.prototype, "computed proto prototype 60");
check(computedProtoObj60.__proto__ === protoComputed60, "computed proto own data 60");
check(computedProtoObj60.ownMarker === 310 + 3, "computed proto other data 60");
var ignoredProtoObj60 = { __proto__: 310, regular60: 310 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj60) === Object.prototype, "non object proto ignored 60");
check(ignoredProtoObj60.regular60 === 310 + 4, "non object proto regular 60");

var protoLiteral61 = { inheritedMarker: 315 };
var literalProtoObj61 = { __proto__: protoLiteral61, ownMarker: 315 + 1 };
check(Object.getPrototypeOf(literalProtoObj61) === protoLiteral61, "literal proto prototype 61");
check(literalProtoObj61.inheritedMarker === 315, "literal proto inherited 61");
var protoComputed61 = { dataMarker: 315 + 2 };
var computedProtoObj61 = { ["__proto__"]: protoComputed61, ownMarker: 315 + 3 };
check(Object.getPrototypeOf(computedProtoObj61) === Object.prototype, "computed proto prototype 61");
check(computedProtoObj61.__proto__ === protoComputed61, "computed proto own data 61");
check(computedProtoObj61.ownMarker === 315 + 3, "computed proto other data 61");
var ignoredProtoObj61 = { __proto__: 315, regular61: 315 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj61) === Object.prototype, "non object proto ignored 61");
check(ignoredProtoObj61.regular61 === 315 + 4, "non object proto regular 61");

var protoLiteral62 = { inheritedMarker: 320 };
var literalProtoObj62 = { __proto__: protoLiteral62, ownMarker: 320 + 1 };
check(Object.getPrototypeOf(literalProtoObj62) === protoLiteral62, "literal proto prototype 62");
check(literalProtoObj62.inheritedMarker === 320, "literal proto inherited 62");
var protoComputed62 = { dataMarker: 320 + 2 };
var computedProtoObj62 = { ["__proto__"]: protoComputed62, ownMarker: 320 + 3 };
check(Object.getPrototypeOf(computedProtoObj62) === Object.prototype, "computed proto prototype 62");
check(computedProtoObj62.__proto__ === protoComputed62, "computed proto own data 62");
check(computedProtoObj62.ownMarker === 320 + 3, "computed proto other data 62");
var ignoredProtoObj62 = { __proto__: 320, regular62: 320 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj62) === Object.prototype, "non object proto ignored 62");
check(ignoredProtoObj62.regular62 === 320 + 4, "non object proto regular 62");

var protoLiteral63 = { inheritedMarker: 325 };
var literalProtoObj63 = { __proto__: protoLiteral63, ownMarker: 325 + 1 };
check(Object.getPrototypeOf(literalProtoObj63) === protoLiteral63, "literal proto prototype 63");
check(literalProtoObj63.inheritedMarker === 325, "literal proto inherited 63");
var protoComputed63 = { dataMarker: 325 + 2 };
var computedProtoObj63 = { ["__proto__"]: protoComputed63, ownMarker: 325 + 3 };
check(Object.getPrototypeOf(computedProtoObj63) === Object.prototype, "computed proto prototype 63");
check(computedProtoObj63.__proto__ === protoComputed63, "computed proto own data 63");
check(computedProtoObj63.ownMarker === 325 + 3, "computed proto other data 63");
var ignoredProtoObj63 = { __proto__: 325, regular63: 325 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj63) === Object.prototype, "non object proto ignored 63");
check(ignoredProtoObj63.regular63 === 325 + 4, "non object proto regular 63");

var protoLiteral64 = { inheritedMarker: 330 };
var literalProtoObj64 = { __proto__: protoLiteral64, ownMarker: 330 + 1 };
check(Object.getPrototypeOf(literalProtoObj64) === protoLiteral64, "literal proto prototype 64");
check(literalProtoObj64.inheritedMarker === 330, "literal proto inherited 64");
var protoComputed64 = { dataMarker: 330 + 2 };
var computedProtoObj64 = { ["__proto__"]: protoComputed64, ownMarker: 330 + 3 };
check(Object.getPrototypeOf(computedProtoObj64) === Object.prototype, "computed proto prototype 64");
check(computedProtoObj64.__proto__ === protoComputed64, "computed proto own data 64");
check(computedProtoObj64.ownMarker === 330 + 3, "computed proto other data 64");
var ignoredProtoObj64 = { __proto__: 330, regular64: 330 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj64) === Object.prototype, "non object proto ignored 64");
check(ignoredProtoObj64.regular64 === 330 + 4, "non object proto regular 64");

var protoLiteral65 = { inheritedMarker: 335 };
var literalProtoObj65 = { __proto__: protoLiteral65, ownMarker: 335 + 1 };
check(Object.getPrototypeOf(literalProtoObj65) === protoLiteral65, "literal proto prototype 65");
check(literalProtoObj65.inheritedMarker === 335, "literal proto inherited 65");
var protoComputed65 = { dataMarker: 335 + 2 };
var computedProtoObj65 = { ["__proto__"]: protoComputed65, ownMarker: 335 + 3 };
check(Object.getPrototypeOf(computedProtoObj65) === Object.prototype, "computed proto prototype 65");
check(computedProtoObj65.__proto__ === protoComputed65, "computed proto own data 65");
check(computedProtoObj65.ownMarker === 335 + 3, "computed proto other data 65");
var ignoredProtoObj65 = { __proto__: 335, regular65: 335 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj65) === Object.prototype, "non object proto ignored 65");
check(ignoredProtoObj65.regular65 === 335 + 4, "non object proto regular 65");

var protoLiteral66 = { inheritedMarker: 340 };
var literalProtoObj66 = { __proto__: protoLiteral66, ownMarker: 340 + 1 };
check(Object.getPrototypeOf(literalProtoObj66) === protoLiteral66, "literal proto prototype 66");
check(literalProtoObj66.inheritedMarker === 340, "literal proto inherited 66");
var protoComputed66 = { dataMarker: 340 + 2 };
var computedProtoObj66 = { ["__proto__"]: protoComputed66, ownMarker: 340 + 3 };
check(Object.getPrototypeOf(computedProtoObj66) === Object.prototype, "computed proto prototype 66");
check(computedProtoObj66.__proto__ === protoComputed66, "computed proto own data 66");
check(computedProtoObj66.ownMarker === 340 + 3, "computed proto other data 66");
var ignoredProtoObj66 = { __proto__: 340, regular66: 340 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj66) === Object.prototype, "non object proto ignored 66");
check(ignoredProtoObj66.regular66 === 340 + 4, "non object proto regular 66");

var protoLiteral67 = { inheritedMarker: 345 };
var literalProtoObj67 = { __proto__: protoLiteral67, ownMarker: 345 + 1 };
check(Object.getPrototypeOf(literalProtoObj67) === protoLiteral67, "literal proto prototype 67");
check(literalProtoObj67.inheritedMarker === 345, "literal proto inherited 67");
var protoComputed67 = { dataMarker: 345 + 2 };
var computedProtoObj67 = { ["__proto__"]: protoComputed67, ownMarker: 345 + 3 };
check(Object.getPrototypeOf(computedProtoObj67) === Object.prototype, "computed proto prototype 67");
check(computedProtoObj67.__proto__ === protoComputed67, "computed proto own data 67");
check(computedProtoObj67.ownMarker === 345 + 3, "computed proto other data 67");
var ignoredProtoObj67 = { __proto__: 345, regular67: 345 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj67) === Object.prototype, "non object proto ignored 67");
check(ignoredProtoObj67.regular67 === 345 + 4, "non object proto regular 67");

var protoLiteral68 = { inheritedMarker: 350 };
var literalProtoObj68 = { __proto__: protoLiteral68, ownMarker: 350 + 1 };
check(Object.getPrototypeOf(literalProtoObj68) === protoLiteral68, "literal proto prototype 68");
check(literalProtoObj68.inheritedMarker === 350, "literal proto inherited 68");
var protoComputed68 = { dataMarker: 350 + 2 };
var computedProtoObj68 = { ["__proto__"]: protoComputed68, ownMarker: 350 + 3 };
check(Object.getPrototypeOf(computedProtoObj68) === Object.prototype, "computed proto prototype 68");
check(computedProtoObj68.__proto__ === protoComputed68, "computed proto own data 68");
check(computedProtoObj68.ownMarker === 350 + 3, "computed proto other data 68");
var ignoredProtoObj68 = { __proto__: 350, regular68: 350 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj68) === Object.prototype, "non object proto ignored 68");
check(ignoredProtoObj68.regular68 === 350 + 4, "non object proto regular 68");

var protoLiteral69 = { inheritedMarker: 355 };
var literalProtoObj69 = { __proto__: protoLiteral69, ownMarker: 355 + 1 };
check(Object.getPrototypeOf(literalProtoObj69) === protoLiteral69, "literal proto prototype 69");
check(literalProtoObj69.inheritedMarker === 355, "literal proto inherited 69");
var protoComputed69 = { dataMarker: 355 + 2 };
var computedProtoObj69 = { ["__proto__"]: protoComputed69, ownMarker: 355 + 3 };
check(Object.getPrototypeOf(computedProtoObj69) === Object.prototype, "computed proto prototype 69");
check(computedProtoObj69.__proto__ === protoComputed69, "computed proto own data 69");
check(computedProtoObj69.ownMarker === 355 + 3, "computed proto other data 69");
var ignoredProtoObj69 = { __proto__: 355, regular69: 355 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj69) === Object.prototype, "non object proto ignored 69");
check(ignoredProtoObj69.regular69 === 355 + 4, "non object proto regular 69");

var protoLiteral70 = { inheritedMarker: 360 };
var literalProtoObj70 = { __proto__: protoLiteral70, ownMarker: 360 + 1 };
check(Object.getPrototypeOf(literalProtoObj70) === protoLiteral70, "literal proto prototype 70");
check(literalProtoObj70.inheritedMarker === 360, "literal proto inherited 70");
var protoComputed70 = { dataMarker: 360 + 2 };
var computedProtoObj70 = { ["__proto__"]: protoComputed70, ownMarker: 360 + 3 };
check(Object.getPrototypeOf(computedProtoObj70) === Object.prototype, "computed proto prototype 70");
check(computedProtoObj70.__proto__ === protoComputed70, "computed proto own data 70");
check(computedProtoObj70.ownMarker === 360 + 3, "computed proto other data 70");
var ignoredProtoObj70 = { __proto__: 360, regular70: 360 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj70) === Object.prototype, "non object proto ignored 70");
check(ignoredProtoObj70.regular70 === 360 + 4, "non object proto regular 70");

var protoLiteral71 = { inheritedMarker: 365 };
var literalProtoObj71 = { __proto__: protoLiteral71, ownMarker: 365 + 1 };
check(Object.getPrototypeOf(literalProtoObj71) === protoLiteral71, "literal proto prototype 71");
check(literalProtoObj71.inheritedMarker === 365, "literal proto inherited 71");
var protoComputed71 = { dataMarker: 365 + 2 };
var computedProtoObj71 = { ["__proto__"]: protoComputed71, ownMarker: 365 + 3 };
check(Object.getPrototypeOf(computedProtoObj71) === Object.prototype, "computed proto prototype 71");
check(computedProtoObj71.__proto__ === protoComputed71, "computed proto own data 71");
check(computedProtoObj71.ownMarker === 365 + 3, "computed proto other data 71");
var ignoredProtoObj71 = { __proto__: 365, regular71: 365 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj71) === Object.prototype, "non object proto ignored 71");
check(ignoredProtoObj71.regular71 === 365 + 4, "non object proto regular 71");

var protoLiteral72 = { inheritedMarker: 370 };
var literalProtoObj72 = { __proto__: protoLiteral72, ownMarker: 370 + 1 };
check(Object.getPrototypeOf(literalProtoObj72) === protoLiteral72, "literal proto prototype 72");
check(literalProtoObj72.inheritedMarker === 370, "literal proto inherited 72");
var protoComputed72 = { dataMarker: 370 + 2 };
var computedProtoObj72 = { ["__proto__"]: protoComputed72, ownMarker: 370 + 3 };
check(Object.getPrototypeOf(computedProtoObj72) === Object.prototype, "computed proto prototype 72");
check(computedProtoObj72.__proto__ === protoComputed72, "computed proto own data 72");
check(computedProtoObj72.ownMarker === 370 + 3, "computed proto other data 72");
var ignoredProtoObj72 = { __proto__: 370, regular72: 370 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj72) === Object.prototype, "non object proto ignored 72");
check(ignoredProtoObj72.regular72 === 370 + 4, "non object proto regular 72");

var protoLiteral73 = { inheritedMarker: 375 };
var literalProtoObj73 = { __proto__: protoLiteral73, ownMarker: 375 + 1 };
check(Object.getPrototypeOf(literalProtoObj73) === protoLiteral73, "literal proto prototype 73");
check(literalProtoObj73.inheritedMarker === 375, "literal proto inherited 73");
var protoComputed73 = { dataMarker: 375 + 2 };
var computedProtoObj73 = { ["__proto__"]: protoComputed73, ownMarker: 375 + 3 };
check(Object.getPrototypeOf(computedProtoObj73) === Object.prototype, "computed proto prototype 73");
check(computedProtoObj73.__proto__ === protoComputed73, "computed proto own data 73");
check(computedProtoObj73.ownMarker === 375 + 3, "computed proto other data 73");
var ignoredProtoObj73 = { __proto__: 375, regular73: 375 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj73) === Object.prototype, "non object proto ignored 73");
check(ignoredProtoObj73.regular73 === 375 + 4, "non object proto regular 73");

var protoLiteral74 = { inheritedMarker: 380 };
var literalProtoObj74 = { __proto__: protoLiteral74, ownMarker: 380 + 1 };
check(Object.getPrototypeOf(literalProtoObj74) === protoLiteral74, "literal proto prototype 74");
check(literalProtoObj74.inheritedMarker === 380, "literal proto inherited 74");
var protoComputed74 = { dataMarker: 380 + 2 };
var computedProtoObj74 = { ["__proto__"]: protoComputed74, ownMarker: 380 + 3 };
check(Object.getPrototypeOf(computedProtoObj74) === Object.prototype, "computed proto prototype 74");
check(computedProtoObj74.__proto__ === protoComputed74, "computed proto own data 74");
check(computedProtoObj74.ownMarker === 380 + 3, "computed proto other data 74");
var ignoredProtoObj74 = { __proto__: 380, regular74: 380 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj74) === Object.prototype, "non object proto ignored 74");
check(ignoredProtoObj74.regular74 === 380 + 4, "non object proto regular 74");

var protoLiteral75 = { inheritedMarker: 385 };
var literalProtoObj75 = { __proto__: protoLiteral75, ownMarker: 385 + 1 };
check(Object.getPrototypeOf(literalProtoObj75) === protoLiteral75, "literal proto prototype 75");
check(literalProtoObj75.inheritedMarker === 385, "literal proto inherited 75");
var protoComputed75 = { dataMarker: 385 + 2 };
var computedProtoObj75 = { ["__proto__"]: protoComputed75, ownMarker: 385 + 3 };
check(Object.getPrototypeOf(computedProtoObj75) === Object.prototype, "computed proto prototype 75");
check(computedProtoObj75.__proto__ === protoComputed75, "computed proto own data 75");
check(computedProtoObj75.ownMarker === 385 + 3, "computed proto other data 75");
var ignoredProtoObj75 = { __proto__: 385, regular75: 385 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj75) === Object.prototype, "non object proto ignored 75");
check(ignoredProtoObj75.regular75 === 385 + 4, "non object proto regular 75");

var protoLiteral76 = { inheritedMarker: 390 };
var literalProtoObj76 = { __proto__: protoLiteral76, ownMarker: 390 + 1 };
check(Object.getPrototypeOf(literalProtoObj76) === protoLiteral76, "literal proto prototype 76");
check(literalProtoObj76.inheritedMarker === 390, "literal proto inherited 76");
var protoComputed76 = { dataMarker: 390 + 2 };
var computedProtoObj76 = { ["__proto__"]: protoComputed76, ownMarker: 390 + 3 };
check(Object.getPrototypeOf(computedProtoObj76) === Object.prototype, "computed proto prototype 76");
check(computedProtoObj76.__proto__ === protoComputed76, "computed proto own data 76");
check(computedProtoObj76.ownMarker === 390 + 3, "computed proto other data 76");
var ignoredProtoObj76 = { __proto__: 390, regular76: 390 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj76) === Object.prototype, "non object proto ignored 76");
check(ignoredProtoObj76.regular76 === 390 + 4, "non object proto regular 76");

var protoLiteral77 = { inheritedMarker: 395 };
var literalProtoObj77 = { __proto__: protoLiteral77, ownMarker: 395 + 1 };
check(Object.getPrototypeOf(literalProtoObj77) === protoLiteral77, "literal proto prototype 77");
check(literalProtoObj77.inheritedMarker === 395, "literal proto inherited 77");
var protoComputed77 = { dataMarker: 395 + 2 };
var computedProtoObj77 = { ["__proto__"]: protoComputed77, ownMarker: 395 + 3 };
check(Object.getPrototypeOf(computedProtoObj77) === Object.prototype, "computed proto prototype 77");
check(computedProtoObj77.__proto__ === protoComputed77, "computed proto own data 77");
check(computedProtoObj77.ownMarker === 395 + 3, "computed proto other data 77");
var ignoredProtoObj77 = { __proto__: 395, regular77: 395 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj77) === Object.prototype, "non object proto ignored 77");
check(ignoredProtoObj77.regular77 === 395 + 4, "non object proto regular 77");

var protoLiteral78 = { inheritedMarker: 400 };
var literalProtoObj78 = { __proto__: protoLiteral78, ownMarker: 400 + 1 };
check(Object.getPrototypeOf(literalProtoObj78) === protoLiteral78, "literal proto prototype 78");
check(literalProtoObj78.inheritedMarker === 400, "literal proto inherited 78");
var protoComputed78 = { dataMarker: 400 + 2 };
var computedProtoObj78 = { ["__proto__"]: protoComputed78, ownMarker: 400 + 3 };
check(Object.getPrototypeOf(computedProtoObj78) === Object.prototype, "computed proto prototype 78");
check(computedProtoObj78.__proto__ === protoComputed78, "computed proto own data 78");
check(computedProtoObj78.ownMarker === 400 + 3, "computed proto other data 78");
var ignoredProtoObj78 = { __proto__: 400, regular78: 400 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj78) === Object.prototype, "non object proto ignored 78");
check(ignoredProtoObj78.regular78 === 400 + 4, "non object proto regular 78");

var protoLiteral79 = { inheritedMarker: 405 };
var literalProtoObj79 = { __proto__: protoLiteral79, ownMarker: 405 + 1 };
check(Object.getPrototypeOf(literalProtoObj79) === protoLiteral79, "literal proto prototype 79");
check(literalProtoObj79.inheritedMarker === 405, "literal proto inherited 79");
var protoComputed79 = { dataMarker: 405 + 2 };
var computedProtoObj79 = { ["__proto__"]: protoComputed79, ownMarker: 405 + 3 };
check(Object.getPrototypeOf(computedProtoObj79) === Object.prototype, "computed proto prototype 79");
check(computedProtoObj79.__proto__ === protoComputed79, "computed proto own data 79");
check(computedProtoObj79.ownMarker === 405 + 3, "computed proto other data 79");
var ignoredProtoObj79 = { __proto__: 405, regular79: 405 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj79) === Object.prototype, "non object proto ignored 79");
check(ignoredProtoObj79.regular79 === 405 + 4, "non object proto regular 79");

var protoLiteral80 = { inheritedMarker: 410 };
var literalProtoObj80 = { __proto__: protoLiteral80, ownMarker: 410 + 1 };
check(Object.getPrototypeOf(literalProtoObj80) === protoLiteral80, "literal proto prototype 80");
check(literalProtoObj80.inheritedMarker === 410, "literal proto inherited 80");
var protoComputed80 = { dataMarker: 410 + 2 };
var computedProtoObj80 = { ["__proto__"]: protoComputed80, ownMarker: 410 + 3 };
check(Object.getPrototypeOf(computedProtoObj80) === Object.prototype, "computed proto prototype 80");
check(computedProtoObj80.__proto__ === protoComputed80, "computed proto own data 80");
check(computedProtoObj80.ownMarker === 410 + 3, "computed proto other data 80");
var ignoredProtoObj80 = { __proto__: 410, regular80: 410 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj80) === Object.prototype, "non object proto ignored 80");
check(ignoredProtoObj80.regular80 === 410 + 4, "non object proto regular 80");

var protoLiteral81 = { inheritedMarker: 415 };
var literalProtoObj81 = { __proto__: protoLiteral81, ownMarker: 415 + 1 };
check(Object.getPrototypeOf(literalProtoObj81) === protoLiteral81, "literal proto prototype 81");
check(literalProtoObj81.inheritedMarker === 415, "literal proto inherited 81");
var protoComputed81 = { dataMarker: 415 + 2 };
var computedProtoObj81 = { ["__proto__"]: protoComputed81, ownMarker: 415 + 3 };
check(Object.getPrototypeOf(computedProtoObj81) === Object.prototype, "computed proto prototype 81");
check(computedProtoObj81.__proto__ === protoComputed81, "computed proto own data 81");
check(computedProtoObj81.ownMarker === 415 + 3, "computed proto other data 81");
var ignoredProtoObj81 = { __proto__: 415, regular81: 415 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj81) === Object.prototype, "non object proto ignored 81");
check(ignoredProtoObj81.regular81 === 415 + 4, "non object proto regular 81");

var protoLiteral82 = { inheritedMarker: 420 };
var literalProtoObj82 = { __proto__: protoLiteral82, ownMarker: 420 + 1 };
check(Object.getPrototypeOf(literalProtoObj82) === protoLiteral82, "literal proto prototype 82");
check(literalProtoObj82.inheritedMarker === 420, "literal proto inherited 82");
var protoComputed82 = { dataMarker: 420 + 2 };
var computedProtoObj82 = { ["__proto__"]: protoComputed82, ownMarker: 420 + 3 };
check(Object.getPrototypeOf(computedProtoObj82) === Object.prototype, "computed proto prototype 82");
check(computedProtoObj82.__proto__ === protoComputed82, "computed proto own data 82");
check(computedProtoObj82.ownMarker === 420 + 3, "computed proto other data 82");
var ignoredProtoObj82 = { __proto__: 420, regular82: 420 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj82) === Object.prototype, "non object proto ignored 82");
check(ignoredProtoObj82.regular82 === 420 + 4, "non object proto regular 82");

var protoLiteral83 = { inheritedMarker: 425 };
var literalProtoObj83 = { __proto__: protoLiteral83, ownMarker: 425 + 1 };
check(Object.getPrototypeOf(literalProtoObj83) === protoLiteral83, "literal proto prototype 83");
check(literalProtoObj83.inheritedMarker === 425, "literal proto inherited 83");
var protoComputed83 = { dataMarker: 425 + 2 };
var computedProtoObj83 = { ["__proto__"]: protoComputed83, ownMarker: 425 + 3 };
check(Object.getPrototypeOf(computedProtoObj83) === Object.prototype, "computed proto prototype 83");
check(computedProtoObj83.__proto__ === protoComputed83, "computed proto own data 83");
check(computedProtoObj83.ownMarker === 425 + 3, "computed proto other data 83");
var ignoredProtoObj83 = { __proto__: 425, regular83: 425 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj83) === Object.prototype, "non object proto ignored 83");
check(ignoredProtoObj83.regular83 === 425 + 4, "non object proto regular 83");

var protoLiteral84 = { inheritedMarker: 430 };
var literalProtoObj84 = { __proto__: protoLiteral84, ownMarker: 430 + 1 };
check(Object.getPrototypeOf(literalProtoObj84) === protoLiteral84, "literal proto prototype 84");
check(literalProtoObj84.inheritedMarker === 430, "literal proto inherited 84");
var protoComputed84 = { dataMarker: 430 + 2 };
var computedProtoObj84 = { ["__proto__"]: protoComputed84, ownMarker: 430 + 3 };
check(Object.getPrototypeOf(computedProtoObj84) === Object.prototype, "computed proto prototype 84");
check(computedProtoObj84.__proto__ === protoComputed84, "computed proto own data 84");
check(computedProtoObj84.ownMarker === 430 + 3, "computed proto other data 84");
var ignoredProtoObj84 = { __proto__: 430, regular84: 430 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj84) === Object.prototype, "non object proto ignored 84");
check(ignoredProtoObj84.regular84 === 430 + 4, "non object proto regular 84");

var protoLiteral85 = { inheritedMarker: 435 };
var literalProtoObj85 = { __proto__: protoLiteral85, ownMarker: 435 + 1 };
check(Object.getPrototypeOf(literalProtoObj85) === protoLiteral85, "literal proto prototype 85");
check(literalProtoObj85.inheritedMarker === 435, "literal proto inherited 85");
var protoComputed85 = { dataMarker: 435 + 2 };
var computedProtoObj85 = { ["__proto__"]: protoComputed85, ownMarker: 435 + 3 };
check(Object.getPrototypeOf(computedProtoObj85) === Object.prototype, "computed proto prototype 85");
check(computedProtoObj85.__proto__ === protoComputed85, "computed proto own data 85");
check(computedProtoObj85.ownMarker === 435 + 3, "computed proto other data 85");
var ignoredProtoObj85 = { __proto__: 435, regular85: 435 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj85) === Object.prototype, "non object proto ignored 85");
check(ignoredProtoObj85.regular85 === 435 + 4, "non object proto regular 85");

var protoLiteral86 = { inheritedMarker: 440 };
var literalProtoObj86 = { __proto__: protoLiteral86, ownMarker: 440 + 1 };
check(Object.getPrototypeOf(literalProtoObj86) === protoLiteral86, "literal proto prototype 86");
check(literalProtoObj86.inheritedMarker === 440, "literal proto inherited 86");
var protoComputed86 = { dataMarker: 440 + 2 };
var computedProtoObj86 = { ["__proto__"]: protoComputed86, ownMarker: 440 + 3 };
check(Object.getPrototypeOf(computedProtoObj86) === Object.prototype, "computed proto prototype 86");
check(computedProtoObj86.__proto__ === protoComputed86, "computed proto own data 86");
check(computedProtoObj86.ownMarker === 440 + 3, "computed proto other data 86");
var ignoredProtoObj86 = { __proto__: 440, regular86: 440 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj86) === Object.prototype, "non object proto ignored 86");
check(ignoredProtoObj86.regular86 === 440 + 4, "non object proto regular 86");

var protoLiteral87 = { inheritedMarker: 445 };
var literalProtoObj87 = { __proto__: protoLiteral87, ownMarker: 445 + 1 };
check(Object.getPrototypeOf(literalProtoObj87) === protoLiteral87, "literal proto prototype 87");
check(literalProtoObj87.inheritedMarker === 445, "literal proto inherited 87");
var protoComputed87 = { dataMarker: 445 + 2 };
var computedProtoObj87 = { ["__proto__"]: protoComputed87, ownMarker: 445 + 3 };
check(Object.getPrototypeOf(computedProtoObj87) === Object.prototype, "computed proto prototype 87");
check(computedProtoObj87.__proto__ === protoComputed87, "computed proto own data 87");
check(computedProtoObj87.ownMarker === 445 + 3, "computed proto other data 87");
var ignoredProtoObj87 = { __proto__: 445, regular87: 445 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj87) === Object.prototype, "non object proto ignored 87");
check(ignoredProtoObj87.regular87 === 445 + 4, "non object proto regular 87");

var protoLiteral88 = { inheritedMarker: 450 };
var literalProtoObj88 = { __proto__: protoLiteral88, ownMarker: 450 + 1 };
check(Object.getPrototypeOf(literalProtoObj88) === protoLiteral88, "literal proto prototype 88");
check(literalProtoObj88.inheritedMarker === 450, "literal proto inherited 88");
var protoComputed88 = { dataMarker: 450 + 2 };
var computedProtoObj88 = { ["__proto__"]: protoComputed88, ownMarker: 450 + 3 };
check(Object.getPrototypeOf(computedProtoObj88) === Object.prototype, "computed proto prototype 88");
check(computedProtoObj88.__proto__ === protoComputed88, "computed proto own data 88");
check(computedProtoObj88.ownMarker === 450 + 3, "computed proto other data 88");
var ignoredProtoObj88 = { __proto__: 450, regular88: 450 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj88) === Object.prototype, "non object proto ignored 88");
check(ignoredProtoObj88.regular88 === 450 + 4, "non object proto regular 88");

var protoLiteral89 = { inheritedMarker: 455 };
var literalProtoObj89 = { __proto__: protoLiteral89, ownMarker: 455 + 1 };
check(Object.getPrototypeOf(literalProtoObj89) === protoLiteral89, "literal proto prototype 89");
check(literalProtoObj89.inheritedMarker === 455, "literal proto inherited 89");
var protoComputed89 = { dataMarker: 455 + 2 };
var computedProtoObj89 = { ["__proto__"]: protoComputed89, ownMarker: 455 + 3 };
check(Object.getPrototypeOf(computedProtoObj89) === Object.prototype, "computed proto prototype 89");
check(computedProtoObj89.__proto__ === protoComputed89, "computed proto own data 89");
check(computedProtoObj89.ownMarker === 455 + 3, "computed proto other data 89");
var ignoredProtoObj89 = { __proto__: 455, regular89: 455 + 4 };
check(Object.getPrototypeOf(ignoredProtoObj89) === Object.prototype, "non object proto ignored 89");
check(ignoredProtoObj89.regular89 === 455 + 4, "non object proto regular 89");

check(score > 0, "computed proto score");
