// behavior: bracket-access-evaluates-base-then-expression-key
// expected: pass
// goal: script
// size: large
// variant: script.sloppy

var bracketScore = 0;
function bracketCheck(condition, label) {
if (!condition) {
throw label;
}
bracketScore = bracketScore + 1;
return true;
}
var bracketOrder = 0;
function bracketBase(tag, object) { bracketOrder = bracketOrder * 10 + tag; return object; }
function bracketKey(tag, key) { bracketOrder = bracketOrder * 10 + tag; return key; }
function bracketValue(tag, value) { bracketOrder = bracketOrder * 10 + tag; return value; }
var bracketTotal = 0;
var bracketObj0 = { k0: 3, k1: 7, nested: { hit: 11 } };
bracketOrder = 0;
var bracketRead0 = bracketBase(1, bracketObj0)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 0");
bracketCheck(bracketRead0 === 3, "bracket read value 0");
bracketOrder = 0;
bracketBase(3, bracketObj0)[bracketKey(4, "k1")] = bracketValue(5, 50);
bracketCheck(bracketOrder === 345, "bracket write order 0");
bracketCheck(bracketObj0.k1 === 50, "bracket write value 0");
bracketOrder = 0;
var bracketNested0 = bracketBase(6, bracketObj0)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 0");
bracketCheck(bracketNested0 === 11, "bracket nested value 0");
bracketTotal = bracketTotal + bracketRead0 + bracketObj0.k1 + bracketNested0;
var bracketObj1 = { k0: 4, k1: 8, nested: { hit: 12 } };
bracketOrder = 0;
var bracketRead1 = bracketBase(1, bracketObj1)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 1");
bracketCheck(bracketRead1 === 4, "bracket read value 1");
bracketOrder = 0;
bracketBase(3, bracketObj1)[bracketKey(4, "k1")] = bracketValue(5, 51);
bracketCheck(bracketOrder === 345, "bracket write order 1");
bracketCheck(bracketObj1.k1 === 51, "bracket write value 1");
bracketOrder = 0;
var bracketNested1 = bracketBase(6, bracketObj1)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 1");
bracketCheck(bracketNested1 === 12, "bracket nested value 1");
bracketTotal = bracketTotal + bracketRead1 + bracketObj1.k1 + bracketNested1;
var bracketObj2 = { k0: 5, k1: 9, nested: { hit: 13 } };
bracketOrder = 0;
var bracketRead2 = bracketBase(1, bracketObj2)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 2");
bracketCheck(bracketRead2 === 5, "bracket read value 2");
bracketOrder = 0;
bracketBase(3, bracketObj2)[bracketKey(4, "k1")] = bracketValue(5, 52);
bracketCheck(bracketOrder === 345, "bracket write order 2");
bracketCheck(bracketObj2.k1 === 52, "bracket write value 2");
bracketOrder = 0;
var bracketNested2 = bracketBase(6, bracketObj2)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 2");
bracketCheck(bracketNested2 === 13, "bracket nested value 2");
bracketTotal = bracketTotal + bracketRead2 + bracketObj2.k1 + bracketNested2;
var bracketObj3 = { k0: 6, k1: 10, nested: { hit: 14 } };
bracketOrder = 0;
var bracketRead3 = bracketBase(1, bracketObj3)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 3");
bracketCheck(bracketRead3 === 6, "bracket read value 3");
bracketOrder = 0;
bracketBase(3, bracketObj3)[bracketKey(4, "k1")] = bracketValue(5, 53);
bracketCheck(bracketOrder === 345, "bracket write order 3");
bracketCheck(bracketObj3.k1 === 53, "bracket write value 3");
bracketOrder = 0;
var bracketNested3 = bracketBase(6, bracketObj3)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 3");
bracketCheck(bracketNested3 === 14, "bracket nested value 3");
bracketTotal = bracketTotal + bracketRead3 + bracketObj3.k1 + bracketNested3;
var bracketObj4 = { k0: 7, k1: 11, nested: { hit: 15 } };
bracketOrder = 0;
var bracketRead4 = bracketBase(1, bracketObj4)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 4");
bracketCheck(bracketRead4 === 7, "bracket read value 4");
bracketOrder = 0;
bracketBase(3, bracketObj4)[bracketKey(4, "k1")] = bracketValue(5, 54);
bracketCheck(bracketOrder === 345, "bracket write order 4");
bracketCheck(bracketObj4.k1 === 54, "bracket write value 4");
bracketOrder = 0;
var bracketNested4 = bracketBase(6, bracketObj4)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 4");
bracketCheck(bracketNested4 === 15, "bracket nested value 4");
bracketTotal = bracketTotal + bracketRead4 + bracketObj4.k1 + bracketNested4;
var bracketObj5 = { k0: 8, k1: 12, nested: { hit: 16 } };
bracketOrder = 0;
var bracketRead5 = bracketBase(1, bracketObj5)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 5");
bracketCheck(bracketRead5 === 8, "bracket read value 5");
bracketOrder = 0;
bracketBase(3, bracketObj5)[bracketKey(4, "k1")] = bracketValue(5, 55);
bracketCheck(bracketOrder === 345, "bracket write order 5");
bracketCheck(bracketObj5.k1 === 55, "bracket write value 5");
bracketOrder = 0;
var bracketNested5 = bracketBase(6, bracketObj5)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 5");
bracketCheck(bracketNested5 === 16, "bracket nested value 5");
bracketTotal = bracketTotal + bracketRead5 + bracketObj5.k1 + bracketNested5;
var bracketObj6 = { k0: 9, k1: 13, nested: { hit: 17 } };
bracketOrder = 0;
var bracketRead6 = bracketBase(1, bracketObj6)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 6");
bracketCheck(bracketRead6 === 9, "bracket read value 6");
bracketOrder = 0;
bracketBase(3, bracketObj6)[bracketKey(4, "k1")] = bracketValue(5, 56);
bracketCheck(bracketOrder === 345, "bracket write order 6");
bracketCheck(bracketObj6.k1 === 56, "bracket write value 6");
bracketOrder = 0;
var bracketNested6 = bracketBase(6, bracketObj6)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 6");
bracketCheck(bracketNested6 === 17, "bracket nested value 6");
bracketTotal = bracketTotal + bracketRead6 + bracketObj6.k1 + bracketNested6;
var bracketObj7 = { k0: 10, k1: 14, nested: { hit: 18 } };
bracketOrder = 0;
var bracketRead7 = bracketBase(1, bracketObj7)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 7");
bracketCheck(bracketRead7 === 10, "bracket read value 7");
bracketOrder = 0;
bracketBase(3, bracketObj7)[bracketKey(4, "k1")] = bracketValue(5, 57);
bracketCheck(bracketOrder === 345, "bracket write order 7");
bracketCheck(bracketObj7.k1 === 57, "bracket write value 7");
bracketOrder = 0;
var bracketNested7 = bracketBase(6, bracketObj7)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 7");
bracketCheck(bracketNested7 === 18, "bracket nested value 7");
bracketTotal = bracketTotal + bracketRead7 + bracketObj7.k1 + bracketNested7;
var bracketObj8 = { k0: 11, k1: 15, nested: { hit: 19 } };
bracketOrder = 0;
var bracketRead8 = bracketBase(1, bracketObj8)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 8");
bracketCheck(bracketRead8 === 11, "bracket read value 8");
bracketOrder = 0;
bracketBase(3, bracketObj8)[bracketKey(4, "k1")] = bracketValue(5, 58);
bracketCheck(bracketOrder === 345, "bracket write order 8");
bracketCheck(bracketObj8.k1 === 58, "bracket write value 8");
bracketOrder = 0;
var bracketNested8 = bracketBase(6, bracketObj8)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 8");
bracketCheck(bracketNested8 === 19, "bracket nested value 8");
bracketTotal = bracketTotal + bracketRead8 + bracketObj8.k1 + bracketNested8;
var bracketObj9 = { k0: 12, k1: 16, nested: { hit: 20 } };
bracketOrder = 0;
var bracketRead9 = bracketBase(1, bracketObj9)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 9");
bracketCheck(bracketRead9 === 12, "bracket read value 9");
bracketOrder = 0;
bracketBase(3, bracketObj9)[bracketKey(4, "k1")] = bracketValue(5, 59);
bracketCheck(bracketOrder === 345, "bracket write order 9");
bracketCheck(bracketObj9.k1 === 59, "bracket write value 9");
bracketOrder = 0;
var bracketNested9 = bracketBase(6, bracketObj9)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 9");
bracketCheck(bracketNested9 === 20, "bracket nested value 9");
bracketTotal = bracketTotal + bracketRead9 + bracketObj9.k1 + bracketNested9;
var bracketObj10 = { k0: 13, k1: 17, nested: { hit: 21 } };
bracketOrder = 0;
var bracketRead10 = bracketBase(1, bracketObj10)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 10");
bracketCheck(bracketRead10 === 13, "bracket read value 10");
bracketOrder = 0;
bracketBase(3, bracketObj10)[bracketKey(4, "k1")] = bracketValue(5, 60);
bracketCheck(bracketOrder === 345, "bracket write order 10");
bracketCheck(bracketObj10.k1 === 60, "bracket write value 10");
bracketOrder = 0;
var bracketNested10 = bracketBase(6, bracketObj10)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 10");
bracketCheck(bracketNested10 === 21, "bracket nested value 10");
bracketTotal = bracketTotal + bracketRead10 + bracketObj10.k1 + bracketNested10;
var bracketObj11 = { k0: 14, k1: 18, nested: { hit: 22 } };
bracketOrder = 0;
var bracketRead11 = bracketBase(1, bracketObj11)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 11");
bracketCheck(bracketRead11 === 14, "bracket read value 11");
bracketOrder = 0;
bracketBase(3, bracketObj11)[bracketKey(4, "k1")] = bracketValue(5, 61);
bracketCheck(bracketOrder === 345, "bracket write order 11");
bracketCheck(bracketObj11.k1 === 61, "bracket write value 11");
bracketOrder = 0;
var bracketNested11 = bracketBase(6, bracketObj11)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 11");
bracketCheck(bracketNested11 === 22, "bracket nested value 11");
bracketTotal = bracketTotal + bracketRead11 + bracketObj11.k1 + bracketNested11;
var bracketObj12 = { k0: 15, k1: 19, nested: { hit: 23 } };
bracketOrder = 0;
var bracketRead12 = bracketBase(1, bracketObj12)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 12");
bracketCheck(bracketRead12 === 15, "bracket read value 12");
bracketOrder = 0;
bracketBase(3, bracketObj12)[bracketKey(4, "k1")] = bracketValue(5, 62);
bracketCheck(bracketOrder === 345, "bracket write order 12");
bracketCheck(bracketObj12.k1 === 62, "bracket write value 12");
bracketOrder = 0;
var bracketNested12 = bracketBase(6, bracketObj12)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 12");
bracketCheck(bracketNested12 === 23, "bracket nested value 12");
bracketTotal = bracketTotal + bracketRead12 + bracketObj12.k1 + bracketNested12;
var bracketObj13 = { k0: 16, k1: 20, nested: { hit: 24 } };
bracketOrder = 0;
var bracketRead13 = bracketBase(1, bracketObj13)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 13");
bracketCheck(bracketRead13 === 16, "bracket read value 13");
bracketOrder = 0;
bracketBase(3, bracketObj13)[bracketKey(4, "k1")] = bracketValue(5, 63);
bracketCheck(bracketOrder === 345, "bracket write order 13");
bracketCheck(bracketObj13.k1 === 63, "bracket write value 13");
bracketOrder = 0;
var bracketNested13 = bracketBase(6, bracketObj13)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 13");
bracketCheck(bracketNested13 === 24, "bracket nested value 13");
bracketTotal = bracketTotal + bracketRead13 + bracketObj13.k1 + bracketNested13;
var bracketObj14 = { k0: 17, k1: 21, nested: { hit: 25 } };
bracketOrder = 0;
var bracketRead14 = bracketBase(1, bracketObj14)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 14");
bracketCheck(bracketRead14 === 17, "bracket read value 14");
bracketOrder = 0;
bracketBase(3, bracketObj14)[bracketKey(4, "k1")] = bracketValue(5, 64);
bracketCheck(bracketOrder === 345, "bracket write order 14");
bracketCheck(bracketObj14.k1 === 64, "bracket write value 14");
bracketOrder = 0;
var bracketNested14 = bracketBase(6, bracketObj14)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 14");
bracketCheck(bracketNested14 === 25, "bracket nested value 14");
bracketTotal = bracketTotal + bracketRead14 + bracketObj14.k1 + bracketNested14;
var bracketObj15 = { k0: 18, k1: 22, nested: { hit: 26 } };
bracketOrder = 0;
var bracketRead15 = bracketBase(1, bracketObj15)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 15");
bracketCheck(bracketRead15 === 18, "bracket read value 15");
bracketOrder = 0;
bracketBase(3, bracketObj15)[bracketKey(4, "k1")] = bracketValue(5, 65);
bracketCheck(bracketOrder === 345, "bracket write order 15");
bracketCheck(bracketObj15.k1 === 65, "bracket write value 15");
bracketOrder = 0;
var bracketNested15 = bracketBase(6, bracketObj15)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 15");
bracketCheck(bracketNested15 === 26, "bracket nested value 15");
bracketTotal = bracketTotal + bracketRead15 + bracketObj15.k1 + bracketNested15;
var bracketObj16 = { k0: 19, k1: 23, nested: { hit: 27 } };
bracketOrder = 0;
var bracketRead16 = bracketBase(1, bracketObj16)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 16");
bracketCheck(bracketRead16 === 19, "bracket read value 16");
bracketOrder = 0;
bracketBase(3, bracketObj16)[bracketKey(4, "k1")] = bracketValue(5, 66);
bracketCheck(bracketOrder === 345, "bracket write order 16");
bracketCheck(bracketObj16.k1 === 66, "bracket write value 16");
bracketOrder = 0;
var bracketNested16 = bracketBase(6, bracketObj16)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 16");
bracketCheck(bracketNested16 === 27, "bracket nested value 16");
bracketTotal = bracketTotal + bracketRead16 + bracketObj16.k1 + bracketNested16;
var bracketObj17 = { k0: 20, k1: 24, nested: { hit: 28 } };
bracketOrder = 0;
var bracketRead17 = bracketBase(1, bracketObj17)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 17");
bracketCheck(bracketRead17 === 20, "bracket read value 17");
bracketOrder = 0;
bracketBase(3, bracketObj17)[bracketKey(4, "k1")] = bracketValue(5, 67);
bracketCheck(bracketOrder === 345, "bracket write order 17");
bracketCheck(bracketObj17.k1 === 67, "bracket write value 17");
bracketOrder = 0;
var bracketNested17 = bracketBase(6, bracketObj17)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 17");
bracketCheck(bracketNested17 === 28, "bracket nested value 17");
bracketTotal = bracketTotal + bracketRead17 + bracketObj17.k1 + bracketNested17;
var bracketObj18 = { k0: 21, k1: 25, nested: { hit: 29 } };
bracketOrder = 0;
var bracketRead18 = bracketBase(1, bracketObj18)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 18");
bracketCheck(bracketRead18 === 21, "bracket read value 18");
bracketOrder = 0;
bracketBase(3, bracketObj18)[bracketKey(4, "k1")] = bracketValue(5, 68);
bracketCheck(bracketOrder === 345, "bracket write order 18");
bracketCheck(bracketObj18.k1 === 68, "bracket write value 18");
bracketOrder = 0;
var bracketNested18 = bracketBase(6, bracketObj18)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 18");
bracketCheck(bracketNested18 === 29, "bracket nested value 18");
bracketTotal = bracketTotal + bracketRead18 + bracketObj18.k1 + bracketNested18;
var bracketObj19 = { k0: 22, k1: 26, nested: { hit: 30 } };
bracketOrder = 0;
var bracketRead19 = bracketBase(1, bracketObj19)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 19");
bracketCheck(bracketRead19 === 22, "bracket read value 19");
bracketOrder = 0;
bracketBase(3, bracketObj19)[bracketKey(4, "k1")] = bracketValue(5, 69);
bracketCheck(bracketOrder === 345, "bracket write order 19");
bracketCheck(bracketObj19.k1 === 69, "bracket write value 19");
bracketOrder = 0;
var bracketNested19 = bracketBase(6, bracketObj19)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 19");
bracketCheck(bracketNested19 === 30, "bracket nested value 19");
bracketTotal = bracketTotal + bracketRead19 + bracketObj19.k1 + bracketNested19;
var bracketObj20 = { k0: 23, k1: 27, nested: { hit: 31 } };
bracketOrder = 0;
var bracketRead20 = bracketBase(1, bracketObj20)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 20");
bracketCheck(bracketRead20 === 23, "bracket read value 20");
bracketOrder = 0;
bracketBase(3, bracketObj20)[bracketKey(4, "k1")] = bracketValue(5, 70);
bracketCheck(bracketOrder === 345, "bracket write order 20");
bracketCheck(bracketObj20.k1 === 70, "bracket write value 20");
bracketOrder = 0;
var bracketNested20 = bracketBase(6, bracketObj20)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 20");
bracketCheck(bracketNested20 === 31, "bracket nested value 20");
bracketTotal = bracketTotal + bracketRead20 + bracketObj20.k1 + bracketNested20;
var bracketObj21 = { k0: 24, k1: 28, nested: { hit: 32 } };
bracketOrder = 0;
var bracketRead21 = bracketBase(1, bracketObj21)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 21");
bracketCheck(bracketRead21 === 24, "bracket read value 21");
bracketOrder = 0;
bracketBase(3, bracketObj21)[bracketKey(4, "k1")] = bracketValue(5, 71);
bracketCheck(bracketOrder === 345, "bracket write order 21");
bracketCheck(bracketObj21.k1 === 71, "bracket write value 21");
bracketOrder = 0;
var bracketNested21 = bracketBase(6, bracketObj21)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 21");
bracketCheck(bracketNested21 === 32, "bracket nested value 21");
bracketTotal = bracketTotal + bracketRead21 + bracketObj21.k1 + bracketNested21;
var bracketObj22 = { k0: 25, k1: 29, nested: { hit: 33 } };
bracketOrder = 0;
var bracketRead22 = bracketBase(1, bracketObj22)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 22");
bracketCheck(bracketRead22 === 25, "bracket read value 22");
bracketOrder = 0;
bracketBase(3, bracketObj22)[bracketKey(4, "k1")] = bracketValue(5, 72);
bracketCheck(bracketOrder === 345, "bracket write order 22");
bracketCheck(bracketObj22.k1 === 72, "bracket write value 22");
bracketOrder = 0;
var bracketNested22 = bracketBase(6, bracketObj22)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 22");
bracketCheck(bracketNested22 === 33, "bracket nested value 22");
bracketTotal = bracketTotal + bracketRead22 + bracketObj22.k1 + bracketNested22;
var bracketObj23 = { k0: 26, k1: 30, nested: { hit: 34 } };
bracketOrder = 0;
var bracketRead23 = bracketBase(1, bracketObj23)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 23");
bracketCheck(bracketRead23 === 26, "bracket read value 23");
bracketOrder = 0;
bracketBase(3, bracketObj23)[bracketKey(4, "k1")] = bracketValue(5, 73);
bracketCheck(bracketOrder === 345, "bracket write order 23");
bracketCheck(bracketObj23.k1 === 73, "bracket write value 23");
bracketOrder = 0;
var bracketNested23 = bracketBase(6, bracketObj23)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 23");
bracketCheck(bracketNested23 === 34, "bracket nested value 23");
bracketTotal = bracketTotal + bracketRead23 + bracketObj23.k1 + bracketNested23;
var bracketObj24 = { k0: 27, k1: 31, nested: { hit: 35 } };
bracketOrder = 0;
var bracketRead24 = bracketBase(1, bracketObj24)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 24");
bracketCheck(bracketRead24 === 27, "bracket read value 24");
bracketOrder = 0;
bracketBase(3, bracketObj24)[bracketKey(4, "k1")] = bracketValue(5, 74);
bracketCheck(bracketOrder === 345, "bracket write order 24");
bracketCheck(bracketObj24.k1 === 74, "bracket write value 24");
bracketOrder = 0;
var bracketNested24 = bracketBase(6, bracketObj24)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 24");
bracketCheck(bracketNested24 === 35, "bracket nested value 24");
bracketTotal = bracketTotal + bracketRead24 + bracketObj24.k1 + bracketNested24;
var bracketObj25 = { k0: 28, k1: 32, nested: { hit: 36 } };
bracketOrder = 0;
var bracketRead25 = bracketBase(1, bracketObj25)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 25");
bracketCheck(bracketRead25 === 28, "bracket read value 25");
bracketOrder = 0;
bracketBase(3, bracketObj25)[bracketKey(4, "k1")] = bracketValue(5, 75);
bracketCheck(bracketOrder === 345, "bracket write order 25");
bracketCheck(bracketObj25.k1 === 75, "bracket write value 25");
bracketOrder = 0;
var bracketNested25 = bracketBase(6, bracketObj25)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 25");
bracketCheck(bracketNested25 === 36, "bracket nested value 25");
bracketTotal = bracketTotal + bracketRead25 + bracketObj25.k1 + bracketNested25;
var bracketObj26 = { k0: 29, k1: 33, nested: { hit: 37 } };
bracketOrder = 0;
var bracketRead26 = bracketBase(1, bracketObj26)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 26");
bracketCheck(bracketRead26 === 29, "bracket read value 26");
bracketOrder = 0;
bracketBase(3, bracketObj26)[bracketKey(4, "k1")] = bracketValue(5, 76);
bracketCheck(bracketOrder === 345, "bracket write order 26");
bracketCheck(bracketObj26.k1 === 76, "bracket write value 26");
bracketOrder = 0;
var bracketNested26 = bracketBase(6, bracketObj26)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 26");
bracketCheck(bracketNested26 === 37, "bracket nested value 26");
bracketTotal = bracketTotal + bracketRead26 + bracketObj26.k1 + bracketNested26;
var bracketObj27 = { k0: 30, k1: 34, nested: { hit: 38 } };
bracketOrder = 0;
var bracketRead27 = bracketBase(1, bracketObj27)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 27");
bracketCheck(bracketRead27 === 30, "bracket read value 27");
bracketOrder = 0;
bracketBase(3, bracketObj27)[bracketKey(4, "k1")] = bracketValue(5, 77);
bracketCheck(bracketOrder === 345, "bracket write order 27");
bracketCheck(bracketObj27.k1 === 77, "bracket write value 27");
bracketOrder = 0;
var bracketNested27 = bracketBase(6, bracketObj27)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 27");
bracketCheck(bracketNested27 === 38, "bracket nested value 27");
bracketTotal = bracketTotal + bracketRead27 + bracketObj27.k1 + bracketNested27;
var bracketObj28 = { k0: 31, k1: 35, nested: { hit: 39 } };
bracketOrder = 0;
var bracketRead28 = bracketBase(1, bracketObj28)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 28");
bracketCheck(bracketRead28 === 31, "bracket read value 28");
bracketOrder = 0;
bracketBase(3, bracketObj28)[bracketKey(4, "k1")] = bracketValue(5, 78);
bracketCheck(bracketOrder === 345, "bracket write order 28");
bracketCheck(bracketObj28.k1 === 78, "bracket write value 28");
bracketOrder = 0;
var bracketNested28 = bracketBase(6, bracketObj28)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 28");
bracketCheck(bracketNested28 === 39, "bracket nested value 28");
bracketTotal = bracketTotal + bracketRead28 + bracketObj28.k1 + bracketNested28;
var bracketObj29 = { k0: 32, k1: 36, nested: { hit: 40 } };
bracketOrder = 0;
var bracketRead29 = bracketBase(1, bracketObj29)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 29");
bracketCheck(bracketRead29 === 32, "bracket read value 29");
bracketOrder = 0;
bracketBase(3, bracketObj29)[bracketKey(4, "k1")] = bracketValue(5, 79);
bracketCheck(bracketOrder === 345, "bracket write order 29");
bracketCheck(bracketObj29.k1 === 79, "bracket write value 29");
bracketOrder = 0;
var bracketNested29 = bracketBase(6, bracketObj29)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 29");
bracketCheck(bracketNested29 === 40, "bracket nested value 29");
bracketTotal = bracketTotal + bracketRead29 + bracketObj29.k1 + bracketNested29;
var bracketObj30 = { k0: 33, k1: 37, nested: { hit: 41 } };
bracketOrder = 0;
var bracketRead30 = bracketBase(1, bracketObj30)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 30");
bracketCheck(bracketRead30 === 33, "bracket read value 30");
bracketOrder = 0;
bracketBase(3, bracketObj30)[bracketKey(4, "k1")] = bracketValue(5, 80);
bracketCheck(bracketOrder === 345, "bracket write order 30");
bracketCheck(bracketObj30.k1 === 80, "bracket write value 30");
bracketOrder = 0;
var bracketNested30 = bracketBase(6, bracketObj30)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 30");
bracketCheck(bracketNested30 === 41, "bracket nested value 30");
bracketTotal = bracketTotal + bracketRead30 + bracketObj30.k1 + bracketNested30;
var bracketObj31 = { k0: 34, k1: 38, nested: { hit: 42 } };
bracketOrder = 0;
var bracketRead31 = bracketBase(1, bracketObj31)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 31");
bracketCheck(bracketRead31 === 34, "bracket read value 31");
bracketOrder = 0;
bracketBase(3, bracketObj31)[bracketKey(4, "k1")] = bracketValue(5, 81);
bracketCheck(bracketOrder === 345, "bracket write order 31");
bracketCheck(bracketObj31.k1 === 81, "bracket write value 31");
bracketOrder = 0;
var bracketNested31 = bracketBase(6, bracketObj31)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 31");
bracketCheck(bracketNested31 === 42, "bracket nested value 31");
bracketTotal = bracketTotal + bracketRead31 + bracketObj31.k1 + bracketNested31;
var bracketObj32 = { k0: 35, k1: 39, nested: { hit: 43 } };
bracketOrder = 0;
var bracketRead32 = bracketBase(1, bracketObj32)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 32");
bracketCheck(bracketRead32 === 35, "bracket read value 32");
bracketOrder = 0;
bracketBase(3, bracketObj32)[bracketKey(4, "k1")] = bracketValue(5, 82);
bracketCheck(bracketOrder === 345, "bracket write order 32");
bracketCheck(bracketObj32.k1 === 82, "bracket write value 32");
bracketOrder = 0;
var bracketNested32 = bracketBase(6, bracketObj32)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 32");
bracketCheck(bracketNested32 === 43, "bracket nested value 32");
bracketTotal = bracketTotal + bracketRead32 + bracketObj32.k1 + bracketNested32;
var bracketObj33 = { k0: 36, k1: 40, nested: { hit: 44 } };
bracketOrder = 0;
var bracketRead33 = bracketBase(1, bracketObj33)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 33");
bracketCheck(bracketRead33 === 36, "bracket read value 33");
bracketOrder = 0;
bracketBase(3, bracketObj33)[bracketKey(4, "k1")] = bracketValue(5, 83);
bracketCheck(bracketOrder === 345, "bracket write order 33");
bracketCheck(bracketObj33.k1 === 83, "bracket write value 33");
bracketOrder = 0;
var bracketNested33 = bracketBase(6, bracketObj33)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 33");
bracketCheck(bracketNested33 === 44, "bracket nested value 33");
bracketTotal = bracketTotal + bracketRead33 + bracketObj33.k1 + bracketNested33;
var bracketObj34 = { k0: 37, k1: 41, nested: { hit: 45 } };
bracketOrder = 0;
var bracketRead34 = bracketBase(1, bracketObj34)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 34");
bracketCheck(bracketRead34 === 37, "bracket read value 34");
bracketOrder = 0;
bracketBase(3, bracketObj34)[bracketKey(4, "k1")] = bracketValue(5, 84);
bracketCheck(bracketOrder === 345, "bracket write order 34");
bracketCheck(bracketObj34.k1 === 84, "bracket write value 34");
bracketOrder = 0;
var bracketNested34 = bracketBase(6, bracketObj34)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 34");
bracketCheck(bracketNested34 === 45, "bracket nested value 34");
bracketTotal = bracketTotal + bracketRead34 + bracketObj34.k1 + bracketNested34;
var bracketObj35 = { k0: 38, k1: 42, nested: { hit: 46 } };
bracketOrder = 0;
var bracketRead35 = bracketBase(1, bracketObj35)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 35");
bracketCheck(bracketRead35 === 38, "bracket read value 35");
bracketOrder = 0;
bracketBase(3, bracketObj35)[bracketKey(4, "k1")] = bracketValue(5, 85);
bracketCheck(bracketOrder === 345, "bracket write order 35");
bracketCheck(bracketObj35.k1 === 85, "bracket write value 35");
bracketOrder = 0;
var bracketNested35 = bracketBase(6, bracketObj35)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 35");
bracketCheck(bracketNested35 === 46, "bracket nested value 35");
bracketTotal = bracketTotal + bracketRead35 + bracketObj35.k1 + bracketNested35;
var bracketObj36 = { k0: 39, k1: 43, nested: { hit: 47 } };
bracketOrder = 0;
var bracketRead36 = bracketBase(1, bracketObj36)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 36");
bracketCheck(bracketRead36 === 39, "bracket read value 36");
bracketOrder = 0;
bracketBase(3, bracketObj36)[bracketKey(4, "k1")] = bracketValue(5, 86);
bracketCheck(bracketOrder === 345, "bracket write order 36");
bracketCheck(bracketObj36.k1 === 86, "bracket write value 36");
bracketOrder = 0;
var bracketNested36 = bracketBase(6, bracketObj36)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 36");
bracketCheck(bracketNested36 === 47, "bracket nested value 36");
bracketTotal = bracketTotal + bracketRead36 + bracketObj36.k1 + bracketNested36;
var bracketObj37 = { k0: 40, k1: 44, nested: { hit: 48 } };
bracketOrder = 0;
var bracketRead37 = bracketBase(1, bracketObj37)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 37");
bracketCheck(bracketRead37 === 40, "bracket read value 37");
bracketOrder = 0;
bracketBase(3, bracketObj37)[bracketKey(4, "k1")] = bracketValue(5, 87);
bracketCheck(bracketOrder === 345, "bracket write order 37");
bracketCheck(bracketObj37.k1 === 87, "bracket write value 37");
bracketOrder = 0;
var bracketNested37 = bracketBase(6, bracketObj37)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 37");
bracketCheck(bracketNested37 === 48, "bracket nested value 37");
bracketTotal = bracketTotal + bracketRead37 + bracketObj37.k1 + bracketNested37;
var bracketObj38 = { k0: 41, k1: 45, nested: { hit: 49 } };
bracketOrder = 0;
var bracketRead38 = bracketBase(1, bracketObj38)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 38");
bracketCheck(bracketRead38 === 41, "bracket read value 38");
bracketOrder = 0;
bracketBase(3, bracketObj38)[bracketKey(4, "k1")] = bracketValue(5, 88);
bracketCheck(bracketOrder === 345, "bracket write order 38");
bracketCheck(bracketObj38.k1 === 88, "bracket write value 38");
bracketOrder = 0;
var bracketNested38 = bracketBase(6, bracketObj38)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 38");
bracketCheck(bracketNested38 === 49, "bracket nested value 38");
bracketTotal = bracketTotal + bracketRead38 + bracketObj38.k1 + bracketNested38;
var bracketObj39 = { k0: 42, k1: 46, nested: { hit: 50 } };
bracketOrder = 0;
var bracketRead39 = bracketBase(1, bracketObj39)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 39");
bracketCheck(bracketRead39 === 42, "bracket read value 39");
bracketOrder = 0;
bracketBase(3, bracketObj39)[bracketKey(4, "k1")] = bracketValue(5, 89);
bracketCheck(bracketOrder === 345, "bracket write order 39");
bracketCheck(bracketObj39.k1 === 89, "bracket write value 39");
bracketOrder = 0;
var bracketNested39 = bracketBase(6, bracketObj39)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 39");
bracketCheck(bracketNested39 === 50, "bracket nested value 39");
bracketTotal = bracketTotal + bracketRead39 + bracketObj39.k1 + bracketNested39;
var bracketObj40 = { k0: 43, k1: 47, nested: { hit: 51 } };
bracketOrder = 0;
var bracketRead40 = bracketBase(1, bracketObj40)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 40");
bracketCheck(bracketRead40 === 43, "bracket read value 40");
bracketOrder = 0;
bracketBase(3, bracketObj40)[bracketKey(4, "k1")] = bracketValue(5, 90);
bracketCheck(bracketOrder === 345, "bracket write order 40");
bracketCheck(bracketObj40.k1 === 90, "bracket write value 40");
bracketOrder = 0;
var bracketNested40 = bracketBase(6, bracketObj40)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 40");
bracketCheck(bracketNested40 === 51, "bracket nested value 40");
bracketTotal = bracketTotal + bracketRead40 + bracketObj40.k1 + bracketNested40;
var bracketObj41 = { k0: 44, k1: 48, nested: { hit: 52 } };
bracketOrder = 0;
var bracketRead41 = bracketBase(1, bracketObj41)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 41");
bracketCheck(bracketRead41 === 44, "bracket read value 41");
bracketOrder = 0;
bracketBase(3, bracketObj41)[bracketKey(4, "k1")] = bracketValue(5, 91);
bracketCheck(bracketOrder === 345, "bracket write order 41");
bracketCheck(bracketObj41.k1 === 91, "bracket write value 41");
bracketOrder = 0;
var bracketNested41 = bracketBase(6, bracketObj41)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 41");
bracketCheck(bracketNested41 === 52, "bracket nested value 41");
bracketTotal = bracketTotal + bracketRead41 + bracketObj41.k1 + bracketNested41;
var bracketObj42 = { k0: 45, k1: 49, nested: { hit: 53 } };
bracketOrder = 0;
var bracketRead42 = bracketBase(1, bracketObj42)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 42");
bracketCheck(bracketRead42 === 45, "bracket read value 42");
bracketOrder = 0;
bracketBase(3, bracketObj42)[bracketKey(4, "k1")] = bracketValue(5, 92);
bracketCheck(bracketOrder === 345, "bracket write order 42");
bracketCheck(bracketObj42.k1 === 92, "bracket write value 42");
bracketOrder = 0;
var bracketNested42 = bracketBase(6, bracketObj42)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 42");
bracketCheck(bracketNested42 === 53, "bracket nested value 42");
bracketTotal = bracketTotal + bracketRead42 + bracketObj42.k1 + bracketNested42;
var bracketObj43 = { k0: 46, k1: 50, nested: { hit: 54 } };
bracketOrder = 0;
var bracketRead43 = bracketBase(1, bracketObj43)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 43");
bracketCheck(bracketRead43 === 46, "bracket read value 43");
bracketOrder = 0;
bracketBase(3, bracketObj43)[bracketKey(4, "k1")] = bracketValue(5, 93);
bracketCheck(bracketOrder === 345, "bracket write order 43");
bracketCheck(bracketObj43.k1 === 93, "bracket write value 43");
bracketOrder = 0;
var bracketNested43 = bracketBase(6, bracketObj43)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 43");
bracketCheck(bracketNested43 === 54, "bracket nested value 43");
bracketTotal = bracketTotal + bracketRead43 + bracketObj43.k1 + bracketNested43;
var bracketObj44 = { k0: 47, k1: 51, nested: { hit: 55 } };
bracketOrder = 0;
var bracketRead44 = bracketBase(1, bracketObj44)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 44");
bracketCheck(bracketRead44 === 47, "bracket read value 44");
bracketOrder = 0;
bracketBase(3, bracketObj44)[bracketKey(4, "k1")] = bracketValue(5, 94);
bracketCheck(bracketOrder === 345, "bracket write order 44");
bracketCheck(bracketObj44.k1 === 94, "bracket write value 44");
bracketOrder = 0;
var bracketNested44 = bracketBase(6, bracketObj44)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 44");
bracketCheck(bracketNested44 === 55, "bracket nested value 44");
bracketTotal = bracketTotal + bracketRead44 + bracketObj44.k1 + bracketNested44;
var bracketObj45 = { k0: 48, k1: 52, nested: { hit: 56 } };
bracketOrder = 0;
var bracketRead45 = bracketBase(1, bracketObj45)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 45");
bracketCheck(bracketRead45 === 48, "bracket read value 45");
bracketOrder = 0;
bracketBase(3, bracketObj45)[bracketKey(4, "k1")] = bracketValue(5, 95);
bracketCheck(bracketOrder === 345, "bracket write order 45");
bracketCheck(bracketObj45.k1 === 95, "bracket write value 45");
bracketOrder = 0;
var bracketNested45 = bracketBase(6, bracketObj45)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 45");
bracketCheck(bracketNested45 === 56, "bracket nested value 45");
bracketTotal = bracketTotal + bracketRead45 + bracketObj45.k1 + bracketNested45;
var bracketObj46 = { k0: 49, k1: 53, nested: { hit: 57 } };
bracketOrder = 0;
var bracketRead46 = bracketBase(1, bracketObj46)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 46");
bracketCheck(bracketRead46 === 49, "bracket read value 46");
bracketOrder = 0;
bracketBase(3, bracketObj46)[bracketKey(4, "k1")] = bracketValue(5, 96);
bracketCheck(bracketOrder === 345, "bracket write order 46");
bracketCheck(bracketObj46.k1 === 96, "bracket write value 46");
bracketOrder = 0;
var bracketNested46 = bracketBase(6, bracketObj46)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 46");
bracketCheck(bracketNested46 === 57, "bracket nested value 46");
bracketTotal = bracketTotal + bracketRead46 + bracketObj46.k1 + bracketNested46;
var bracketObj47 = { k0: 50, k1: 54, nested: { hit: 58 } };
bracketOrder = 0;
var bracketRead47 = bracketBase(1, bracketObj47)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 47");
bracketCheck(bracketRead47 === 50, "bracket read value 47");
bracketOrder = 0;
bracketBase(3, bracketObj47)[bracketKey(4, "k1")] = bracketValue(5, 97);
bracketCheck(bracketOrder === 345, "bracket write order 47");
bracketCheck(bracketObj47.k1 === 97, "bracket write value 47");
bracketOrder = 0;
var bracketNested47 = bracketBase(6, bracketObj47)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 47");
bracketCheck(bracketNested47 === 58, "bracket nested value 47");
bracketTotal = bracketTotal + bracketRead47 + bracketObj47.k1 + bracketNested47;
var bracketObj48 = { k0: 51, k1: 55, nested: { hit: 59 } };
bracketOrder = 0;
var bracketRead48 = bracketBase(1, bracketObj48)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 48");
bracketCheck(bracketRead48 === 51, "bracket read value 48");
bracketOrder = 0;
bracketBase(3, bracketObj48)[bracketKey(4, "k1")] = bracketValue(5, 98);
bracketCheck(bracketOrder === 345, "bracket write order 48");
bracketCheck(bracketObj48.k1 === 98, "bracket write value 48");
bracketOrder = 0;
var bracketNested48 = bracketBase(6, bracketObj48)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 48");
bracketCheck(bracketNested48 === 59, "bracket nested value 48");
bracketTotal = bracketTotal + bracketRead48 + bracketObj48.k1 + bracketNested48;
var bracketObj49 = { k0: 52, k1: 56, nested: { hit: 60 } };
bracketOrder = 0;
var bracketRead49 = bracketBase(1, bracketObj49)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 49");
bracketCheck(bracketRead49 === 52, "bracket read value 49");
bracketOrder = 0;
bracketBase(3, bracketObj49)[bracketKey(4, "k1")] = bracketValue(5, 99);
bracketCheck(bracketOrder === 345, "bracket write order 49");
bracketCheck(bracketObj49.k1 === 99, "bracket write value 49");
bracketOrder = 0;
var bracketNested49 = bracketBase(6, bracketObj49)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 49");
bracketCheck(bracketNested49 === 60, "bracket nested value 49");
bracketTotal = bracketTotal + bracketRead49 + bracketObj49.k1 + bracketNested49;
var bracketObj50 = { k0: 53, k1: 57, nested: { hit: 61 } };
bracketOrder = 0;
var bracketRead50 = bracketBase(1, bracketObj50)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 50");
bracketCheck(bracketRead50 === 53, "bracket read value 50");
bracketOrder = 0;
bracketBase(3, bracketObj50)[bracketKey(4, "k1")] = bracketValue(5, 100);
bracketCheck(bracketOrder === 345, "bracket write order 50");
bracketCheck(bracketObj50.k1 === 100, "bracket write value 50");
bracketOrder = 0;
var bracketNested50 = bracketBase(6, bracketObj50)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 50");
bracketCheck(bracketNested50 === 61, "bracket nested value 50");
bracketTotal = bracketTotal + bracketRead50 + bracketObj50.k1 + bracketNested50;
var bracketObj51 = { k0: 54, k1: 58, nested: { hit: 62 } };
bracketOrder = 0;
var bracketRead51 = bracketBase(1, bracketObj51)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 51");
bracketCheck(bracketRead51 === 54, "bracket read value 51");
bracketOrder = 0;
bracketBase(3, bracketObj51)[bracketKey(4, "k1")] = bracketValue(5, 101);
bracketCheck(bracketOrder === 345, "bracket write order 51");
bracketCheck(bracketObj51.k1 === 101, "bracket write value 51");
bracketOrder = 0;
var bracketNested51 = bracketBase(6, bracketObj51)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 51");
bracketCheck(bracketNested51 === 62, "bracket nested value 51");
bracketTotal = bracketTotal + bracketRead51 + bracketObj51.k1 + bracketNested51;
bracketCheck(bracketScore === 312, "bracket score");
bracketCheck(bracketTotal > 0, "bracket accumulated result");
