// behavior: bracket-access-evaluates-base-then-expression-key
// expected: pass
// goal: script
// size: standard
// variant: script.sloppy

var bracketScore = 0;
function bracketCheck(condition, label) {
if (!condition) {
throw label;
}
bracketScore = bracketScore + 1;
return true;
}
var bracketOrder = 0;
function bracketBase(tag, object) { bracketOrder = bracketOrder * 10 + tag; return object; }
function bracketKey(tag, key) { bracketOrder = bracketOrder * 10 + tag; return key; }
function bracketValue(tag, value) { bracketOrder = bracketOrder * 10 + tag; return value; }
var bracketTotal = 0;
var bracketObj0 = { k0: 3, k1: 7, nested: { hit: 11 } };
bracketOrder = 0;
var bracketRead0 = bracketBase(1, bracketObj0)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 0");
bracketCheck(bracketRead0 === 3, "bracket read value 0");
bracketOrder = 0;
bracketBase(3, bracketObj0)[bracketKey(4, "k1")] = bracketValue(5, 50);
bracketCheck(bracketOrder === 345, "bracket write order 0");
bracketCheck(bracketObj0.k1 === 50, "bracket write value 0");
bracketOrder = 0;
var bracketNested0 = bracketBase(6, bracketObj0)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 0");
bracketCheck(bracketNested0 === 11, "bracket nested value 0");
bracketTotal = bracketTotal + bracketRead0 + bracketObj0.k1 + bracketNested0;
var bracketObj1 = { k0: 4, k1: 8, nested: { hit: 12 } };
bracketOrder = 0;
var bracketRead1 = bracketBase(1, bracketObj1)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 1");
bracketCheck(bracketRead1 === 4, "bracket read value 1");
bracketOrder = 0;
bracketBase(3, bracketObj1)[bracketKey(4, "k1")] = bracketValue(5, 51);
bracketCheck(bracketOrder === 345, "bracket write order 1");
bracketCheck(bracketObj1.k1 === 51, "bracket write value 1");
bracketOrder = 0;
var bracketNested1 = bracketBase(6, bracketObj1)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 1");
bracketCheck(bracketNested1 === 12, "bracket nested value 1");
bracketTotal = bracketTotal + bracketRead1 + bracketObj1.k1 + bracketNested1;
var bracketObj2 = { k0: 5, k1: 9, nested: { hit: 13 } };
bracketOrder = 0;
var bracketRead2 = bracketBase(1, bracketObj2)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 2");
bracketCheck(bracketRead2 === 5, "bracket read value 2");
bracketOrder = 0;
bracketBase(3, bracketObj2)[bracketKey(4, "k1")] = bracketValue(5, 52);
bracketCheck(bracketOrder === 345, "bracket write order 2");
bracketCheck(bracketObj2.k1 === 52, "bracket write value 2");
bracketOrder = 0;
var bracketNested2 = bracketBase(6, bracketObj2)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 2");
bracketCheck(bracketNested2 === 13, "bracket nested value 2");
bracketTotal = bracketTotal + bracketRead2 + bracketObj2.k1 + bracketNested2;
var bracketObj3 = { k0: 6, k1: 10, nested: { hit: 14 } };
bracketOrder = 0;
var bracketRead3 = bracketBase(1, bracketObj3)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 3");
bracketCheck(bracketRead3 === 6, "bracket read value 3");
bracketOrder = 0;
bracketBase(3, bracketObj3)[bracketKey(4, "k1")] = bracketValue(5, 53);
bracketCheck(bracketOrder === 345, "bracket write order 3");
bracketCheck(bracketObj3.k1 === 53, "bracket write value 3");
bracketOrder = 0;
var bracketNested3 = bracketBase(6, bracketObj3)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 3");
bracketCheck(bracketNested3 === 14, "bracket nested value 3");
bracketTotal = bracketTotal + bracketRead3 + bracketObj3.k1 + bracketNested3;
var bracketObj4 = { k0: 7, k1: 11, nested: { hit: 15 } };
bracketOrder = 0;
var bracketRead4 = bracketBase(1, bracketObj4)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 4");
bracketCheck(bracketRead4 === 7, "bracket read value 4");
bracketOrder = 0;
bracketBase(3, bracketObj4)[bracketKey(4, "k1")] = bracketValue(5, 54);
bracketCheck(bracketOrder === 345, "bracket write order 4");
bracketCheck(bracketObj4.k1 === 54, "bracket write value 4");
bracketOrder = 0;
var bracketNested4 = bracketBase(6, bracketObj4)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 4");
bracketCheck(bracketNested4 === 15, "bracket nested value 4");
bracketTotal = bracketTotal + bracketRead4 + bracketObj4.k1 + bracketNested4;
var bracketObj5 = { k0: 8, k1: 12, nested: { hit: 16 } };
bracketOrder = 0;
var bracketRead5 = bracketBase(1, bracketObj5)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 5");
bracketCheck(bracketRead5 === 8, "bracket read value 5");
bracketOrder = 0;
bracketBase(3, bracketObj5)[bracketKey(4, "k1")] = bracketValue(5, 55);
bracketCheck(bracketOrder === 345, "bracket write order 5");
bracketCheck(bracketObj5.k1 === 55, "bracket write value 5");
bracketOrder = 0;
var bracketNested5 = bracketBase(6, bracketObj5)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 5");
bracketCheck(bracketNested5 === 16, "bracket nested value 5");
bracketTotal = bracketTotal + bracketRead5 + bracketObj5.k1 + bracketNested5;
var bracketObj6 = { k0: 9, k1: 13, nested: { hit: 17 } };
bracketOrder = 0;
var bracketRead6 = bracketBase(1, bracketObj6)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 6");
bracketCheck(bracketRead6 === 9, "bracket read value 6");
bracketOrder = 0;
bracketBase(3, bracketObj6)[bracketKey(4, "k1")] = bracketValue(5, 56);
bracketCheck(bracketOrder === 345, "bracket write order 6");
bracketCheck(bracketObj6.k1 === 56, "bracket write value 6");
bracketOrder = 0;
var bracketNested6 = bracketBase(6, bracketObj6)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 6");
bracketCheck(bracketNested6 === 17, "bracket nested value 6");
bracketTotal = bracketTotal + bracketRead6 + bracketObj6.k1 + bracketNested6;
var bracketObj7 = { k0: 10, k1: 14, nested: { hit: 18 } };
bracketOrder = 0;
var bracketRead7 = bracketBase(1, bracketObj7)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 7");
bracketCheck(bracketRead7 === 10, "bracket read value 7");
bracketOrder = 0;
bracketBase(3, bracketObj7)[bracketKey(4, "k1")] = bracketValue(5, 57);
bracketCheck(bracketOrder === 345, "bracket write order 7");
bracketCheck(bracketObj7.k1 === 57, "bracket write value 7");
bracketOrder = 0;
var bracketNested7 = bracketBase(6, bracketObj7)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 7");
bracketCheck(bracketNested7 === 18, "bracket nested value 7");
bracketTotal = bracketTotal + bracketRead7 + bracketObj7.k1 + bracketNested7;
var bracketObj8 = { k0: 11, k1: 15, nested: { hit: 19 } };
bracketOrder = 0;
var bracketRead8 = bracketBase(1, bracketObj8)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 8");
bracketCheck(bracketRead8 === 11, "bracket read value 8");
bracketOrder = 0;
bracketBase(3, bracketObj8)[bracketKey(4, "k1")] = bracketValue(5, 58);
bracketCheck(bracketOrder === 345, "bracket write order 8");
bracketCheck(bracketObj8.k1 === 58, "bracket write value 8");
bracketOrder = 0;
var bracketNested8 = bracketBase(6, bracketObj8)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 8");
bracketCheck(bracketNested8 === 19, "bracket nested value 8");
bracketTotal = bracketTotal + bracketRead8 + bracketObj8.k1 + bracketNested8;
var bracketObj9 = { k0: 12, k1: 16, nested: { hit: 20 } };
bracketOrder = 0;
var bracketRead9 = bracketBase(1, bracketObj9)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 9");
bracketCheck(bracketRead9 === 12, "bracket read value 9");
bracketOrder = 0;
bracketBase(3, bracketObj9)[bracketKey(4, "k1")] = bracketValue(5, 59);
bracketCheck(bracketOrder === 345, "bracket write order 9");
bracketCheck(bracketObj9.k1 === 59, "bracket write value 9");
bracketOrder = 0;
var bracketNested9 = bracketBase(6, bracketObj9)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 9");
bracketCheck(bracketNested9 === 20, "bracket nested value 9");
bracketTotal = bracketTotal + bracketRead9 + bracketObj9.k1 + bracketNested9;
var bracketObj10 = { k0: 13, k1: 17, nested: { hit: 21 } };
bracketOrder = 0;
var bracketRead10 = bracketBase(1, bracketObj10)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 10");
bracketCheck(bracketRead10 === 13, "bracket read value 10");
bracketOrder = 0;
bracketBase(3, bracketObj10)[bracketKey(4, "k1")] = bracketValue(5, 60);
bracketCheck(bracketOrder === 345, "bracket write order 10");
bracketCheck(bracketObj10.k1 === 60, "bracket write value 10");
bracketOrder = 0;
var bracketNested10 = bracketBase(6, bracketObj10)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 10");
bracketCheck(bracketNested10 === 21, "bracket nested value 10");
bracketTotal = bracketTotal + bracketRead10 + bracketObj10.k1 + bracketNested10;
var bracketObj11 = { k0: 14, k1: 18, nested: { hit: 22 } };
bracketOrder = 0;
var bracketRead11 = bracketBase(1, bracketObj11)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 11");
bracketCheck(bracketRead11 === 14, "bracket read value 11");
bracketOrder = 0;
bracketBase(3, bracketObj11)[bracketKey(4, "k1")] = bracketValue(5, 61);
bracketCheck(bracketOrder === 345, "bracket write order 11");
bracketCheck(bracketObj11.k1 === 61, "bracket write value 11");
bracketOrder = 0;
var bracketNested11 = bracketBase(6, bracketObj11)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 11");
bracketCheck(bracketNested11 === 22, "bracket nested value 11");
bracketTotal = bracketTotal + bracketRead11 + bracketObj11.k1 + bracketNested11;
bracketCheck(bracketScore === 72, "bracket score");
bracketCheck(bracketTotal > 0, "bracket accumulated result");
