// behavior: bracket-access-evaluates-base-then-expression-key
// expected: pass
// goal: script
// size: stress
// variant: script.sloppy

var bracketScore = 0;
function bracketCheck(condition, label) {
if (!condition) {
throw label;
}
bracketScore = bracketScore + 1;
return true;
}
var bracketOrder = 0;
function bracketBase(tag, object) { bracketOrder = bracketOrder * 10 + tag; return object; }
function bracketKey(tag, key) { bracketOrder = bracketOrder * 10 + tag; return key; }
function bracketValue(tag, value) { bracketOrder = bracketOrder * 10 + tag; return value; }
var bracketTotal = 0;
var bracketObj0 = { k0: 3, k1: 7, nested: { hit: 11 } };
bracketOrder = 0;
var bracketRead0 = bracketBase(1, bracketObj0)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 0");
bracketCheck(bracketRead0 === 3, "bracket read value 0");
bracketOrder = 0;
bracketBase(3, bracketObj0)[bracketKey(4, "k1")] = bracketValue(5, 50);
bracketCheck(bracketOrder === 345, "bracket write order 0");
bracketCheck(bracketObj0.k1 === 50, "bracket write value 0");
bracketOrder = 0;
var bracketNested0 = bracketBase(6, bracketObj0)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 0");
bracketCheck(bracketNested0 === 11, "bracket nested value 0");
bracketTotal = bracketTotal + bracketRead0 + bracketObj0.k1 + bracketNested0;
var bracketObj1 = { k0: 4, k1: 8, nested: { hit: 12 } };
bracketOrder = 0;
var bracketRead1 = bracketBase(1, bracketObj1)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 1");
bracketCheck(bracketRead1 === 4, "bracket read value 1");
bracketOrder = 0;
bracketBase(3, bracketObj1)[bracketKey(4, "k1")] = bracketValue(5, 51);
bracketCheck(bracketOrder === 345, "bracket write order 1");
bracketCheck(bracketObj1.k1 === 51, "bracket write value 1");
bracketOrder = 0;
var bracketNested1 = bracketBase(6, bracketObj1)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 1");
bracketCheck(bracketNested1 === 12, "bracket nested value 1");
bracketTotal = bracketTotal + bracketRead1 + bracketObj1.k1 + bracketNested1;
var bracketObj2 = { k0: 5, k1: 9, nested: { hit: 13 } };
bracketOrder = 0;
var bracketRead2 = bracketBase(1, bracketObj2)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 2");
bracketCheck(bracketRead2 === 5, "bracket read value 2");
bracketOrder = 0;
bracketBase(3, bracketObj2)[bracketKey(4, "k1")] = bracketValue(5, 52);
bracketCheck(bracketOrder === 345, "bracket write order 2");
bracketCheck(bracketObj2.k1 === 52, "bracket write value 2");
bracketOrder = 0;
var bracketNested2 = bracketBase(6, bracketObj2)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 2");
bracketCheck(bracketNested2 === 13, "bracket nested value 2");
bracketTotal = bracketTotal + bracketRead2 + bracketObj2.k1 + bracketNested2;
var bracketObj3 = { k0: 6, k1: 10, nested: { hit: 14 } };
bracketOrder = 0;
var bracketRead3 = bracketBase(1, bracketObj3)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 3");
bracketCheck(bracketRead3 === 6, "bracket read value 3");
bracketOrder = 0;
bracketBase(3, bracketObj3)[bracketKey(4, "k1")] = bracketValue(5, 53);
bracketCheck(bracketOrder === 345, "bracket write order 3");
bracketCheck(bracketObj3.k1 === 53, "bracket write value 3");
bracketOrder = 0;
var bracketNested3 = bracketBase(6, bracketObj3)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 3");
bracketCheck(bracketNested3 === 14, "bracket nested value 3");
bracketTotal = bracketTotal + bracketRead3 + bracketObj3.k1 + bracketNested3;
var bracketObj4 = { k0: 7, k1: 11, nested: { hit: 15 } };
bracketOrder = 0;
var bracketRead4 = bracketBase(1, bracketObj4)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 4");
bracketCheck(bracketRead4 === 7, "bracket read value 4");
bracketOrder = 0;
bracketBase(3, bracketObj4)[bracketKey(4, "k1")] = bracketValue(5, 54);
bracketCheck(bracketOrder === 345, "bracket write order 4");
bracketCheck(bracketObj4.k1 === 54, "bracket write value 4");
bracketOrder = 0;
var bracketNested4 = bracketBase(6, bracketObj4)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 4");
bracketCheck(bracketNested4 === 15, "bracket nested value 4");
bracketTotal = bracketTotal + bracketRead4 + bracketObj4.k1 + bracketNested4;
var bracketObj5 = { k0: 8, k1: 12, nested: { hit: 16 } };
bracketOrder = 0;
var bracketRead5 = bracketBase(1, bracketObj5)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 5");
bracketCheck(bracketRead5 === 8, "bracket read value 5");
bracketOrder = 0;
bracketBase(3, bracketObj5)[bracketKey(4, "k1")] = bracketValue(5, 55);
bracketCheck(bracketOrder === 345, "bracket write order 5");
bracketCheck(bracketObj5.k1 === 55, "bracket write value 5");
bracketOrder = 0;
var bracketNested5 = bracketBase(6, bracketObj5)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 5");
bracketCheck(bracketNested5 === 16, "bracket nested value 5");
bracketTotal = bracketTotal + bracketRead5 + bracketObj5.k1 + bracketNested5;
var bracketObj6 = { k0: 9, k1: 13, nested: { hit: 17 } };
bracketOrder = 0;
var bracketRead6 = bracketBase(1, bracketObj6)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 6");
bracketCheck(bracketRead6 === 9, "bracket read value 6");
bracketOrder = 0;
bracketBase(3, bracketObj6)[bracketKey(4, "k1")] = bracketValue(5, 56);
bracketCheck(bracketOrder === 345, "bracket write order 6");
bracketCheck(bracketObj6.k1 === 56, "bracket write value 6");
bracketOrder = 0;
var bracketNested6 = bracketBase(6, bracketObj6)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 6");
bracketCheck(bracketNested6 === 17, "bracket nested value 6");
bracketTotal = bracketTotal + bracketRead6 + bracketObj6.k1 + bracketNested6;
var bracketObj7 = { k0: 10, k1: 14, nested: { hit: 18 } };
bracketOrder = 0;
var bracketRead7 = bracketBase(1, bracketObj7)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 7");
bracketCheck(bracketRead7 === 10, "bracket read value 7");
bracketOrder = 0;
bracketBase(3, bracketObj7)[bracketKey(4, "k1")] = bracketValue(5, 57);
bracketCheck(bracketOrder === 345, "bracket write order 7");
bracketCheck(bracketObj7.k1 === 57, "bracket write value 7");
bracketOrder = 0;
var bracketNested7 = bracketBase(6, bracketObj7)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 7");
bracketCheck(bracketNested7 === 18, "bracket nested value 7");
bracketTotal = bracketTotal + bracketRead7 + bracketObj7.k1 + bracketNested7;
var bracketObj8 = { k0: 11, k1: 15, nested: { hit: 19 } };
bracketOrder = 0;
var bracketRead8 = bracketBase(1, bracketObj8)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 8");
bracketCheck(bracketRead8 === 11, "bracket read value 8");
bracketOrder = 0;
bracketBase(3, bracketObj8)[bracketKey(4, "k1")] = bracketValue(5, 58);
bracketCheck(bracketOrder === 345, "bracket write order 8");
bracketCheck(bracketObj8.k1 === 58, "bracket write value 8");
bracketOrder = 0;
var bracketNested8 = bracketBase(6, bracketObj8)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 8");
bracketCheck(bracketNested8 === 19, "bracket nested value 8");
bracketTotal = bracketTotal + bracketRead8 + bracketObj8.k1 + bracketNested8;
var bracketObj9 = { k0: 12, k1: 16, nested: { hit: 20 } };
bracketOrder = 0;
var bracketRead9 = bracketBase(1, bracketObj9)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 9");
bracketCheck(bracketRead9 === 12, "bracket read value 9");
bracketOrder = 0;
bracketBase(3, bracketObj9)[bracketKey(4, "k1")] = bracketValue(5, 59);
bracketCheck(bracketOrder === 345, "bracket write order 9");
bracketCheck(bracketObj9.k1 === 59, "bracket write value 9");
bracketOrder = 0;
var bracketNested9 = bracketBase(6, bracketObj9)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 9");
bracketCheck(bracketNested9 === 20, "bracket nested value 9");
bracketTotal = bracketTotal + bracketRead9 + bracketObj9.k1 + bracketNested9;
var bracketObj10 = { k0: 13, k1: 17, nested: { hit: 21 } };
bracketOrder = 0;
var bracketRead10 = bracketBase(1, bracketObj10)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 10");
bracketCheck(bracketRead10 === 13, "bracket read value 10");
bracketOrder = 0;
bracketBase(3, bracketObj10)[bracketKey(4, "k1")] = bracketValue(5, 60);
bracketCheck(bracketOrder === 345, "bracket write order 10");
bracketCheck(bracketObj10.k1 === 60, "bracket write value 10");
bracketOrder = 0;
var bracketNested10 = bracketBase(6, bracketObj10)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 10");
bracketCheck(bracketNested10 === 21, "bracket nested value 10");
bracketTotal = bracketTotal + bracketRead10 + bracketObj10.k1 + bracketNested10;
var bracketObj11 = { k0: 14, k1: 18, nested: { hit: 22 } };
bracketOrder = 0;
var bracketRead11 = bracketBase(1, bracketObj11)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 11");
bracketCheck(bracketRead11 === 14, "bracket read value 11");
bracketOrder = 0;
bracketBase(3, bracketObj11)[bracketKey(4, "k1")] = bracketValue(5, 61);
bracketCheck(bracketOrder === 345, "bracket write order 11");
bracketCheck(bracketObj11.k1 === 61, "bracket write value 11");
bracketOrder = 0;
var bracketNested11 = bracketBase(6, bracketObj11)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 11");
bracketCheck(bracketNested11 === 22, "bracket nested value 11");
bracketTotal = bracketTotal + bracketRead11 + bracketObj11.k1 + bracketNested11;
var bracketObj12 = { k0: 15, k1: 19, nested: { hit: 23 } };
bracketOrder = 0;
var bracketRead12 = bracketBase(1, bracketObj12)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 12");
bracketCheck(bracketRead12 === 15, "bracket read value 12");
bracketOrder = 0;
bracketBase(3, bracketObj12)[bracketKey(4, "k1")] = bracketValue(5, 62);
bracketCheck(bracketOrder === 345, "bracket write order 12");
bracketCheck(bracketObj12.k1 === 62, "bracket write value 12");
bracketOrder = 0;
var bracketNested12 = bracketBase(6, bracketObj12)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 12");
bracketCheck(bracketNested12 === 23, "bracket nested value 12");
bracketTotal = bracketTotal + bracketRead12 + bracketObj12.k1 + bracketNested12;
var bracketObj13 = { k0: 16, k1: 20, nested: { hit: 24 } };
bracketOrder = 0;
var bracketRead13 = bracketBase(1, bracketObj13)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 13");
bracketCheck(bracketRead13 === 16, "bracket read value 13");
bracketOrder = 0;
bracketBase(3, bracketObj13)[bracketKey(4, "k1")] = bracketValue(5, 63);
bracketCheck(bracketOrder === 345, "bracket write order 13");
bracketCheck(bracketObj13.k1 === 63, "bracket write value 13");
bracketOrder = 0;
var bracketNested13 = bracketBase(6, bracketObj13)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 13");
bracketCheck(bracketNested13 === 24, "bracket nested value 13");
bracketTotal = bracketTotal + bracketRead13 + bracketObj13.k1 + bracketNested13;
var bracketObj14 = { k0: 17, k1: 21, nested: { hit: 25 } };
bracketOrder = 0;
var bracketRead14 = bracketBase(1, bracketObj14)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 14");
bracketCheck(bracketRead14 === 17, "bracket read value 14");
bracketOrder = 0;
bracketBase(3, bracketObj14)[bracketKey(4, "k1")] = bracketValue(5, 64);
bracketCheck(bracketOrder === 345, "bracket write order 14");
bracketCheck(bracketObj14.k1 === 64, "bracket write value 14");
bracketOrder = 0;
var bracketNested14 = bracketBase(6, bracketObj14)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 14");
bracketCheck(bracketNested14 === 25, "bracket nested value 14");
bracketTotal = bracketTotal + bracketRead14 + bracketObj14.k1 + bracketNested14;
var bracketObj15 = { k0: 18, k1: 22, nested: { hit: 26 } };
bracketOrder = 0;
var bracketRead15 = bracketBase(1, bracketObj15)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 15");
bracketCheck(bracketRead15 === 18, "bracket read value 15");
bracketOrder = 0;
bracketBase(3, bracketObj15)[bracketKey(4, "k1")] = bracketValue(5, 65);
bracketCheck(bracketOrder === 345, "bracket write order 15");
bracketCheck(bracketObj15.k1 === 65, "bracket write value 15");
bracketOrder = 0;
var bracketNested15 = bracketBase(6, bracketObj15)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 15");
bracketCheck(bracketNested15 === 26, "bracket nested value 15");
bracketTotal = bracketTotal + bracketRead15 + bracketObj15.k1 + bracketNested15;
var bracketObj16 = { k0: 19, k1: 23, nested: { hit: 27 } };
bracketOrder = 0;
var bracketRead16 = bracketBase(1, bracketObj16)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 16");
bracketCheck(bracketRead16 === 19, "bracket read value 16");
bracketOrder = 0;
bracketBase(3, bracketObj16)[bracketKey(4, "k1")] = bracketValue(5, 66);
bracketCheck(bracketOrder === 345, "bracket write order 16");
bracketCheck(bracketObj16.k1 === 66, "bracket write value 16");
bracketOrder = 0;
var bracketNested16 = bracketBase(6, bracketObj16)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 16");
bracketCheck(bracketNested16 === 27, "bracket nested value 16");
bracketTotal = bracketTotal + bracketRead16 + bracketObj16.k1 + bracketNested16;
var bracketObj17 = { k0: 20, k1: 24, nested: { hit: 28 } };
bracketOrder = 0;
var bracketRead17 = bracketBase(1, bracketObj17)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 17");
bracketCheck(bracketRead17 === 20, "bracket read value 17");
bracketOrder = 0;
bracketBase(3, bracketObj17)[bracketKey(4, "k1")] = bracketValue(5, 67);
bracketCheck(bracketOrder === 345, "bracket write order 17");
bracketCheck(bracketObj17.k1 === 67, "bracket write value 17");
bracketOrder = 0;
var bracketNested17 = bracketBase(6, bracketObj17)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 17");
bracketCheck(bracketNested17 === 28, "bracket nested value 17");
bracketTotal = bracketTotal + bracketRead17 + bracketObj17.k1 + bracketNested17;
var bracketObj18 = { k0: 21, k1: 25, nested: { hit: 29 } };
bracketOrder = 0;
var bracketRead18 = bracketBase(1, bracketObj18)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 18");
bracketCheck(bracketRead18 === 21, "bracket read value 18");
bracketOrder = 0;
bracketBase(3, bracketObj18)[bracketKey(4, "k1")] = bracketValue(5, 68);
bracketCheck(bracketOrder === 345, "bracket write order 18");
bracketCheck(bracketObj18.k1 === 68, "bracket write value 18");
bracketOrder = 0;
var bracketNested18 = bracketBase(6, bracketObj18)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 18");
bracketCheck(bracketNested18 === 29, "bracket nested value 18");
bracketTotal = bracketTotal + bracketRead18 + bracketObj18.k1 + bracketNested18;
var bracketObj19 = { k0: 22, k1: 26, nested: { hit: 30 } };
bracketOrder = 0;
var bracketRead19 = bracketBase(1, bracketObj19)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 19");
bracketCheck(bracketRead19 === 22, "bracket read value 19");
bracketOrder = 0;
bracketBase(3, bracketObj19)[bracketKey(4, "k1")] = bracketValue(5, 69);
bracketCheck(bracketOrder === 345, "bracket write order 19");
bracketCheck(bracketObj19.k1 === 69, "bracket write value 19");
bracketOrder = 0;
var bracketNested19 = bracketBase(6, bracketObj19)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 19");
bracketCheck(bracketNested19 === 30, "bracket nested value 19");
bracketTotal = bracketTotal + bracketRead19 + bracketObj19.k1 + bracketNested19;
var bracketObj20 = { k0: 23, k1: 27, nested: { hit: 31 } };
bracketOrder = 0;
var bracketRead20 = bracketBase(1, bracketObj20)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 20");
bracketCheck(bracketRead20 === 23, "bracket read value 20");
bracketOrder = 0;
bracketBase(3, bracketObj20)[bracketKey(4, "k1")] = bracketValue(5, 70);
bracketCheck(bracketOrder === 345, "bracket write order 20");
bracketCheck(bracketObj20.k1 === 70, "bracket write value 20");
bracketOrder = 0;
var bracketNested20 = bracketBase(6, bracketObj20)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 20");
bracketCheck(bracketNested20 === 31, "bracket nested value 20");
bracketTotal = bracketTotal + bracketRead20 + bracketObj20.k1 + bracketNested20;
var bracketObj21 = { k0: 24, k1: 28, nested: { hit: 32 } };
bracketOrder = 0;
var bracketRead21 = bracketBase(1, bracketObj21)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 21");
bracketCheck(bracketRead21 === 24, "bracket read value 21");
bracketOrder = 0;
bracketBase(3, bracketObj21)[bracketKey(4, "k1")] = bracketValue(5, 71);
bracketCheck(bracketOrder === 345, "bracket write order 21");
bracketCheck(bracketObj21.k1 === 71, "bracket write value 21");
bracketOrder = 0;
var bracketNested21 = bracketBase(6, bracketObj21)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 21");
bracketCheck(bracketNested21 === 32, "bracket nested value 21");
bracketTotal = bracketTotal + bracketRead21 + bracketObj21.k1 + bracketNested21;
var bracketObj22 = { k0: 25, k1: 29, nested: { hit: 33 } };
bracketOrder = 0;
var bracketRead22 = bracketBase(1, bracketObj22)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 22");
bracketCheck(bracketRead22 === 25, "bracket read value 22");
bracketOrder = 0;
bracketBase(3, bracketObj22)[bracketKey(4, "k1")] = bracketValue(5, 72);
bracketCheck(bracketOrder === 345, "bracket write order 22");
bracketCheck(bracketObj22.k1 === 72, "bracket write value 22");
bracketOrder = 0;
var bracketNested22 = bracketBase(6, bracketObj22)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 22");
bracketCheck(bracketNested22 === 33, "bracket nested value 22");
bracketTotal = bracketTotal + bracketRead22 + bracketObj22.k1 + bracketNested22;
var bracketObj23 = { k0: 26, k1: 30, nested: { hit: 34 } };
bracketOrder = 0;
var bracketRead23 = bracketBase(1, bracketObj23)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 23");
bracketCheck(bracketRead23 === 26, "bracket read value 23");
bracketOrder = 0;
bracketBase(3, bracketObj23)[bracketKey(4, "k1")] = bracketValue(5, 73);
bracketCheck(bracketOrder === 345, "bracket write order 23");
bracketCheck(bracketObj23.k1 === 73, "bracket write value 23");
bracketOrder = 0;
var bracketNested23 = bracketBase(6, bracketObj23)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 23");
bracketCheck(bracketNested23 === 34, "bracket nested value 23");
bracketTotal = bracketTotal + bracketRead23 + bracketObj23.k1 + bracketNested23;
var bracketObj24 = { k0: 27, k1: 31, nested: { hit: 35 } };
bracketOrder = 0;
var bracketRead24 = bracketBase(1, bracketObj24)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 24");
bracketCheck(bracketRead24 === 27, "bracket read value 24");
bracketOrder = 0;
bracketBase(3, bracketObj24)[bracketKey(4, "k1")] = bracketValue(5, 74);
bracketCheck(bracketOrder === 345, "bracket write order 24");
bracketCheck(bracketObj24.k1 === 74, "bracket write value 24");
bracketOrder = 0;
var bracketNested24 = bracketBase(6, bracketObj24)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 24");
bracketCheck(bracketNested24 === 35, "bracket nested value 24");
bracketTotal = bracketTotal + bracketRead24 + bracketObj24.k1 + bracketNested24;
var bracketObj25 = { k0: 28, k1: 32, nested: { hit: 36 } };
bracketOrder = 0;
var bracketRead25 = bracketBase(1, bracketObj25)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 25");
bracketCheck(bracketRead25 === 28, "bracket read value 25");
bracketOrder = 0;
bracketBase(3, bracketObj25)[bracketKey(4, "k1")] = bracketValue(5, 75);
bracketCheck(bracketOrder === 345, "bracket write order 25");
bracketCheck(bracketObj25.k1 === 75, "bracket write value 25");
bracketOrder = 0;
var bracketNested25 = bracketBase(6, bracketObj25)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 25");
bracketCheck(bracketNested25 === 36, "bracket nested value 25");
bracketTotal = bracketTotal + bracketRead25 + bracketObj25.k1 + bracketNested25;
var bracketObj26 = { k0: 29, k1: 33, nested: { hit: 37 } };
bracketOrder = 0;
var bracketRead26 = bracketBase(1, bracketObj26)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 26");
bracketCheck(bracketRead26 === 29, "bracket read value 26");
bracketOrder = 0;
bracketBase(3, bracketObj26)[bracketKey(4, "k1")] = bracketValue(5, 76);
bracketCheck(bracketOrder === 345, "bracket write order 26");
bracketCheck(bracketObj26.k1 === 76, "bracket write value 26");
bracketOrder = 0;
var bracketNested26 = bracketBase(6, bracketObj26)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 26");
bracketCheck(bracketNested26 === 37, "bracket nested value 26");
bracketTotal = bracketTotal + bracketRead26 + bracketObj26.k1 + bracketNested26;
var bracketObj27 = { k0: 30, k1: 34, nested: { hit: 38 } };
bracketOrder = 0;
var bracketRead27 = bracketBase(1, bracketObj27)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 27");
bracketCheck(bracketRead27 === 30, "bracket read value 27");
bracketOrder = 0;
bracketBase(3, bracketObj27)[bracketKey(4, "k1")] = bracketValue(5, 77);
bracketCheck(bracketOrder === 345, "bracket write order 27");
bracketCheck(bracketObj27.k1 === 77, "bracket write value 27");
bracketOrder = 0;
var bracketNested27 = bracketBase(6, bracketObj27)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 27");
bracketCheck(bracketNested27 === 38, "bracket nested value 27");
bracketTotal = bracketTotal + bracketRead27 + bracketObj27.k1 + bracketNested27;
var bracketObj28 = { k0: 31, k1: 35, nested: { hit: 39 } };
bracketOrder = 0;
var bracketRead28 = bracketBase(1, bracketObj28)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 28");
bracketCheck(bracketRead28 === 31, "bracket read value 28");
bracketOrder = 0;
bracketBase(3, bracketObj28)[bracketKey(4, "k1")] = bracketValue(5, 78);
bracketCheck(bracketOrder === 345, "bracket write order 28");
bracketCheck(bracketObj28.k1 === 78, "bracket write value 28");
bracketOrder = 0;
var bracketNested28 = bracketBase(6, bracketObj28)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 28");
bracketCheck(bracketNested28 === 39, "bracket nested value 28");
bracketTotal = bracketTotal + bracketRead28 + bracketObj28.k1 + bracketNested28;
var bracketObj29 = { k0: 32, k1: 36, nested: { hit: 40 } };
bracketOrder = 0;
var bracketRead29 = bracketBase(1, bracketObj29)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 29");
bracketCheck(bracketRead29 === 32, "bracket read value 29");
bracketOrder = 0;
bracketBase(3, bracketObj29)[bracketKey(4, "k1")] = bracketValue(5, 79);
bracketCheck(bracketOrder === 345, "bracket write order 29");
bracketCheck(bracketObj29.k1 === 79, "bracket write value 29");
bracketOrder = 0;
var bracketNested29 = bracketBase(6, bracketObj29)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 29");
bracketCheck(bracketNested29 === 40, "bracket nested value 29");
bracketTotal = bracketTotal + bracketRead29 + bracketObj29.k1 + bracketNested29;
var bracketObj30 = { k0: 33, k1: 37, nested: { hit: 41 } };
bracketOrder = 0;
var bracketRead30 = bracketBase(1, bracketObj30)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 30");
bracketCheck(bracketRead30 === 33, "bracket read value 30");
bracketOrder = 0;
bracketBase(3, bracketObj30)[bracketKey(4, "k1")] = bracketValue(5, 80);
bracketCheck(bracketOrder === 345, "bracket write order 30");
bracketCheck(bracketObj30.k1 === 80, "bracket write value 30");
bracketOrder = 0;
var bracketNested30 = bracketBase(6, bracketObj30)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 30");
bracketCheck(bracketNested30 === 41, "bracket nested value 30");
bracketTotal = bracketTotal + bracketRead30 + bracketObj30.k1 + bracketNested30;
var bracketObj31 = { k0: 34, k1: 38, nested: { hit: 42 } };
bracketOrder = 0;
var bracketRead31 = bracketBase(1, bracketObj31)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 31");
bracketCheck(bracketRead31 === 34, "bracket read value 31");
bracketOrder = 0;
bracketBase(3, bracketObj31)[bracketKey(4, "k1")] = bracketValue(5, 81);
bracketCheck(bracketOrder === 345, "bracket write order 31");
bracketCheck(bracketObj31.k1 === 81, "bracket write value 31");
bracketOrder = 0;
var bracketNested31 = bracketBase(6, bracketObj31)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 31");
bracketCheck(bracketNested31 === 42, "bracket nested value 31");
bracketTotal = bracketTotal + bracketRead31 + bracketObj31.k1 + bracketNested31;
var bracketObj32 = { k0: 35, k1: 39, nested: { hit: 43 } };
bracketOrder = 0;
var bracketRead32 = bracketBase(1, bracketObj32)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 32");
bracketCheck(bracketRead32 === 35, "bracket read value 32");
bracketOrder = 0;
bracketBase(3, bracketObj32)[bracketKey(4, "k1")] = bracketValue(5, 82);
bracketCheck(bracketOrder === 345, "bracket write order 32");
bracketCheck(bracketObj32.k1 === 82, "bracket write value 32");
bracketOrder = 0;
var bracketNested32 = bracketBase(6, bracketObj32)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 32");
bracketCheck(bracketNested32 === 43, "bracket nested value 32");
bracketTotal = bracketTotal + bracketRead32 + bracketObj32.k1 + bracketNested32;
var bracketObj33 = { k0: 36, k1: 40, nested: { hit: 44 } };
bracketOrder = 0;
var bracketRead33 = bracketBase(1, bracketObj33)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 33");
bracketCheck(bracketRead33 === 36, "bracket read value 33");
bracketOrder = 0;
bracketBase(3, bracketObj33)[bracketKey(4, "k1")] = bracketValue(5, 83);
bracketCheck(bracketOrder === 345, "bracket write order 33");
bracketCheck(bracketObj33.k1 === 83, "bracket write value 33");
bracketOrder = 0;
var bracketNested33 = bracketBase(6, bracketObj33)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 33");
bracketCheck(bracketNested33 === 44, "bracket nested value 33");
bracketTotal = bracketTotal + bracketRead33 + bracketObj33.k1 + bracketNested33;
var bracketObj34 = { k0: 37, k1: 41, nested: { hit: 45 } };
bracketOrder = 0;
var bracketRead34 = bracketBase(1, bracketObj34)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 34");
bracketCheck(bracketRead34 === 37, "bracket read value 34");
bracketOrder = 0;
bracketBase(3, bracketObj34)[bracketKey(4, "k1")] = bracketValue(5, 84);
bracketCheck(bracketOrder === 345, "bracket write order 34");
bracketCheck(bracketObj34.k1 === 84, "bracket write value 34");
bracketOrder = 0;
var bracketNested34 = bracketBase(6, bracketObj34)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 34");
bracketCheck(bracketNested34 === 45, "bracket nested value 34");
bracketTotal = bracketTotal + bracketRead34 + bracketObj34.k1 + bracketNested34;
var bracketObj35 = { k0: 38, k1: 42, nested: { hit: 46 } };
bracketOrder = 0;
var bracketRead35 = bracketBase(1, bracketObj35)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 35");
bracketCheck(bracketRead35 === 38, "bracket read value 35");
bracketOrder = 0;
bracketBase(3, bracketObj35)[bracketKey(4, "k1")] = bracketValue(5, 85);
bracketCheck(bracketOrder === 345, "bracket write order 35");
bracketCheck(bracketObj35.k1 === 85, "bracket write value 35");
bracketOrder = 0;
var bracketNested35 = bracketBase(6, bracketObj35)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 35");
bracketCheck(bracketNested35 === 46, "bracket nested value 35");
bracketTotal = bracketTotal + bracketRead35 + bracketObj35.k1 + bracketNested35;
var bracketObj36 = { k0: 39, k1: 43, nested: { hit: 47 } };
bracketOrder = 0;
var bracketRead36 = bracketBase(1, bracketObj36)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 36");
bracketCheck(bracketRead36 === 39, "bracket read value 36");
bracketOrder = 0;
bracketBase(3, bracketObj36)[bracketKey(4, "k1")] = bracketValue(5, 86);
bracketCheck(bracketOrder === 345, "bracket write order 36");
bracketCheck(bracketObj36.k1 === 86, "bracket write value 36");
bracketOrder = 0;
var bracketNested36 = bracketBase(6, bracketObj36)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 36");
bracketCheck(bracketNested36 === 47, "bracket nested value 36");
bracketTotal = bracketTotal + bracketRead36 + bracketObj36.k1 + bracketNested36;
var bracketObj37 = { k0: 40, k1: 44, nested: { hit: 48 } };
bracketOrder = 0;
var bracketRead37 = bracketBase(1, bracketObj37)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 37");
bracketCheck(bracketRead37 === 40, "bracket read value 37");
bracketOrder = 0;
bracketBase(3, bracketObj37)[bracketKey(4, "k1")] = bracketValue(5, 87);
bracketCheck(bracketOrder === 345, "bracket write order 37");
bracketCheck(bracketObj37.k1 === 87, "bracket write value 37");
bracketOrder = 0;
var bracketNested37 = bracketBase(6, bracketObj37)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 37");
bracketCheck(bracketNested37 === 48, "bracket nested value 37");
bracketTotal = bracketTotal + bracketRead37 + bracketObj37.k1 + bracketNested37;
var bracketObj38 = { k0: 41, k1: 45, nested: { hit: 49 } };
bracketOrder = 0;
var bracketRead38 = bracketBase(1, bracketObj38)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 38");
bracketCheck(bracketRead38 === 41, "bracket read value 38");
bracketOrder = 0;
bracketBase(3, bracketObj38)[bracketKey(4, "k1")] = bracketValue(5, 88);
bracketCheck(bracketOrder === 345, "bracket write order 38");
bracketCheck(bracketObj38.k1 === 88, "bracket write value 38");
bracketOrder = 0;
var bracketNested38 = bracketBase(6, bracketObj38)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 38");
bracketCheck(bracketNested38 === 49, "bracket nested value 38");
bracketTotal = bracketTotal + bracketRead38 + bracketObj38.k1 + bracketNested38;
var bracketObj39 = { k0: 42, k1: 46, nested: { hit: 50 } };
bracketOrder = 0;
var bracketRead39 = bracketBase(1, bracketObj39)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 39");
bracketCheck(bracketRead39 === 42, "bracket read value 39");
bracketOrder = 0;
bracketBase(3, bracketObj39)[bracketKey(4, "k1")] = bracketValue(5, 89);
bracketCheck(bracketOrder === 345, "bracket write order 39");
bracketCheck(bracketObj39.k1 === 89, "bracket write value 39");
bracketOrder = 0;
var bracketNested39 = bracketBase(6, bracketObj39)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 39");
bracketCheck(bracketNested39 === 50, "bracket nested value 39");
bracketTotal = bracketTotal + bracketRead39 + bracketObj39.k1 + bracketNested39;
var bracketObj40 = { k0: 43, k1: 47, nested: { hit: 51 } };
bracketOrder = 0;
var bracketRead40 = bracketBase(1, bracketObj40)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 40");
bracketCheck(bracketRead40 === 43, "bracket read value 40");
bracketOrder = 0;
bracketBase(3, bracketObj40)[bracketKey(4, "k1")] = bracketValue(5, 90);
bracketCheck(bracketOrder === 345, "bracket write order 40");
bracketCheck(bracketObj40.k1 === 90, "bracket write value 40");
bracketOrder = 0;
var bracketNested40 = bracketBase(6, bracketObj40)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 40");
bracketCheck(bracketNested40 === 51, "bracket nested value 40");
bracketTotal = bracketTotal + bracketRead40 + bracketObj40.k1 + bracketNested40;
var bracketObj41 = { k0: 44, k1: 48, nested: { hit: 52 } };
bracketOrder = 0;
var bracketRead41 = bracketBase(1, bracketObj41)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 41");
bracketCheck(bracketRead41 === 44, "bracket read value 41");
bracketOrder = 0;
bracketBase(3, bracketObj41)[bracketKey(4, "k1")] = bracketValue(5, 91);
bracketCheck(bracketOrder === 345, "bracket write order 41");
bracketCheck(bracketObj41.k1 === 91, "bracket write value 41");
bracketOrder = 0;
var bracketNested41 = bracketBase(6, bracketObj41)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 41");
bracketCheck(bracketNested41 === 52, "bracket nested value 41");
bracketTotal = bracketTotal + bracketRead41 + bracketObj41.k1 + bracketNested41;
var bracketObj42 = { k0: 45, k1: 49, nested: { hit: 53 } };
bracketOrder = 0;
var bracketRead42 = bracketBase(1, bracketObj42)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 42");
bracketCheck(bracketRead42 === 45, "bracket read value 42");
bracketOrder = 0;
bracketBase(3, bracketObj42)[bracketKey(4, "k1")] = bracketValue(5, 92);
bracketCheck(bracketOrder === 345, "bracket write order 42");
bracketCheck(bracketObj42.k1 === 92, "bracket write value 42");
bracketOrder = 0;
var bracketNested42 = bracketBase(6, bracketObj42)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 42");
bracketCheck(bracketNested42 === 53, "bracket nested value 42");
bracketTotal = bracketTotal + bracketRead42 + bracketObj42.k1 + bracketNested42;
var bracketObj43 = { k0: 46, k1: 50, nested: { hit: 54 } };
bracketOrder = 0;
var bracketRead43 = bracketBase(1, bracketObj43)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 43");
bracketCheck(bracketRead43 === 46, "bracket read value 43");
bracketOrder = 0;
bracketBase(3, bracketObj43)[bracketKey(4, "k1")] = bracketValue(5, 93);
bracketCheck(bracketOrder === 345, "bracket write order 43");
bracketCheck(bracketObj43.k1 === 93, "bracket write value 43");
bracketOrder = 0;
var bracketNested43 = bracketBase(6, bracketObj43)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 43");
bracketCheck(bracketNested43 === 54, "bracket nested value 43");
bracketTotal = bracketTotal + bracketRead43 + bracketObj43.k1 + bracketNested43;
var bracketObj44 = { k0: 47, k1: 51, nested: { hit: 55 } };
bracketOrder = 0;
var bracketRead44 = bracketBase(1, bracketObj44)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 44");
bracketCheck(bracketRead44 === 47, "bracket read value 44");
bracketOrder = 0;
bracketBase(3, bracketObj44)[bracketKey(4, "k1")] = bracketValue(5, 94);
bracketCheck(bracketOrder === 345, "bracket write order 44");
bracketCheck(bracketObj44.k1 === 94, "bracket write value 44");
bracketOrder = 0;
var bracketNested44 = bracketBase(6, bracketObj44)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 44");
bracketCheck(bracketNested44 === 55, "bracket nested value 44");
bracketTotal = bracketTotal + bracketRead44 + bracketObj44.k1 + bracketNested44;
var bracketObj45 = { k0: 48, k1: 52, nested: { hit: 56 } };
bracketOrder = 0;
var bracketRead45 = bracketBase(1, bracketObj45)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 45");
bracketCheck(bracketRead45 === 48, "bracket read value 45");
bracketOrder = 0;
bracketBase(3, bracketObj45)[bracketKey(4, "k1")] = bracketValue(5, 95);
bracketCheck(bracketOrder === 345, "bracket write order 45");
bracketCheck(bracketObj45.k1 === 95, "bracket write value 45");
bracketOrder = 0;
var bracketNested45 = bracketBase(6, bracketObj45)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 45");
bracketCheck(bracketNested45 === 56, "bracket nested value 45");
bracketTotal = bracketTotal + bracketRead45 + bracketObj45.k1 + bracketNested45;
var bracketObj46 = { k0: 49, k1: 53, nested: { hit: 57 } };
bracketOrder = 0;
var bracketRead46 = bracketBase(1, bracketObj46)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 46");
bracketCheck(bracketRead46 === 49, "bracket read value 46");
bracketOrder = 0;
bracketBase(3, bracketObj46)[bracketKey(4, "k1")] = bracketValue(5, 96);
bracketCheck(bracketOrder === 345, "bracket write order 46");
bracketCheck(bracketObj46.k1 === 96, "bracket write value 46");
bracketOrder = 0;
var bracketNested46 = bracketBase(6, bracketObj46)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 46");
bracketCheck(bracketNested46 === 57, "bracket nested value 46");
bracketTotal = bracketTotal + bracketRead46 + bracketObj46.k1 + bracketNested46;
var bracketObj47 = { k0: 50, k1: 54, nested: { hit: 58 } };
bracketOrder = 0;
var bracketRead47 = bracketBase(1, bracketObj47)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 47");
bracketCheck(bracketRead47 === 50, "bracket read value 47");
bracketOrder = 0;
bracketBase(3, bracketObj47)[bracketKey(4, "k1")] = bracketValue(5, 97);
bracketCheck(bracketOrder === 345, "bracket write order 47");
bracketCheck(bracketObj47.k1 === 97, "bracket write value 47");
bracketOrder = 0;
var bracketNested47 = bracketBase(6, bracketObj47)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 47");
bracketCheck(bracketNested47 === 58, "bracket nested value 47");
bracketTotal = bracketTotal + bracketRead47 + bracketObj47.k1 + bracketNested47;
var bracketObj48 = { k0: 51, k1: 55, nested: { hit: 59 } };
bracketOrder = 0;
var bracketRead48 = bracketBase(1, bracketObj48)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 48");
bracketCheck(bracketRead48 === 51, "bracket read value 48");
bracketOrder = 0;
bracketBase(3, bracketObj48)[bracketKey(4, "k1")] = bracketValue(5, 98);
bracketCheck(bracketOrder === 345, "bracket write order 48");
bracketCheck(bracketObj48.k1 === 98, "bracket write value 48");
bracketOrder = 0;
var bracketNested48 = bracketBase(6, bracketObj48)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 48");
bracketCheck(bracketNested48 === 59, "bracket nested value 48");
bracketTotal = bracketTotal + bracketRead48 + bracketObj48.k1 + bracketNested48;
var bracketObj49 = { k0: 52, k1: 56, nested: { hit: 60 } };
bracketOrder = 0;
var bracketRead49 = bracketBase(1, bracketObj49)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 49");
bracketCheck(bracketRead49 === 52, "bracket read value 49");
bracketOrder = 0;
bracketBase(3, bracketObj49)[bracketKey(4, "k1")] = bracketValue(5, 99);
bracketCheck(bracketOrder === 345, "bracket write order 49");
bracketCheck(bracketObj49.k1 === 99, "bracket write value 49");
bracketOrder = 0;
var bracketNested49 = bracketBase(6, bracketObj49)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 49");
bracketCheck(bracketNested49 === 60, "bracket nested value 49");
bracketTotal = bracketTotal + bracketRead49 + bracketObj49.k1 + bracketNested49;
var bracketObj50 = { k0: 53, k1: 57, nested: { hit: 61 } };
bracketOrder = 0;
var bracketRead50 = bracketBase(1, bracketObj50)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 50");
bracketCheck(bracketRead50 === 53, "bracket read value 50");
bracketOrder = 0;
bracketBase(3, bracketObj50)[bracketKey(4, "k1")] = bracketValue(5, 100);
bracketCheck(bracketOrder === 345, "bracket write order 50");
bracketCheck(bracketObj50.k1 === 100, "bracket write value 50");
bracketOrder = 0;
var bracketNested50 = bracketBase(6, bracketObj50)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 50");
bracketCheck(bracketNested50 === 61, "bracket nested value 50");
bracketTotal = bracketTotal + bracketRead50 + bracketObj50.k1 + bracketNested50;
var bracketObj51 = { k0: 54, k1: 58, nested: { hit: 62 } };
bracketOrder = 0;
var bracketRead51 = bracketBase(1, bracketObj51)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 51");
bracketCheck(bracketRead51 === 54, "bracket read value 51");
bracketOrder = 0;
bracketBase(3, bracketObj51)[bracketKey(4, "k1")] = bracketValue(5, 101);
bracketCheck(bracketOrder === 345, "bracket write order 51");
bracketCheck(bracketObj51.k1 === 101, "bracket write value 51");
bracketOrder = 0;
var bracketNested51 = bracketBase(6, bracketObj51)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 51");
bracketCheck(bracketNested51 === 62, "bracket nested value 51");
bracketTotal = bracketTotal + bracketRead51 + bracketObj51.k1 + bracketNested51;
var bracketObj52 = { k0: 55, k1: 59, nested: { hit: 63 } };
bracketOrder = 0;
var bracketRead52 = bracketBase(1, bracketObj52)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 52");
bracketCheck(bracketRead52 === 55, "bracket read value 52");
bracketOrder = 0;
bracketBase(3, bracketObj52)[bracketKey(4, "k1")] = bracketValue(5, 102);
bracketCheck(bracketOrder === 345, "bracket write order 52");
bracketCheck(bracketObj52.k1 === 102, "bracket write value 52");
bracketOrder = 0;
var bracketNested52 = bracketBase(6, bracketObj52)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 52");
bracketCheck(bracketNested52 === 63, "bracket nested value 52");
bracketTotal = bracketTotal + bracketRead52 + bracketObj52.k1 + bracketNested52;
var bracketObj53 = { k0: 56, k1: 60, nested: { hit: 64 } };
bracketOrder = 0;
var bracketRead53 = bracketBase(1, bracketObj53)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 53");
bracketCheck(bracketRead53 === 56, "bracket read value 53");
bracketOrder = 0;
bracketBase(3, bracketObj53)[bracketKey(4, "k1")] = bracketValue(5, 103);
bracketCheck(bracketOrder === 345, "bracket write order 53");
bracketCheck(bracketObj53.k1 === 103, "bracket write value 53");
bracketOrder = 0;
var bracketNested53 = bracketBase(6, bracketObj53)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 53");
bracketCheck(bracketNested53 === 64, "bracket nested value 53");
bracketTotal = bracketTotal + bracketRead53 + bracketObj53.k1 + bracketNested53;
var bracketObj54 = { k0: 57, k1: 61, nested: { hit: 65 } };
bracketOrder = 0;
var bracketRead54 = bracketBase(1, bracketObj54)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 54");
bracketCheck(bracketRead54 === 57, "bracket read value 54");
bracketOrder = 0;
bracketBase(3, bracketObj54)[bracketKey(4, "k1")] = bracketValue(5, 104);
bracketCheck(bracketOrder === 345, "bracket write order 54");
bracketCheck(bracketObj54.k1 === 104, "bracket write value 54");
bracketOrder = 0;
var bracketNested54 = bracketBase(6, bracketObj54)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 54");
bracketCheck(bracketNested54 === 65, "bracket nested value 54");
bracketTotal = bracketTotal + bracketRead54 + bracketObj54.k1 + bracketNested54;
var bracketObj55 = { k0: 58, k1: 62, nested: { hit: 66 } };
bracketOrder = 0;
var bracketRead55 = bracketBase(1, bracketObj55)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 55");
bracketCheck(bracketRead55 === 58, "bracket read value 55");
bracketOrder = 0;
bracketBase(3, bracketObj55)[bracketKey(4, "k1")] = bracketValue(5, 105);
bracketCheck(bracketOrder === 345, "bracket write order 55");
bracketCheck(bracketObj55.k1 === 105, "bracket write value 55");
bracketOrder = 0;
var bracketNested55 = bracketBase(6, bracketObj55)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 55");
bracketCheck(bracketNested55 === 66, "bracket nested value 55");
bracketTotal = bracketTotal + bracketRead55 + bracketObj55.k1 + bracketNested55;
var bracketObj56 = { k0: 59, k1: 63, nested: { hit: 67 } };
bracketOrder = 0;
var bracketRead56 = bracketBase(1, bracketObj56)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 56");
bracketCheck(bracketRead56 === 59, "bracket read value 56");
bracketOrder = 0;
bracketBase(3, bracketObj56)[bracketKey(4, "k1")] = bracketValue(5, 106);
bracketCheck(bracketOrder === 345, "bracket write order 56");
bracketCheck(bracketObj56.k1 === 106, "bracket write value 56");
bracketOrder = 0;
var bracketNested56 = bracketBase(6, bracketObj56)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 56");
bracketCheck(bracketNested56 === 67, "bracket nested value 56");
bracketTotal = bracketTotal + bracketRead56 + bracketObj56.k1 + bracketNested56;
var bracketObj57 = { k0: 60, k1: 64, nested: { hit: 68 } };
bracketOrder = 0;
var bracketRead57 = bracketBase(1, bracketObj57)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 57");
bracketCheck(bracketRead57 === 60, "bracket read value 57");
bracketOrder = 0;
bracketBase(3, bracketObj57)[bracketKey(4, "k1")] = bracketValue(5, 107);
bracketCheck(bracketOrder === 345, "bracket write order 57");
bracketCheck(bracketObj57.k1 === 107, "bracket write value 57");
bracketOrder = 0;
var bracketNested57 = bracketBase(6, bracketObj57)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 57");
bracketCheck(bracketNested57 === 68, "bracket nested value 57");
bracketTotal = bracketTotal + bracketRead57 + bracketObj57.k1 + bracketNested57;
var bracketObj58 = { k0: 61, k1: 65, nested: { hit: 69 } };
bracketOrder = 0;
var bracketRead58 = bracketBase(1, bracketObj58)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 58");
bracketCheck(bracketRead58 === 61, "bracket read value 58");
bracketOrder = 0;
bracketBase(3, bracketObj58)[bracketKey(4, "k1")] = bracketValue(5, 108);
bracketCheck(bracketOrder === 345, "bracket write order 58");
bracketCheck(bracketObj58.k1 === 108, "bracket write value 58");
bracketOrder = 0;
var bracketNested58 = bracketBase(6, bracketObj58)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 58");
bracketCheck(bracketNested58 === 69, "bracket nested value 58");
bracketTotal = bracketTotal + bracketRead58 + bracketObj58.k1 + bracketNested58;
var bracketObj59 = { k0: 62, k1: 66, nested: { hit: 70 } };
bracketOrder = 0;
var bracketRead59 = bracketBase(1, bracketObj59)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 59");
bracketCheck(bracketRead59 === 62, "bracket read value 59");
bracketOrder = 0;
bracketBase(3, bracketObj59)[bracketKey(4, "k1")] = bracketValue(5, 109);
bracketCheck(bracketOrder === 345, "bracket write order 59");
bracketCheck(bracketObj59.k1 === 109, "bracket write value 59");
bracketOrder = 0;
var bracketNested59 = bracketBase(6, bracketObj59)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 59");
bracketCheck(bracketNested59 === 70, "bracket nested value 59");
bracketTotal = bracketTotal + bracketRead59 + bracketObj59.k1 + bracketNested59;
var bracketObj60 = { k0: 63, k1: 67, nested: { hit: 71 } };
bracketOrder = 0;
var bracketRead60 = bracketBase(1, bracketObj60)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 60");
bracketCheck(bracketRead60 === 63, "bracket read value 60");
bracketOrder = 0;
bracketBase(3, bracketObj60)[bracketKey(4, "k1")] = bracketValue(5, 110);
bracketCheck(bracketOrder === 345, "bracket write order 60");
bracketCheck(bracketObj60.k1 === 110, "bracket write value 60");
bracketOrder = 0;
var bracketNested60 = bracketBase(6, bracketObj60)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 60");
bracketCheck(bracketNested60 === 71, "bracket nested value 60");
bracketTotal = bracketTotal + bracketRead60 + bracketObj60.k1 + bracketNested60;
var bracketObj61 = { k0: 64, k1: 68, nested: { hit: 72 } };
bracketOrder = 0;
var bracketRead61 = bracketBase(1, bracketObj61)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 61");
bracketCheck(bracketRead61 === 64, "bracket read value 61");
bracketOrder = 0;
bracketBase(3, bracketObj61)[bracketKey(4, "k1")] = bracketValue(5, 111);
bracketCheck(bracketOrder === 345, "bracket write order 61");
bracketCheck(bracketObj61.k1 === 111, "bracket write value 61");
bracketOrder = 0;
var bracketNested61 = bracketBase(6, bracketObj61)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 61");
bracketCheck(bracketNested61 === 72, "bracket nested value 61");
bracketTotal = bracketTotal + bracketRead61 + bracketObj61.k1 + bracketNested61;
var bracketObj62 = { k0: 65, k1: 69, nested: { hit: 73 } };
bracketOrder = 0;
var bracketRead62 = bracketBase(1, bracketObj62)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 62");
bracketCheck(bracketRead62 === 65, "bracket read value 62");
bracketOrder = 0;
bracketBase(3, bracketObj62)[bracketKey(4, "k1")] = bracketValue(5, 112);
bracketCheck(bracketOrder === 345, "bracket write order 62");
bracketCheck(bracketObj62.k1 === 112, "bracket write value 62");
bracketOrder = 0;
var bracketNested62 = bracketBase(6, bracketObj62)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 62");
bracketCheck(bracketNested62 === 73, "bracket nested value 62");
bracketTotal = bracketTotal + bracketRead62 + bracketObj62.k1 + bracketNested62;
var bracketObj63 = { k0: 66, k1: 70, nested: { hit: 74 } };
bracketOrder = 0;
var bracketRead63 = bracketBase(1, bracketObj63)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 63");
bracketCheck(bracketRead63 === 66, "bracket read value 63");
bracketOrder = 0;
bracketBase(3, bracketObj63)[bracketKey(4, "k1")] = bracketValue(5, 113);
bracketCheck(bracketOrder === 345, "bracket write order 63");
bracketCheck(bracketObj63.k1 === 113, "bracket write value 63");
bracketOrder = 0;
var bracketNested63 = bracketBase(6, bracketObj63)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 63");
bracketCheck(bracketNested63 === 74, "bracket nested value 63");
bracketTotal = bracketTotal + bracketRead63 + bracketObj63.k1 + bracketNested63;
var bracketObj64 = { k0: 67, k1: 71, nested: { hit: 75 } };
bracketOrder = 0;
var bracketRead64 = bracketBase(1, bracketObj64)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 64");
bracketCheck(bracketRead64 === 67, "bracket read value 64");
bracketOrder = 0;
bracketBase(3, bracketObj64)[bracketKey(4, "k1")] = bracketValue(5, 114);
bracketCheck(bracketOrder === 345, "bracket write order 64");
bracketCheck(bracketObj64.k1 === 114, "bracket write value 64");
bracketOrder = 0;
var bracketNested64 = bracketBase(6, bracketObj64)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 64");
bracketCheck(bracketNested64 === 75, "bracket nested value 64");
bracketTotal = bracketTotal + bracketRead64 + bracketObj64.k1 + bracketNested64;
var bracketObj65 = { k0: 68, k1: 72, nested: { hit: 76 } };
bracketOrder = 0;
var bracketRead65 = bracketBase(1, bracketObj65)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 65");
bracketCheck(bracketRead65 === 68, "bracket read value 65");
bracketOrder = 0;
bracketBase(3, bracketObj65)[bracketKey(4, "k1")] = bracketValue(5, 115);
bracketCheck(bracketOrder === 345, "bracket write order 65");
bracketCheck(bracketObj65.k1 === 115, "bracket write value 65");
bracketOrder = 0;
var bracketNested65 = bracketBase(6, bracketObj65)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 65");
bracketCheck(bracketNested65 === 76, "bracket nested value 65");
bracketTotal = bracketTotal + bracketRead65 + bracketObj65.k1 + bracketNested65;
var bracketObj66 = { k0: 69, k1: 73, nested: { hit: 77 } };
bracketOrder = 0;
var bracketRead66 = bracketBase(1, bracketObj66)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 66");
bracketCheck(bracketRead66 === 69, "bracket read value 66");
bracketOrder = 0;
bracketBase(3, bracketObj66)[bracketKey(4, "k1")] = bracketValue(5, 116);
bracketCheck(bracketOrder === 345, "bracket write order 66");
bracketCheck(bracketObj66.k1 === 116, "bracket write value 66");
bracketOrder = 0;
var bracketNested66 = bracketBase(6, bracketObj66)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 66");
bracketCheck(bracketNested66 === 77, "bracket nested value 66");
bracketTotal = bracketTotal + bracketRead66 + bracketObj66.k1 + bracketNested66;
var bracketObj67 = { k0: 70, k1: 74, nested: { hit: 78 } };
bracketOrder = 0;
var bracketRead67 = bracketBase(1, bracketObj67)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 67");
bracketCheck(bracketRead67 === 70, "bracket read value 67");
bracketOrder = 0;
bracketBase(3, bracketObj67)[bracketKey(4, "k1")] = bracketValue(5, 117);
bracketCheck(bracketOrder === 345, "bracket write order 67");
bracketCheck(bracketObj67.k1 === 117, "bracket write value 67");
bracketOrder = 0;
var bracketNested67 = bracketBase(6, bracketObj67)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 67");
bracketCheck(bracketNested67 === 78, "bracket nested value 67");
bracketTotal = bracketTotal + bracketRead67 + bracketObj67.k1 + bracketNested67;
var bracketObj68 = { k0: 71, k1: 75, nested: { hit: 79 } };
bracketOrder = 0;
var bracketRead68 = bracketBase(1, bracketObj68)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 68");
bracketCheck(bracketRead68 === 71, "bracket read value 68");
bracketOrder = 0;
bracketBase(3, bracketObj68)[bracketKey(4, "k1")] = bracketValue(5, 118);
bracketCheck(bracketOrder === 345, "bracket write order 68");
bracketCheck(bracketObj68.k1 === 118, "bracket write value 68");
bracketOrder = 0;
var bracketNested68 = bracketBase(6, bracketObj68)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 68");
bracketCheck(bracketNested68 === 79, "bracket nested value 68");
bracketTotal = bracketTotal + bracketRead68 + bracketObj68.k1 + bracketNested68;
var bracketObj69 = { k0: 72, k1: 76, nested: { hit: 80 } };
bracketOrder = 0;
var bracketRead69 = bracketBase(1, bracketObj69)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 69");
bracketCheck(bracketRead69 === 72, "bracket read value 69");
bracketOrder = 0;
bracketBase(3, bracketObj69)[bracketKey(4, "k1")] = bracketValue(5, 119);
bracketCheck(bracketOrder === 345, "bracket write order 69");
bracketCheck(bracketObj69.k1 === 119, "bracket write value 69");
bracketOrder = 0;
var bracketNested69 = bracketBase(6, bracketObj69)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 69");
bracketCheck(bracketNested69 === 80, "bracket nested value 69");
bracketTotal = bracketTotal + bracketRead69 + bracketObj69.k1 + bracketNested69;
var bracketObj70 = { k0: 73, k1: 77, nested: { hit: 81 } };
bracketOrder = 0;
var bracketRead70 = bracketBase(1, bracketObj70)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 70");
bracketCheck(bracketRead70 === 73, "bracket read value 70");
bracketOrder = 0;
bracketBase(3, bracketObj70)[bracketKey(4, "k1")] = bracketValue(5, 120);
bracketCheck(bracketOrder === 345, "bracket write order 70");
bracketCheck(bracketObj70.k1 === 120, "bracket write value 70");
bracketOrder = 0;
var bracketNested70 = bracketBase(6, bracketObj70)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 70");
bracketCheck(bracketNested70 === 81, "bracket nested value 70");
bracketTotal = bracketTotal + bracketRead70 + bracketObj70.k1 + bracketNested70;
var bracketObj71 = { k0: 74, k1: 78, nested: { hit: 82 } };
bracketOrder = 0;
var bracketRead71 = bracketBase(1, bracketObj71)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 71");
bracketCheck(bracketRead71 === 74, "bracket read value 71");
bracketOrder = 0;
bracketBase(3, bracketObj71)[bracketKey(4, "k1")] = bracketValue(5, 121);
bracketCheck(bracketOrder === 345, "bracket write order 71");
bracketCheck(bracketObj71.k1 === 121, "bracket write value 71");
bracketOrder = 0;
var bracketNested71 = bracketBase(6, bracketObj71)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 71");
bracketCheck(bracketNested71 === 82, "bracket nested value 71");
bracketTotal = bracketTotal + bracketRead71 + bracketObj71.k1 + bracketNested71;
var bracketObj72 = { k0: 75, k1: 79, nested: { hit: 83 } };
bracketOrder = 0;
var bracketRead72 = bracketBase(1, bracketObj72)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 72");
bracketCheck(bracketRead72 === 75, "bracket read value 72");
bracketOrder = 0;
bracketBase(3, bracketObj72)[bracketKey(4, "k1")] = bracketValue(5, 122);
bracketCheck(bracketOrder === 345, "bracket write order 72");
bracketCheck(bracketObj72.k1 === 122, "bracket write value 72");
bracketOrder = 0;
var bracketNested72 = bracketBase(6, bracketObj72)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 72");
bracketCheck(bracketNested72 === 83, "bracket nested value 72");
bracketTotal = bracketTotal + bracketRead72 + bracketObj72.k1 + bracketNested72;
var bracketObj73 = { k0: 76, k1: 80, nested: { hit: 84 } };
bracketOrder = 0;
var bracketRead73 = bracketBase(1, bracketObj73)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 73");
bracketCheck(bracketRead73 === 76, "bracket read value 73");
bracketOrder = 0;
bracketBase(3, bracketObj73)[bracketKey(4, "k1")] = bracketValue(5, 123);
bracketCheck(bracketOrder === 345, "bracket write order 73");
bracketCheck(bracketObj73.k1 === 123, "bracket write value 73");
bracketOrder = 0;
var bracketNested73 = bracketBase(6, bracketObj73)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 73");
bracketCheck(bracketNested73 === 84, "bracket nested value 73");
bracketTotal = bracketTotal + bracketRead73 + bracketObj73.k1 + bracketNested73;
var bracketObj74 = { k0: 77, k1: 81, nested: { hit: 85 } };
bracketOrder = 0;
var bracketRead74 = bracketBase(1, bracketObj74)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 74");
bracketCheck(bracketRead74 === 77, "bracket read value 74");
bracketOrder = 0;
bracketBase(3, bracketObj74)[bracketKey(4, "k1")] = bracketValue(5, 124);
bracketCheck(bracketOrder === 345, "bracket write order 74");
bracketCheck(bracketObj74.k1 === 124, "bracket write value 74");
bracketOrder = 0;
var bracketNested74 = bracketBase(6, bracketObj74)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 74");
bracketCheck(bracketNested74 === 85, "bracket nested value 74");
bracketTotal = bracketTotal + bracketRead74 + bracketObj74.k1 + bracketNested74;
var bracketObj75 = { k0: 78, k1: 82, nested: { hit: 86 } };
bracketOrder = 0;
var bracketRead75 = bracketBase(1, bracketObj75)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 75");
bracketCheck(bracketRead75 === 78, "bracket read value 75");
bracketOrder = 0;
bracketBase(3, bracketObj75)[bracketKey(4, "k1")] = bracketValue(5, 125);
bracketCheck(bracketOrder === 345, "bracket write order 75");
bracketCheck(bracketObj75.k1 === 125, "bracket write value 75");
bracketOrder = 0;
var bracketNested75 = bracketBase(6, bracketObj75)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 75");
bracketCheck(bracketNested75 === 86, "bracket nested value 75");
bracketTotal = bracketTotal + bracketRead75 + bracketObj75.k1 + bracketNested75;
var bracketObj76 = { k0: 79, k1: 83, nested: { hit: 87 } };
bracketOrder = 0;
var bracketRead76 = bracketBase(1, bracketObj76)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 76");
bracketCheck(bracketRead76 === 79, "bracket read value 76");
bracketOrder = 0;
bracketBase(3, bracketObj76)[bracketKey(4, "k1")] = bracketValue(5, 126);
bracketCheck(bracketOrder === 345, "bracket write order 76");
bracketCheck(bracketObj76.k1 === 126, "bracket write value 76");
bracketOrder = 0;
var bracketNested76 = bracketBase(6, bracketObj76)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 76");
bracketCheck(bracketNested76 === 87, "bracket nested value 76");
bracketTotal = bracketTotal + bracketRead76 + bracketObj76.k1 + bracketNested76;
var bracketObj77 = { k0: 80, k1: 84, nested: { hit: 88 } };
bracketOrder = 0;
var bracketRead77 = bracketBase(1, bracketObj77)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 77");
bracketCheck(bracketRead77 === 80, "bracket read value 77");
bracketOrder = 0;
bracketBase(3, bracketObj77)[bracketKey(4, "k1")] = bracketValue(5, 127);
bracketCheck(bracketOrder === 345, "bracket write order 77");
bracketCheck(bracketObj77.k1 === 127, "bracket write value 77");
bracketOrder = 0;
var bracketNested77 = bracketBase(6, bracketObj77)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 77");
bracketCheck(bracketNested77 === 88, "bracket nested value 77");
bracketTotal = bracketTotal + bracketRead77 + bracketObj77.k1 + bracketNested77;
var bracketObj78 = { k0: 81, k1: 85, nested: { hit: 89 } };
bracketOrder = 0;
var bracketRead78 = bracketBase(1, bracketObj78)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 78");
bracketCheck(bracketRead78 === 81, "bracket read value 78");
bracketOrder = 0;
bracketBase(3, bracketObj78)[bracketKey(4, "k1")] = bracketValue(5, 128);
bracketCheck(bracketOrder === 345, "bracket write order 78");
bracketCheck(bracketObj78.k1 === 128, "bracket write value 78");
bracketOrder = 0;
var bracketNested78 = bracketBase(6, bracketObj78)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 78");
bracketCheck(bracketNested78 === 89, "bracket nested value 78");
bracketTotal = bracketTotal + bracketRead78 + bracketObj78.k1 + bracketNested78;
var bracketObj79 = { k0: 82, k1: 86, nested: { hit: 90 } };
bracketOrder = 0;
var bracketRead79 = bracketBase(1, bracketObj79)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 79");
bracketCheck(bracketRead79 === 82, "bracket read value 79");
bracketOrder = 0;
bracketBase(3, bracketObj79)[bracketKey(4, "k1")] = bracketValue(5, 129);
bracketCheck(bracketOrder === 345, "bracket write order 79");
bracketCheck(bracketObj79.k1 === 129, "bracket write value 79");
bracketOrder = 0;
var bracketNested79 = bracketBase(6, bracketObj79)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 79");
bracketCheck(bracketNested79 === 90, "bracket nested value 79");
bracketTotal = bracketTotal + bracketRead79 + bracketObj79.k1 + bracketNested79;
var bracketObj80 = { k0: 83, k1: 87, nested: { hit: 91 } };
bracketOrder = 0;
var bracketRead80 = bracketBase(1, bracketObj80)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 80");
bracketCheck(bracketRead80 === 83, "bracket read value 80");
bracketOrder = 0;
bracketBase(3, bracketObj80)[bracketKey(4, "k1")] = bracketValue(5, 130);
bracketCheck(bracketOrder === 345, "bracket write order 80");
bracketCheck(bracketObj80.k1 === 130, "bracket write value 80");
bracketOrder = 0;
var bracketNested80 = bracketBase(6, bracketObj80)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 80");
bracketCheck(bracketNested80 === 91, "bracket nested value 80");
bracketTotal = bracketTotal + bracketRead80 + bracketObj80.k1 + bracketNested80;
var bracketObj81 = { k0: 84, k1: 88, nested: { hit: 92 } };
bracketOrder = 0;
var bracketRead81 = bracketBase(1, bracketObj81)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 81");
bracketCheck(bracketRead81 === 84, "bracket read value 81");
bracketOrder = 0;
bracketBase(3, bracketObj81)[bracketKey(4, "k1")] = bracketValue(5, 131);
bracketCheck(bracketOrder === 345, "bracket write order 81");
bracketCheck(bracketObj81.k1 === 131, "bracket write value 81");
bracketOrder = 0;
var bracketNested81 = bracketBase(6, bracketObj81)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 81");
bracketCheck(bracketNested81 === 92, "bracket nested value 81");
bracketTotal = bracketTotal + bracketRead81 + bracketObj81.k1 + bracketNested81;
var bracketObj82 = { k0: 85, k1: 89, nested: { hit: 93 } };
bracketOrder = 0;
var bracketRead82 = bracketBase(1, bracketObj82)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 82");
bracketCheck(bracketRead82 === 85, "bracket read value 82");
bracketOrder = 0;
bracketBase(3, bracketObj82)[bracketKey(4, "k1")] = bracketValue(5, 132);
bracketCheck(bracketOrder === 345, "bracket write order 82");
bracketCheck(bracketObj82.k1 === 132, "bracket write value 82");
bracketOrder = 0;
var bracketNested82 = bracketBase(6, bracketObj82)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 82");
bracketCheck(bracketNested82 === 93, "bracket nested value 82");
bracketTotal = bracketTotal + bracketRead82 + bracketObj82.k1 + bracketNested82;
var bracketObj83 = { k0: 86, k1: 90, nested: { hit: 94 } };
bracketOrder = 0;
var bracketRead83 = bracketBase(1, bracketObj83)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 83");
bracketCheck(bracketRead83 === 86, "bracket read value 83");
bracketOrder = 0;
bracketBase(3, bracketObj83)[bracketKey(4, "k1")] = bracketValue(5, 133);
bracketCheck(bracketOrder === 345, "bracket write order 83");
bracketCheck(bracketObj83.k1 === 133, "bracket write value 83");
bracketOrder = 0;
var bracketNested83 = bracketBase(6, bracketObj83)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 83");
bracketCheck(bracketNested83 === 94, "bracket nested value 83");
bracketTotal = bracketTotal + bracketRead83 + bracketObj83.k1 + bracketNested83;
var bracketObj84 = { k0: 87, k1: 91, nested: { hit: 95 } };
bracketOrder = 0;
var bracketRead84 = bracketBase(1, bracketObj84)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 84");
bracketCheck(bracketRead84 === 87, "bracket read value 84");
bracketOrder = 0;
bracketBase(3, bracketObj84)[bracketKey(4, "k1")] = bracketValue(5, 134);
bracketCheck(bracketOrder === 345, "bracket write order 84");
bracketCheck(bracketObj84.k1 === 134, "bracket write value 84");
bracketOrder = 0;
var bracketNested84 = bracketBase(6, bracketObj84)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 84");
bracketCheck(bracketNested84 === 95, "bracket nested value 84");
bracketTotal = bracketTotal + bracketRead84 + bracketObj84.k1 + bracketNested84;
var bracketObj85 = { k0: 88, k1: 92, nested: { hit: 96 } };
bracketOrder = 0;
var bracketRead85 = bracketBase(1, bracketObj85)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 85");
bracketCheck(bracketRead85 === 88, "bracket read value 85");
bracketOrder = 0;
bracketBase(3, bracketObj85)[bracketKey(4, "k1")] = bracketValue(5, 135);
bracketCheck(bracketOrder === 345, "bracket write order 85");
bracketCheck(bracketObj85.k1 === 135, "bracket write value 85");
bracketOrder = 0;
var bracketNested85 = bracketBase(6, bracketObj85)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 85");
bracketCheck(bracketNested85 === 96, "bracket nested value 85");
bracketTotal = bracketTotal + bracketRead85 + bracketObj85.k1 + bracketNested85;
var bracketObj86 = { k0: 89, k1: 93, nested: { hit: 97 } };
bracketOrder = 0;
var bracketRead86 = bracketBase(1, bracketObj86)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 86");
bracketCheck(bracketRead86 === 89, "bracket read value 86");
bracketOrder = 0;
bracketBase(3, bracketObj86)[bracketKey(4, "k1")] = bracketValue(5, 136);
bracketCheck(bracketOrder === 345, "bracket write order 86");
bracketCheck(bracketObj86.k1 === 136, "bracket write value 86");
bracketOrder = 0;
var bracketNested86 = bracketBase(6, bracketObj86)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 86");
bracketCheck(bracketNested86 === 97, "bracket nested value 86");
bracketTotal = bracketTotal + bracketRead86 + bracketObj86.k1 + bracketNested86;
var bracketObj87 = { k0: 90, k1: 94, nested: { hit: 98 } };
bracketOrder = 0;
var bracketRead87 = bracketBase(1, bracketObj87)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 87");
bracketCheck(bracketRead87 === 90, "bracket read value 87");
bracketOrder = 0;
bracketBase(3, bracketObj87)[bracketKey(4, "k1")] = bracketValue(5, 137);
bracketCheck(bracketOrder === 345, "bracket write order 87");
bracketCheck(bracketObj87.k1 === 137, "bracket write value 87");
bracketOrder = 0;
var bracketNested87 = bracketBase(6, bracketObj87)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 87");
bracketCheck(bracketNested87 === 98, "bracket nested value 87");
bracketTotal = bracketTotal + bracketRead87 + bracketObj87.k1 + bracketNested87;
var bracketObj88 = { k0: 91, k1: 95, nested: { hit: 99 } };
bracketOrder = 0;
var bracketRead88 = bracketBase(1, bracketObj88)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 88");
bracketCheck(bracketRead88 === 91, "bracket read value 88");
bracketOrder = 0;
bracketBase(3, bracketObj88)[bracketKey(4, "k1")] = bracketValue(5, 138);
bracketCheck(bracketOrder === 345, "bracket write order 88");
bracketCheck(bracketObj88.k1 === 138, "bracket write value 88");
bracketOrder = 0;
var bracketNested88 = bracketBase(6, bracketObj88)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 88");
bracketCheck(bracketNested88 === 99, "bracket nested value 88");
bracketTotal = bracketTotal + bracketRead88 + bracketObj88.k1 + bracketNested88;
var bracketObj89 = { k0: 92, k1: 96, nested: { hit: 100 } };
bracketOrder = 0;
var bracketRead89 = bracketBase(1, bracketObj89)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 89");
bracketCheck(bracketRead89 === 92, "bracket read value 89");
bracketOrder = 0;
bracketBase(3, bracketObj89)[bracketKey(4, "k1")] = bracketValue(5, 139);
bracketCheck(bracketOrder === 345, "bracket write order 89");
bracketCheck(bracketObj89.k1 === 139, "bracket write value 89");
bracketOrder = 0;
var bracketNested89 = bracketBase(6, bracketObj89)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 89");
bracketCheck(bracketNested89 === 100, "bracket nested value 89");
bracketTotal = bracketTotal + bracketRead89 + bracketObj89.k1 + bracketNested89;
var bracketObj90 = { k0: 93, k1: 97, nested: { hit: 101 } };
bracketOrder = 0;
var bracketRead90 = bracketBase(1, bracketObj90)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 90");
bracketCheck(bracketRead90 === 93, "bracket read value 90");
bracketOrder = 0;
bracketBase(3, bracketObj90)[bracketKey(4, "k1")] = bracketValue(5, 140);
bracketCheck(bracketOrder === 345, "bracket write order 90");
bracketCheck(bracketObj90.k1 === 140, "bracket write value 90");
bracketOrder = 0;
var bracketNested90 = bracketBase(6, bracketObj90)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 90");
bracketCheck(bracketNested90 === 101, "bracket nested value 90");
bracketTotal = bracketTotal + bracketRead90 + bracketObj90.k1 + bracketNested90;
var bracketObj91 = { k0: 94, k1: 98, nested: { hit: 102 } };
bracketOrder = 0;
var bracketRead91 = bracketBase(1, bracketObj91)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 91");
bracketCheck(bracketRead91 === 94, "bracket read value 91");
bracketOrder = 0;
bracketBase(3, bracketObj91)[bracketKey(4, "k1")] = bracketValue(5, 141);
bracketCheck(bracketOrder === 345, "bracket write order 91");
bracketCheck(bracketObj91.k1 === 141, "bracket write value 91");
bracketOrder = 0;
var bracketNested91 = bracketBase(6, bracketObj91)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 91");
bracketCheck(bracketNested91 === 102, "bracket nested value 91");
bracketTotal = bracketTotal + bracketRead91 + bracketObj91.k1 + bracketNested91;
var bracketObj92 = { k0: 95, k1: 99, nested: { hit: 103 } };
bracketOrder = 0;
var bracketRead92 = bracketBase(1, bracketObj92)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 92");
bracketCheck(bracketRead92 === 95, "bracket read value 92");
bracketOrder = 0;
bracketBase(3, bracketObj92)[bracketKey(4, "k1")] = bracketValue(5, 142);
bracketCheck(bracketOrder === 345, "bracket write order 92");
bracketCheck(bracketObj92.k1 === 142, "bracket write value 92");
bracketOrder = 0;
var bracketNested92 = bracketBase(6, bracketObj92)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 92");
bracketCheck(bracketNested92 === 103, "bracket nested value 92");
bracketTotal = bracketTotal + bracketRead92 + bracketObj92.k1 + bracketNested92;
var bracketObj93 = { k0: 96, k1: 100, nested: { hit: 104 } };
bracketOrder = 0;
var bracketRead93 = bracketBase(1, bracketObj93)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 93");
bracketCheck(bracketRead93 === 96, "bracket read value 93");
bracketOrder = 0;
bracketBase(3, bracketObj93)[bracketKey(4, "k1")] = bracketValue(5, 143);
bracketCheck(bracketOrder === 345, "bracket write order 93");
bracketCheck(bracketObj93.k1 === 143, "bracket write value 93");
bracketOrder = 0;
var bracketNested93 = bracketBase(6, bracketObj93)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 93");
bracketCheck(bracketNested93 === 104, "bracket nested value 93");
bracketTotal = bracketTotal + bracketRead93 + bracketObj93.k1 + bracketNested93;
var bracketObj94 = { k0: 97, k1: 101, nested: { hit: 105 } };
bracketOrder = 0;
var bracketRead94 = bracketBase(1, bracketObj94)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 94");
bracketCheck(bracketRead94 === 97, "bracket read value 94");
bracketOrder = 0;
bracketBase(3, bracketObj94)[bracketKey(4, "k1")] = bracketValue(5, 144);
bracketCheck(bracketOrder === 345, "bracket write order 94");
bracketCheck(bracketObj94.k1 === 144, "bracket write value 94");
bracketOrder = 0;
var bracketNested94 = bracketBase(6, bracketObj94)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 94");
bracketCheck(bracketNested94 === 105, "bracket nested value 94");
bracketTotal = bracketTotal + bracketRead94 + bracketObj94.k1 + bracketNested94;
var bracketObj95 = { k0: 98, k1: 102, nested: { hit: 106 } };
bracketOrder = 0;
var bracketRead95 = bracketBase(1, bracketObj95)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 95");
bracketCheck(bracketRead95 === 98, "bracket read value 95");
bracketOrder = 0;
bracketBase(3, bracketObj95)[bracketKey(4, "k1")] = bracketValue(5, 145);
bracketCheck(bracketOrder === 345, "bracket write order 95");
bracketCheck(bracketObj95.k1 === 145, "bracket write value 95");
bracketOrder = 0;
var bracketNested95 = bracketBase(6, bracketObj95)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 95");
bracketCheck(bracketNested95 === 106, "bracket nested value 95");
bracketTotal = bracketTotal + bracketRead95 + bracketObj95.k1 + bracketNested95;
var bracketObj96 = { k0: 99, k1: 103, nested: { hit: 107 } };
bracketOrder = 0;
var bracketRead96 = bracketBase(1, bracketObj96)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 96");
bracketCheck(bracketRead96 === 99, "bracket read value 96");
bracketOrder = 0;
bracketBase(3, bracketObj96)[bracketKey(4, "k1")] = bracketValue(5, 146);
bracketCheck(bracketOrder === 345, "bracket write order 96");
bracketCheck(bracketObj96.k1 === 146, "bracket write value 96");
bracketOrder = 0;
var bracketNested96 = bracketBase(6, bracketObj96)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 96");
bracketCheck(bracketNested96 === 107, "bracket nested value 96");
bracketTotal = bracketTotal + bracketRead96 + bracketObj96.k1 + bracketNested96;
var bracketObj97 = { k0: 100, k1: 104, nested: { hit: 108 } };
bracketOrder = 0;
var bracketRead97 = bracketBase(1, bracketObj97)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 97");
bracketCheck(bracketRead97 === 100, "bracket read value 97");
bracketOrder = 0;
bracketBase(3, bracketObj97)[bracketKey(4, "k1")] = bracketValue(5, 147);
bracketCheck(bracketOrder === 345, "bracket write order 97");
bracketCheck(bracketObj97.k1 === 147, "bracket write value 97");
bracketOrder = 0;
var bracketNested97 = bracketBase(6, bracketObj97)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 97");
bracketCheck(bracketNested97 === 108, "bracket nested value 97");
bracketTotal = bracketTotal + bracketRead97 + bracketObj97.k1 + bracketNested97;
var bracketObj98 = { k0: 101, k1: 105, nested: { hit: 109 } };
bracketOrder = 0;
var bracketRead98 = bracketBase(1, bracketObj98)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 98");
bracketCheck(bracketRead98 === 101, "bracket read value 98");
bracketOrder = 0;
bracketBase(3, bracketObj98)[bracketKey(4, "k1")] = bracketValue(5, 148);
bracketCheck(bracketOrder === 345, "bracket write order 98");
bracketCheck(bracketObj98.k1 === 148, "bracket write value 98");
bracketOrder = 0;
var bracketNested98 = bracketBase(6, bracketObj98)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 98");
bracketCheck(bracketNested98 === 109, "bracket nested value 98");
bracketTotal = bracketTotal + bracketRead98 + bracketObj98.k1 + bracketNested98;
var bracketObj99 = { k0: 102, k1: 106, nested: { hit: 110 } };
bracketOrder = 0;
var bracketRead99 = bracketBase(1, bracketObj99)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 99");
bracketCheck(bracketRead99 === 102, "bracket read value 99");
bracketOrder = 0;
bracketBase(3, bracketObj99)[bracketKey(4, "k1")] = bracketValue(5, 149);
bracketCheck(bracketOrder === 345, "bracket write order 99");
bracketCheck(bracketObj99.k1 === 149, "bracket write value 99");
bracketOrder = 0;
var bracketNested99 = bracketBase(6, bracketObj99)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 99");
bracketCheck(bracketNested99 === 110, "bracket nested value 99");
bracketTotal = bracketTotal + bracketRead99 + bracketObj99.k1 + bracketNested99;
var bracketObj100 = { k0: 103, k1: 107, nested: { hit: 111 } };
bracketOrder = 0;
var bracketRead100 = bracketBase(1, bracketObj100)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 100");
bracketCheck(bracketRead100 === 103, "bracket read value 100");
bracketOrder = 0;
bracketBase(3, bracketObj100)[bracketKey(4, "k1")] = bracketValue(5, 150);
bracketCheck(bracketOrder === 345, "bracket write order 100");
bracketCheck(bracketObj100.k1 === 150, "bracket write value 100");
bracketOrder = 0;
var bracketNested100 = bracketBase(6, bracketObj100)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 100");
bracketCheck(bracketNested100 === 111, "bracket nested value 100");
bracketTotal = bracketTotal + bracketRead100 + bracketObj100.k1 + bracketNested100;
var bracketObj101 = { k0: 104, k1: 108, nested: { hit: 112 } };
bracketOrder = 0;
var bracketRead101 = bracketBase(1, bracketObj101)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 101");
bracketCheck(bracketRead101 === 104, "bracket read value 101");
bracketOrder = 0;
bracketBase(3, bracketObj101)[bracketKey(4, "k1")] = bracketValue(5, 151);
bracketCheck(bracketOrder === 345, "bracket write order 101");
bracketCheck(bracketObj101.k1 === 151, "bracket write value 101");
bracketOrder = 0;
var bracketNested101 = bracketBase(6, bracketObj101)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 101");
bracketCheck(bracketNested101 === 112, "bracket nested value 101");
bracketTotal = bracketTotal + bracketRead101 + bracketObj101.k1 + bracketNested101;
var bracketObj102 = { k0: 105, k1: 109, nested: { hit: 113 } };
bracketOrder = 0;
var bracketRead102 = bracketBase(1, bracketObj102)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 102");
bracketCheck(bracketRead102 === 105, "bracket read value 102");
bracketOrder = 0;
bracketBase(3, bracketObj102)[bracketKey(4, "k1")] = bracketValue(5, 152);
bracketCheck(bracketOrder === 345, "bracket write order 102");
bracketCheck(bracketObj102.k1 === 152, "bracket write value 102");
bracketOrder = 0;
var bracketNested102 = bracketBase(6, bracketObj102)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 102");
bracketCheck(bracketNested102 === 113, "bracket nested value 102");
bracketTotal = bracketTotal + bracketRead102 + bracketObj102.k1 + bracketNested102;
var bracketObj103 = { k0: 106, k1: 110, nested: { hit: 114 } };
bracketOrder = 0;
var bracketRead103 = bracketBase(1, bracketObj103)[bracketKey(2, "k0")];
bracketCheck(bracketOrder === 12, "bracket read order 103");
bracketCheck(bracketRead103 === 106, "bracket read value 103");
bracketOrder = 0;
bracketBase(3, bracketObj103)[bracketKey(4, "k1")] = bracketValue(5, 153);
bracketCheck(bracketOrder === 345, "bracket write order 103");
bracketCheck(bracketObj103.k1 === 153, "bracket write value 103");
bracketOrder = 0;
var bracketNested103 = bracketBase(6, bracketObj103)[bracketKey(7, "nested")][bracketKey(8, "hit")];
bracketCheck(bracketOrder === 678, "bracket nested order 103");
bracketCheck(bracketNested103 === 114, "bracket nested value 103");
bracketTotal = bracketTotal + bracketRead103 + bracketObj103.k1 + bracketNested103;
bracketCheck(bracketScore === 624, "bracket score");
bracketCheck(bracketTotal > 0, "bracket accumulated result");
