// behavior: expression-key-topropertykey-for-read
// expected: pass
// goal: script
// size: standard
// variant: script.sloppy

var readKeyScore = 0;
function readKeyCheck(condition, label) {
if (!condition) {
throw label;
}
readKeyScore = readKeyScore + 1;
return true;
}
var readKeyLog = [];
function readKeyMark(value) { readKeyLog[readKeyLog.length] = value; return value; }
var readKeyTotal = 0;
var readTarget0 = { p0: 30, q0: 40, 1: 50 };
var readStart0 = readKeyLog.length;
var readKeyObj0 = { name: "p0", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot0 = readTarget0[readKeyObj0];
readKeyCheck(readGot0 === 30, "toString property key read 0");
readKeyCheck(readKeyLog[readStart0] === 1 && readKeyLog[readStart0 + 1] === 2, "toString order 0");
var readValueKey0 = { name: "q0", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue0 = readTarget0[readValueKey0];
readKeyCheck(readGotValue0 === 40, "valueOf fallback key read 0");
var readNumeric0 = readTarget0[1];
readKeyCheck(readNumeric0 === 50, "numeric key read 0");
readKeyTotal = readKeyTotal + readGot0 + readGotValue0 + readNumeric0;
var readTarget1 = { p1: 31, q1: 41, 1: 51 };
var readStart1 = readKeyLog.length;
var readKeyObj1 = { name: "p1", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot1 = readTarget1[readKeyObj1];
readKeyCheck(readGot1 === 31, "toString property key read 1");
readKeyCheck(readKeyLog[readStart1] === 1 && readKeyLog[readStart1 + 1] === 2, "toString order 1");
var readValueKey1 = { name: "q1", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue1 = readTarget1[readValueKey1];
readKeyCheck(readGotValue1 === 41, "valueOf fallback key read 1");
var readNumeric1 = readTarget1[1];
readKeyCheck(readNumeric1 === 51, "numeric key read 1");
readKeyTotal = readKeyTotal + readGot1 + readGotValue1 + readNumeric1;
var readTarget2 = { p2: 32, q2: 42, 1: 52 };
var readStart2 = readKeyLog.length;
var readKeyObj2 = { name: "p2", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot2 = readTarget2[readKeyObj2];
readKeyCheck(readGot2 === 32, "toString property key read 2");
readKeyCheck(readKeyLog[readStart2] === 1 && readKeyLog[readStart2 + 1] === 2, "toString order 2");
var readValueKey2 = { name: "q2", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue2 = readTarget2[readValueKey2];
readKeyCheck(readGotValue2 === 42, "valueOf fallback key read 2");
var readNumeric2 = readTarget2[1];
readKeyCheck(readNumeric2 === 52, "numeric key read 2");
readKeyTotal = readKeyTotal + readGot2 + readGotValue2 + readNumeric2;
var readTarget3 = { p3: 33, q3: 43, 1: 53 };
var readStart3 = readKeyLog.length;
var readKeyObj3 = { name: "p3", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot3 = readTarget3[readKeyObj3];
readKeyCheck(readGot3 === 33, "toString property key read 3");
readKeyCheck(readKeyLog[readStart3] === 1 && readKeyLog[readStart3 + 1] === 2, "toString order 3");
var readValueKey3 = { name: "q3", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue3 = readTarget3[readValueKey3];
readKeyCheck(readGotValue3 === 43, "valueOf fallback key read 3");
var readNumeric3 = readTarget3[1];
readKeyCheck(readNumeric3 === 53, "numeric key read 3");
readKeyTotal = readKeyTotal + readGot3 + readGotValue3 + readNumeric3;
var readTarget4 = { p4: 34, q4: 44, 1: 54 };
var readStart4 = readKeyLog.length;
var readKeyObj4 = { name: "p4", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot4 = readTarget4[readKeyObj4];
readKeyCheck(readGot4 === 34, "toString property key read 4");
readKeyCheck(readKeyLog[readStart4] === 1 && readKeyLog[readStart4 + 1] === 2, "toString order 4");
var readValueKey4 = { name: "q4", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue4 = readTarget4[readValueKey4];
readKeyCheck(readGotValue4 === 44, "valueOf fallback key read 4");
var readNumeric4 = readTarget4[1];
readKeyCheck(readNumeric4 === 54, "numeric key read 4");
readKeyTotal = readKeyTotal + readGot4 + readGotValue4 + readNumeric4;
var readTarget5 = { p5: 35, q5: 45, 1: 55 };
var readStart5 = readKeyLog.length;
var readKeyObj5 = { name: "p5", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot5 = readTarget5[readKeyObj5];
readKeyCheck(readGot5 === 35, "toString property key read 5");
readKeyCheck(readKeyLog[readStart5] === 1 && readKeyLog[readStart5 + 1] === 2, "toString order 5");
var readValueKey5 = { name: "q5", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue5 = readTarget5[readValueKey5];
readKeyCheck(readGotValue5 === 45, "valueOf fallback key read 5");
var readNumeric5 = readTarget5[1];
readKeyCheck(readNumeric5 === 55, "numeric key read 5");
readKeyTotal = readKeyTotal + readGot5 + readGotValue5 + readNumeric5;
var readTarget6 = { p6: 36, q6: 46, 1: 56 };
var readStart6 = readKeyLog.length;
var readKeyObj6 = { name: "p6", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot6 = readTarget6[readKeyObj6];
readKeyCheck(readGot6 === 36, "toString property key read 6");
readKeyCheck(readKeyLog[readStart6] === 1 && readKeyLog[readStart6 + 1] === 2, "toString order 6");
var readValueKey6 = { name: "q6", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue6 = readTarget6[readValueKey6];
readKeyCheck(readGotValue6 === 46, "valueOf fallback key read 6");
var readNumeric6 = readTarget6[1];
readKeyCheck(readNumeric6 === 56, "numeric key read 6");
readKeyTotal = readKeyTotal + readGot6 + readGotValue6 + readNumeric6;
var readTarget7 = { p7: 37, q7: 47, 1: 57 };
var readStart7 = readKeyLog.length;
var readKeyObj7 = { name: "p7", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot7 = readTarget7[readKeyObj7];
readKeyCheck(readGot7 === 37, "toString property key read 7");
readKeyCheck(readKeyLog[readStart7] === 1 && readKeyLog[readStart7 + 1] === 2, "toString order 7");
var readValueKey7 = { name: "q7", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue7 = readTarget7[readValueKey7];
readKeyCheck(readGotValue7 === 47, "valueOf fallback key read 7");
var readNumeric7 = readTarget7[1];
readKeyCheck(readNumeric7 === 57, "numeric key read 7");
readKeyTotal = readKeyTotal + readGot7 + readGotValue7 + readNumeric7;
var readTarget8 = { p8: 38, q8: 48, 1: 58 };
var readStart8 = readKeyLog.length;
var readKeyObj8 = { name: "p8", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot8 = readTarget8[readKeyObj8];
readKeyCheck(readGot8 === 38, "toString property key read 8");
readKeyCheck(readKeyLog[readStart8] === 1 && readKeyLog[readStart8 + 1] === 2, "toString order 8");
var readValueKey8 = { name: "q8", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue8 = readTarget8[readValueKey8];
readKeyCheck(readGotValue8 === 48, "valueOf fallback key read 8");
var readNumeric8 = readTarget8[1];
readKeyCheck(readNumeric8 === 58, "numeric key read 8");
readKeyTotal = readKeyTotal + readGot8 + readGotValue8 + readNumeric8;
var readTarget9 = { p9: 39, q9: 49, 1: 59 };
var readStart9 = readKeyLog.length;
var readKeyObj9 = { name: "p9", toString: function() { readKeyMark(2); return this.name; } };
readKeyMark(1);
var readGot9 = readTarget9[readKeyObj9];
readKeyCheck(readGot9 === 39, "toString property key read 9");
readKeyCheck(readKeyLog[readStart9] === 1 && readKeyLog[readStart9 + 1] === 2, "toString order 9");
var readValueKey9 = { name: "q9", toString: 7, valueOf: function() { readKeyMark(3); return this.name; } };
var readGotValue9 = readTarget9[readValueKey9];
readKeyCheck(readGotValue9 === 49, "valueOf fallback key read 9");
var readNumeric9 = readTarget9[1];
readKeyCheck(readNumeric9 === 59, "numeric key read 9");
readKeyTotal = readKeyTotal + readGot9 + readGotValue9 + readNumeric9;
readKeyCheck(readKeyScore === 40, "read key score");
readKeyCheck(readKeyTotal > 0, "read key accumulated result");
