// behavior: property-name-list-ignores-computed-names
// expected: pass
// goal: script
// size: large
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}

var protoList0 = { inheritedList: 20 };
var firstComputedProto0 = { data: 20 + 1 };
var secondComputedProto0 = { data: 20 + 2 };
var listObj0 = { ["__proto__"]: firstComputedProto0, __proto__: protoList0, ["__proto__"]: secondComputedProto0, value0: 20 + 3 };
check(Object.getPrototypeOf(listObj0) === protoList0, "property name list literal proto 0");
check(listObj0.__proto__ === secondComputedProto0, "property name list computed last wins 0");
check(listObj0.inheritedList === 20, "property name list inherited 0");
check(listObj0.value0 === 20 + 3, "property name list value 0");
var keyName0 = "__proto__";
var computedOnlyObj0 = { [keyName0]: firstComputedProto0, [keyName0]: secondComputedProto0 };
check(Object.getPrototypeOf(computedOnlyObj0) === Object.prototype, "computed only proto base 0");
check(computedOnlyObj0.__proto__ === secondComputedProto0, "computed only proto own 0");

var protoList1 = { inheritedList: 27 };
var firstComputedProto1 = { data: 27 + 1 };
var secondComputedProto1 = { data: 27 + 2 };
var listObj1 = { ["__proto__"]: firstComputedProto1, __proto__: protoList1, ["__proto__"]: secondComputedProto1, value1: 27 + 3 };
check(Object.getPrototypeOf(listObj1) === protoList1, "property name list literal proto 1");
check(listObj1.__proto__ === secondComputedProto1, "property name list computed last wins 1");
check(listObj1.inheritedList === 27, "property name list inherited 1");
check(listObj1.value1 === 27 + 3, "property name list value 1");
var keyName1 = "__proto__";
var computedOnlyObj1 = { [keyName1]: firstComputedProto1, [keyName1]: secondComputedProto1 };
check(Object.getPrototypeOf(computedOnlyObj1) === Object.prototype, "computed only proto base 1");
check(computedOnlyObj1.__proto__ === secondComputedProto1, "computed only proto own 1");

var protoList2 = { inheritedList: 34 };
var firstComputedProto2 = { data: 34 + 1 };
var secondComputedProto2 = { data: 34 + 2 };
var listObj2 = { ["__proto__"]: firstComputedProto2, __proto__: protoList2, ["__proto__"]: secondComputedProto2, value2: 34 + 3 };
check(Object.getPrototypeOf(listObj2) === protoList2, "property name list literal proto 2");
check(listObj2.__proto__ === secondComputedProto2, "property name list computed last wins 2");
check(listObj2.inheritedList === 34, "property name list inherited 2");
check(listObj2.value2 === 34 + 3, "property name list value 2");
var keyName2 = "__proto__";
var computedOnlyObj2 = { [keyName2]: firstComputedProto2, [keyName2]: secondComputedProto2 };
check(Object.getPrototypeOf(computedOnlyObj2) === Object.prototype, "computed only proto base 2");
check(computedOnlyObj2.__proto__ === secondComputedProto2, "computed only proto own 2");

var protoList3 = { inheritedList: 41 };
var firstComputedProto3 = { data: 41 + 1 };
var secondComputedProto3 = { data: 41 + 2 };
var listObj3 = { ["__proto__"]: firstComputedProto3, __proto__: protoList3, ["__proto__"]: secondComputedProto3, value3: 41 + 3 };
check(Object.getPrototypeOf(listObj3) === protoList3, "property name list literal proto 3");
check(listObj3.__proto__ === secondComputedProto3, "property name list computed last wins 3");
check(listObj3.inheritedList === 41, "property name list inherited 3");
check(listObj3.value3 === 41 + 3, "property name list value 3");
var keyName3 = "__proto__";
var computedOnlyObj3 = { [keyName3]: firstComputedProto3, [keyName3]: secondComputedProto3 };
check(Object.getPrototypeOf(computedOnlyObj3) === Object.prototype, "computed only proto base 3");
check(computedOnlyObj3.__proto__ === secondComputedProto3, "computed only proto own 3");

var protoList4 = { inheritedList: 48 };
var firstComputedProto4 = { data: 48 + 1 };
var secondComputedProto4 = { data: 48 + 2 };
var listObj4 = { ["__proto__"]: firstComputedProto4, __proto__: protoList4, ["__proto__"]: secondComputedProto4, value4: 48 + 3 };
check(Object.getPrototypeOf(listObj4) === protoList4, "property name list literal proto 4");
check(listObj4.__proto__ === secondComputedProto4, "property name list computed last wins 4");
check(listObj4.inheritedList === 48, "property name list inherited 4");
check(listObj4.value4 === 48 + 3, "property name list value 4");
var keyName4 = "__proto__";
var computedOnlyObj4 = { [keyName4]: firstComputedProto4, [keyName4]: secondComputedProto4 };
check(Object.getPrototypeOf(computedOnlyObj4) === Object.prototype, "computed only proto base 4");
check(computedOnlyObj4.__proto__ === secondComputedProto4, "computed only proto own 4");

var protoList5 = { inheritedList: 55 };
var firstComputedProto5 = { data: 55 + 1 };
var secondComputedProto5 = { data: 55 + 2 };
var listObj5 = { ["__proto__"]: firstComputedProto5, __proto__: protoList5, ["__proto__"]: secondComputedProto5, value5: 55 + 3 };
check(Object.getPrototypeOf(listObj5) === protoList5, "property name list literal proto 5");
check(listObj5.__proto__ === secondComputedProto5, "property name list computed last wins 5");
check(listObj5.inheritedList === 55, "property name list inherited 5");
check(listObj5.value5 === 55 + 3, "property name list value 5");
var keyName5 = "__proto__";
var computedOnlyObj5 = { [keyName5]: firstComputedProto5, [keyName5]: secondComputedProto5 };
check(Object.getPrototypeOf(computedOnlyObj5) === Object.prototype, "computed only proto base 5");
check(computedOnlyObj5.__proto__ === secondComputedProto5, "computed only proto own 5");

var protoList6 = { inheritedList: 62 };
var firstComputedProto6 = { data: 62 + 1 };
var secondComputedProto6 = { data: 62 + 2 };
var listObj6 = { ["__proto__"]: firstComputedProto6, __proto__: protoList6, ["__proto__"]: secondComputedProto6, value6: 62 + 3 };
check(Object.getPrototypeOf(listObj6) === protoList6, "property name list literal proto 6");
check(listObj6.__proto__ === secondComputedProto6, "property name list computed last wins 6");
check(listObj6.inheritedList === 62, "property name list inherited 6");
check(listObj6.value6 === 62 + 3, "property name list value 6");
var keyName6 = "__proto__";
var computedOnlyObj6 = { [keyName6]: firstComputedProto6, [keyName6]: secondComputedProto6 };
check(Object.getPrototypeOf(computedOnlyObj6) === Object.prototype, "computed only proto base 6");
check(computedOnlyObj6.__proto__ === secondComputedProto6, "computed only proto own 6");

var protoList7 = { inheritedList: 69 };
var firstComputedProto7 = { data: 69 + 1 };
var secondComputedProto7 = { data: 69 + 2 };
var listObj7 = { ["__proto__"]: firstComputedProto7, __proto__: protoList7, ["__proto__"]: secondComputedProto7, value7: 69 + 3 };
check(Object.getPrototypeOf(listObj7) === protoList7, "property name list literal proto 7");
check(listObj7.__proto__ === secondComputedProto7, "property name list computed last wins 7");
check(listObj7.inheritedList === 69, "property name list inherited 7");
check(listObj7.value7 === 69 + 3, "property name list value 7");
var keyName7 = "__proto__";
var computedOnlyObj7 = { [keyName7]: firstComputedProto7, [keyName7]: secondComputedProto7 };
check(Object.getPrototypeOf(computedOnlyObj7) === Object.prototype, "computed only proto base 7");
check(computedOnlyObj7.__proto__ === secondComputedProto7, "computed only proto own 7");

var protoList8 = { inheritedList: 76 };
var firstComputedProto8 = { data: 76 + 1 };
var secondComputedProto8 = { data: 76 + 2 };
var listObj8 = { ["__proto__"]: firstComputedProto8, __proto__: protoList8, ["__proto__"]: secondComputedProto8, value8: 76 + 3 };
check(Object.getPrototypeOf(listObj8) === protoList8, "property name list literal proto 8");
check(listObj8.__proto__ === secondComputedProto8, "property name list computed last wins 8");
check(listObj8.inheritedList === 76, "property name list inherited 8");
check(listObj8.value8 === 76 + 3, "property name list value 8");
var keyName8 = "__proto__";
var computedOnlyObj8 = { [keyName8]: firstComputedProto8, [keyName8]: secondComputedProto8 };
check(Object.getPrototypeOf(computedOnlyObj8) === Object.prototype, "computed only proto base 8");
check(computedOnlyObj8.__proto__ === secondComputedProto8, "computed only proto own 8");

var protoList9 = { inheritedList: 83 };
var firstComputedProto9 = { data: 83 + 1 };
var secondComputedProto9 = { data: 83 + 2 };
var listObj9 = { ["__proto__"]: firstComputedProto9, __proto__: protoList9, ["__proto__"]: secondComputedProto9, value9: 83 + 3 };
check(Object.getPrototypeOf(listObj9) === protoList9, "property name list literal proto 9");
check(listObj9.__proto__ === secondComputedProto9, "property name list computed last wins 9");
check(listObj9.inheritedList === 83, "property name list inherited 9");
check(listObj9.value9 === 83 + 3, "property name list value 9");
var keyName9 = "__proto__";
var computedOnlyObj9 = { [keyName9]: firstComputedProto9, [keyName9]: secondComputedProto9 };
check(Object.getPrototypeOf(computedOnlyObj9) === Object.prototype, "computed only proto base 9");
check(computedOnlyObj9.__proto__ === secondComputedProto9, "computed only proto own 9");

var protoList10 = { inheritedList: 90 };
var firstComputedProto10 = { data: 90 + 1 };
var secondComputedProto10 = { data: 90 + 2 };
var listObj10 = { ["__proto__"]: firstComputedProto10, __proto__: protoList10, ["__proto__"]: secondComputedProto10, value10: 90 + 3 };
check(Object.getPrototypeOf(listObj10) === protoList10, "property name list literal proto 10");
check(listObj10.__proto__ === secondComputedProto10, "property name list computed last wins 10");
check(listObj10.inheritedList === 90, "property name list inherited 10");
check(listObj10.value10 === 90 + 3, "property name list value 10");
var keyName10 = "__proto__";
var computedOnlyObj10 = { [keyName10]: firstComputedProto10, [keyName10]: secondComputedProto10 };
check(Object.getPrototypeOf(computedOnlyObj10) === Object.prototype, "computed only proto base 10");
check(computedOnlyObj10.__proto__ === secondComputedProto10, "computed only proto own 10");

var protoList11 = { inheritedList: 97 };
var firstComputedProto11 = { data: 97 + 1 };
var secondComputedProto11 = { data: 97 + 2 };
var listObj11 = { ["__proto__"]: firstComputedProto11, __proto__: protoList11, ["__proto__"]: secondComputedProto11, value11: 97 + 3 };
check(Object.getPrototypeOf(listObj11) === protoList11, "property name list literal proto 11");
check(listObj11.__proto__ === secondComputedProto11, "property name list computed last wins 11");
check(listObj11.inheritedList === 97, "property name list inherited 11");
check(listObj11.value11 === 97 + 3, "property name list value 11");
var keyName11 = "__proto__";
var computedOnlyObj11 = { [keyName11]: firstComputedProto11, [keyName11]: secondComputedProto11 };
check(Object.getPrototypeOf(computedOnlyObj11) === Object.prototype, "computed only proto base 11");
check(computedOnlyObj11.__proto__ === secondComputedProto11, "computed only proto own 11");

var protoList12 = { inheritedList: 104 };
var firstComputedProto12 = { data: 104 + 1 };
var secondComputedProto12 = { data: 104 + 2 };
var listObj12 = { ["__proto__"]: firstComputedProto12, __proto__: protoList12, ["__proto__"]: secondComputedProto12, value12: 104 + 3 };
check(Object.getPrototypeOf(listObj12) === protoList12, "property name list literal proto 12");
check(listObj12.__proto__ === secondComputedProto12, "property name list computed last wins 12");
check(listObj12.inheritedList === 104, "property name list inherited 12");
check(listObj12.value12 === 104 + 3, "property name list value 12");
var keyName12 = "__proto__";
var computedOnlyObj12 = { [keyName12]: firstComputedProto12, [keyName12]: secondComputedProto12 };
check(Object.getPrototypeOf(computedOnlyObj12) === Object.prototype, "computed only proto base 12");
check(computedOnlyObj12.__proto__ === secondComputedProto12, "computed only proto own 12");

var protoList13 = { inheritedList: 111 };
var firstComputedProto13 = { data: 111 + 1 };
var secondComputedProto13 = { data: 111 + 2 };
var listObj13 = { ["__proto__"]: firstComputedProto13, __proto__: protoList13, ["__proto__"]: secondComputedProto13, value13: 111 + 3 };
check(Object.getPrototypeOf(listObj13) === protoList13, "property name list literal proto 13");
check(listObj13.__proto__ === secondComputedProto13, "property name list computed last wins 13");
check(listObj13.inheritedList === 111, "property name list inherited 13");
check(listObj13.value13 === 111 + 3, "property name list value 13");
var keyName13 = "__proto__";
var computedOnlyObj13 = { [keyName13]: firstComputedProto13, [keyName13]: secondComputedProto13 };
check(Object.getPrototypeOf(computedOnlyObj13) === Object.prototype, "computed only proto base 13");
check(computedOnlyObj13.__proto__ === secondComputedProto13, "computed only proto own 13");

var protoList14 = { inheritedList: 118 };
var firstComputedProto14 = { data: 118 + 1 };
var secondComputedProto14 = { data: 118 + 2 };
var listObj14 = { ["__proto__"]: firstComputedProto14, __proto__: protoList14, ["__proto__"]: secondComputedProto14, value14: 118 + 3 };
check(Object.getPrototypeOf(listObj14) === protoList14, "property name list literal proto 14");
check(listObj14.__proto__ === secondComputedProto14, "property name list computed last wins 14");
check(listObj14.inheritedList === 118, "property name list inherited 14");
check(listObj14.value14 === 118 + 3, "property name list value 14");
var keyName14 = "__proto__";
var computedOnlyObj14 = { [keyName14]: firstComputedProto14, [keyName14]: secondComputedProto14 };
check(Object.getPrototypeOf(computedOnlyObj14) === Object.prototype, "computed only proto base 14");
check(computedOnlyObj14.__proto__ === secondComputedProto14, "computed only proto own 14");

var protoList15 = { inheritedList: 125 };
var firstComputedProto15 = { data: 125 + 1 };
var secondComputedProto15 = { data: 125 + 2 };
var listObj15 = { ["__proto__"]: firstComputedProto15, __proto__: protoList15, ["__proto__"]: secondComputedProto15, value15: 125 + 3 };
check(Object.getPrototypeOf(listObj15) === protoList15, "property name list literal proto 15");
check(listObj15.__proto__ === secondComputedProto15, "property name list computed last wins 15");
check(listObj15.inheritedList === 125, "property name list inherited 15");
check(listObj15.value15 === 125 + 3, "property name list value 15");
var keyName15 = "__proto__";
var computedOnlyObj15 = { [keyName15]: firstComputedProto15, [keyName15]: secondComputedProto15 };
check(Object.getPrototypeOf(computedOnlyObj15) === Object.prototype, "computed only proto base 15");
check(computedOnlyObj15.__proto__ === secondComputedProto15, "computed only proto own 15");

var protoList16 = { inheritedList: 132 };
var firstComputedProto16 = { data: 132 + 1 };
var secondComputedProto16 = { data: 132 + 2 };
var listObj16 = { ["__proto__"]: firstComputedProto16, __proto__: protoList16, ["__proto__"]: secondComputedProto16, value16: 132 + 3 };
check(Object.getPrototypeOf(listObj16) === protoList16, "property name list literal proto 16");
check(listObj16.__proto__ === secondComputedProto16, "property name list computed last wins 16");
check(listObj16.inheritedList === 132, "property name list inherited 16");
check(listObj16.value16 === 132 + 3, "property name list value 16");
var keyName16 = "__proto__";
var computedOnlyObj16 = { [keyName16]: firstComputedProto16, [keyName16]: secondComputedProto16 };
check(Object.getPrototypeOf(computedOnlyObj16) === Object.prototype, "computed only proto base 16");
check(computedOnlyObj16.__proto__ === secondComputedProto16, "computed only proto own 16");

var protoList17 = { inheritedList: 139 };
var firstComputedProto17 = { data: 139 + 1 };
var secondComputedProto17 = { data: 139 + 2 };
var listObj17 = { ["__proto__"]: firstComputedProto17, __proto__: protoList17, ["__proto__"]: secondComputedProto17, value17: 139 + 3 };
check(Object.getPrototypeOf(listObj17) === protoList17, "property name list literal proto 17");
check(listObj17.__proto__ === secondComputedProto17, "property name list computed last wins 17");
check(listObj17.inheritedList === 139, "property name list inherited 17");
check(listObj17.value17 === 139 + 3, "property name list value 17");
var keyName17 = "__proto__";
var computedOnlyObj17 = { [keyName17]: firstComputedProto17, [keyName17]: secondComputedProto17 };
check(Object.getPrototypeOf(computedOnlyObj17) === Object.prototype, "computed only proto base 17");
check(computedOnlyObj17.__proto__ === secondComputedProto17, "computed only proto own 17");

var protoList18 = { inheritedList: 146 };
var firstComputedProto18 = { data: 146 + 1 };
var secondComputedProto18 = { data: 146 + 2 };
var listObj18 = { ["__proto__"]: firstComputedProto18, __proto__: protoList18, ["__proto__"]: secondComputedProto18, value18: 146 + 3 };
check(Object.getPrototypeOf(listObj18) === protoList18, "property name list literal proto 18");
check(listObj18.__proto__ === secondComputedProto18, "property name list computed last wins 18");
check(listObj18.inheritedList === 146, "property name list inherited 18");
check(listObj18.value18 === 146 + 3, "property name list value 18");
var keyName18 = "__proto__";
var computedOnlyObj18 = { [keyName18]: firstComputedProto18, [keyName18]: secondComputedProto18 };
check(Object.getPrototypeOf(computedOnlyObj18) === Object.prototype, "computed only proto base 18");
check(computedOnlyObj18.__proto__ === secondComputedProto18, "computed only proto own 18");

var protoList19 = { inheritedList: 153 };
var firstComputedProto19 = { data: 153 + 1 };
var secondComputedProto19 = { data: 153 + 2 };
var listObj19 = { ["__proto__"]: firstComputedProto19, __proto__: protoList19, ["__proto__"]: secondComputedProto19, value19: 153 + 3 };
check(Object.getPrototypeOf(listObj19) === protoList19, "property name list literal proto 19");
check(listObj19.__proto__ === secondComputedProto19, "property name list computed last wins 19");
check(listObj19.inheritedList === 153, "property name list inherited 19");
check(listObj19.value19 === 153 + 3, "property name list value 19");
var keyName19 = "__proto__";
var computedOnlyObj19 = { [keyName19]: firstComputedProto19, [keyName19]: secondComputedProto19 };
check(Object.getPrototypeOf(computedOnlyObj19) === Object.prototype, "computed only proto base 19");
check(computedOnlyObj19.__proto__ === secondComputedProto19, "computed only proto own 19");

var protoList20 = { inheritedList: 160 };
var firstComputedProto20 = { data: 160 + 1 };
var secondComputedProto20 = { data: 160 + 2 };
var listObj20 = { ["__proto__"]: firstComputedProto20, __proto__: protoList20, ["__proto__"]: secondComputedProto20, value20: 160 + 3 };
check(Object.getPrototypeOf(listObj20) === protoList20, "property name list literal proto 20");
check(listObj20.__proto__ === secondComputedProto20, "property name list computed last wins 20");
check(listObj20.inheritedList === 160, "property name list inherited 20");
check(listObj20.value20 === 160 + 3, "property name list value 20");
var keyName20 = "__proto__";
var computedOnlyObj20 = { [keyName20]: firstComputedProto20, [keyName20]: secondComputedProto20 };
check(Object.getPrototypeOf(computedOnlyObj20) === Object.prototype, "computed only proto base 20");
check(computedOnlyObj20.__proto__ === secondComputedProto20, "computed only proto own 20");

var protoList21 = { inheritedList: 167 };
var firstComputedProto21 = { data: 167 + 1 };
var secondComputedProto21 = { data: 167 + 2 };
var listObj21 = { ["__proto__"]: firstComputedProto21, __proto__: protoList21, ["__proto__"]: secondComputedProto21, value21: 167 + 3 };
check(Object.getPrototypeOf(listObj21) === protoList21, "property name list literal proto 21");
check(listObj21.__proto__ === secondComputedProto21, "property name list computed last wins 21");
check(listObj21.inheritedList === 167, "property name list inherited 21");
check(listObj21.value21 === 167 + 3, "property name list value 21");
var keyName21 = "__proto__";
var computedOnlyObj21 = { [keyName21]: firstComputedProto21, [keyName21]: secondComputedProto21 };
check(Object.getPrototypeOf(computedOnlyObj21) === Object.prototype, "computed only proto base 21");
check(computedOnlyObj21.__proto__ === secondComputedProto21, "computed only proto own 21");

var protoList22 = { inheritedList: 174 };
var firstComputedProto22 = { data: 174 + 1 };
var secondComputedProto22 = { data: 174 + 2 };
var listObj22 = { ["__proto__"]: firstComputedProto22, __proto__: protoList22, ["__proto__"]: secondComputedProto22, value22: 174 + 3 };
check(Object.getPrototypeOf(listObj22) === protoList22, "property name list literal proto 22");
check(listObj22.__proto__ === secondComputedProto22, "property name list computed last wins 22");
check(listObj22.inheritedList === 174, "property name list inherited 22");
check(listObj22.value22 === 174 + 3, "property name list value 22");
var keyName22 = "__proto__";
var computedOnlyObj22 = { [keyName22]: firstComputedProto22, [keyName22]: secondComputedProto22 };
check(Object.getPrototypeOf(computedOnlyObj22) === Object.prototype, "computed only proto base 22");
check(computedOnlyObj22.__proto__ === secondComputedProto22, "computed only proto own 22");

var protoList23 = { inheritedList: 181 };
var firstComputedProto23 = { data: 181 + 1 };
var secondComputedProto23 = { data: 181 + 2 };
var listObj23 = { ["__proto__"]: firstComputedProto23, __proto__: protoList23, ["__proto__"]: secondComputedProto23, value23: 181 + 3 };
check(Object.getPrototypeOf(listObj23) === protoList23, "property name list literal proto 23");
check(listObj23.__proto__ === secondComputedProto23, "property name list computed last wins 23");
check(listObj23.inheritedList === 181, "property name list inherited 23");
check(listObj23.value23 === 181 + 3, "property name list value 23");
var keyName23 = "__proto__";
var computedOnlyObj23 = { [keyName23]: firstComputedProto23, [keyName23]: secondComputedProto23 };
check(Object.getPrototypeOf(computedOnlyObj23) === Object.prototype, "computed only proto base 23");
check(computedOnlyObj23.__proto__ === secondComputedProto23, "computed only proto own 23");

var protoList24 = { inheritedList: 188 };
var firstComputedProto24 = { data: 188 + 1 };
var secondComputedProto24 = { data: 188 + 2 };
var listObj24 = { ["__proto__"]: firstComputedProto24, __proto__: protoList24, ["__proto__"]: secondComputedProto24, value24: 188 + 3 };
check(Object.getPrototypeOf(listObj24) === protoList24, "property name list literal proto 24");
check(listObj24.__proto__ === secondComputedProto24, "property name list computed last wins 24");
check(listObj24.inheritedList === 188, "property name list inherited 24");
check(listObj24.value24 === 188 + 3, "property name list value 24");
var keyName24 = "__proto__";
var computedOnlyObj24 = { [keyName24]: firstComputedProto24, [keyName24]: secondComputedProto24 };
check(Object.getPrototypeOf(computedOnlyObj24) === Object.prototype, "computed only proto base 24");
check(computedOnlyObj24.__proto__ === secondComputedProto24, "computed only proto own 24");

var protoList25 = { inheritedList: 195 };
var firstComputedProto25 = { data: 195 + 1 };
var secondComputedProto25 = { data: 195 + 2 };
var listObj25 = { ["__proto__"]: firstComputedProto25, __proto__: protoList25, ["__proto__"]: secondComputedProto25, value25: 195 + 3 };
check(Object.getPrototypeOf(listObj25) === protoList25, "property name list literal proto 25");
check(listObj25.__proto__ === secondComputedProto25, "property name list computed last wins 25");
check(listObj25.inheritedList === 195, "property name list inherited 25");
check(listObj25.value25 === 195 + 3, "property name list value 25");
var keyName25 = "__proto__";
var computedOnlyObj25 = { [keyName25]: firstComputedProto25, [keyName25]: secondComputedProto25 };
check(Object.getPrototypeOf(computedOnlyObj25) === Object.prototype, "computed only proto base 25");
check(computedOnlyObj25.__proto__ === secondComputedProto25, "computed only proto own 25");

var protoList26 = { inheritedList: 202 };
var firstComputedProto26 = { data: 202 + 1 };
var secondComputedProto26 = { data: 202 + 2 };
var listObj26 = { ["__proto__"]: firstComputedProto26, __proto__: protoList26, ["__proto__"]: secondComputedProto26, value26: 202 + 3 };
check(Object.getPrototypeOf(listObj26) === protoList26, "property name list literal proto 26");
check(listObj26.__proto__ === secondComputedProto26, "property name list computed last wins 26");
check(listObj26.inheritedList === 202, "property name list inherited 26");
check(listObj26.value26 === 202 + 3, "property name list value 26");
var keyName26 = "__proto__";
var computedOnlyObj26 = { [keyName26]: firstComputedProto26, [keyName26]: secondComputedProto26 };
check(Object.getPrototypeOf(computedOnlyObj26) === Object.prototype, "computed only proto base 26");
check(computedOnlyObj26.__proto__ === secondComputedProto26, "computed only proto own 26");

var protoList27 = { inheritedList: 209 };
var firstComputedProto27 = { data: 209 + 1 };
var secondComputedProto27 = { data: 209 + 2 };
var listObj27 = { ["__proto__"]: firstComputedProto27, __proto__: protoList27, ["__proto__"]: secondComputedProto27, value27: 209 + 3 };
check(Object.getPrototypeOf(listObj27) === protoList27, "property name list literal proto 27");
check(listObj27.__proto__ === secondComputedProto27, "property name list computed last wins 27");
check(listObj27.inheritedList === 209, "property name list inherited 27");
check(listObj27.value27 === 209 + 3, "property name list value 27");
var keyName27 = "__proto__";
var computedOnlyObj27 = { [keyName27]: firstComputedProto27, [keyName27]: secondComputedProto27 };
check(Object.getPrototypeOf(computedOnlyObj27) === Object.prototype, "computed only proto base 27");
check(computedOnlyObj27.__proto__ === secondComputedProto27, "computed only proto own 27");

var protoList28 = { inheritedList: 216 };
var firstComputedProto28 = { data: 216 + 1 };
var secondComputedProto28 = { data: 216 + 2 };
var listObj28 = { ["__proto__"]: firstComputedProto28, __proto__: protoList28, ["__proto__"]: secondComputedProto28, value28: 216 + 3 };
check(Object.getPrototypeOf(listObj28) === protoList28, "property name list literal proto 28");
check(listObj28.__proto__ === secondComputedProto28, "property name list computed last wins 28");
check(listObj28.inheritedList === 216, "property name list inherited 28");
check(listObj28.value28 === 216 + 3, "property name list value 28");
var keyName28 = "__proto__";
var computedOnlyObj28 = { [keyName28]: firstComputedProto28, [keyName28]: secondComputedProto28 };
check(Object.getPrototypeOf(computedOnlyObj28) === Object.prototype, "computed only proto base 28");
check(computedOnlyObj28.__proto__ === secondComputedProto28, "computed only proto own 28");

var protoList29 = { inheritedList: 223 };
var firstComputedProto29 = { data: 223 + 1 };
var secondComputedProto29 = { data: 223 + 2 };
var listObj29 = { ["__proto__"]: firstComputedProto29, __proto__: protoList29, ["__proto__"]: secondComputedProto29, value29: 223 + 3 };
check(Object.getPrototypeOf(listObj29) === protoList29, "property name list literal proto 29");
check(listObj29.__proto__ === secondComputedProto29, "property name list computed last wins 29");
check(listObj29.inheritedList === 223, "property name list inherited 29");
check(listObj29.value29 === 223 + 3, "property name list value 29");
var keyName29 = "__proto__";
var computedOnlyObj29 = { [keyName29]: firstComputedProto29, [keyName29]: secondComputedProto29 };
check(Object.getPrototypeOf(computedOnlyObj29) === Object.prototype, "computed only proto base 29");
check(computedOnlyObj29.__proto__ === secondComputedProto29, "computed only proto own 29");

var protoList30 = { inheritedList: 230 };
var firstComputedProto30 = { data: 230 + 1 };
var secondComputedProto30 = { data: 230 + 2 };
var listObj30 = { ["__proto__"]: firstComputedProto30, __proto__: protoList30, ["__proto__"]: secondComputedProto30, value30: 230 + 3 };
check(Object.getPrototypeOf(listObj30) === protoList30, "property name list literal proto 30");
check(listObj30.__proto__ === secondComputedProto30, "property name list computed last wins 30");
check(listObj30.inheritedList === 230, "property name list inherited 30");
check(listObj30.value30 === 230 + 3, "property name list value 30");
var keyName30 = "__proto__";
var computedOnlyObj30 = { [keyName30]: firstComputedProto30, [keyName30]: secondComputedProto30 };
check(Object.getPrototypeOf(computedOnlyObj30) === Object.prototype, "computed only proto base 30");
check(computedOnlyObj30.__proto__ === secondComputedProto30, "computed only proto own 30");

var protoList31 = { inheritedList: 237 };
var firstComputedProto31 = { data: 237 + 1 };
var secondComputedProto31 = { data: 237 + 2 };
var listObj31 = { ["__proto__"]: firstComputedProto31, __proto__: protoList31, ["__proto__"]: secondComputedProto31, value31: 237 + 3 };
check(Object.getPrototypeOf(listObj31) === protoList31, "property name list literal proto 31");
check(listObj31.__proto__ === secondComputedProto31, "property name list computed last wins 31");
check(listObj31.inheritedList === 237, "property name list inherited 31");
check(listObj31.value31 === 237 + 3, "property name list value 31");
var keyName31 = "__proto__";
var computedOnlyObj31 = { [keyName31]: firstComputedProto31, [keyName31]: secondComputedProto31 };
check(Object.getPrototypeOf(computedOnlyObj31) === Object.prototype, "computed only proto base 31");
check(computedOnlyObj31.__proto__ === secondComputedProto31, "computed only proto own 31");

var protoList32 = { inheritedList: 244 };
var firstComputedProto32 = { data: 244 + 1 };
var secondComputedProto32 = { data: 244 + 2 };
var listObj32 = { ["__proto__"]: firstComputedProto32, __proto__: protoList32, ["__proto__"]: secondComputedProto32, value32: 244 + 3 };
check(Object.getPrototypeOf(listObj32) === protoList32, "property name list literal proto 32");
check(listObj32.__proto__ === secondComputedProto32, "property name list computed last wins 32");
check(listObj32.inheritedList === 244, "property name list inherited 32");
check(listObj32.value32 === 244 + 3, "property name list value 32");
var keyName32 = "__proto__";
var computedOnlyObj32 = { [keyName32]: firstComputedProto32, [keyName32]: secondComputedProto32 };
check(Object.getPrototypeOf(computedOnlyObj32) === Object.prototype, "computed only proto base 32");
check(computedOnlyObj32.__proto__ === secondComputedProto32, "computed only proto own 32");

var protoList33 = { inheritedList: 251 };
var firstComputedProto33 = { data: 251 + 1 };
var secondComputedProto33 = { data: 251 + 2 };
var listObj33 = { ["__proto__"]: firstComputedProto33, __proto__: protoList33, ["__proto__"]: secondComputedProto33, value33: 251 + 3 };
check(Object.getPrototypeOf(listObj33) === protoList33, "property name list literal proto 33");
check(listObj33.__proto__ === secondComputedProto33, "property name list computed last wins 33");
check(listObj33.inheritedList === 251, "property name list inherited 33");
check(listObj33.value33 === 251 + 3, "property name list value 33");
var keyName33 = "__proto__";
var computedOnlyObj33 = { [keyName33]: firstComputedProto33, [keyName33]: secondComputedProto33 };
check(Object.getPrototypeOf(computedOnlyObj33) === Object.prototype, "computed only proto base 33");
check(computedOnlyObj33.__proto__ === secondComputedProto33, "computed only proto own 33");

var protoList34 = { inheritedList: 258 };
var firstComputedProto34 = { data: 258 + 1 };
var secondComputedProto34 = { data: 258 + 2 };
var listObj34 = { ["__proto__"]: firstComputedProto34, __proto__: protoList34, ["__proto__"]: secondComputedProto34, value34: 258 + 3 };
check(Object.getPrototypeOf(listObj34) === protoList34, "property name list literal proto 34");
check(listObj34.__proto__ === secondComputedProto34, "property name list computed last wins 34");
check(listObj34.inheritedList === 258, "property name list inherited 34");
check(listObj34.value34 === 258 + 3, "property name list value 34");
var keyName34 = "__proto__";
var computedOnlyObj34 = { [keyName34]: firstComputedProto34, [keyName34]: secondComputedProto34 };
check(Object.getPrototypeOf(computedOnlyObj34) === Object.prototype, "computed only proto base 34");
check(computedOnlyObj34.__proto__ === secondComputedProto34, "computed only proto own 34");

var protoList35 = { inheritedList: 265 };
var firstComputedProto35 = { data: 265 + 1 };
var secondComputedProto35 = { data: 265 + 2 };
var listObj35 = { ["__proto__"]: firstComputedProto35, __proto__: protoList35, ["__proto__"]: secondComputedProto35, value35: 265 + 3 };
check(Object.getPrototypeOf(listObj35) === protoList35, "property name list literal proto 35");
check(listObj35.__proto__ === secondComputedProto35, "property name list computed last wins 35");
check(listObj35.inheritedList === 265, "property name list inherited 35");
check(listObj35.value35 === 265 + 3, "property name list value 35");
var keyName35 = "__proto__";
var computedOnlyObj35 = { [keyName35]: firstComputedProto35, [keyName35]: secondComputedProto35 };
check(Object.getPrototypeOf(computedOnlyObj35) === Object.prototype, "computed only proto base 35");
check(computedOnlyObj35.__proto__ === secondComputedProto35, "computed only proto own 35");

var protoList36 = { inheritedList: 272 };
var firstComputedProto36 = { data: 272 + 1 };
var secondComputedProto36 = { data: 272 + 2 };
var listObj36 = { ["__proto__"]: firstComputedProto36, __proto__: protoList36, ["__proto__"]: secondComputedProto36, value36: 272 + 3 };
check(Object.getPrototypeOf(listObj36) === protoList36, "property name list literal proto 36");
check(listObj36.__proto__ === secondComputedProto36, "property name list computed last wins 36");
check(listObj36.inheritedList === 272, "property name list inherited 36");
check(listObj36.value36 === 272 + 3, "property name list value 36");
var keyName36 = "__proto__";
var computedOnlyObj36 = { [keyName36]: firstComputedProto36, [keyName36]: secondComputedProto36 };
check(Object.getPrototypeOf(computedOnlyObj36) === Object.prototype, "computed only proto base 36");
check(computedOnlyObj36.__proto__ === secondComputedProto36, "computed only proto own 36");

var protoList37 = { inheritedList: 279 };
var firstComputedProto37 = { data: 279 + 1 };
var secondComputedProto37 = { data: 279 + 2 };
var listObj37 = { ["__proto__"]: firstComputedProto37, __proto__: protoList37, ["__proto__"]: secondComputedProto37, value37: 279 + 3 };
check(Object.getPrototypeOf(listObj37) === protoList37, "property name list literal proto 37");
check(listObj37.__proto__ === secondComputedProto37, "property name list computed last wins 37");
check(listObj37.inheritedList === 279, "property name list inherited 37");
check(listObj37.value37 === 279 + 3, "property name list value 37");
var keyName37 = "__proto__";
var computedOnlyObj37 = { [keyName37]: firstComputedProto37, [keyName37]: secondComputedProto37 };
check(Object.getPrototypeOf(computedOnlyObj37) === Object.prototype, "computed only proto base 37");
check(computedOnlyObj37.__proto__ === secondComputedProto37, "computed only proto own 37");

var protoList38 = { inheritedList: 286 };
var firstComputedProto38 = { data: 286 + 1 };
var secondComputedProto38 = { data: 286 + 2 };
var listObj38 = { ["__proto__"]: firstComputedProto38, __proto__: protoList38, ["__proto__"]: secondComputedProto38, value38: 286 + 3 };
check(Object.getPrototypeOf(listObj38) === protoList38, "property name list literal proto 38");
check(listObj38.__proto__ === secondComputedProto38, "property name list computed last wins 38");
check(listObj38.inheritedList === 286, "property name list inherited 38");
check(listObj38.value38 === 286 + 3, "property name list value 38");
var keyName38 = "__proto__";
var computedOnlyObj38 = { [keyName38]: firstComputedProto38, [keyName38]: secondComputedProto38 };
check(Object.getPrototypeOf(computedOnlyObj38) === Object.prototype, "computed only proto base 38");
check(computedOnlyObj38.__proto__ === secondComputedProto38, "computed only proto own 38");

var protoList39 = { inheritedList: 293 };
var firstComputedProto39 = { data: 293 + 1 };
var secondComputedProto39 = { data: 293 + 2 };
var listObj39 = { ["__proto__"]: firstComputedProto39, __proto__: protoList39, ["__proto__"]: secondComputedProto39, value39: 293 + 3 };
check(Object.getPrototypeOf(listObj39) === protoList39, "property name list literal proto 39");
check(listObj39.__proto__ === secondComputedProto39, "property name list computed last wins 39");
check(listObj39.inheritedList === 293, "property name list inherited 39");
check(listObj39.value39 === 293 + 3, "property name list value 39");
var keyName39 = "__proto__";
var computedOnlyObj39 = { [keyName39]: firstComputedProto39, [keyName39]: secondComputedProto39 };
check(Object.getPrototypeOf(computedOnlyObj39) === Object.prototype, "computed only proto base 39");
check(computedOnlyObj39.__proto__ === secondComputedProto39, "computed only proto own 39");

var protoList40 = { inheritedList: 300 };
var firstComputedProto40 = { data: 300 + 1 };
var secondComputedProto40 = { data: 300 + 2 };
var listObj40 = { ["__proto__"]: firstComputedProto40, __proto__: protoList40, ["__proto__"]: secondComputedProto40, value40: 300 + 3 };
check(Object.getPrototypeOf(listObj40) === protoList40, "property name list literal proto 40");
check(listObj40.__proto__ === secondComputedProto40, "property name list computed last wins 40");
check(listObj40.inheritedList === 300, "property name list inherited 40");
check(listObj40.value40 === 300 + 3, "property name list value 40");
var keyName40 = "__proto__";
var computedOnlyObj40 = { [keyName40]: firstComputedProto40, [keyName40]: secondComputedProto40 };
check(Object.getPrototypeOf(computedOnlyObj40) === Object.prototype, "computed only proto base 40");
check(computedOnlyObj40.__proto__ === secondComputedProto40, "computed only proto own 40");

var protoList41 = { inheritedList: 307 };
var firstComputedProto41 = { data: 307 + 1 };
var secondComputedProto41 = { data: 307 + 2 };
var listObj41 = { ["__proto__"]: firstComputedProto41, __proto__: protoList41, ["__proto__"]: secondComputedProto41, value41: 307 + 3 };
check(Object.getPrototypeOf(listObj41) === protoList41, "property name list literal proto 41");
check(listObj41.__proto__ === secondComputedProto41, "property name list computed last wins 41");
check(listObj41.inheritedList === 307, "property name list inherited 41");
check(listObj41.value41 === 307 + 3, "property name list value 41");
var keyName41 = "__proto__";
var computedOnlyObj41 = { [keyName41]: firstComputedProto41, [keyName41]: secondComputedProto41 };
check(Object.getPrototypeOf(computedOnlyObj41) === Object.prototype, "computed only proto base 41");
check(computedOnlyObj41.__proto__ === secondComputedProto41, "computed only proto own 41");

var protoList42 = { inheritedList: 314 };
var firstComputedProto42 = { data: 314 + 1 };
var secondComputedProto42 = { data: 314 + 2 };
var listObj42 = { ["__proto__"]: firstComputedProto42, __proto__: protoList42, ["__proto__"]: secondComputedProto42, value42: 314 + 3 };
check(Object.getPrototypeOf(listObj42) === protoList42, "property name list literal proto 42");
check(listObj42.__proto__ === secondComputedProto42, "property name list computed last wins 42");
check(listObj42.inheritedList === 314, "property name list inherited 42");
check(listObj42.value42 === 314 + 3, "property name list value 42");
var keyName42 = "__proto__";
var computedOnlyObj42 = { [keyName42]: firstComputedProto42, [keyName42]: secondComputedProto42 };
check(Object.getPrototypeOf(computedOnlyObj42) === Object.prototype, "computed only proto base 42");
check(computedOnlyObj42.__proto__ === secondComputedProto42, "computed only proto own 42");

var protoList43 = { inheritedList: 321 };
var firstComputedProto43 = { data: 321 + 1 };
var secondComputedProto43 = { data: 321 + 2 };
var listObj43 = { ["__proto__"]: firstComputedProto43, __proto__: protoList43, ["__proto__"]: secondComputedProto43, value43: 321 + 3 };
check(Object.getPrototypeOf(listObj43) === protoList43, "property name list literal proto 43");
check(listObj43.__proto__ === secondComputedProto43, "property name list computed last wins 43");
check(listObj43.inheritedList === 321, "property name list inherited 43");
check(listObj43.value43 === 321 + 3, "property name list value 43");
var keyName43 = "__proto__";
var computedOnlyObj43 = { [keyName43]: firstComputedProto43, [keyName43]: secondComputedProto43 };
check(Object.getPrototypeOf(computedOnlyObj43) === Object.prototype, "computed only proto base 43");
check(computedOnlyObj43.__proto__ === secondComputedProto43, "computed only proto own 43");

var protoList44 = { inheritedList: 328 };
var firstComputedProto44 = { data: 328 + 1 };
var secondComputedProto44 = { data: 328 + 2 };
var listObj44 = { ["__proto__"]: firstComputedProto44, __proto__: protoList44, ["__proto__"]: secondComputedProto44, value44: 328 + 3 };
check(Object.getPrototypeOf(listObj44) === protoList44, "property name list literal proto 44");
check(listObj44.__proto__ === secondComputedProto44, "property name list computed last wins 44");
check(listObj44.inheritedList === 328, "property name list inherited 44");
check(listObj44.value44 === 328 + 3, "property name list value 44");
var keyName44 = "__proto__";
var computedOnlyObj44 = { [keyName44]: firstComputedProto44, [keyName44]: secondComputedProto44 };
check(Object.getPrototypeOf(computedOnlyObj44) === Object.prototype, "computed only proto base 44");
check(computedOnlyObj44.__proto__ === secondComputedProto44, "computed only proto own 44");

check(score > 0, "property name list score");
