// behavior: property-name-list-ignores-computed-names
// expected: pass
// goal: script
// size: stress
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}

var protoList0 = { inheritedList: 20 };
var firstComputedProto0 = { data: 20 + 1 };
var secondComputedProto0 = { data: 20 + 2 };
var listObj0 = { ["__proto__"]: firstComputedProto0, __proto__: protoList0, ["__proto__"]: secondComputedProto0, value0: 20 + 3 };
check(Object.getPrototypeOf(listObj0) === protoList0, "property name list literal proto 0");
check(listObj0.__proto__ === secondComputedProto0, "property name list computed last wins 0");
check(listObj0.inheritedList === 20, "property name list inherited 0");
check(listObj0.value0 === 20 + 3, "property name list value 0");
var keyName0 = "__proto__";
var computedOnlyObj0 = { [keyName0]: firstComputedProto0, [keyName0]: secondComputedProto0 };
check(Object.getPrototypeOf(computedOnlyObj0) === Object.prototype, "computed only proto base 0");
check(computedOnlyObj0.__proto__ === secondComputedProto0, "computed only proto own 0");

var protoList1 = { inheritedList: 27 };
var firstComputedProto1 = { data: 27 + 1 };
var secondComputedProto1 = { data: 27 + 2 };
var listObj1 = { ["__proto__"]: firstComputedProto1, __proto__: protoList1, ["__proto__"]: secondComputedProto1, value1: 27 + 3 };
check(Object.getPrototypeOf(listObj1) === protoList1, "property name list literal proto 1");
check(listObj1.__proto__ === secondComputedProto1, "property name list computed last wins 1");
check(listObj1.inheritedList === 27, "property name list inherited 1");
check(listObj1.value1 === 27 + 3, "property name list value 1");
var keyName1 = "__proto__";
var computedOnlyObj1 = { [keyName1]: firstComputedProto1, [keyName1]: secondComputedProto1 };
check(Object.getPrototypeOf(computedOnlyObj1) === Object.prototype, "computed only proto base 1");
check(computedOnlyObj1.__proto__ === secondComputedProto1, "computed only proto own 1");

var protoList2 = { inheritedList: 34 };
var firstComputedProto2 = { data: 34 + 1 };
var secondComputedProto2 = { data: 34 + 2 };
var listObj2 = { ["__proto__"]: firstComputedProto2, __proto__: protoList2, ["__proto__"]: secondComputedProto2, value2: 34 + 3 };
check(Object.getPrototypeOf(listObj2) === protoList2, "property name list literal proto 2");
check(listObj2.__proto__ === secondComputedProto2, "property name list computed last wins 2");
check(listObj2.inheritedList === 34, "property name list inherited 2");
check(listObj2.value2 === 34 + 3, "property name list value 2");
var keyName2 = "__proto__";
var computedOnlyObj2 = { [keyName2]: firstComputedProto2, [keyName2]: secondComputedProto2 };
check(Object.getPrototypeOf(computedOnlyObj2) === Object.prototype, "computed only proto base 2");
check(computedOnlyObj2.__proto__ === secondComputedProto2, "computed only proto own 2");

var protoList3 = { inheritedList: 41 };
var firstComputedProto3 = { data: 41 + 1 };
var secondComputedProto3 = { data: 41 + 2 };
var listObj3 = { ["__proto__"]: firstComputedProto3, __proto__: protoList3, ["__proto__"]: secondComputedProto3, value3: 41 + 3 };
check(Object.getPrototypeOf(listObj3) === protoList3, "property name list literal proto 3");
check(listObj3.__proto__ === secondComputedProto3, "property name list computed last wins 3");
check(listObj3.inheritedList === 41, "property name list inherited 3");
check(listObj3.value3 === 41 + 3, "property name list value 3");
var keyName3 = "__proto__";
var computedOnlyObj3 = { [keyName3]: firstComputedProto3, [keyName3]: secondComputedProto3 };
check(Object.getPrototypeOf(computedOnlyObj3) === Object.prototype, "computed only proto base 3");
check(computedOnlyObj3.__proto__ === secondComputedProto3, "computed only proto own 3");

var protoList4 = { inheritedList: 48 };
var firstComputedProto4 = { data: 48 + 1 };
var secondComputedProto4 = { data: 48 + 2 };
var listObj4 = { ["__proto__"]: firstComputedProto4, __proto__: protoList4, ["__proto__"]: secondComputedProto4, value4: 48 + 3 };
check(Object.getPrototypeOf(listObj4) === protoList4, "property name list literal proto 4");
check(listObj4.__proto__ === secondComputedProto4, "property name list computed last wins 4");
check(listObj4.inheritedList === 48, "property name list inherited 4");
check(listObj4.value4 === 48 + 3, "property name list value 4");
var keyName4 = "__proto__";
var computedOnlyObj4 = { [keyName4]: firstComputedProto4, [keyName4]: secondComputedProto4 };
check(Object.getPrototypeOf(computedOnlyObj4) === Object.prototype, "computed only proto base 4");
check(computedOnlyObj4.__proto__ === secondComputedProto4, "computed only proto own 4");

var protoList5 = { inheritedList: 55 };
var firstComputedProto5 = { data: 55 + 1 };
var secondComputedProto5 = { data: 55 + 2 };
var listObj5 = { ["__proto__"]: firstComputedProto5, __proto__: protoList5, ["__proto__"]: secondComputedProto5, value5: 55 + 3 };
check(Object.getPrototypeOf(listObj5) === protoList5, "property name list literal proto 5");
check(listObj5.__proto__ === secondComputedProto5, "property name list computed last wins 5");
check(listObj5.inheritedList === 55, "property name list inherited 5");
check(listObj5.value5 === 55 + 3, "property name list value 5");
var keyName5 = "__proto__";
var computedOnlyObj5 = { [keyName5]: firstComputedProto5, [keyName5]: secondComputedProto5 };
check(Object.getPrototypeOf(computedOnlyObj5) === Object.prototype, "computed only proto base 5");
check(computedOnlyObj5.__proto__ === secondComputedProto5, "computed only proto own 5");

var protoList6 = { inheritedList: 62 };
var firstComputedProto6 = { data: 62 + 1 };
var secondComputedProto6 = { data: 62 + 2 };
var listObj6 = { ["__proto__"]: firstComputedProto6, __proto__: protoList6, ["__proto__"]: secondComputedProto6, value6: 62 + 3 };
check(Object.getPrototypeOf(listObj6) === protoList6, "property name list literal proto 6");
check(listObj6.__proto__ === secondComputedProto6, "property name list computed last wins 6");
check(listObj6.inheritedList === 62, "property name list inherited 6");
check(listObj6.value6 === 62 + 3, "property name list value 6");
var keyName6 = "__proto__";
var computedOnlyObj6 = { [keyName6]: firstComputedProto6, [keyName6]: secondComputedProto6 };
check(Object.getPrototypeOf(computedOnlyObj6) === Object.prototype, "computed only proto base 6");
check(computedOnlyObj6.__proto__ === secondComputedProto6, "computed only proto own 6");

var protoList7 = { inheritedList: 69 };
var firstComputedProto7 = { data: 69 + 1 };
var secondComputedProto7 = { data: 69 + 2 };
var listObj7 = { ["__proto__"]: firstComputedProto7, __proto__: protoList7, ["__proto__"]: secondComputedProto7, value7: 69 + 3 };
check(Object.getPrototypeOf(listObj7) === protoList7, "property name list literal proto 7");
check(listObj7.__proto__ === secondComputedProto7, "property name list computed last wins 7");
check(listObj7.inheritedList === 69, "property name list inherited 7");
check(listObj7.value7 === 69 + 3, "property name list value 7");
var keyName7 = "__proto__";
var computedOnlyObj7 = { [keyName7]: firstComputedProto7, [keyName7]: secondComputedProto7 };
check(Object.getPrototypeOf(computedOnlyObj7) === Object.prototype, "computed only proto base 7");
check(computedOnlyObj7.__proto__ === secondComputedProto7, "computed only proto own 7");

var protoList8 = { inheritedList: 76 };
var firstComputedProto8 = { data: 76 + 1 };
var secondComputedProto8 = { data: 76 + 2 };
var listObj8 = { ["__proto__"]: firstComputedProto8, __proto__: protoList8, ["__proto__"]: secondComputedProto8, value8: 76 + 3 };
check(Object.getPrototypeOf(listObj8) === protoList8, "property name list literal proto 8");
check(listObj8.__proto__ === secondComputedProto8, "property name list computed last wins 8");
check(listObj8.inheritedList === 76, "property name list inherited 8");
check(listObj8.value8 === 76 + 3, "property name list value 8");
var keyName8 = "__proto__";
var computedOnlyObj8 = { [keyName8]: firstComputedProto8, [keyName8]: secondComputedProto8 };
check(Object.getPrototypeOf(computedOnlyObj8) === Object.prototype, "computed only proto base 8");
check(computedOnlyObj8.__proto__ === secondComputedProto8, "computed only proto own 8");

var protoList9 = { inheritedList: 83 };
var firstComputedProto9 = { data: 83 + 1 };
var secondComputedProto9 = { data: 83 + 2 };
var listObj9 = { ["__proto__"]: firstComputedProto9, __proto__: protoList9, ["__proto__"]: secondComputedProto9, value9: 83 + 3 };
check(Object.getPrototypeOf(listObj9) === protoList9, "property name list literal proto 9");
check(listObj9.__proto__ === secondComputedProto9, "property name list computed last wins 9");
check(listObj9.inheritedList === 83, "property name list inherited 9");
check(listObj9.value9 === 83 + 3, "property name list value 9");
var keyName9 = "__proto__";
var computedOnlyObj9 = { [keyName9]: firstComputedProto9, [keyName9]: secondComputedProto9 };
check(Object.getPrototypeOf(computedOnlyObj9) === Object.prototype, "computed only proto base 9");
check(computedOnlyObj9.__proto__ === secondComputedProto9, "computed only proto own 9");

var protoList10 = { inheritedList: 90 };
var firstComputedProto10 = { data: 90 + 1 };
var secondComputedProto10 = { data: 90 + 2 };
var listObj10 = { ["__proto__"]: firstComputedProto10, __proto__: protoList10, ["__proto__"]: secondComputedProto10, value10: 90 + 3 };
check(Object.getPrototypeOf(listObj10) === protoList10, "property name list literal proto 10");
check(listObj10.__proto__ === secondComputedProto10, "property name list computed last wins 10");
check(listObj10.inheritedList === 90, "property name list inherited 10");
check(listObj10.value10 === 90 + 3, "property name list value 10");
var keyName10 = "__proto__";
var computedOnlyObj10 = { [keyName10]: firstComputedProto10, [keyName10]: secondComputedProto10 };
check(Object.getPrototypeOf(computedOnlyObj10) === Object.prototype, "computed only proto base 10");
check(computedOnlyObj10.__proto__ === secondComputedProto10, "computed only proto own 10");

var protoList11 = { inheritedList: 97 };
var firstComputedProto11 = { data: 97 + 1 };
var secondComputedProto11 = { data: 97 + 2 };
var listObj11 = { ["__proto__"]: firstComputedProto11, __proto__: protoList11, ["__proto__"]: secondComputedProto11, value11: 97 + 3 };
check(Object.getPrototypeOf(listObj11) === protoList11, "property name list literal proto 11");
check(listObj11.__proto__ === secondComputedProto11, "property name list computed last wins 11");
check(listObj11.inheritedList === 97, "property name list inherited 11");
check(listObj11.value11 === 97 + 3, "property name list value 11");
var keyName11 = "__proto__";
var computedOnlyObj11 = { [keyName11]: firstComputedProto11, [keyName11]: secondComputedProto11 };
check(Object.getPrototypeOf(computedOnlyObj11) === Object.prototype, "computed only proto base 11");
check(computedOnlyObj11.__proto__ === secondComputedProto11, "computed only proto own 11");

var protoList12 = { inheritedList: 104 };
var firstComputedProto12 = { data: 104 + 1 };
var secondComputedProto12 = { data: 104 + 2 };
var listObj12 = { ["__proto__"]: firstComputedProto12, __proto__: protoList12, ["__proto__"]: secondComputedProto12, value12: 104 + 3 };
check(Object.getPrototypeOf(listObj12) === protoList12, "property name list literal proto 12");
check(listObj12.__proto__ === secondComputedProto12, "property name list computed last wins 12");
check(listObj12.inheritedList === 104, "property name list inherited 12");
check(listObj12.value12 === 104 + 3, "property name list value 12");
var keyName12 = "__proto__";
var computedOnlyObj12 = { [keyName12]: firstComputedProto12, [keyName12]: secondComputedProto12 };
check(Object.getPrototypeOf(computedOnlyObj12) === Object.prototype, "computed only proto base 12");
check(computedOnlyObj12.__proto__ === secondComputedProto12, "computed only proto own 12");

var protoList13 = { inheritedList: 111 };
var firstComputedProto13 = { data: 111 + 1 };
var secondComputedProto13 = { data: 111 + 2 };
var listObj13 = { ["__proto__"]: firstComputedProto13, __proto__: protoList13, ["__proto__"]: secondComputedProto13, value13: 111 + 3 };
check(Object.getPrototypeOf(listObj13) === protoList13, "property name list literal proto 13");
check(listObj13.__proto__ === secondComputedProto13, "property name list computed last wins 13");
check(listObj13.inheritedList === 111, "property name list inherited 13");
check(listObj13.value13 === 111 + 3, "property name list value 13");
var keyName13 = "__proto__";
var computedOnlyObj13 = { [keyName13]: firstComputedProto13, [keyName13]: secondComputedProto13 };
check(Object.getPrototypeOf(computedOnlyObj13) === Object.prototype, "computed only proto base 13");
check(computedOnlyObj13.__proto__ === secondComputedProto13, "computed only proto own 13");

var protoList14 = { inheritedList: 118 };
var firstComputedProto14 = { data: 118 + 1 };
var secondComputedProto14 = { data: 118 + 2 };
var listObj14 = { ["__proto__"]: firstComputedProto14, __proto__: protoList14, ["__proto__"]: secondComputedProto14, value14: 118 + 3 };
check(Object.getPrototypeOf(listObj14) === protoList14, "property name list literal proto 14");
check(listObj14.__proto__ === secondComputedProto14, "property name list computed last wins 14");
check(listObj14.inheritedList === 118, "property name list inherited 14");
check(listObj14.value14 === 118 + 3, "property name list value 14");
var keyName14 = "__proto__";
var computedOnlyObj14 = { [keyName14]: firstComputedProto14, [keyName14]: secondComputedProto14 };
check(Object.getPrototypeOf(computedOnlyObj14) === Object.prototype, "computed only proto base 14");
check(computedOnlyObj14.__proto__ === secondComputedProto14, "computed only proto own 14");

var protoList15 = { inheritedList: 125 };
var firstComputedProto15 = { data: 125 + 1 };
var secondComputedProto15 = { data: 125 + 2 };
var listObj15 = { ["__proto__"]: firstComputedProto15, __proto__: protoList15, ["__proto__"]: secondComputedProto15, value15: 125 + 3 };
check(Object.getPrototypeOf(listObj15) === protoList15, "property name list literal proto 15");
check(listObj15.__proto__ === secondComputedProto15, "property name list computed last wins 15");
check(listObj15.inheritedList === 125, "property name list inherited 15");
check(listObj15.value15 === 125 + 3, "property name list value 15");
var keyName15 = "__proto__";
var computedOnlyObj15 = { [keyName15]: firstComputedProto15, [keyName15]: secondComputedProto15 };
check(Object.getPrototypeOf(computedOnlyObj15) === Object.prototype, "computed only proto base 15");
check(computedOnlyObj15.__proto__ === secondComputedProto15, "computed only proto own 15");

var protoList16 = { inheritedList: 132 };
var firstComputedProto16 = { data: 132 + 1 };
var secondComputedProto16 = { data: 132 + 2 };
var listObj16 = { ["__proto__"]: firstComputedProto16, __proto__: protoList16, ["__proto__"]: secondComputedProto16, value16: 132 + 3 };
check(Object.getPrototypeOf(listObj16) === protoList16, "property name list literal proto 16");
check(listObj16.__proto__ === secondComputedProto16, "property name list computed last wins 16");
check(listObj16.inheritedList === 132, "property name list inherited 16");
check(listObj16.value16 === 132 + 3, "property name list value 16");
var keyName16 = "__proto__";
var computedOnlyObj16 = { [keyName16]: firstComputedProto16, [keyName16]: secondComputedProto16 };
check(Object.getPrototypeOf(computedOnlyObj16) === Object.prototype, "computed only proto base 16");
check(computedOnlyObj16.__proto__ === secondComputedProto16, "computed only proto own 16");

var protoList17 = { inheritedList: 139 };
var firstComputedProto17 = { data: 139 + 1 };
var secondComputedProto17 = { data: 139 + 2 };
var listObj17 = { ["__proto__"]: firstComputedProto17, __proto__: protoList17, ["__proto__"]: secondComputedProto17, value17: 139 + 3 };
check(Object.getPrototypeOf(listObj17) === protoList17, "property name list literal proto 17");
check(listObj17.__proto__ === secondComputedProto17, "property name list computed last wins 17");
check(listObj17.inheritedList === 139, "property name list inherited 17");
check(listObj17.value17 === 139 + 3, "property name list value 17");
var keyName17 = "__proto__";
var computedOnlyObj17 = { [keyName17]: firstComputedProto17, [keyName17]: secondComputedProto17 };
check(Object.getPrototypeOf(computedOnlyObj17) === Object.prototype, "computed only proto base 17");
check(computedOnlyObj17.__proto__ === secondComputedProto17, "computed only proto own 17");

var protoList18 = { inheritedList: 146 };
var firstComputedProto18 = { data: 146 + 1 };
var secondComputedProto18 = { data: 146 + 2 };
var listObj18 = { ["__proto__"]: firstComputedProto18, __proto__: protoList18, ["__proto__"]: secondComputedProto18, value18: 146 + 3 };
check(Object.getPrototypeOf(listObj18) === protoList18, "property name list literal proto 18");
check(listObj18.__proto__ === secondComputedProto18, "property name list computed last wins 18");
check(listObj18.inheritedList === 146, "property name list inherited 18");
check(listObj18.value18 === 146 + 3, "property name list value 18");
var keyName18 = "__proto__";
var computedOnlyObj18 = { [keyName18]: firstComputedProto18, [keyName18]: secondComputedProto18 };
check(Object.getPrototypeOf(computedOnlyObj18) === Object.prototype, "computed only proto base 18");
check(computedOnlyObj18.__proto__ === secondComputedProto18, "computed only proto own 18");

var protoList19 = { inheritedList: 153 };
var firstComputedProto19 = { data: 153 + 1 };
var secondComputedProto19 = { data: 153 + 2 };
var listObj19 = { ["__proto__"]: firstComputedProto19, __proto__: protoList19, ["__proto__"]: secondComputedProto19, value19: 153 + 3 };
check(Object.getPrototypeOf(listObj19) === protoList19, "property name list literal proto 19");
check(listObj19.__proto__ === secondComputedProto19, "property name list computed last wins 19");
check(listObj19.inheritedList === 153, "property name list inherited 19");
check(listObj19.value19 === 153 + 3, "property name list value 19");
var keyName19 = "__proto__";
var computedOnlyObj19 = { [keyName19]: firstComputedProto19, [keyName19]: secondComputedProto19 };
check(Object.getPrototypeOf(computedOnlyObj19) === Object.prototype, "computed only proto base 19");
check(computedOnlyObj19.__proto__ === secondComputedProto19, "computed only proto own 19");

var protoList20 = { inheritedList: 160 };
var firstComputedProto20 = { data: 160 + 1 };
var secondComputedProto20 = { data: 160 + 2 };
var listObj20 = { ["__proto__"]: firstComputedProto20, __proto__: protoList20, ["__proto__"]: secondComputedProto20, value20: 160 + 3 };
check(Object.getPrototypeOf(listObj20) === protoList20, "property name list literal proto 20");
check(listObj20.__proto__ === secondComputedProto20, "property name list computed last wins 20");
check(listObj20.inheritedList === 160, "property name list inherited 20");
check(listObj20.value20 === 160 + 3, "property name list value 20");
var keyName20 = "__proto__";
var computedOnlyObj20 = { [keyName20]: firstComputedProto20, [keyName20]: secondComputedProto20 };
check(Object.getPrototypeOf(computedOnlyObj20) === Object.prototype, "computed only proto base 20");
check(computedOnlyObj20.__proto__ === secondComputedProto20, "computed only proto own 20");

var protoList21 = { inheritedList: 167 };
var firstComputedProto21 = { data: 167 + 1 };
var secondComputedProto21 = { data: 167 + 2 };
var listObj21 = { ["__proto__"]: firstComputedProto21, __proto__: protoList21, ["__proto__"]: secondComputedProto21, value21: 167 + 3 };
check(Object.getPrototypeOf(listObj21) === protoList21, "property name list literal proto 21");
check(listObj21.__proto__ === secondComputedProto21, "property name list computed last wins 21");
check(listObj21.inheritedList === 167, "property name list inherited 21");
check(listObj21.value21 === 167 + 3, "property name list value 21");
var keyName21 = "__proto__";
var computedOnlyObj21 = { [keyName21]: firstComputedProto21, [keyName21]: secondComputedProto21 };
check(Object.getPrototypeOf(computedOnlyObj21) === Object.prototype, "computed only proto base 21");
check(computedOnlyObj21.__proto__ === secondComputedProto21, "computed only proto own 21");

var protoList22 = { inheritedList: 174 };
var firstComputedProto22 = { data: 174 + 1 };
var secondComputedProto22 = { data: 174 + 2 };
var listObj22 = { ["__proto__"]: firstComputedProto22, __proto__: protoList22, ["__proto__"]: secondComputedProto22, value22: 174 + 3 };
check(Object.getPrototypeOf(listObj22) === protoList22, "property name list literal proto 22");
check(listObj22.__proto__ === secondComputedProto22, "property name list computed last wins 22");
check(listObj22.inheritedList === 174, "property name list inherited 22");
check(listObj22.value22 === 174 + 3, "property name list value 22");
var keyName22 = "__proto__";
var computedOnlyObj22 = { [keyName22]: firstComputedProto22, [keyName22]: secondComputedProto22 };
check(Object.getPrototypeOf(computedOnlyObj22) === Object.prototype, "computed only proto base 22");
check(computedOnlyObj22.__proto__ === secondComputedProto22, "computed only proto own 22");

var protoList23 = { inheritedList: 181 };
var firstComputedProto23 = { data: 181 + 1 };
var secondComputedProto23 = { data: 181 + 2 };
var listObj23 = { ["__proto__"]: firstComputedProto23, __proto__: protoList23, ["__proto__"]: secondComputedProto23, value23: 181 + 3 };
check(Object.getPrototypeOf(listObj23) === protoList23, "property name list literal proto 23");
check(listObj23.__proto__ === secondComputedProto23, "property name list computed last wins 23");
check(listObj23.inheritedList === 181, "property name list inherited 23");
check(listObj23.value23 === 181 + 3, "property name list value 23");
var keyName23 = "__proto__";
var computedOnlyObj23 = { [keyName23]: firstComputedProto23, [keyName23]: secondComputedProto23 };
check(Object.getPrototypeOf(computedOnlyObj23) === Object.prototype, "computed only proto base 23");
check(computedOnlyObj23.__proto__ === secondComputedProto23, "computed only proto own 23");

var protoList24 = { inheritedList: 188 };
var firstComputedProto24 = { data: 188 + 1 };
var secondComputedProto24 = { data: 188 + 2 };
var listObj24 = { ["__proto__"]: firstComputedProto24, __proto__: protoList24, ["__proto__"]: secondComputedProto24, value24: 188 + 3 };
check(Object.getPrototypeOf(listObj24) === protoList24, "property name list literal proto 24");
check(listObj24.__proto__ === secondComputedProto24, "property name list computed last wins 24");
check(listObj24.inheritedList === 188, "property name list inherited 24");
check(listObj24.value24 === 188 + 3, "property name list value 24");
var keyName24 = "__proto__";
var computedOnlyObj24 = { [keyName24]: firstComputedProto24, [keyName24]: secondComputedProto24 };
check(Object.getPrototypeOf(computedOnlyObj24) === Object.prototype, "computed only proto base 24");
check(computedOnlyObj24.__proto__ === secondComputedProto24, "computed only proto own 24");

var protoList25 = { inheritedList: 195 };
var firstComputedProto25 = { data: 195 + 1 };
var secondComputedProto25 = { data: 195 + 2 };
var listObj25 = { ["__proto__"]: firstComputedProto25, __proto__: protoList25, ["__proto__"]: secondComputedProto25, value25: 195 + 3 };
check(Object.getPrototypeOf(listObj25) === protoList25, "property name list literal proto 25");
check(listObj25.__proto__ === secondComputedProto25, "property name list computed last wins 25");
check(listObj25.inheritedList === 195, "property name list inherited 25");
check(listObj25.value25 === 195 + 3, "property name list value 25");
var keyName25 = "__proto__";
var computedOnlyObj25 = { [keyName25]: firstComputedProto25, [keyName25]: secondComputedProto25 };
check(Object.getPrototypeOf(computedOnlyObj25) === Object.prototype, "computed only proto base 25");
check(computedOnlyObj25.__proto__ === secondComputedProto25, "computed only proto own 25");

var protoList26 = { inheritedList: 202 };
var firstComputedProto26 = { data: 202 + 1 };
var secondComputedProto26 = { data: 202 + 2 };
var listObj26 = { ["__proto__"]: firstComputedProto26, __proto__: protoList26, ["__proto__"]: secondComputedProto26, value26: 202 + 3 };
check(Object.getPrototypeOf(listObj26) === protoList26, "property name list literal proto 26");
check(listObj26.__proto__ === secondComputedProto26, "property name list computed last wins 26");
check(listObj26.inheritedList === 202, "property name list inherited 26");
check(listObj26.value26 === 202 + 3, "property name list value 26");
var keyName26 = "__proto__";
var computedOnlyObj26 = { [keyName26]: firstComputedProto26, [keyName26]: secondComputedProto26 };
check(Object.getPrototypeOf(computedOnlyObj26) === Object.prototype, "computed only proto base 26");
check(computedOnlyObj26.__proto__ === secondComputedProto26, "computed only proto own 26");

var protoList27 = { inheritedList: 209 };
var firstComputedProto27 = { data: 209 + 1 };
var secondComputedProto27 = { data: 209 + 2 };
var listObj27 = { ["__proto__"]: firstComputedProto27, __proto__: protoList27, ["__proto__"]: secondComputedProto27, value27: 209 + 3 };
check(Object.getPrototypeOf(listObj27) === protoList27, "property name list literal proto 27");
check(listObj27.__proto__ === secondComputedProto27, "property name list computed last wins 27");
check(listObj27.inheritedList === 209, "property name list inherited 27");
check(listObj27.value27 === 209 + 3, "property name list value 27");
var keyName27 = "__proto__";
var computedOnlyObj27 = { [keyName27]: firstComputedProto27, [keyName27]: secondComputedProto27 };
check(Object.getPrototypeOf(computedOnlyObj27) === Object.prototype, "computed only proto base 27");
check(computedOnlyObj27.__proto__ === secondComputedProto27, "computed only proto own 27");

var protoList28 = { inheritedList: 216 };
var firstComputedProto28 = { data: 216 + 1 };
var secondComputedProto28 = { data: 216 + 2 };
var listObj28 = { ["__proto__"]: firstComputedProto28, __proto__: protoList28, ["__proto__"]: secondComputedProto28, value28: 216 + 3 };
check(Object.getPrototypeOf(listObj28) === protoList28, "property name list literal proto 28");
check(listObj28.__proto__ === secondComputedProto28, "property name list computed last wins 28");
check(listObj28.inheritedList === 216, "property name list inherited 28");
check(listObj28.value28 === 216 + 3, "property name list value 28");
var keyName28 = "__proto__";
var computedOnlyObj28 = { [keyName28]: firstComputedProto28, [keyName28]: secondComputedProto28 };
check(Object.getPrototypeOf(computedOnlyObj28) === Object.prototype, "computed only proto base 28");
check(computedOnlyObj28.__proto__ === secondComputedProto28, "computed only proto own 28");

var protoList29 = { inheritedList: 223 };
var firstComputedProto29 = { data: 223 + 1 };
var secondComputedProto29 = { data: 223 + 2 };
var listObj29 = { ["__proto__"]: firstComputedProto29, __proto__: protoList29, ["__proto__"]: secondComputedProto29, value29: 223 + 3 };
check(Object.getPrototypeOf(listObj29) === protoList29, "property name list literal proto 29");
check(listObj29.__proto__ === secondComputedProto29, "property name list computed last wins 29");
check(listObj29.inheritedList === 223, "property name list inherited 29");
check(listObj29.value29 === 223 + 3, "property name list value 29");
var keyName29 = "__proto__";
var computedOnlyObj29 = { [keyName29]: firstComputedProto29, [keyName29]: secondComputedProto29 };
check(Object.getPrototypeOf(computedOnlyObj29) === Object.prototype, "computed only proto base 29");
check(computedOnlyObj29.__proto__ === secondComputedProto29, "computed only proto own 29");

var protoList30 = { inheritedList: 230 };
var firstComputedProto30 = { data: 230 + 1 };
var secondComputedProto30 = { data: 230 + 2 };
var listObj30 = { ["__proto__"]: firstComputedProto30, __proto__: protoList30, ["__proto__"]: secondComputedProto30, value30: 230 + 3 };
check(Object.getPrototypeOf(listObj30) === protoList30, "property name list literal proto 30");
check(listObj30.__proto__ === secondComputedProto30, "property name list computed last wins 30");
check(listObj30.inheritedList === 230, "property name list inherited 30");
check(listObj30.value30 === 230 + 3, "property name list value 30");
var keyName30 = "__proto__";
var computedOnlyObj30 = { [keyName30]: firstComputedProto30, [keyName30]: secondComputedProto30 };
check(Object.getPrototypeOf(computedOnlyObj30) === Object.prototype, "computed only proto base 30");
check(computedOnlyObj30.__proto__ === secondComputedProto30, "computed only proto own 30");

var protoList31 = { inheritedList: 237 };
var firstComputedProto31 = { data: 237 + 1 };
var secondComputedProto31 = { data: 237 + 2 };
var listObj31 = { ["__proto__"]: firstComputedProto31, __proto__: protoList31, ["__proto__"]: secondComputedProto31, value31: 237 + 3 };
check(Object.getPrototypeOf(listObj31) === protoList31, "property name list literal proto 31");
check(listObj31.__proto__ === secondComputedProto31, "property name list computed last wins 31");
check(listObj31.inheritedList === 237, "property name list inherited 31");
check(listObj31.value31 === 237 + 3, "property name list value 31");
var keyName31 = "__proto__";
var computedOnlyObj31 = { [keyName31]: firstComputedProto31, [keyName31]: secondComputedProto31 };
check(Object.getPrototypeOf(computedOnlyObj31) === Object.prototype, "computed only proto base 31");
check(computedOnlyObj31.__proto__ === secondComputedProto31, "computed only proto own 31");

var protoList32 = { inheritedList: 244 };
var firstComputedProto32 = { data: 244 + 1 };
var secondComputedProto32 = { data: 244 + 2 };
var listObj32 = { ["__proto__"]: firstComputedProto32, __proto__: protoList32, ["__proto__"]: secondComputedProto32, value32: 244 + 3 };
check(Object.getPrototypeOf(listObj32) === protoList32, "property name list literal proto 32");
check(listObj32.__proto__ === secondComputedProto32, "property name list computed last wins 32");
check(listObj32.inheritedList === 244, "property name list inherited 32");
check(listObj32.value32 === 244 + 3, "property name list value 32");
var keyName32 = "__proto__";
var computedOnlyObj32 = { [keyName32]: firstComputedProto32, [keyName32]: secondComputedProto32 };
check(Object.getPrototypeOf(computedOnlyObj32) === Object.prototype, "computed only proto base 32");
check(computedOnlyObj32.__proto__ === secondComputedProto32, "computed only proto own 32");

var protoList33 = { inheritedList: 251 };
var firstComputedProto33 = { data: 251 + 1 };
var secondComputedProto33 = { data: 251 + 2 };
var listObj33 = { ["__proto__"]: firstComputedProto33, __proto__: protoList33, ["__proto__"]: secondComputedProto33, value33: 251 + 3 };
check(Object.getPrototypeOf(listObj33) === protoList33, "property name list literal proto 33");
check(listObj33.__proto__ === secondComputedProto33, "property name list computed last wins 33");
check(listObj33.inheritedList === 251, "property name list inherited 33");
check(listObj33.value33 === 251 + 3, "property name list value 33");
var keyName33 = "__proto__";
var computedOnlyObj33 = { [keyName33]: firstComputedProto33, [keyName33]: secondComputedProto33 };
check(Object.getPrototypeOf(computedOnlyObj33) === Object.prototype, "computed only proto base 33");
check(computedOnlyObj33.__proto__ === secondComputedProto33, "computed only proto own 33");

var protoList34 = { inheritedList: 258 };
var firstComputedProto34 = { data: 258 + 1 };
var secondComputedProto34 = { data: 258 + 2 };
var listObj34 = { ["__proto__"]: firstComputedProto34, __proto__: protoList34, ["__proto__"]: secondComputedProto34, value34: 258 + 3 };
check(Object.getPrototypeOf(listObj34) === protoList34, "property name list literal proto 34");
check(listObj34.__proto__ === secondComputedProto34, "property name list computed last wins 34");
check(listObj34.inheritedList === 258, "property name list inherited 34");
check(listObj34.value34 === 258 + 3, "property name list value 34");
var keyName34 = "__proto__";
var computedOnlyObj34 = { [keyName34]: firstComputedProto34, [keyName34]: secondComputedProto34 };
check(Object.getPrototypeOf(computedOnlyObj34) === Object.prototype, "computed only proto base 34");
check(computedOnlyObj34.__proto__ === secondComputedProto34, "computed only proto own 34");

var protoList35 = { inheritedList: 265 };
var firstComputedProto35 = { data: 265 + 1 };
var secondComputedProto35 = { data: 265 + 2 };
var listObj35 = { ["__proto__"]: firstComputedProto35, __proto__: protoList35, ["__proto__"]: secondComputedProto35, value35: 265 + 3 };
check(Object.getPrototypeOf(listObj35) === protoList35, "property name list literal proto 35");
check(listObj35.__proto__ === secondComputedProto35, "property name list computed last wins 35");
check(listObj35.inheritedList === 265, "property name list inherited 35");
check(listObj35.value35 === 265 + 3, "property name list value 35");
var keyName35 = "__proto__";
var computedOnlyObj35 = { [keyName35]: firstComputedProto35, [keyName35]: secondComputedProto35 };
check(Object.getPrototypeOf(computedOnlyObj35) === Object.prototype, "computed only proto base 35");
check(computedOnlyObj35.__proto__ === secondComputedProto35, "computed only proto own 35");

var protoList36 = { inheritedList: 272 };
var firstComputedProto36 = { data: 272 + 1 };
var secondComputedProto36 = { data: 272 + 2 };
var listObj36 = { ["__proto__"]: firstComputedProto36, __proto__: protoList36, ["__proto__"]: secondComputedProto36, value36: 272 + 3 };
check(Object.getPrototypeOf(listObj36) === protoList36, "property name list literal proto 36");
check(listObj36.__proto__ === secondComputedProto36, "property name list computed last wins 36");
check(listObj36.inheritedList === 272, "property name list inherited 36");
check(listObj36.value36 === 272 + 3, "property name list value 36");
var keyName36 = "__proto__";
var computedOnlyObj36 = { [keyName36]: firstComputedProto36, [keyName36]: secondComputedProto36 };
check(Object.getPrototypeOf(computedOnlyObj36) === Object.prototype, "computed only proto base 36");
check(computedOnlyObj36.__proto__ === secondComputedProto36, "computed only proto own 36");

var protoList37 = { inheritedList: 279 };
var firstComputedProto37 = { data: 279 + 1 };
var secondComputedProto37 = { data: 279 + 2 };
var listObj37 = { ["__proto__"]: firstComputedProto37, __proto__: protoList37, ["__proto__"]: secondComputedProto37, value37: 279 + 3 };
check(Object.getPrototypeOf(listObj37) === protoList37, "property name list literal proto 37");
check(listObj37.__proto__ === secondComputedProto37, "property name list computed last wins 37");
check(listObj37.inheritedList === 279, "property name list inherited 37");
check(listObj37.value37 === 279 + 3, "property name list value 37");
var keyName37 = "__proto__";
var computedOnlyObj37 = { [keyName37]: firstComputedProto37, [keyName37]: secondComputedProto37 };
check(Object.getPrototypeOf(computedOnlyObj37) === Object.prototype, "computed only proto base 37");
check(computedOnlyObj37.__proto__ === secondComputedProto37, "computed only proto own 37");

var protoList38 = { inheritedList: 286 };
var firstComputedProto38 = { data: 286 + 1 };
var secondComputedProto38 = { data: 286 + 2 };
var listObj38 = { ["__proto__"]: firstComputedProto38, __proto__: protoList38, ["__proto__"]: secondComputedProto38, value38: 286 + 3 };
check(Object.getPrototypeOf(listObj38) === protoList38, "property name list literal proto 38");
check(listObj38.__proto__ === secondComputedProto38, "property name list computed last wins 38");
check(listObj38.inheritedList === 286, "property name list inherited 38");
check(listObj38.value38 === 286 + 3, "property name list value 38");
var keyName38 = "__proto__";
var computedOnlyObj38 = { [keyName38]: firstComputedProto38, [keyName38]: secondComputedProto38 };
check(Object.getPrototypeOf(computedOnlyObj38) === Object.prototype, "computed only proto base 38");
check(computedOnlyObj38.__proto__ === secondComputedProto38, "computed only proto own 38");

var protoList39 = { inheritedList: 293 };
var firstComputedProto39 = { data: 293 + 1 };
var secondComputedProto39 = { data: 293 + 2 };
var listObj39 = { ["__proto__"]: firstComputedProto39, __proto__: protoList39, ["__proto__"]: secondComputedProto39, value39: 293 + 3 };
check(Object.getPrototypeOf(listObj39) === protoList39, "property name list literal proto 39");
check(listObj39.__proto__ === secondComputedProto39, "property name list computed last wins 39");
check(listObj39.inheritedList === 293, "property name list inherited 39");
check(listObj39.value39 === 293 + 3, "property name list value 39");
var keyName39 = "__proto__";
var computedOnlyObj39 = { [keyName39]: firstComputedProto39, [keyName39]: secondComputedProto39 };
check(Object.getPrototypeOf(computedOnlyObj39) === Object.prototype, "computed only proto base 39");
check(computedOnlyObj39.__proto__ === secondComputedProto39, "computed only proto own 39");

var protoList40 = { inheritedList: 300 };
var firstComputedProto40 = { data: 300 + 1 };
var secondComputedProto40 = { data: 300 + 2 };
var listObj40 = { ["__proto__"]: firstComputedProto40, __proto__: protoList40, ["__proto__"]: secondComputedProto40, value40: 300 + 3 };
check(Object.getPrototypeOf(listObj40) === protoList40, "property name list literal proto 40");
check(listObj40.__proto__ === secondComputedProto40, "property name list computed last wins 40");
check(listObj40.inheritedList === 300, "property name list inherited 40");
check(listObj40.value40 === 300 + 3, "property name list value 40");
var keyName40 = "__proto__";
var computedOnlyObj40 = { [keyName40]: firstComputedProto40, [keyName40]: secondComputedProto40 };
check(Object.getPrototypeOf(computedOnlyObj40) === Object.prototype, "computed only proto base 40");
check(computedOnlyObj40.__proto__ === secondComputedProto40, "computed only proto own 40");

var protoList41 = { inheritedList: 307 };
var firstComputedProto41 = { data: 307 + 1 };
var secondComputedProto41 = { data: 307 + 2 };
var listObj41 = { ["__proto__"]: firstComputedProto41, __proto__: protoList41, ["__proto__"]: secondComputedProto41, value41: 307 + 3 };
check(Object.getPrototypeOf(listObj41) === protoList41, "property name list literal proto 41");
check(listObj41.__proto__ === secondComputedProto41, "property name list computed last wins 41");
check(listObj41.inheritedList === 307, "property name list inherited 41");
check(listObj41.value41 === 307 + 3, "property name list value 41");
var keyName41 = "__proto__";
var computedOnlyObj41 = { [keyName41]: firstComputedProto41, [keyName41]: secondComputedProto41 };
check(Object.getPrototypeOf(computedOnlyObj41) === Object.prototype, "computed only proto base 41");
check(computedOnlyObj41.__proto__ === secondComputedProto41, "computed only proto own 41");

var protoList42 = { inheritedList: 314 };
var firstComputedProto42 = { data: 314 + 1 };
var secondComputedProto42 = { data: 314 + 2 };
var listObj42 = { ["__proto__"]: firstComputedProto42, __proto__: protoList42, ["__proto__"]: secondComputedProto42, value42: 314 + 3 };
check(Object.getPrototypeOf(listObj42) === protoList42, "property name list literal proto 42");
check(listObj42.__proto__ === secondComputedProto42, "property name list computed last wins 42");
check(listObj42.inheritedList === 314, "property name list inherited 42");
check(listObj42.value42 === 314 + 3, "property name list value 42");
var keyName42 = "__proto__";
var computedOnlyObj42 = { [keyName42]: firstComputedProto42, [keyName42]: secondComputedProto42 };
check(Object.getPrototypeOf(computedOnlyObj42) === Object.prototype, "computed only proto base 42");
check(computedOnlyObj42.__proto__ === secondComputedProto42, "computed only proto own 42");

var protoList43 = { inheritedList: 321 };
var firstComputedProto43 = { data: 321 + 1 };
var secondComputedProto43 = { data: 321 + 2 };
var listObj43 = { ["__proto__"]: firstComputedProto43, __proto__: protoList43, ["__proto__"]: secondComputedProto43, value43: 321 + 3 };
check(Object.getPrototypeOf(listObj43) === protoList43, "property name list literal proto 43");
check(listObj43.__proto__ === secondComputedProto43, "property name list computed last wins 43");
check(listObj43.inheritedList === 321, "property name list inherited 43");
check(listObj43.value43 === 321 + 3, "property name list value 43");
var keyName43 = "__proto__";
var computedOnlyObj43 = { [keyName43]: firstComputedProto43, [keyName43]: secondComputedProto43 };
check(Object.getPrototypeOf(computedOnlyObj43) === Object.prototype, "computed only proto base 43");
check(computedOnlyObj43.__proto__ === secondComputedProto43, "computed only proto own 43");

var protoList44 = { inheritedList: 328 };
var firstComputedProto44 = { data: 328 + 1 };
var secondComputedProto44 = { data: 328 + 2 };
var listObj44 = { ["__proto__"]: firstComputedProto44, __proto__: protoList44, ["__proto__"]: secondComputedProto44, value44: 328 + 3 };
check(Object.getPrototypeOf(listObj44) === protoList44, "property name list literal proto 44");
check(listObj44.__proto__ === secondComputedProto44, "property name list computed last wins 44");
check(listObj44.inheritedList === 328, "property name list inherited 44");
check(listObj44.value44 === 328 + 3, "property name list value 44");
var keyName44 = "__proto__";
var computedOnlyObj44 = { [keyName44]: firstComputedProto44, [keyName44]: secondComputedProto44 };
check(Object.getPrototypeOf(computedOnlyObj44) === Object.prototype, "computed only proto base 44");
check(computedOnlyObj44.__proto__ === secondComputedProto44, "computed only proto own 44");

var protoList45 = { inheritedList: 335 };
var firstComputedProto45 = { data: 335 + 1 };
var secondComputedProto45 = { data: 335 + 2 };
var listObj45 = { ["__proto__"]: firstComputedProto45, __proto__: protoList45, ["__proto__"]: secondComputedProto45, value45: 335 + 3 };
check(Object.getPrototypeOf(listObj45) === protoList45, "property name list literal proto 45");
check(listObj45.__proto__ === secondComputedProto45, "property name list computed last wins 45");
check(listObj45.inheritedList === 335, "property name list inherited 45");
check(listObj45.value45 === 335 + 3, "property name list value 45");
var keyName45 = "__proto__";
var computedOnlyObj45 = { [keyName45]: firstComputedProto45, [keyName45]: secondComputedProto45 };
check(Object.getPrototypeOf(computedOnlyObj45) === Object.prototype, "computed only proto base 45");
check(computedOnlyObj45.__proto__ === secondComputedProto45, "computed only proto own 45");

var protoList46 = { inheritedList: 342 };
var firstComputedProto46 = { data: 342 + 1 };
var secondComputedProto46 = { data: 342 + 2 };
var listObj46 = { ["__proto__"]: firstComputedProto46, __proto__: protoList46, ["__proto__"]: secondComputedProto46, value46: 342 + 3 };
check(Object.getPrototypeOf(listObj46) === protoList46, "property name list literal proto 46");
check(listObj46.__proto__ === secondComputedProto46, "property name list computed last wins 46");
check(listObj46.inheritedList === 342, "property name list inherited 46");
check(listObj46.value46 === 342 + 3, "property name list value 46");
var keyName46 = "__proto__";
var computedOnlyObj46 = { [keyName46]: firstComputedProto46, [keyName46]: secondComputedProto46 };
check(Object.getPrototypeOf(computedOnlyObj46) === Object.prototype, "computed only proto base 46");
check(computedOnlyObj46.__proto__ === secondComputedProto46, "computed only proto own 46");

var protoList47 = { inheritedList: 349 };
var firstComputedProto47 = { data: 349 + 1 };
var secondComputedProto47 = { data: 349 + 2 };
var listObj47 = { ["__proto__"]: firstComputedProto47, __proto__: protoList47, ["__proto__"]: secondComputedProto47, value47: 349 + 3 };
check(Object.getPrototypeOf(listObj47) === protoList47, "property name list literal proto 47");
check(listObj47.__proto__ === secondComputedProto47, "property name list computed last wins 47");
check(listObj47.inheritedList === 349, "property name list inherited 47");
check(listObj47.value47 === 349 + 3, "property name list value 47");
var keyName47 = "__proto__";
var computedOnlyObj47 = { [keyName47]: firstComputedProto47, [keyName47]: secondComputedProto47 };
check(Object.getPrototypeOf(computedOnlyObj47) === Object.prototype, "computed only proto base 47");
check(computedOnlyObj47.__proto__ === secondComputedProto47, "computed only proto own 47");

var protoList48 = { inheritedList: 356 };
var firstComputedProto48 = { data: 356 + 1 };
var secondComputedProto48 = { data: 356 + 2 };
var listObj48 = { ["__proto__"]: firstComputedProto48, __proto__: protoList48, ["__proto__"]: secondComputedProto48, value48: 356 + 3 };
check(Object.getPrototypeOf(listObj48) === protoList48, "property name list literal proto 48");
check(listObj48.__proto__ === secondComputedProto48, "property name list computed last wins 48");
check(listObj48.inheritedList === 356, "property name list inherited 48");
check(listObj48.value48 === 356 + 3, "property name list value 48");
var keyName48 = "__proto__";
var computedOnlyObj48 = { [keyName48]: firstComputedProto48, [keyName48]: secondComputedProto48 };
check(Object.getPrototypeOf(computedOnlyObj48) === Object.prototype, "computed only proto base 48");
check(computedOnlyObj48.__proto__ === secondComputedProto48, "computed only proto own 48");

var protoList49 = { inheritedList: 363 };
var firstComputedProto49 = { data: 363 + 1 };
var secondComputedProto49 = { data: 363 + 2 };
var listObj49 = { ["__proto__"]: firstComputedProto49, __proto__: protoList49, ["__proto__"]: secondComputedProto49, value49: 363 + 3 };
check(Object.getPrototypeOf(listObj49) === protoList49, "property name list literal proto 49");
check(listObj49.__proto__ === secondComputedProto49, "property name list computed last wins 49");
check(listObj49.inheritedList === 363, "property name list inherited 49");
check(listObj49.value49 === 363 + 3, "property name list value 49");
var keyName49 = "__proto__";
var computedOnlyObj49 = { [keyName49]: firstComputedProto49, [keyName49]: secondComputedProto49 };
check(Object.getPrototypeOf(computedOnlyObj49) === Object.prototype, "computed only proto base 49");
check(computedOnlyObj49.__proto__ === secondComputedProto49, "computed only proto own 49");

var protoList50 = { inheritedList: 370 };
var firstComputedProto50 = { data: 370 + 1 };
var secondComputedProto50 = { data: 370 + 2 };
var listObj50 = { ["__proto__"]: firstComputedProto50, __proto__: protoList50, ["__proto__"]: secondComputedProto50, value50: 370 + 3 };
check(Object.getPrototypeOf(listObj50) === protoList50, "property name list literal proto 50");
check(listObj50.__proto__ === secondComputedProto50, "property name list computed last wins 50");
check(listObj50.inheritedList === 370, "property name list inherited 50");
check(listObj50.value50 === 370 + 3, "property name list value 50");
var keyName50 = "__proto__";
var computedOnlyObj50 = { [keyName50]: firstComputedProto50, [keyName50]: secondComputedProto50 };
check(Object.getPrototypeOf(computedOnlyObj50) === Object.prototype, "computed only proto base 50");
check(computedOnlyObj50.__proto__ === secondComputedProto50, "computed only proto own 50");

var protoList51 = { inheritedList: 377 };
var firstComputedProto51 = { data: 377 + 1 };
var secondComputedProto51 = { data: 377 + 2 };
var listObj51 = { ["__proto__"]: firstComputedProto51, __proto__: protoList51, ["__proto__"]: secondComputedProto51, value51: 377 + 3 };
check(Object.getPrototypeOf(listObj51) === protoList51, "property name list literal proto 51");
check(listObj51.__proto__ === secondComputedProto51, "property name list computed last wins 51");
check(listObj51.inheritedList === 377, "property name list inherited 51");
check(listObj51.value51 === 377 + 3, "property name list value 51");
var keyName51 = "__proto__";
var computedOnlyObj51 = { [keyName51]: firstComputedProto51, [keyName51]: secondComputedProto51 };
check(Object.getPrototypeOf(computedOnlyObj51) === Object.prototype, "computed only proto base 51");
check(computedOnlyObj51.__proto__ === secondComputedProto51, "computed only proto own 51");

var protoList52 = { inheritedList: 384 };
var firstComputedProto52 = { data: 384 + 1 };
var secondComputedProto52 = { data: 384 + 2 };
var listObj52 = { ["__proto__"]: firstComputedProto52, __proto__: protoList52, ["__proto__"]: secondComputedProto52, value52: 384 + 3 };
check(Object.getPrototypeOf(listObj52) === protoList52, "property name list literal proto 52");
check(listObj52.__proto__ === secondComputedProto52, "property name list computed last wins 52");
check(listObj52.inheritedList === 384, "property name list inherited 52");
check(listObj52.value52 === 384 + 3, "property name list value 52");
var keyName52 = "__proto__";
var computedOnlyObj52 = { [keyName52]: firstComputedProto52, [keyName52]: secondComputedProto52 };
check(Object.getPrototypeOf(computedOnlyObj52) === Object.prototype, "computed only proto base 52");
check(computedOnlyObj52.__proto__ === secondComputedProto52, "computed only proto own 52");

var protoList53 = { inheritedList: 391 };
var firstComputedProto53 = { data: 391 + 1 };
var secondComputedProto53 = { data: 391 + 2 };
var listObj53 = { ["__proto__"]: firstComputedProto53, __proto__: protoList53, ["__proto__"]: secondComputedProto53, value53: 391 + 3 };
check(Object.getPrototypeOf(listObj53) === protoList53, "property name list literal proto 53");
check(listObj53.__proto__ === secondComputedProto53, "property name list computed last wins 53");
check(listObj53.inheritedList === 391, "property name list inherited 53");
check(listObj53.value53 === 391 + 3, "property name list value 53");
var keyName53 = "__proto__";
var computedOnlyObj53 = { [keyName53]: firstComputedProto53, [keyName53]: secondComputedProto53 };
check(Object.getPrototypeOf(computedOnlyObj53) === Object.prototype, "computed only proto base 53");
check(computedOnlyObj53.__proto__ === secondComputedProto53, "computed only proto own 53");

var protoList54 = { inheritedList: 398 };
var firstComputedProto54 = { data: 398 + 1 };
var secondComputedProto54 = { data: 398 + 2 };
var listObj54 = { ["__proto__"]: firstComputedProto54, __proto__: protoList54, ["__proto__"]: secondComputedProto54, value54: 398 + 3 };
check(Object.getPrototypeOf(listObj54) === protoList54, "property name list literal proto 54");
check(listObj54.__proto__ === secondComputedProto54, "property name list computed last wins 54");
check(listObj54.inheritedList === 398, "property name list inherited 54");
check(listObj54.value54 === 398 + 3, "property name list value 54");
var keyName54 = "__proto__";
var computedOnlyObj54 = { [keyName54]: firstComputedProto54, [keyName54]: secondComputedProto54 };
check(Object.getPrototypeOf(computedOnlyObj54) === Object.prototype, "computed only proto base 54");
check(computedOnlyObj54.__proto__ === secondComputedProto54, "computed only proto own 54");

var protoList55 = { inheritedList: 405 };
var firstComputedProto55 = { data: 405 + 1 };
var secondComputedProto55 = { data: 405 + 2 };
var listObj55 = { ["__proto__"]: firstComputedProto55, __proto__: protoList55, ["__proto__"]: secondComputedProto55, value55: 405 + 3 };
check(Object.getPrototypeOf(listObj55) === protoList55, "property name list literal proto 55");
check(listObj55.__proto__ === secondComputedProto55, "property name list computed last wins 55");
check(listObj55.inheritedList === 405, "property name list inherited 55");
check(listObj55.value55 === 405 + 3, "property name list value 55");
var keyName55 = "__proto__";
var computedOnlyObj55 = { [keyName55]: firstComputedProto55, [keyName55]: secondComputedProto55 };
check(Object.getPrototypeOf(computedOnlyObj55) === Object.prototype, "computed only proto base 55");
check(computedOnlyObj55.__proto__ === secondComputedProto55, "computed only proto own 55");

var protoList56 = { inheritedList: 412 };
var firstComputedProto56 = { data: 412 + 1 };
var secondComputedProto56 = { data: 412 + 2 };
var listObj56 = { ["__proto__"]: firstComputedProto56, __proto__: protoList56, ["__proto__"]: secondComputedProto56, value56: 412 + 3 };
check(Object.getPrototypeOf(listObj56) === protoList56, "property name list literal proto 56");
check(listObj56.__proto__ === secondComputedProto56, "property name list computed last wins 56");
check(listObj56.inheritedList === 412, "property name list inherited 56");
check(listObj56.value56 === 412 + 3, "property name list value 56");
var keyName56 = "__proto__";
var computedOnlyObj56 = { [keyName56]: firstComputedProto56, [keyName56]: secondComputedProto56 };
check(Object.getPrototypeOf(computedOnlyObj56) === Object.prototype, "computed only proto base 56");
check(computedOnlyObj56.__proto__ === secondComputedProto56, "computed only proto own 56");

var protoList57 = { inheritedList: 419 };
var firstComputedProto57 = { data: 419 + 1 };
var secondComputedProto57 = { data: 419 + 2 };
var listObj57 = { ["__proto__"]: firstComputedProto57, __proto__: protoList57, ["__proto__"]: secondComputedProto57, value57: 419 + 3 };
check(Object.getPrototypeOf(listObj57) === protoList57, "property name list literal proto 57");
check(listObj57.__proto__ === secondComputedProto57, "property name list computed last wins 57");
check(listObj57.inheritedList === 419, "property name list inherited 57");
check(listObj57.value57 === 419 + 3, "property name list value 57");
var keyName57 = "__proto__";
var computedOnlyObj57 = { [keyName57]: firstComputedProto57, [keyName57]: secondComputedProto57 };
check(Object.getPrototypeOf(computedOnlyObj57) === Object.prototype, "computed only proto base 57");
check(computedOnlyObj57.__proto__ === secondComputedProto57, "computed only proto own 57");

var protoList58 = { inheritedList: 426 };
var firstComputedProto58 = { data: 426 + 1 };
var secondComputedProto58 = { data: 426 + 2 };
var listObj58 = { ["__proto__"]: firstComputedProto58, __proto__: protoList58, ["__proto__"]: secondComputedProto58, value58: 426 + 3 };
check(Object.getPrototypeOf(listObj58) === protoList58, "property name list literal proto 58");
check(listObj58.__proto__ === secondComputedProto58, "property name list computed last wins 58");
check(listObj58.inheritedList === 426, "property name list inherited 58");
check(listObj58.value58 === 426 + 3, "property name list value 58");
var keyName58 = "__proto__";
var computedOnlyObj58 = { [keyName58]: firstComputedProto58, [keyName58]: secondComputedProto58 };
check(Object.getPrototypeOf(computedOnlyObj58) === Object.prototype, "computed only proto base 58");
check(computedOnlyObj58.__proto__ === secondComputedProto58, "computed only proto own 58");

var protoList59 = { inheritedList: 433 };
var firstComputedProto59 = { data: 433 + 1 };
var secondComputedProto59 = { data: 433 + 2 };
var listObj59 = { ["__proto__"]: firstComputedProto59, __proto__: protoList59, ["__proto__"]: secondComputedProto59, value59: 433 + 3 };
check(Object.getPrototypeOf(listObj59) === protoList59, "property name list literal proto 59");
check(listObj59.__proto__ === secondComputedProto59, "property name list computed last wins 59");
check(listObj59.inheritedList === 433, "property name list inherited 59");
check(listObj59.value59 === 433 + 3, "property name list value 59");
var keyName59 = "__proto__";
var computedOnlyObj59 = { [keyName59]: firstComputedProto59, [keyName59]: secondComputedProto59 };
check(Object.getPrototypeOf(computedOnlyObj59) === Object.prototype, "computed only proto base 59");
check(computedOnlyObj59.__proto__ === secondComputedProto59, "computed only proto own 59");

var protoList60 = { inheritedList: 440 };
var firstComputedProto60 = { data: 440 + 1 };
var secondComputedProto60 = { data: 440 + 2 };
var listObj60 = { ["__proto__"]: firstComputedProto60, __proto__: protoList60, ["__proto__"]: secondComputedProto60, value60: 440 + 3 };
check(Object.getPrototypeOf(listObj60) === protoList60, "property name list literal proto 60");
check(listObj60.__proto__ === secondComputedProto60, "property name list computed last wins 60");
check(listObj60.inheritedList === 440, "property name list inherited 60");
check(listObj60.value60 === 440 + 3, "property name list value 60");
var keyName60 = "__proto__";
var computedOnlyObj60 = { [keyName60]: firstComputedProto60, [keyName60]: secondComputedProto60 };
check(Object.getPrototypeOf(computedOnlyObj60) === Object.prototype, "computed only proto base 60");
check(computedOnlyObj60.__proto__ === secondComputedProto60, "computed only proto own 60");

var protoList61 = { inheritedList: 447 };
var firstComputedProto61 = { data: 447 + 1 };
var secondComputedProto61 = { data: 447 + 2 };
var listObj61 = { ["__proto__"]: firstComputedProto61, __proto__: protoList61, ["__proto__"]: secondComputedProto61, value61: 447 + 3 };
check(Object.getPrototypeOf(listObj61) === protoList61, "property name list literal proto 61");
check(listObj61.__proto__ === secondComputedProto61, "property name list computed last wins 61");
check(listObj61.inheritedList === 447, "property name list inherited 61");
check(listObj61.value61 === 447 + 3, "property name list value 61");
var keyName61 = "__proto__";
var computedOnlyObj61 = { [keyName61]: firstComputedProto61, [keyName61]: secondComputedProto61 };
check(Object.getPrototypeOf(computedOnlyObj61) === Object.prototype, "computed only proto base 61");
check(computedOnlyObj61.__proto__ === secondComputedProto61, "computed only proto own 61");

var protoList62 = { inheritedList: 454 };
var firstComputedProto62 = { data: 454 + 1 };
var secondComputedProto62 = { data: 454 + 2 };
var listObj62 = { ["__proto__"]: firstComputedProto62, __proto__: protoList62, ["__proto__"]: secondComputedProto62, value62: 454 + 3 };
check(Object.getPrototypeOf(listObj62) === protoList62, "property name list literal proto 62");
check(listObj62.__proto__ === secondComputedProto62, "property name list computed last wins 62");
check(listObj62.inheritedList === 454, "property name list inherited 62");
check(listObj62.value62 === 454 + 3, "property name list value 62");
var keyName62 = "__proto__";
var computedOnlyObj62 = { [keyName62]: firstComputedProto62, [keyName62]: secondComputedProto62 };
check(Object.getPrototypeOf(computedOnlyObj62) === Object.prototype, "computed only proto base 62");
check(computedOnlyObj62.__proto__ === secondComputedProto62, "computed only proto own 62");

var protoList63 = { inheritedList: 461 };
var firstComputedProto63 = { data: 461 + 1 };
var secondComputedProto63 = { data: 461 + 2 };
var listObj63 = { ["__proto__"]: firstComputedProto63, __proto__: protoList63, ["__proto__"]: secondComputedProto63, value63: 461 + 3 };
check(Object.getPrototypeOf(listObj63) === protoList63, "property name list literal proto 63");
check(listObj63.__proto__ === secondComputedProto63, "property name list computed last wins 63");
check(listObj63.inheritedList === 461, "property name list inherited 63");
check(listObj63.value63 === 461 + 3, "property name list value 63");
var keyName63 = "__proto__";
var computedOnlyObj63 = { [keyName63]: firstComputedProto63, [keyName63]: secondComputedProto63 };
check(Object.getPrototypeOf(computedOnlyObj63) === Object.prototype, "computed only proto base 63");
check(computedOnlyObj63.__proto__ === secondComputedProto63, "computed only proto own 63");

var protoList64 = { inheritedList: 468 };
var firstComputedProto64 = { data: 468 + 1 };
var secondComputedProto64 = { data: 468 + 2 };
var listObj64 = { ["__proto__"]: firstComputedProto64, __proto__: protoList64, ["__proto__"]: secondComputedProto64, value64: 468 + 3 };
check(Object.getPrototypeOf(listObj64) === protoList64, "property name list literal proto 64");
check(listObj64.__proto__ === secondComputedProto64, "property name list computed last wins 64");
check(listObj64.inheritedList === 468, "property name list inherited 64");
check(listObj64.value64 === 468 + 3, "property name list value 64");
var keyName64 = "__proto__";
var computedOnlyObj64 = { [keyName64]: firstComputedProto64, [keyName64]: secondComputedProto64 };
check(Object.getPrototypeOf(computedOnlyObj64) === Object.prototype, "computed only proto base 64");
check(computedOnlyObj64.__proto__ === secondComputedProto64, "computed only proto own 64");

var protoList65 = { inheritedList: 475 };
var firstComputedProto65 = { data: 475 + 1 };
var secondComputedProto65 = { data: 475 + 2 };
var listObj65 = { ["__proto__"]: firstComputedProto65, __proto__: protoList65, ["__proto__"]: secondComputedProto65, value65: 475 + 3 };
check(Object.getPrototypeOf(listObj65) === protoList65, "property name list literal proto 65");
check(listObj65.__proto__ === secondComputedProto65, "property name list computed last wins 65");
check(listObj65.inheritedList === 475, "property name list inherited 65");
check(listObj65.value65 === 475 + 3, "property name list value 65");
var keyName65 = "__proto__";
var computedOnlyObj65 = { [keyName65]: firstComputedProto65, [keyName65]: secondComputedProto65 };
check(Object.getPrototypeOf(computedOnlyObj65) === Object.prototype, "computed only proto base 65");
check(computedOnlyObj65.__proto__ === secondComputedProto65, "computed only proto own 65");

var protoList66 = { inheritedList: 482 };
var firstComputedProto66 = { data: 482 + 1 };
var secondComputedProto66 = { data: 482 + 2 };
var listObj66 = { ["__proto__"]: firstComputedProto66, __proto__: protoList66, ["__proto__"]: secondComputedProto66, value66: 482 + 3 };
check(Object.getPrototypeOf(listObj66) === protoList66, "property name list literal proto 66");
check(listObj66.__proto__ === secondComputedProto66, "property name list computed last wins 66");
check(listObj66.inheritedList === 482, "property name list inherited 66");
check(listObj66.value66 === 482 + 3, "property name list value 66");
var keyName66 = "__proto__";
var computedOnlyObj66 = { [keyName66]: firstComputedProto66, [keyName66]: secondComputedProto66 };
check(Object.getPrototypeOf(computedOnlyObj66) === Object.prototype, "computed only proto base 66");
check(computedOnlyObj66.__proto__ === secondComputedProto66, "computed only proto own 66");

var protoList67 = { inheritedList: 489 };
var firstComputedProto67 = { data: 489 + 1 };
var secondComputedProto67 = { data: 489 + 2 };
var listObj67 = { ["__proto__"]: firstComputedProto67, __proto__: protoList67, ["__proto__"]: secondComputedProto67, value67: 489 + 3 };
check(Object.getPrototypeOf(listObj67) === protoList67, "property name list literal proto 67");
check(listObj67.__proto__ === secondComputedProto67, "property name list computed last wins 67");
check(listObj67.inheritedList === 489, "property name list inherited 67");
check(listObj67.value67 === 489 + 3, "property name list value 67");
var keyName67 = "__proto__";
var computedOnlyObj67 = { [keyName67]: firstComputedProto67, [keyName67]: secondComputedProto67 };
check(Object.getPrototypeOf(computedOnlyObj67) === Object.prototype, "computed only proto base 67");
check(computedOnlyObj67.__proto__ === secondComputedProto67, "computed only proto own 67");

var protoList68 = { inheritedList: 496 };
var firstComputedProto68 = { data: 496 + 1 };
var secondComputedProto68 = { data: 496 + 2 };
var listObj68 = { ["__proto__"]: firstComputedProto68, __proto__: protoList68, ["__proto__"]: secondComputedProto68, value68: 496 + 3 };
check(Object.getPrototypeOf(listObj68) === protoList68, "property name list literal proto 68");
check(listObj68.__proto__ === secondComputedProto68, "property name list computed last wins 68");
check(listObj68.inheritedList === 496, "property name list inherited 68");
check(listObj68.value68 === 496 + 3, "property name list value 68");
var keyName68 = "__proto__";
var computedOnlyObj68 = { [keyName68]: firstComputedProto68, [keyName68]: secondComputedProto68 };
check(Object.getPrototypeOf(computedOnlyObj68) === Object.prototype, "computed only proto base 68");
check(computedOnlyObj68.__proto__ === secondComputedProto68, "computed only proto own 68");

var protoList69 = { inheritedList: 503 };
var firstComputedProto69 = { data: 503 + 1 };
var secondComputedProto69 = { data: 503 + 2 };
var listObj69 = { ["__proto__"]: firstComputedProto69, __proto__: protoList69, ["__proto__"]: secondComputedProto69, value69: 503 + 3 };
check(Object.getPrototypeOf(listObj69) === protoList69, "property name list literal proto 69");
check(listObj69.__proto__ === secondComputedProto69, "property name list computed last wins 69");
check(listObj69.inheritedList === 503, "property name list inherited 69");
check(listObj69.value69 === 503 + 3, "property name list value 69");
var keyName69 = "__proto__";
var computedOnlyObj69 = { [keyName69]: firstComputedProto69, [keyName69]: secondComputedProto69 };
check(Object.getPrototypeOf(computedOnlyObj69) === Object.prototype, "computed only proto base 69");
check(computedOnlyObj69.__proto__ === secondComputedProto69, "computed only proto own 69");

var protoList70 = { inheritedList: 510 };
var firstComputedProto70 = { data: 510 + 1 };
var secondComputedProto70 = { data: 510 + 2 };
var listObj70 = { ["__proto__"]: firstComputedProto70, __proto__: protoList70, ["__proto__"]: secondComputedProto70, value70: 510 + 3 };
check(Object.getPrototypeOf(listObj70) === protoList70, "property name list literal proto 70");
check(listObj70.__proto__ === secondComputedProto70, "property name list computed last wins 70");
check(listObj70.inheritedList === 510, "property name list inherited 70");
check(listObj70.value70 === 510 + 3, "property name list value 70");
var keyName70 = "__proto__";
var computedOnlyObj70 = { [keyName70]: firstComputedProto70, [keyName70]: secondComputedProto70 };
check(Object.getPrototypeOf(computedOnlyObj70) === Object.prototype, "computed only proto base 70");
check(computedOnlyObj70.__proto__ === secondComputedProto70, "computed only proto own 70");

var protoList71 = { inheritedList: 517 };
var firstComputedProto71 = { data: 517 + 1 };
var secondComputedProto71 = { data: 517 + 2 };
var listObj71 = { ["__proto__"]: firstComputedProto71, __proto__: protoList71, ["__proto__"]: secondComputedProto71, value71: 517 + 3 };
check(Object.getPrototypeOf(listObj71) === protoList71, "property name list literal proto 71");
check(listObj71.__proto__ === secondComputedProto71, "property name list computed last wins 71");
check(listObj71.inheritedList === 517, "property name list inherited 71");
check(listObj71.value71 === 517 + 3, "property name list value 71");
var keyName71 = "__proto__";
var computedOnlyObj71 = { [keyName71]: firstComputedProto71, [keyName71]: secondComputedProto71 };
check(Object.getPrototypeOf(computedOnlyObj71) === Object.prototype, "computed only proto base 71");
check(computedOnlyObj71.__proto__ === secondComputedProto71, "computed only proto own 71");

var protoList72 = { inheritedList: 524 };
var firstComputedProto72 = { data: 524 + 1 };
var secondComputedProto72 = { data: 524 + 2 };
var listObj72 = { ["__proto__"]: firstComputedProto72, __proto__: protoList72, ["__proto__"]: secondComputedProto72, value72: 524 + 3 };
check(Object.getPrototypeOf(listObj72) === protoList72, "property name list literal proto 72");
check(listObj72.__proto__ === secondComputedProto72, "property name list computed last wins 72");
check(listObj72.inheritedList === 524, "property name list inherited 72");
check(listObj72.value72 === 524 + 3, "property name list value 72");
var keyName72 = "__proto__";
var computedOnlyObj72 = { [keyName72]: firstComputedProto72, [keyName72]: secondComputedProto72 };
check(Object.getPrototypeOf(computedOnlyObj72) === Object.prototype, "computed only proto base 72");
check(computedOnlyObj72.__proto__ === secondComputedProto72, "computed only proto own 72");

var protoList73 = { inheritedList: 531 };
var firstComputedProto73 = { data: 531 + 1 };
var secondComputedProto73 = { data: 531 + 2 };
var listObj73 = { ["__proto__"]: firstComputedProto73, __proto__: protoList73, ["__proto__"]: secondComputedProto73, value73: 531 + 3 };
check(Object.getPrototypeOf(listObj73) === protoList73, "property name list literal proto 73");
check(listObj73.__proto__ === secondComputedProto73, "property name list computed last wins 73");
check(listObj73.inheritedList === 531, "property name list inherited 73");
check(listObj73.value73 === 531 + 3, "property name list value 73");
var keyName73 = "__proto__";
var computedOnlyObj73 = { [keyName73]: firstComputedProto73, [keyName73]: secondComputedProto73 };
check(Object.getPrototypeOf(computedOnlyObj73) === Object.prototype, "computed only proto base 73");
check(computedOnlyObj73.__proto__ === secondComputedProto73, "computed only proto own 73");

var protoList74 = { inheritedList: 538 };
var firstComputedProto74 = { data: 538 + 1 };
var secondComputedProto74 = { data: 538 + 2 };
var listObj74 = { ["__proto__"]: firstComputedProto74, __proto__: protoList74, ["__proto__"]: secondComputedProto74, value74: 538 + 3 };
check(Object.getPrototypeOf(listObj74) === protoList74, "property name list literal proto 74");
check(listObj74.__proto__ === secondComputedProto74, "property name list computed last wins 74");
check(listObj74.inheritedList === 538, "property name list inherited 74");
check(listObj74.value74 === 538 + 3, "property name list value 74");
var keyName74 = "__proto__";
var computedOnlyObj74 = { [keyName74]: firstComputedProto74, [keyName74]: secondComputedProto74 };
check(Object.getPrototypeOf(computedOnlyObj74) === Object.prototype, "computed only proto base 74");
check(computedOnlyObj74.__proto__ === secondComputedProto74, "computed only proto own 74");

var protoList75 = { inheritedList: 545 };
var firstComputedProto75 = { data: 545 + 1 };
var secondComputedProto75 = { data: 545 + 2 };
var listObj75 = { ["__proto__"]: firstComputedProto75, __proto__: protoList75, ["__proto__"]: secondComputedProto75, value75: 545 + 3 };
check(Object.getPrototypeOf(listObj75) === protoList75, "property name list literal proto 75");
check(listObj75.__proto__ === secondComputedProto75, "property name list computed last wins 75");
check(listObj75.inheritedList === 545, "property name list inherited 75");
check(listObj75.value75 === 545 + 3, "property name list value 75");
var keyName75 = "__proto__";
var computedOnlyObj75 = { [keyName75]: firstComputedProto75, [keyName75]: secondComputedProto75 };
check(Object.getPrototypeOf(computedOnlyObj75) === Object.prototype, "computed only proto base 75");
check(computedOnlyObj75.__proto__ === secondComputedProto75, "computed only proto own 75");

var protoList76 = { inheritedList: 552 };
var firstComputedProto76 = { data: 552 + 1 };
var secondComputedProto76 = { data: 552 + 2 };
var listObj76 = { ["__proto__"]: firstComputedProto76, __proto__: protoList76, ["__proto__"]: secondComputedProto76, value76: 552 + 3 };
check(Object.getPrototypeOf(listObj76) === protoList76, "property name list literal proto 76");
check(listObj76.__proto__ === secondComputedProto76, "property name list computed last wins 76");
check(listObj76.inheritedList === 552, "property name list inherited 76");
check(listObj76.value76 === 552 + 3, "property name list value 76");
var keyName76 = "__proto__";
var computedOnlyObj76 = { [keyName76]: firstComputedProto76, [keyName76]: secondComputedProto76 };
check(Object.getPrototypeOf(computedOnlyObj76) === Object.prototype, "computed only proto base 76");
check(computedOnlyObj76.__proto__ === secondComputedProto76, "computed only proto own 76");

var protoList77 = { inheritedList: 559 };
var firstComputedProto77 = { data: 559 + 1 };
var secondComputedProto77 = { data: 559 + 2 };
var listObj77 = { ["__proto__"]: firstComputedProto77, __proto__: protoList77, ["__proto__"]: secondComputedProto77, value77: 559 + 3 };
check(Object.getPrototypeOf(listObj77) === protoList77, "property name list literal proto 77");
check(listObj77.__proto__ === secondComputedProto77, "property name list computed last wins 77");
check(listObj77.inheritedList === 559, "property name list inherited 77");
check(listObj77.value77 === 559 + 3, "property name list value 77");
var keyName77 = "__proto__";
var computedOnlyObj77 = { [keyName77]: firstComputedProto77, [keyName77]: secondComputedProto77 };
check(Object.getPrototypeOf(computedOnlyObj77) === Object.prototype, "computed only proto base 77");
check(computedOnlyObj77.__proto__ === secondComputedProto77, "computed only proto own 77");

var protoList78 = { inheritedList: 566 };
var firstComputedProto78 = { data: 566 + 1 };
var secondComputedProto78 = { data: 566 + 2 };
var listObj78 = { ["__proto__"]: firstComputedProto78, __proto__: protoList78, ["__proto__"]: secondComputedProto78, value78: 566 + 3 };
check(Object.getPrototypeOf(listObj78) === protoList78, "property name list literal proto 78");
check(listObj78.__proto__ === secondComputedProto78, "property name list computed last wins 78");
check(listObj78.inheritedList === 566, "property name list inherited 78");
check(listObj78.value78 === 566 + 3, "property name list value 78");
var keyName78 = "__proto__";
var computedOnlyObj78 = { [keyName78]: firstComputedProto78, [keyName78]: secondComputedProto78 };
check(Object.getPrototypeOf(computedOnlyObj78) === Object.prototype, "computed only proto base 78");
check(computedOnlyObj78.__proto__ === secondComputedProto78, "computed only proto own 78");

var protoList79 = { inheritedList: 573 };
var firstComputedProto79 = { data: 573 + 1 };
var secondComputedProto79 = { data: 573 + 2 };
var listObj79 = { ["__proto__"]: firstComputedProto79, __proto__: protoList79, ["__proto__"]: secondComputedProto79, value79: 573 + 3 };
check(Object.getPrototypeOf(listObj79) === protoList79, "property name list literal proto 79");
check(listObj79.__proto__ === secondComputedProto79, "property name list computed last wins 79");
check(listObj79.inheritedList === 573, "property name list inherited 79");
check(listObj79.value79 === 573 + 3, "property name list value 79");
var keyName79 = "__proto__";
var computedOnlyObj79 = { [keyName79]: firstComputedProto79, [keyName79]: secondComputedProto79 };
check(Object.getPrototypeOf(computedOnlyObj79) === Object.prototype, "computed only proto base 79");
check(computedOnlyObj79.__proto__ === secondComputedProto79, "computed only proto own 79");

var protoList80 = { inheritedList: 580 };
var firstComputedProto80 = { data: 580 + 1 };
var secondComputedProto80 = { data: 580 + 2 };
var listObj80 = { ["__proto__"]: firstComputedProto80, __proto__: protoList80, ["__proto__"]: secondComputedProto80, value80: 580 + 3 };
check(Object.getPrototypeOf(listObj80) === protoList80, "property name list literal proto 80");
check(listObj80.__proto__ === secondComputedProto80, "property name list computed last wins 80");
check(listObj80.inheritedList === 580, "property name list inherited 80");
check(listObj80.value80 === 580 + 3, "property name list value 80");
var keyName80 = "__proto__";
var computedOnlyObj80 = { [keyName80]: firstComputedProto80, [keyName80]: secondComputedProto80 };
check(Object.getPrototypeOf(computedOnlyObj80) === Object.prototype, "computed only proto base 80");
check(computedOnlyObj80.__proto__ === secondComputedProto80, "computed only proto own 80");

var protoList81 = { inheritedList: 587 };
var firstComputedProto81 = { data: 587 + 1 };
var secondComputedProto81 = { data: 587 + 2 };
var listObj81 = { ["__proto__"]: firstComputedProto81, __proto__: protoList81, ["__proto__"]: secondComputedProto81, value81: 587 + 3 };
check(Object.getPrototypeOf(listObj81) === protoList81, "property name list literal proto 81");
check(listObj81.__proto__ === secondComputedProto81, "property name list computed last wins 81");
check(listObj81.inheritedList === 587, "property name list inherited 81");
check(listObj81.value81 === 587 + 3, "property name list value 81");
var keyName81 = "__proto__";
var computedOnlyObj81 = { [keyName81]: firstComputedProto81, [keyName81]: secondComputedProto81 };
check(Object.getPrototypeOf(computedOnlyObj81) === Object.prototype, "computed only proto base 81");
check(computedOnlyObj81.__proto__ === secondComputedProto81, "computed only proto own 81");

var protoList82 = { inheritedList: 594 };
var firstComputedProto82 = { data: 594 + 1 };
var secondComputedProto82 = { data: 594 + 2 };
var listObj82 = { ["__proto__"]: firstComputedProto82, __proto__: protoList82, ["__proto__"]: secondComputedProto82, value82: 594 + 3 };
check(Object.getPrototypeOf(listObj82) === protoList82, "property name list literal proto 82");
check(listObj82.__proto__ === secondComputedProto82, "property name list computed last wins 82");
check(listObj82.inheritedList === 594, "property name list inherited 82");
check(listObj82.value82 === 594 + 3, "property name list value 82");
var keyName82 = "__proto__";
var computedOnlyObj82 = { [keyName82]: firstComputedProto82, [keyName82]: secondComputedProto82 };
check(Object.getPrototypeOf(computedOnlyObj82) === Object.prototype, "computed only proto base 82");
check(computedOnlyObj82.__proto__ === secondComputedProto82, "computed only proto own 82");

var protoList83 = { inheritedList: 601 };
var firstComputedProto83 = { data: 601 + 1 };
var secondComputedProto83 = { data: 601 + 2 };
var listObj83 = { ["__proto__"]: firstComputedProto83, __proto__: protoList83, ["__proto__"]: secondComputedProto83, value83: 601 + 3 };
check(Object.getPrototypeOf(listObj83) === protoList83, "property name list literal proto 83");
check(listObj83.__proto__ === secondComputedProto83, "property name list computed last wins 83");
check(listObj83.inheritedList === 601, "property name list inherited 83");
check(listObj83.value83 === 601 + 3, "property name list value 83");
var keyName83 = "__proto__";
var computedOnlyObj83 = { [keyName83]: firstComputedProto83, [keyName83]: secondComputedProto83 };
check(Object.getPrototypeOf(computedOnlyObj83) === Object.prototype, "computed only proto base 83");
check(computedOnlyObj83.__proto__ === secondComputedProto83, "computed only proto own 83");

var protoList84 = { inheritedList: 608 };
var firstComputedProto84 = { data: 608 + 1 };
var secondComputedProto84 = { data: 608 + 2 };
var listObj84 = { ["__proto__"]: firstComputedProto84, __proto__: protoList84, ["__proto__"]: secondComputedProto84, value84: 608 + 3 };
check(Object.getPrototypeOf(listObj84) === protoList84, "property name list literal proto 84");
check(listObj84.__proto__ === secondComputedProto84, "property name list computed last wins 84");
check(listObj84.inheritedList === 608, "property name list inherited 84");
check(listObj84.value84 === 608 + 3, "property name list value 84");
var keyName84 = "__proto__";
var computedOnlyObj84 = { [keyName84]: firstComputedProto84, [keyName84]: secondComputedProto84 };
check(Object.getPrototypeOf(computedOnlyObj84) === Object.prototype, "computed only proto base 84");
check(computedOnlyObj84.__proto__ === secondComputedProto84, "computed only proto own 84");

var protoList85 = { inheritedList: 615 };
var firstComputedProto85 = { data: 615 + 1 };
var secondComputedProto85 = { data: 615 + 2 };
var listObj85 = { ["__proto__"]: firstComputedProto85, __proto__: protoList85, ["__proto__"]: secondComputedProto85, value85: 615 + 3 };
check(Object.getPrototypeOf(listObj85) === protoList85, "property name list literal proto 85");
check(listObj85.__proto__ === secondComputedProto85, "property name list computed last wins 85");
check(listObj85.inheritedList === 615, "property name list inherited 85");
check(listObj85.value85 === 615 + 3, "property name list value 85");
var keyName85 = "__proto__";
var computedOnlyObj85 = { [keyName85]: firstComputedProto85, [keyName85]: secondComputedProto85 };
check(Object.getPrototypeOf(computedOnlyObj85) === Object.prototype, "computed only proto base 85");
check(computedOnlyObj85.__proto__ === secondComputedProto85, "computed only proto own 85");

var protoList86 = { inheritedList: 622 };
var firstComputedProto86 = { data: 622 + 1 };
var secondComputedProto86 = { data: 622 + 2 };
var listObj86 = { ["__proto__"]: firstComputedProto86, __proto__: protoList86, ["__proto__"]: secondComputedProto86, value86: 622 + 3 };
check(Object.getPrototypeOf(listObj86) === protoList86, "property name list literal proto 86");
check(listObj86.__proto__ === secondComputedProto86, "property name list computed last wins 86");
check(listObj86.inheritedList === 622, "property name list inherited 86");
check(listObj86.value86 === 622 + 3, "property name list value 86");
var keyName86 = "__proto__";
var computedOnlyObj86 = { [keyName86]: firstComputedProto86, [keyName86]: secondComputedProto86 };
check(Object.getPrototypeOf(computedOnlyObj86) === Object.prototype, "computed only proto base 86");
check(computedOnlyObj86.__proto__ === secondComputedProto86, "computed only proto own 86");

var protoList87 = { inheritedList: 629 };
var firstComputedProto87 = { data: 629 + 1 };
var secondComputedProto87 = { data: 629 + 2 };
var listObj87 = { ["__proto__"]: firstComputedProto87, __proto__: protoList87, ["__proto__"]: secondComputedProto87, value87: 629 + 3 };
check(Object.getPrototypeOf(listObj87) === protoList87, "property name list literal proto 87");
check(listObj87.__proto__ === secondComputedProto87, "property name list computed last wins 87");
check(listObj87.inheritedList === 629, "property name list inherited 87");
check(listObj87.value87 === 629 + 3, "property name list value 87");
var keyName87 = "__proto__";
var computedOnlyObj87 = { [keyName87]: firstComputedProto87, [keyName87]: secondComputedProto87 };
check(Object.getPrototypeOf(computedOnlyObj87) === Object.prototype, "computed only proto base 87");
check(computedOnlyObj87.__proto__ === secondComputedProto87, "computed only proto own 87");

var protoList88 = { inheritedList: 636 };
var firstComputedProto88 = { data: 636 + 1 };
var secondComputedProto88 = { data: 636 + 2 };
var listObj88 = { ["__proto__"]: firstComputedProto88, __proto__: protoList88, ["__proto__"]: secondComputedProto88, value88: 636 + 3 };
check(Object.getPrototypeOf(listObj88) === protoList88, "property name list literal proto 88");
check(listObj88.__proto__ === secondComputedProto88, "property name list computed last wins 88");
check(listObj88.inheritedList === 636, "property name list inherited 88");
check(listObj88.value88 === 636 + 3, "property name list value 88");
var keyName88 = "__proto__";
var computedOnlyObj88 = { [keyName88]: firstComputedProto88, [keyName88]: secondComputedProto88 };
check(Object.getPrototypeOf(computedOnlyObj88) === Object.prototype, "computed only proto base 88");
check(computedOnlyObj88.__proto__ === secondComputedProto88, "computed only proto own 88");

var protoList89 = { inheritedList: 643 };
var firstComputedProto89 = { data: 643 + 1 };
var secondComputedProto89 = { data: 643 + 2 };
var listObj89 = { ["__proto__"]: firstComputedProto89, __proto__: protoList89, ["__proto__"]: secondComputedProto89, value89: 643 + 3 };
check(Object.getPrototypeOf(listObj89) === protoList89, "property name list literal proto 89");
check(listObj89.__proto__ === secondComputedProto89, "property name list computed last wins 89");
check(listObj89.inheritedList === 643, "property name list inherited 89");
check(listObj89.value89 === 643 + 3, "property name list value 89");
var keyName89 = "__proto__";
var computedOnlyObj89 = { [keyName89]: firstComputedProto89, [keyName89]: secondComputedProto89 };
check(Object.getPrototypeOf(computedOnlyObj89) === Object.prototype, "computed only proto base 89");
check(computedOnlyObj89.__proto__ === secondComputedProto89, "computed only proto own 89");

check(score > 0, "property name list score");
