// behavior: elisions-advance-index-with-holes
// expected: pass
// goal: script
// size: large
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}
var leadingElision0 = [,,11];
check(leadingElision0.length === 3, 'leading elision length 0');
check(!(0 in leadingElision0) && !(1 in leadingElision0), 'leading elision holes 0');
check((2 in leadingElision0) && leadingElision0[2] === 11, 'leading elision value 0');
var middleElision0 = [11,,12,,];
check(middleElision0.length === 4, 'middle elision length 0');
check((0 in middleElision0) && !(1 in middleElision0) && (2 in middleElision0) && !(3 in middleElision0), 'middle elision properties 0');
check(middleElision0[0] === 11 && middleElision0[2] === 12, 'middle elision values 0');
var onlyElision0 = [,,,];
check(onlyElision0.length === 3, 'only elision length 0');
check(!(0 in onlyElision0) && !(1 in onlyElision0) && !(2 in onlyElision0), 'only elision holes 0');
var leadingElision1 = [,,12];
check(leadingElision1.length === 3, 'leading elision length 1');
check(!(0 in leadingElision1) && !(1 in leadingElision1), 'leading elision holes 1');
check((2 in leadingElision1) && leadingElision1[2] === 12, 'leading elision value 1');
var middleElision1 = [12,,13,,];
check(middleElision1.length === 4, 'middle elision length 1');
check((0 in middleElision1) && !(1 in middleElision1) && (2 in middleElision1) && !(3 in middleElision1), 'middle elision properties 1');
check(middleElision1[0] === 12 && middleElision1[2] === 13, 'middle elision values 1');
var onlyElision1 = [,,,];
check(onlyElision1.length === 3, 'only elision length 1');
check(!(0 in onlyElision1) && !(1 in onlyElision1) && !(2 in onlyElision1), 'only elision holes 1');
var leadingElision2 = [,,13];
check(leadingElision2.length === 3, 'leading elision length 2');
check(!(0 in leadingElision2) && !(1 in leadingElision2), 'leading elision holes 2');
check((2 in leadingElision2) && leadingElision2[2] === 13, 'leading elision value 2');
var middleElision2 = [13,,14,,];
check(middleElision2.length === 4, 'middle elision length 2');
check((0 in middleElision2) && !(1 in middleElision2) && (2 in middleElision2) && !(3 in middleElision2), 'middle elision properties 2');
check(middleElision2[0] === 13 && middleElision2[2] === 14, 'middle elision values 2');
var onlyElision2 = [,,,];
check(onlyElision2.length === 3, 'only elision length 2');
check(!(0 in onlyElision2) && !(1 in onlyElision2) && !(2 in onlyElision2), 'only elision holes 2');
var leadingElision3 = [,,14];
check(leadingElision3.length === 3, 'leading elision length 3');
check(!(0 in leadingElision3) && !(1 in leadingElision3), 'leading elision holes 3');
check((2 in leadingElision3) && leadingElision3[2] === 14, 'leading elision value 3');
var middleElision3 = [14,,15,,];
check(middleElision3.length === 4, 'middle elision length 3');
check((0 in middleElision3) && !(1 in middleElision3) && (2 in middleElision3) && !(3 in middleElision3), 'middle elision properties 3');
check(middleElision3[0] === 14 && middleElision3[2] === 15, 'middle elision values 3');
var onlyElision3 = [,,,];
check(onlyElision3.length === 3, 'only elision length 3');
check(!(0 in onlyElision3) && !(1 in onlyElision3) && !(2 in onlyElision3), 'only elision holes 3');
var leadingElision4 = [,,15];
check(leadingElision4.length === 3, 'leading elision length 4');
check(!(0 in leadingElision4) && !(1 in leadingElision4), 'leading elision holes 4');
check((2 in leadingElision4) && leadingElision4[2] === 15, 'leading elision value 4');
var middleElision4 = [15,,16,,];
check(middleElision4.length === 4, 'middle elision length 4');
check((0 in middleElision4) && !(1 in middleElision4) && (2 in middleElision4) && !(3 in middleElision4), 'middle elision properties 4');
check(middleElision4[0] === 15 && middleElision4[2] === 16, 'middle elision values 4');
var onlyElision4 = [,,,];
check(onlyElision4.length === 3, 'only elision length 4');
check(!(0 in onlyElision4) && !(1 in onlyElision4) && !(2 in onlyElision4), 'only elision holes 4');
var leadingElision5 = [,,16];
check(leadingElision5.length === 3, 'leading elision length 5');
check(!(0 in leadingElision5) && !(1 in leadingElision5), 'leading elision holes 5');
check((2 in leadingElision5) && leadingElision5[2] === 16, 'leading elision value 5');
var middleElision5 = [16,,17,,];
check(middleElision5.length === 4, 'middle elision length 5');
check((0 in middleElision5) && !(1 in middleElision5) && (2 in middleElision5) && !(3 in middleElision5), 'middle elision properties 5');
check(middleElision5[0] === 16 && middleElision5[2] === 17, 'middle elision values 5');
var onlyElision5 = [,,,];
check(onlyElision5.length === 3, 'only elision length 5');
check(!(0 in onlyElision5) && !(1 in onlyElision5) && !(2 in onlyElision5), 'only elision holes 5');
var leadingElision6 = [,,17];
check(leadingElision6.length === 3, 'leading elision length 6');
check(!(0 in leadingElision6) && !(1 in leadingElision6), 'leading elision holes 6');
check((2 in leadingElision6) && leadingElision6[2] === 17, 'leading elision value 6');
var middleElision6 = [17,,18,,];
check(middleElision6.length === 4, 'middle elision length 6');
check((0 in middleElision6) && !(1 in middleElision6) && (2 in middleElision6) && !(3 in middleElision6), 'middle elision properties 6');
check(middleElision6[0] === 17 && middleElision6[2] === 18, 'middle elision values 6');
var onlyElision6 = [,,,];
check(onlyElision6.length === 3, 'only elision length 6');
check(!(0 in onlyElision6) && !(1 in onlyElision6) && !(2 in onlyElision6), 'only elision holes 6');
var leadingElision7 = [,,18];
check(leadingElision7.length === 3, 'leading elision length 7');
check(!(0 in leadingElision7) && !(1 in leadingElision7), 'leading elision holes 7');
check((2 in leadingElision7) && leadingElision7[2] === 18, 'leading elision value 7');
var middleElision7 = [18,,19,,];
check(middleElision7.length === 4, 'middle elision length 7');
check((0 in middleElision7) && !(1 in middleElision7) && (2 in middleElision7) && !(3 in middleElision7), 'middle elision properties 7');
check(middleElision7[0] === 18 && middleElision7[2] === 19, 'middle elision values 7');
var onlyElision7 = [,,,];
check(onlyElision7.length === 3, 'only elision length 7');
check(!(0 in onlyElision7) && !(1 in onlyElision7) && !(2 in onlyElision7), 'only elision holes 7');
var leadingElision8 = [,,19];
check(leadingElision8.length === 3, 'leading elision length 8');
check(!(0 in leadingElision8) && !(1 in leadingElision8), 'leading elision holes 8');
check((2 in leadingElision8) && leadingElision8[2] === 19, 'leading elision value 8');
var middleElision8 = [19,,20,,];
check(middleElision8.length === 4, 'middle elision length 8');
check((0 in middleElision8) && !(1 in middleElision8) && (2 in middleElision8) && !(3 in middleElision8), 'middle elision properties 8');
check(middleElision8[0] === 19 && middleElision8[2] === 20, 'middle elision values 8');
var onlyElision8 = [,,,];
check(onlyElision8.length === 3, 'only elision length 8');
check(!(0 in onlyElision8) && !(1 in onlyElision8) && !(2 in onlyElision8), 'only elision holes 8');
var leadingElision9 = [,,20];
check(leadingElision9.length === 3, 'leading elision length 9');
check(!(0 in leadingElision9) && !(1 in leadingElision9), 'leading elision holes 9');
check((2 in leadingElision9) && leadingElision9[2] === 20, 'leading elision value 9');
var middleElision9 = [20,,21,,];
check(middleElision9.length === 4, 'middle elision length 9');
check((0 in middleElision9) && !(1 in middleElision9) && (2 in middleElision9) && !(3 in middleElision9), 'middle elision properties 9');
check(middleElision9[0] === 20 && middleElision9[2] === 21, 'middle elision values 9');
var onlyElision9 = [,,,];
check(onlyElision9.length === 3, 'only elision length 9');
check(!(0 in onlyElision9) && !(1 in onlyElision9) && !(2 in onlyElision9), 'only elision holes 9');
var leadingElision10 = [,,21];
check(leadingElision10.length === 3, 'leading elision length 10');
check(!(0 in leadingElision10) && !(1 in leadingElision10), 'leading elision holes 10');
check((2 in leadingElision10) && leadingElision10[2] === 21, 'leading elision value 10');
var middleElision10 = [21,,22,,];
check(middleElision10.length === 4, 'middle elision length 10');
check((0 in middleElision10) && !(1 in middleElision10) && (2 in middleElision10) && !(3 in middleElision10), 'middle elision properties 10');
check(middleElision10[0] === 21 && middleElision10[2] === 22, 'middle elision values 10');
var onlyElision10 = [,,,];
check(onlyElision10.length === 3, 'only elision length 10');
check(!(0 in onlyElision10) && !(1 in onlyElision10) && !(2 in onlyElision10), 'only elision holes 10');
var leadingElision11 = [,,22];
check(leadingElision11.length === 3, 'leading elision length 11');
check(!(0 in leadingElision11) && !(1 in leadingElision11), 'leading elision holes 11');
check((2 in leadingElision11) && leadingElision11[2] === 22, 'leading elision value 11');
var middleElision11 = [22,,23,,];
check(middleElision11.length === 4, 'middle elision length 11');
check((0 in middleElision11) && !(1 in middleElision11) && (2 in middleElision11) && !(3 in middleElision11), 'middle elision properties 11');
check(middleElision11[0] === 22 && middleElision11[2] === 23, 'middle elision values 11');
var onlyElision11 = [,,,];
check(onlyElision11.length === 3, 'only elision length 11');
check(!(0 in onlyElision11) && !(1 in onlyElision11) && !(2 in onlyElision11), 'only elision holes 11');
var leadingElision12 = [,,23];
check(leadingElision12.length === 3, 'leading elision length 12');
check(!(0 in leadingElision12) && !(1 in leadingElision12), 'leading elision holes 12');
check((2 in leadingElision12) && leadingElision12[2] === 23, 'leading elision value 12');
var middleElision12 = [23,,24,,];
check(middleElision12.length === 4, 'middle elision length 12');
check((0 in middleElision12) && !(1 in middleElision12) && (2 in middleElision12) && !(3 in middleElision12), 'middle elision properties 12');
check(middleElision12[0] === 23 && middleElision12[2] === 24, 'middle elision values 12');
var onlyElision12 = [,,,];
check(onlyElision12.length === 3, 'only elision length 12');
check(!(0 in onlyElision12) && !(1 in onlyElision12) && !(2 in onlyElision12), 'only elision holes 12');
var leadingElision13 = [,,24];
check(leadingElision13.length === 3, 'leading elision length 13');
check(!(0 in leadingElision13) && !(1 in leadingElision13), 'leading elision holes 13');
check((2 in leadingElision13) && leadingElision13[2] === 24, 'leading elision value 13');
var middleElision13 = [24,,25,,];
check(middleElision13.length === 4, 'middle elision length 13');
check((0 in middleElision13) && !(1 in middleElision13) && (2 in middleElision13) && !(3 in middleElision13), 'middle elision properties 13');
check(middleElision13[0] === 24 && middleElision13[2] === 25, 'middle elision values 13');
var onlyElision13 = [,,,];
check(onlyElision13.length === 3, 'only elision length 13');
check(!(0 in onlyElision13) && !(1 in onlyElision13) && !(2 in onlyElision13), 'only elision holes 13');
var leadingElision14 = [,,25];
check(leadingElision14.length === 3, 'leading elision length 14');
check(!(0 in leadingElision14) && !(1 in leadingElision14), 'leading elision holes 14');
check((2 in leadingElision14) && leadingElision14[2] === 25, 'leading elision value 14');
var middleElision14 = [25,,26,,];
check(middleElision14.length === 4, 'middle elision length 14');
check((0 in middleElision14) && !(1 in middleElision14) && (2 in middleElision14) && !(3 in middleElision14), 'middle elision properties 14');
check(middleElision14[0] === 25 && middleElision14[2] === 26, 'middle elision values 14');
var onlyElision14 = [,,,];
check(onlyElision14.length === 3, 'only elision length 14');
check(!(0 in onlyElision14) && !(1 in onlyElision14) && !(2 in onlyElision14), 'only elision holes 14');
var leadingElision15 = [,,26];
check(leadingElision15.length === 3, 'leading elision length 15');
check(!(0 in leadingElision15) && !(1 in leadingElision15), 'leading elision holes 15');
check((2 in leadingElision15) && leadingElision15[2] === 26, 'leading elision value 15');
var middleElision15 = [26,,27,,];
check(middleElision15.length === 4, 'middle elision length 15');
check((0 in middleElision15) && !(1 in middleElision15) && (2 in middleElision15) && !(3 in middleElision15), 'middle elision properties 15');
check(middleElision15[0] === 26 && middleElision15[2] === 27, 'middle elision values 15');
var onlyElision15 = [,,,];
check(onlyElision15.length === 3, 'only elision length 15');
check(!(0 in onlyElision15) && !(1 in onlyElision15) && !(2 in onlyElision15), 'only elision holes 15');
var leadingElision16 = [,,27];
check(leadingElision16.length === 3, 'leading elision length 16');
check(!(0 in leadingElision16) && !(1 in leadingElision16), 'leading elision holes 16');
check((2 in leadingElision16) && leadingElision16[2] === 27, 'leading elision value 16');
var middleElision16 = [27,,28,,];
check(middleElision16.length === 4, 'middle elision length 16');
check((0 in middleElision16) && !(1 in middleElision16) && (2 in middleElision16) && !(3 in middleElision16), 'middle elision properties 16');
check(middleElision16[0] === 27 && middleElision16[2] === 28, 'middle elision values 16');
var onlyElision16 = [,,,];
check(onlyElision16.length === 3, 'only elision length 16');
check(!(0 in onlyElision16) && !(1 in onlyElision16) && !(2 in onlyElision16), 'only elision holes 16');
var leadingElision17 = [,,28];
check(leadingElision17.length === 3, 'leading elision length 17');
check(!(0 in leadingElision17) && !(1 in leadingElision17), 'leading elision holes 17');
check((2 in leadingElision17) && leadingElision17[2] === 28, 'leading elision value 17');
var middleElision17 = [28,,29,,];
check(middleElision17.length === 4, 'middle elision length 17');
check((0 in middleElision17) && !(1 in middleElision17) && (2 in middleElision17) && !(3 in middleElision17), 'middle elision properties 17');
check(middleElision17[0] === 28 && middleElision17[2] === 29, 'middle elision values 17');
var onlyElision17 = [,,,];
check(onlyElision17.length === 3, 'only elision length 17');
check(!(0 in onlyElision17) && !(1 in onlyElision17) && !(2 in onlyElision17), 'only elision holes 17');
var leadingElision18 = [,,29];
check(leadingElision18.length === 3, 'leading elision length 18');
check(!(0 in leadingElision18) && !(1 in leadingElision18), 'leading elision holes 18');
check((2 in leadingElision18) && leadingElision18[2] === 29, 'leading elision value 18');
var middleElision18 = [29,,30,,];
check(middleElision18.length === 4, 'middle elision length 18');
check((0 in middleElision18) && !(1 in middleElision18) && (2 in middleElision18) && !(3 in middleElision18), 'middle elision properties 18');
check(middleElision18[0] === 29 && middleElision18[2] === 30, 'middle elision values 18');
var onlyElision18 = [,,,];
check(onlyElision18.length === 3, 'only elision length 18');
check(!(0 in onlyElision18) && !(1 in onlyElision18) && !(2 in onlyElision18), 'only elision holes 18');
var leadingElision19 = [,,30];
check(leadingElision19.length === 3, 'leading elision length 19');
check(!(0 in leadingElision19) && !(1 in leadingElision19), 'leading elision holes 19');
check((2 in leadingElision19) && leadingElision19[2] === 30, 'leading elision value 19');
var middleElision19 = [30,,31,,];
check(middleElision19.length === 4, 'middle elision length 19');
check((0 in middleElision19) && !(1 in middleElision19) && (2 in middleElision19) && !(3 in middleElision19), 'middle elision properties 19');
check(middleElision19[0] === 30 && middleElision19[2] === 31, 'middle elision values 19');
var onlyElision19 = [,,,];
check(onlyElision19.length === 3, 'only elision length 19');
check(!(0 in onlyElision19) && !(1 in onlyElision19) && !(2 in onlyElision19), 'only elision holes 19');
var leadingElision20 = [,,31];
check(leadingElision20.length === 3, 'leading elision length 20');
check(!(0 in leadingElision20) && !(1 in leadingElision20), 'leading elision holes 20');
check((2 in leadingElision20) && leadingElision20[2] === 31, 'leading elision value 20');
var middleElision20 = [31,,32,,];
check(middleElision20.length === 4, 'middle elision length 20');
check((0 in middleElision20) && !(1 in middleElision20) && (2 in middleElision20) && !(3 in middleElision20), 'middle elision properties 20');
check(middleElision20[0] === 31 && middleElision20[2] === 32, 'middle elision values 20');
var onlyElision20 = [,,,];
check(onlyElision20.length === 3, 'only elision length 20');
check(!(0 in onlyElision20) && !(1 in onlyElision20) && !(2 in onlyElision20), 'only elision holes 20');
var leadingElision21 = [,,32];
check(leadingElision21.length === 3, 'leading elision length 21');
check(!(0 in leadingElision21) && !(1 in leadingElision21), 'leading elision holes 21');
check((2 in leadingElision21) && leadingElision21[2] === 32, 'leading elision value 21');
var middleElision21 = [32,,33,,];
check(middleElision21.length === 4, 'middle elision length 21');
check((0 in middleElision21) && !(1 in middleElision21) && (2 in middleElision21) && !(3 in middleElision21), 'middle elision properties 21');
check(middleElision21[0] === 32 && middleElision21[2] === 33, 'middle elision values 21');
var onlyElision21 = [,,,];
check(onlyElision21.length === 3, 'only elision length 21');
check(!(0 in onlyElision21) && !(1 in onlyElision21) && !(2 in onlyElision21), 'only elision holes 21');
var leadingElision22 = [,,33];
check(leadingElision22.length === 3, 'leading elision length 22');
check(!(0 in leadingElision22) && !(1 in leadingElision22), 'leading elision holes 22');
check((2 in leadingElision22) && leadingElision22[2] === 33, 'leading elision value 22');
var middleElision22 = [33,,34,,];
check(middleElision22.length === 4, 'middle elision length 22');
check((0 in middleElision22) && !(1 in middleElision22) && (2 in middleElision22) && !(3 in middleElision22), 'middle elision properties 22');
check(middleElision22[0] === 33 && middleElision22[2] === 34, 'middle elision values 22');
var onlyElision22 = [,,,];
check(onlyElision22.length === 3, 'only elision length 22');
check(!(0 in onlyElision22) && !(1 in onlyElision22) && !(2 in onlyElision22), 'only elision holes 22');
var leadingElision23 = [,,34];
check(leadingElision23.length === 3, 'leading elision length 23');
check(!(0 in leadingElision23) && !(1 in leadingElision23), 'leading elision holes 23');
check((2 in leadingElision23) && leadingElision23[2] === 34, 'leading elision value 23');
var middleElision23 = [34,,35,,];
check(middleElision23.length === 4, 'middle elision length 23');
check((0 in middleElision23) && !(1 in middleElision23) && (2 in middleElision23) && !(3 in middleElision23), 'middle elision properties 23');
check(middleElision23[0] === 34 && middleElision23[2] === 35, 'middle elision values 23');
var onlyElision23 = [,,,];
check(onlyElision23.length === 3, 'only elision length 23');
check(!(0 in onlyElision23) && !(1 in onlyElision23) && !(2 in onlyElision23), 'only elision holes 23');
var leadingElision24 = [,,35];
check(leadingElision24.length === 3, 'leading elision length 24');
check(!(0 in leadingElision24) && !(1 in leadingElision24), 'leading elision holes 24');
check((2 in leadingElision24) && leadingElision24[2] === 35, 'leading elision value 24');
var middleElision24 = [35,,36,,];
check(middleElision24.length === 4, 'middle elision length 24');
check((0 in middleElision24) && !(1 in middleElision24) && (2 in middleElision24) && !(3 in middleElision24), 'middle elision properties 24');
check(middleElision24[0] === 35 && middleElision24[2] === 36, 'middle elision values 24');
var onlyElision24 = [,,,];
check(onlyElision24.length === 3, 'only elision length 24');
check(!(0 in onlyElision24) && !(1 in onlyElision24) && !(2 in onlyElision24), 'only elision holes 24');
var leadingElision25 = [,,36];
check(leadingElision25.length === 3, 'leading elision length 25');
check(!(0 in leadingElision25) && !(1 in leadingElision25), 'leading elision holes 25');
check((2 in leadingElision25) && leadingElision25[2] === 36, 'leading elision value 25');
var middleElision25 = [36,,37,,];
check(middleElision25.length === 4, 'middle elision length 25');
check((0 in middleElision25) && !(1 in middleElision25) && (2 in middleElision25) && !(3 in middleElision25), 'middle elision properties 25');
check(middleElision25[0] === 36 && middleElision25[2] === 37, 'middle elision values 25');
var onlyElision25 = [,,,];
check(onlyElision25.length === 3, 'only elision length 25');
check(!(0 in onlyElision25) && !(1 in onlyElision25) && !(2 in onlyElision25), 'only elision holes 25');
var leadingElision26 = [,,37];
check(leadingElision26.length === 3, 'leading elision length 26');
check(!(0 in leadingElision26) && !(1 in leadingElision26), 'leading elision holes 26');
check((2 in leadingElision26) && leadingElision26[2] === 37, 'leading elision value 26');
var middleElision26 = [37,,38,,];
check(middleElision26.length === 4, 'middle elision length 26');
check((0 in middleElision26) && !(1 in middleElision26) && (2 in middleElision26) && !(3 in middleElision26), 'middle elision properties 26');
check(middleElision26[0] === 37 && middleElision26[2] === 38, 'middle elision values 26');
var onlyElision26 = [,,,];
check(onlyElision26.length === 3, 'only elision length 26');
check(!(0 in onlyElision26) && !(1 in onlyElision26) && !(2 in onlyElision26), 'only elision holes 26');
var leadingElision27 = [,,38];
check(leadingElision27.length === 3, 'leading elision length 27');
check(!(0 in leadingElision27) && !(1 in leadingElision27), 'leading elision holes 27');
check((2 in leadingElision27) && leadingElision27[2] === 38, 'leading elision value 27');
var middleElision27 = [38,,39,,];
check(middleElision27.length === 4, 'middle elision length 27');
check((0 in middleElision27) && !(1 in middleElision27) && (2 in middleElision27) && !(3 in middleElision27), 'middle elision properties 27');
check(middleElision27[0] === 38 && middleElision27[2] === 39, 'middle elision values 27');
var onlyElision27 = [,,,];
check(onlyElision27.length === 3, 'only elision length 27');
check(!(0 in onlyElision27) && !(1 in onlyElision27) && !(2 in onlyElision27), 'only elision holes 27');
var leadingElision28 = [,,39];
check(leadingElision28.length === 3, 'leading elision length 28');
check(!(0 in leadingElision28) && !(1 in leadingElision28), 'leading elision holes 28');
check((2 in leadingElision28) && leadingElision28[2] === 39, 'leading elision value 28');
var middleElision28 = [39,,40,,];
check(middleElision28.length === 4, 'middle elision length 28');
check((0 in middleElision28) && !(1 in middleElision28) && (2 in middleElision28) && !(3 in middleElision28), 'middle elision properties 28');
check(middleElision28[0] === 39 && middleElision28[2] === 40, 'middle elision values 28');
var onlyElision28 = [,,,];
check(onlyElision28.length === 3, 'only elision length 28');
check(!(0 in onlyElision28) && !(1 in onlyElision28) && !(2 in onlyElision28), 'only elision holes 28');
var leadingElision29 = [,,40];
check(leadingElision29.length === 3, 'leading elision length 29');
check(!(0 in leadingElision29) && !(1 in leadingElision29), 'leading elision holes 29');
check((2 in leadingElision29) && leadingElision29[2] === 40, 'leading elision value 29');
var middleElision29 = [40,,41,,];
check(middleElision29.length === 4, 'middle elision length 29');
check((0 in middleElision29) && !(1 in middleElision29) && (2 in middleElision29) && !(3 in middleElision29), 'middle elision properties 29');
check(middleElision29[0] === 40 && middleElision29[2] === 41, 'middle elision values 29');
var onlyElision29 = [,,,];
check(onlyElision29.length === 3, 'only elision length 29');
check(!(0 in onlyElision29) && !(1 in onlyElision29) && !(2 in onlyElision29), 'only elision holes 29');
var leadingElision30 = [,,41];
check(leadingElision30.length === 3, 'leading elision length 30');
check(!(0 in leadingElision30) && !(1 in leadingElision30), 'leading elision holes 30');
check((2 in leadingElision30) && leadingElision30[2] === 41, 'leading elision value 30');
var middleElision30 = [41,,42,,];
check(middleElision30.length === 4, 'middle elision length 30');
check((0 in middleElision30) && !(1 in middleElision30) && (2 in middleElision30) && !(3 in middleElision30), 'middle elision properties 30');
check(middleElision30[0] === 41 && middleElision30[2] === 42, 'middle elision values 30');
var onlyElision30 = [,,,];
check(onlyElision30.length === 3, 'only elision length 30');
check(!(0 in onlyElision30) && !(1 in onlyElision30) && !(2 in onlyElision30), 'only elision holes 30');
var leadingElision31 = [,,42];
check(leadingElision31.length === 3, 'leading elision length 31');
check(!(0 in leadingElision31) && !(1 in leadingElision31), 'leading elision holes 31');
check((2 in leadingElision31) && leadingElision31[2] === 42, 'leading elision value 31');
var middleElision31 = [42,,43,,];
check(middleElision31.length === 4, 'middle elision length 31');
check((0 in middleElision31) && !(1 in middleElision31) && (2 in middleElision31) && !(3 in middleElision31), 'middle elision properties 31');
check(middleElision31[0] === 42 && middleElision31[2] === 43, 'middle elision values 31');
var onlyElision31 = [,,,];
check(onlyElision31.length === 3, 'only elision length 31');
check(!(0 in onlyElision31) && !(1 in onlyElision31) && !(2 in onlyElision31), 'only elision holes 31');
var leadingElision32 = [,,43];
check(leadingElision32.length === 3, 'leading elision length 32');
check(!(0 in leadingElision32) && !(1 in leadingElision32), 'leading elision holes 32');
check((2 in leadingElision32) && leadingElision32[2] === 43, 'leading elision value 32');
var middleElision32 = [43,,44,,];
check(middleElision32.length === 4, 'middle elision length 32');
check((0 in middleElision32) && !(1 in middleElision32) && (2 in middleElision32) && !(3 in middleElision32), 'middle elision properties 32');
check(middleElision32[0] === 43 && middleElision32[2] === 44, 'middle elision values 32');
var onlyElision32 = [,,,];
check(onlyElision32.length === 3, 'only elision length 32');
check(!(0 in onlyElision32) && !(1 in onlyElision32) && !(2 in onlyElision32), 'only elision holes 32');
var leadingElision33 = [,,44];
check(leadingElision33.length === 3, 'leading elision length 33');
check(!(0 in leadingElision33) && !(1 in leadingElision33), 'leading elision holes 33');
check((2 in leadingElision33) && leadingElision33[2] === 44, 'leading elision value 33');
var middleElision33 = [44,,45,,];
check(middleElision33.length === 4, 'middle elision length 33');
check((0 in middleElision33) && !(1 in middleElision33) && (2 in middleElision33) && !(3 in middleElision33), 'middle elision properties 33');
check(middleElision33[0] === 44 && middleElision33[2] === 45, 'middle elision values 33');
var onlyElision33 = [,,,];
check(onlyElision33.length === 3, 'only elision length 33');
check(!(0 in onlyElision33) && !(1 in onlyElision33) && !(2 in onlyElision33), 'only elision holes 33');
var leadingElision34 = [,,45];
check(leadingElision34.length === 3, 'leading elision length 34');
check(!(0 in leadingElision34) && !(1 in leadingElision34), 'leading elision holes 34');
check((2 in leadingElision34) && leadingElision34[2] === 45, 'leading elision value 34');
var middleElision34 = [45,,46,,];
check(middleElision34.length === 4, 'middle elision length 34');
check((0 in middleElision34) && !(1 in middleElision34) && (2 in middleElision34) && !(3 in middleElision34), 'middle elision properties 34');
check(middleElision34[0] === 45 && middleElision34[2] === 46, 'middle elision values 34');
var onlyElision34 = [,,,];
check(onlyElision34.length === 3, 'only elision length 34');
check(!(0 in onlyElision34) && !(1 in onlyElision34) && !(2 in onlyElision34), 'only elision holes 34');
var leadingElision35 = [,,46];
check(leadingElision35.length === 3, 'leading elision length 35');
check(!(0 in leadingElision35) && !(1 in leadingElision35), 'leading elision holes 35');
check((2 in leadingElision35) && leadingElision35[2] === 46, 'leading elision value 35');
var middleElision35 = [46,,47,,];
check(middleElision35.length === 4, 'middle elision length 35');
check((0 in middleElision35) && !(1 in middleElision35) && (2 in middleElision35) && !(3 in middleElision35), 'middle elision properties 35');
check(middleElision35[0] === 46 && middleElision35[2] === 47, 'middle elision values 35');
var onlyElision35 = [,,,];
check(onlyElision35.length === 3, 'only elision length 35');
check(!(0 in onlyElision35) && !(1 in onlyElision35) && !(2 in onlyElision35), 'only elision holes 35');
var leadingElision36 = [,,47];
check(leadingElision36.length === 3, 'leading elision length 36');
check(!(0 in leadingElision36) && !(1 in leadingElision36), 'leading elision holes 36');
check((2 in leadingElision36) && leadingElision36[2] === 47, 'leading elision value 36');
var middleElision36 = [47,,48,,];
check(middleElision36.length === 4, 'middle elision length 36');
check((0 in middleElision36) && !(1 in middleElision36) && (2 in middleElision36) && !(3 in middleElision36), 'middle elision properties 36');
check(middleElision36[0] === 47 && middleElision36[2] === 48, 'middle elision values 36');
var onlyElision36 = [,,,];
check(onlyElision36.length === 3, 'only elision length 36');
check(!(0 in onlyElision36) && !(1 in onlyElision36) && !(2 in onlyElision36), 'only elision holes 36');
var leadingElision37 = [,,48];
check(leadingElision37.length === 3, 'leading elision length 37');
check(!(0 in leadingElision37) && !(1 in leadingElision37), 'leading elision holes 37');
check((2 in leadingElision37) && leadingElision37[2] === 48, 'leading elision value 37');
var middleElision37 = [48,,49,,];
check(middleElision37.length === 4, 'middle elision length 37');
check((0 in middleElision37) && !(1 in middleElision37) && (2 in middleElision37) && !(3 in middleElision37), 'middle elision properties 37');
check(middleElision37[0] === 48 && middleElision37[2] === 49, 'middle elision values 37');
var onlyElision37 = [,,,];
check(onlyElision37.length === 3, 'only elision length 37');
check(!(0 in onlyElision37) && !(1 in onlyElision37) && !(2 in onlyElision37), 'only elision holes 37');
var leadingElision38 = [,,49];
check(leadingElision38.length === 3, 'leading elision length 38');
check(!(0 in leadingElision38) && !(1 in leadingElision38), 'leading elision holes 38');
check((2 in leadingElision38) && leadingElision38[2] === 49, 'leading elision value 38');
var middleElision38 = [49,,50,,];
check(middleElision38.length === 4, 'middle elision length 38');
check((0 in middleElision38) && !(1 in middleElision38) && (2 in middleElision38) && !(3 in middleElision38), 'middle elision properties 38');
check(middleElision38[0] === 49 && middleElision38[2] === 50, 'middle elision values 38');
var onlyElision38 = [,,,];
check(onlyElision38.length === 3, 'only elision length 38');
check(!(0 in onlyElision38) && !(1 in onlyElision38) && !(2 in onlyElision38), 'only elision holes 38');
var leadingElision39 = [,,50];
check(leadingElision39.length === 3, 'leading elision length 39');
check(!(0 in leadingElision39) && !(1 in leadingElision39), 'leading elision holes 39');
check((2 in leadingElision39) && leadingElision39[2] === 50, 'leading elision value 39');
var middleElision39 = [50,,51,,];
check(middleElision39.length === 4, 'middle elision length 39');
check((0 in middleElision39) && !(1 in middleElision39) && (2 in middleElision39) && !(3 in middleElision39), 'middle elision properties 39');
check(middleElision39[0] === 50 && middleElision39[2] === 51, 'middle elision values 39');
var onlyElision39 = [,,,];
check(onlyElision39.length === 3, 'only elision length 39');
check(!(0 in onlyElision39) && !(1 in onlyElision39) && !(2 in onlyElision39), 'only elision holes 39');
var leadingElision40 = [,,51];
check(leadingElision40.length === 3, 'leading elision length 40');
check(!(0 in leadingElision40) && !(1 in leadingElision40), 'leading elision holes 40');
check((2 in leadingElision40) && leadingElision40[2] === 51, 'leading elision value 40');
var middleElision40 = [51,,52,,];
check(middleElision40.length === 4, 'middle elision length 40');
check((0 in middleElision40) && !(1 in middleElision40) && (2 in middleElision40) && !(3 in middleElision40), 'middle elision properties 40');
check(middleElision40[0] === 51 && middleElision40[2] === 52, 'middle elision values 40');
var onlyElision40 = [,,,];
check(onlyElision40.length === 3, 'only elision length 40');
check(!(0 in onlyElision40) && !(1 in onlyElision40) && !(2 in onlyElision40), 'only elision holes 40');
var leadingElision41 = [,,52];
check(leadingElision41.length === 3, 'leading elision length 41');
check(!(0 in leadingElision41) && !(1 in leadingElision41), 'leading elision holes 41');
check((2 in leadingElision41) && leadingElision41[2] === 52, 'leading elision value 41');
var middleElision41 = [52,,53,,];
check(middleElision41.length === 4, 'middle elision length 41');
check((0 in middleElision41) && !(1 in middleElision41) && (2 in middleElision41) && !(3 in middleElision41), 'middle elision properties 41');
check(middleElision41[0] === 52 && middleElision41[2] === 53, 'middle elision values 41');
var onlyElision41 = [,,,];
check(onlyElision41.length === 3, 'only elision length 41');
check(!(0 in onlyElision41) && !(1 in onlyElision41) && !(2 in onlyElision41), 'only elision holes 41');
var leadingElision42 = [,,53];
check(leadingElision42.length === 3, 'leading elision length 42');
check(!(0 in leadingElision42) && !(1 in leadingElision42), 'leading elision holes 42');
check((2 in leadingElision42) && leadingElision42[2] === 53, 'leading elision value 42');
var middleElision42 = [53,,54,,];
check(middleElision42.length === 4, 'middle elision length 42');
check((0 in middleElision42) && !(1 in middleElision42) && (2 in middleElision42) && !(3 in middleElision42), 'middle elision properties 42');
check(middleElision42[0] === 53 && middleElision42[2] === 54, 'middle elision values 42');
var onlyElision42 = [,,,];
check(onlyElision42.length === 3, 'only elision length 42');
check(!(0 in onlyElision42) && !(1 in onlyElision42) && !(2 in onlyElision42), 'only elision holes 42');
var leadingElision43 = [,,54];
check(leadingElision43.length === 3, 'leading elision length 43');
check(!(0 in leadingElision43) && !(1 in leadingElision43), 'leading elision holes 43');
check((2 in leadingElision43) && leadingElision43[2] === 54, 'leading elision value 43');
var middleElision43 = [54,,55,,];
check(middleElision43.length === 4, 'middle elision length 43');
check((0 in middleElision43) && !(1 in middleElision43) && (2 in middleElision43) && !(3 in middleElision43), 'middle elision properties 43');
check(middleElision43[0] === 54 && middleElision43[2] === 55, 'middle elision values 43');
var onlyElision43 = [,,,];
check(onlyElision43.length === 3, 'only elision length 43');
check(!(0 in onlyElision43) && !(1 in onlyElision43) && !(2 in onlyElision43), 'only elision holes 43');
var leadingElision44 = [,,55];
check(leadingElision44.length === 3, 'leading elision length 44');
check(!(0 in leadingElision44) && !(1 in leadingElision44), 'leading elision holes 44');
check((2 in leadingElision44) && leadingElision44[2] === 55, 'leading elision value 44');
var middleElision44 = [55,,56,,];
check(middleElision44.length === 4, 'middle elision length 44');
check((0 in middleElision44) && !(1 in middleElision44) && (2 in middleElision44) && !(3 in middleElision44), 'middle elision properties 44');
check(middleElision44[0] === 55 && middleElision44[2] === 56, 'middle elision values 44');
var onlyElision44 = [,,,];
check(onlyElision44.length === 3, 'only elision length 44');
check(!(0 in onlyElision44) && !(1 in onlyElision44) && !(2 in onlyElision44), 'only elision holes 44');
var leadingElision45 = [,,56];
check(leadingElision45.length === 3, 'leading elision length 45');
check(!(0 in leadingElision45) && !(1 in leadingElision45), 'leading elision holes 45');
check((2 in leadingElision45) && leadingElision45[2] === 56, 'leading elision value 45');
var middleElision45 = [56,,57,,];
check(middleElision45.length === 4, 'middle elision length 45');
check((0 in middleElision45) && !(1 in middleElision45) && (2 in middleElision45) && !(3 in middleElision45), 'middle elision properties 45');
check(middleElision45[0] === 56 && middleElision45[2] === 57, 'middle elision values 45');
var onlyElision45 = [,,,];
check(onlyElision45.length === 3, 'only elision length 45');
check(!(0 in onlyElision45) && !(1 in onlyElision45) && !(2 in onlyElision45), 'only elision holes 45');
console.log('elisions-advance-index-with-holes large ' + score);
