// behavior: elisions-advance-index-with-holes
// expected: pass
// goal: script
// size: standard
// variant: script.sloppy

var score = 0;
function check(condition, label) {
if (!condition) {
throw label;
}
score = score + 1;
return true;
}
var leadingElision0 = [,,11];
check(leadingElision0.length === 3, 'leading elision length 0');
check(!(0 in leadingElision0) && !(1 in leadingElision0), 'leading elision holes 0');
check((2 in leadingElision0) && leadingElision0[2] === 11, 'leading elision value 0');
var middleElision0 = [11,,12,,];
check(middleElision0.length === 4, 'middle elision length 0');
check((0 in middleElision0) && !(1 in middleElision0) && (2 in middleElision0) && !(3 in middleElision0), 'middle elision properties 0');
check(middleElision0[0] === 11 && middleElision0[2] === 12, 'middle elision values 0');
var onlyElision0 = [,,,];
check(onlyElision0.length === 3, 'only elision length 0');
check(!(0 in onlyElision0) && !(1 in onlyElision0) && !(2 in onlyElision0), 'only elision holes 0');
var leadingElision1 = [,,12];
check(leadingElision1.length === 3, 'leading elision length 1');
check(!(0 in leadingElision1) && !(1 in leadingElision1), 'leading elision holes 1');
check((2 in leadingElision1) && leadingElision1[2] === 12, 'leading elision value 1');
var middleElision1 = [12,,13,,];
check(middleElision1.length === 4, 'middle elision length 1');
check((0 in middleElision1) && !(1 in middleElision1) && (2 in middleElision1) && !(3 in middleElision1), 'middle elision properties 1');
check(middleElision1[0] === 12 && middleElision1[2] === 13, 'middle elision values 1');
var onlyElision1 = [,,,];
check(onlyElision1.length === 3, 'only elision length 1');
check(!(0 in onlyElision1) && !(1 in onlyElision1) && !(2 in onlyElision1), 'only elision holes 1');
var leadingElision2 = [,,13];
check(leadingElision2.length === 3, 'leading elision length 2');
check(!(0 in leadingElision2) && !(1 in leadingElision2), 'leading elision holes 2');
check((2 in leadingElision2) && leadingElision2[2] === 13, 'leading elision value 2');
var middleElision2 = [13,,14,,];
check(middleElision2.length === 4, 'middle elision length 2');
check((0 in middleElision2) && !(1 in middleElision2) && (2 in middleElision2) && !(3 in middleElision2), 'middle elision properties 2');
check(middleElision2[0] === 13 && middleElision2[2] === 14, 'middle elision values 2');
var onlyElision2 = [,,,];
check(onlyElision2.length === 3, 'only elision length 2');
check(!(0 in onlyElision2) && !(1 in onlyElision2) && !(2 in onlyElision2), 'only elision holes 2');
var leadingElision3 = [,,14];
check(leadingElision3.length === 3, 'leading elision length 3');
check(!(0 in leadingElision3) && !(1 in leadingElision3), 'leading elision holes 3');
check((2 in leadingElision3) && leadingElision3[2] === 14, 'leading elision value 3');
var middleElision3 = [14,,15,,];
check(middleElision3.length === 4, 'middle elision length 3');
check((0 in middleElision3) && !(1 in middleElision3) && (2 in middleElision3) && !(3 in middleElision3), 'middle elision properties 3');
check(middleElision3[0] === 14 && middleElision3[2] === 15, 'middle elision values 3');
var onlyElision3 = [,,,];
check(onlyElision3.length === 3, 'only elision length 3');
check(!(0 in onlyElision3) && !(1 in onlyElision3) && !(2 in onlyElision3), 'only elision holes 3');
var leadingElision4 = [,,15];
check(leadingElision4.length === 3, 'leading elision length 4');
check(!(0 in leadingElision4) && !(1 in leadingElision4), 'leading elision holes 4');
check((2 in leadingElision4) && leadingElision4[2] === 15, 'leading elision value 4');
var middleElision4 = [15,,16,,];
check(middleElision4.length === 4, 'middle elision length 4');
check((0 in middleElision4) && !(1 in middleElision4) && (2 in middleElision4) && !(3 in middleElision4), 'middle elision properties 4');
check(middleElision4[0] === 15 && middleElision4[2] === 16, 'middle elision values 4');
var onlyElision4 = [,,,];
check(onlyElision4.length === 3, 'only elision length 4');
check(!(0 in onlyElision4) && !(1 in onlyElision4) && !(2 in onlyElision4), 'only elision holes 4');
var leadingElision5 = [,,16];
check(leadingElision5.length === 3, 'leading elision length 5');
check(!(0 in leadingElision5) && !(1 in leadingElision5), 'leading elision holes 5');
check((2 in leadingElision5) && leadingElision5[2] === 16, 'leading elision value 5');
var middleElision5 = [16,,17,,];
check(middleElision5.length === 4, 'middle elision length 5');
check((0 in middleElision5) && !(1 in middleElision5) && (2 in middleElision5) && !(3 in middleElision5), 'middle elision properties 5');
check(middleElision5[0] === 16 && middleElision5[2] === 17, 'middle elision values 5');
var onlyElision5 = [,,,];
check(onlyElision5.length === 3, 'only elision length 5');
check(!(0 in onlyElision5) && !(1 in onlyElision5) && !(2 in onlyElision5), 'only elision holes 5');
var leadingElision6 = [,,17];
check(leadingElision6.length === 3, 'leading elision length 6');
check(!(0 in leadingElision6) && !(1 in leadingElision6), 'leading elision holes 6');
check((2 in leadingElision6) && leadingElision6[2] === 17, 'leading elision value 6');
var middleElision6 = [17,,18,,];
check(middleElision6.length === 4, 'middle elision length 6');
check((0 in middleElision6) && !(1 in middleElision6) && (2 in middleElision6) && !(3 in middleElision6), 'middle elision properties 6');
check(middleElision6[0] === 17 && middleElision6[2] === 18, 'middle elision values 6');
var onlyElision6 = [,,,];
check(onlyElision6.length === 3, 'only elision length 6');
check(!(0 in onlyElision6) && !(1 in onlyElision6) && !(2 in onlyElision6), 'only elision holes 6');
var leadingElision7 = [,,18];
check(leadingElision7.length === 3, 'leading elision length 7');
check(!(0 in leadingElision7) && !(1 in leadingElision7), 'leading elision holes 7');
check((2 in leadingElision7) && leadingElision7[2] === 18, 'leading elision value 7');
var middleElision7 = [18,,19,,];
check(middleElision7.length === 4, 'middle elision length 7');
check((0 in middleElision7) && !(1 in middleElision7) && (2 in middleElision7) && !(3 in middleElision7), 'middle elision properties 7');
check(middleElision7[0] === 18 && middleElision7[2] === 19, 'middle elision values 7');
var onlyElision7 = [,,,];
check(onlyElision7.length === 3, 'only elision length 7');
check(!(0 in onlyElision7) && !(1 in onlyElision7) && !(2 in onlyElision7), 'only elision holes 7');
var leadingElision8 = [,,19];
check(leadingElision8.length === 3, 'leading elision length 8');
check(!(0 in leadingElision8) && !(1 in leadingElision8), 'leading elision holes 8');
check((2 in leadingElision8) && leadingElision8[2] === 19, 'leading elision value 8');
var middleElision8 = [19,,20,,];
check(middleElision8.length === 4, 'middle elision length 8');
check((0 in middleElision8) && !(1 in middleElision8) && (2 in middleElision8) && !(3 in middleElision8), 'middle elision properties 8');
check(middleElision8[0] === 19 && middleElision8[2] === 20, 'middle elision values 8');
var onlyElision8 = [,,,];
check(onlyElision8.length === 3, 'only elision length 8');
check(!(0 in onlyElision8) && !(1 in onlyElision8) && !(2 in onlyElision8), 'only elision holes 8');
var leadingElision9 = [,,20];
check(leadingElision9.length === 3, 'leading elision length 9');
check(!(0 in leadingElision9) && !(1 in leadingElision9), 'leading elision holes 9');
check((2 in leadingElision9) && leadingElision9[2] === 20, 'leading elision value 9');
var middleElision9 = [20,,21,,];
check(middleElision9.length === 4, 'middle elision length 9');
check((0 in middleElision9) && !(1 in middleElision9) && (2 in middleElision9) && !(3 in middleElision9), 'middle elision properties 9');
check(middleElision9[0] === 20 && middleElision9[2] === 21, 'middle elision values 9');
var onlyElision9 = [,,,];
check(onlyElision9.length === 3, 'only elision length 9');
check(!(0 in onlyElision9) && !(1 in onlyElision9) && !(2 in onlyElision9), 'only elision holes 9');
console.log('elisions-advance-index-with-holes standard ' + score);
